### ISSUE TITLE
Potential connection churn caused by DBConn.Kill()

### ISSUE THREAD

**Issue by wangmeng99** [vitessio/vitess#10059]
We currently use `KILL` to kill the running query per https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/connpool/dbconn.go#L363

Using KILL would cause the underlying Mysql connection to be closed, which means they need to recreated later on when the resource object is checked out. If there are many kills due to request cancellation, e.g. client just gives up after sending many requests, it could end up with a connection churn in the pool, i.e. Mysql connection is killed as a result of the cancellation but later on created to serve new request which in turn is cancelled. 

KILL QUERY just terminates the query while keeping the connection around, which could reduce the churn. The downside is that KILL QUERY was introduced in 5.7 so it will just break on older versions of Mysql.

**Comment by harshit-gangal** [comment]
This is feasible only for non-transaction queries. With transactional queries it will lead to more locks in the system causing other transactions to fail.
Also, on a context timeout/canceled, VTGates would not receive the response back from the VTGate and there is possibility of transaction not getting recorded by the VTGates. This would also lead to client not able to perform rollback on those transactions. 
Therefore this change is only possible with non-transactions.
