### ISSUE TITLE
Bug Report: Zookeeper unit tests are failing on Mac M1

### ISSUE THREAD

**Issue by rsajwani** [vitessio/vitess#10093]
### Overview of the Issue

Two Issues

Issue #1.  'Make Tools' is failing on Mac M1. The error is related to zookeeper

build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 6
    [javac] error: Source option 6 is no longer supported. Use 7 or later.
    [javac] error: Target option 6 is no longer supported. Use 7 or later.

BUILD FAILED
/Users/rameezsajwani/Code/fork/vitess/dist/vt-zookeeper-3.4.14/zookeeper-3.4.14/build.xml:321: Compile failed; see the compiler error output for details.

Issue #2 Zookeeper unit test cases are failing on local box. 

### Reproduction Steps

Run
make tools

Run
go test vitess.io/vitess/go/vt/topo/zk2topo

### Binary Version

```sh
Main
```

### Operating System and Environment details

```sh
Mac M1
```

**Comment by deepthi** [comment]
@rsajwani can this be closed? #10117 should have fixed this, correct?
