### ISSUE TITLE
Refactor aggregation function structs

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#10113]
Our parser outputs all aggregations functions using the general `sqlparser.FuncExpr`. This is a little clunky and requires us to do additional checks before we are sure that the aggregation we have is valid and what it is aggregating.

I suggest we instead introduce one struct type per aggregation, and have them all implement some interface. This would help clean up the code.

Example:

```golang
type (
	AggrFunc interface {
		iAggrFunc()
	}

	CountStar struct {}

	Count struct {
		Arg Expr
	}
        // and the rest
)
```

Tasks:
- [ ] Add AST structs
- [ ] Update the parser to use these structs
- [ ] Find and replace uses of the old representation and use the new structs instead

**Comment by skant7** [comment]
Hi @systay is there any chance to include this issue as one of the projects for summer 2022 lfx mentorship ?

**Comment by AllMight2099** [comment]
Hey @rsajwani, I'd like to work on this issue if that's alright with you

**Comment by GuptaManan100** [comment]
I think @rsajwani already started working on it and the associated PR is https://github.com/vitessio/vitess/pull/10347

**Comment by AllMight2099** [comment]
Oh okay. @GuptaManan100 Are there any good first issues that you'd recommend?

**Comment by GuptaManan100** [comment]
@AllMight2099 We have a `Good First Issue` label in Vitess. You can try filtering out issues with that, or you could pick up something for the list ☝️
