### ISSUE TITLE
Bug Report: ChangeTabletType is considered success without updating all the internal states

### ISSUE THREAD

**Issue by zhongr3n** [vitessio/vitess#10145]
#### Background
We did some manual operation on a shard to mitigate an unrelated issue, which unexpectedly broke the shard in such a way that any newly restored tablet will run into the following problem
```
Tablespace is missing for table `vt_<redacted>`.`_bfd62e12_a055_11ec_a8d6_022a23b59a1c_20220310093754_vrepl`. (errno 1812) (sqlstate HY000) during query: select * from _bfd62e12_a055_11ec_a8d6_022a23b59a1c_20220310093754_vrepl where 1 != 1
```
#### What happened?
We see the above error from the following ChangeTabletType code paths
https://github.com/vitessio/vitess/blob/40df731e82daa28cfa5b89024dca12c60958f9e1/go/vt/vttablet/tabletmanager/tm_state.go#L262
https://github.com/vitessio/vitess/blob/40df731e82daa28cfa5b89024dca12c60958f9e1/go/vt/vttablet/tabletmanager/tm_state.go#L300

Example log below (see more in the log fragments [here](https://gist.github.com/zhongr3n/d233711203846d42efe48b0c94f4faf0
))
```
[2022-03-28 16:57:25.392780] E0328 16:57:25.392079 3564410 tm_state.go:265] SetServingType(serving=false) failed: Tablespace is missing for table `vt_<redacted>`.`_bfd62e12_a055_11ec_a8d6_022a23b59a1c_20220310093754_vrepl`. (errno 1812) (sqlstate HY000) during query: select * from _bfd62e12_a055_11ec_a8d6_022a23b59a1c_20220310093754_vrepl where 1 != 1
```

However, the problem is that the error doesn't cause ChangeTabletType to fail. As a result, the newly restored tablet was never able to serve traffic, but successfully transitioned from SPARE to REPLICA and eventually PRIMARY. When it actually became PRIMARY, all queries against this shard failed with the following error
```
Failed FullyQualifiedShard: cluster:"fourxlarge" keyspace:"<redacted>" shard:"-80" rpc error: code = FailedPrecondition desc = target: <redacted>.-80.primary: vttablet: rpc error: code = FailedPrecondition desc = wrong tablet type: PRIMARY, want: REPLICA or []
```
Error code path https://github.com/vitessio/vitess/blob/40df731e82daa28cfa5b89024dca12c60958f9e1/go/vt/vttablet/tabletserver/state_manager.go#L396

#### Possible solution
Looking at the code, it seems like we swallow any error in `updateLocked` method, which is called at multiple places including ChangeTabletType
https://github.com/vitessio/vitess/blob/40df731e82daa28cfa5b89024dca12c60958f9e1/go/vt/vttablet/tabletmanager/tm_state.go#L246

I think ChangeTabletType should keep the invariant that all the internal states about the tablet type should be updated (ideally synchronously within the call) before returning a success response. Do you think that would make sense?

### Reproduction Steps

N/A

### Binary Version

```sh
N/A
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

https://gist.github.com/zhongr3n/d233711203846d42efe48b0c94f4faf0

**Comment by harshit-gangal** [comment]
@vitessio/cluster-management
