### ISSUE TITLE
Flaky vtgate_gen4 test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#10208]
### Overview of the Issue

`vtgate_gen4` is failing in approximately 1 out of every 10 CI runs.

### Reproduction Steps

See https://github.com/vitessio/vitess/actions/workflows/cluster_endtoend_vtgate_gen4.yml

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
CI
```

### Log Fragments

https://gist.github.com/deepthi/376b8b84b8d36ca1e67a84deae9381de

**Comment by GuptaManan100** [comment]
I don't think this is required anymore.
