### ISSUE TITLE
Explore Reducing Scope of Tablet Query Plan Cache

### ISSUE THREAD

**Issue by rbranson** [vitessio/vitess#10210]
### Feature Description

The tabletserver query plan cache will keep query plans around associated by their SQL statement string.

One of the functions of the query plan cache is that it can optionally cache field information. It appears that this is largely to improve the parsing performance of cached query plans because it allows parsing this information in the result packet. However, this is not safe in the face of schema changes, which can potentially catastrophically corrupt the results that are returned to the client in real world cases. Further, it doesn't appear to provide a major performance gain. Inspecting the code, the additional work is UTF-8 validation.

I put together a quick microbenchmark within the framework provided by `go/mysql/query_benchmark.go` of parsing a single-row result with 10 columns, each with 1-byte values, and the difference was around 6% (~750ns per result) for largely just parsing:

```cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz                                                                                                     
BenchmarkWantfieldsTrueOneRow-4           943192             12566 ns/op           1.59 MB/s
BenchmarkWantfieldsFalseOneRow-4          884964             11798 ns/op           1.70 MB/s                
```

The field cache itself adds meaningful complexity to the planning path and seems to already have some issues, such as where it holds a read lock during blocking I/O: https://github.com/vitessio/vitess/blob/8de235531d8af08dbe4f96ff6e63b24ad9de9481/go/vt/vttablet/tabletserver/query_engine.go#L328

There's probably reasonable justification for deprecating and removing the field cache given the correctness concerns and it's very marginal performance impact, which could pave the way to simplify the plan cache. So let's talk about the plan cache.

Calling the tabletservers planner a "planner" is really a bit of a misnomer, particularly compared to what's going on in vtgate. It's more of a "decorator."  To do its job, however, it does need to parse the SQL statement. I'm not entirely sure, but it does seem like that is likely the bulk of the work during the planning phase within the tabletserver. Parsing SQL is a pure function, so the same input SQL string will always produce the same result. The ideal caching scenario. I'd propose running some benchmarks where the planner is paired back to only caching the result of the SQL parsing and see if there's a meaningful difference. If not, it's probably worth saving the complexity and chance for introducing severe bugs on a very critical path.

### Use Case(s)

This covers all query execution within the tabletserver.

**Comment by rbranson** [comment]
The wantfields benchmark is here: https://github.com/rbranson/vitess/tree/benchmark-wantfields

**Comment by sougou** [comment]
The field cache was built in the early days to account for the fact that we were using cgo for the sql connection. Also, go was extremely inefficient those days.

I think removing the cache should greatly simplify this code, and should not have any noticeable performance impact.
