### ISSUE TITLE
Feature Request: Differentiate backfill data in VStream

### ISSUE THREAD

**Issue by 5antelope** [vitessio/vitess#10327]
### Feature Description

Right now, when we do a reshard, Vitess went through a copy-and-catch-up process, where we do a lot of bulk writes (a transaction with multiple rows) in the copy phase.

This is fine for the target shard to get all the data, however it does not play nicely with VStream end point. Because it will stream out a lot of transactions (VEvent) with abnormal pattern and also they are old data.

Since VStream is the recommended way to do CDC with Vitess, I think it makes sense to add a "non-materialized" field in VEvent to indicate the transaction is for backfill purpose (e.g., a `is_backfill` boolean filed), so that VTGate can choose to filter them out on the target shard. 

I'm not sure how feasible it is to get `is_backfill` information without materializing an extra column, a naive idea is to reference `_vt.vreplication` table and see if there is an ongoing backfill process. Would love to have your thoughts on this @deepthi @rohit-nayak-ps 

### Use Case(s)

All the use cases that using VStream for CDC purpose.

**Comment by rohit-nayak-ps** [comment]
VStream handles resharding natively if you are streaming from the entire keyspace. As part of `Reshard SwitchTraffic`, a `JournalEvent` is written to the source when the reshard cuts over. The JournalEvent contains the set of new shards and the corresponding VGTID of the last related source event associated with that target shard. 

When the `VStreamManager` at `VTGate` sees this event the default behaviour (based on the `VStreamFlags.StopOnReshard` flag) is to synchronize the streams: it waits for all source streams to reach this point, discards the `JournalEvent`, and creates new streams that stream from the target, starting at the GTID of the cutover. So there should not be duplication of CDC events.

If `VStreamFlags.StopOnReshard` is set, then the `JournalEvent` is sent as the last event from each of the source shards and streaming stops once all shards reach this point. The user is then expected to call the API again with the new VGTIDs sent for each of the new shards. This is useful if there is some action to be taken on the client, you are streaming from individual shards and not the entire keyspace.

Not sure if this addresses your requirement. If not, can you please expand further on your use case.

**Comment by y5w** [comment]
Thanks @rohit-nayak-ps - in our setup we have `StopOnReshard = true`.  I think having client to understand the semantic of `JournalEvent` works well if the CDC client is specific tailored for Vitess, but for other generic CDC solution (e.g., Debezim), it is a little bit leak of abstraction.

If we can have a `is_backfill` field to indicate if a VEvent is for backfill, then the CDC on reshard process can be simplified:
- provision new shards and enable CDC for the new shards
- filter out everything with `is_backfill = true` (either on VTGate or CDC client)

Do you think that's a reasonable alternative for `JournalEvent`?

**Comment by rohit-nayak-ps** [comment]
If you start streaming fresh from a new (reshard target) shard, some of the rows that are streamed as part of the copy phase might have been updated between the time the reshard completed (which is reported in the JournalEvent) and when you start the CDC. Vitess has no way to differentiate between these rows and those that have not changed.

**Comment by derekperkins** [comment]
> Since VStream is the recommended way to do CDC with Vitess

That's a good point about complexity, and I submitted a related feature request #10348

**Comment by mattlord** [comment]
We now have events in the stream which indicate that a copy phase is in progress, and then another when it's completed. Is there still any work to do here on this? I'm not sure what it would be. If not, then I will close this as done.

See: https://github.com/vitessio/vitess/pull/11740
