### ISSUE TITLE
Bug Report: transaction not rolled back after insert

### ISSUE THREAD

**Issue by tdryer** [vitessio/vitess#10398]
### Overview of the Issue

When executing the following queries on the same connection, I'm observing that the `UPDATE` is not rolled back by the transaction as expected, leaving the inserted row modified (`test=1`) instead of in its original state (`test=0`):

```sql
INSERT INTO test_table (test) VALUES (0);
BEGIN;
UPDATE test_table SET test=1;
ROLLBACK;
```

### Reproduction Steps

1. Start a `vttestserver` container:
```
docker run --detach --rm --name vitess --env KEYSPACES=test --env NUM_SHARDS=1 \
    --env PORT=30000 vitess/vttestserver:mysql57
```

2. Wait for the container to be ready:
```
until docker exec vitess mysqladmin ping --host 127.0.0.1 --port 30003 \
    --silent; do sleep 1 ; done
```

3. Execute the query sequence:
```
docker exec vitess mysql --host 127.0.0.1 --port 30003 test -e '
CREATE TABLE `test_table` (`test` bigint unsigned NOT NULL, PRIMARY KEY (`test`));
INSERT INTO test_table (test) VALUES (0);
BEGIN;
UPDATE test_table SET test=1;
ROLLBACK;
SELECT * FROM test_table;
'
```
4. Observe from the result of the final query that the transaction was not rolled back as expected:
```
test
1
```
5. Stop the container:
```
docker stop --time 1 vitess
```

### Binary Version

```sh
$ docker exec vitess vtcombo --version
Version: 14.0.0-SNAPSHOT (Git revision f5222ab0aaae0cba35fc42b0b60790beae0247dd branch 'main') built on Mon May 30 15:40:28 UTC 2022 by vitess@buildkitsandbox using go1.18.1 linux/amd64
```

### Operating System and Environment details

```sh
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -sr
Linux 5.13.0-41-generic
$ uname -m
x86_64
```

### Log Fragments

```sh
https://gist.github.com/tdryer/d4fa83031d255346e4eae3f2f7b15373
```

**Comment by harshit-gangal** [comment]
This seems to be only happening with vttestserver and not with the full vitess cluster i.e vtgate, vttablet, etc.

Also, only when a ddl is executed as the part of the query packet.
As it does not impact the production vitess setup, we will keep the severity to low for this issue.
