### ISSUE TITLE
Bug Report: Orchestrator doesn't work with latest vitess and operator version

### ISSUE THREAD

**Issue by resworld** [vitessio/vitess#10511]
### Overview of the Issue

I am following steps for running operator with orchestrator in latest (15) version of vitess and orchestrator can't discover new vitess cluster I've run. Scripts I've used are from https://github.com/vitessio/vitess/tree/main/examples/operator

### Reproduction Steps

1. Clone repo latest version: 
```sh
git clone https://github.com/vitessio/vitess.git
cd vitess && git log -1
```
Current commit hash I've tested it is:
```sh
commit 9f08615cb180aa3806d6a45eadeecf45455ab52b (HEAD -> main, origin/main, origin/HEAD)
Author: Manan Gupta <35839558+GuptaManan100@users.noreply.github.com>
Date:   Tue Jun 14 18:58:09 2022 +0530
```

2. Run minikube:
```sh
minikube start --cpus=8 --memory=11000 --disk-size=50g --kubernetes-version=v1.19.5
```

3. Run operator: 
```sh
kubectl apply -f operator.yaml
```

4. Start vitess cluster with vtorc example:
```sh
kubectl apply -f vtorc_example.yaml
```

5. Start forwarding script:
```sh
./orcpf.sh
```

6. Open http://localhost:3000 and check cluster status
```sh
No clusters found
```

### Binary Version

```sh
Image:         vitess/lite:latest
    Image ID:      docker-pullable://vitess/lite@sha256:89717535f987ceb87142be08a7cd9c029c3244fefd963aedee1979244cad8ec7
```

### Operating System and Environment details

```sh
running a minikube in macOS
```

### Log Fragments

```sh
I am attaching logs from vtorc container:


[martini] Started GET /web/clusters for 172.17.0.1:36540
[martini] Completed 200 OK in 1.496781ms
2022-06-15 06:45:08    DEBUG orchestrator.go:332] kv.SubmitPrimariesToKvStores, clusterName: , force: false: numPairs: 0
2022-06-15 06:45:08    DEBUG orchestrator.go:355] kv.SubmitPrimariesToKvStores: submitKvPairs: 0
2022-06-15 06:45:08     INFO audit_dao.go:105] auditType:review-unseen-instances instance::0 cluster: message:Operations: 0
2022-06-15 06:45:08     INFO audit_dao.go:105] auditType:resolve-unknown-primaries instance::0 cluster: message:Num resolved hostnames: 0
2022-06-15 06:45:08     INFO audit_dao.go:105] auditType:inject-unseen-primaries instance::0 cluster: message:Operations: 0
2022-06-15 06:45:08     INFO audit_dao.go:105] auditType:forget-unseen-differently-resolved instance::0 cluster: message:Forgotten instances: 0
2022-06-15 06:45:08     INFO audit_dao.go:105] auditType:forget-unseen instance::0 cluster: message:Forgotten instances: 0
[martini] Started GET /web/clusters for 172.17.0.1:36640
[martini] Completed 200 OK in 4.582535ms
```

**Comment by GuptaManan100** [comment]
@resworld It takes some time for a new VTOrc instance to initialise and read all the clusters information. The API endpoint `web/clusters` only reads from VTOrc's backend i.e., it only lists the clusters that VTOrc has discovered and doesn't make it discover anything new. Could you wait for 5-10 seconds and see if the clusters appear? Did they not appear at all even after waiting?

**Comment by resworld** [comment]
Yes I have wait even more, but still nothing. But if it's work on your side I can give it another try ?

**Comment by GuptaManan100** [comment]
@resworld I have found the issue why VTOrc wasn't showing any tablets. It was because of changes made to how durability policy is stored in the keyspace information. Until the durability policy is explicitly stored in the topo-server, by `SetKeyspaceDurabilityPolicy` of at the time of creating the keyspace, VTOrc will ignore those tablets.

I am going to patch the vitess operator to do this at the time of keyspace creation, but until then, you can get the example to work by running `vtctldclient --server=localhost:15999 SetKeyspaceDurabilityPolicy --durability-policy="none" commerce` and then restarting vtorc.

**Comment by GuptaManan100** [comment]
VTOrc restart should also not be required, but I found a bug in VTOrc while testing this https://github.com/vitessio/vitess/issues/10650

**Comment by GuptaManan100** [comment]
Bug #10650 has been fixed and the PR https://github.com/vitessio/vitess/pull/10687 updates the example to the latest version of the operator which takes care of running `SetKeyspaceDurabilityPolicy` for the user.
