### ISSUE TITLE
Bug Report:   Link Broken in docs

### ISSUE THREAD

**Issue by jeremy-donson** [vitessio/vitess#10539]
### Overview of the Issue

https://vitess.io/docs/15.0/reference/vtadmin/architecture/

The  "getting started" link on that page is broken and needs to be updated.

If you would show me where in repo all of those docs are ket, then that would be a help.  Thx!

 - jeremy donson, nyc => jjdonson@gmail.com

### Reproduction Steps

web doc issue

### Binary Version

```sh
current web docs
```

### Operating System and Environment details

```sh
current web docs
```

### Log Fragments

```sh
web docs issue
```

**Comment by ajm188** [comment]
Hey Jeremy, thanks for opening an issue! This code is actually on the [website](https://github.com/vitessio/website), I can fix this (for future reference there's also an "Edit Me!" button on each page you can use)
