### ISSUE TITLE
Error codes for all errors

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#10594]
Some (maybe even most) database systems have a list of error messages with additional information, keyed on an error code. Examples:

- [Oracle](https://docs.oracle.com/cd/E11882_01/server.112/e17766/)
- [Microsoft SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver16)
- [MySQL](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html)

Clearly, we need something like this for the errors that Vitess produces. We don't want to embed URLs into the code because that would have to change too much, so having an easy-to-search error code for _ALL_ errors produced by Vitess would be very helpful.

In the golang code, this would also make it easier to create a single store of all existing errors in our large codebase.

**Comment by GuptaManan100** [comment]
@systay For query serving, this has been accomplished by the work that you and @frouioui put in to have the errors in a single file with the error codes and generating a doc for it for the website? If it is complete, we should close this issue.

**Comment by systay** [comment]
I don't mind closing it. 
We could do the same for more error codes, but it's not something I feel like pushing for, so closing this for now.
