### ISSUE TITLE
Bug Report: Stream Consolidations do not work by default, unclear why to the user

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#10660]
### Overview of the Issue

`vttablet` has the query consolidator on by default (for historical reasons, the default can be debated, but that is for another issue).  When we added the stream consolidator (for streaming or `workload=olap` queries), we added the sizing configuration variables to `tabletenv/config.go`;  but did not add flags for `vttablet`.  In addition the defaults for the streaming config variables are `0`, which leads to the (streaming) consolidator not getting created at tablet startup.

The result is that you will not get any streaming consolidations unless:
  * You use the YAML tablet configuration (not that common)
  * and you set the relevant stream consolidation sizing vars (`consolidatorStreamQuerySize` and `consolidatorStreamTotalSize`) both to something appropriate, non-0

Additionally, we don't log anything at startup to indicate the state of the stream consolidator (or the consolidator in general).  This made this problem challenging to debug.

### Reproduction Steps

 * Deploy an unsharded keyspace with default-ish `vttablet` parameters
 * Create a test table (I used `sysbench ... prepare` to create a table called `sbtest1` and insert 1000 rows in it)
 * Use a threaded client to set `workload=olap` and run `select * from sbtest1` from multiple threads.
 * Capture the querylog for the tablet using curl from the `/debug/querylog` endpoint on the tablet HTTP interface
 * Observe that from the query log there are no lines with `consolidator` as the query source, indicating that no consolidations are occurring.

Now:
  * either restart `vttablet` with YAML config that includes the missing streaming variables;  or patch `tabletenv/config.go:Init()` to set them by default
  * Re-run the test above
  * You will observe from the querylog that consolidations are now occurring

Test client I used:

```
import mysql.connector
from threading import Thread

def run():
    cnx = mysql.connector.Connect(host='localhost', port=15306,
        database='unsharded', user='user', password="password",
        charset='utf8', get_warnings=True, autocommit=True)
    curprep = cnx.cursor(prepared=False)
    stmt = 'set workload=olap;'
    curprep.execute(stmt, ())
    stmt = 'select * from sbtest1;'
    curprep.execute(stmt, ())

threads = []
for j in range(0,100):
    print(j)
    for i in range(0,50):
        t = Thread(target=run)
        threads.append(t)
        t.start()

    for t in threads:
        t.join()
```

### Binary Version

```sh
release-14.0 ; but I believe this problem exists since we merged the stream consolidator.
```

### Operating System and Environment details

```sh
Fedora 36, amd64
```

**Comment by maxenglander** [comment]
Today I tested `main` branch with commit 3e3365ee. Confirmed that stream consolidations are working (by default).
