### ISSUE TITLE
Feature Request: Allow sqlparser to be used in another project that uses the `version` flag

### ISSUE THREAD

**Issue by mpchadwick** [vitessio/vitess#10714]
### Feature Description

I am trying to use the Vitess SQL parser in [my database anonymization project](https://github.com/mpchadwick/dbanon). My project has a `version` flag to return the version of the tool in use. When I try to pull in the Vitess SQL parser I get an error due to flag conflict. Here's a simplified script demonstrating the issue

```go
package main

import (
	"flag"
	"fmt"
	"vitess.io/vitess/go/vt/sqlparser"
)

func main() {

	ver := flag.Bool("version", false, "Get current version")
	flag.Parse()

	if *ver {
		fmt.Println("My version output...")
	}

	stmt, _ := sqlparser.Parse("INSERT INTO `admin_user` (`firstname`) VALUES ('bob');")
	fmt.Println(stmt)

}
```

Then running it

```
$ go run main.go
/zzzzzzzzz/exe/main flag redefined: version
panic: /zzzzzzzzz/exe/main flag redefined: version
```

Haven't fully traced why this is happening or what would be involved in changing it but, as far as I know at this point my only option is to rename the flag in my project so avoid the conflict, which I'd prefer not to do.

### Use Case(s)

N/A

**Comment by GuptaManan100** [comment]
@mpchadwick I have located why this is happening, but honestly, I have no idea if we can do anything about it. The `sqlparser` package imports the `servenv` package which has this `version` flag. The definition for this can be found at https://github.com/vitessio/vitess/blob/71265d05b3043b3540df246607da1328d79abe9a/go/vt/servenv/buildinfo.go#L38

I checked golang docs and it seems that flags cannot be redefined, so I don't think there is another alternative than renaming your flag on your end. 

WDYT @vitessio/query-serving?

**Comment by frouioui** [comment]
Hello @mpchadwick 👋🏻 Defining a new `FlagSet` on the `flag` package will "erase" the previous flag set defined by the imported packages. The following snippet works:

```go
package main

import (
	"flag"
	"fmt"
	"os"
	"vitess.io/vitess/go/vt/sqlparser"
)

func main() {
	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ExitOnError)

	ver := flag.Bool("version", false, "Get current version")
	flag.Parse()

	if *ver {
		fmt.Println("My version output...")
	}

	stmt, _ := sqlparser.Parse("INSERT INTO `admin_user` (`firstname`) VALUES ('bob');")
	fmt.Println(stmt)
}
```

**Comment by mpchadwick** [comment]
@frouioui - Thanks so much
