### ISSUE TITLE
vttablet: dangerous undocumented new flag (vreplication_max_time_to_retry_on_error)

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#10783]
`vreplication_max_time_to_retry_on_error` was introduced in #10429 to reduce wasted resources on retrying unrecoverable vreplication errors. While I understand the idea behind it, rather than making an allowlist for unrecoverable errors, the default simply stops vreplication after 15 minutes if the same error occurs, even if that error is recoverable - e.g. a tablet is unavailable during an upgrade or backup. It was extra dangerous because it wasn't documented in the [v14 release notes](https://github.com/vitessio/vitess/releases/tag/v14.0.0) or in the [vreplication flags](https://vitess.io/docs/14.0/reference/vreplication/flags/) page on the website.

https://github.com/vitessio/vitess/blob/cc7974f974d8a4e8d2b44a945204c28498f73e40/go/vt/vttablet/tabletmanager/vreplication/controller.go#L51

This caused us multiple outages, though we've since handled this by setting the max time to 1 year, but I believe we need to fix the default behavior to be less dangerous and unexpected. Here are my suggestions for making this much safer:

1. Create an allow/deny list to require explicit opt in to unrecoverable errors. OnlineDDL was the original impetus for the feature, but I'm sure there are other errors that aren't recoverable.
2. Change the default to something much higher, or IMO make this opt-in so that the default 0 value means retry infinitely
3. Add a new flag `vreplication_retry_max_delay` to allow for exponential backoff, which should more safely reduce resource waste
`retryMaxDelay = flag.Duration("vreplication_retry_max_delay", 5*time.Minute, "max delay (after exponential backoff) before retrying a failed workflow event in the replication phase")`
4. Add documentation to both the release notes and the website

cc @mattlord

**Comment by shlomi-noach** [comment]
@derekperkins thank you -- we're looking into it.

**Comment by shlomi-noach** [comment]
Circling back from an internal discussion, the current idea is to keep the flag, but default it to `0`, which then means "infinite", making the behavior backwards compatible. It's then the user's choice to supply any other value for this flag. Does that make sense?

**Comment by derekperkins** [comment]
That's perfect, thanks!
