### ISSUE TITLE
Bug Report: vtctld CrashLoopBackOff in kubernetes cluster

### ISSUE THREAD

**Issue by javadm11** [vitessio/vitess#10898]
### Overview of the Issue

vtctld CrashLoopBackOff in kubernetes cluster

### Reproduction Steps

Deploy Vitess with following command:

```
  1. git clone git@github.com:vitessio/vitess.git
  2. cd vitess/examples/operator
  3. kubectl apply -f operator.yaml
  4. kubectl apply -f 101_initial_cluster.yaml
```
after this all pods are in running state except vtctld
and when I get log with:  `kubectl logs example-zone1-vtctld-1d4dcad0-845878bcd7-sgt8q`
raise this error: **ERROR: logging before flag.Parse: E0731 21:11:45.228239       1 syslogger.go:149] can't connect to syslog
unknown flag: --enable_queries**

### Binary Version

```sh
/vt/bin/vtctld --version
Version: 15.0.0-SNAPSHOT (Git revision 477f67f380d27045e76523a28ed4defa739ab118 branch 'main') built on Sat Jul 30 17:12:49 UTC 2022 by vitess@buildkitsandbox using go1.18.4 linux/amd64
```

### Operating System and Environment details

```sh
kubernetes cluster with : "kind"
```

**Comment by deepthi** [comment]
Fix PR is in progress https://github.com/planetscale/vitess-operator/pull/300

**Comment by GuptaManan100** [comment]
The PR is merged.
