### ISSUE TITLE
Question: Primary  vttablet would change to read-only mode automatically 

### ISSUE THREAD

**Issue by Kean9527** [vitessio/vitess#10925]
### Question

I encountered several times on this problem. I deployed the vitess and it worked well, but when I use it on the next day, it reports that the primary is read-only. How can I to troubleshoot this?

background:
I use docker compose to start the vitess. today I see the vttablet is unavailable with short time.

**Comment by deepthi** [comment]
Usually if the primary becomes read-only that means that the mysql has restarted for some reason. Vitess managed mysql is always started with read-only. It could be that your docker cluster is running out of memory, or there is some other reason why mysql is shutting down and restarting.
The short-term solution (for local testing only) is to issue a `vtctldclient ... SetReadWrite` command on the primary. In a production environment, something like this will trigger an alert that requires manual intervention.
We do have vtorc, which is experimental right now, but expected to be GA in v15. That will take care of monitoring and fixing such failures.

**Comment by GuptaManan100** [comment]
Docker compose example now also runs VTOrc, so this shouldn't be an issue anymore.
