### ISSUE TITLE
Switch flag definitions to be on pflag instead of flag in `package go/vt/vtgate/vschemaacl`

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#10936]
Part of https://github.com/vitessio/vitess/issues/10697.

Current flags:

```
$ git grep -E "\bflag\.[A-Z]" -- go/vt/vtgate/vschemaacl/*.go
go/vt/vtgate/vschemaacl/vschemaacl.go:  AuthorizedDDLUsers = flag.String("vschema_ddl_authorized_users", "", "List of users authorized to execute vschema ddl operations, or '%' to allow all users.")
```

**Comment by rsajwani** [comment]
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ "vitess.io/vitess/go/vt/vtgate/vschemaacl" {print $1}'                                                                                                      
vitess.io/vitess/go/cmd/vtadmin
vitess.io/vitess/go/cmd/vtcombo
vitess.io/vitess/go/cmd/vtexplain
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vtgateclienttest
