### ISSUE TITLE
docker-compose start failed,vtgate always unhealthy.

### ISSUE THREAD

**Issue by yigeqiji** [vitessio/vitess#11069]
### Question

I run as follows, no other redundant operations, it always fails to run.
https://github.com/vitessio/vitess/tree/main/examples/compose
error:
![image](https://user-images.githubusercontent.com/59365443/186088870-d849418a-b258-48c7-b79b-81db6de62c18.png)
vtgate logs:
![image](https://user-images.githubusercontent.com/59365443/186089138-30104867-120f-4f75-bd33-8cb624d0bb51.png)
Did I miss something important, sorry I'm a rookie.

**Comment by yigeqiji** [comment]
can someone help me

**Comment by mattlord** [comment]
You should use the Vitess community slack when seeking help: https://vitess.io/community/

GitHub issues are not effective as we'd need to ask a bunch of questions and get responses, look at log files etc.

**Comment by yigeqiji** [comment]
> You should use the Vitess community slack when seeking help: https://vitess.io/community/
> 
> GitHub issues are not effective as we'd need to ask a bunch of questions and get responses, look at log files etc.
> 
> That being said, it's possible that this is a bug related to the recent config file changes (moving to spf13 Cobra and Viper for flags). Do you still see the same failure when pulling again from main?
> 
> Do you still see the same error if you instead use release-14? https://github.com/vitessio/vitess/tree/release-14.0/examples/compose
> 
> From there, we really should move this to the Slack.

Thank you very much for your answer, I tried release-14, but the problem is still the same, the vtgate log shows: unknown shorthand flag: 't' in -topo_implementation...
Is it possible that it is because I use docker-compose in wsl?

**Comment by frouioui** [comment]
We have opened a Pull Request (https://github.com/vitessio/vitess/pull/11130) that should fix this issue. The Docker image used in the docker-compose examples, in the release branches, is incorrect. It uses main's Docker images, which are not compatible with `release-14` and below.

After the patch releases of this week, the problem you are seeing on `release-14.0` should disappear.
