### ISSUE TITLE
Feature Request: Option to return MySQL errors without bind vars

### ISSUE THREAD

**Issue by brendar** [vitessio/vitess#11150]
### Feature Description

By default, Vitess will return query error messages to clients that include the underlying MySQL error message plus bind vars. We can control this with the vttablet flag `--queryserver-config-terse-errors=true` but that will cause both the MySQL error message and bind vars to be removed. This can present a challenge for applications moving from plain MySQL to Vitess, as they may rely on the returned error message (and are safely handling any sensitive information in it), but are not prepared to safely handle the bind vars added by Vitess.

e.g. with this table and row:
```
CREATE TABLE users (
  id int NOT NULL PRIMARY KEY,
  email varchar(255) NOT NULL,
  password_hash varchar(255) NOT NULL,
  UNIQUE KEY `index_users_on_email` (`email`)
);

INSERT INTO users (id, email, password_hash) VALUES (1, 'foo@example.com', 'asdf123');
```

Using plain MySQL a duplicate entry error would look like:
```
mysql> INSERT INTO users (id, email, password_hash) VALUES (2, 'foo@example.com', 'asdf123');
ERROR 1062 (23000): Duplicate entry 'foo@example.com' for key 'index_users_on_email'
```

Using vtgate (v14) the error would look like:
```
mysql> INSERT INTO users (id, email, password_hash) VALUES (2, 'foo@example.com', 'asdf123');
ERROR 1062 (23000): target: integration-test.-.primary: vttablet: rpc error: code = AlreadyExists desc = Duplicate entry 'foo@example.com' for key 'index_users_on_email' (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into users(id, email, password_hash) values (:vtg1, :vtg2, :vtg3)", BindVars: {vtg1: "type:INT64 value:\"2\""vtg2: "type:VARCHAR value:\"foo@example.com\""vtg3: "type:VARCHAR value:\"asdf123\""}
```

In this case the MySQL error message contains somewhat sensitive information (email) but the bind vars contain very sensitive information (password_hash). An existing application should be prepared to deal with sensitive information from plain MySQL error messages, but it would not be expecting the additional information in the bind vars. If it were to log the error message or send it to a bug reporting service, that information could be exposed. The bind vars could be especially problematic for "unexpected" errors like lock wait timeouts, deadlocks, etc, where an existing app likely has no specific handling in place and may log them blindly.

If we set `--queryserver-config-terse-errors=true` on the vttablet the error through vtgate looks like:
```
mysql> INSERT INTO users (id, email, password_hash) VALUES (2, 'foo@example.com', 'asdf123');
ERROR 1062 (23000): target: integration-test.-.primary: vttablet: rpc error: code = AlreadyExists desc = (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into users(id, email, password_hash) values (:vtg1, :vtg2, :vtg3)", BindVars: {[REDACTED]}
```

Overall having the ability to remove bind vars is great, but it would be nice to have an option to preserve the MySQL error message so that existing applications can continue to use it.

In [this slack thread](https://vitess.slack.com/archives/C0PQY0PTK/p1661892178269949) @harshit-gangal suggested introducing a new flag to replace `queryserver-config-terse-errors` with modes like: 
```
None
Only BindVars
Non Mysql Errors
All
```
We think this makes a lot of sense and are interested in hearing feedback.

### Use Case(s)

Applications moving from plain MySQL to Vitess

**Comment by systay** [comment]
@brendar [This](https://github.com/vitessio/vitess/pull/11540) change just landed on `main`, and I think it solves your issue. Can you look at it and close this issue if you feel like that solves your problem?

**Comment by brendar** [comment]
Yes, that works. Thanks for bringing it to my attention!

With that change in place we can leave `queryserver-config-terse-errors` unset on vttablet and set `vtgate-config-terse-errors` on vtgate. Client error messages then look like this:
```
mysql> INSERT INTO users (id, email, password_hash) VALUES (2, 'foo@example.com', 'asdf123');
ERROR 1062 (23000): target: commerce.0.primary: vttablet: rpc error: code = AlreadyExists desc = Duplicate entry 'foo@example.com' for key 'index_users_on_email' (errno 1062) (sqlstate 23000) (CallerID: userData1): Sql: "insert into users(id, email, password_hash) values (:vtg1, :vtg2, :vtg3)", BindVars: {REDACTED}
```
