### ISSUE TITLE
Feature Request: MoveTables feature disables RoutingRules

### ISSUE THREAD

**Issue by chhan-coupang** [vitessio/vitess#11218]
### Feature Description

Now we have parameter `keep_routing_rules` to avoid cleaning routing rules.
It's just that we don't use routing_rules, it just brings misoperation (I deleted the source table by mistake when I deleted the migrated tables on vitess! Many times!).
The MoveTables function can create routing rules by default, but also wants to provide a parameter to control not to create it.

### Use Case(s)

No use case.
This new parameter is provided for users who do not want to use the routing rules feature.

**Comment by mattlord** [comment]
Hi @chhan-coupang !

The routing rules are a critical part of VReplication workflows. We can't ensure proper behavior w/o them. For this reason, I don't think this is a feature that we should implement. 

If you think I'm missing something, please let me know. If you REALLY don't want the routing rules in some case (I would strongly advise against it), you can remove them using the [GetRoutingRules](https://vitess.io/docs/14.0/reference/programs/vtctldclient/vtctldclient_getroutingrules/) command to get the current rules as a JSON doc. Remove the ones that you do not want, and then save the new routing rules with the [ApplyRoutingRules](https://vitess.io/docs/14.0/reference/programs/vtctldclient/vtctldclient_applyroutingrules/) command. You should not generally be deleting the target tables directly either, but instead using [MoveTables Cancel](https://vitess.io/docs/14.0/reference/vreplication/cancel/). If you really must delete one table on the target for some reason, then you should use Shard Targeting (e.g. `mysql> use newks:-40`) to be sure that you connect to the correct keyspace (or of course you can connect directly to MySQL).

I'm going to close this for now as I think this would be a dangerous feature to add.

I appreciate the feedback though! If you'd like to discuss further, please reach out in the [Vitess OSS Slack](https://vitess.io/slack). 

Best Regards
