### ISSUE TITLE
Loading multiple INSERTS through vtgate vs standalone MySQL

### ISSUE THREAD

**Issue by skaosYan** [vitessio/vitess#11250]
### Question

Hi, 

I am loading 410M of rows from Oracle into MySQL(2 shards cluster). I run the initial load in parallel with up to 100 inserting processes. Here is the problem:

When I connect my workload through vtgate, I get not more than 5000 inserts per second, per shard.
When I connect the same kind of workload, with the same database configuration to MySQL at shard1, directly, on port 3306, I get maximum around 60 000 inserts per seconds on this MySQL.
 
Can you help me, please, with vtgate tuning? 15X difference is too high.

**Comment by mattlord** [comment]
Hi @skaosYan,

This is a pretty open ended question that could take a lot of back and forth, and this is not the appropriate forum. Let's move this to the [Vitess Slack](https://vitess.io/slack) and we can discuss further there. We'd need to gather _a lot_ more detail about exactly what you're doing and how, what your setup is (starting with vitess version), etc before even digging into where the bottlenecks are and what to recommend.

Best Regards
