### ISSUE TITLE
Bug Report: VTOrc infinitely forgets instance which was restarted and is delayed to respond to discovery query

### ISSUE THREAD

**Issue by vkovacik** [vitessio/vitess#11270]
### Overview of the Issue

VTOrc in version 14.0.2 suffers from the issue described in https://github.com/vitessio/vitess/pull/10662

**Problem:**

When Vitess tablet restarts and MySQL takes time to start responding to VTOrc discovery query, VTOrc will infinitely forget the instance. Even though tablet eventually starts healthy few seconds later, VTOrc will never discover the instance again, leaving it unmanaged.

This can be dangerous at least in the following situations:
- new primary will be promoted and the affected instance will not be reparented with the new primary
- high availability of the shard can be affected

**Goal:**

Fix from https://github.com/vitessio/vitess/pull/10662 (from July 12th) has not been merged into the latest release 14.0.2
Can we prioritise merging the fix in the next release?

### Reproduction Steps

1. Restart tablet
2. Simulate MySQL slow start
3. VTOrc will forget the instance (tablet)

### Binary Version

```sh
Vitess version 14.0.2
```

### Operating System and Environment details

```sh
N/A
```

**Comment by vkovacik** [comment]
cc @GuptaManan100 @deepthi

**Comment by GuptaManan100** [comment]
The PR with the fix has been backported to release-14.0 branch https://github.com/vitessio/vitess/pull/11238.
We use this branch to create new releases, so this fix will be part of the next 14.0 patch release.

**Comment by mattlord** [comment]
Thank you for the bug report, @vkovacik! I'm going to close this as fixed for now, but please let me know if I missed or misunderstood anything and we can re-open it.
