### ISSUE TITLE
Release of v15.0.0

### ISSUE THREAD

**Issue by rsajwani** [vitessio/vitess#11426]
## Description

This issue list the different actions that need to be taken before/during/after the release of `v15.0.0`. The release is scheduled for **Wednesday Oct 26**.

### Pre-Release

- [x] Make sure that the documentation for `v15` fixes/features is merged before `GA`.
- [x] Notify the community on Slack
- [x] Draft the blog post 
   - [x] by @deepthi ( https://docs.google.com/document/d/1wOhRO_eJdGtXUKm6RuB6xJ6nWjOYaFoWjPe_8ah46Ws/edit)
- [x] Review the blog post
- [x] Add release notes diff to the release summary
- [x] Fix release automation issues @frouioui 
  - [x] https://github.com/vitessio/website/pull/1176
  - [x] https://github.com/planetscale/vitess-operator/pull/331
- [x] Create a PR for the blog post on the website repository @frouioui 
  - https://github.com/vitessio/website/pull/1181
- [x] Make sure the release note summary is prepared and clean
  - [x] https://github.com/vitessio/vitess/pull/11502
- [x] Make sure the Pull Request titles that are included in the release notes are well-written and explicit
- [x] Test the operator examples with the latest version of vitess-operator
  - [x] https://github.com/vitessio/website/pull/1184
  - [x] https://github.com/planetscale/vitess-operator/pull/334
  - [x] https://github.com/vitessio/vitess/pull/11548
  - [x] https://github.com/vitessio/vitess/pull/11546
- [x] Upgrade `release-15.0` to `go1.18.7` @frouioui 
- [x] Make sure backports are reviewed and merged onto `release-15.0`
  - [x] https://github.com/vitessio/vitess/pull/11493
  - [x] https://github.com/vitessio/vitess/pull/11415
  - [x] https://github.com/vitessio/vitess/pull/11489
  - [x] https://github.com/vitessio/vitess/pull/11497
  - [x] https://github.com/vitessio/vitess/pull/11505
  - [x] https://github.com/vitessio/vitess/pull/11499
  - [x] https://github.com/vitessio/vitess/pull/11491
  - [x] https://github.com/vitessio/vitess/pull/11481
  - [x] https://github.com/vitessio/vitess/pull/11479
  - [x] https://github.com/vitessio/vitess/pull/11495
  - [x] https://github.com/vitessio/vitess/pull/11527
  - [x] https://github.com/vitessio/vitess/pull/11501
  - [x] https://github.com/vitessio/vitess/pull/11518
  - [x] https://github.com/vitessio/vitess/pull/11528
  - [x] https://github.com/vitessio/vitess/pull/11526
  - [x] https://github.com/vitessio/vitess/pull/11530
  - [x] https://github.com/vitessio/vitess/pull/11516
  - [x] https://github.com/vitessio/vitess/pull/11534
  - [x] https://github.com/vitessio/vitess/pull/11522
  - [x] https://github.com/vitessio/vitess/pull/11541
  - [x] https://github.com/vitessio/vitess/pull/11540
  - [x] https://github.com/vitessio/vitess/pull/11551
  - [x] #11557 
  - [x] #11558
  - [x] https://github.com/vitessio/website/pull/1191
- [x] https://github.com/vitessio/website/issues/1182
- [x] Access the Maven release website
- [x] Prepare the x-posting of the blog post
  - [x] PlanetScale
  - [x] CNCF

### Release

- [x] Follow the release instructions for release: [here](https://github.com/vitessio/vitess/blob/main/doc/internal/ReleaseInstructions.md#pre-requisites-for-releases)
- [x] Continue with the Java release following [these](https://github.com/vitessio/vitess/blob/main/doc/internal/ReleaseInstructions.md#java-packages-deploy--release) instructions.
- [x] `v15.0.0` is released on GitHub and DockerHub
- [x] vitess-operator release `v2.8`
- [x] vtop post release
  - [x] https://github.com/planetscale/vitess-operator/pull/339
  - [x] https://github.com/planetscale/vitess-operator/pull/338
- [x] On the Vitess website repository, update the current and next version variables.
  - [x] https://github.com/vitessio/website/pull/1195
- [x] Merge the `15.0.0` release notes on `main`
  - [x] https://github.com/vitessio/vitess/pull/11567
- [x] Merge the `15.0.0` release notes on `release-15.0`
  - [x] https://github.com/vitessio/vitess/pull/11573
  - [x] https://github.com/vitessio/vitess/pull/11574
- [x] Make sure arewefastyet benchmarks the new release (https://benchmark.vitess.io/status)

### Post-Release

- [x] Benchmarking results: https://benchmark.vitess.io/macrobench?ltag=14.0.0&rtag=15.0.0
- [x] Make sure the Java release is available
  - [x] https://mvnrepository.com/artifact/io.vitess/vitess-jdbc/15.0.0
- [x] Notify the community on:
  - [x] Slack
  - [x] Twitter
- [x] Make sure the blog post is published on:
  - [x] PlanetScale
  - [x] CNCF
  - [x] vitess.io
- [x] Make sure all [forward ports to main](https://github.com/vitessio/vitess/pulls?q=is%3Apr+label%3A%22Forwardport+to%3A+main%22+is%3Aclosed) are done. vitess-bot sometimes fails to do the cherry-picks
  - [x] https://github.com/vitessio/vitess/pull/11578 @rsajwani
  - [x] https://github.com/vitessio/vitess/pull/11557 @GuptaManan100 
  - [x] https://github.com/vitessio/vitess/pull/11551
  - [x] https://github.com/vitessio/vitess/pull/11548 @frouioui 
  - [x] https://github.com/vitessio/vitess/pull/11546
  - [x] https://github.com/vitessio/vitess/pull/11541
  - [x] https://github.com/vitessio/vitess/pull/11540 @frouioui 
  - [x] https://github.com/vitessio/vitess/pull/11534
  - [x] https://github.com/vitessio/vitess/pull/11522 @rsajwani 
  - [x] https://github.com/vitessio/vitess/pull/11507
  - [x] https://github.com/vitessio/vitess/pull/11502
  - [x] https://github.com/vitessio/vitess/pull/11501
  - [x] https://github.com/vitessio/vitess/pull/11499
  - [x] https://github.com/vitessio/vitess/pull/11495 @rsajwani 
  - [x] https://github.com/vitessio/vitess/pull/11493 @rsajwani 
  - [x] https://github.com/vitessio/vitess/pull/11491 @rsajwani 
  - [x] https://github.com/vitessio/vitess/pull/11489
  - [x] https://github.com/vitessio/vitess/pull/11479 @rsajwani 
  - [x] https://github.com/vitessio/vitess/pull/11465
  - [x] https://github.com/vitessio/vitess/pull/11450
- [x] https://github.com/vitessio/vitess/issues/11577
- [x] archive v12.0.0 @frouioui 
- [x] Fix docker/release.sh to upload images of VTAdmin/LogTail/LogRotate @GuptaManan100 - https://github.com/vitessio/vitess/pull/11628
- [x] Update release instructions to include step for docker/release.sh @GuptaManan100

**Comment by frouioui** [comment]
@rsajwani, regarding the line `Access the Maven release website` in the pre-release section, you should create an issue on Sonatype's Jira similar to this one: https://issues.sonatype.org/browse/OSSRH-81956, you can tag me and i'll comment the issue to say that i approve.

**Comment by frouioui** [comment]
@deepthi, regarding `Release the blog post before 9 AM PST on the website repo`, what is the timeline that we wanted to follow to post the blog post with the CNCF/KubeCon?

**Comment by deepthi** [comment]
> @deepthi, regarding `Release the blog post before 9 AM PST on the website repo`, what is the timeline that we wanted to follow to post the blog post with the CNCF/KubeCon?

We decided that the release will be built on Oct 25, and the blog post published at 8 am EDT on Oct 26. We should ask CNCF and PlanetScale to do their x-post at the same time.

**Comment by glortho** [comment]
👋🏼 @deepthi or others -- can you confirm that 👆🏼 this last comment means the official v15 release will be publicly available on Oct 25?

**Comment by deepthi** [comment]
> @glortho, this is correct, it will be available on Oct 25. But will be announced on Oct 26 in case some tasks take longer than expected on Oct 25.

It is almost always the case that the binary release is available on GH several hours before we announce it. That's because after we publish the vitess artifacts on GH, we also do a vitess-operator release, and wait for docker hub to finish building the images (that takes several hours).

**Comment by frouioui** [comment]
@rsajwani @GuptaManan100, I have tagged the three of us in several items of the `Post Release` list. We have to forwardports some of our Pull Requests to `main`.

**Comment by frouioui** [comment]
Closing this issue as all items have been checked off.
