### ISSUE TITLE
Feature Request: Support K8S 1.25+

### ISSUE THREAD

**Issue by Levitan** [vitessio/vitess#11449]
### Feature Description

K8S of versions 1.25+ now not supported by Vitess Operator. On startup fails with `policy/v1beta1 PodDisruptionBudget Deprecated in v1.21+, unavailable in v1.25+`

### Use Case(s)

Setup operator in k8s 1.25+

**Comment by lisachenko-indriver** [comment]
I think, this issue should be moved to the operator project: https://github.com/planetscale/vitess-operator/

**Comment by lisachenko-indriver** [comment]
Will be covered after merge of https://github.com/planetscale/vitess-operator/pull/309

**Comment by frouioui** [comment]
This is supported since https://github.com/planetscale/vitess-operator/pull/397 was merged! Closing this for now :)
