### ISSUE TITLE
Bug Report: Move CI workflow to use latest community version of mysql 8.0

### ISSUE THREAD

**Issue by rsajwani** [vitessio/vitess#11511]
### Overview of the Issue

Our current git workflows are not using latest version of mysql. We are using latest version of percona which has not been updated since Aug 2021
https://repo.percona.com/apt/

here is what we are using in our template file
wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb

This is preventing us to test vitess code against that latest version of mysql. We should always run main against the latest version of mysql. 

As part of this Issue we will track down upgrading across different branches. Issue will be closed manually when all the following branches have been upgraded.

- [x] v13.0
- [x] v14.0
- [x] v15.0
- [x] upstream (v16.0)

### Reproduction Steps

Pick up action run against any PR. Under "Get Dependencies" you will see following lines , which indicate we are still using 8.0.29 version

Unpacking percona-server-server (8.0.29-21-1.focal) ...

action: https://github.com/vitessio/vitess/actions/runs/3246745623/jobs/5325860316

### Binary Version

```sh
All versions
```

### Operating System and Environment details

```sh
All OS
```

**Comment by deepthi** [comment]
We need to port #11493 to main to fix this.
