### ISSUE TITLE
Question: Overhead of 'VSTREAM COPY'

### ISSUE THREAD

**Issue by HenryCaiHaiying** [vitessio/vitess#11561]
### Question

I know 'VSTREAM COPY' is implemented as a big SELECT query with REPEATABLE READ LOCK.  I know MySQL's repeatable lock is implemented using MVCC but it's still going to be a performance impact on Tablet Server.  

Per this doc (https://vitess.io/docs/design-docs/vreplication/vstream/vscopy/): 

"The copy phase is nuanced: we copy a batch of rows until a particular PK using a consistent snapshot. However, once the copy is completed the binlog position would have moved possibly containing updates to the rows already transmitted. Hence we need to perform a “catchup” where we play the events up to the current position. We can only send updates to rows that we have already sent to the stream."

I think the code implementation is here: 
* code to iterate through query result: https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go#L388
* code to generate the SELECT query: https://github.com/vitessio/vitess/blob/main/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go#L266

The SELECT query is going to look like: 'select col from sample-table where pk-col > last-pk-value order by pk-col'

The where clause is open ended: [last-pk-value, infinity], I didn't see how 'until a particular PK' in the doc is implemented in the code.  So the loop to iterate through the query result will either finish or crash, did I miss something here?

**Comment by mattlord** [comment]
Hi @HenryCaiHaiying!

Please join the [Vitess Slack](https://vitess.io/slack) to discuss things like this — we have a growing and vibrant community there than can help and participate in discussions like this whereas the GitHub issues are primarily only seen by maintainers. You can ping me there and I'm happy to discuss it. This would likely require a fairly long thread there to get through all of your related questions on the topic and as not well suited to the project ticketing system. 

In the meantime, you can find more docs on the copy phase here:
  - https://vitess.io/docs/design-docs/vreplication/life-of-a-stream/
  - See speaker notes on slide 20 [here](https://static.sched.com/hosted_files/perconalive2022/7a/PerconaLive_Austin_2022__Vitess_VReplication.pptx)

And to answer the only clear question I see:
> The where clause is open ended: [last-pk-value, infinity], I didn't see how 'until a particular PK' in the doc is implemented in the code. So the loop to iterate through the query result will either finish or crash, did I miss something here?

The row copy portion of the copy phase cycles end either when all rows for the table have been copied from the transactional snapshot OR we have been copying rows for [vreplication_copy_phase_duration](https://vitess.io/docs/14.0/reference/vreplication/flags/#vreplication_copy_phase_duration).

As an aside, that design doc is fairly old now and some of the wording could certainly be improved to add more clarity so I'm also happy to discuss suggestions around that. I agree that the wording you called out is a little misleading as it's not until a specific fixed PK, but rather we do copy until a specific PK as we keep track of the last PK copied along the way and we know where we stopped.

Please do reach out in the [Vitess Slack](https://vitess.io/slack) as it's a great place to discuss all things Vitess.

Best Regards

**Comment by HenryCaiHaiying** [comment]
@mattlord Thanks for the pointer.  Looks like vreplication_copy_phase_duration is only used for vreplication code path (in vcopier.go).  Our use case is bit different, we are VStream subscription client and  use VGtid = "" to subscribe, this would trigger the 'VSTREAM COPY', this code path does not go through vcopier, is there also a similar timeout used for the SELECT query?

**Comment by mattlord** [comment]
Sorry, you’re right. That design doc was written with the intent to add multiple cycles / resumeability to vstream copy like we have with vreplication but it was never added. So vstream copy is at the moment a single cycle copy phase and if it’s interrupted must be started over. Please move this to discussion to slack. There I will share an ongoing thread/discussion there about adding this feature. And a number of us involved can discuss whatever follow-up questions you may have.

Thanks.
