### ISSUE TITLE
Links on 15_0_0_summary.md and 15_0_0_release_notes.md are broken

### ISSUE THREAD

**Issue by rsajwani** [vitessio/vitess#11577]
### Overview of the Issue

bookmarks on these md files are not working

### Reproduction Steps

- got to https://github.com/vitessio/vitess/blob/release-15.0/doc/releasenotes/15_0_0_release_notes.md
- click on 'Deprecations' or any other link , you will see that it won't jump on that bookmark.

### Binary Version

```sh
all
```

### Operating System and Environment details

```sh
all
```

**Comment by frouioui** [comment]
Fixed by https://github.com/vitessio/vitess/pull/11578
