### ISSUE TITLE
Escape symbols in LIKE clause are removed by vtgate

### ISSUE THREAD

**Issue by skaosYan** [vitessio/vitess#11599]
### Overview of the Issue

I have build a testcase:
Prepared a SQL and ran it through vtgate:

`select 'yan' from jobs where partner_id = 123 and partner_job_code like '\_yanzT4C4j\_7yLWngWP93ZtXgnukm6NuPchqtS2u0mHbSnI\%';
`
In MySQL processlist I see Escape slash characters are removed.`
| 16793605 | vt_app          | localhost                    | vt_test      | Query            |       4 | executing                                                       | select 'yan' from jobs where partner_id = 3790221 and partner_job_code like '_yanzT4C4j_7yLWngWP93ZtXgnukm6NuPchqtS2u0mHbSnI%' limit 10000000001 |`

Any way to avoid it Vitess? It breaks functionality of SQL.

### Reproduction Steps

Run a SQL with LIKE and escape character with backslash. It will be removed.

### Binary Version

```sh
Version: 11.0.4 (Git revision cb142ee branch 'HEAD') built on Mon Jan 10 15:55:07 UTC 2022 by runner@fv-az201-838 using go1.16.13 linux/amd64
```

### Operating System and Environment details

```sh
Linux 3.10.0-1160.53.1.el7.x86_64 #1 SMP Thu Dec 16 10:19:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mattlord** [comment]
Hi @skaosYan,

Thank you for the bug report!

I'm not able to repeat this on v15:
```
pushd examples/local
./101_initial_cluster.sh
vtctlclient InitShardPrimary --force commerce/0 zone1-100

command mysql -u root --socket=${VTDATAROOT}/vt_0000000100/mysql.sock --binary-as-hex=false -e "set global general_log=ON"
mysql commerce -e "create table liketest (id int not null auto_increment primary key, ttext varchar(100))"
mysql commerce -e "select * from liketest where ttext like '\_yanzT4C4j\_7yLWngWP93ZtXgnukm6NuPchqtS2u0mHbSnI\%'"
grep liketest ${VTDATAROOT}/vt_0000000100/data/*.log

./401_teardown.sh
popd
```

I see:
```
2022-10-27T22:39:33.712335Z	   88 Query	create table liketest (
		WHERE TABLE_SCHEMA = 'vt_commerce' AND TABLE_NAME = 'liketest'
2022-10-27T22:39:33.735605Z	   89 Query	SELECT `id`, `ttext` FROM `vt_commerce`.`liketest` WHERE 1 != 1
2022-10-27T22:39:33.752878Z	   91 Query	select * from liketest where ttext like '_yanzT4C4j_7yLWngWP93ZtXgnukm6NuPchqtS2u0mHbSnI%' limit 10001
```

I'm going to close this as fixed for now, but please let us know if we missed something and we can re-open it.
