### ISSUE TITLE
RFC: New vexplain command having a format to glean information about vtgate and MySQL plans

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#11621]
### Description

We propose adding a new Vitess-specific command called `vexplain`, which extends the `explain` query that MySQL offers. The command would have multiple FORMATs that it supports -

| **Type Name** | **Description**                                                                           | **Actually Runs Queries**                 |
|:---------------:|---------------------------------------|------------------------|
|       PLAN (DEFAULT)      | VTGate plan in JSON format                                                                | No. (Only gets the VTGate Plan)           |
|     QUERIES    | All the MySQL queries run along with information about the keyspace shard they are run on | Yes.                                      |
|    ALL   | Same as JSON format, annotated with the MySQL plans for all the queries in ROUTEs         | Yes. (Also runs EXPLAIN queries on MySQL) |

The command `VEXPLAIN PLAN` is going to have more information than `EXPLAIN FORMAT = VITESS` and is intended to replace its usage. The output format is going to be different, though. The output of `VEXPLAIN QUERIES` is going to be equivalent to `EXPLAIN FORMAT = VTEXPLAIN`. We would like to deprecate the latter commands entirely, so as the clean up the `EXPLAIN` command.

The end goal is that the `EXPLAIN` command only routes the query to MySQL instances and for any Vitess level planning information, `VEXPLAIN` should be used.

We also propose the addition of the ALL type, which will also gather the MySQL plans for the executed queries and show them along with the VTGate plans. An example for this format would look something like this - 

```sql
mysql [localhost:8026] (ks) > VEXPLAIN ALL SELECT name FROM user where id = 1
+------------------------------------------------------------------------------------------------+
| VEXPLAIN                                                                                      |
+------------------------------------------------------------------------------------------------+
{
  "OperatorType": "Route",
  "Variant": "EqualUnique",
  "Keyspace": {
    "Name": "user",
    "Sharded": true
  },
  "FieldQuery": "select `name` from `user` where 1 != 1",
  "Query": "select `name` from `user` where id = 1",
  "Table": "`user`",
  "Values": [
    "INT64(1)"
  ],
  "Vindex": "user_index",
  "MySQLPlan": {
    "query_block": {
      "select_id": 1,
      "cost_info": {
        "query_cost": "1.00"
      },
      "table": {
        "table_name": "user",
        "access_type": "const",
        "possible_keys": [
          "PRIMARY"
        ],
        "key": "PRIMARY",
        "used_key_parts": [
          "id"
        ],
        "key_length": "8",
        "ref": [
          "const"
        ],
        "rows_examined_per_scan": 1,
        "rows_produced_per_join": 1,
        "filtered": "100.00",
        "cost_info": {
          "read_cost": "0.00",
          "eval_cost": "0.10",
          "prefix_cost": "0.00",
          "data_read_per_join": "24"
        },
        "used_columns": [
          "id",
          "name"
        ]
      }
    }
  }
}
+------------------------------------------------------------------------------------------------+
```
In the above output, we have the vtgate plan which is annotated with the MySQL plan for the actual query executed, which can be seen in the field `MySQLPlan` on all `Route` operators.

An example output for the ALL mode used for a join query `select id, user_id, name from user join user_extra where user.id = user_extra.col` will look like this -
```json
{
  "OperatorType": "Join",
  "Variant": "Join",
  "JoinColumnIndexes": "R:0,L:1,R:1",
  "JoinVars": {
    "user_extra_col": 0
  },
  "TableName": "user_extra_`user`",
  "Inputs": [
    {
      "OperatorType": "Route",
      "Variant": "Scatter",
      "Keyspace": {
        "Name": "user",
        "Sharded": true
      },
      "FieldQuery": "select user_extra.col, user_id from user_extra where 1 != 1",
      "Query": "select user_extra.col, user_id from user_extra",
      "Table": "user_extra",
      "MySQLPlan": {
        "query_block": {
          "select_id": 1,
          "cost_info": {
            "query_cost": "0.45"
          },
          "table": {
            "table_name": "user",
            "access_type": "ALL",
            "rows_examined_per_scan": 2,
            "rows_produced_per_join": 2,
            "filtered": "100.00",
            "cost_info": {
              "read_cost": "0.25",
              "eval_cost": "0.20",
              "prefix_cost": "0.45",
              "data_read_per_join": "48"
            },
            "used_columns": [
              "id",
              "name"
            ]
          }
        }
      }
    },
    {
      "OperatorType": "Route",
      "Variant": "EqualUnique",
      "Keyspace": {
        "Name": "user",
        "Sharded": true
      },
      "FieldQuery": "select id, `name` from `user` where 1 != 1",
      "Query": "select id, `name` from `user` where `user`.id = :user_extra_col",
      "Table": "`user`",
      "Values": [
        ":user_extra_col"
      ],
      "Vindex": "user_index",
      "MySQLPlan": {
        "query_block": {
          "select_id": 1,
          "cost_info": {
            "query_cost": "1.00"
          },
          "table": {
            "table_name": "user_extra",
            "access_type": "const",
            "possible_keys": [
              "PRIMARY"
            ],
            "key": "PRIMARY",
            "used_key_parts": [
              "col"
            ],
            "key_length": "8",
            "ref": [
              "const"
            ],
            "rows_examined_per_scan": 1,
            "rows_produced_per_join": 1,
            "filtered": "100.00",
            "cost_info": {
              "read_cost": "0.00",
              "eval_cost": "0.10",
              "prefix_cost": "0.00",
              "data_read_per_join": "24"
            },
            "used_columns": [
              "user_id",
              "col"
            ]
          }
        }
      }
    }
  ]
}
```

**Comment by arthurschreiber** [comment]
`EXPLAIN ANALYZE` in MySQL provides additional information on the runtime execution of queries, like start and end times of individual steps. I think having something like that be part of the `QUERIES` or `EXHAUSTIVE` format would be incredibly helpful in understanding Query execution and performance in Vitess, especially as queries can be split up across shards and executed in parallel.

**Comment by deepthi** [comment]
Great proposal.

> The end goal is that the EXPLAIN command only routes the query to MySQL instances and for any Vitess level planning information, VTEXPLAIN should be used.

Can you elaborate on a few things?
- Why do we not want to override `EXPLAIN` further? 
- What is the scenario where you would route the `EXPLAIN` directly to MySQL?

I can guess but I'd like these to be written down as well.

**Comment by arthurschreiber** [comment]
> Can you elaborate on a few things?
> 
> - Why do we not want to override `EXPLAIN` further? 

I think we could do that as well, but it requires that we come up with more explain format names. Having a completely separate command seems cleaner, but I think either works.

We can't extend existing explain output formats because that would break existing tooling that treats vitess like regular MySQL. 

> - What is the scenario where you would route the `EXPLAIN` directly to MySQL?

That's actually a good question as well. Sharded or cross keyspace queries will probably never be routable correctly anyway 🤷

Maybe we should throw an error if we detect an explain for a query like that and mention the vitess explain command. Normal/single keyspace queries should continue working as-is.

**Comment by GuptaManan100** [comment]
> Why do we not want to override EXPLAIN further?

Yes, exactly as @arthurschreiber said. We don't want to add more and more formats to EXPLAIN which are Vitess-specific, because I believe it will be too convoluted and harder to use. Instead having a new command, demarcates the two boundaries quite well. `vtexplain` if we want the Vitess-only information (along with MySQL info too, if requested) and `explain` if you want `MySQL` information. Because it is a new command, we can choose whatever format we want for the output. We don't need to worry about any tooling for MySQL running these.

> What is the scenario where you would route the EXPLAIN directly to MySQL?


Well, `explain` is meant to be used only for unsharded (or single-shard) keyspaces wherein the query is invariably routed to MySQL. Currently, Vitess routes the explain queries to any shard (if not shard targeted) for formats that aren't vitess-specific. This I believe is because we don't want to throw errors in case `explain` statements are executed in sharded mode because some frameworks might be using them. We can probably iterate on this too later and instead be a little smarter in our routing of the query or try and merge multiple `explain`s in case of Joins etc, but that is not in the scope of this RFC. 

The way that I am thinking of this is that `vtexplain` gives us more insight into the Vitess planning but isn't meant to be used by frameworks.
`explain`, since it is a MySQL command, will be used by frameworks and we'll have to adhere to the structure of the data to be returned for the frameworks to continue working. This is trivial for unsharded keyspaces, and not ideal for the sharded case (wherein we just route the query to any shard), but that can be improved upon. However, we would still be returning data which would be in known MySQL format. i.e., if later we want to improve the `explain` output for a query that does a join across keyspaces, we can show that as a JOIN but only as an output that MySQL would show too. So, we can't show that the join in on vtgate level or anything else like that, just the part that it was a join. 
WDYT @systay ?

**Comment by frouioui** [comment]
This is a great proposal.

Are we planning on reusing some of the bricks used to build the `vtexplain` binary?

**Comment by systay** [comment]
> `EXPLAIN ANALYZE` in MySQL provides additional information on the runtime execution of queries, like start and end times of individual steps. I think having something like that be part of the `QUERIES` or `EXHAUSTIVE` format would be incredibly helpful in understanding Query execution and performance in Vitess, especially as queries can be executed in parallel when split up across shards.

That's actually a pretty great idea. The only issue would be:
When we do joins, we usually run the RHS route multiple times. Similarly, for scatter queries, we are doing many tablet calls for one route operator in the plan.

How would we show the timing information for these operators? Do we show the number of calls, min max and the median? What would be helpful?

**Comment by systay** [comment]
> This is a great proposal.
> 
> Are we planning on reusing some of the bricks used to build the `vtexplain` binary?

Not much, no. The way vtexplain is very different from what we can do in vtgate. In vtexplain, we need to fake a lot of stuff, since we don't have a running cluster to query.

Also, `explain format=vtexplain` is already implemented, this proposal would just change the syntax for it to `vtexplain format=queries`, not re-implement it.

**Comment by frouioui** [comment]
> Not much, no. The way vtexplain is very different from what we can do in vtgate. In vtexplain, we need to fake a lot of stuff, since we don't have a running cluster to query.

As someone who does not know much about `vtexplain`, having two different things called `vtexplain` but that do different things might be slightly confusing.

**Comment by systay** [comment]
From the outside, the two `vtexplain`s look very similar. The implementation is what is different

**Comment by frouioui** [comment]
> From the outside, the two `vtexplain`s look very similar. The implementation is what is different

Right

**Comment by mattlord** [comment]
I like it! Couple of minor points/thoughts (many of which are echoing previous comments):
  1. `a new Vitess-specific command called vtexplain` IMO it's helpful to be more specific and note that it's an SQL command/statement
  2. IMO it should be `vexplain` as VT is Vitess Technology and used for binaries/commands/tools — vtgate, vttablet, vtexplain, etc — whereas V is a Vitess version of some concept or structure like vgtid, vevent, vstream, vreplication, vschema, etc. This also addresses Florent's concern about the same name being used for two related but different things (one a stand-alone binary and the other a vitess variant of an existing concept)
  3. IMO it should be `VEXPLAIN FORMAT = JSON` rather than exhaustive as this better matches MySQL behavior (JSON format has a lot of additional info not in the tabular output)
  4. I also like the idea of `VEXPLAIN ANALYZE` to try and track down where time is being spent during query execution (where/what to try and optimize) — you could e.g. see that cross cell traffic is much slower than expected during RPCs
  5. Since we're allowing `VEXPLAIN` and `EXPLAIN` I think it's on us to produce a helpful error when we cannot execute EXPLAIN in an intuitive way that produces correct results (and the error should let people know about vexplain).

Thank you for working on this! ❤️

**Comment by arthurschreiber** [comment]
I agree with basically all of the suggestions made by @mattlord 😅

Having consistent naming across Vitess concepts (when to use `vt` as the prefix, and when to use `v` instead) makes sense and would make it easier to understand things on a glance.

Merging `EXHAUSTIVE` and `JSON` also seems like a good idea, but we might want to try that out first? I fear that the output might become so large that it might be hard to read.

`VEXPLAIN ANALYZE` should definitely "be a thing" - it would be incredibly helpful.

I also agree that in a sharded keyspace, `EXPLAIN` should work as-is if the query is a single shard query, for everything else the command should fail and refer to using `VEXPLAIN` instead.
