### ISSUE TITLE
Bug Report: VTOrc repairs fail when vttablet is unreachable

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#11662]
### Overview of the Issue

It has been noticed that if the vttablet is unreachable then, VTOrc fails to repair the issue with the default values set for `LockShardTimeoutSeconds` and `TopoRemoteOperationTimeout`.

Both of these values have a default for 30 seconds. The `RemoteOperationTimeout` is used to wait for a tablet's response when we want to refresh the information for a shard in VTOrc. Since the `LockShardTimeout` is also 30 seconds, we end up spending all the time in the refresh phase itself before we even reach the repair. 

This leads to VTOrc timing out again and again and failing to run the repairs.

This problem is generally less likely to happen in an environment deployed by an operator because the vttablet pods that are unreachable are readily restarted by the operator. Most of the times there we run into issues with the vttablet being not serving or MySQL not being in the correct state. These situations VTOrc handles already.

This same problem is also present in the ERS codepath, wherein we use the TopoRemoteOperationTimeout for waiting for DemotePrimary to return. In case of multiple failures due to vttablets not being reachable, we won't be able to handle them.

### Reproduction Steps

Have a cluster running with VTOrc. Shutdown a vttablet instance and wait for VTOrc to repair. Check logs to see the failures in repair that VTOrc runs into.

### Binary Version

```sh
All
```

### Operating System and Environment details

```sh
All
```

**Comment by johnwangwangjun** [comment]
Add my 2 Cents here, believe we observed 3 of our Dev Vitess clusters ran into a similar situation but a slightly different angle here.

Last weekend one of our K8S nodes failed, took down 1 MASTER vttablet PoD each Vitess cluster, our 3 Vitess clusters are running in the same specs, and configs, and basically are mirrored setups, they had the exact same symptom during this kind of failure.

Our K8S cluster times 1 hour of unreachable hardware, after that, K8S redeploys PoDs on healthy nodes.

**Reproduction Steps:**
Vitess version: V14.0.3, runs on K8S.
Kill 1 MASTER vttablet of a shard, by pulling out its power
Make sure K8S doesn't respawn a new vttablet

**Expect symptoms**
Vtorc detects UnreachablePrimary, but fails on finding Successor
Vtorc detects DeadPrimary, but continues to fail on Successor
Expect to see a lot of Locking / Unlocking the shard messages, but eventually a lot of Unlocking fail, example logs:

``` 
2022-11-06 08:48:00    ERROR topology_recovery.go:1484] deadline exceeded: /vitess/vitess-db-blueberry-dev/global/keyspaces/instance_inventory_user/shards/80-/locks
 I1106 08:48:00.866126       1 locks.go:412] Unlocking shard instance_inventory_user/80- for action Orc Recovery with error Code: INVALID_ARGUMENT
 lock for shard instance_inventory_user/80- is already held
 {"level":"warn","ts":"2022-11-06T08:48:00.868Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":     "etcd-endpoints://0xc00046a8c0/#initially=[vitess-db-blueberry-dev-etcd-c3f34000-client.instance-inventory.svc:2379]","attempt":0,"error":"rpc error: code = NotFound      desc = etcdserver: requested lease not found"}
 W1106 08:48:00.868711       1 locks.go:341] unlockShard(instance_inventory_user/80-) failed: node doesn't exist: lease
 2022-11-06 08:48:00    ERROR topology_recovery.go:1484] Code: INVALID_ARGUMENT
 lock for shard instance_inventory_user/80- is already held
```

Start to see AttemptRecoveryRegistration operations:

```
AttemptRecoveryRegistration: cluster 10.78.160.235:3306 has recently experienced a failover (of 10.78.160.235:3306) and is in    active period. It will not be failed over again. You may acknowledge the failure on this cluster (-c ack-cluster-recoveries) or on 10.78.160.235:3306 (-c ack-instance-    recoveries) to remove this blockage
``` 

The shard continues to run without MASTER, with 2 REPLICAs in NOT_SERVING status

**How did clusters recover**
1 hour later, as soon as our K8S repaved the new vttablets, the shard come back as normal.

**Some investigations**
We figured our Vitess clusters have this config, we expect this message to go away after 2 minutes but the above message prints forever.
`FailureDetectionPeriodBlockMinutes: 2`

This is [the piece of code](https://github.com/planetscale/vitess/blob/adeccd2ae1e5b34da0da2fbf89debdc5ccefde2c/go/vt/vtorc/logic/topology_recovery_dao.go#L179-L186) that executes AttemptRecoveryRegistration and prints out above message, it query current in_active_period nods with:
```
	whereClause := `
		where
			in_active_period=1
			and
				successor_hostname=? and successor_port=?`
```

However it seems that the function _ClearActiveFailureDetections()_ which updates in_active_period = 0 [only executes when](https://github.com/planetscale/vitess/blob/adeccd2ae1e5b34da0da2fbf89debdc5ccefde2c/go/vt/vtorc/logic/orchestrator.go#L414-L415) this vttablet is _IsLeaderOrActive()_, which makes under this scenario, Vtorc does not respect FailureDetectionPeriodBlockMinutes.

**Comment by GuptaManan100** [comment]
I looked at this issue in detail today and found that it is not as straight-forward as initially presumed. There are multiple issues here which I'll describe one by one - 

1. VTOrc refresh waits for `RemoteOperationTimeout` seconds for _each_ vttablet to refresh. The overall LockShard timeout is defined by `LockShardTimeout`. One piece of information that I have found is that the code for `LockShard` in topo-server also adds and additional timeout of `RemoteOperationTimeout` like -
    ```go
    func (l *Lock) lockShard(ctx context.Context, ts *Server, keyspace, shard string) (LockDescriptor, error) {
	log.Infof("Locking shard %v/%v for action %v", keyspace, shard, l.Action)

	ctx, cancel := context.WithTimeout(ctx, RemoteOperationTimeout)
    ```
    What this means is that _any_ configuration of VTOrc will not fix the issue. Even if the `LockShardTimeout` is set to a higher value, the shard lock is capped by the `RemoteOperationTimeout` i.e. effective value of `LockShardTimeout` <= `RemoteOperationTimeout`. This kinda throws the utility of `LockShardTimeout` seconds value into question. We use `RemoteOperationTimeout` to set the context timeout for operations like `FullStatus`, `RefreshKeyspaceInformation`, `ResetReplicationParameters` among other operations. So it doesn't make any sense to have `LockShardTimeout` to be anything lower than `RemoteOperationTimeout`. Setting it higher does nothing, so that parameter is entirely useless as it stands now.

2. There is no parallelism in refreshing tablets in VTOrc. This is also an issue (even though not an immediate one). If there are two failures of vttablets, it doesn't make sense to wait for the first and then wait again for the second. All the refreshes should be parallel and should be capped by whatever timeout we set.

3. ERS suffers from a similar issue as VTOrc as the original description specifies. We use `WaitReplicasTimeout` for waiting for tablets to respond to `DemotePrimary` call and this value defaults to equal to `RemoteOperationTimeout` which is the exact amount of time we can lock the shard for. This means that we can't handle more than 1 failure of vttablets when we run ERS. 

4. VTOrc also has a throttling problem wherein the registeration and clearing of recoveries is not handled correctly. This is orhtogonal to the current issue, but still something to fix.

**Comment by GuptaManan100** [comment]
Here is my proposed solution to the problems listed above - 

1. We should remove the `LockShardTimeoutSeconds` entirely as it not doing anything.
2. Add parallelism to VTOrc refresh just like how we have in ERS. This is always going to be better and faster.
3. Add a new parameter called `ReachabilityTimeout` (or some other better name for it), both in ERS configuraitons and VTOrc which is the amount of time to wait for a response from a vttablet for `DemotePrimary` in the case of ERS and `FullStatus` in case of VTOrc refresh. The total amount of time we lock the shard for should allow for atleast 2 of these waits. i.e. `RemoteOperationTimeout` > `ReachabilityTimeout` * 2 so that we can have a refresh phase and then ERS phase and still have some time left-over to complete the ERS operation.
4. Throttling to be fixed separately.

**Comment by GuptaManan100** [comment]
After discussing with @deepthi, we have come to the conclusion that from the proposed solutions points 1,2, and 4 make perfect sense, but there is a better alternative to point 3 proposed above.

https://github.com/vitessio/vitess/pull/4550 made the change of introducing `RemoteOperationTimeout` while deprecating `LockTimeout`. This also added the change to `LockShard` and `LockTimeout` to be capped by `RemoteOperationTimeout`. This seems incorrect because the assumption that we would only run one RPC after acquiring a shard lock doesn't hold. Instead, we should have a separate `LockTimeout` which is set to a larger value (preferably 3 times of the `RemoteOperationTimeout`) and `RemoteOperationTimeout` should be the amount of time given to a single RPC call. 

The PR https://github.com/vitessio/vitess/pull/651/ which introduced ERS for the first time also had a bug in the usage of `waitReplicasTimeout`. This value was used for all RPCs and not just for the waiting for replicas to be caught up. The idea is that each RPC should be capped by `RemoteOperationTimeout` but the user should be able to increase the time for the replicas to catch up. This shouldn't affect the other RPCs like getting the replication status, etc. They should still be capped by `RemoteOperationTimeout`.

Both of the two things pointed above will be fixed. We will introduce a new `LockTimeout` to increase the amount of time shard and keyspaces can be locked for. The usages of `RemoteOperationTimeout` and `WaitReplicasTimeout` will be fixed to as described above.

**Comment by vkovacik** [comment]
@GuptaManan100 @deepthi 

> This problem is generally less likely to happen in an environment deployed by an operator because the vttablet pods that are unreachable are readily restarted by the operator. 

This is not entirely true. We have recently encountered an issue where vtorc failed to promote new primary because it was unable to acquire the shard lock for a prolonged time. This happened during regular, planned Kubernetes cluster maintenance, in which each Kubernetes node was drained and upgraded in a rolling fashion. It took more than an hour to fully drain Kube node (which was running primary pod), during which primary pod was being held in Pending status (waiting for the underlying local persistent PVC).

We have observed that vitess-operator started reconciling the pod and acquired the shard lock before vtorc would detect primary tablet being down. Since vitess-operator kept holding the lock while pod was being scheduled (more than an hour) it technically blocked vtorc from failing over the primary.

I believe this is more a vitess-operator issue I will create a separate issue for the operator.

**Comment by GuptaManan100** [comment]
I am not sure if the operator would be holding the lock. I see in the operator code that the only places it acquires the shard locks is when it is repairing replication or electing a new primary. It is likely that a different go-routine of VTOrc itself is holding the shard lock. After acquiring the shard lock, that go-routine would probably be refreshing the tablets information and timing out because of the issue described in the description.

Do you see `Locking shard ... for action ...` in the operator logs?

**Comment by vkovacik** [comment]
@GuptaManan100 You are correct that it's not related to vitess-operator. There are no logs showing that the operator was locking the shard. 

However I was able to find repro steps for the issue that I described. The important point that I had previously missed is that vtorc pod had been rescheduled few seconds before the primary tablet went down. When vtorc started, it detected downed primary and executed PlannedReparentShard which failed with error:
```
unsharded/- [reparent xxx-0830547867 -> xxx-3964364658] failed PlannedReparentShard: cannot get replication position on current primary xxx-0830547867; current primary must be healthy to perform PlannedReparent: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp 10.77.18.38:15999: i/o timeout" ()
```
I'm assuming when vtorc starts it assumes that all tablets are healthy hence it executed PRS. The issue is that all subsequent recovery attempts were failing with:
```
Locking shard unsharded/- for action Orc Recovery
2023-01-17 21:03:09    ERROR topology_recovery.go:1484] deadline exceeded: /vitess/scratch-db/global/keyspaces/unsharded/shards/-/locks

AttemptRecoveryRegistration: cluster 10.77.16.47:3306 has recently experienced a failover (of 10.77.16.47:3306) and is in active period. It will not be failed over again. You may acknowledge the failure on this cluster (-c ack-cluster-recoveries) or on 10.77.16.47:3306 (-c ack-instance-recoveries) to remove this blockage
```

**Reproduction steps:**

1. Disable namespace applier
2. Disable vtorc in the shard by scaling vtorc deployment replicas to 0
3. Cordon Kubernetes node which is running primary pod - this will prevent pod from being scheduled on the node
4. Delete primary pod but KEEP it's PVC
5. Confirm that primary pod is waiting to be scheduled
6. Enable vtorc by scaling replicas back to 1
7. Confirm that vtorc failed to recover the primary
