### ISSUE TITLE
Bug Report: v15.0.0 Release doesn't have the `web` directory leading to VTAdmin not being deployed properly

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#11679]
### Overview of the Issue

The v15.0.0 release doesn't have the `web` directory in the release. This leads to the initial cluster failing as VTAdmin web isn't deployed properly

### Reproduction Steps

Download V15 from https://github.com/vitessio/vitess/releases/download/v15.0.0/vitess-15.0.0-e8c7e27.tar.gz and try running the local example.

### Binary Version

```sh
v15, maybe even v14 (still to check)
```

### Operating System and Environment details

```sh
all
```

**Comment by frouioui** [comment]
Closing this issue as #11683 is merged.

**Comment by Danmark** [comment]
> Closing this issue as #11683 is merged.

It never made it in to the main branch. So this issue persists in v.16.0.0
