### ISSUE TITLE
Operator Examples: Add `commerce` sequences with vtctldclient fails on parsing

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#11785]
### Overview of the Issue

When running the operator example, at the third step (resharding), we are asked to add the vitess sequences to the `commerce` keyspace using `vtctldclient` using the following commands:
```
vtctldclient ApplySchema --sql="$(cat create_commerce_seq.sql)" commerce
vtctldclient ApplyVSchema --vschema="$(cat vschema_commerce_seq.json)" commerce
```

However, the first command fails with a parsing error on the first line of the `create_commerce_seq.sql` file. The file is well written:

```sql
create table customer_seq(id int, next_id bigint, cache bigint, primary key(id)) comment 'vitess_sequence';
insert into customer_seq(id, next_id, cache) values(0, 1000, 100);
create table order_seq(id int, next_id bigint, cache bigint, primary key(id)) comment 'vitess_sequence';
insert into order_seq(id, next_id, cache) values(0, 1000, 100);
```

It seems that the first line of the file is always the issue. If I commend the first two lines and executes, it passes without an issue. If I add a comment before the 4 existing line and execute, it passes well.

My current workaround is to simply add one line of comment at the beginning of the file.

### Reproduction Steps

Run the local examples until the resharding phase.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
OSX
```

**Comment by ajm188** [comment]
I'm guessing that the problem has to do with an interaction with the semi-colon splitting [here](https://github.com/vitessio/vitess/blob/main/go/cmd/vtctldclient/command/schema.go#L122), taking a look today!

**Comment by frouioui** [comment]
Thank you @ajm188!
