### ISSUE TITLE
Bug Report: `bug: not supported pushWeightStringForDistinct on *planbuilder.limit`

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#11805]
### Overview of the Issue

If a query contains more than 64 tables joined via union statements, it fails with `bug: not supported pushWeightStringForDistinct on *planbuilder.limit` when using the Gen4 planner.

### Reproduction Steps

See https://github.com/vitessio/vitess/pull/11797 for an reproducible example.

### Binary Version

```sh
v15.0.0
```

### Operating System and Environment details

```sh
N/A
```

**Comment by Mideluna** [comment]
docs/install_linux.md
