### ISSUE TITLE
Bug Report: Movetables and Reshard Fail - comment for tables and columns include multibyte characters, 

### ISSUE THREAD

**Issue by huangzhiyong** [vitessio/vitess#11809]
### Overview of the Issue

Movetables and Reshard fail to apply DDL when tables and columns have multibyte strings. The reason is that the character set is not set when the mysql command is executed, resulting in inconsistencies when comparing the table structure. The specific code and test cases are as follows:

The call chain is as follows:
Wrangler.applySQLShard 
-> TabletManager.ApplySchema 
      -> Mysqld.ApplySchemaChange 
            -> Mysqld.executeSchemaCommands
                 -> Mysqld.executeMysqlScript
                      -> Mysqld. defaultsExtraFile
When **_defaultsExtraFile_** builds a temporary config file, the connection character set is not set, resulting in inconsistent comments in the table structure in SourceKs and TargetKs.

How to fix:
Both Movetables and Reshard use the parameters of the **vt_dba** user to create a connection. The default character set exists, and we can directly refer to it.
go/vt/mysqlctl/mysqld.go
```
func (mysqld *Mysqld) defaultsExtraFile(connParams *mysql.ConnParams) (string, error) {
	var contents string
	connParams.Pass = strings.Replace(connParams.Pass, "#", "\\#", -1)
	if connParams.UnixSocket == "" {
		contents = fmt.Sprintf(`
[client]
user=%v
password=%v
host=%v
port=%v
`, connParams.Uname, connParams.Pass, connParams.Host, connParams.Port)
	} else {
		contents = fmt.Sprintf(`
[client]
user=%v
password=%v
socket=%v
`, connParams.Uname, connParams.Pass, connParams.UnixSocket)
	}
 
       // set the character set according to the passed connection parameters
        if connParams.Charset != "" {
                contents += fmt.Sprintf("\ndefault-character-set=%v\n", connParams.Charset)
        }

...
}
```

### Reproduction Steps

The test sample is as follows:
```
create table test_mbytes(
`id` bigint NOT NULL AUTO_INCREMENT primary key,
`name` VARCHAR(20) NOT NULL  COMMENT '층',
`name2` VARCHAR(20)  NOT NULL  COMMENT '我的'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Test Wall Ã¬Â â€¢Ã«Â³Â´'
```
### Binary Version

```sh
v14.0.2
I think other versions will have the same problem.
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

```sh
schemas differ on table xxxx:\n xxx: %v\n differs from:\n xxx: xxx",
```

**Comment by mattlord** [comment]
Hi @huangzhiyong ! 

Thank you for the bug report!

I cannot seem to create that table through a `vtgate`, so I'm unsure if the issue is specific to VReplication or not.
```
mysql> select @@version;
+-------------------------------+
| @@version                     |
+-------------------------------+
| 8.0.31-vitess-16.0.0-SNAPSHOT |
+-------------------------------+
1 row in set (0.00 sec)

mysql> set names utf8mb4;
Query OK, 0 rows affected (0.00 sec)

mysql> create table test_mbytes( `id` bigint NOT NULL AUTO_INCREMENT primary key, `name` NOT NULL VARCHAR(20) COMMENT '층', `name2` NOT NULL VARCHAR(20) COMMENT '我的' )  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Test Wall Ã¬Â â€¢Ã«Â³Â´';
ERROR 1064 (42000): target: commerce.0.primary: vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL VARCHAR(20) COMMENT '층', `name2` NOT NULL VARCHAR(20) COMMENT '我的' at line 1 (errno 1064) (sqlstate 42000) (CallerID: userData1): Sql: "create table test_mbytes( `id` bigint NOT NULL AUTO_INCREMENT primary key, `name` NOT NULL VARCHAR(20) COMMENT '층', `name2` NOT NULL VARCHAR(20)
mysql>
```

Can you please share a full test case that allows you to repeat this? Preferably using the `local/examples` in the repo. I suspect that perhaps you added this table directly in MySQL and from there it's Vitess handling (in this case in `GetSchema` and `CopySchemaShard`) that is off, with the VReplication workflow simply being what exposes the issue in your case. That or I'm missing something(s) that your more complete test case may help to pinpoint.

Please feel free to reach out to me in the [Vitess Slack](https://vitess.io/slack) if you'd rather dive in together there and discuss the issue further.

Thanks again!

**Comment by huangzhiyong** [comment]
@mattlord ,  sorry , the table definition is written wrong.
```
create table test_mbytes(
`id` bigint NOT NULL AUTO_INCREMENT primary key,
`name` VARCHAR(20) NOT NULL  COMMENT '층',
`name2` VARCHAR(20)  NOT NULL  COMMENT '我的'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Test Wall Ã¬Â â€¢Ã«Â³Â´';
```

**Comment by huangzhiyong** [comment]
@mattlord  
1. Create this table, remember to use the character set utf8 or utf8mb4 for mysql connection
2. I just checked the code, and the Movetable is not verified again after ApplySchema
3. please test Reshard again

**Comment by mattlord** [comment]
> 1. Create this table, remember to use the character set utf8 or utf8mb4 for mysql connection

utf8mb4 is used by default in Vitess and MySQL (5.7 and 8.0). Using MySQL's utf8[mb3] character set in Vitess or MySQL would be problematic as it only supports unicode's Basic Multilingual Plane. 

> 2. I just checked the code, and the Movetable is not verified again after ApplySchema

The config file is only used to provide connection information -- socket/hostport, user, password -- and it is used to avoid specifying the password on the command-line. You would not specify character set and collation information there as those have been configured elsewhere. If in your case you require specifying `default-character-set=utf8mb4` there for the client connection then that would indicate that the target  is not using utf8mb4 by default and that will cause a variety of issues.

The schema is verified afterward: https://github.com/vitessio/vitess/blob/main/go/vt/mysqlctl/schema.go#L460-L538 

And as my test case demonstrates, the table is copied correctly. So I don't know what you mean by "MoveTables is not verified again".

> 3. please test Reshard again

I've provided a full copy and paste test case that you or anyone can use to demonstrate that this works as expected. There are countless variables in your specific environment that could explain what you saw. I'm afraid that you'll need to provide a full repeatable test case or much more detail. 

Best Regards
