### ISSUE TITLE
Bug Report: Vitess operator not working

### ISSUE THREAD

**Issue by javaboboApp** [vitessio/vitess#11822]
### Overview of the Issue

Hi there , when I run: 

kubectl apply -f operator.yaml
 
Following next documentation:

https://vitess.io/docs/15.0/get-started/operator/ 

i got next error: 

xxxx@xxxx operator % kubectl get pods
NAME                               READY   STATUS             RESTARTS      AGE
vitess-operator-69f65546b7-zwfzz   0/1     CrashLoopBackOff   5 (97s ago)   4m52s

xxxx@xxxx % kubectl describe pod/vitess-operator-69f65546b7-zwfzz
Name:                 vitess-operator-69f65546b7-zwfzz
Namespace:            default
Priority:             5000
Priority Class Name:  vitess-operator-control-plane
Node:                 k3s-worker-n1-jdm/10.1.0.101
Start Time:           Sun, 27 Nov 2022 11:13:55 +0000
Labels:               app=vitess-operator
                      pod-template-hash=69f65546b7
Annotations:          cni.projectcalico.org/containerID: 7058389a33940ab4d8c5e52c38ed599663ba33ab4c860ca77042589a2130b46f
                      cni.projectcalico.org/podIP: 10.42.168.218/32
                      cni.projectcalico.org/podIPs: 10.42.168.218/32
Status:               Running
IP:                   10.42.168.218
IPs:
  IP:           10.42.168.218
Controlled By:  ReplicaSet/vitess-operator-69f65546b7
Containers:
  vitess-operator:
    Container ID:  containerd://2b11a8dcfc13f381277fecd918d296248c265b21c8d2834ebdb00ccb0d43ea90
    Image:         planetscale/vitess-operator:latest
    Image ID:      docker.io/planetscale/vitess-operator@sha256:679dcf6a76d62e785918a29516206550b2b7b907123d04fb40ea08f23d351561
    Port:          <none>
    Host Port:     <none>
    Command:
      vitess-operator
    Args:
      --logtostderr
      -v=4
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sun, 27 Nov 2022 11:17:08 +0000
      Finished:     Sun, 27 Nov 2022 11:17:10 +0000
    Ready:          False
    Restart Count:  5
    Limits:
      memory:  512Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      WATCH_NAMESPACE:            default (v1:metadata.namespace)
      POD_NAME:                   vitess-operator-69f65546b7-zwfzz (v1:metadata.name)
      PS_OPERATOR_POD_NAMESPACE:  default (v1:metadata.namespace)
      PS_OPERATOR_POD_NAME:       vitess-operator-69f65546b7-zwfzz (v1:metadata.name)
      OPERATOR_NAME:              vitess-operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8fmz2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-8fmz2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m22s                  default-scheduler  Successfully assigned default/vitess-operator-69f65546b7-zwfzz to k3s-worker-n1-jdm
  Normal   Pulled     5m22s                  kubelet            Successfully pulled image "planetscale/vitess-operator:latest" in 754.840848ms
  Normal   Pulled     5m18s                  kubelet            Successfully pulled image "planetscale/vitess-operator:latest" in 846.967816ms
  Normal   Pulled     4m59s                  kubelet            Successfully pulled image "planetscale/vitess-operator:latest" in 766.913075ms
  Normal   Created    4m32s (x4 over 5m22s)  kubelet            Created container vitess-operator
  Normal   Pulled     4m32s                  kubelet            Successfully pulled image "planetscale/vitess-operator:latest" in 782.188265ms
  Normal   Started    4m31s (x4 over 5m22s)  kubelet            Started container vitess-operator
  Normal   Pulling    3m35s (x5 over 5m23s)  kubelet            Pulling image "planetscale/vitess-operator:latest"
  Normal   Pulled     3m35s                  kubelet            Successfully pulled image "planetscale/vitess-operator:latest" in 756.053016ms
  Warning  BackOff    11s (x23 over 5m15s)   kubelet            Back-off restarting failed container

xxxx@xxxx % kubectl logs vitess-operator-69f65546b7-zwfzz 
ERROR: logging before flag.Parse: E1127 11:20:00.056912       1 syslogger.go:149] can't connect to syslog
{"level":"info","ts":1669548000.083683,"logger":"manager","msg":"Operator Version: 2.8.0"}
{"level":"info","ts":1669548000.0838952,"logger":"manager","msg":"Go Version: go1.18.5"}
{"level":"info","ts":1669548000.083987,"logger":"manager","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1669548000.0843978,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1669548000.2948384,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1669548000.294978,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1669548000.5057206,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"0.0.0.0:8383"}
{"level":"info","ts":1669548000.5061855,"logger":"controller-manager","msg":"Registering Components."}
{"level":"info","ts":1669548000.5064497,"logger":"manager","msg":"Starting the manager."}
{"level":"info","ts":1669548000.506726,"msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1669548000.5072103,"logger":"controller.etcdlockserver-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5073316,"logger":"controller.etcdlockserver-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5075397,"logger":"controller.etcdlockserver-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.507658,"logger":"controller.etcdlockserver-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5076735,"logger":"controller.etcdlockserver-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5077257,"logger":"controller.etcdlockserver-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.507891,"logger":"controller.vitessbackupstorage-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5081615,"logger":"controller.vitessbackupstorage-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5083106,"logger":"controller.vitessbackupstorage-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.508339,"logger":"controller.vitessshardreplication-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5086477,"logger":"controller.vitessshardreplication-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5087984,"logger":"controller.vitessshardreplication-controller","msg":"Starting EventSource","source":"channel source: 0xc00076bf40"}
{"level":"info","ts":1669548000.5092773,"logger":"controller.vitessshardreplication-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.5092487,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5096316,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5098898,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5100663,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5093994,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5102715,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5103543,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5104446,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5105162,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5105386,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.51055,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5106575,"logger":"controller.vitesscluster-controller","msg":"Starting EventSource","source":"channel source: 0xc00076bc20"}
{"level":"info","ts":1669548000.5108442,"logger":"controller.vitesscluster-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.508152,"logger":"controller.vitessshard-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5111337,"logger":"controller.vitessshard-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5112839,"logger":"controller.vitessshard-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.510231,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.512036,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5114672,"logger":"controller.vitessshard-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5124052,"logger":"controller.vitessshard-controller","msg":"Starting EventSource","source":"channel source: 0xc00076be50"}
{"level":"info","ts":1669548000.5125961,"logger":"controller.vitessshard-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.5072215,"logger":"controller.vitesskeyspace-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.512638,"logger":"controller.vitesskeyspace-controller","msg":"Starting EventSource","source":"kind source: /, Kind="}
{"level":"info","ts":1669548000.5126538,"logger":"controller.vitesskeyspace-controller","msg":"Starting EventSource","source":"channel source: 0xc00076bd10"}
{"level":"info","ts":1669548000.512672,"logger":"controller.vitesskeyspace-controller","msg":"Starting Controller"}
{"level":"info","ts":1669548000.512255,"logger":"controller.vitesscell-controller","msg":"Starting EventSource","source":"channel source: 0xc00076b9a0"}
{"level":"info","ts":1669548000.5128713,"logger":"controller.vitesscell-controller","msg":"Starting Controller"}
I1127 11:20:01.651493       1 request.go:668] Waited for 1.046543793s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/autoscaling/v2beta2?timeout=32s
{"level":"error","ts":1669548002.2043445,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"PodDisruptionBudget.policy","error":"no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""}
{"level":"error","ts":1669548002.3076897,"logger":"controller.etcdlockserver-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for etcdlockserver-controller caches to sync: no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"info","ts":1669548002.3082128,"logger":"controller.vitessshardreplication-controller","msg":"Starting workers","worker count":10}
{"level":"info","ts":1669548002.3082786,"logger":"controller.vitessshardreplication-controller","msg":"Shutdown signal received, waiting for all workers to finish"}
{"level":"error","ts":1669548002.3100529,"logger":"controller.vitessbackupstorage-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for vitessbackupstorage-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1669548002.3103178,"logger":"controller.vitesskeyspace-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for vitesskeyspace-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1669548002.310422,"logger":"controller.vitesscluster-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for vitesscluster-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1669548002.3105414,"logger":"controller.vitessshard-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for vitessshard-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1669548002.3107815,"logger":"controller.vitesscell-controller","msg":"Could not wait for Cache to sync","error":"failed to wait for vitesscell-controller caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1669548002.311432,"msg":"error received after stop sequence was engaged","error":"failed to wait for vitessbackupstorage-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1669548002.3114793,"msg":"error received after stop sequence was engaged","error":"failed to wait for vitesskeyspace-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1669548002.3114982,"msg":"error received after stop sequence was engaged","error":"failed to wait for vitesscluster-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1669548002.3116162,"msg":"error received after stop sequence was engaged","error":"failed to wait for vitessshard-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"info","ts":1669548002.31167,"logger":"controller.vitessshardreplication-controller","msg":"All workers finished"}
{"level":"error","ts":1669548002.3116286,"msg":"error received after stop sequence was engaged","error":"failed to wait for vitesscell-controller caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1669548002.3119025,"logger":"manager","msg":"Manager exited non-zero","error":"failed to wait for etcdlockserver-controller caches to sync: no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""}

### Reproduction Steps

1. Follow documentation https://vitess.io/docs/15.0/get-started/operator/  
2. Afer run: kubectl apply -f operator.yaml
3. Observer error during the pod creation

### Binary Version

```sh
v15.0
```

### Operating System and Environment details

```sh
I am using heztner cloud solution.
```

**Comment by GuptaManan100** [comment]
@javaboboApp Are you using Kubernetes version `1.25`? It as [open issue](https://github.com/vitessio/vitess/issues/11449) in the Vitess-operator to update it to work with that version. Currently Vtop works with Kubernetes versions up to `1.24` and the reason is that `PodDisruptionBudget` has been deprecated. I see error lines suggesting that is exactly the issue you are seeing - 
```
"failed to wait for etcdlockserver-controller caches to sync: no matches for kind "PodDisruptionBudget" in version "policy/v1beta1""
```

**Comment by javaboboApp** [comment]
Thanks I think this was the issue (I am using version v1.24 ) and it is working ;)
