### ISSUE TITLE
Bug Report: `BUG: tablet identifier should represent single table: TableSet{0,1}`

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#11869]
### Overview of the Issue

When executing a subquery that contains more than a single table (e.g. by joining two tables), the planner generates the following warnings:

```
W1201 19:52:27.315947    7944 SQL_builder.go:79] error in replacing table expression in semtable: Code: INTERNAL
BUG: tablet identifier should represent single table: TableSet{0,1}
```

Note that the planner does not fail - it only outputs the error but then ignores it.

### Reproduction Steps

Use the vschema defined in `go/vt/vtgate/planbuilder/testdata/vschemas/schema.json`.

Run the following query:

```sql
select count(*) from (select 1 from music join user on user.id = music.user_id where music.id = 10) as __subquery_for_count
```

### Binary Version

```sh
Built using commit 22067c7a4e334a7e90850a2119135e6b1ae23279.
```

### Operating System and Environment details

```sh
N/A
```

**Comment by arthurschreiber** [comment]
The error message is generated here: https://github.com/vitessio/vitess/blob/22067c7a4e334a7e90850a2119135e6b1ae23279/go/vt/vtgate/semantics/semantic_state.go#L153-L156

**Comment by deepthi** [comment]
Also what seems to be a typo in the error message: tablet should have been table.

**Comment by deepthi** [comment]
@vitessio/query-serving
