### ISSUE TITLE
Bug Report: table equivalence doesn't work, vtgate doesn't route reference tables across keyspaces

### ISSUE THREAD

**Issue by maxenglander** [vitessio/vitess#11863]
### Overview of the Issue

Reference tables work as follows:

 * A source table exists in an unsharded keyspace.
 * That table can be materialized to all shards of a sharded keyspace.
 * VSchema option `type` `reference` tells VTGate to join the reference table locally.

This all appears to be working as expected. 

What does not appear to be working is [equivalence table](https://vitess.io/docs/15.0/reference/features/schema-routing-rules/#table-equivalence) routing rules. From the documentation it appears that this routing feature was intended to instruct VTGate where to route queries for tables that have both a source table in one keyspace and a materialized reference reference table in another. 

Attempting to use equivalence tables always results in this error: https://github.com/vitessio/vitess/blob/7651c429ef4628cc0e29b4f30a0afd06982c57d7/go/vt/vtgate/vindexes/vschema.go#L483

A bit more background:
 * [Here is a YouTube demo](https://www.youtube.com/watch?v=E6H4bgJ3Z6c&amp;t=1451s) of VTGate routing a query for a materialized table to different keyspaces.
 * It looks like the ability to route a table to targets in different keyspaces [was introduced here](https://github.com/vitessio/vitess/pull/4833).
 * And looks like [it was reverted here](https://github.com/vitessio/vitess/pull/6531).

### Reproduction Steps

1. Deploy a `vschema` in the `src` keyspace.
   ```
   {
     "sharded": false,
     "tables": {
       "subjects": {}
     }
   }
   ```
2. With the following `schema`:
   ```
   DROP TABLE IF EXISTS `subjects`;
   CREATE TABLE `subjects` (
     `id` bigint NOT NULL,
     `name` varchar(255) DEFAULT NULL,
     PRIMARY KEY (`id`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

   INSERT INTO `subjects` VALUES (1,'math'),(2,'history'),(3,'english'),(4,'gym');
   ```
3. Deploy a `vschema` in the `dst` keyspace:
   ```
   {
     "sharded": true,
     "tables": {
       "subjects": {
         "type": "reference"
       }
     }
   }
   ```
4. Materialize from `src` to `dst`:
   ```
   vtctlclient --server 127.0.0.1:15999 Materialize -- '{"workflow": "copy_subjects_1", "source_keyspace": "src", "target_keyspace": "dst", "table_settings": [{"target_table": "subjects", "source_expression": "select * from subjects","create_ddl":"copy"}]}'
   ```
5. Attempt to query from or insert into `subjects` without qualifying the keyspace results in this error: https://github.com/vitessio/vitess/blob/7651c429ef4628cc0e29b4f30a0afd06982c57d7/go/vt/vtgate/vindexes/vschema.go#L483

### Binary Version

```sh
./bin/vtgate --version
Version: 16.0.0-SNAPSHOT (Git revision aa8b5034ab71b9000460cfc3b1042c2f51b1eaf1 branch 'main') built on Mon Nov 28 15:03:17 EST 2022 by maxenglander@planetscale.local using go1.19.3 darwin/arm64
```
```


### Operating System and Environment details

```sh
* macOS Monterey 12.6.1
* MacBook Air (M1, 2020)
```

**Comment by maxenglander** [comment]
Some useful bits from conversations that have happened elsewhere:

@harshit-gangal said
> I think we should solve this at vitess level to introduce things like original table and materialized reference table. so the planner can select the right keyspace for sending the query.

@aquarapid said
> Or just teach routing about writes vs reads

@deepthi said
> routing rules are supposed to be temporary and not permanent
> we can do what Harshit is suggesting but no guarantee that we won't run into some other issue next

**Comment by maxenglander** [comment]
Also relevant https://stackoverflow.com/questions/68181633/vitess-table-equivalence-configuration

**Comment by rsajwani** [comment]
tagging @vitessio/query-serving

**Comment by harshit-gangal** [comment]
Table Equivalence was removed in 8.0.
It was an experimental feature at that time. 
We should remove it from all our current documents.

**Comment by harshit-gangal** [comment]
Closing this as we have an RFC now for re-introducing a similar thing which is feature-focused for reference table with materialization.
