### ISSUE TITLE
Question: Error when I run vtctlclient --logtostderr  BackupShard 

### ISSUE THREAD

**Issue by javaboboApp** [vitessio/vitess#11883]
### Question

Hi , I am getting an error after running  **vtctlclient --logtostderr  BackupShard  apidbtest/-** 

BackupShard Error: rpc error: code = unknown desc = no tablet available for backup
E1205 18:37:30.752038    1861 main.go:105] remote error: rpc error: code = Unknown desc = no tablet available for backup

I am using an external nfs server also I have also run some tests again this **nfs server** using a pvc,pv and a test pod and it is working as expected (kubernetes is able to mount the unit and use it).

I do know not why I am getting this error. I have tried to search for a reason, but nothing similar happens in other issues.

**Comment by GuptaManan100** [comment]
Could you show us the list of all the tablets with a `GetTablets` command? Which version of Vitess are you on?

**Comment by javaboboApp** [comment]
sure: 

 vtctlclient GetTablet zone1-1205982007
Handling connection for 15999
{
  "alias": {
    "cell": "zone1",
    "uid": 1205982007
  },
  "hostname": "10.42.208.138",
  "port_map": {
    "grpc": 15999,
    "vt": 15000
  },
  "keyspace": "apidbtest3",
  "shard": "-",
  "key_range": {
    "start": "",
    "end": ""
  },
  "type": 2,
  "db_name_override": "vt_apidbtest3",
  "tags": {},
  "mysql_hostname": "10.42.208.138",
  "mysql_port": 3306,
  "primary_term_start_time": null,
  "db_server_version": "5.7.31",
  "default_conn_collation": 45
}

The vitess version that I am using is: 

vtctlclient --version
**Version: 15.0.1** (Git revision  branch '') built on Wed Nov 30 06:18:47 UTC 2022 by brew@HMBRW-A-001-M1-005.local using go1.19.3 darwin/arm64

**Comment by frouioui** [comment]
The output you just pasted shows the tablet belongs to `apidbtest3`, but the command you ran uses `apidbtest`.
