### ISSUE TITLE
Bug Report: `SELECT *` expansion only considers subquery in column list on unsharded queries

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#11880]
### Overview of the Issue

@yoheimuta encountered a bug where a subquery in the columns list of an inner query would be the only column expanded by the `SELECT *` expression of the outer query. This bug only exists in the Gen4 planner.

### Reproduction Steps

Using the vschema defined at `go/vt/vtexplain/testdata/test-vschema.json`:

```sql
SELECT * FROM (
  SELECT *,
  (SELECT id FROM unsharded_b LIMIT 1) AS unsharded_b_id
  FROM unsharded_a LIMIT 10
) as results
```

V3 plan:

```json
{
  "QueryType": "SELECT",
  "Original": "SELECT * FROM (SELECT *, (SELECT id FROM unsharded_b LIMIT 1) AS unsharded_b_id FROM unsharded_a LIMIT 10) as results",
  "Instructions": {
    "OperatorType": "Route",
    "Variant": "Unsharded",
    "Keyspace": {
      "Name": "main",
      "Sharded": false
    },
    "FieldQuery": "select * from (select *, (select id from unsharded_b where 1 != 1) as unsharded_b_id from unsharded_a where 1 != 1) as results where 1 != 1",
    "Query": "select * from (select *, (select id from unsharded_b limit 1) as unsharded_b_id from unsharded_a limit 10) as results",
    "Table": "unsharded_a"
  }
}
```

Gen4 plan:

```json
{
  "QueryType": "SELECT",
  "Original": "SELECT * FROM (SELECT *, (SELECT id FROM unsharded_b LIMIT 1) AS unsharded_b_id FROM unsharded_a LIMIT 10) as results",
  "Instructions": {
    "OperatorType": "Route",
    "Variant": "Unsharded",
    "Keyspace": {
      "Name": "main",
      "Sharded": false
    },
    "FieldQuery": "select results.unsharded_b_id from (select *, (select id from unsharded_b where 1 != 1) as unsharded_b_id from unsharded_a where 1 != 1) as results where 1 != 1",
    "Query": "select results.unsharded_b_id from (select *, (select id from unsharded_b limit 1) as unsharded_b_id from unsharded_a limit 10) as results",
    "Table": "unsharded_a, unsharded_b"
  },
  "TablesUsed": [
    "main.unsharded_a",
    "main.unsharded_b"
  ]
}
```

### Binary Version

```sh
Version: 22067c7a4e334a7e90850a2119135e6b1ae23279
```

### Operating System and Environment details

```sh
N/A
```

**Comment by arthurschreiber** [comment]
I traced this down to the `expandTableColumns` function in the `earlyRewriter` type, specifically these lines here:

https://github.com/vitessio/vitess/blob/22067c7a4e334a7e90850a2119135e6b1ae23279/go/vt/vtgate/semantics/early_rewriter.go#L355-L358

The early `expandTableColumns` function is called for the `StarExpr` of the derived `results` table. The `authoritative` function on `DerivedTable` is implemented to always return true, so the code ends up trying to perform a star expansion for the derived table, but when iterating over the columns of the derived table using `getColumns`, only the columns directly defined on it (in this case `unsharded_b_id`) are returned, ignoring the other columns from `unsharded_a`.

@systay I'm not 100% sure about the fix here, but maybe `authoritative` on a `DerivedTable` should only be true if any of the dervied table's dependencies is authoritative? 🤔

**Comment by systay** [comment]
Great stuff @arthurschreiber. I'll take a look today. 🙇

**Comment by systay** [comment]
> Great stuff @arthurschreiber. I'll take a look today. 🙇

That was a really long day... 😞
