### ISSUE TITLE
Bug Report: v12 and v13 releases for tabletgateway don't perform alias nil check in tx_conn.go queryService function

### ISSUE THREAD

**Issue by pbibra** [vitessio/vitess#11904]
### Overview of the Issue

discussion here: https://vitess.slack.com/archives/C0PQY0PTK/p1670351761839309

When performing COMMITs using `tabletgateway`, we run into the following error: 

```
tablet: <nil> is either down or nonexistent"
```

This nil check does not exist in v12 and v13 releases and should probably be backported: https://github.com/slackhq/vitess/commit/18234019398bac30dfe4040f529cb5a7fe68bc00#diff-33ceb6465a70a93307b16c53d48aa46ec05feabbfa39f5de52522f5eb8f52835R277

### Reproduction Steps

1. Use Vitess 12 
2. Set `gateway_implementation` to `tabletgateway`
3. Send a `COMMIT` transaction to a VTGate
4. Should get the `tablet: <nil> is either down or nonexistent"` error. The `queryService` function in `tx_conn.go` tries to fetch `QueryServiceByAlias()->TabletConnection()` which is a function only implemented by `TabletGateway` and the new `healthcheck` respectively.

### Binary Version

```sh
v12.0.5
```

### Operating System and Environment details

```sh
n/a
```

**Comment by systay** [comment]
v12 and v13 are no longer supported
