### ISSUE TITLE
Update the MySQL version used in the Docker lite images

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#11948]
The MySQL version we are using in our `vitess/lite` images is pretty old (`8.0.23`) we should upgrade it to a more recent and stable version: `8.0.31`.

- [ ] Find the implications of this change. Run some upgrade/downgrade tests between v15 and v16 on docker. and also with the operator.
- [ ] Use those findings to warns users in the release notes.
- [ ] We also need to change the default docker image we publish from 5.7 to 8.0.

**Comment by deepthi** [comment]
We also need to change the default docker image we publish from 5.7 to 8.0.

**Comment by frouioui** [comment]
Linking https://github.com/vitessio/vitess/issues/7812 to this issue as the enhancement proposed by the two issues is the same.
