### ISSUE TITLE
Delete deprecated vtctl flags

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#11973]
- [ ] `vtctl_healthcheck_topology_refresh`
- [ ] `vtctl_healthcheck_retry_delay`
- [ ] `vtctl_healthcheck_timeout`

**Comment by frouioui** [comment]
@ajm188 seems like this can be closed since #11974 was merged. Was there anything else pending before closing this issue?

**Comment by ajm188** [comment]
No, we need to delete them. #11974 was just the deprecation notice (see https://github.com/vitessio/vitess/blob/721d5813cdc610bbe8afdce9f0c1acb037d9ae96/go/vt/vtctl/vtctl.go#L148 for example)
