### ISSUE TITLE
Bug Report: Unexplainable `vtexplain` CI failures in PR

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#11995]
No pun intended, I'm having some unexplainable `vitess.io/vitess/go/vt/vtexplain` unit test/CI failures in the following PR: https://github.com/vitessio/vitess/pull/11972. These failure reproduce on GitHub CI as well as on a local box.

The changes in the PR relate to the tablet throttler only, and I cannot see how they might affect the `vitess.io/vitess/go/vt/vtexplain` tests.

Example failure: https://github.com/vitessio/vitess/actions/runs/3723536776/jobs/6318087809

To reproduce, please checkout [`planetscale:tablegc-operate-state`](https://github.com/planetscale/vitess/tree/tablegc-operate-state) and run `make unit_test`.

**Comment by shlomi-noach** [comment]
Forgot to tag @vitessio/query-serving for this bug report.

**Comment by systay** [comment]
> Resolved by [398d022](https://github.com/vitessio/vitess/commit/398d022cc97b41d6f48b61fc0777c8579c144fba)

You are linking to a commit sha that doesn't seem to exist in any branch. Which PR did that change belong to?

**Comment by shlomi-noach** [comment]
The commit is https://github.com/vitessio/vitess/pull/11972/commits/398d022cc97b41d6f48b61fc0777c8579c144fba, and it is unmerged yet

**Comment by shlomi-noach** [comment]
grrrr. I see the problem. GitHub the website redirect that commit into a "not found" page. At any case, it's part of https://github.com/vitessio/vitess/pull/11972/commits
