### ISSUE TITLE
Bug Report: gen4 planner causes 'Row count exceeded 10000' errors

### ISSUE THREAD

**Issue by zengmin-wish** [vitessio/vitess#12037]
### Overview of the Issue

Hi Vitess experts, we are running v13 and trying to upgrade to v15. We noticed an issue that seems to be a bug of the ‘gen4’ planner. Adding a hint to use v3 planner works. Our query is like:
```mysql
SELECT t2.*
FROM table1 AS t1
  INNER JOIN table2 AS t2
    ON t1.table2_id = t2.id
WHERE t1.id IN (1234, 5678)
```
It works fine in v13, but in v15, it fails because of the ‘Row count exceeded 10000’ error. The above query would return just two rows.  Since table1 and table2 are sharded, so it looks like v3 planner was able to find the 2 rows using the where clause before doing the inner join, while gen4 seems to be doing the inner join first thus too many rows?  

### Reproduction Steps

 Below are the vindex info for the two tables in case it’s relevant.
```
  "vindexes": {
    "table1_keyspace_idx": {
      "type": "consistent_lookup_unique",
      "params": {
        "from": "table2_id",
        "ignore_nulls": "true",
        "table": "table1_keyspace_idx",
        "to": "keyspace_id"
      },
      "owner": "table1"
    },    
...
    "table1": {
      "columnVindexes": [
        {
          "column": "id",
          "name": "hash"
        },
        {
          "column": "table2_id",
          "name": "table1_keyspace_idx"
        }
      ],
...    
     "table2": {
      "columnVindexes": [
        {
          "column": "some_id",
          "name": "xxhash"
        }
      ],
      "autoIncrement": {
        "column": "id",
        "sequence": "wish.table2_seq"
      }
    },    
    
```

### Binary Version

```sh
v15.0.2
```

### Operating System and Environment details

```sh
root@app05dev-temporal-0-repl-0:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@app05dev-temporal-0-repl-0:/# uname -sr
Linux 5.13.0-1031-aws
root@app05dev-temporal-0-repl-0:/# uname -m
x86_64
```

**Comment by GuptaManan100** [comment]
There are two alternate plans for the gen4 planner to choose from. One of which gives the rows exceeded error and the other works fine, but its very hard to tell which would succeed during planning phase. Gen4 picks the first one. To force it to do the join in the specified order of tables in the query you can use the comment directive `/*vt+ PLANNER=left2right */`. This will make your query work.
So your query will look like 
```SQL
SELECT /*vt+ PLANNER=left2right */ t2.id, t2.some_id FROM table1 AS t1 INNER JOIN table2 AS t2 ON t1.table2_id = t2.id WHERE t1.id IN (1234, 5678)
```

We would also recommend adding a secondary vindex to your `t2.id` column since it is going to help filter the rows faster in the join.

The choice between the two alternative plans can be improved by estimating the cost of the number of rows to be read in table. Currently we don't have that functionality in Gen4 but we plan to add something for it this year.

**Comment by GuptaManan100** [comment]
If you add a secondary vindex to table_2 id column as follows - 

```
vindex - 
"table2_id_idx": {
          "type": "consistent_lookup_unique",
          "params": {
            "from": "id",
            "ignore_nulls": "true",
            "table": "table2_id_idx",
            "to": "keyspace_id"
          },
          "owner": "table2"
        }
tables -
"table2": {
          "columnVindexes": [
            {
              "column": "some_id",
              "name": "hash"
            },
            {
              "column": "id",
              "name": "table2_id_idx"
            }
          ]
        },
        "table2_id_idx": {
          "columnVindexes": [
            {
              "column": "id",
              "name": "hash"
            }
          ]
        },
```

You'll have a plan which is faster than both the alternates previously and you won't need the comment directive either.

**Comment by GuptaManan100** [comment]
We are going to close this for now. Please reopen if this doesn't solve your problem.
