### ISSUE TITLE
Bug Report: Date math produces syntax error

### ISSUE THREAD

**Issue by olyazavr** [vitessio/vitess#12076]
### Overview of the Issue

Vitess 14 doesn't support some set of date math queries, for example: `select '2020-01-01' + interval month(DATE_SUB(FROM_UNIXTIME(1234), interval 1 month))-1 month` is a valid mysql query, but produces a syntax error when run against Vitess 14

Workaround is to use parens: `select '2020-01-01' + interval (month(DATE_SUB(FROM_UNIXTIME(1234), interval 1 month))-1) month` but original query shouldn't fail like this

### Reproduction Steps

Run `select '2020-01-01' + interval month(DATE_SUB(FROM_UNIXTIME(1234), interval 1 month))-1 month`

Another example: `select DATE_ADD(MIN(FROM_UNIXTIME(1673444922)),interval -DAYOFWEEK(MIN(FROM_UNIXTIME(1673444922)))+1 DAY)`

### Binary Version

```sh
Vitess 14.04
```

### Operating System and Environment details

```sh
Currently being reproduced with java unit tests against vtcombo
```

### Log Fragments

```sh
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLSyntaxErrorException: message: "syntax error at position 120"
code: INVALID_ARGUMENT
 [statement:"select /*+ MAX_EXECUTION_TIME(30000) */ '2020-01-01' + interval month(DATE_SUB(FROM_UNIXTIME(1234), interval 1 month))-1 month", arguments:{positional:{}, named:{}, finder:[]}]
```

```
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.SQLSyntaxErrorException: message: "syntax error at position 133"
code: INVALID_ARGUMENT
 [statement:"select /*+ MAX_EXECUTION_TIME(30000) */ DATE_ADD(MIN(FROM_UNIXTIME(1673444922)),interval -DAYOFWEEK(MIN(FROM_UNIXTIME(1673444922)))+1 DAY)", arguments:{positional:{}, named:{}, finder:[]}]
```
```

**Comment by GuptaManan100** [comment]
I checked and this is a failure even on `main`.
