### ISSUE TITLE
Bug Report: Vreplication can stop suddenly after an error instead of retrying

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#12101]
### Overview of the Issue

We've been running a `CreateLookupVindex` in a sharded keyspace, and ran into an issue where on one of the shards, multiple (but not all) of the workflows stopped unexpectedly, and were not retried.

I believe this is due to a bug in the `lastWorkflowError` functionality in the `vreplication` controller code.

When a vreplication controller encounters an error, the error is recorded using [`ct.lastWorkflowError.record(err)`](https://github.com/vitessio/vitess/blob/ece6501975604ef5d0be3ab256145047e13d9c00/go/vt/vttablet/tabletmanager/vreplication/controller.go#L270-L271).

If the error is seen as recoverable, and [`ct.lastWorkflowError.shouldRetry()`](https://github.com/vitessio/vitess/blob/ece6501975604ef5d0be3ab256145047e13d9c00/go/vt/vttablet/tabletmanager/vreplication/controller.go#L273) signals that the vreplication can be retried, the controller will attempt to restart the vreplication workflow.

The idea behind `lastWorkflowError` is to record errors from the vreplication call, and allow restarting vreplication again unless vreplication continuously fails with the same error for a duration longer than specified by the `vreplication_max_time_to_retry_on_error` flag.

Unfortunately, I believe this check is implemented incorrectly. [`vr.Replicate(ctx)`](https://github.com/vitessio/vitess/blob/ece6501975604ef5d0be3ab256145047e13d9c00/go/vt/vttablet/tabletmanager/vreplication/controller.go#L269) is a potentially long running call, and errors are only recorded (or cleared) if `vr.Replicate` returns.

We've seen the following happen:
* `vr.Replicate(ctx)` fails with some error
* the error is recorded via `ct.lastWorkflowError.record(err)`
* the error is seen as recoverable (`isUnrecoverableError(err)` returns false) and `ct.lastWorkflowError.shouldRetry()` returns true as the error happened for the first time just now
* Vreplication is retried and restarted successfully
* ... a long time passes (hours / days / weeks)
* `vr.Replicate(ctx)` fails with the same error as before
* the error is passed to `ct.lastWorkflowError.record(err)`, but as it's the same error, [no new timestamp is recorded](https://github.com/vitessio/vitess/blob/ece6501975604ef5d0be3ab256145047e13d9c00/go/vt/vttablet/tabletmanager/vreplication/last_error.go#L55-L59)
* the error is seen as recoverable (`isUnrecoverableError(err)` returns false) but `ct.lastWorkflowError.shouldRetry()` now returns false, as the "first" occurence of this error happened a long time ago (exceeding `vreplication_max_time_to_retry_on_error`)
* vreplication is marked as errored and not retried

I believe the `lastError` handling needs to be made more robust. Maybe we should also record the last time an error was seen, and clear the `firstSeen` timestamp if the duration from the previous occurrence is larger than `vreplication_max_time_to_retry_on_error`?

### Reproduction Steps

n/a

### Binary Version

```sh
n/a
```

### Operating System and Environment details

```sh
n/a
```

**Comment by rohit-nayak-ps** [comment]
> I believe the lastError handling needs to be made more robust. Maybe we should also record the last time an error was seen, and clear the firstSeen timestamp if the duration from the previous occurrence is larger than vreplication_max_time_to_retry_on_error?

Agree. We will work on this asap and backport to v15 as well. I wanted to check: are you blocked by this error at the moment or were you able to work around this with a manual `Workflow Start` ?

**Comment by arthurschreiber** [comment]
We simply restarted the workflow.

**Comment by mattlord** [comment]
Fixed in https://github.com/vitessio/vitess/pull/12114
