### ISSUE TITLE
Bug Report: Syntax error near 'AS'

### ISSUE THREAD

**Issue by ddelange** [vitessio/vitess#12122]
### Overview of the Issue

Hi 👋

This query was constructed by our Django backend:

```mysql
mysql> INSERT INTO `profiles_profile` (`companyProfileId`, `lastModified`, `content`) VALUES ('bW9jMDAwNzAwLmNvbQ==', '2022-12-01 20:16:34.944717', _binary '123') AS new ON DUPLICATE KEY UPDATE `lastModified` = new.`lastModified`, `content` = new.`content`;
ERROR 1105 (HY000): syntax error at position 159 near 'AS'
```

When I remove everything starting with `AS`, we're green:
```mysql
mysql> INSERT INTO `profiles_profile` (`companyProfileId`, `lastModified`, `content`) VALUES ('bW9jMDAwNzAwLmNvbQ==', '2022-12-01 20:16:34.944717', _binary '123');
Query OK, 1 row affected (0.08 sec)
```

Here is the [source code](https://github.com/django/django/blob/4.1.5/django/db/backends/mysql/operations.py#L444-L450) that creates the query part starting with `AS`, with a comment:
> The use of VALUES() is deprecated in MySQL 8.0.20+. Instead, use aliases for the new row and its columns available in MySQL 8.0.19+.

From what I can tell, this query should be totally fine 🤔

### Reproduction Steps

This is a fresh db, schema populated by django (based on your docs https://github.com/vitessio/vitess/blob/v15.0.2/support/django/). Migrations ran succesfully, so far so good.

I don't have a MWE for you right now, but maybe from eyeballing the query above, this is something you have encountered before?

### Binary Version

this is hosted by planetscale.com

```
mysql> SHOW VARIABLES LIKE "%version%";
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| admin_tls_version        | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| immediate_server_version | 999999                        |
| innodb_version           | 8.0.23                        |
| original_server_version  | 999999                        |
| protocol_version         | 10                            |
| slave_type_conversions   |                               |
| tls_version              | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| version                  | 8.0.21-Vitess                 |
| version_comment          |                               |
| version_compile_machine  | x86_64                        |
| version_compile_os       | Linux                         |
| version_compile_zlib     | 1.2.11                        |
+--------------------------+-------------------------------+
12 rows in set (0.13 sec)
```

### Operating System and Environment details

mac x86_64, cpython 3.11, mysql client built from source yesterday using homebrew. occurs on our k8s cluster (arm64 debian) as well with mysql client from apt. the python bindings are served by https://pypi.org/project/mysqlclient/

### Log Fragments

```sh
see the above, I don't have access to db logs afaik
```

**Comment by harshit-gangal** [comment]
This is a new syntax that got added in MySQL, Vitess has to enhance the parser and planner to understand the new syntax.
