### ISSUE TITLE
Bug Report: vitessdriver does not correctly INSERT NULL []byte values

### ISSUE THREAD

**Issue by simon-engledew** [vitessio/vitess#12121]
### Overview of the Issue

Using the Golang vitess database driver (`vitess.io/vitess/go/vt/vitessdriver`) when attempting to insert a row with a `[]byte(nil)` value, `vendor/vitess.io/vitess/go/sqltypes/bind_variables.go` incorrectly inserts the value as an empty string. `''`.

This can be fixed by modifying `bind_variables.go` slightly:

https://github.com/simon-engledew/vitess/blob/6beaa908a547d0b5b39262cfa3a216f6f792f414/go/sqltypes/bind_variables.go#L144-L153

### Reproduction Steps

Create a table with a `VARBINARY DEFAULT NULL`.

Set up a [connection in go](https://pkg.go.dev/vitess.io/vitess/go/vt/vitessdriver) and run:

```
db.Exec("INSERT INTO some_table VALUES (?)", []byte(nil))
```

The value in the database will be `''` instead of `NULL`.

### Binary Version

From go.mod:

```sh
vitess.io/vitess v0.15.2
```

### Operating System and Environment details

```sh
Go version 1.19
```

**Comment by harshit-gangal** [comment]
Could you create an upstream PR for this change with a unit test?

**Comment by simon-engledew** [comment]
Sure! Here is a unit test and a fix:

https://github.com/vitessio/vitess/pull/12363

**Comment by simon-engledew** [comment]
It looks like this behaviour is intentional! 🙇‍♂️ Thanks for looking into the issue. 😂
