### ISSUE TITLE
Question: Can we change -h from 127.0.0.1 to something else?

### ISSUE THREAD

**Issue by reddyreddy73** [vitessio/vitess#12127]
### Question

I wanted to change my MySQL -h 127.0.01 to something else like MySQL -h 10.16.1.1. Can we do that? I am installing via Kubernetes on my server. Can anyone please tell me how to do that if possible?

**Comment by mattlord** [comment]
We're discussing this in the [Vitess Slack](https://vitess.io/slack) so closing the issue.
