### ISSUE TITLE
Feature Request: Show rows_copied in `workflow show` output 

### ISSUE THREAD

**Issue by Phanatic** [vitessio/vitess#12203]
### Feature Description

vreplication currently tracks how many rows have been copied from the source in the `_vt.vreplication` table as the `rows_copied` column. But this value is not part of the `workflow show` output when run with a MoveTables workflow name.

The query and the type representing the output seem to be missing the `rows_copied` property 

Query : https://github.com/vitessio/vitess/blob/4f5ab229213de475cb4d46f524f566ebf89167fa/go/vt/wrangler/vexec.go#L558-L576
Type : 
https://github.com/vitessio/vitess/blob/4f5ab229213de475cb4d46f524f566ebf89167fa/go/vt/wrangler/vexec.go#L403-L443

### Use Case(s)

I'd like to see the `rows_copied` column in the `workflow <id> show` command's output so I can see how many rows have been copied from the source.

**Comment by mattlord** [comment]
Fixed by: https://github.com/vitessio/vitess/pull/12231
