### ISSUE TITLE
Bug Report: outer join query failed with "unknown plan type for DISTINCT *planbuilder.filter"

### ISSUE THREAD

**Issue by tanjinx** [vitessio/vitess#12259]
### Overview of the Issue

An outer join query used to work in version 12 but failed in version 13, 

```sql
create table test_tbl (c1 int, c2 int, c3 int, c4 int);
select distinct
   t1.c1, t1.c2, t1.c3, t1.c4
from test_tbl t1
inner join test_tbl t2
on (t1.c2= t2.c2 and t1.c3 = t2.c3 and t2.c4 >= 10) 
left join test_tbl t3
on (t1.c2 = t3.c2 and t1.c3 = t3.c3 and t3.c4 < 10 and t1.c1 < t3.c1)
where t1.c2 = 10
order by t1.c4 desc, t1.c1 desc limit 10;
```

use the default query planner version, but underneath, we forced to the gen4 planner for outer join queries due to potential correctness problems.

The problem is gone in version 14 (v14.0.4) and likely fixed by:
- https://github.com/vitessio/vitess/pull/11422
- https://github.com/vitessio/vitess/pull/11786

### Reproduction Steps

create table test_tbl (c1 int, c2 int, c3 int, c4 int);
select distinct
   t1.c1, t1.c2, t1.c3, t1.c4
from test_tbl t1
inner join test_tbl t2
on (t1.c2= t2.c2 and t1.c3 = t2.c3 and t2.c4 >= 10) 
left join test_tbl t3
on (t1.c2 = t3.c2 and t1.c3 = t3.c3 and t3.c4 < 10 and t1.c1 < t3.c1)
where t3.c1 is NULL and t1.c2 = 10
order by t1.c4 desc, t1.c1 desc limit 10;

### Binary Version

```sh
tag v13.0.3
```

### Operating System and Environment details

```sh
linuxamd64
```

**Comment by systay** [comment]
Release 14 is the oldest supported version of Vitess. We won't do a backport to earlier versions of this fix
