### ISSUE TITLE
Bug Report: "npm: command not found" when following Vitess 14 Local Install.

### ISSUE THREAD

**Issue by jfg956** [vitessio/vitess#12310]
### Overview of the Issue

When running "Local Install" on CentOs 8 {1}...

{1}: https://vitess.io/docs/14.0/get-started/local/

...I am getting "npm: command not found" when running `101_initial_cluster.sh`:
```
[...]
vtgate is up!
Access vtgate at http://<my hostname>:15001/debug/status
vtadmin-api is running!
  - API: http://localhost:14200
  - Logs: /home/$USER/my-vitess-example/vtdataroot/tmp/vtadmin-api.out
  - PID: 5455

./scripts/vtadmin-up.sh: line 38: npm: command not found
./scripts/vtadmin-up.sh: line 40: npm: command not found
vtadmin-web is running!
[...]
```

### Reproduction Steps

```
./scripts/vtadmin-up.sh: line 38: npm: command not found
./scripts/vtadmin-up.sh: line 40: npm: command not found
```

### Binary Version

```sh
vitess-14.0.4-7fafc94
```

### Operating System and Environment details

```sh
$ cat /etc/centos-release
CentOS Stream release 8
```

**Comment by jfg956** [comment]
Running `sudo yum install npm` solved the problem, but this is missing from the doc.

I might submit a PR to fix this.  And at the same time, I might fix a few references to v13 in the v14 doc.

However, after installing npm, I still have an `EACCES` error, not sure how to fix this one yet.
```
Waiting for vtgate to be up...
vtgate is up!
Access vtgate at http://na1-jgagne-vitess-test06.iad03.hubspot-networks.net:15001/debug/status
vtadmin-api is running!
  - API: http://localhost:14200
  - Logs: /home/jgagne/my-vitess-example/vtdataroot/tmp/vtadmin-api.out
  - PID: 17602

Error: EACCES: permission denied, mkdir '/home/web'
Error: EACCES: permission denied, mkdir '/home/web'
vtadmin-web is running!
  - Browser: http://localhost:14201
  - Logs: /home/jgagne/my-vitess-example/vtdataroot/tmp/vtadmin-web.out
  - PID: 17675
```

**Comment by mattlord** [comment]
Hi @jfg956 !

You're right about the `npm` issue, but the examples do not manage dependencies today as installing a missing package will differ from system to system. If you have some ideas though, they're most welcome. 

Regarding the web directory issue... that's where `vtadmin-web` (a node.js app) has its files. This is a bug in the v14 docs as the step to copy those files is not there:
  - https://vitess.io/docs/14.0/get-started/local/#start-a-single-keyspace-cluster
  - https://vitess.io/docs/15.0/get-started/local/#start-a-single-keyspace-cluster

Specifically this step:
```
cp -r /usr/local/vitess/web ~/my-vitess-example
```

I can open a website PR quickly to add that. Or if you're interested, I can also help you through that process if you're interested. Just let me know. 

Thank you for reporting this!

**Comment by jfg956** [comment]
Hi Matt,

> You're right about the npm issue, but the examples do not manage dependencies today as installing a missing package will differ from system to system. If you have some ideas though, they're most welcome.

There are already instructions to install Vitess on Ubuntu, Debian and Yum, IMHO it would not be super complicated to add npm in these.  But in the end, it is your doc, and the problem is not that big as quite easy to fix, so your call.

> I can open a website PR quickly to add that.

I will not have time to work more on this, so you fixing this with a PR would be appreciated.

Cheers, J-F

**Comment by jfg956** [comment]
Manan, you set this as closed in a PR, but when looking at this PR, I only see modification to docker files, and this report is for the local install.  Also, in {1}, I still do not see any references to npm nor "web".  Finally, {1} still contains reference to Vitess version 13 while it is the doc for v14.

{1}: https://vitess.io/docs/14.0/get-started/local/

**Comment by mattlord** [comment]
@jfg956 you're right, it's not complicated. Just takes some time. It's an easy way to contribute, which is why I was asking if you were. I'll open a PR that adds `npm`, e.g.:
```
Install MySQL and etcd [#](https://vitess.io/docs/14.0/get-started/local/#install-mysql-and-etcd)

Vitess supports the databases listed [here](https://vitess.io/docs/14.0/overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:

# Ubuntu based
sudo apt install -y mysql-server etcd curl

# Debian
sudo apt install -y default-mysql-server default-mysql-client etcd curl

# Yum based
sudo yum -y localinstall https://dev.mysql.com/get/mysql80-community-release-el8-3.noarch.rpm
sudo yum -y install mysql-community-server etcd curl
```

Becomes:
```
Install MySQL and etcd [#](https://vitess.io/docs/14.0/get-started/local/#install-mysql-and-etcd)

Vitess supports the databases listed [here](https://vitess.io/docs/14.0/overview/supported-databases/). We recommend MySQL 8.0 if your installation method provides that option:

# Ubuntu based
sudo apt install -y mysql-server etcd curl npm

# Debian
sudo apt install -y default-mysql-server default-mysql-client etcd curl npm

# Yum based
sudo yum -y localinstall https://dev.mysql.com/get/mysql80-community-release-el8-3.noarch.rpm
sudo yum -y install mysql-community-server etcd curl npm
```

I can't say that the version of npm provided will meet the requirements of vtadmin, but it's a step in the right direction.

**Comment by mattlord** [comment]
Just FYI, discussed this with the vtadmin team and I think we're going to instead try and install the dependency via `nvm` directly in the script. Thanks again for bringing this to our attention @jfg956!

**Comment by frouioui** [comment]
Closing this since #12467 is merged. @jfg956 feel free to re-open if this is incorrect.
