### ISSUE TITLE
Bug Report: regression, VReplication errors lost their type, converted to errorString

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#12326]
### Overview of the Issue

In Vreplication, the function `isUnrecoverableError()` needs to identify specific errors from which it is impossible to recover. This is done by casting the error to `SqlErr` and checking for specific SQL code.

https://github.com/vitessio/vitess/blob/c4292b7c560766275e22be8105cf95d9d5afe7b8/go/vt/vttablet/tabletmanager/vreplication/utils.go#L123-L135

However, at this time, we find the error cannot be casted to `SqlErr` and is in fact `errorString`, which is the type you get when you e.g. `return fmt.Errorf("task error: %s", err)`

We need to retrace the changes and ensure to use proper wrapping (such as `vterrors.Wrapf`) as well as add unwrapping functionality for `isUnrecoverableError()` to use. 

The impact of this issue is that VReplication does not bail out on clearly terminal scenarios, and instead keeps on retrying until some timeout (default `10min`). This is still logically correct. But in CI we don't have that much time to spend.

### Reproduction Steps

-

### Binary Version

```sh
-
```

### Operating System and Environment details

```sh
-
```

**Comment by shlomi-noach** [comment]
The regression is caused by https://github.com/vitessio/vitess/pull/10828, where a bunch of `fmt.Errorf(...)` wrapping were introduced. e.g.:

https://github.com/vitessio/vitess/pull/10828/files#diff-a1cffc790e352be31a3f600180d968b6d96f3bd90acf4bfa0a49e3a66611558cR1033-R1065

**Comment by systay** [comment]
There is a helper method `go/mysql/sql_error.go:NewSQLErrorFromError()` that will do a bit of magic to extract a SQLError from inside a given error. I think we should use that more!
