### ISSUE TITLE
Bug Report: `USE databasename@replica` and then `flush status` will introduce errant GTID on replica

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#12330]
### Overview of the Issue

Originally found by @aquarapid:

`flush status` for some reason writes to the binary log (I don't see why, since it's session-local, but it does).

### Reproduction Steps

- `USE databasename@replica;`
- `flush status;`

Observe via `vtctlclient ShardReplicationPositions` that one of the replicas in the is now further advanced than the primary.

Result:
  * If the keyspace isn't failed over to the replica in question within the binlog expiry period (default 3 days);  we will eventually have an errant GTID situation that causes the replicas to stop replicating from the primary upon the next time the replica with the errant GTID becomes the primary (just a question of time with upgrades).

For investigation:
  * Are there other commands that an application user can execute that effectively bypass the MySQL `read_only` flag we have on the replicas and write to the binary log?

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
N/A
```

**Comment by deepthi** [comment]
@vitessio/vreplication is it possible that the changes in #11344 can introduce errant GTIDs? If the source for the vstream is a replica..

**Comment by rohit-nayak-ps** [comment]
> @vitessio/vreplication is it possible that the changes in #11344 can introduce errant GTIDs? If the source for the vstream is a replica..

Yes, looks like we need to call it like `FLUSH NO_WRITE_TO_BINLOG BINARY LOGS`.  
See https://dev.mysql.com/doc/refman/8.0/en/flush.html

```
FLUSH [NO_WRITE_TO_BINLOG | LOCAL] {
    flush_option [, flush_option] ...
  | tables_option
}

flush_option: {
    BINARY LOGS
```
```
By default, the server writes statements to the binary log so that they replicate to replicas. 
To suppress logging, specify the optional NO_WRITE_TO_BINLOG keyword or its alias LOCAL.
```

I will confirm it tomorrow locally and create a corrective PR.
