### ISSUE TITLE
Feature Request: Add support for `MySQL Workbench Table Data Import Wizard`

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#12334]
### Overview of the Issue

The original issue can be found in https://github.com/planetscale/discussion/discussions/372.

### Reproduction Steps

See https://github.com/planetscale/discussion/discussions/372.

### Binary Version

```sh
main and below
```

### Operating System and Environment details

```sh
n/a
```

**Comment by harshit-gangal** [comment]
PREPARE EXECUTE as a command is not supported and this is a feature request to add the support.
