### ISSUE TITLE
Bug Report: OnlineDDL VReplication Throttle Via Vstream CI Test Flakiness

### ISSUE THREAD

**Issue by mattlord** [vitessio/vitess#12336]
### Overview of the Issue

In local runs I see this test fail every so often: https://github.com/vitessio/vitess/blob/d15766ef21dd85615d2db66db7a920e32f036128/go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go#L391-L422

When it does fail, it always fails here: https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/test/endtoend/onlineddl/vrepl/onlineddl_vrepl_test.go#L419

With a message like this:
```
--- FAIL: TestSchemaChange/throttled_and_unthrottled_migration_via_vstreamer (9.11s)
Error:      	"2023-02-12 16:50:54" is not greater than or equal to "2023-02-12 16:50:55"
```

It's always one second in the past. 

This can happen when the test runs at the second boundary as we're using second based precision timestamps on the database side. It's the same basic issue that I had seen and addressed in the VDiff2 tests here: https://github.com/vitessio/vitess/pull/11054

### Reproduction Steps

If you run the test locally enough times, you'll see it (it's a timing issue):
```
go test -timeout 30m -v -failfast -run TestSchemaChange vitess.io/vitess/go/test/endtoend/onlineddl/vrepl
```

### Binary Version

```sh
Version: 17.0.0-SNAPSHOT
```

### Operating System and Environment details

```sh
N/A (FWIW I was running it locally on macOS arm64)
```

**Comment by shlomi-noach** [comment]
> This can happen when the test runs at the second boundary as we're using second based precision timestamps on the database side. 

I'm still confused on how this might happen? The migration _first starts_, ie `started_timestamp` is updated to `now()`. Then, it may or may not throttle. It's impossible for throttling to take place before the migration started. So how does the throttling timestamp lower that `started_timestamp`?

**Comment by shlomi-noach** [comment]
`time_throttled` is set in `_vt.vreplication` in:

https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go#L534-L535

Then, the value is copied over to `_vt.schema_migrations` in:

https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/onlineddl/executor.go#L3568

https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/onlineddl/executor.go#L4230-L4241

`started_timestamp` is updated in this query:

https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/onlineddl/schema.go#L113-L117

and first invoked here:

https://github.com/vitessio/vitess/blob/a6529e1df6ea6e4e7b7ecfa65f985f5f1db0803d/go/vt/vttablet/onlineddl/executor.go#L1346-L1348

and that happens _before_ starting `vreplication`. That's before the `_vt.vreplication` row gets created.

I could understand how the value might be _earlier_ if these were different machines, but this runs on your local box, so the clock is clearly in sync between all components. This is not about an ETA, this is comparing the output of `time.Now()` and `CURRENT_TIMESTAMP()`.

Obviously, as you say this does happen, I just don't get how.

**Comment by mattlord** [comment]
I'm not sure either, but in theory at least it can be caused by operations happening near the second boundary and the hwclock time getting adjusted slightly backward via e.g. NTP.

**Comment by mattlord** [comment]
I *think* this may be the underlying cause: 
```
diff --git a/go/vt/vttablet/onlineddl/executor.go b/go/vt/vttablet/onlineddl/executor.go
index ef0907fea7..a929d0ea55 100644
--- a/go/vt/vttablet/onlineddl/executor.go
+++ b/go/vt/vttablet/onlineddl/executor.go
@@ -4776,12 +4776,10 @@ func (e *Executor) onSchemaMigrationStatus(ctx context.Context,
        case schema.OnlineDDLStatusComplete:
                {
                        progressPct = progressPctFull
-                       _ = e.updateMigrationStartedTimestamp(ctx, uuid)
                        err = e.updateMigrationTimestamp(ctx, "completed_timestamp", uuid)
                }
        case schema.OnlineDDLStatusFailed:
                {
-                       _ = e.updateMigrationStartedTimestamp(ctx, uuid)
                        err = e.updateMigrationTimestamp(ctx, "completed_timestamp", uuid)
                }
        }
```

**Comment by shlomi-noach** [comment]
Sadly that's not it, `started_timestamp` is effectively only set once and then never modified,  see https://github.com/vitessio/vitess/pull/12582#pullrequestreview-1332059712

**Comment by shlomi-noach** [comment]
My current assumption is that `golang` and `MySQL` do not agree on converting timestamp->unixtime->timestamp, and that the reason this only happens on GitHub CI, and the fact that there's a single second difference, has to do with leap second config? I'm not sure. But I'm refactoring the code so that both evaluations happen in `golang` space.

**Comment by shlomi-noach** [comment]
Proposed solution in https://github.com/vitessio/vitess/pull/12826; I'll run it in CI multiple times.

**Comment by shlomi-noach** [comment]
Just hit another of these test failures. Seems like https://github.com/planetscale/vitess-private/pull/1896 did not fix the issue after all.
