### ISSUE TITLE
Bug Report: MariaDB support broken in vdiff2

### ISSUE THREAD

**Issue by mikehamrick** [vitessio/vitess#12419]
### Overview of the Issue

When attempting to perform an import from an importkeyspace of `10.3.36-MariaDB-log` we see repeated errors in the Vitess logs in the form of:

>  Error retrying vdiffs: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '>>'$.core_options.auto_retry' = 'true'' at line 1 (errno 1064) (sqlstate 42000) during query: select * from _vt.vdiff where state = 'error' and options->>'$.core_options.auto_retry' = 'true'

It appears that the `column->>path` JSON operator used in the SQL here is [not supported](https://jira.mariadb.org/browse/MDEV-13594) by MariaDB.

### Reproduction Steps

I don't have a complete list of reproduction steps here sadly. It's from an import of an external MariaDB keyspace. Hopefully the error message alone will be enough to find the issue!

### Binary Version

```sh
2023-02-07.e775d05
```

### Operating System and Environment details

```sh
N/A
```

**Comment by mattlord** [comment]
[We do not support MariaDB in Vitess v16](https://github.com/vitessio/vitess/issues/9518) (where [VDiff2 is GA and the default](https://github.com/vitessio/vitess/pull/12084)) and later, BUT this is a pretty easy fix — as `col1->>'$.field1'` is equivalent to `JSON_UNQUOTE(JSON_EXTRACT(col1, '$.field1'))` — and doing so allows us to fully support VDiff2 with MariaDB imports, even when running the diffs against the reverse workflows.

**Comment by deepthi** [comment]
@mattlord to me this looks like
- there's an external primary vttablet against MariaDB
- because it is a primary we create all the engines (including VDiff)
- that engine periodically checks for failed VDiff attempts
- the query for fetching those fails

So even before anyone tries to actually run a VDiff this will continuously error.

**Comment by mattlord** [comment]
@deepthi correct, you would see an error log message about this every 30 seconds on that tablet. It wouldn't cause anything to fail, but you would see that in the logs.

**Comment by mattlord** [comment]
Fixed by: https://github.com/vitessio/vitess/pull/12420
