### ISSUE TITLE
Feature Request: extend numeric_static_map vindex to support a hash fallback

### ISSUE THREAD

**Issue by maxenglander** [vitessio/vitess#12411]
## Description

It would be useful to have the ability to fallback to a hash lookup when there are keys missing from the JSON mapping of `numeric_static_map`. 

E.g.

```
{
  "sharded": true,
  "vindexes": {
    "nsm_idx": {
      "type": "numeric_static_map",
      "params": {
        "fallback_type": "xxhash"
      }
    }
  }
}
```

When `fallback_type` is set, `numeric_static_map` would internally fall back to using the specified hashing function to map requested keys not present in the JSON mapping.

## Use Cases

This would be helpful for use cases like placing large tenants on specific shards, and falling back to hashing for tenants that don't need special handling.

**Comment by dbussink** [comment]
> "use_fallback": true

What identifies in this case what we fall back to? Could you add what the full vschema would look like with how the fallback is defined?

**Comment by maxenglander** [comment]
Hey @dbussink currently in [this draft implementation](https://github.com/vitessio/vitess/pull/12414/files#diff-2706bb924ecf40a03b2fedc1ba40aba4980f022665692a0efb631ee4805d19a0R85-R97) the fallback is hardcoded as `xxhash`. I figured that's simplest for now, and would allow for expansion later on. 

E.g. eventually the draft implementation could be amended like this in a backwards-compatible way:

```
if useFallback != "true" {
  /* assume it's a hashing vindex defined elsewhere in the vschema, look for it and use it */
}
```

I'm open to making this more flexible now if that's your preference. For now I've clarified in this feature request that I'd be fine with a hardcoded hashing function.

**Comment by deepthi** [comment]
Why not replace `use_fallback` with something like `fallback_type: xxhash`? The eliminates hard-coding and ambiguity.

**Comment by maxenglander** [comment]
@deepthi I'm totally fine with that. My thinking was to keep the minimize code complexity and edge cases by limiting options initially, and be able to expand later as the demand for new params/hashes arises.

I'll update the FR  inline with your suggestion.
