### ISSUE TITLE
Bug Report: VTAdmin Does Not Show Any Resources With The Vitess Examples

### ISSUE THREAD

**Issue by mattlord** [vitessio/vitess#12416]
### Overview of the Issue

When using the Vitess examples, e.g. the local example: https://vitess.io/docs/16.0/get-started/local/

The VTAdmin web UI does not show any resources.

### Reproduction Steps

```
git checkout release-16.0

cd examples/local

./101_initial_cluster.sh

open http://localhost:14201
```

### Binary Version

```sh
v16.0-rc1
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

```sh
N/A
```

**Comment by deepthi** [comment]
Fixed by #12415
