### ISSUE TITLE
Feature Request: support throttling on "any" cell by default in vttablet transaction throttler

### ISSUE THREAD

**Issue by timvaillancourt** [vitessio/vitess#12435]
### Feature Description

Currently the `vttablet` transaction throttler will not start if the list of cells to healthcheck is not defined. This scenario also causes the transaction throttler to be somewhat-silently disabled, [which is another issue I reported here](https://github.com/vitessio/vitess/issues/12410)

An example:
```bash
$ /mnt/vitess/bin/vitess/current/vttablet -tablet-path us_east_1e-123456 \
          -mycnf-file /mnt/vitess/mysql/datadir/my.cnf -topo_implementation "consul" \
          -topo_global_server_address "consul.redacted.com:8500" -topo_global_root "vitess/global" \
          -init_keyspace test -init_shard -80 -init_tablet_type "replica" \
          -enable-tx-throttler 
E0221 10:13:18.843054    6307 tx_throttler.go:88] Error creating transaction throttler. Transaction throttling will be disabled. Error: empty healthCheckCells given. &{enabled:true topoServer:0xc0012319c0 throttlerConfig:0xc001217950 healthCheckCells:[]}
W0221 10:13:18.970389    6307 tm_init.go:706] creating keyspace and shard failed (Get "http://consul.redacted.com:8500/v1/kv/vitess/global/keyspaces/test/shards/-80/Shard": dial tcp: lookup consul.redacted.com on 127.0.0.1:53: no such host), backing off 1s before retrying
W0221 10:13:19.973236    6307 tm_init.go:706] creating keyspace and shard failed (Get "http://consul.redacted.com:8500/v1/kv/vitess/global/keyspaces/test/shards/-80/Shard": dial tcp: lookup consul.redacted.com on 127.0.0.1:53: no such host), backing off 1.125602181s before retrying
W0221 10:13:21.101325    6307 tm_init.go:706] creating keyspace and shard failed (Get "http://consul.redacted.com:8500/v1/kv/vitess/global/keyspaces/test/shards/-80/Shard": dial tcp: lookup consul.redacted.com on 127.0.0.1:53: no such host), backing off 1.295018994s before retrying
^C
```

When no `-tx-throttler-healthcheck-cells` is specified I suggest `vttablet` uses all available cells instead of refusing to start the transaction throttler

I am happy to make a PR implementing what is decided here 👍. If we decide to leave this as-is, I feel more could be done to highlight that `-tx-throttler-healthcheck-cells` is a required flag when using `-enable-tx-throttler`

### Use Case(s)

A fallback to "any cell" simplifies deployment/config automation for some users who today need to define an exhaustive list of cells to monitor. Users without a preference on cells to monitor can simply not-define this flag.

To me, this seems like the more intuitive default as well.

**Comment by harshit-gangal** [comment]
@timvaillancourt are you suggesting `all cells` or `any cells`? Use case mentions `any` while descriptions says `all`

**Comment by timvaillancourt** [comment]
@harshit-gangal I mean all cells available to the `vttablet` assuming that is easy to know

For example: if deployed in a cluster with cells `dc1`, `dc2` and `dc3`, the `vttablet` Transaction Throttler will consider healthchecks from `dc1`, `dc2` and `dc3` when `--tx-throttler-healthcheck-cells` is not provided

Today the transaction throttler will fail to start unless an explicit list of cells is provided, even if you just want "all available"

**Comment by harshit-gangal** [comment]
I like this. Thank you for clarifying.

**Comment by timvaillancourt** [comment]
@harshit-gangal thanks! I think it's more in line with how `--cells-to-watch` and other 'selectors' works for example 👍

A PR has been created to implement this: https://github.com/vitessio/vitess/pull/12477

**Comment by shlomi-noach** [comment]
I'm also in agreement this should be the solution.
