### ISSUE TITLE
Bug Report: Vitess 16 online DDL makes xtrabackup to fails

### ISSUE THREAD

**Issue by L3o-pold** [vitessio/vitess#12517]
### Overview of the Issue

Similar to https://github.com/vitessio/vitess/issues/12300 but this time with an online DDL.

I runned:

```sql
SET @@ddl_strategy='vitess';

ALTER TABLE my_table
DROP COLUMN my_column;

alter vitess_migration '...' cleanup;

ALTER TABLE my_other_table
DROP COLUMN my_column;

alter vitess_migration '...' cleanup;
```

The next backup then failed:

```
"@timestamp",message
"Feb 28, 2023 @ 18:00:17.715","E0228 17:00:17.715768       9 main.go:105] remote error: rpc error: code = Unknown desc = TabletManager.Backup on d2-0000100011 error: xtrabackup failed with error. Output=: exit status 1: xtrabackup failed with error. Output=: exit status 1"
"Feb 28, 2023 @ 18:00:17.715","E0228 17:00:17.715327       9 main.go:96] E0228 17:00:17.714869 backup.go:108] E0228 17:00:17.714869 backup.go:143] failed to finish backup: [MalformedXML: The XML you provided was not well-formed or did not validate against our published schema."
"Feb 28, 2023 @ 18:00:17.715","	status code: 400, request id: txe2538300eabf4542a4043-0063fe3321, host id: txe2538300eabf4542a4043-0063fe3321]: %!v(MISSING)"
"Feb 28, 2023 @ 18:00:17.715","BackupShard Error: rpc error: code = Unknown desc = TabletManager.Backup on d2-0000100011 error: xtrabackup failed with error. Output=: exit status 1: xtrabackup failed with error. Output=: exit status 1"
"Feb 28, 2023 @ 18:00:17.688","xtrabackup failed with error. Output=]"
"Feb 28, 2023 @ 18:00:17.688","I0228 17:00:17.688641       9 main.go:96] I0228 17:00:17.688379 backup.go:108] I0228 17:00:17.688449 xtrabackupengine.go:146] Closing backup file backup.xbstream.gz"
"Feb 28, 2023 @ 18:00:17.688","E0228 17:00:17.688757       9 main.go:96] E0228 17:00:17.688492 backup.go:108] E0228 17:00:17.688557 backup.go:135] backup is not usable, aborting it: [exit status 1"
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682735       9 main.go:96] I0228 17:00:17.682162 backup.go:108] I0228 17:00:17.682051 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681965-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Please run OPTIMIZE TABLE or ALTER TABLE ALGORITHM=COPY on all listed tables to fix this issue."
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682700       9 main.go:96] I0228 17:00:17.682126 backup.go:108] I0228 17:00:17.682017 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681943-00:00 0 [ERROR] [MY-011825] [Xtrabackup] vt_database/my_table"
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682649       9 main.go:96] I0228 17:00:17.682085 backup.go:108] I0228 17:00:17.681985 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681920-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Please check https://docs.percona.com/percona-xtrabackup/8.0/em/instant.html for more details."
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682633       9 main.go:96] I0228 17:00:17.682063 backup.go:108] I0228 17:00:17.681969 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681904-00:00 0 [ERROR] [MY-011825] [Xtrabackup] This feature is not stable and will cause backup corruption."
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682589       9 main.go:96] I0228 17:00:17.682011 backup.go:108] I0228 17:00:17.681940 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681854-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Found tables with row versions due to INSTANT ADD/DROP columns"
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682687       9 main.go:96] I0228 17:00:17.682108 backup.go:108] I0228 17:00:17.682002 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681932-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Tables found:"
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682711       9 main.go:96] I0228 17:00:17.682144 backup.go:108] I0228 17:00:17.682035 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681954-00:00 0 [ERROR] [MY-011825] [Xtrabackup] vt_database/my_other_table"
"Feb 28, 2023 @ 18:00:17.650","I0228 17:00:17.650506       9 main.go:96] I0228 17:00:17.650203 backup.go:108] I0228 17:00:17.650269 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.650208-00:00 0 [Note] [MY-011825] [Xtrabackup] Executing LOCK INSTANCE FOR BACKUP ..."
"Feb 28, 2023 @ 18:00:17.639","I0228 17:00:17.639846       9 main.go:96] I0228 17:00:17.639590 backup.go:108] I0228 17:00:17.639670 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.639594-00:00 0 [Note] [MY-011825] [Xtrabackup] Using server version 8.0.30"
"Feb 28, 2023 @ 18:00:17.629","I0228 17:00:17.628943       9 main.go:96] I0228 17:00:17.628479 backup.go:108] I0228 17:00:17.628536 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.628431-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: localhost, user: vt_dba, password: not set, port: not set, socket: /vt/socket/mysql.sock"
"Feb 28, 2023 @ 18:00:17.619","I0228 17:00:17.619185       9 main.go:96] I0228 17:00:17.618611 backup.go:108] I0228 17:00:17.618562 xtrabackupengine.go:369] xtrabackup stderr: 230228 17:00:17  version_check Done."
"Feb 28, 2023 @ 18:00:17.160","I0228 17:00:17.160681       9 main.go:96] I0228 17:00:17.160340 backup.go:108] I0228 17:00:17.160353 xtrabackupengine.go:369] xtrabackup stderr: 230228 17:00:17  version_check Connected to MySQL server"
"Feb 28, 2023 @ 18:00:17.160","I0228 17:00:17.160778       9 main.go:96] I0228 17:00:17.160552 backup.go:108] I0228 17:00:17.160616 xtrabackupengine.go:369] xtrabackup stderr: 230228 17:00:17  version_check Executing a version check against the server..."
"Feb 28, 2023 @ 18:00:17.159","I0228 17:00:17.159330       9 main.go:96] I0228 17:00:17.158932 backup.go:108] I0228 17:00:17.158849 xtrabackupengine.go:369] xtrabackup stderr: 230228 17:00:17  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup;mysql_socket=/vt/socket/mysql.sock' as 'vt_dba'  (using password: NO)."
"Feb 28, 2023 @ 18:00:16.979","I0228 17:00:16.979713       9 main.go:96] I0228 17:00:16.979468 backup.go:108] I0228 17:00:16.979475 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:16.979364-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --socket=/vt/socket/mysql.sock --slave-info=1 --user=vt_dba --target-dir=/vt/vtdataroot/vt_0000100011/tmp --stream=xbstream "
"Feb 28, 2023 @ 18:00:16.979","I0228 17:00:16.979537       9 main.go:96] I0228 17:00:16.979280 backup.go:108] I0228 17:00:16.979322 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:16.979129-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized server arguments: --datadir=/vt/vtdataroot/vt_0000100011/data --innodb_data_home_dir=/vt/vtdataroot/vt_0000100011/innodb/data --innodb_log_group_home_dir=/vt/vtdataroot/vt_0000100011/innodb/logs --log_bin=/vt/vtdataroot/vt_0000100011/bin-logs/vt-0000100011-bin --server-id=2141437576 --tmpdir=/vt/vtdataroot/vt_0000100011/tmp --innodb_buffer_pool_size=20G --innodb_log_file_size=16M "
"Feb 28, 2023 @ 18:00:16.979","I0228 17:00:16.979737       9 main.go:96] I0228 17:00:16.979520 backup.go:108] I0228 17:00:16.979518 xtrabackupengine.go:369] xtrabackup stderr: xtrabackup version 8.0.32-25 based on MySQL server 8.0.32 Linux (x86_64) (revision id: 14f007fb)"
"Feb 28, 2023 @ 18:00:16.955","I0228 17:00:16.955697       9 main.go:96] I0228 17:00:16.955477 backup.go:108] I0228 17:00:16.954551 compression.go:257] Compressing backup using engine ""pargzip"""
"Feb 28, 2023 @ 18:00:16.951","I0228 17:00:16.951492       9 main.go:96] I0228 17:00:16.950760 backup.go:108] I0228 17:00:16.950648 xtrabackupengine.go:194] backup file name: backup.xbstream.gz"
"Feb 28, 2023 @ 18:00:16.951","I0228 17:00:16.951507       9 main.go:96] I0228 17:00:16.950785 backup.go:108] I0228 17:00:16.950668 xtrabackupengine.go:202] Starting backup with 0 stripe(s)"
"Feb 28, 2023 @ 18:00:16.718","OKI0228 17:00:16.951338       9 main.go:96] I0228 17:00:16.950713 backup.go:108] I0228 17:00:16.950594 xtrabackupengine.go:191] Detected MySQL flavor: MySQL56"
"Feb 28, 2023 @ 18:00:16.681","                                 Dload  Upload   Total   Spent    Left  Speed"
"Feb 28, 2023 @ 18:00:16.681","
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     2  100     2    0     0     54      0 --:--:-- --:--:-- --:--:--    54"
"Feb 28, 2023 @ 18:00:16.681","  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current"
```

### Reproduction Steps

Run an online DDL droping a column. Run xtrabackup and see it fails.

### Binary Version

```sh
Version: 16.0.0 (Git revision bb768df0008fc09f7e6868a4fa571c32cc1cb526 branch 'heads/v16.0.0') built on Tue Feb 28 15:38:00 UTC 2023 by vitess@buildkitsandbox using go1.20.1 linux/amd64
```

### Operating System and Environment details

```sh
docker
```

**Comment by L3o-pold** [comment]
@deepthi the one provided by the `vitess/lite:16.0.0` docker image.

```
xtrabackup --version
2023-02-28T18:45:49.407191-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized server arguments: --datadir=/var/lib/mysql 
xtrabackup version 8.0.32-25 based on MySQL server 8.0.32 Linux (x86_64) (revision id: 14f007fb)
```

**Comment by deepthi** [comment]
@L3o-pold could it be that the table you are encountering this was originally created/altered with an older version of MySQL and that is continuing to cause problems?
In other words, can you create a new table using online DDL, and then alter it using online DDL and still run into this problem that that particular table?

**Comment by deepthi** [comment]
cc @shlomi-noach we'll need to investigate this further

**Comment by deepthi** [comment]
Looks like we are not pinning the xtrabackup version to be the same as MySQL version:
https://github.com/vitessio/vitess/blob/main/docker/lite/install_dependencies.sh#LL104

@L3o-pold are you able to change that file to pin xtrabackup to 8.0.30 and rebuild the image and re-test?

**Comment by L3o-pold** [comment]
@deepthi the table was created on Vitess 15.0.2 (MySQL 8.0.23). An other important thing to note is that backups were working fine before running the online DDL. 

I can try to re-build the image

**Comment by L3o-pold** [comment]
@deepthi not sure I can

```
apt list --all-versions percona-xtrabackup-80
Listing... Done
percona-xtrabackup-80/unknown 8.0.32-25-1.buster amd64
```

**Comment by shlomi-noach** [comment]
Under the hood Online DDL only runs standard MySQL primitives; it creates a table, drops a column on that table, copies data over. I don't have any immediate insight on why `xtrabackup` would fail? To MySQL, Vitess's Online DDL looks like anything a user might do.

Moreover, we're not using `INSTANT DDL`, which in my understanding does cause `xtrabackup` failures for some versions. This is isn't the case here.

**Comment by deepthi** [comment]
@L3o-pold did you follow the upgrade instructions? From the release notes
```
However, if you are running MySQL 8.0 on the vitess-operator, with for instance vitess/lite:v15.0.2-mysql80, considering that we are bumping the patch version of MySQL 80 from 8.0.23 to 8.0.30, you will have to manually upgrade:

Add innodb_fast_shutdown=0 to your extra cnf in your YAML file.
Apply this file.
Wait for all the pods to be healthy.
Then change your YAML file to use the new Docker Images (vitess/lite:v16.0.0, defaults to mysql80).
Remove innodb_fast_shutdown=0 from your extra cnf in your YAML file.
Apply this file.
```

**Comment by shlomi-noach** [comment]
The log says:

```
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682589       9 main.go:96] I0228 17:00:17.682011 backup.go:108] I0228 17:00:17.681940 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681854-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Found tables with row versions due to INSTANT ADD/DROP columns"
```

hmmmm, is it possible thought that the `ALTER TABLE` we run on the empty vreplication (aka "shadow") table, is implicitly a `INSTANT` operation? That's a possibility. If that is indeed the case, the solution is for vitess to add `ALGORITHM=COPY`.

**Comment by deepthi** [comment]
It also says
```
Please run OPTIMIZE TABLE or ALTER TABLE ALGORITHM=COPY on all listed tables to fix this issue."
xtrabackup stderr: 2023-02-28T17:00:17.681943-00:00 0 [ERROR] [MY-011825] [Xtrabackup] vt_database/my_table"
xtrabackup stderr: 2023-02-28T17:00:17.681920-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Please check https://docs.percona.com/percona-xtrabackup/8.0/em/instant.html for more details."
"Feb 28, 2023 @ 18:00:17.682","I0228 17:00:17.682633       9 main.go:96] I0228 17:00:17.682063 backup.go:108] I0228 17:00:17.681969 xtrabackupengine.go:369] xtrabackup stderr: 2023-02-28T17:00:17.681904-00:00 0 [ERROR] [MY-011825] [Xtrabackup] This feature is not stable and will cause backup corruption."
xtrabackup stderr: 2023-02-28T17:00:17.681854-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Found tables with row versions due to INSTANT ADD/DROP columns"
xtrabackup stderr: 2023-02-28T17:00:17.681932-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Tables found:"
xtrabackup stderr: 2023-02-28T17:00:17.681954-00:00 0 [ERROR] [MY-011825] [Xtrabackup] vt_database/my_other_table"
```
So this is not about our _vt internal tables any more.

**Comment by L3o-pold** [comment]
@deepthi I tried to follow the upgrade guide but I missed this part. But I upgraded to rc-1 weeks ago, and the issue (on non _vt internal tables) appeared after updated from 16.0.0-rc.1 to 16.0.0 and only after then, I runned the online DDL.

**Comment by shlomi-noach** [comment]
Still, `vt_database/my_table` is a table we created, initially under the name `_somethingsomething_vrepl`, modified, potentially implicitly via `INSTANT`, then renamed as `my_table` at the end of cut-over?

**Comment by deepthi** [comment]
> Still, `vt_database/my_table` is a table we created, initially under the name `_somethingsomething_vrepl`, modified, potentially implicitly via `INSTANT`, then renamed as `my_table` at the end of cut-over?

Yeah, this seems like a plausible theory.

**Comment by L3o-pold** [comment]
@deepthi do you still want me to try with downgraded version of xtrabackup ?

**Comment by deepthi** [comment]
> @deepthi I tried to follow the upgrade guide but I missed this part. But I upgraded to rc-1 weeks ago, and the issue (on non _vt internal tables) appeared after updated from 16.0.0-rc.1 to 16.0.0 and only after then, I runned the online DDL.

OK, so the 8.0.23 to 8.0.30 upgrade actually happened when you upgraded from v15.0.2 to v16.0.0-rc1, correct?
And you did not attempt an online DDL when you were running v16.0.0-rc1?

You pretty much have to run `optimize table` at this point. We can possibly fix the online DDL INSTANT vs COPY issue in a patch release.

**Comment by shlomi-noach** [comment]
This issue shouldn't be tied to the vitess version -- it should be tied to the MySQL version, I believe. The vitess logic hasn't changed in a while on that part. But possibly a recent MySQL version chooses to implicitly use `INSTANT` algorithm where a previous MySQL version did not? Just a conjecture.

**Comment by shlomi-noach** [comment]
Possibly related: https://github.com/vitessio/vitess/pull/12436

**Comment by deepthi** [comment]
> This issue shouldn't be tied to the vitess version -- it should be tied to the MySQL version, I believe. The vitess logic hasn't changed in a while on that part. But possibly a recent MySQL version chooses to implicitly use `INSTANT` algorithm where a previous MySQL version did not? Just a conjecture.

Agreed. We do know that MySQL has been making more and more DDLs INSTANT over time, and 8.0.23 is a pretty old version at this point. It's unfortunate that INSTANT DDL doesn't seem to be compatible with xtrabackup though.

**Comment by shlomi-noach** [comment]
> It's unfortunate that INSTANT DDL doesn't seem to be compatible with xtrabackup though.

This has some far reaching implications, in case uses choose to either:

- `ApplySchema` with `direct` strategy, or
- `ApplySchema` with `mysql` strategy, or
- just run `ALTER TABLE` in `vtgate`,
- and use `ALGORITHM=INSTANT`.

**Comment by L3o-pold** [comment]
> > @deepthi I tried to follow the upgrade guide but I missed this part. But I upgraded to rc-1 weeks ago, and the issue (on non _vt internal tables) appeared after updated from 16.0.0-rc.1 to 16.0.0 and only after then, I runned the online DDL.
> 
> 
> 
> OK, so the 8.0.23 to 8.0.30 upgrade actually happened when you upgraded from v15.0.2 to v16.0.0-rc1, correct?
> 
> And you did not attempt an online DDL when you were running v16.0.0-rc1?
> 
> 
> 
> You pretty much have to run `optimize table` at this point. We can possibly fix the online DDL INSTANT vs COPY issue in a patch release.

That is correct. And I runned optimized and backups work again.

**Comment by shlomi-noach** [comment]
Suggested PR: https://github.com/vitessio/vitess/pull/12521

**Comment by deepthi** [comment]
@shlomi-noach pointed out that this has been fixed in the version of xtrabackup that was released yesterday
https://docs.percona.com/percona-xtrabackup/8.0/em/instant.html

**Comment by L3o-pold** [comment]
From my understanding it need MySQL >= 8.0.32

**Comment by L3o-pold** [comment]
never going to work expect if running `OPTIMIZE` right? 😨

**Comment by shlomi-noach** [comment]
Yes, correct :sweat_smile:

**Comment by deepthi** [comment]
One other workaround suggested by someone on our team:
- Switch your backups to use the builtin method instead of xtrabackup and take an immediate backup
- this requires you to change some flags/properties in the operator yaml and re-deploy. vtctld and vttablets will all need to be rolled with the new flags.

**Comment by L3o-pold** [comment]
Is it planned to update MySQL >= 8.0.32 in Vitess 17? https://github.com/vitessio/vitess/blob/main/docker/lite/install_dependencies.sh#L86

**Comment by frouioui** [comment]
> Is it planned to update MySQL >= 8.0.32 in Vitess 17? https://github.com/vitessio/vitess/blob/main/docker/lite/install_dependencies.sh#L86

@L3o-pold, AFAIK, we plan on keeping the MySQL version we use up-to-date with recent MySQL versions, the same way we did in `v16` by upgrading from `8.0.23` to `8.0.30`.
