### ISSUE TITLE
Bug Report: vtorc waits 15-30s to reach a dead primary before recovery

### ISSUE THREAD

**Issue by olyazavr** [vitessio/vitess#12578]
### Overview of the Issue

When vtorc is recovering a dead (unreachable) primary, it first does a full refresh of all tablet via [forceRefreshAllTabletsInShard](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/logic/topology_recovery.go#L666), which does a [FullStatus](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/inst/tablet_dao.go#L140) on each tablet, attempting to connect to it. This will of course hang on the dead primary, but the timeout here is `RemoteOperationTimeout`, which is 15-30s depending on your Vitess version. That makes recovery needlessly slow. Our workaround is to make this timeout 3s instead, which brings out total recovery time to 15s instead of something much longer.

### Reproduction Steps

To kill a primary running in kube, I do: 
1. `pkill -9 mysqlctld`
2. `kubectl delete pod $pod_name --grace-period=1`(fast shutdown)

You can then see a bunch of logs like:
```
topology_recovery.go:1005] executeCheckAndRecoverFunction: proceeding with DeadPrimary detection on 172.18.127.104:3306; isActionable?: true; skipProcesses: false
locks.go:373] Locking shard VitessTest/0 for action Orc Recovery
```

for quite some time, until the timeout

Unfortunately, if the pod you deleted comes back faster than the timeout, vtorc then chooses to make that one the primary again instead of doing ERS (in our setup, a dead primary has suspect data and should be restored instead of made primary again)

### Binary Version

```sh
Vitess 16, through commit https://github.com/vitessio/vitess/commit/aa7ab6578078cdb761c1eb6f12f4c7ea509ad06a
```

### Operating System and Environment details

```sh
Centos8, Linux 5.4.141-hs22.el8.x86_64
```

**Comment by rsajwani** [comment]
I tried to repro this issue using local example. Here are the steps

1- Start 101_initial_cluster.sh with 1 primary and 2 replica.
2- Kill primary's `mysqld_safe`, `vttablet` and `mysqld` processes in the same order.
3- As you can observer below `forceRefreshAllTabletsInShard` took 15 seconds.   
```
I0410 14:58:17.916432    8421 tablet_discovery.go:169] 7706e9bd-ca44-4368-9a7f-69fe3b214764 start force refresh of all tablets in shard - commerce/0
I0410 14:58:32.920279    8421 tablet_discovery.go:175] 7706e9bd-ca44-4368-9a7f-69fe3b214764 end force refresh of all tablets in shard - commerce/0
```
