### ISSUE TITLE
Question: Database stop working

### ISSUE THREAD

**Issue by javaboboApp** [vitessio/vitess#12611]
### Question

Hi there, I am getting the next error when making a query using vitess: 

`Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1105 target: apidbtest3.-.primary: primary is not serving, there is a reparent operation in progress (SQL: select * from `oauth_access_tokens` where `id` = 5a78c83bd1bd6f13d34c4ac2f7223017283c7ff9262e7486fad5c44231ce5ff98d9dec0b655464d8 limit 1) in file /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 712`

runnig command:

**kubectl logs xxx-mysql-cluster-vttablet-zone1-1205982007-c97a35d4  -c vttablet** 

I got the next logs: 

```
I0312 11:10:18.273387       1 rpc_replication.go:781] StopReplicationAndGetStatus: mode: IOTHREADONLY
W0312 11:10:18.274000       1 rpc_server.go:80] TabletManager.StopReplicationAndGetStatus(stop_replication_mode:IOTHREADONLY)(on zone1-1205982007 from ) error: before status failed: net.Dial(/vt/socket/mysql.sock) to local server failed: dial unix /vt/socket/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
W0312 11:10:18.337297       1 rpc_server.go:80] TabletManager.FullStatus()(on zone1-1205982007 from ) error: net.Dial(/vt/socket/mysql.sock) to local server failed: dial unix /vt/socket/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
E0312 11:10:18.458916       1 engine.go:340] Error retrying vdiffs: error in connecting to mysql db with connection <nil>, err net.Dial(/vt/socket/mysql.sock) to local server failed: dial unix /vt/socket/mysql.sock: connect: no such file or directory (errno 2002) (sqlstate HY000)
```

I am getting next events: 

Events:
```
  Type     Reason     Age                   From     Message
  ----     ------     ----                  ----     -------
  Warning  Unhealthy  2m (x27917 over 88d)  kubelet  Readiness probe failed: dial tcp 10.42.208.143:3306: connect: connection refused.
```
  
The databse stop working and I do no know why, any idea??

**Comment by deepthi** [comment]
primary is not serving usually means that your mysqld crashed. you will need to look at that container and its logs. It could have OOM'ed because of a large query, or something else.
Assuming you are running with vitess-operator you may need to provide more resources (memory) to the tablets if the cause is OOM. Or make your queries smaller.
