### ISSUE TITLE
Set read-only token permissions for all workflows

### ISSUE THREAD

**Issue by pnacht** [vitessio/vitess#12717]
By default, GitHub workflows run with write-all permissions. This is dangerous, since it opens `vitess` up to supply-chain attacks. [GitHub itself](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-secrets) recommends ensuring all workflows run with minimal permissions.

As far as I can tell, `vitess`' workflows are mainly used for testingand therefore don't need such broad permissions.

This issue can be solved in two ways:

- add top-level read-only permissions to all workflows, and then give additional job-level permissions as necessary; and/or
- set the default token permissions to read-only in the repo settings.

I have a PR ready with the workflow changes (and to their templates), if you're interested.

If you instead (or also) wish to modify the default token permissions:

1. Open the repo settings
2. Go to [Actions > General](https://github.com/vitessio/vitess/settings/actions)
3. Under "Workflow permissions", set them to "Read repository contents and packages permissions"

If you wish to only modify the default token permissions, know that you'll need to modify any workflows that require additional permissions.

---

**Disclosure**: My name is Pedro and I work with Google and the Linux Foundation's [Open Source Security Foundation (OpenSSF)](https://www.openssf.org/) to improve the supply-chain security of the open-source ecosystem.

**Comment by deepthi** [comment]
Hi Pedro, thank you for opening this issue. A PR with the necessary changes will be appreciated.
cc @frouioui

**Comment by pnacht** [comment]
Hey @deepthi, just sent it over.

**Comment by frouioui** [comment]
Hello Pedro, thanks a bunch for this contribution. I have approved and contributed to your Pull Request.
