### ISSUE TITLE
Question: How to use aws rds in Vitess?

### ISSUE THREAD

**Issue by shizhibo2016** [vitessio/vitess#12816]
### Question

i use command below, but it do not work:

vttablet \
 --topo_implementation=etcd2 --topo_global_server_address=$TOPO_SERVER --topo_global_root=/vitess/global  \
 --logtostderr \
 --log_queries_to_file $VTDATAROOT/tmp/vttablet_0000000701_querylog.txt \
 --tablet-path "zone1-0000000701" \
 --init_keyspace test3 \
 --init_shard 0 \
 --init_tablet_type replica \
 --port 15701 \
 --grpc_port 16701 \
 --service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream' \
 --pid_file $VTDATAROOT/vt_0000000701/vttablet.pid \
 --vtctld_addr http://localhost:15000/ \
 --db_host xxx.xxx.rds.amazonaws.com \
 --db_port 3306 \
 --db_app_user msandbox \
 --db_app_password msandbox \
 --db_dba_user msandbox \
 --db_dba_password msandbox \
 --db_repl_user msandbox \
 --db_repl_password msandbox \
 --db_filtered_user msandbox \
 --db_filtered_password msandbox \
 --db_allprivs_user msandbox \
 --db_allprivs_password msandbox \
 --init_db_name_override test3 \
 --disable_active_reparents

**Comment by rohit-nayak-ps** [comment]
@shizhibo2016, can you please ask any questions related to usage of Vitess in the Vitess Slack at https://vitess.io/slack? Thanks!
