### ISSUE TITLE
Feature Request: GetThrottlerConfig vtctld RPC

### ISSUE THREAD

**Issue by mdlayher** [vitessio/vitess#12925]
### Feature Description

There is an RPC available to update the throttler configuration, but no matching RPC to fetch what is currently set: https://vitess.io/docs/16.0/reference/programs/vtctldclient/vtctldclient_updatethrottlerconfig/

### Use Case(s)

Allowing applications to make informed decision based on prior state, and easily exposing the current throttler configuration for user display.

**Comment by deepthi** [comment]
Why isn't the GetKeyspace RPC sufficient? It returns the throttler config among other things.

**Comment by mdlayher** [comment]
My apologies, it appears we didn't realize this was already exposed! Closing.

**Comment by mattlord** [comment]
Yep! And FWIW, you can also now see the actual live configuration on a given tablet as well: https://github.com/vitessio/vitess/pull/12737

**Comment by shlomi-noach** [comment]
I misled @mdlayher to believe there was no RPC to get the throttler config. And the reason I misled him is that I actually didn't realize I could use `GetKeyspace`, though in retrospect it shold have been obvious to me.

Having said that, `GetKeyspace` does not return `ThrottlerConfig` data:

```sh
$ vtctlclient -- GetKeyspace commerce
{
  "served_froms": [],
  "keyspace_type": 0,
  "base_keyspace": "",
  "snapshot_time": null,
  "durability_policy": "semi_sync",
  "throttler_config": null,
  "sidecar_db_name": "_vt"
}
```

`GetSrvKeyspace` does:

```sh
$ vtctlclient -- GetSrvKeyspace zone1 commerce
{
  "partitions": [
    {
      "served_type": 1,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    },
    {
      "served_type": 2,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    },
    {
      "served_type": 3,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    }
  ],
  "served_from": [],
  "throttler_config": {
    "enabled": true,
    "threshold": 3.7,
    "custom_query": "",
    "check_as_check_self": false
  }
}
```

Thanks @mattlord for pointing out the HTTP endpoint (also SQL query) -- we were specifically looking for a gRPC call, with HTTP/SQL being "plan B".

Reopening this Issue because I still want to understand the discrepancy between `GetKeyspace` and `GetSrvKeyspace`

**Comment by mattlord** [comment]
The SrvKeyspace record only has a *copy* of what's in the Keyspace record. I think you probably got confused somewhere along the way:
```
❯ vtctldclient GetKeyspace commerce
{
  "name": "commerce",
  "keyspace": {
    "served_froms": [],
    "keyspace_type": 0,
    "base_keyspace": "",
    "snapshot_time": null,
    "durability_policy": "semi_sync",
    "throttler_config": null,
    "sidecar_db_name": "_vt"
  }
}
❯ vtctldclient UpdateThrottlerConfig --enable commerce --custom-query="select 1" --threshold=3 --check-as-check-shard
❯ vtctldclient GetKeyspace commerce
{
  "name": "commerce",
  "keyspace": {
    "served_froms": [],
    "keyspace_type": 0,
    "base_keyspace": "",
    "snapshot_time": null,
    "durability_policy": "semi_sync",
    "throttler_config": {
      "enabled": true,
      "threshold": 3,
      "custom_query": "select 1",
      "check_as_check_self": false
    },
    "sidecar_db_name": "_vt"
  }
```

**Comment by shlomi-noach** [comment]
@mattlord thank you -- there's unfortunately no confusion here:
```
shlomi@ip-172-31-45-90: /tmp/examples/local$ vtctlclient -- UpdateThrottlerConfig --enable --threshold 2.70 commerce
shlomi@ip-172-31-45-90: /tmp/examples/local$ vtctlclient -- GetKeyspace commerce
{
  "served_froms": [],
  "keyspace_type": 0,
  "base_keyspace": "",
  "snapshot_time": null,
  "durability_policy": "semi_sync",
  "throttler_config": null,
  "sidecar_db_name": "_vt"
}
shlomi@ip-172-31-45-90: /tmp/examples/local$ vtctlclient -- GetSrvKeyspace zone1 commerce
{
  "partitions": [
    {
      "served_type": 1,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    },
    {
      "served_type": 2,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    },
    {
      "served_type": 3,
      "shard_references": [
        {
          "name": "0",
          "key_range": null
        }
      ],
      "shard_tablet_controls": []
    }
  ],
  "served_from": [],
  "throttler_config": {
    "enabled": true,
    "threshold": 2.7,
    "custom_query": "",
    "check_as_check_self": false
  }
}
```

**Comment by mattlord** [comment]
@shlomi-noach I'm afraid that there is some confusion somewhere here (perhaps with me 🙂). There's no way that can be on on v17/main. I'm not sure what version you're using or what other unique factors may be in play in your environment. `UpdateThrottlerConfig` updates the Keyspace record, then that gets *copied* to the SrvKeyspace records. See: https://github.com/vitessio/vitess/pull/12520

You can see the code for the `UpdateThrottlerConfig` RPC here: https://github.com/planetscale/vitess/blob/main/go/vt/vtctl/grpcvtctldserver/server.go#L1568-L1631

A SrvKeyspace record having a value that doesn't exist in the Keyspace record would be a serious bug -- one that I don't see an explanation for. If you have a repeatable test case (I cannot repeat what you're seeing on main) then please open an issue.

Perhaps the confusion here is that you're testing with a v16 based build? The dynamic throttler config was experimental and broken (IMO) in v16 and my changes/fixes were not backported. You can compare the code for the `UpdateThrottlerConfig` RPC in v16: https://github.com/planetscale/vitess/blob/release-16.0/go/vt/vtctl/grpcvtctldserver/server.go#L1570-L1624

**Comment by shlomi-noach** [comment]
@mattlord I know :sweat_smile: I read the code 5 times, it looks super legit! However, I'm using the most up to date `main` -- just deployed a completely fresh setup. A brand new `examples/local` cluster, and this still happens.

I'll close this issue and open a new issue.

**Comment by shlomi-noach** [comment]
Bug report: https://github.com/vitessio/vitess/issues/12935
