### ISSUE TITLE
Feature Request: make throttled transactions get a better error code to client applications

### ISSUE THREAD

**Issue by ejortegau** [vitessio/vitess#12958]
### Feature Description

Currently, when the transaction throttler decides that a query needs to be throttled, the client application receives a MySQL error code [1203 ER_TOO_MANY_USER_CONNECTIONS](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_too_many_user_connections). Only by examining the error's message string can it be determined that the underlying issue is actually that the transaction was throttled. This code is returned by MySQL when a user that has been set to have at most N connections, has already reached N open connections, and tries to establish a new one - hence, this error is expected during connection establishment, not after establishing it and issuing a query. 

We would like throttled transactions to return an error code that, first, makes sense when issuing a query, not when connceting; and second, that better signals that vitess (or the underlying MySQL) is overloaded and that therefore the request has been rejected. In an ideal world, we could have a new error code for this. However, MySQL server error codes are not - to the best of my knowledge - meant to be user-extendable, so we need to use one of the existing ones.

We feel that the best available one is [1041 ER_OUT_OF_RESOURCES](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_out_of_resources).

### Use Case(s)

Clear, unambiguous signaling of vitess/MySQL being overloaded can be leveraged by client applications to implement client-side throttling (for example, as described in section `Client-Side Throttling` of chapter [Handling Overload](https://sre.google/sre-book/handling-overload/) of the Google SRE Book.

An error code such as 1041 seems to signal this better than an error about hitting the (somewhat arbitrary) limit of connections of a particular user.

**Comment by harshit-gangal** [comment]
merged in main
