### ISSUE TITLE
Bug Report: rate limiter instances created via `NewRateLimiter` leak goroutines

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#13012]
### Overview of the Issue

We recently noticed that when a VReplication stream is constantly failing / being retried, each new retry creates a new rate limiter via [`NewRateLimiter`](https://github.com/vitessio/vitess/blob/d43ac8638a14cea5f5fe5bdf7d4c02b908d6a85c/go/timer/rate_limiter.go#LL39C1-L39C1)

This creates a [new ticker and goroutine](https://github.com/vitessio/vitess/blob/d43ac8638a14cea5f5fe5bdf7d4c02b908d6a85c/go/timer/rate_limiter.go#L43-L54). In all three uses of the rate limiter that I could find, the `Stop()` function that would allow cleaning up the goroutine/ticker instance are never called.

This leads to a slowly increasing memory leak / goroutine leak:

![Number of goroutines that currently exist](https://user-images.githubusercontent.com/2195/235704934-1f95d609-1c79-43d1-88d1-029767355c7d.png)

### Reproduction Steps

Create a vreplication stream that fails (i.e. starting position is no longer in the binlog) and is automatically retried.

### Binary Version

```sh
15.0.2
```

### Operating System and Environment details

```sh
N/A
```

**Comment by mattlord** [comment]
Thank you, @arthurschreiber ! /cc @shlomi-noach

**Comment by mattlord** [comment]
The fix may be something like this, but will require more investigation and test work:
```
diff --git a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
index 77318792de..6f1433cae9 100644
--- a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
+++ b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
@@ -185,6 +185,7 @@ func newVReplicator(id int32, source *binlogdatapb.BinlogSource, sourceVStreamer
 // However, there are some subtle differences, explained in the plan builder
 // code.
 func (vr *vreplicator) Replicate(ctx context.Context) error {
+	defer vr.throttleUpdatesRateLimiter.Stop()
 	err := vr.replicate(ctx)
 	if err != nil {
 		if err := vr.setMessage(err.Error()); err != nil {
diff --git a/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go b/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
index 8155f3bedb..030460d28e 100644
--- a/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
+++ b/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go
@@ -278,7 +278,7 @@ func (rs *rowStreamer) buildSelect() (string, error) {
 }
 
 func (rs *rowStreamer) streamQuery(conn *snapshotConn, send func(*binlogdatapb.VStreamRowsResponse) error) error {
-
+	defer rs.throttleResponseRateLimiter.Stop()
 	var sendMu sync.Mutex
 	safeSend := func(r *binlogdatapb.VStreamRowsResponse) error {
 		sendMu.Lock()
diff --git a/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go b/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
index 36ae5c77e3..d9ac730e43 100644
--- a/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
+++ b/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go
@@ -299,6 +299,7 @@ func (vs *vstreamer) parseEvents(ctx context.Context, events <-chan mysql.Binlog
 
 	throttleEvents := func(throttledEvents chan mysql.BinlogEvent) {
 		throttledHeartbeatsRateLimiter := timer.NewRateLimiter(HeartbeatTime)
+		defer throttledHeartbeatsRateLimiter.Stop()
 		for {
 			// check throttler.
 			if !vs.vse.throttlerClient.ThrottleCheckOKOrWait(ctx) {

```

**Comment by shlomi-noach** [comment]
Fixed in https://github.com/vitessio/vitess/pull/13016
