### ISSUE TITLE
Feature Request: filter topology by shard in vttablet txthrottler

### ISSUE THREAD

**Issue by timvaillancourt** [vitessio/vitess#13068]
### Feature Description

The txthrottler (on the `PRIMARY`) uses healthcheck streams to determine the replication lag of replicas in the shard

Today, the txthrottler uses `discovery.NewCellTabletsWatcher` to watch the topology with a filter on the keyspace only. This means the topology watcher is "watching" more tablets than is necessary

This feature request is to support filtering by keyspace AND shard

### Use Case(s)

Standard deploy w/TxThrottler enabled

**Comment by frouioui** [comment]
@vitessio/cluster-management

**Comment by timvaillancourt** [comment]
Before was the health checks from other shards ignored?

@harshit-gangal in v14 and below only the local shard was watched, which I feel is more correct/efficient

This behaviour was changed to filter by keyspace-only [here in this PR from v15](https://github.com/vitessio/vitess/pull/10542/files#diff-64fadbfcdb19a882612e389b82fe2b2ab116cfad9ccf43190b86d59fd51b98a1R200)

> Were they taking part in determining that throttling to be done?

I feel the Transaction Throttler (on `PRIMARY`) should only be concerned about replicas within it's local shard. This will prevent lag in one shard affecting all

**Comment by harshit-gangal** [comment]
That looks like the side effect of removing the legacy health check. Thank you for digging into that.

**Comment by timvaillancourt** [comment]
Indirectly resolved by https://github.com/vitessio/vitess/pull/14412. Thanks @deepthi!
