### ISSUE TITLE
Bug Report: Vitess Operator issue on Kubernetes

### ISSUE THREAD

**Issue by sabuhigr** [vitessio/vitess#13074]
### Overview of the Issue

I have v16.0 on Kubernetes environment, I have tried to create keyspace from VTAdmin UI, also from vtctlclient, but both of them behaviours is same.It creates, but after sometime it deletes the keyspace with all inside (Shards also)

### Reproduction Steps

time="2023-05-11T15:32:41Z" level=info msg="Reconciling EtcdLockserver" controller=EtcdLockserver etcdlockserver=voicespin-vitess-cluster-gke-etcd-b0e90f0f namespace=vitess-cluster-stage
time="2023-05-11T15:33:19Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
time="2023-05-11T15:33:43Z" level=info msg="Reconciling VitessCell" controller=VitessCell namespace=vitess-cluster-stage vitesscell=voicespin-vitess-cluster-gke-voicespin-gke-zone1-8ff2ce8d
time="2023-05-11T15:33:43Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
I0511 15:33:43.844645       1 vschema.go:58] deleting vschema for keyspace cloudbills-unsharded
I0511 15:33:43.851513       1 locks.go:246] Locking keyspace cloudbills-unsharded for action DeleteKeyspace
I0511 15:33:43.875317       1 server.go:865] Deleting all 1 shards (and their tablets) in keyspace cloudbills-unsharded
I0511 15:33:43.875418       1 server.go:871] Recursively deleting shard cloudbills-unsharded/0
I0511 15:33:43.877057       1 locks.go:432] Locking shard cloudbills-unsharded/0 for action DeleteShard
I0511 15:33:43.980305       1 syslogger.go:129] cloudbills-unsharded/0 [shard] deleted value: <nil>
I0511 15:33:43.980338       1 locks.go:473] Unlocking shard cloudbills-unsharded/0 for successful action DeleteShard
I0511 15:33:44.000684       1 vschema.go:58] deleting vschema for keyspace cloudbills-unsharded
I0511 15:33:44.008309       1 syslogger.go:129] cloudbills-unsharded [keyspace] deleted value: <nil>
I0511 15:33:44.009082       1 locks.go:283] Unlocking keyspace cloudbills-unsharded for successful action DeleteKeyspace
time="2023-05-11T15:36:55Z" level=info msg="Reconciling EtcdLockserver" controller=EtcdLockserver etcdlockserver=voicespin-vitess-cluster-gke-etcd-b0e90f0f namespace=vitess-cluster-stage
time="2023-05-11T15:36:55Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
I0511 15:36:55.161452       1 vschema.go:58] deleting vschema for keyspace cloudbills-unshard
I0511 15:36:55.181989       1 locks.go:246] Locking keyspace cloudbills-unshard for action DeleteKeyspace
I0511 15:36:55.200212       1 server.go:865] Deleting all 1 shards (and their tablets) in keyspace cloudbills-unshard
I0511 15:36:55.200257       1 server.go:871] Recursively deleting shard cloudbills-unshard/0
I0511 15:36:55.200489       1 locks.go:432] Locking shard cloudbills-unshard/0 for action DeleteShard
I0511 15:36:55.244445       1 syslogger.go:129] cloudbills-unshard/0 [shard] deleted value: <nil>
I0511 15:36:55.244469       1 locks.go:473] Unlocking shard cloudbills-unshard/0 for successful action DeleteShard
I0511 15:36:55.265989       1 vschema.go:58] deleting vschema for keyspace cloudbills-unshard
I0511 15:36:55.271507       1 syslogger.go:129] cloudbills-unshard [keyspace] deleted value: <nil>
I0511 15:36:55.272045       1 locks.go:283] Unlocking keyspace cloudbills-unshard for successful action DeleteKeyspace

### Binary Version

```sh
Version: 13.0.0 (Git revision bc4a960 branch 'HEAD') built on Tue Feb 22 14:57:47 UTC 2022 by runner@fv-az201-581 using go1.17.7 linux/amd64
```

### Operating System and Environment details

```sh
Kubernetes
```

### Log Fragments

```sh
time="2023-05-11T15:32:41Z" level=info msg="Reconciling EtcdLockserver" controller=EtcdLockserver etcdlockserver=voicespin-vitess-cluster-gke-etcd-b0e90f0f namespace=vitess-cluster-stage
time="2023-05-11T15:33:19Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
time="2023-05-11T15:33:43Z" level=info msg="Reconciling VitessCell" controller=VitessCell namespace=vitess-cluster-stage vitesscell=voicespin-vitess-cluster-gke-voicespin-gke-zone1-8ff2ce8d
time="2023-05-11T15:33:43Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
I0511 15:33:43.844645       1 vschema.go:58] deleting vschema for keyspace cloudbills-unsharded
I0511 15:33:43.851513       1 locks.go:246] Locking keyspace cloudbills-unsharded for action DeleteKeyspace
I0511 15:33:43.875317       1 server.go:865] Deleting all 1 shards (and their tablets) in keyspace cloudbills-unsharded
I0511 15:33:43.875418       1 server.go:871] Recursively deleting shard cloudbills-unsharded/0
I0511 15:33:43.877057       1 locks.go:432] Locking shard cloudbills-unsharded/0 for action DeleteShard
I0511 15:33:43.980305       1 syslogger.go:129] cloudbills-unsharded/0 [shard] deleted value: <nil>
I0511 15:33:43.980338       1 locks.go:473] Unlocking shard cloudbills-unsharded/0 for successful action DeleteShard
I0511 15:33:44.000684       1 vschema.go:58] deleting vschema for keyspace cloudbills-unsharded
I0511 15:33:44.008309       1 syslogger.go:129] cloudbills-unsharded [keyspace] deleted value: <nil>
I0511 15:33:44.009082       1 locks.go:283] Unlocking keyspace cloudbills-unsharded for successful action DeleteKeyspace
time="2023-05-11T15:36:55Z" level=info msg="Reconciling EtcdLockserver" controller=EtcdLockserver etcdlockserver=voicespin-vitess-cluster-gke-etcd-b0e90f0f namespace=vitess-cluster-stage
time="2023-05-11T15:36:55Z" level=info msg="Reconciling VitessCluster" VitessCluster=voicespin-vitess-cluster-gke controller=VitessCluster namespace=vitess-cluster-stage
I0511 15:36:55.161452       1 vschema.go:58] deleting vschema for keyspace cloudbills-unshard
I0511 15:36:55.181989       1 locks.go:246] Locking keyspace cloudbills-unshard for action DeleteKeyspace
I0511 15:36:55.200212       1 server.go:865] Deleting all 1 shards (and their tablets) in keyspace cloudbills-unshard
I0511 15:36:55.200257       1 server.go:871] Recursively deleting shard cloudbills-unshard/0
I0511 15:36:55.200489       1 locks.go:432] Locking shard cloudbills-unshard/0 for action DeleteShard
I0511 15:36:55.244445       1 syslogger.go:129] cloudbills-unshard/0 [shard] deleted value: <nil>
I0511 15:36:55.244469       1 locks.go:473] Unlocking shard cloudbills-unshard/0 for successful action DeleteShard
I0511 15:36:55.265989       1 vschema.go:58] deleting vschema for keyspace cloudbills-unshard
I0511 15:36:55.271507       1 syslogger.go:129] cloudbills-unshard [keyspace] deleted value: <nil>
I0511 15:36:55.272045       1 locks.go:283] Unlocking keyspace cloudbills-unshard for successful action DeleteKeyspace
```

**Comment by deepthi** [comment]
The way to create new keyspaces or shards with operator is to add them to the yaml. Doing them from vtadmin doesn't work because
(a) VTAdmin only creates the topo metadata. The way to actually bring up a keyspace/shard in Vitess has always been to run vttablets, and that is not something you can do from VTAdmin
(b) operator periodically reconciles and prunes metadata that it has not been told about.

Please look at the yaml files in the [operator example](https://github.com/vitessio/vitess/tree/main/examples/operator) + [the guide on the website](https://vitess.io/docs/16.0/get-started/operator/) to see how you can create a keyspace and shard(s) along with vttablets for them.
