### ISSUE TITLE
Feature Request: Enable TLS in the Go vtctlclient

### ISSUE THREAD

**Issue by erikhalperin-hub** [vitessio/vitess#13084]
### Feature Description

Currently it's not possible to add TLS to a vtctlclient programmatically created using the [Go client library.](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/vtctlclient/interface.go#L83), though there are flags that allow a human to pass in params if running vtctl from the command line.

It would be great to be able to do this from a security standpoint in order to provide end to end encryption.

### Use Case(s)

It is up to the user to decide if they want to use SSL or not, but I believe this would be a fairly common use case, as there are a lot of general security requirements that involve locking down traffic with SSL.

**Comment by frouioui** [comment]
@vitessio/cluster-management

**Comment by ajm188** [comment]
@erikhalperin-hub I'm not clear on why this is necessary. I think you can "just" (I know, sorry!) add the flags to your own program, as such:

```go
import (
    "github.com/spf13/pflag"

    "vitess.io/vitess/go/vt/vtctl/grpcclientcommon"
    "vitess.io/vitess/go/vt/vtctl/vtctlclient"
)

func main() {
    grpcclientcommon.RegisterFlags(pflag.FlagSet)
    addr := pflag.String("addr", "localhost:15999", "vtctld address")

    pflag.Parse() // will handle flags like --vtctld_grpc_{ca,cert,...}

    client, err := vtctlclient.New() // will have TLS if the flags were set via grpcclientcommon.SecureDialOption

    doStuff(client)
}

**Comment by erikhalperin-hub** [comment]
@ajm188 Interesting thanks, I actually didn't know that
