### ISSUE TITLE
Feature Request: Add metrics to vtgate to determine lag and number of vstreams assigned

### ISSUE THREAD

**Issue by twthorn** [vitessio/vitess#13099]
### Feature Description

This issue requests that metrics are added to vtgate to monitor the number of vstreams created and the lag of events relative to vttablets. There is no way to monitor these two metrics currently for vtgate. We have seen various instances in our production deploy at Slack where this would be useful, and believe other users would benefit from this additional visibility. 

### Use Case(s)

Vtgate is falling behind realtime on data from vttablet, need lag metric in order to detect this
Vtgate host has high memory usage, vstreams created count metric allows us to determine if this is the issue

**Comment by twthorn** [comment]
PR: https://github.com/vitessio/vitess/pull/13098

**Comment by frouioui** [comment]
Hello @twthorn thanks for opening this issue, can you provide a title to your issue?
