### ISSUE TITLE
Feature Request: cache stream query plans

### ISSUE THREAD

**Issue by samanthadrago** [vitessio/vitess#13263]
### Feature Description

Query plans for OLTP queries are cached; it would be nice to also cache OLAP stream query plans, both for feature parity and performance reasons. 

### Use Case(s)

At Etsy we use OLAP mode for queries. We implemented a patch to Vitess to cache the query plans for stream queries to help improve query performance.

**Comment by mattlord** [comment]
cc @vitessio/query-serving
