### ISSUE TITLE
Bug Report: Backup/Restore metrics deleted in v16

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#13336]
### Overview of the Issue

In #11520, we removed the `local_metadata` table from the sidecar db. Along with metadata used for orchestrator integration, this table also used to store 2 additional pieces of information:
```
	// Add backupTime and restorePosition to LocalMetadata
	params.LocalMetadata["RestoredBackupTime"] = manifest.BackupTime
	params.LocalMetadata["RestorePosition"] = mysql.EncodePosition(manifest.Position)
```
This information is no longer available on a restored vttablet.

### Reproduction Steps

On a running vitess cluster (local example will suffice):
- take a backup of a keyspace/shard
- restore one of the tablets from backup (or create a new tablet from backup)
- there's no way to know what time or position the tablet was restored from

### Binary Version

```sh
main, v17, v16
```

### Operating System and Environment details

```sh
any
```

**Comment by frouioui** [comment]
@deepthi @rohit-nayak-ps can we close this issue?
