### ISSUE TITLE
Question: how many nodes can vitess support? the largest deployment possible

### ISSUE THREAD

**Issue by kolinfluence** [vitessio/vitess#13340]
### Question

i saw planetscale mentioned 70000 nodes, i wonder if this nodes are replicated nodes or primary nodes.
https://www.infoworld.com/article/3631149/planetscale-review-mysql-at-cloud-scale.html

what's the maximum number of nodes able to be supported by vitess?
because each recommended node size is 250GB database size. so i'm wondering what's the maximum limit i can stretch with vitess.

with reference to this question which is not answered:
https://github.com/vitessio/vitess/issues/13225

**Comment by mattlord** [comment]
This was already answered in 13225. As noted, the limit will come from something other than Vitess itself.

Also, please note that the Vitess Slack is the best place to ask these kinds of questions.
