### ISSUE TITLE
Bug Report: SHOW VSCHEMA TABLES returns incorrect result

### ISSUE THREAD

**Issue by tanjinx** [vitessio/vitess#13475]
### Overview of the Issue

`show vschema tables` returns tables that are not in vschema, i.e. temporary tables created on the tablets directly.

### Reproduction Steps

```
// create a dummy table on the tablet
[vt_loadtest]> create table blabla_t(c1 int not null, c2 int, primary key(c1));
Query OK, 0 rows affected (0.01 sec)

// then run SHOW VSCHEMA TABLES on one vtgate
mysql> show vschema tables;
+-------------------------------+
| Tables                        |
+-------------------------------+
| blabla_t
...

// the table is not in vschema
$ vtctl GetVSchema loadtest|grep "\": {$"|grep blabla_t|wc -l
0
```

### Binary Version

```sh
v14.0.5
```

### Operating System and Environment details

```sh
linux amd64
```

**Comment by mattlord** [comment]
Hi @tanjinx !

I think that this might be expected/intentional. Test case on main:
```
git checkout main 
make build
cd examples/local

./101_initial_cluster.sh

vtctldclient GetVSchema commerce

mysql commerce -e "create table stest (id int)"
mysql commerce -e "show vschema tables"

vtctldclient GetVSchema commerce
```

If you disable the schema tracker in the vtgate:
```
diff --git a/examples/common/scripts/vtgate-up.sh b/examples/common/scripts/vtgate-up.sh
index 03b85869e5..9c81d9fdb4 100755
--- a/examples/common/scripts/vtgate-up.sh
+++ b/examples/common/scripts/vtgate-up.sh
@@ -40,6 +40,7 @@ vtgate \
   --service_map 'grpc-vtgateservice' \
   --pid_file $VTDATAROOT/tmp/vtgate.pid \
   --mysql_auth_server_impl none \
+  --schema_change_signal=false \
   > $VTDATAROOT/tmp/vtgate.out 2>&1 &

 # Block waiting for vtgate to be listening
```

And run the same steps, then the `stest` table does not show up. I think this is because vtgate adds the new table to its vschema cache as well (not stored/updated in the topo server) via the schema tracker.

I will let @vitessio/query-serving investigate though.

Thanks!

**Comment by GuptaManan100** [comment]
Yes, @mattlord is right, if schema-tracking allows vtgates to augment the vschema they have cached. This is intentional behaviour.
