### ISSUE TITLE
Feature Request: Add support for request_context when executing Online DDL via vtgate

### ISSUE THREAD

**Issue by vkovacik** [vitessio/vitess#13631]
### Background
We would like to use [request_context](https://vitess.io/docs/16.0/reference/programs/vtctl/schema-version-permissions/#applyschema) feature of Online DDL to set an idempotency identifier. Unfortunately `request_context` is supported only when schema is applied via vtctlclient but not via vtgate.  

### Request
Add support for `request_context` when submitting DDL via vtgate. Suggested session variable could be `@@ddl_request_context`.
This is a follow up of the request raised in [PR that implemented `request_context`](https://github.com/vitessio/vitess/pull/9107).

### Use Case(s)

We use Alembic for DB schema migrations. Each migration executes DDL statements via vtgate. The migration may be applied partially only to a subset of the shards. It is currently not possible to retry DDL (via vtgate) to fix the shards that had failed the migration.

**Comment by shlomi-noach** [comment]
Thank you for the feature request. It makes sense, I will look into it.
