### ISSUE TITLE
sql: Vitess cannot support Grafana 10+ CTEs

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#13632]
We've used Vitess for Grafana persistence for several years, but after upgrading to v10, certain functionality including dashboard list/search fails due to usage of CTEs. This is a known issue, I just wanted to call this out specifically since we have tracked compatibility with major projects in the past. Feel free to close if it isn't useful, but it'll at least help anyone searching.

`"Search failed" error="Error 1235: unsupported: with expression in select statement"`

Related issues:
- https://github.com/vitessio/vitess/issues/4099
- https://github.com/vitessio/vitess/issues/9459

**Comment by systay** [comment]
@derekperkins Any chance you could share the query that is breaking vtgate?

**Comment by derekperkins** [comment]
There's a test here for recursive queries
https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/sqlstore.go#L363-L392

And a comment about how it relates to Vitess
https://github.com/grafana/grafana/issues/73725#issuecomment-1793547863

**Comment by derekperkins** [comment]
I submitted a PR based on that comment, hopefully they accept it and it works
- https://github.com/grafana/grafana/pull/83357

**Comment by derekperkins** [comment]
Still trying to get this to work. This has been longer coming, but `go-sql-driver/mysql` just released a new version that supports a `/` in the db name. I also have a PR into Grafana to use that new dependency, so that I can use shard targeting to allow the recursive queries to execute.

- https://github.com/go-sql-driver/mysql/issues/1534
- https://github.com/grafana/grafana/pull/84131

**Comment by harshit-gangal** [comment]
Now that Vitess have CTE support, do you want to try it?

**Comment by derekperkins** [comment]
Planning on rolling out v21 this weekend, then I'll try it

**Comment by derekperkins** [comment]
v21 actually made things worse. Previously, Grafana detected that recursive CTEs weren't supported and would fallback to other mechanisms. Now that Vitess says that they are supported, it uses the regular recursive SQL, but that fails. Here is the vttablet log

```
tabletserver.go:1587] Unknown column 'n' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: grafanaAdmin): Sql: "with recursive cte as (select :vtg1 /* INT64 */ from dual union all select n + :vtg1 /* INT64 */ from cte where n < :n /* INT64 */) select n from cte", BindVars: {#maxLimit: "type:INT64 value:\"50001\""n: "type:INT64 value:\"2\""vtg1: "type:INT64 value:\"1\""}
```

**Comment by deepthi** [comment]
That's a bummer. Can you create a separate issue with the query so that we can try to fix it?

**Comment by systay** [comment]
@derekperkins wdyt - can we close this issue now?

**Comment by derekperkins** [comment]
Sure. I'll open it again once this is available in a release if there are any other issues
