### ISSUE TITLE
Backup: address scenario where file `Close()` hangs indefinitely

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#13677]
Backup/restore supports a variety of backup file read/write implementations. It can read/write local files, or it can read/write from some cloud, or it can use an external command.

We have seen scenarios where trying to `Close()` a file, hangs. This was first addressed as early as https://github.com/vitessio/vitess/pull/5193. Closing the file is at the very end of the backup/restore process. However, it is nonetheless a critical part of the flow. If a file cannot be `Close()`d, we cannot vouch for the backup.

Ideally, the backup process shouldn't hang forever. There needs to be some timeout `Close()`ing the file. And timing out should fail the backup operation. But another thing to consider is that the `Close()` operation may still hang for hours. Depending on the implementation, this might hold resources or file locks.

More related discussion in https://github.com/vitessio/vitess/pull/5193 and https://github.com/vitessio/vitess/pull/13668.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/vitessio/vitess/pull/13668

**Comment by frouioui** [comment]
As mentioned in the previous comment, issue is fixed.
