### ISSUE TITLE
passdown show vitess migration query to vttablet

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#13706]
Currently, VTGate generates select query and send that to vttablet, this created version dependency.
The support for the query is added in vttablet already via https://github.com/vitessio/vitess/pull/12688, now vtgate have to stop generating the select query and send the show query as-is to vttablet.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/vitessio/vitess/pull/13726
