### ISSUE TITLE
Migrate `OnlineDDL Launch`

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#13718]

**Comment by ajm188** [comment]
@shlomi-noach For the "all" side on the CLI/rpc side at least, I was thinking we won't need separate commands (right now it's `launch-all` and `launch <uuid>`) instead similar to `show` where we take `launch {<uuid>|'all'}`. Thoughts?

**Comment by shlomi-noach** [comment]
Agreed. We reuse the same command but the argument changes. This was also my re-implementation in `vtctl`: https://github.com/vitessio/vitess/pull/12963
