### ISSUE TITLE
Bug Report: it reports ”column list does not match values“ when execute insert DML

### ISSUE THREAD

**Issue by lujiashun** [vitessio/vitess#13745]
### Overview of the Issue

when i execute this sql in the vtgate （vitess 16）， it reports ”column list does not match values“.
```
use customer;
alter vschema create vindex myhash using hash;
create table test_ljs(customer_id bigint, next_id bigint , cache bigint, primary key(customer_id));
alter vschema on test_ljs add vindex myhash(customer_id ) using hash;
insert into test_ljs values(1,2,8);
```

![image](https://github.com/vitessio/vitess/assets/112846998/0187bbd7-5aee-4d0e-8b34-e38fcefd0779)

if i use explicit about the column names in your INSERT， it works well.

`insert into test_ljs (customer_id, next_id, cache) values (1,2,8);`

if i  execute this sql for  a  while after the vshcema ddl "alter vschema on test_ljs add vindex myhash(customer_id ) using hash;"， the sql works well "insert into test_ljs values(1,2,8);"

### Reproduction Steps

just to see the overview of the issue

### Binary Version

```sh
[vitess@localhost local]$ vtgate --version
Version: 16.0.1
```

### Operating System and Environment details

```sh
[vitess@localhost local]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

**Comment by harshit-gangal** [comment]
This is an expected behaviour.
- Vschema should provide the column list and make the table authoritative.
- Otherwise, the query has to wait till schema-tracking kicks in and updates the column list for the table on its own.
Once, either of the two happens the query will start working.

**Comment by lujiashun** [comment]
@harshit-gangal ,  wha

> This is an expected behaviour.
> 
> * Vschema should provide the column list and make the table authoritative.
> * Otherwise, the query has to wait till schema-tracking kicks in and updates the column list for the table on its own.
>   Once, either of the two happens the query will start working.

@harshit-gangal , how to do to let the first condition happens "Vschema should provide the column list and make the table authoritative."

**Comment by harshit-gangal** [comment]
checkout the documentation https://vitess.io/docs/17.0/user-guides/vschema-guide/advanced-vschema/#authoritative-list
Let us know if you have more questions so that we can improve our documentation.
