### ISSUE TITLE
Bug Report: Vttbalet memory spikes after upgarde to v16 during backup to AZ blob storage

### ISSUE THREAD

**Issue by gairadzi** [vitessio/vitess#13771]
### Overview of the Issue

After upgrading our vitess cluster to v16.0.2 we see that when issuing the `Backup` command on a tablet the vttablet container's memory spikes (the size of the DB being backup up has little effect on the total memory needed).

### Reproduction Steps

Run `vtctlclient Backup <TABLET_NAME>` and check the memory usage on the vttablet container in that pod:
![image](https://github.com/vitessio/vitess/assets/13506295/45daa0f8-0781-4798-a5a5-52583a7b1346)

Including the `allocs` & `heap` debug profiles from the vttablet during the backup:
[allocs.zip](https://github.com/vitessio/vitess/files/12327096/allocs.zip)
[heap.zip](https://github.com/vitessio/vitess/files/12327097/heap.zip)

### Binary Version

```sh
Using the `vitess/lite:v16.0.2-mysql80` vitess images
```

### Operating System and Environment details

```sh
Using the `vitess/lite:v16.0.2-mysql80` vitess images
```

**Comment by shlomi-noach** [comment]
v17 backport: https://github.com/vitessio/vitess/pull/13775
v16 backport: https://github.com/vitessio/vitess/pull/13774
