### ISSUE TITLE
Release Summary for new `vtctldclient` vrep/onlineddl commands

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#13826]
This is a tracking issue to cover the following release notes before 18.0:

> > How were you planning to manage the release summary? Once we're (hopefully) done with the OnlineDDL and VReplication work, we could add one (both) or two (individual) entries in the summary.md file about support for these being added in vtctldclient.
> 
> I think let's do a "new in vtctld server/client section" with bullets for each. How does that sound to you?

Sure, sounds good.

_Originally posted by @mattlord in https://github.com/vitessio/vitess/issues/13738#issuecomment-1684214194_

This issue also covers adding related notes to the 18.0 GA release blog post.

**Comment by frouioui** [comment]
@ajm188, is this still planned for v18.0.0?

**Comment by mattlord** [comment]
> @ajm188, is this still planned for v18.0.0?

Yeah, I still plan to do it. I need to actually finish the VReplication commands though first. 🙂
