### ISSUE TITLE
Bug Report: v16.0.3 VDiff not respecting source or target cell specifications for shard-by-shard workflow? 

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#13831]
### Overview of the Issue

Scenario:
  * Running a VDiff on a shard-by-shard workflow
  * Kicking off a VDiff on the workflow with something like:
```
vtctlclient --server localhost:15999 VDiff -- --source_cell="cell1" --target_cell="cell2" --tablet_types="in_order:REPLICA,PRIMARY" --filtered_replication_wait_time=5m  keyspace_lookup.workflow1 create
```

However, if you look at the target tablet (PRIMARY) for the workflow's logs, you see:

```
I0822 02:02:46.351043       1 tablet_picker.go:186] Unable to resolve cell all, ignoring
I0822 02:02:46.351091       1 tablet_picker.go:136] No healthy serving tablet found for streaming, shard keyspace_lookup.40-80, cells [all], tabletTypes [REPLICA PRIMARY], sleeping for 30.000 seconds.
```

Which then just loops.

`all` is supposed to the the default for the VDiff, using all cells, but that does not seem to work either?

Also tried:
  * to specify a list of cells for `--source_cell` and `--target_cell`
  * specify a cell alias that covers all the cells for `--source_cell` and `--target_cell`
  * create a cell alias called `all` and use that for `--source_cell` and `--target_cell`

None of these attempted workarounds worked.

What did eventually work to get the VDiff going was to reparent the target primary into the same cell as the source primary, but obviously would want to avoid that.

### Reproduction Steps

See above

### Binary Version

```sh
16.0.3
```

### Operating System and Environment details

```sh
x86_64
```

### Log Fragments

```sh
See above
```

**Comment by mattlord** [comment]
There's some missing variable(s) here. This simple test on vitessio/vitess/release-16.0 and planetscale/vitess/latest-16.0 both demonstrate that the value is *not ignored*, because it's used and the VDiff fails to start because there are no source tablets in the specified cell:
```bash
pushd ${VTROOT}/examples/local

source ../common/env.sh

CELL=zone1 ../common/scripts/etcd-up.sh

CELL=zone1 ../common/scripts/vtctld-up.sh

vtctldclient AddCellInfo --root /vitess/zone2 --server-address "${ETCD_SERVER}" zone2

./101_initial_cluster.sh

mysql < ../common/insert_commerce_data.sql

./201_customer_tablets.sh

./202_move_tables.sh

vtctlclient VDiff -- --format=json --source_cell=zone2 customer.commerce2customer

vtctlclient VDiff -- --format=json customer.commerce2customer show last

sleep 10

vtctlclient VDiff -- --format=json customer.commerce2customer show last

command mysql -u root --socket=${VTDATAROOT}/vt_0000000200/mysql.sock --binary-as-hex=false -e "select * from _vt.vdiff\G"

grep -Ei 'vdiff|tablet_picker' ${VTDATAROOT}/tmp/vttablet*.INFO*
```

I've also verified various correct/expected behaviors on main. So focusing specifically on v16 here.

@aquarapid is there some environment where you're able to repeat this that I can examine more closely?
