### ISSUE TITLE
Allow for explicit bind address in `servenv`

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#13891]
This is a follow-up issue of https://github.com/vitessio/vitess/pull/12987 that should be carried on in v18.

From #12987:
> By moving everything away from the default mux to an explicit mux for the servenv, we can make this configurable in the near future.
> The changes here now explicitly add the profiling endpoints so that we can make that optional in a follow up.

**Comment by k1nho** [comment]
Hi 👋 @frouioui , I would like to take on this issue. I'm new to Vitess and would appreciate any pointers

**Comment by frouioui** [comment]
> Hi 👋 @frouioui , I would like to take on this issue. I'm new to Vitess and would appreciate any pointers

Hey @k1nho, I am currently working on this here: https://github.com/vitessio/vitess/pull/13188.
