### ISSUE TITLE
VTGate's foreign key operations should ignore vitess-internal tables

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#13894]
Work of VTGate foreign key support described in https://github.com/vitessio/vitess/issues/12967, and some substantial work in https://github.com/vitessio/vitess/pull/13823.

Vitess maintains internal tables of the following forms:

- GC tables, e.g. `_vt_HOLD_...`
- Online DDL tables, e.g. `_..._vrepl` tables

Those tables can be identified by `IsInternalOperationTableName()`, as defined here:

https://github.com/vitessio/vitess/blob/99271d4d92a4d86f3dbd22e31ab295119d3f3ca2/go/vt/schema/name.go#L58-L71

Reasoning is that these tables are non-production, and are _likely_ to be out of sync with parent/child relationships.

- A `*_vrepl` table is either ongoing an Online DDL operation via `vreplication`, which means it's being slowly and asynchronously populated from another table, or is the "leftover" of the original table once cut-over is complete. In both cases the table cannot be guaranteed to agree to FK constraints. In fact, it is harmful for VTGate to work with these queries because these are being populated by `vreplication`.
- A `_vt_DROP...` table is for example one that's about to be dropped. It does not make sense to withhold operations in production table due to e.g. missing rows in this table.

VTGate should completely ignore any parent-child relationship where either parent or child (or both) have an internal table name.

**Comment by harshit-gangal** [comment]
The best is to avoid sending any information from the vttablet to vtgate about those table that they exists. We would not need any logic in VTGate for it.

**Comment by shlomi-noach** [comment]
@harshit-gangal does that mean one would never be able to e.g. `SELECT COUNT(*) FROM _..._vrepl`? I'm not opposed, just trying to understand the impact.

How would we go about not sending information from `vttable` about those tables?

**Comment by harshit-gangal** [comment]
For unsharded you can, for sharded you cannot because we do not know the sharding key. Nothing to lose here.

**Comment by shlomi-noach** [comment]
Solution proposed in https://github.com/vitessio/vitess/pull/13897
