### ISSUE TITLE
End-to-end test to validate the foreign key implementation and interactions between VTGate and VReplication

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#13954]
## Description

As part of adding Foreign Key support in Vitess we have changes mainly at the VTGate layer and also for imports, in
VReplication. We need an e2e test to make sure that, once we have imported data into Vitess and all queries run via
VTGate, other VReplication workflows will continue to work. This will confirm that the binlogs contain the correct
events, also in the case of cascades.

This test will use the schema and other components from and extend the stress test from https://github.com/vitessio/vitess/pull/13799.

### Test Imports

We set up and populate a source keyspace and run a MoveTables workflow using its new atomic copy mode to simulate an 
import into Vitess.

* Set up an unsharded source cluster `sourceKeyspace` with tables that use foreign keys. The data for this cluster is
  populated using mysql (i.e. not through vtgate. This is so that we emulate a source MySQL database, uncontrolled by Vitess. The single-copy vreplication workflow was designed to handle imports of raw databases that may have cascading FK rules. This approach will validate that.
* Once we have a reasonable amount of data in the source, we import this data using the new atomic copy mode of
  MoveTables into a new, again unsharded,`targetKeyspace-1`. Once the copy phase is done, we wait for some time,
  before switching traffic, so that we are testing the replication mode as well.
* We will run reverse replication on this workflow. We continue to populate data for some time and then do a
  ReverseTrafficSwitch to switch traffic back to the source keyspace.
* After some time we confirm that the source and target stay in sync using VDiff and then do a final SwitchTraffic
  to `targetKeyspace-1`.

### Test VTGate query serving changes

Next, we will populate data via vtgate on the imported keyspace so that we can check that the correct query 
generation is happening at the vtgate layer for foreign key cascades.

* We stop the direct data population and switch to populating using vtgate.
* We then set up another unsharded keyspace, `targetKeyspace-2` and we run a regular (i.e. _not_ using atomic copy)
  MoveTables from `targetKeyspace-1`  to `targetKeyspace-2`.
* We will use only `primary` tablets as sources for this workflow, so that we stream directly from the binlogs which 
  the vtgate layer is generating, i.e., not involving the mysql replication mechanism.

### Test other VReplication workflows

* We will then reshard `targetKeyspace-2`, into (say) two shards, `targetKeyspace-2-80` and `targetKeyspace-2-80-`.
* Run a Materialize workflows for: just the parent table, just the child table, and both parent and child tables.
* We will use only `replica`s as sources for these workflows, so that we stream from the binlogs generated by the 
  mysql replication mechanism.
* Like the existing setup in https://github.com/vitessio/vitess/pull/13799 , setup a special replica where we forcibly run DROP CONSTRAINT for all foreign keys, which in turn validates that vtgate cascades writes correctly.

## Data population

Data will be populated based on the approach in https://github.com/vitessio/vitess/pull/13799. A
fuzzer-based online query generator will be added to this based on the work being done currently in vtgate.

## Enhancements
* Add OnlineDDL workflows in addition to the other VReplication workflows.

**Comment by shlomi-noach** [comment]
Overall looks good!

In **Test Imports**, I just find it important to clarify why we should write directly to MySQL: this emulates a source MySQL database, uncontrolled by vitess. The single-copy vreplication workflow was designed to handle imports of raw databases that may have cascading FK rules. This approach will validate that.

In **Test other VReplication workflows**, I'd also add:

- Like the existing setup in #13799 , setup a special replica where we forcibly run `DROP CONSTRAINT` for all foreign keys, which in turn validates that `vtgate` cascades writes correctly.

**Comment by GuptaManan100** [comment]
A bunch of different scenarios for query-serving with foreign keys were tested in this PR - https://github.com/vitessio/vitess/pull/13870. I am currently working on a follow up which would fuzz the data in the test and run it like a stress test.
