### ISSUE TITLE
Bug Report: Potential leak of non-stopping goroutines

### ISSUE THREAD

**Issue by LundstromJoseph** [vitessio/vitess#14201]
### Overview of the Issue

When using workload OLAP, goroutines are infinitely growing inside VTGate, leading to infinite memory usage.
We noticed this in a real world environment, gladly we weren't dependent on OLAP and reverted back to default.
It shows in the default local docker as well (https://vitess.io/docs/17.0/get-started/local-docker/). 

### Reproduction Steps

1. Run Vitess using the default docker (https://vitess.io/docs/17.0/get-started/local-docker/)
2. Run `mysql` inside the docker
3. Run `set workload="olap";`
4. Run `BEGIN; SELECT * FROM customer; COMMIT;` a few times (maybe 10)
5. Watch as the amount of goroutines grow at http://127.0.0.1:15001/debug/pprof/ and never shrink again

It seems every single transaction spawns a goroutine that never stops.

### Binary Version

```sh
vtgate version Version: 19.0.0-SNAPSHOT (Git revision 370696b6a9d40e1ef031fd69525f0bb5a2a94487 branch 'main') built on Fri Oct  6 09:35:48 UTC 2023 by vitess@buildkitsandbox using go1.21.2 linux/amd64
```

### Operating System and Environment details

```sh
MacOS 14.0
Apple Silicon M2
Ran inside Docker though
```

**Comment by GuptaManan100** [comment]
Thank you for reporting the issue @LundstromJoseph. It has been fixed by https://github.com/vitessio/vitess/pull/15293 and will be backported to all supported versions of Vitess.
