### ISSUE TITLE
Feature Request: Uninstall bootstraped deps

### ISSUE THREAD

**Issue by FirePing32** [vitessio/vitess#14288]
### Feature Description

A bash script to uninstall dependencies installed by `./bootstrap.sh`.

### Use Case(s)

These dependencies take up ~9 GB of disk space. Manually clearing them up and removing symlinks is too much of a manual process.

**Comment by deepthi** [comment]
I doubt that we'll get this prioritized any time soon. Are you able to contribute a script?

**Comment by FirePing32** [comment]
@deepthi I can try working on it. Please assign it to me.

**Comment by frouioui** [comment]
Reviewed the PR, thank you for opening this!
