### ISSUE TITLE
Bug Report: When performing an insert with seqence, a mismatch between the column count and the value count can result in an array index out of bounds error.

### ISSUE THREAD

**Issue by wlx5575** [vitessio/vitess#14322]
### Overview of the Issue

Bug Report: When performing an insert with seqence, a mismatch between the column count and the value count can result in an array index out of bounds error.
Test SQL:INSERT INTO seqtest (customer_id, order_date, total_amount, string) VALUES (11, '2023-09-02', 200.00);
The location of the array index out of bounds error：
![image](https://github.com/vitessio/vitess/assets/116170461/e768003b-2660-4b17-b51a-e430b678c31e)

The expected error message is "VT03006: column count does not match value count at row 1“

The following judgment can be made in advance

![image](https://github.com/vitessio/vitess/assets/116170461/3c46322e-f93d-4dd2-a897-481efdb91e0d)

### Reproduction Steps

{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    },
  "tables": {
  	"seqtest": {
      "columnVindexes": [
        {
          "column": "customer_id",
          "name": "binary_hash"
        }
      ],
      "autoIncrement": {
        "column": "sequence_id",
        "sequence": "vindexs_new.seqtest_seq"
      }
    }
  }
}	
}

### Binary Version

```sh
Version: 17.0.2
```

### Operating System and Environment details

```sh
Operating system  MAC
Kernel version Darwin 21.1.0
Architecture x86_64
```

**Comment by FirePing32** [comment]
So should the whole insert operation be halted, or only the specific rows which are invalid ?

**Comment by dbussink** [comment]
> So should the whole insert operation be halted, or only the specific rows which are invalid ?

since it needs to be transactional, the whole insert operation needs to fail. Can you also make sure to add that to tests in the PR as well?
