### ISSUE TITLE
Feature Request: Support invisible columns

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#14367]
### Feature Description

MySQL supports invisible columns that are valid to use explicitly, but that won't be included when using `*` expressions.

Vitess does not support this, and it should.

```sql
mysql> CREATE TABLE t1 (
    ->   i INT,
    ->   j DATE INVISIBLE
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 (i,j) values (0, '2023-01-01');
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+------+
| i    |
+------+
|    0 |
+------+
1 row in set (0.00 sec)
```

**Comment by harshit-gangal** [comment]
Should the fix be backported to older versions as the invisible columns are broken when schema tracking is enabled? From v15 onwards schema tracking is default.
