### ISSUE TITLE
VReplication: workaround for --all-tables when `FLUSH TABLES WITH READ LOCK` is unavailable

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#14577]
When importing data from external source via `MoveTables --all-tables`, Vitess issues a `FLUSH TABLES WITH READ LOCK` (FTWRL). Some external database, namely RDS/Auora, do not allow FTWRL. Vitess should use an alternative method.

**Comment by rohit-nayak-ps** [comment]
Closed via #14578
