### ISSUE TITLE
Bug Report: vtctlclient failed to run backupShard command when replica(s) is not_serving

### ISSUE THREAD

**Issue by jwangace** [vitessio/vitess#14602]
### Overview of the Issue

vtctlclient failed to run backupShard command when:
**There is a bad replica in the shard [  chance rate: 1/(n-1) where n equals to number of vttablets in a shard]** 

When this happens and causes backupShard to fail, all the consecutive backupShard will fail and never be able to take a backup, until humans intervene and fix the bad replica, putting risks of production data lost.

There was a report on this: https://github.com/vitessio/vitess/issues/8908, which addressed **ShardReplicationStatuses** as the cause, has been closed with a fix https://github.com/vitessio/vitess/pull/8966 doesn't really fix.

I want to re-raise this issue and will try to put up a PR for a potential fix. 

### Reproduction Steps

This can be consistently reproduced in K8s by making one of (or all of) the replicas in not ready status, for example, when replica(s) is Pending or Dead, the status of that replica is not_serving.

This can be observed from vtctld, log shows vtctld tried to connect to a bad vttablet.

<img width="1532" alt="Screenshot 2023-11-24 at 11 41 49 AM" src="https://github.com/vitessio/vitess/assets/121262788/4cebd2d0-b127-4efb-8b78-f0406441aace">

### Binary Version

```sh
This issue should be present on all vitess versions.
```

### Operating System and Environment details

```sh
vitess deployed in k8s, and this is not a version-specific issue.
```

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/vitessio/vitess/pull/14604

**Comment by shlomi-noach** [comment]
fixed by https://github.com/vitessio/vitess/pull/14604
