### ISSUE TITLE
Bug Report: vtorc leaves shard with two primaries, both accepting queries

### ISSUE THREAD

**Issue by makmanalp** [vitessio/vitess#14637]
### Overview of the Issue

I was directed by Deepthi to open a ticket after a long debugging session together [here](https://vitess.slack.com/archives/C0PQY0PTK/p1700596003219569) and [here](https://vitess.slack.com/archives/CMPP9K2CE/p1700600084621709).

TLDR: some shards had 2 primaries both serving queries, which should never happen
- Something causes a vtorc failover (we have multiple examples, see reproduction section)
- After failover, shards are broken in a way that the old replica has writes hung due to a hung semisync ack. This is not entirely unprecedented ([mysql bug: "losing semisync acks could stall the primary"](https://bugs.mysql.com/bug.php?id=104015) - thanks JFG) but what's scary and new is that this results in the old primaries serving real queries to clients, meaning:
  - Writes sent to old primaries fail (timeout, pool full due to hung writes, vtgate rejects flat out, etc)
  - Old primaries serve stale data since writes are hung
- We've traced this to a demotion that got stuck halfway and never could complete and left the old primary there, while vtorc's promotion added a new one.

----

Regarding who is marked primary where:
- In the vttablet UIs all seems good: the old primary is now marked REPLICA
- In the vtgate UI's healthcheck section we see two tablets marked primary, one with a PrimaryStartTime of `-6213559680` which is the difference in seconds between jan 1st, 1970 (unix epoch time 0) and jan 1st 0001 (golang timestamp 0), indicating that that's just a null value:

![image](https://github.com/vitessio/vitess/assets/161965/3255b119-d100-48e1-a056-4f3bf1f3f7fb)

- In the vtctld UI we see both tablets marked `master`.
- `vtctl TopoCat -decode_proto_json -long -- keyspaces/$KEYSPACE/shards/80-/Shard` gives the correct primary.
- If l look at the tablets in the topo: `vtctl TopoCat -decode_proto_json -long -cell vt_green tablets/<newprimaryUID>/Tablet`: 

```
alias:{cell:"vt_green" uid:289066700} hostname:"..." port_map:{key:"grpc" value:...} port_map:{key:"vt" value:...} keyspace:"AutomationPlatform" shard:"80-" key_range:{start:"\x80"} type:PRIMARY db_name_override:"AutomationPlatform" mysql_hostname:"..." mysql_port:... primary_term_start_time:{seconds:1700528839 nanoseconds:840902764} db_server_version:"..." default_conn_collation:45
```
the old primary however still says PRIMARY too though:
```
alias:{cell:"vt_green" uid:289066701} hostname:"..." port_map:{key:"grpc" value:...} port_map:{key:"vt" value:...} keyspace:"AutomationPlatform" shard:"80-" key_range:{start:"\x80"} type:PRIMARY db_name_override:"AutomationPlatform" mysql_hostname:"..." mysql_port:... primary_term_start_time:{seconds:1700493209 nanoseconds:915036668} db_server_version:"..." default_conn_collation:45
```
however the primaryStartTime there is not actually negative, unlike in the vtgate healthcheck UI.

When we look into the old primary we find it in the following state:
- The heartbeat query is hung in the processlist due to semisync ack (mysql bug mentioned above): `| 194300 | ...      | localhost | ... | Query   | 72395 | Waiting for semi-sync ACK from slave | INSERT INTO _vt.heartbeat (ts, tabletUid, keyspaceShard) VALUES (1700528819058406187, 289066701, '...:80-') ON DUPLICATE KEY UPDATE ts=VALUES(ts), tabletUid=VALUES(tabletUid)`. This query is unkillable.
  - `SHOW MASTER STATUS` also hangs (due to bug above) and there's a few of these piled up from the dba user in the tablet (from `grpcServer.handleStream -> tabletmanagerservice._TabletManager_FullStatus_Handler`)
  - Last binlog entry via mysqlbinlog is long ago, corresponding with the time of the incident, so it's not just the timestamp.
  - When we check the data we can confirm that it's missing rows the primary has.
  - There's other stuff also hung like `FLUSH BINARY LOGS` and `LOCK TABLES FOR BACKUP` and some `commit`s but I won't get into more details since the mysql bug itself is not our subject, but all this to say that writes are hung, while reads proceed OK.

We know that the old primary is taking and responding to real queries because:
- In the tablet UI we see it doing queries in the chart.
- When we look at the mysql general log we see queries flowing to it with `target: KeySpaceName.primary` (which is again, odd), and these are not marked as warming reads.

When I trigger a thread dump I find the heartbeatwriter stuck on IO wait to the `Waiting for semi-sync ACK` query from the processlist I mentioned above:
```
goroutine 17151358 [IO wait, 1210 minutes]:
internal/poll.runtime_pollWait(0x7ffb34227108, 0x72)
    runtime/netpoll.go:302 +0x89
...
vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker.(*heartbeatWriter).writeHeartbeat(0xc0027c9ec0?)
    vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker/writer.go:198 +0x1e
vitess.io/vitess/go/timer.(*Timer).run(0xc000476740, 0xc004d4e040)
    vitess.io/vitess/go/timer/timer.go:112 +0x10b
created by vitess.io/vitess/go/timer.(*Timer).Start
    vitess.io/vitess/go/timer/timer.go:86 +0xed
```

Then, searching for `0xc000476740` I find another goroutine hung while trying to `endPrimaryTerm / serveNonPrimary`, stuck on  that same`timer.Stop` while enabling heartbeat writes (because it's waiting on `timer.Start` from the above hung query).
```
  goroutine 96 [chan send, 1208 minutes]:
  vitess.io/vitess/go/timer.(*Timer).Stop(0xc000476740)
      vitess.io/vitess/go/timer/timer.go:151 +0x9a
  vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker.(*heartbeatWriter).enableWrites(0xc0012c0500, 0x35?)
      vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker/writer.go:255 +0x75
  ...
  vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker.(*ReplTracker).MakeNonPrimary(0xc00043af00)
      vitess.io/vitess/go/vt/vttablet/tabletserver/repltracker/repltracker.go:113 +0x116
  vitess.io/vitess/go/vt/vttablet/tabletserver.(*stateManager).serveNonPrimary(0xc0013921c0, 0x30e2e87?)
      vitess.io/vitess/go/vt/vttablet/tabletserver/state_manager.go:469 +0x138
  ...
  vitess.io/vitess/go/vt/vttablet/tabletmanager.(*tmState).ChangeTabletType(0xc00050fd00, {0x2b90498, 0xc003a1c0c0}, 0x2, 0x0)
      vitess.io/vitess/go/vt/vttablet/tabletmanager/tm_state.go:225 +0x485
  vitess.io/vitess/go/vt/vttablet/tabletmanager.(*TabletManager).endPrimaryTerm(0xc0004bc780, {0x2b90428, 0xc001178300}, 0xc0062ee800)
  ...

```
So there's our root cause as to why the topo never got updated. 

Deepthi thinks the null / negative value for the timestamp comes from [here](https://git.hubteam.com/HubSpot/vitess-upstream/blob/744f753298a3278d3f9a395c56ebd05c786ed925/go/vt/vttablet/tabletmanager/tm_state.go#L218) which happens when tabletType == topodatapb.TabletType_PRIMARY is false. Though it's not entirely clear to me how we land there, but I haven't traced the call through either.

---

To put it all together: semisync hangs, meaning heartbeat write / replication tracker hangs, meaning timer start/stop hangs, meaning tablet shutdown hangs, meaning stuff doesn't get updated in the vitess zookeeper topo, meaning old primary record is still there while new one is also there, meaning the old primary gets queries.

The open questions are:
- Should endPrimaryTerm timeout / exit somehow instead of getting stuck even if the underlying query is stuck?
  - Was it desirable that the heartbeat write's timer.Run block the timer.Stop of the shutdown? I think no, though probably a timeout like the above suggested would prevent this.
- Should vtorc clean up the other tablet records that are marked primary when it does a promotion / "external" reparent?
- I'm not sure I understand the mechanism via which the vtgates send queries / round robin? to both primaries and not just the one that has higher primaryStartTime or whatever - should this be different or is there a case where this behavior is desirable?

Let me know if I can provide any more data.

### Reproduction Steps

Unfortunately reproducing is tricky, though we've observed it in 2 separate incidents:

- The first case was organic, we think (still investigating) vtorc kicked in due to a zk network blip (`failed to read from connection: read tcp ...: read: connection timed out `) and in the aftermath 20-30 keyspaces were affected, we're unsure if perhaps the kubernetes pods themselves also had network issues, perhaps that was the true cause.
- The second time was during a manual chaos test where we ran `iptables -I INPUT -j DROP` and `iptables -I OUTPUT -j DROP` against the vttablet (which lives in a separate host than the vtgates and everything else) to simulate an outage. Perhaps this is the best path to a repro.
- We seem to be running `--disable_active_reparents` which surprised me and makes me wonder, but seems like it's somehow a prerequisite of vtorc, and [seems like planetscale folks agreed with this](https://vitess.slack.com/archives/C0PQY0PTK/p1677247768083579).

### Binary Version

```sh
ERROR: logging before flag.Parse: E1129 21:11:53.982862   38081 syslogger.go:149] can't connect to syslog
Version: 14.0.4-SNAPSHOT (Git revision 446ed206404d1a46a47fbb94d97319aabd21d67a branch 'HEAD') built on Wed Nov  8 21:02:31 UTC 2023 by root@buildkitsandbox using go1.18.7 linux/amd64

it's v14 with various more recent patches like this included: https://github.com/vitessio/vitess/pull/11157
```

### Operating System and Environment details

```sh
Linux ... 6.1.52-hs50.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 11 19:06:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by GuptaManan100** [comment]
@makmanalp I understand the situation. Would it be possible for you to share the go stack that calls `DemotePrimary`. Since `DemotePrimary` is stuck on the older primary vttablet, there would presumably be a go-routine that is running `DemotePrimary` but is stuck. I just need that go-routine stack

**Comment by GuptaManan100** [comment]
@makmanalp If there is no stack that has `DemotePrimary` call in it, then it's not that `DemotePrimary` was stuck right? This was what was bugging me. If `DemotePrimary` is stuck, then VTOrc would not be able to proceed with the PRS. It would continue to fail and you'll never have 2 primaries. What is happening is `DemotePrimary` doesn't get stuck but the old primary is not ending its priamry term properly.
`DemotePrimary` doesn't actually change the tablet status, it doesn't really demote the tablet, but primes it for demotion. Its the endprimaryterm that does the actual demotion, and that is stuck. I understand the situation now! Thank-you for all the information! I'll work on fixing this 👍

**Comment by makmanalp** [comment]
> If there is no stack that has DemotePrimary call in it, then it's not that DemotePrimary was stuck right? 

Gotcha - I'm not extremely familiar with that part of the code so it wasn't super clear to me if e.g. the demote process spawns a goroutine or writes via a channel to an existing one and so the goroutine with DemotePrimary in the stack continues on and disappears.

> DemotePrimary doesn't actually change the tablet status, it doesn't really demote the tablet, but primes it for demotion. Its the endprimaryterm that does the actual demotion, and that is stuck. 

Seems like you figured it out before I could, thanks!
