### ISSUE TITLE
Question: How do differentiate `foreignKeyMode=managed` and `foreignKeyMode=unmanaged` _functionally_? How are they actually different?

### ISSUE THREAD

**Issue by janpio** [vitessio/vitess#14660]
### Question

Hey, via https://github.com/vitessio/vitess/issues/14495#issuecomment-1808938031 I know that I can run `SHOW VSCHEMA KEYSPACES` to get a list of all the foreign key mode settings for all existing vschemas. Is there also a way to functionally differentiate the two modes that I could run in a test on the specific database/keyspace? Are the modes somehow different in a way that I can really confirm that the database I am talking to currently runs which mode?

This would be useful for tests that need to know and confirm which mode they are running against (as a simple `CREATE DATABASE` currently creates a database/keyspace with `foreignKeyMode=unmanaged` by default.

**Comment by GuptaManan100** [comment]
As you said, `Show vschema keyspaces` is already a way for an application to tell what mode a certain keyspace is running in. I am not sure what more you are looking for to differentiate the two modes.

**Comment by janpio** [comment]
Ok, if they indeed _should_ be functionally identical, then we can just run our tests in both modes and look for differences (and also compare to a similar run for MySQL).

**Comment by GuptaManan100** [comment]
Yes, that is correct. We adopt a similar testing approach in Vitess.
