### ISSUE TITLE
Bug Report: FLUSH TABLES WITH READ LOCK will lock a Vitess database in a way that is not recoverable by user

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#14719]
### Overview of the Issue

In a DB session, issue a `FLUSH TABLES WITH READ LOCK` (FTWRL)
All other writes to MySQL are now locked out (expected).
Disconnect from the session you issued FTWRL on
Observe writes to MySQL via Vitess is still locked out

### Reproduction Steps

This does not align with MySQL's behavior. After the session that issues the FTWRL disconnects, the lock is released.
Once the session the FTWRL was issued on dies/refreshes (if ever), the read lock is released.
The problem is that the user has no control over this because of the connection pooling.

Once a database is in this state, it's rather hard to figure out, because other than the writes being stuck in Waiting for global read lock state, there is no indication of the problem.
It will persist for hours (indefinitely?) as long as the pool connection remains active.
It is also not trivial to determine which pool session issued the FTWRL. If you discover this, you can just kill that session in MySQL, and things should recover (unlock)
In the absence of the above, the only workaround is probably just to bounce MySQL.

### Binary Version

```sh
`main`
```

### Operating System and Environment details

```sh
NA
```

**Comment by harshit-gangal** [comment]
Currently, the support for FTWRL is broken.

I propose we change in `vttablet` to allow execution of `FTWRL` only with Reserved connection. 
This change will break the current execution but prevent user from locked out of MySQL.

The second change will happen in `vtgate` where `FTWRL` will be executed with Reserved connection API to vtgate.

**Comment by deepthi** [comment]
> This change will break the current execution but prevent user from locked out of MySQL.

So effectively people will be prevented from running FTWRL because it will return an error, correct?
