### ISSUE TITLE
Bug Report: PRS promotes replica that has not caught to old primary as new primary

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#14738]
### Overview of the Issue

We ran into an issue where promoting the replica to primary via PlannedReparent succeeded. However, the new primary had actually not caught up to the position of the old primary. There were several thousand missing transactions.

### Reproduction Steps

This is non-trivial to reproduce, it needs a decent amount of load, or some other condition to make the replica lag.
One way to make the replica lag is to use it take a backup. As soon as the backup is complete, while the replica is lagged, use PRS to promote it.
Necessary pre-condition: Lag should be high enough that replica cannot catchup during the time allowed (wait-replicas-timeout). Making `wait-replicas-timeout` small (like 1 second) will probably help to reproduce.

### Binary Version

```sh
main for now, will check other versions and update.
```

### Operating System and Environment details

```sh
any
```

### Log Fragments

```sh
2023-12-08 22:45:20.064	
I1208 22:45:20.064349       1 rpc_replication.go:199] WaitForPosition: <redacted>
2023-12-08 22:45:49.097	
I1208 22:45:49.097332       1 rpc_replication.go:867] PromoteReplica
```
Note the time difference - almost 30 seconds, which is the amount of time allowed by default.

**Comment by deepthi** [comment]
> main for now, will check other versions and update.
The bug is present on all release branches, but not in any released version. We will be fixing this on all branches.

**Comment by GuptaManan100** [comment]
This part https://github.com/vitessio/vitess/issues/14738#issuecomment-1848686929 has not been implemented yet. So reopening.
