### ISSUE TITLE
Bug Report: Not able to list backups using kubectl get vitessbackups

### ISSUE THREAD

**Issue by GenLN** [vitessio/vitess#14766]
### Overview of the Issue

This is not working for 2 vitess cluster (only for one in separate namespace) on same K8S cluster. 

### Reproduction Steps

1. Deploy operator and CRD into namespace A
2. Deploy vitess cluster1 on namespace A
3. Run full backups
4. Run kubectl get vitessbackups into namespace A(it works)
5. Update operator deployment and assign also to watch namespace B
6. Deploy vitess cluster2 on namespace B
7. Run full backups
8. Run kubectl get vitessbackups into namespace B (empty for cluster2, even the backups are done and uploaded to gcs,s3 etc...)
8. Run kubectl get vitessbackups into namespace A(list for cluster1 vitessbackups are shown)

Second test different K8S cluster:
1. Deploy operator and CRD into namespace A1
2. Deploy cluster11 into namespace A1
3. Run full backups
4. Run kubectl get vitessbackups into namespace A1 for cluster11(backup list shown)
5. Deploy Operator deployment kind only into namespace B1
6. Deploy cluster21 into namespace B1
7. Run full backups
8. Run kubectl get vitessbackups into namespace B1 for cluster 21 (empty list no backups shown)
9. Run kubectl get vitessbackups into namespace A1 for cluster 11 (vitessbackups list shown)

### Binary Version

```sh
Vitess v18.0.1
latest tag vitess operator
```

### Operating System and Environment details

```sh
K8S cluster
```

**Comment by frouioui** [comment]
Closing this in favor of https://github.com/planetscale/vitess-operator/issues/626
