### ISSUE TITLE
Bug Report: `SIGSEGV` in vtgate upon shutdown in `shutdownMysqlProtocolAndDrain`

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#14901]
### Overview of the Issue

If `mysqlServer` is nil, when `shutdownMysqlProtocolAndDrain` is called during shutdown, it will panic.

### Reproduction Steps

Misconfigure mysql server port and socket path to get a nil mysqlserver.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
-
```

**Comment by dbussink** [comment]
> Misconfigure

Doesn’t have to be misconfigure right? Disabling it can also trigger it which is an explicit option.
