### ISSUE TITLE
Bug Report: "select 1" parsing error

### ISSUE THREAD

**Issue by mike9421** [vitessio/vitess#14937]
### Overview of the Issue

I found that when sqlparser parses "select 1", the table name will be parsed as "dual" by [default](https://github.com/vitessio/vitess/blob/961a9786e7a76b98069c36a63048edb0f28b8a5d/go/vt/sqlparser/sql.y#L4905). Is it more reasonable to set the table name to empty?

<img width="442" alt="image" src="https://github.com/vitessio/vitess/assets/37992936/bc760764-bfc5-482f-8c7a-03cbeb9d3bd5">

### Reproduction Steps

Use sqlparser to parse "select 1" and it will appear

### Binary Version

```sh
the [sqlparser](https://github.com/vitessio/vitess/tree/main/go/vt/sqlparser) of master branch
```

### Operating System and Environment details

```sh
Operating syste
ventura 13.6

Kernel version 
Darwin 22.6.0

Architecture 
arm64
```

**Comment by systay** [comment]
Hi @mike9421!

The two queries are semantically equivalent, and we prefer to use as few variations as possible. The AST string output is often different from the input string - this is just one of the many changes you'll get by `string -> ast -> string`

I understand it can be annoying, I had the same reaction first time I saw it, but it's not very important and keeps the code simple.
