### ISSUE TITLE
Bug Report: `format.AppendFloat` returns unexpected byte slice

### ISSUE THREAD

**Issue by beingnoble03** [vitessio/vitess#14972]
### Overview of the Issue

Currently, `format.AppendFloat([]byte, float64)` is being used in just `format.FormatFloat(float64)` in `go/mysql/format` package itself, which returns `format.AppendFloat(nil, someFloatValue)`. `format.AppendFloat` is used because the float printer in MySQL does not add a positive sign before the exponent for positive exponents, but the Golang printer does do that, and there's no way to customize it, so we must strip the redundant positive sign manually. e.g. 1.234E+56789 -> 1.234E56789

But, if we call `format.AppendFloat([]byte("A string containing 'e'"), 1e+16)`, we don't receive the expected []byte.

### Reproduction Steps

1. Run the following `code`:
```go
import "vitess.io/vitess/go/mysql/format"

buf := []byte("Test Value is:")
res := format.AppendFloat(buf, 1e16)
fmt.Printf("%s", string(res))

```
2. Prints `Test Value is: 1e+16`. But the expected string should be `Test Value is: 1e16`

### Binary Version

```sh
Version: 19.0.0
```

### Operating System and Environment details

```sh
- Operating system macOS 14.0
- Kernel version Darwin 23.0.0
- Architecture arm64
```

**Comment by beingnoble03** [comment]
Please confirm, so that I can start working on it.

**Comment by dbussink** [comment]
You are right, the logic is broken for when an existing buffer is passed in. We don't use that anywhere though, so how I'd fix it is to remove `AppendFloat` entirely then and inline it into `FormatFloat` which is used.  And then only add some tests for `FormatFloat`.

**Comment by beingnoble03** [comment]
@dbussink Yup, sounds good. Can you please assign me this issue? I'll create a PR.
