### ISSUE TITLE
Bug Report: `Unescape(Escape())` does not return the original string in `go/sqlescape`

### ISSUE THREAD

**Issue by Maniktherana** [vitessio/vitess#14992]
### Overview of the Issue

`EscapeID` for the string ``` a`a ``` returns ``` `a``a` ``` but `UnescapeID` doesn't reverse it. Currently, it simply returns ``` a``a ```, removing the outer backticks without halving the ones inside the string.

related: #14987

### Reproduction Steps

run this code:
```go
package main

import (
	"fmt"

	"vitess.io/vitess/go/sqlescape"
)

func main() {
	str := "a`a"
	escaped := sqlescape.EscapeID(str)
	unescaped := sqlescape.UnescapeID(escaped)
	unescaped2 := sqlescape.UnescapeID("`a`a`")
	fmt.Printf("String: %s\nEscaped: %s\nUnescaped: %s\nUnescaped2: %s", str, escaped, unescaped, unescaped2)
}
```

output should be:
```
String: a`a
Escaped: `a``a`
Unescaped: a``a
Unescaped2: a`a
```

### Binary Version

```sh
vtgate version Version: 18.0.3-SNAPSHOT
```

### Operating System and Environment details

```sh
- Operating system macOS 14.0
- Kernel version Darwin 23.0.0
- Architecture arm64
```

**Comment by Maniktherana** [comment]
If this is a bug, I'd be happy to patch it while working on tests for `go/sqlescape`

**Comment by systay** [comment]
this looks like a real bug. thanks for taking it on!

if possible, make the bug fix into a separate PR. That makes it much easier to back port the fix to earlier releases.
