### ISSUE TITLE
Feature Request: `schemadiff` strategy for `enum`/`set` value ordinal change

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#15105]
### Feature Description

Consider this scenario: a schema is being changed from `create table t(e enum('a', 'b', 'c'))` to `create table t(e enum(''b', 'c', 'a'))`. The ordinals of the names `'a'`, `'b'`, and `'c'` have all changed.
Remember that in MySQL enum values are numeric and therefore this change causes unexpected behavior on the application side, where same `'a'` value yields different stored numeric value.
This kind of change is undesired and likely accidental. `schemadiff` should have a way to prevent/error this type of change.

### Use Case(s)

-

**Comment by dbussink** [comment]
@shlomi-noach Should we also have a bit more overarching issue that renames today break for online DDL? And track that separately? Maybe we'd want to one day fix that by having the correct schema knowledge but that this change is a stop-gap until we'd have that?

**Comment by shlomi-noach** [comment]
This was fixed by https://github.com/vitessio/vitess/pull/15106

**Comment by shlomi-noach** [comment]
>  Should we also have a bit more overarching issue that renames today break for online DDL? And track that separately?

Tracked in https://github.com/vitessio/vitess/issues/15349
