### ISSUE TITLE
Feature Request: support for managed TRUNCATE statements

### ISSUE THREAD

**Issue by maxenglander** [vitessio/vitess#15151]
### Feature Description

Add an option to make Vitess execute `TRUNCATE` with the Online DDL system.

Currently, when `@@ddl_strategy` is set to `vitess`, `TRUNCATE` statements are not handled by the Online DDL system.

This is what happens currently when `--enable_direct_ddl=false` and `@@ddl_strategy='vitess'`:

```mysql
mysql> use commerce;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> create table foo (id int);
ERROR 1105 (HY000): direct DDL is disabled
mysql> set @@ddl_strategy='vitess';
Query OK, 0 rows affected (0.00 sec)

mysql> create table foo (id int);
+--------------------------------------+
| uuid                                 |
+--------------------------------------+
| 4dfbb05a_c519_11ee_b164_9e8adcc50d2a |
+--------------------------------------+
1 row in set (0.01 sec)

mysql> truncate table foo;
ERROR 1105 (HY000): direct DDL is disabled
```

If there are concerns that changing the current `TRUNCATE` behavior will break existing use cases, and additional CLI or `@@ddl_strategy` flag could resolve the conflict.

### Use Case(s)

Having `--enable_direct_ddl=false` set with `--enable_online_ddl=true` is a powerful combination that ensures, if and when users run DDL, they do so with the safety of Vitess' built-in online DDL.

Users and some frameworks (e.g. certain WordPress plugins) will sometimes run `TRUNCATE` in the normal course of business activity, and not as a maintenance action. It would be great if Vitess clusters configured with `--enable_direct_ddl=false` were able to accommodate these users/frameworks.

**Comment by shlomi-noach** [comment]
While running `TRUNCATE` as part of Online DDL is feasible, and I believe rather simple, the problem is with the synchronous nature of the command. Online DDL operates asynchronously. The challenge would be to make the `TRUNCATE` command wait until the operation is complete. And this would need to take place in both `vtgate` as well as `vtctldclient`. I don't have an immediate solution in mind as this goes against the existing design.

**Comment by maxenglander** [comment]
@shlomi-noach for my purposes, I don't think this is needed for `vtctldclient`. `vtgate` would be enough. What do you think of an `--wait` flag for `@ddl_strategy`. I don't know anything about how `vtgate` and Online DDL interact, so sorry if that suggestion is nonsensical. If it isn't nonsensical, I can open a separate issue to explore that idea.

**Comment by shlomi-noach** [comment]
I'm thinking the way a `--wait` would be implemented in VTGate is for VTGate to invoke the command on the tablet, then poll for results. Or polling could take place on the tablet.
Is there then some timeout? What if there's multiple shards, some return and some don't? Does it make sense to run `TRUNCATE` while another, long migration, is running? How about a migration running on the same table? Adding the synchronous nature brings some complexity.

Say we did timeout; say even we provide `--wait=30s`. But what then happens to the app? If it's a Wordpress, how does it react to a timeout? It will probably retry, thus creating yet another migration. But that won't run until the previous one is complete, so it's doomed to wait even more.

I'm thinking of the worst case scenarios of course, and trying to understand whether adding sychronousity is at all safe or whether it adds a risk.

**Comment by maxenglander** [comment]
All good questions. My thinking on some of this:

 * Personally, I'd be fine if we just returned an `unsupported` error if `--wait` is requested in the sharded case. My interest is to enable WordPress users to easily and safely use the Vitess clusters my organization operates, not so much to enable them to shard.
 * I think it would be reasonable as a starting point to reject a `TRUNCATE` altogether when there is a long migration running on the same table, at least when `--wait` is supplied. If this turned out to be a problem for enough people, we could refine further.
 * For the retry case, conceivably we could just have retries `--wait` for the currently queued/running `TRUNCATE` to finish.

**Comment by shlomi-noach** [comment]
> Personally, I'd be fine if we just returned an unsupported error if --wait is requested in the sharded case.

That's doable.

> I think it would be reasonable as a starting point to reject a TRUNCATE altogether when there is a long migration running on the same table, at least when --wait is supplied. If this turned out to be a problem for enough people, we could refine further.

There's actually a mechanism for that (`--singleton`).

> For the retry case, conceivably we could just have retries --wait for the currently queued/running TRUNCATE to finish.

That's a bit more complex, because the retries could be made from another connection. How can you tell if this weren't a valid new request? Or maybe it doesn't matter after all.

**Comment by maxenglander** [comment]
> That's a bit more complex, because the retries could be made from another connection. How can you tell if this weren't a valid new request? Or maybe it doesn't matter after all.

I'm naively imagining Online DDL `TRUNCATE` would work like this:

 1. Create new empty table
 2. Swap new and old table
 3. Evac old table (maybe over the course of days)

If we had two inflight `TRUNCATE` commands for the same table, I'm thinking that the second inflight command could merge with the first when the first has not yet started step 2. 

Once the first inflight has advanced past step 2., then in theory new records could be arriving at the new table, at which point it doesn't make sense to merge the second inflight `TRUNCATE` command with the first.

**Comment by shlomi-noach** [comment]
Actually, I think it must fall under the same conditions as:

> I think it would be reasonable as a starting point to reject a TRUNCATE altogether when there is a long migration running on the same table, at least when --wait is supplied. If this turned out to be a problem for enough people, we could refine further.

So if there's a pending `TRUNCATE`, then it _is_ considered as a long running migration on the same table.

**Comment by maxenglander** [comment]
> So if there's a pending TRUNCATE, then it is considered as a long running migration on the same table.

That may be fine for most cases, depending on how frequently `TRUNCATE` is run and how big the tables are.

One other question that may impact how some of this is handled is..at what point to we return to the user who has requested `TRUNCATE` with `--wait`? After the evac is complete? Or after the table swap?

At the risk of complicating things, maybe it would be better to start simple and return after the evac. But I can see a case to be made for returning after the table swap.

**Comment by shlomi-noach** [comment]
> One other question that may impact how some of this is handled is..at what point would we return to the user who has requested TRUNCATE with --wait? After the evac is complete? Or after the table swap?

Most definitely not after the evac, since that can take long minutes. Why do you feel it's safer to wait for the evac?

**Comment by shlomi-noach** [comment]
The other thing is, would the user/app need to know they must supply `--wait`? That doesn't make sense. In which case, will `--wait` be pre-configured? In which case, how will it affect all other migrations?

**Comment by shlomi-noach** [comment]
I should point out the evac it outside Online DDL's control, and under the TableGC mechanism. Online DDL does not have the information to say whether the old table has been purged or dropped.

Another point of discussion: should `TRUNCATE` be revertible?

**Comment by shlomi-noach** [comment]
It seems like there'a lot of specialized handling for `TRUNCATE` and that more might show up the more we think about it.

**Comment by maxenglander** [comment]
After having the discussion with you I agree. I'm inclined to close this out unless you want to keep it open?

**Comment by shlomi-noach** [comment]
Let's close for now, and reopen if needed.
