### ISSUE TITLE
Question: How do I deploy Vitees on Kubernetes with MariaDB.

### ISSUE THREAD

**Issue by bobymark** [vitessio/vitess#15216]
### Question

How do I deploy Vitees on Kubernetes with MariaDB. Can I get the yamls like given for mysql.

I have tried the deployment going through the Vitees site. Failed to get the cluster with below error.

Kubernetes is on Minikube Cluster 
Warning  FailedScheduling  2m18s              default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..

 Warning  Unhealthy         97s (x3 over 98s)  kubelet            Readiness probe failed: Get "http://10.244.0.89:15000/healthz": dial tcp 10.244.0.89:15000: connect: connection refused
  Warning  Unhealthy         96s                kubelet            Readiness probe failed: dial tcp 10.244.0.89:3306: connect: connection refused

<img width="780" alt="image" src="https://github.com/vitessio/vitess/assets/91247041/8e704103-c5d8-44b7-b40f-6658504de3ce">

Kindly help me fix the above issue and also share the yaml that works with the MariaDB.

**Comment by bobymark** [comment]
> Hi @bobymark,

> And it never was for the operator AFAIK: https://github.com/planetscale/vitess-operator

Thanks for the reply and support  **@mattlord**,

I tried the above link and currently I see below secret related errors. Could you please help me with this. I have attached the screenshots for reference. 

Warning  FailedMount  21s (x463 over 15h)  kubelet  MountVolume.SetUp failed for volume "gcs-backup-auth-secret" : secret "enisoc-dev-vitess" not found

 Warning  FailedMount  3m43s (x463 over 15h)  kubelet  MountVolume.SetUp failed for volume "gcs-backup-auth-secret" : secret "enisoc-dev-vitess" not found


<img width="804" alt="image" src="https://github.com/vitessio/vitess/assets/91247041/b1abfbbb-8670-43c5-8829-8d593417deef">

Regards, 
Mark

**Comment by mattlord** [comment]
Hi @bobymark,

This isn’t a proper support venue. If you’re looking for help from the community then I would encourage you to clearly lay out what you’ve done, how you did it, and what problems you’re seeing (none of which is entirely clear here and would require a lot of back and forth) in the Vitess Slack: https://vitess.io/community/

It’s quite active and is the best community resource for help. 

As noted, if you’re trying to get things working with MariaDB then it’s not going to work as MariaDB is very different than MySQL 8 and is not supported.

Best Regards

**Comment by robertsilen** [comment]
@mattlord What is different in MariaDB that makes it incompatible with Vitess?

**Comment by mattlord** [comment]
@robertsilen it’s simply that MariaDB is not compatible with MySQL — which Vitess fully supports (wire protocol, sql language, replication at a low level, etc — it is very non-trivial to support both). I don’t think that I need to get into every incompatibility between the two databases today — big and small — as MariaDB Foundation knows the differences. 🙂 If MariaDB Foundation prioritized compatibility or contributed to Vitess then that would change things but the project simply does not have the resources to fully support both as things stand today.
