### ISSUE TITLE
Bug Report: `queryserver-config-*-pool-waiter-cap` flags have no effect in v19

### ISSUE THREAD

**Issue by brendar** [vitessio/vitess#15234]
### Overview of the Issue

The new connection pool implementation from https://github.com/vitessio/vitess/pull/14034 no longer uses [`ConnPoolConfig.MaxWaiters`](https://github.com/vitessio/vitess/blob/v19.0.0-rc1/go/vt/vttablet/tabletserver/tabletenv/config.go#L443), which is set by vttablet flags `queryserver-config-query-pool-waiter-cap`, `queryserver-config-stream-pool-waiter-cap`, and `queryserver-config-txpool-waiter-cap`.

### Reproduction Steps

Didn't reproduce manually, noticed while looking at the code

### Binary Version

```sh
On tag: v19.0.0-rc1
```

### Operating System and Environment details

```sh
n/a
```

**Comment by dbussink** [comment]
@vmg should we deprecate these flags or would they still be useful and do we need to chance something in the new pool implementation?
