### ISSUE TITLE
Support all SELECT modifiers

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#15318]
`SELECT` in mysql supports a range of modifiers, such as `DISTINCT` and `SQL_CALC_FOUND_ROWS`.
At the moment, Vitess does not support:

```
[HIGH_PRIORITY]
[SQL_SMALL_RESULT]
[SQL_BIG_RESULT]
[SQL_BUFFER_RESULT]
```

It would be nice to have our parser support all of these. More info can be found [here](https://dev.mysql.com/doc/refman/8.0/en/select.html).

**Comment by systay** [comment]
Hi @jayesh9747!

This makes me happy. 🎉 
You are welcome to create a PR to solve this. 
Have you looked at https://vitess.io/docs/contributing/?

Also, there is a #developers channel in Slack that is very helpful.

**Comment by jayesh9747** [comment]
@systay  thank you for your response , I am egar to contribute and make sure i follw this guidelines  which you  share . Can you share slack channel link ?

**Comment by systay** [comment]
https://vitess.io/slack

**Comment by Utkar5hM** [comment]
Since there has been no updates for a while.  
@systay, Could you assign me this issue? :) I'd like to work on it.

**Comment by systay** [comment]
Hi @Utkar5hM!

Feel free to get started. We don't use the issue assignment much anyway. As soon as you create a PR pointing to this issue, it'll show up here.
