### ISSUE TITLE
Upgrade golang/protobuf dependency

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#15425]
### Task

When we upgraded to go1.22.1, we bumped the google protobuf dependency. However, as just announced by the golang team

version 1.33.0 of [google.golang.org/protobuf](http://google.golang.org/protobuf) inadvertently introduced an incompatibility with the older [github.com/golang/protobuf](http://github.com/golang/protobuf) module. (https://github.com/golang/protobuf/issues/1596) Users of the older module should update to [github.com/golang/protobuf@v1.5.4](http://github.com/golang/protobuf@v1.5.4).

So we should bump the golang protobuf dependency as well.

### Affected Release(s)
v19.0.1, v18.0.3

**Comment by deepthi** [comment]
This also needs to be done on release-19.0 before v19.0.1

**Comment by frouioui** [comment]
+ v18.0.3 as we are using `v1.33.0` on `release-18.0`.
