### ISSUE TITLE
Bug Report: `row_alias` (and column aliases) not supported for `INSERT INTO ...`

### ISSUE THREAD

**Issue by arthurschreiber** [vitessio/vitess#15509]
### Overview of the Issue

MySQL 8.0.20 deprecated the use of `VALUES(col_name)` in the `ON DUPLICATE KEY UPDATE` portion of `INSERT INTO` statements, and recommends the use of row (and column) alias syntax that was added in MySQL 8.0.19 instead.

See https://dev.mysql.com/doc/refman/8.0/en/insert.html and https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

Unfortunately, Vitess does not support this syntax yet. This is awkward, because tools like the Rails framework switched to using the row alias syntax to avoid the deprecation warning from MySQL, but this breaks on Vitess (see https://github.com/rails/rails/pull/51274).

### Reproduction Steps

```sql
INSERT INTO `table_name` (`a`, `b`, `c`) VALUES (1, 2, 3) AS `table_name_values`
```

returns

```
syntax error at position 59 near 'AS'
```

### Binary Version

N/A

### Operating System and Environment details

N/A

### Log Fragments

N/A

**Comment by harshit-gangal** [comment]
@arthurschreiber can this be closed?

**Comment by arthurschreiber** [comment]
Yup! ❤️
