### ISSUE TITLE
Bug Report: Vtorc chooses non-valid candidate as intermediate source

### ISSUE THREAD

**Issue by erikhalperin-hub** [vitessio/vitess#15531]
### Overview of the Issue

In a setup with cross cell replicas and where vtorc is configured to block cross cell promotions, vtorc can still choose a cross cell instance as an `intermediateSource` [here](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L243), if it's most advanced or tied. Then, [filterValidCandidates](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L254) + [isIntermediateSourceIdeal](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L261C21-L261C46) are called and it's determined that the intermediate candidate is not ideal. From there, this [conditional block](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L274) is run, which reparents all tablets to replicate from the intermediate source, although it's not promoted. In [promoteIntermediateSource](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L454), reparentReplicas is called with ALL replicas, including the now dead former primary and with `waitForAllReplicas=true`. Because the former dead primary is in the list, vtorc will attempt to reparent it and wait 30s. The ERS will [ignore any replicas](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L567) that were explicitly passed in as EmergencyReparentOptions, however vtorc specifically [doesn't pass in the former primary here](https://github.com/vitessio/vitess/blob/main/go/vt/vtorc/logic/topology_recovery.go#L266).

This means that a vtorc recovery will take 30s+ instead of only a few seconds.

### Reproduction Steps

1. Create a keyspace that exists cross cell with instances in both cells. It helps to have many more instances in the non-primary cell because this increases the odds that vtorc will select a cross cell intermediate candidate
2. Configure vtorc conf to have `"PreventCrossDataCenterPrimaryFailover" : true`
3. Hard kill mysqld on the primary

This isn't guaranteed to repro since if all replicas are caught up at the same position, it looks like they will be [sorted](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/reparent_sorter.go#L87) and chosen randomly.

### Binary Version
vtorc: the --version flag doesn't work however we're on version close to v15, right around https://github.com/vitessio/vitess/pull/12089

```
$ /opt/vitess/bin/vtorc --version
ERROR: logging before flag.Parse: E0320 13:56:39.719079     616 syslogger.go:149] can't connect to syslog
F0320 13:56:39.804869     616 server.go:231] topo_global_server_address must be configured
*** WARNING: The exit code was: 1 ***
```

vttablet:
```
Version: 14.0.4-SNAPSHOT (Git revision a2da11b61bd05cf6aa472001cc85d4a1f9deb92f branch 'HEAD') built on Fri Mar  8 01:57:56 UTC 2024 by root@buildkitsandbox using go1.18.7 linux/amd64
```

### Operating System and Environment details

```sh
- centos 8
- Linux 6.1.66-hs57.el9.x86_64
- x86_64
```

**Comment by mattlord** [comment]
@GuptaManan100 does this sound like something that may have been fixed since v14? Can you please triage this since there's not a simple test case here and it's reported against a version that's been EOL for about 8 months so much has changed since.

Thank you @erikhalperin-hub and @GuptaManan100 !
