### ISSUE TITLE
[vtadmin] Remove link to vtctld web

### ISSUE THREAD

**Issue by notfelineit** [vitessio/vitess#15597]
I think we're still linking to vtctld web from vtadmin's vtctld page: https://github.com/vitessio/vitess/blob/main/web/vtadmin/src/components/routes/Vtctlds.tsx#L54-L57

vtctld web was deprecated in v17 I believe, so we should remove these links.

**Comment by shlomi-noach** [comment]
Related: https://github.com/vitessio/vitess/issues/15587

**Comment by notfelineit** [comment]
Completed in https://github.com/vitessio/vitess/pull/15607
