### ISSUE TITLE
Question: How can I replace the localhost address

### ISSUE THREAD

**Issue by czxin788** [vitessio/vitess#15747]
### Question

![image](https://github.com/vitessio/vitess/assets/13861904/0a3dac30-28b3-4cbf-8666-ef96e9ccdb7b)

I  visit the web http://192.168.100.128:14000, but jump to http://localhost:14001.
How can I solve the problem?

**Comment by czxin788** [comment]
Thanks, it is ok by set  VITE_VTADMIN_API_ADDRESS=http://192.168.100.128:14001

**Comment by UltraTempest10** [comment]
@notfelineit How can I set the environment variable VITE_VTADMIN_API_ADDRESS on vtadmin-web if I use Vitess operator for Kubernetes? The image is vitess/lite:v18.0.8.
