### ISSUE TITLE
vitess support create view with join operation?

### ISSUE THREAD

**Issue by chanyoung1998** [vitessio/vitess#15817]
### Question

i want to create view using simple join operation. 
But `SQL Error [1235] [42000]: VT12001: unsupported: Complex select queries are not supported in create or alter view statements` this error happens. 
I searched a lot, but i can't find any comments about it.  plz let me know the reason..

```sql
   create view test_view as 
   select scene.id, sampe.id as sample_id, data.id as data_id
   from scene 
   join sample on scene.id  = sample.scene_id  
   join data on sample.id = data.sample_id
```

**Comment by systay** [comment]
Hi @chanyoung1998!

Have you looked at https://vitess.io/docs/19.0/reference/compatibility/mysql-compatibility/#views ?

You have to enable flags on both the vtgate and the vttablet side. If this still doesn't work, please let us know by re-opening this issue
