### ISSUE TITLE
Question: Is the Vitess Google Group still Active?

### ISSUE THREAD

**Issue by runewake2** [vitessio/vitess#16077]
### Question

I've noticed that the Vitess code and documentation has a few references to the [Vitess Google Group](https://groups.google.com/g/vitess) (vitess@googlegroups.com), is this group still active? As far as I can see the group appears to be unmoderated and most recently used as a resource for pirated movies and torrents with most relevant vitess questions occurring years ago. Should the reference to this group be removed and replaced with links to other Vitess communities like the vitess slack?

There's a few references to the group in the pom.xml file:
- https://github.com/vitessio/vitess/blob/main/java/pom.xml#L38
- https://github.com/vitessio/vitess/blob/main/java/pom.xml#L62

And it's being documented in some of the published Vitess images like [`vitess/vtctld`](https://hub.docker.com/r/vitess/vtctld).

It seems like this is just a legacy reference that needs to be cleaned up but I'm not sure if there is another intent here keeping the group around.

**Comment by deepthi** [comment]
Thanks for raising this. We need to shut down that mailing list, and document the new one: cncf-vitess-users@lists.cncf.io

**Comment by frouioui** [comment]
Hello @runewake2, thanks for raising this. I updated the description of our Docker Images on Dockerhub to not reflect the google meet group, and opened #16111 to remove it from `pom.xml`.

**Comment by deepthi** [comment]
@frouioui can you close this after the docker hub pages have all been updated? Thank you for volunteering to do that manually.

**Comment by frouioui** [comment]
The DockerHub pages were already all updated yesterday to redirect to our documentation and GitHub repository. Closing this issue for now, feel free to re-open if something else needs to be fixed 🙇🏻
