### ISSUE TITLE
Bug Report: `show vitess_migrations` not supported from inside a transaction

### ISSUE THREAD

**Issue by pawandubey** [vitessio/vitess#16242]
### Overview of the Issue

Since https://github.com/vitessio/vitess/pull/13726, vtgates are forwarding `show vitess_migrations` queries to the tablet instead of executing `select`s on the MySQLs.

However, as [`txConnExec`](https://github.com/vitessio/vitess/blob/1cc3e149508312a0ab01d95cbbe1cf996f0bbae6/go/vt/vttablet/tabletserver/query_executor.go#L278-L313) does not support `PlanShowMigrations`, if executed from within a transaction, the queries fail with something like:

`vttablet: rpc error: code = Internal desc = [BUG] ShowMigrations unexpected plan type (CallerID: userData1)`

This is a regression from the previous behaviour where `show vitess_migrations` would succeed from within a transaction.

It is not unreasonable for this to be ran from within a transaction (and `txConExec` already accounts for some other read types like `select`s and `show`s), e.g. in Rails, each `ActiveSupport::TestCase` test is wrapped in an implicit transaction and this regression makes any assertions on the result of this query impossible without turning off transactional testing.

Would it be worth supporting this new plan type from within the context of a transaction on the tablet?

### Reproduction Steps

On any schema, with v18.0.0, on a vtgate console

```
USE <keyspace>;
START TRANSACTION;
SHOW VITESS_MIGRATIONS;
```

Should fail with the error described above.

On v17 and earlier, it would succeed.

### Binary Version

```sh
It should be reproducible on v18.0.0 onwards (or with https://github.com/vitessio/vitess/commit/25af35f743d69e7245ce63fb158da8b4e42fbeeb and later).
```

### Operating System and Environment details

```sh
Linux 69eaf41a9693 6.8.8-300.fc40.aarch64 #1 SMP PREEMPT_DYNAMIC Sat Apr 27 18:11:03 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by shlomi-noach** [comment]
It was certainly unintentional for the query to stop working from inside a transaction. Looking into it.

**Comment by shlomi-noach** [comment]
Addressed in https://github.com/vitessio/vitess/pull/16399
