### ISSUE TITLE
Feature Request: `vitess/vtctldclient` container image

### ISSUE THREAD

**Issue by runewake2** [vitessio/vitess#16288]
### Feature Description

[`vtctldclient` has been introduced to provide stronger typing over `vtctlclient`](https://vitess.io/docs/20.0/reference/vtctldclient-transition/overview/) however a containerized copy of the `vtctldclient` is not currently being published with the Vitess docker images. I'm proposing adding a new container with the `vtctldclient` binary similar to the already published [`vitess/vtctlclient`](https://hub.docker.com/r/vitess/vtctlclient) image.

### Use Case(s)

* `vtctldclient` currently is installed by a build of the Vitess source code, this container would provide a way to use this tool without requiring that. That introduces some uses specifically for building out vitess testing environments where `vtctldclient` operations would be handy.
* It also enables further replacing of the old `vtctlclient` uses with the updated `vtctldclient` tool.

**Comment by mattlord** [comment]
Thanks, @runewake2 ! I agree that we should do this. IMO, we should remove the `vtctlclient` image for recent versions — as it's been deprecated since v18 — and replace it with a `vtctldclient` one.

**Comment by runewake2** [comment]
I'd be happy to take a look at implementing this @mattlord. I've started with a simple personal implementation [here](https://github.com/vitessio/vitess/compare/main...runewake2:vitess:swronski/vtctldclient-container) but am unclear how I'd actually contribute this and get it published to the container registry.

I would assume the idea would be to add `vtctldclient`'s container and then deprecate `vtctlclient` sometime after that release?

**Comment by frouioui** [comment]
Hey @runewake2! The Dockerfile you are proposing looks good to me so far. You also need to update our GitHub Actions workflow that builds/pushes the Docker images. You need to add the new binary here: https://github.com/vitessio/vitess/blob/05d7e768e88972bcafba352c4af6bf2b9cde888a/.github/workflows/docker_build_images.yml#L88.

**Comment by frouioui** [comment]
Also FWIW, you can always use the `vtctldclient` in the `vitess/lite` Docker image. We ship the binary in that image.

**Comment by runewake2** [comment]
I opened a draft PR with the changes I have + your suggestions. Unfamiliar with the process of contributing to vitess and it's changed since the last CNCF project I contributed to so please feel free to change or suggest things. I think I followed the contribution guidelines, but I might have overlooked something.

**Comment by frouioui** [comment]
Looks good to me!
