### ISSUE TITLE
Feature Request: per-tablet override to Durability Policy promotion rule

### ISSUE THREAD

**Issue by timvaillancourt** [vitessio/vitess#16377]
### Feature Description

This issue requests the ability for a Vitess user to override the Durability Policy promotion rule of an individual tablet

This feature comes with some risks _(if `must_not` is used too widely)_ and should be avoided unless there is a good reason, however it is a powerful functionality to have in advanced deployments

### Use Case(s)

A Vitess user that would like to override the promotion rule of certain tablets, example: an experiment or upgrade where a promotion to `PRIMARY` is not ideal: a MySQL/OS upgrade, soak of experimental hardware/tunings, a cell/datacenter where `PRIMARY` is not (yet) preferred, etc

A direct example: during Slack's rollout of MySQL 8.x, it was critical that we didn't let an unsoaked/unvalidated 8.x tablet become `PRIMARY`. With old-Orchestrator this was possible with the flexible promotion rule support, but in a VTOrc world this is less straightforward

Also the opposite case is possible, in some cases a user may prefer an individual tablet wins a promotion _(for whatever reason)_

**Comment by GuptaManan100** [comment]
Durability policy is an implementable interface for this reason. Why don't you implement a durability policy interface implementation that takes the MySQL version into account?
If you have a specific preference of a tablet in promotion, you can always specify that tablet as a `--new-primary` flag to PRS. Then PRS would specifically promote the provided tablet unless it is of a promotion rule that doesn't allow it to be promoted.

**Comment by timvaillancourt** [comment]
> Durability policy is an implementable interface for this reason. Why don't you implement a durability policy interface implementation that takes the MySQL version into account?

@GuptaManan100 agreed this is possible with a durability policy, but in practice this can be a bit cumbersome. For example, if we want to test a new type of hardware on just a single replica somewhere, modifying and deploying a new durability policy to do this takes a bit of work

To achieve similar to support to what is proposed here, Slack has a custom version of `cross_cell` that allows tablet-tags _(the `Tags map[string]string` map)_ to allow us to override/influence the behaviour in special cases, but I feel using arbitrary key/values to do this is a bit of a hack/informal

> If you have a specific preference of a tablet in promotion, you can always specify that tablet as a `--new-primary` flag to PRS. Then PRS would specifically promote the provided tablet unless it is of a promotion rule that doesn't allow it to be promoted.

Mainly what we are trying to avoid is VTOrc promoting a tablet we didn't want promoted, not a human planned reparent

**Comment by GuptaManan100** [comment]
@timvaillancourt I think what you're doing right now with the `--init_tags` is something that you should continue to use. I don't think allowing overriding promotion rules on a per vttablet basis makes sense. It feels like an anti-pattern to the existing code which says that durability policy decides which tablet is promotable and which isn't based on the tablet record. 
Like you said, we already have tablet tags to store more information about a tablet in the tablet record, for the durability policy to use. Explicitly storing promotion rules separately doesn't seem like a useful change to me.

**Comment by timvaillancourt** [comment]
> @timvaillancourt I think what you're doing right now with the --init_tags is something that you should continue to use. I don't think allowing overriding promotion rules on a per vttablet basis makes sense.

@GuptaManan100 that's fair 👍. We have a problem with this approach though, `--init_tags`/the `tablet.Tags` map requires a restart of `vttablet` to be updated and we often need these changes to be on-the-fly/temporary

What would work for us is a `vtctl` RPC that would allow us to change tablet tags, such as `ChangeTabletTags`. This would probably need to support a partial and full update of the `Tags map[string]string`. I envision the request looking like:
```
type ChangeTabletTagsRequest struct {
        Tags    map[string]string
        Replace bool
}
```
And response:
```
type ChangeTabletTagsReponse struct {
        Tags    map[string]string
}
```

Unfortunately I think this might require an RPC on `vttablet`, too - it needs to be aware the tags changed so it doesn't pave over them, otherwise it doesn't really "care" what they're set to. What do you think about adding this support @GuptaManan100? 🤔

**Comment by GuptaManan100** [comment]
Sure yes, this feels like a reasonable feature to have 👍. We'll also then probably want to add an RPC to view the tablet flags.

**Comment by timvaillancourt** [comment]
> We'll also then probably want to add an RPC to view the tablet flags.

@GuptaManan100 the tablet tags are a top-level field returned by the `GetTablet` RPC, which I guess is the "read" side of `ChangeTabletType`. I think that's enough but I can add a `GetTabletTags` RPC if you prefer
