### ISSUE TITLE
Feature Request: Allow cross cell promotion in PRS

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#16460]
### Feature Description

If the users want to promote a replica in a different cell than the current primary using `PlannedReparentShard`, they have to specify the new primary with the `--new-primary` flag.

It would be nice to have the capability for PRS to be able to auto-select a replica from a different cell too.

### Use Case(s)

If you're running a mode wherein you have multiple tablets in different cells, and you want to reparent away from the current primary, and you want to allow PRS to be able to choose the best candidate from all the possible cells, then this new feature is required.

**Comment by arthurschreiber** [comment]
This seems like a duplicate of https://github.com/vitessio/vitess/issues/15846. 😬 

Super happy to see this was tackled. Thanks @GuptaManan100 for the great work!

**Comment by GuptaManan100** [comment]
You're welcome ❤️
