### ISSUE TITLE
Bug Report: Column name is the value of bindvar when using SELECT 1 with aggregation

### ISSUE THREAD

**Issue by wlx5575** [vitessio/vitess#16484]
### Overview of the Issue

When using the query SELECT 1 with an aggregation function in Vitess, the returned column name is the value of bindvar instead of the expected column name. Here is an example:
select 1 , name from user group by costly;
+-------------------+------+
| :vtg1 /* INT64 */ | name |
+-------------------+------+
|                 1 | a    |

### Reproduction Steps

query SELECT 1 with an aggregation function 

### Binary Version

```sh
v18
```

### Operating System and Environment details

```sh
Operating system :CentOS Linux
Kernel version:Linux 4.18.0-193.el8.jd_032.x86_64
x86_64:x86_64
```

**Comment by wlx5575** [comment]
I think this is not quite the same as select 1 from dual. After the aggregation has been sent down, the column names have already been returned. When replacing the alias,we can check if it is a bindvar and avoid replacing it.

**Comment by wangweicugw** [comment]
I also encountered similar problems
