### ISSUE TITLE
Bug Report: vindex function query not working

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#16519]
### Overview of the Issue

declare any index on vschema and perform select query on it. It is throwing an error

### Reproduction Steps

mysql> select * from xxhash where id = 5;
ERROR 1105 (HY000): table xxhash not found

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
NA
```

**Comment by mattlord** [comment]
It currently requires you to use an existing DB first. I believe because the identifier is the vindex name defined in that Keyspace's vschema.

**Comment by harshit-gangal** [comment]
I understand, then the error is wrong when the keyspace is not selected

```
ERROR 1105 (HY000): keyspace  fetch error: node doesn't exist: /vitess/zone1/keyspaces/SrvKeyspace
```
