### ISSUE TITLE
VTAdmin: Workflow Details tab

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#16537]
### Feature Description

Currently the VTAdmin page for a specific Workflow shows detailed info in a JSON tab. While this shows all the output of a `Workflow Show` it is difficult for users to quickly find useful information for debugging or monitoring.

Let's add a new tab `Details` which extracts the `Workflow Show` output into structured UI elements which should include:

* Current Status: which phase is this workflow in (copy/running/switched)? Is it stopped? Is it being throttled?
* If switched link to the reverse workflow with some basic information about the reverse workflow like name, keyspace, status and current vreplication lag.
* If the Workflow is in Error, then print the message
* If in copy phase, how many tables left, rows copied, what is the ETA?
* If running, what is the vreplication lag?
* Recent log entries 

If there are multiple streams then show summary information on top wrt Statuses and then each stream info below.

**Comment by beingnoble03** [comment]
As of #16570, the Details tab includes:
- Summary: Gives the overall status of the workflow. Streams status (how many in running, copying, throttling, stopped, error phase), traffic status (whether reads or writes are switched), maximum vreplication lag. If switched, link to reverse workflow.
- Streams: Info about each stream of the workflow. State, stream message, transaction timestamp, database name.
- If in copying phase, progress of each table (i.e. Total Bytes, Bytes Copied, Total Rows, Rows Copied.)
- Recent logs from each stream, each log entry with log type, stream state, update timestamp, log message, count.

Screenshots:

![image](https://github.com/user-attachments/assets/04ab3ad1-b3e7-4896-859b-72963aa88fa3)
![image](https://github.com/user-attachments/assets/333ebe77-bc5d-4e1c-889f-1c0e798a1dde)
