### ISSUE TITLE
Bug Report: Errors returned by LockName are not being handled properly in vtctl workflow

### ISSUE THREAD

**Issue by CAEL0** [vitessio/vitess#16559]
### Overview of the Issue

In [go/vt/vtctl/workflow/server.go](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/workflow/server.go), some `LockErr`s are not begin handled, which may result in a nil pointer dereference.

```golang
// DropTargets cleans up target tables, shards and denied tables if a MoveTables/Reshard
// is cancelled.
func (s *Server) DropTargets(ctx context.Context, ts *trafficSwitcher, keepData, keepRoutingRules, dryRun bool) (*[]string, error) {

	...

	ctx, workflowUnlock, lockErr := s.ts.LockName(ctx, lockName, "DropTargets")
	if lockErr != nil {
		ts.Logger().Errorf("Locking the workflow %s failed: %v", lockName, lockErr)
	}
	defer workflowUnlock(&err)

	...
```

It seems like it should be `return nil, lockErr` when `lockErr != nil`.
There are the same problems in `dropSources` and `finalizeMigrateWorkflow`.

### Reproduction Steps
N/A

### Binary Version
N/A

### Operating System and Environment details
N/A

**Comment by mattlord** [comment]
Thank you, @CAEL0 ! You're right, we are missing `return nil, lockErr` there 🤦 I'll fix this and add a unit test for it.

THANK YOU!
