### ISSUE TITLE
Question: Does vitess support XA transaction?

### ISSUE THREAD

**Issue by jan-brinkmann** [vitessio/vitess#16571]
### Question

As stated in the title, does vitess support XA transactions as a special case of 2PC?

I found a nine year old issue on that, where XA transaction is announced: https://github.com/vitessio/vitess/issues/536
However, I do not find XA transaction in the documentation.

**Comment by harshit-gangal** [comment]
Hi @jan-brinkmann
We are working on adding support for atomic cross-shard transactions. 
It should not impact what we use under the hood, whether it is XA protocol or Vitess's implementation.

For the user, to enable the atomic cross-shard transactions, they should set the transaction mode to `2PC` via `set transaction_mode = twopc` and then any transaction that goes cross-shard will be atomically committed.

We will be updating the existing doc on `TWOPC` with updated information once the feature is ready for use.

**Comment by harshit-gangal** [comment]
You can follow along the work with open RFC: https://github.com/vitessio/vitess/issues/16245

**Comment by jan-brinkmann** [comment]
@harshit-gangal, thank you! 😊

**Comment by GuptaManan100** [comment]
The questions seems to have been answered and the RFC for the support is open and being worked on. I'm going to close this issue, please open a new one if there are any other questions/issues.
