### ISSUE TITLE
Feature Request: Create a vindex that can use one of two different vindex types for a column value

### ISSUE THREAD

**Issue by jmchen28** [vitessio/vitess#16663]
### Feature Description

Create a new vindex type that provides a way to specify two "subvindex" types and an optional threshold. If a threshold is provided, for a given column value, the vindex should choose one of the two subvindexes based on the column value relative to the threshold. If a threshold is not provided, the vindex will always check the first subvindex provided and if no value is returned check the second subvindex.

### Use Case(s)

Allows users to change the sharding schema for a table without needing to reshard all its data. Works best for a column with a strictly increasing value, so a threshold can be provided.

**Comment by deepthi** [comment]
Why should this be a built-in vindex type? There is an interface that you can use to implement a custom vindex.

It is not clear from the description how this actually lets you "change the sharding scheme". All data below the threshold (i.e. all the old data) still use the old scheme, and only new rows will use the new scheme.

**Comment by jmchen28** [comment]
@deepthi we've implemented this as a custom vindex and wanted to see if it would be worth upstreaming. re changing the sharding schema, yes you're right. This vindex allowed us to continue to use our old sharding algorithm for old data but use to the `hash` vindex type for new data.

**Comment by deepthi** [comment]
In that case, you might want to post this in slack (#developers) to gauge interest from the community. Another option is for you to push your vindex implementation into vitessio/contrib which contains contributions that the community might find useful, but which don't necessarily fit into the main repo.

**Comment by jmchen28** [comment]
Gotcha. Thank you!
