### ISSUE TITLE
MoveTables Create: ensure that none of the tables to be moved have data 

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#16817]
### Feature Description

When a `MoveTables` workflow is created, error out if any of the tables (if they exist) have any data.

### Use Case(s)

It is possible by mistake to create two workflows for the same set of tables, or select `All Tables` after some of the tables have been moved. Currently it fails with a `duplicate key` error *after* the workflow is created. We should bail out right at `Create`

**Comment by mattlord** [comment]
Just FYI: https://github.com/vitessio/vitess/pull/16810/files#diff-1e25101181c9311c90765891b1cea65cc520227bf4d35f3ad0421d1077ea9de5R280-R297

**Comment by rohit-nayak-ps** [comment]
Incorrectly marked as fixed in #16810

**Comment by mattlord** [comment]
> Incorrectly marked as fixed in #16810

Whoops. Sorry about that. I've updated the description to remove it.

**Comment by rohit-nayak-ps** [comment]
Closed via #16874
