### ISSUE TITLE
Feature Request: MoveTables support for auto replacing auto_inc cols with sequences

### ISSUE THREAD

**Issue by mattlord** [vitessio/vitess#16864]
### Feature Description

Since https://github.com/vitessio/vitess/pull/15679 we automatically strip any [MySQL `auto_increment` clauses](https://dev.mysql.com/doc/refman/en/example-auto-increment.html) on tables that are being moved (using the [`MoveTables` command](https://vitess.io/docs/user-guides/migration/move-tables/)) from an unsharded keyspace to a sharded one. And since https://github.com/vitessio/vitess/pull/13656 we support initializing any sequences in the target keyspace on `SwitchTraffic`.

It would be really nice if we also supported automatically *replacing* those MySQL auto_increment clauses with Vitess sequences. This would eliminate a fair amount of toil and potential for mistakes.

### Use Case(s)

Moving tables from an unsharded to a sharded keyspace, which is common e.g. when initialing migrating into Vitess. And one initial hurdle is moving from MySQL managed auto_increment values in the MySQL schema to Vitess managed AutoIncrement values in the Vitess vschema.

**Comment by arthurschreiber** [comment]
Yes, this would be really really great.
