### ISSUE TITLE
Bug Report: Grafana generated recursive CTE fails on v21

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#17177]
### Overview of the Issue

Grafana generated recursive CTE fails on v21

Related issue:
- https://github.com/vitessio/vitess/issues/13632#issuecomment-2460393171

cc @systay 

### Reproduction Steps

```sql
with recursive cte as (
  select :vtg1 /* INT64 */
  from dual 
union all 
  select n + :vtg1 /* INT64 */
  from cte
  where n < :n /* INT64 */
)

select n from cte
```

### Binary Version

```sh
v21.0.0 Docker images
```

### Operating System and Environment details

```sh
GKE v1.31.1
```

### Log Fragments

```sh
tabletserver.go:1587] Unknown column 'n' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: grafanaAdmin): Sql: "with recursive cte as (select :vtg1 /* INT64 */ from dual union all select n + :vtg1 /* INT64 */ from cte where n < :n /* INT64 */) select n from cte", BindVars: {#maxLimit: "type:INT64 value:\"50001\""n: "type:INT64 value:\"2\""vtg1: "type:INT64 value:\"1\""}
```

**Comment by systay** [comment]
Hi @derekperkins 👋 

Your query fails with the same error on vanilla MySQL:

```
mysql> with recursive cte as ( select 1 from dual union all select n + 1 from cte where n < 10  ) select n from cte;
ERROR 1054 (42S22): Unknown column 'n' in 'field list'
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.33    |
+-----------+
1 row in set (0.00 sec)
```

In the first part of the query you need to name the `1` column for this to work:

```sql
with recursive cte as (
  select 1 as n
  from dual 
union all 
  select n + 1
  from cte
  where n < 10
)

select n from cte
```

This query works fine in both MySQL and Vitess when I try it.

**Comment by systay** [comment]
Could you check if it’s possible to recover the original query that Grafana is attempting to run? The query shown in the log appears to be malformed, so there might be an issue occurring before it gets logged.

The specific problem is that the query does not declare column names in the initial WITH RECURSIVE clause. In Vitess (and MySQL), the first part of a recursive CTE needs to explicitly define column names, but here, it’s just using a literal value (select :vtg1 from dual). Without column names, this query will not work correctly in either Vitess or MySQL.

If you can retrieve the original query Grafana is generating, that might provide more insight into what’s causing the issue.

**Comment by derekperkins** [comment]
I'm not running that query myself, I'm just reporting what happens when Grafana v11.2.0 boots up. Somehow it's getting mangled.

Confirmation that it's the same query being executed.
https://github.com/grafana/grafana/blob/release-11.2.0/pkg/services/sqlstore/sqlstore.go#L363-L392

### Grafana error

```
level=error msg="Search failed" error="Error 1054 (42S22): target: unsharded.0.primary: vttablet: rpc error: code = NotFound desc = Unknown column 'n' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: grafanaAdmin): Sql: \"with recursive cte as (select :vtg1 /* INT64 */ from dual union all select n + :vtg1 /* INT64 */ from cte where n < :n /* INT64 */) select n from cte\", BindVars: {#maxLimit: \"type:INT64 value:\\\"50001\\\"\"n: \"type:INT64 value:\\\"2\\\"\"vtg1: \"type:INT64 value:\\\"1\\\"\"}" remote_addr=198.217.127.184 traceID=
```

### vttablet error

```
E1108 07:19:49.195724    8092 tabletserver.go:1587] Unknown column 'n' in 'field list' (errno 1054) (sqlstate 42S22) (CallerID: grafanaAdmin): Sql: "with recursive cte as (select :vtg1 /* INT64 */ from dual union all select n + :vtg1 /* INT64 */ from cte where n < :n /* INT64 */) select n from cte", BindVars: {#maxLimit: "type:INT64 value:\"50001\""n: "type:INT64 value:\"2\""vtg1: "type:INT64 value:\"1\""}
```

**Comment by systay** [comment]
You were absolutely right. Thanks for clarifying the issue. We have a suggested fix now.

**Comment by derekperkins** [comment]
Thanks for the quick turnaround!
