### ISSUE TITLE
Feature Request: vtctldclient for arm64

### ISSUE THREAD

**Issue by erikschul** [vitessio/vitess#17225]
### Feature Description

When using a Macbook to administrate a remote amd64 cluster, it may be relevant to use `vtctldclient` locally (at least the guide suggests so).

Could such local CLI tools be made available for arm64, even if Vitess itself cannot support arm64?

Possibly related:
- arm64 in CI #7600

Unrelated discussions:
- arm64 server (raspberry pi): #8037
- arm docker images #9797 #10501
- vttestserver for arm64 #15034

### Use Case(s)

.

**Comment by erikschul** [comment]
Thanks! I'll try that. 
It wasn't clear from the previous issues whether there were problems in compiling and running on arm64.

Have you considered cross-compiling on x86 builders to arm64? You could possibly have a separate 'experimental' release and later use multi-arch, to gather more data points.

**Comment by shlomi-noach** [comment]
Thank you for the suggestion! Unfortunately at this time we're not considering cross compiling to arm64 as part of an official release flow. Releases are quite complex as it is and involve many dependencies and release stages. I think building for arm64 is at a lower priority release-wise. But as @mattlord mentioned, many of the maintainers run on max/arm64 and we'd be the first to know if builds are failing.
