### ISSUE TITLE
Question: Way to know which vtgate I am connected to

### ISSUE THREAD

**Issue by serhatcetinkaya** [vitessio/vitess#17246]
### Question

Hello, we are using multiple vtgate's behind a load balancer and our application connects to vtgate through it. While debugging issues sometimes it is useful for us to know which client is connected to which vtgate host. 

I checked open issues and vtgate documentation but couldn't see anything useful. 

Is there some way to get this information from the client side? Something like `select @@hostname;` would be great.

**Comment by shlomi-noach** [comment]
@serhatcetinkaya thank you for your question. Would you mind taking this to the [Vitess Slack channel](https://vitess.slack.com)? This would give a better opportunity for more visibility and perhaps also answers by the community 🙏

**Comment by serhatcetinkaya** [comment]
@shlomi-noach thanks for the quick reply! it looks like I am not a member in Slack Community and for some reason it doesn't allow me to sign in. maybe there is some intermittent issue, I will try again later and update here

**Comment by systay** [comment]
I think we can close this now, right?

**Comment by serhatcetinkaya** [comment]
I created #17272 after our discussions in community slack. Closing this one to have the conversation on the Feature Request issue.
