### ISSUE TITLE
Feature Request: Expose underlying LocalAddr() for connections

### ISSUE THREAD

**Issue by desdic** [vitessio/vitess#17255]
### Feature Description

when using multiple IP its sometimes nice to know which IP the client connected to

### Use Case(s)

having multiple IP's for the server

**Comment by desdic** [comment]
Added a PR https://github.com/vitessio/vitess/pull/17256

**Comment by dbussink** [comment]
What are you trying to solve here? How are you using Vitess?

**Comment by desdic** [comment]
I'm using vitess for authentication mysql/mariadb in a proxy I'm creating. I need the `to `IP to check which authentication system I need to resolve the user (and where to send the request). But the underlying connection is not exposed so by adding a simple function I can now get the IP that is connected to.

**Comment by deepthi** [comment]
Take a look at the `GetRawConn()` func. You should be able to use that for your purposes.

**Comment by desdic** [comment]
oh this is embarrassing that I actually missed that one. Thank you, I'll close my PR.
