### ISSUE TITLE
Bug Report: VTOrc is detecting errant GTIDs on the primary

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#17286]
### Overview of the Issue

We found out that the changes made in https://github.com/vitessio/vitess/pull/17267 are incomplete. Post those changes, VTOrc detects errant GTID on the primary itself! It compares the executed set of the primary with its own collected data from the last request, and detects errant GTIDs.

### Reproduction Steps

1. Run a cluster with VTOrc.
2. Keep writing to the primary
3. See that VTOrc detects errant GTIDs on the primary.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
-
```

**Comment by shlomi-noach** [comment]
lolsob
