### ISSUE TITLE
LookupIndex: unable to create a non-unique vindex with just one column

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#17302]
### Overview of the Issue

While Vitess itself allows a non-unique vindex with a single column the `vtctldclient` `LookupVindex` command errors out saying that we have to specify at least two columns: `non-unique vindex 'from' should have more than one column`

**Comment by arthmis** [comment]
Is this an issue a new contributor can tackle?

**Comment by rohit-nayak-ps** [comment]
Closed via #17301
