### ISSUE TITLE
java: Zero DATETIME value gets mangled

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#2135]
MySQL allows a special [zero value](http://dev.mysql.com/doc/refman/5.7/en/datetime.html) (`0000-00-00 00:00:00`) as an exception to the rule that DATE and DATETIME values must otherwise be valid dates.

In `java.sql.Timestamp`, an attempt to parse the zero value throws an `IllegalArgumentException`.

In [Connector/J](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html), the `zeroDateTimeBehavior` setting can be used to specify `exception`, `round`, or `convertToNull`. The default behavior is `exception`.

In contrast to these two, [our Java client](https://github.com/youtube/vitess/blob/master/java/client/src/main/java/com/youtube/vitess/mysql/DateTime.java) converts the zero DATETIME value to something around `0002-11-30 00:00:00` (depending on the time zone).

We should either support the `zeroDateTimeBehavior` property, or at least pick a default behavior that matches one of those options.

**Comment by sougou** [comment]
@bbeaudreault @harshit-gangal The Java API has evolved a lot since this was created. Is this still an issue?

**Comment by harshit-gangal** [comment]
This is not yet handled. Property needs to be added along with proper handling.
