### ISSUE TITLE
Codelab for vertical sharding

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#2260]
There's a codelab for horizontal sharding. But in order to use horizontal sharding you first need to apply vertical sharding to move tables to a keyspace that can eventually be sharded. This means there is no clear path from a single-keyspace single-shard database (where most apps start out) to a multi-keyspace multi-shard database.

So it would be nice to also have a codelab for vertical sharding to complete the story.

**Comment by sougou** [comment]
The new tutorial covers this now.
