### ISSUE TITLE
Validate table to be moved against target keyspace Vschema during VerticalSplitClone

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#2296]
Since there is currently no way of moving a table back once the vertical split has completed we should verify that the table to be moved is actually meant to be in the target keyspace.

**Comment by mattlord** [comment]
Closing this as it seems to have gone stale. If I understand the comment correctly, later features have removed the core issue noted here. If I misunderstood then we can reopen with additional details. Thanks!
