### ISSUE TITLE
Make Vitess work with RDS

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#2518]
A few people have asked if Vitess can run on RDS. Although we currently specify that vttablet should run on the same machine as MySQL, it's not a hard requirement. Additionally, there are differences related to MySQL permissions and configurations to be considered.

Let's start with a doc that addresses the feasibility, and also provides guidelines on how to implement this. Then we can iterate accordingly.

**Comment by alainjobart** [comment]
Started this doc:
https://github.com/youtube/vitess/blob/master/doc/SeparatingVttabletMysql.md

**Comment by sougou** [comment]
Since RDS is a paid service, support for this can be obtained through PlanetScale.

**Comment by ethereal-sandeep** [comment]
@sougou Any update on when can this feature be available in vitess.

**Comment by sougou** [comment]
@ethereal-sandeep Support for RDS is available through PlanetScale.

**Comment by ethereal-sandeep** [comment]
Thanks. Could you please redirect me to some resource.

**Comment by ethereal-sandeep** [comment]
@sougou Done, lets continue it there :)

**Comment by JensRantil** [comment]
I think this feature request is still relevant for the Open Source project. I vote for not mixing commercial offering and the open source features here.

**Comment by binaryoak** [comment]
> A few people have asked if Vitess can run on RDS. Although we currently specify that vttablet should run on the same machine as MySQL, it's not a hard requirement. Additionally, there are differences related to MySQL permissions and configurations to be considered.
> 
> Let's start with a doc that addresses the feasibility, and also provides guidelines on how to implement this. Then we can iterate accordingly.

hi, @sougou , in my case,  it would be like, deploying vitess in a AWS EKS cluster and vitess should be able to work with AWS RDS,  I read above doc you shared,  but I cannot find related vttablet config in the k8s manifest,  is it supported now?  if so, can you point me out some resources that I can refer to?
