### ISSUE TITLE
Make Vitess work with CloudSQL

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#2519]
As we address #2518 (Make Vitess work with RDS), it should be possible to incrementally or simultaneously make Vitess work with CloudSQL also,

**Comment by alainjobart** [comment]
Created this doc as a starting point:
https://github.com/youtube/vitess/blob/master/doc/SeparatingVttabletMysql.md

**Comment by sougou** [comment]
Since CloudSQL is a paid service, support for this can be obtained through PlanetScale.
