### ISSUE TITLE
Implement vttee

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#2527]
A few people have asked for the ability to send queries simultaneously to MySQL and Vitess. This is useful for migration where you could bring up an independent dual-write (and read) version of Vitess and verify that there are no compatibility issues before cutover.

**Comment by bbeaudreault** [comment]
This is a good idea. Do you have an idea on how it would work yet?

**Comment by sougou** [comment]
We've discussed some broad options:
* Separate process or part of VTGate.
* Dumb tee vs. one that understands packets.
* Compare query results, and how to handle unordered results.

No concrete decisions yet.

**Comment by morgo** [comment]
@sougou I think this can be handled by a combination of pt-upgrade and ProxySQL. We don't have to write a new tool :-) There is also vtexplain, which I don't think existed when this issue was opened.

I am going to close this now, but if you disagree feel free to reopen :-)
