### ISSUE TITLE
Inconsistency in VTGate UI

### ISSUE THREAD

**Issue by ashudeep-sharma** [vitessio/vitess#2579]
I installed the new build , was exploring the UI of VTGate. There are some inconsistencies with the links that are represented on VTGate UI.
The Cell links in the VTGate UI points to V2 app while the keyspace links points to the old UI. Attaching the screen-shot for reference.
<img width="722" alt="screen shot 2017-02-22 at 5 35 19 pm" src="https://cloud.githubusercontent.com/assets/12492010/23211000/ea9c2178-f925-11e6-9714-290a9f64166f.png">

**Comment by sougou** [comment]
Looks like those links have been removed now. Closing this as obsolete.
