### ISSUE TITLE
vtctl: Replace --action_timeout flag with signal handler and cancelable context.

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#2625]
Some vtctl commands may take very long e.g. ApplySchema with -allow_long_unavailability turned on.

But currently, vtctlclient always sets a context timeout of 1 hour:

https://github.com/youtube/vitess/blob/master/go/cmd/vtctlclient/main.go#L24

That means long-running commands will be aborted. This would probably include our new *Wait commands e.g. WorkflowWait as well.

We should remove that and replace it with a cancelable context that can be canceled by a signal handler.

I already did this for vtworkerclient:

https://github.com/youtube/vitess/blob/master/go/cmd/vtworkerclient/vtworkerclient.go#L28

Backporting the change to vtctl will be trivial.

@alainjobart If you can think of situations where we want to keep the timeout, let me know.

**Comment by aquarapid** [comment]
`vtctlclient` by now has configurable gRPC timeouts, so marking this as fixed.
