### ISSUE TITLE
Vitess wants to join CNCF

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#2670]
We are considering joining forces with CNCF. As you may have heard, Kubernetes, gRPC and Prometheus all recently joined CNCF, and to align ourselves better with those projects and the mission of cloud computing, we want to do the same. Joining CNCF will give us a few additional advantages as a community:

* Increased visibility: People looking for storage solutions in the cloud are more likely to visit CNCF and notice Vitess.
* Improved identity: As a project, we are attracting more stakeholders. Featuring it as a standalone project will more accurately represent its use and adoption.
* Distributed leadership: As more contributors come on board, we look forward to sharing our leadership responsibilities with them.

In order to become a part of CNCF, Vitess licensing will need to change from 3-clause BSD to Apache 2.0.  We will start the paperwork on that in the coming weeks.

**Comment by derekperkins** [comment]
That's pretty awesome!

**Comment by harshit-gangal** [comment]
Awesome.. :)

**Comment by infect2** [comment]
great news!!

**Comment by caniszczyk** [comment]
We are starting to work on an official proposal here: https://docs.google.com/document/d/1p7gqlpQNJpZtsolHeX6vXR4NXXwGrCMsCz8rSi5jsBA/edit?usp=sharing

The TOC still needs to invite the project for a formal proposal, we are waiting to hear from the TOC which should happen by May 17th

**Comment by sougou** [comment]
Voting has begun for project acceptance. Please cast your non-binding vote at https://lists.cncf.io/g/cncf-toc/topic/9260616 to show your support :).

**Comment by rnavarro** [comment]
:clap:

**Comment by sougou** [comment]
This bug is now fixed!
