### ISSUE TITLE
ValidateSchemaKeyspace Fails

### ISSUE THREAD

**Issue by rnavarro** [vitessio/vitess#2763]
When I run ValidateSchemaKeyspace it fails with the following errors. When I look at the vtctld logs I don't see anything that helps to pinpoint the issue.

Can you offer any assistance for further debug info?

> ./kvtctl.sh ValidateSchemaKeyspace stitchlabs_prod
> 2017/04/12 13:36:10 transport: http2Client.notifyError got notified that the client transport was broken connection error: COMPRESSION_ERROR.
> E0412 13:36:10.679455   21498 main.go:43] Remote error: rpc error: code = 13 desc = transport is closing
> 2017/04/12 13:36:10 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing

**Comment by alainjobart** [comment]
My guess is either the topology service, or one of the tablets is unreachable, and that triggers the whole process to fail. ValidateSchemaKeyspace is fairly straightforward: find all the tablets in all shards, and compare their schema to the master. If any difference is found, log the diff as error.

The error reporting in go/vt/wrangler/schema.go is not very good, there is a lot of:
if err := XXX(); err != nil {
  return err
}
Which should be:
if err := XXX(a, b); err != nil {
  return fmt.Errorf("XXX(%v, %v) failed: %v", a, b, err)
}
and would help your investigation.

Please either send a PR to fix it, or I'll do it at some point...
