### ISSUE TITLE
Stop setting default user to "root" in Docker images.

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#2772]
This would be a great task for an external contributor who would like to learn more about Kubernetes and Docker in general or bring in their experience there.

In the past, our Docker images had to be run as root in Kubernetes to set up the initial ownership of mounted volumes.

On the other hand, the binaries itself were launched under the user "vitess" by going through `su` e.g. see here: https://github.com/youtube/vitess/blob/2523fa230c1f884fd052e9c3f694fb65185078e7/examples/kubernetes/vtworker-pod-template.yaml#L23

Running the images as root is no longer required and we should standardize to run everything as user "vitess".

Required changes:
* Remove "root" Docker image.
* Change default user to "vitess" in the "lite" image.
* Change our Helm configuration where necessary to be compatible with these changes.

More details on why we can do this today from @enisoc:

> Now there are several features that make this unnecessary:
> 
> * You can override the image-specified user to anything on a per-container basis with SecurityContext.
> * You can use Init Containers to briefly run a container as root for any setup you need, while keeping the main app container (e.g. vttablet/mysql) as non-root.
> * You can use fsGroup to tell k8s to make all dirs owned and writable by a given group upon mounting, so you may not even need the Init Container step above if all it does is chown and chmod.
> 
> The Helm chart uses some of these features, and as a result it does not need the vitess/lite image to be root. However, I didn't change the vitess/lite image to non-root since the old k8s examples still use it.

The last sentence means that we need to retire the old examples first (tracked in https://github.com/youtube/vitess/issues/2771).

**Comment by mattlord** [comment]
Closing this work as completed for now. As far as I can tell we're using the `vitess` user by default everywhere now.
```
$  for dkrf in docker/lite/Dockerfile*; do grep -q "USER vitess" ${dkrf} || echo "${dkrf} is not using vitess user"; done
$
```

If I missed anything please let me know and we can re-open this. Thanks!
