### ISSUE TITLE
Expose query plans and statistics at vtgate

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#2802]
As discussed in slack it would be nice to have a `/queryz` or similar debug UI at the vtgate to be able to understand how the various queries are processed (i.e. passthrough, scatter gather, join, etc) and to show the aggregate timings.

**Comment by hmcgonig** [comment]
This is super useful. I can see potentially using this when shutting vtgates down to ensure there are no long running queries prior to termination of the vtgate.

**Comment by sougou** [comment]
I believe this is done.
