### ISSUE TITLE
Python client in PyPi

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#2803]
It could be nice to have the Vitess python client available as well in the PyPi repo

**Comment by sougou** [comment]
This is a good idea. I'll be implementing a new Python client exclusively for the 3.0 protocol. I'll work on getting it uploaded.

**Comment by Yasumoto** [comment]
Thanks @sougou! Do you think the current version's dist can/will get uploaded to pypi?

**Comment by sougou** [comment]
The current version is deprecated because the new protocol is different. It was lower on my priority list because you can now connect using MySQLdb. But if you're waiting for it, I'll try to move it up.

**Comment by Yasumoto** [comment]
Aha, totally got it. We can/should set up an internal mirror/devpi server but have been lucky enough not to need it yet 😄 We might do so to host our own version until a new dist with the 3.0 protocol lands, but in the meantime @giaquinti has been able to pull directly from github with some `pip` magic.

Thanks for the heads up! 🙇

**Comment by giaquinti** [comment]
Thanks a lot @sougou !

**Comment by sougou** [comment]
Hijacking this bug and giving it to @rafael who volunteered to look at packaging the vitess protos into a package that can be used by python scripts to wrap cluster management functionality.

**Comment by sougou** [comment]
This is now obsolete.
