### ISSUE TITLE
Retiring zookeeper / etcd old topology implementations after Vitess 2.1.

### ISSUE THREAD

**Issue by alainjobart** [vitessio/vitess#2812]
We are going to retire the old 'zookeeper' and 'etcd' topology implementations. They have been replaced by 'zk2' and 'etcd2' implementations in Vitess 2.1.

This is a heads up for everyone who is using them in production. Please use the migration instructions at:
http://vitess.io/user-guide/topology-service.html#migration-between-implementations
to migrate. (Note we also have a 'tee' topology implementation that can be used for migrations, but it's not yet documented. We're not sure it's useful enough in practice).

Advantages of the new implementations:
- uses the same directory structure and file names as all the other implementations (consul and chubby). This will allow factoring out 75% of the code out of the individual implementations into the go/vt/topo library (to be done after retirement).
- uses a common and simple address / directory addressing scheme (instead of the ZK_CLIENT_CONF config file).
- uses CellInfo for cell description. Cells can be added, reconfigured,  and removed on the fly.
- will allow factoring out Cell Map, read-only global topology connections, and vtctld explorer.

**Comment by alainjobart** [comment]
Status on this:
- factoring out of the code mostly done.
- CellInfo used everywhere.
- vtctld explorer fixed (can be improved a bit more, after Cell Map refactor).

Remaining, coming very soon:
- factoring out Cell Map.
- read-only global topology connections.

**Comment by sougou** [comment]
I'm considering this as done.
