### ISSUE TITLE
2PC Transaction Unresolved on failed master reparent

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#2850]
I executed planned reparent command from vtctl. But the slave was lagging by a close to 2 hours.
The command failed after significant amount of time. The original master remained the master but in read-only mode.
On making it readwrite again, the prepared 2PC transactions were still stuck.

**Comment by sougou** [comment]
I checked the code. The planned reparent actually shuts down the query service now. So, it should not happen again. However, there are other corner cases that I've thought of, for which I'll create a separate issue.
