### ISSUE TITLE
resharding: clone and diff may use wrong order for tables without primary key

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#2880]
Clone and diff compare the source and destination shards during resharding. They assume that the stream of rows on each side is ordered in the same way, that is by primary key.

However, InnoDB allows tables without primary key: 

> If the table has no PRIMARY KEY or suitable UNIQUE index, InnoDB internally generates a hidden clustered index on a synthetic column containing row ID values. The rows are ordered by the ID that InnoDB assigns to the rows in such a table. The row ID is a 6-byte field that increases monotonically as new rows are inserted. Thus, the rows ordered by the row ID are physically in insertion order.

Source: https://dev.mysql.com/doc/refman/5.5/en/innodb-index-types.html

If there's a primary key, our clone code adds an `ORDER BY` to the query which reads all rows. Omitting the `ORDER BY` is wrong though because the insertion order on the dest shard can be different from the source shard. (On top of that, the diff tool does not omit the `ORDER BY` if the primary key is missing and therefore just fails.)

@alainjobart what's your opinion on this? @tirsen suggested that we should use a `UNIQUE` column instead or all columns in the `ORDER BY`. Unfortunately, our `TableDefinition` protobuf message currently does not include the `UNIQUE` columns. And ordering by all columns can be problematic if the table is big. MySQL may resort to a filesort? But I don't see any way around this?

I propose to fix things in this order:
1. Unbreak the diff tool and omit `ORDER BY` if no primary key is available.
2. Use all columns in clone and diff if there is no primary key.
3. Record in the SchemaDefinition `UNIQUE` columns and use them if there is primary key available.

References:
- TableDefinition message: https://github.com/youtube/vitess/blob/master/proto/tabletmanagerdata.proto#L33
- omitted `ORDER BY` in clone code: https://github.com/youtube/vitess/blob/master/go/vt/worker/restartable_result_reader.go#L304

**Comment by alainjobart** [comment]
That sounds like a plan (although item 3 is missing a 'no' in the sentence, but we get it ;) ).

**Comment by sougou** [comment]
Looks like this was fixed? I'll close if there's agreement.
