### ISSUE TITLE
Change the interface for long-running operations in vtworker / vttablet.

### ISSUE THREAD

**Issue by alainjobart** [vitessio/vitess#2883]
We now use a streaming API for long-running operations in vtworker (clone, diffs, ...) and vttablet (backup, restore). We want to change this to an operation-style API, similar to this definition:
https://github.com/googleapis/googleapis/blob/master/google/longrunning/operations.proto

We'd provide a create operation, get operation, delete operation API, and a streaming RPC to get the status of a running operation. The workflows running in vtctld can re-attach to running operations that way. And the operations are not linked to a streaming RPC being up.

**Comment by mattlord** [comment]
I'm going to close this as done for now since this is how things currently work today AFAIUI. If I'm missing something please let me know and we can re-open this.
