### ISSUE TITLE
Ensure the _vt "SideCarDBName" is configurable everywhere

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#2885]
Discussed on Slack's #vitess.

Vitess uses in several places a metadata database name called `_vt`. For people migration from existing systems we may already have a database to store similar metadata and ideally to avoid more complex grant management it would be convenient to be able to designate an alternative name to the default '_vt' database.

It seems this is done in some parts of the code:

"I see now: It is named 'SidecarDBName' for the vttablet query engine. Because we need to be able to use different names when multiple vttablet engines are running inside vtcombo. But _vt is hardcoded in a lot of places too, in particular in all reparenting and resharding operations. I don't think it would be a big deal to make it a parameter that can be set on the command line... Maybe file an issue for it?"

Hence this issue has been raised.

**Comment by sougou** [comment]
We've chosen a different approach to support multiple schemas in mysql, which makes this obsolete.
