### ISSUE TITLE
Support nibbles in vitess keyspace shard ranges

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#2889]
It become clear after a comment on the slack channel that when defining sharding ranges some confusion can arise. In theory the ranges are "left weighted" digits etc and the values provided for the ranges are in hex.

So a small setup may have ranges of `-80,80-` or a larger uneven one may have a something like:
`-40,80-81,81-90,90-` or even something odd like: `-10,1001,1001-20,20-` etc.

The point is the current code assumes that "byte" (2 hex digit) ranges are specified when in practice that shouldn't be necessary. If I want to do something like `-10,101,101-20,20-`  it won't work and I need to write: `-10,1010,1010-20,20-` for the stated reasons, whereas once understood by Vitess the former range sets should be fine.

So please consider adjusting the code to recognise ranges at the "nibble" (4-bit, single hex digit) level when using these key spaces ranges.

**Comment by sougou** [comment]
Closing this as there's been no further traction on this topic.
