### ISSUE TITLE
increment counter for warnings

### ISSUE THREAD

**Issue by acharis** [vitessio/vitess#3028]
tabletenv.go now has a counter for Warnings, but only one call to log.Warn* is accompanied by a counter increment. we should create other appropriate counters under "Warnings" and add increments wherever log.Warn* is called

**Comment by mattlord** [comment]
I'm closing this for now as I'm unsure if it's still relevant -- we no longer have a `tabletenv.go` file -- and from a quick glance at the code I don't see the issue original mentioned. If it's still an issue let me know and we can re-open it with some additional details.

Thanks!
