### ISSUE TITLE
Make V3 accept workbench preamble queries

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3130]
* `SET TRANSACTION ISOLATION LEVEL REPEATABLE READ`
* `SET @@SESSION.wait_timeout=610`
* `help 'SELECT'` -- serverside help
* It also complains about `keyspace performance_schema not found in vschema`. And same for `mysql` and `sys`.

@dveeden let me know if I've missed something.

**Comment by dveeden** [comment]
It also tries to enable 'safe updates'.

**Comment by acharis** [comment]
i connected mysql-workbench to a local mysql with general log turned on, then ran the queries through vitess. the following failed:
```SELECT EVENT_NAME FROM information_schema.EVENTS WHERE EVENT_SCHEMA = 'database_name';
SELECT logfile_group_name FROM information_schema.FILES;
SELECT NAME FROM mysql.func;
SELECT tablespace_name FROM information_schema.FILES;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET SQL_SAFE_UPDATES=1;
USE `database_name`;
show charset;
show collation;
SHOW COLUMNS FROM `database_name`.`table_name`;
SHOW ENGINES;
SHOW FULL TABLES FROM `database_name`;
SHOW FULL TABLES FROM `database_name` LIKE '%';
SHOW FUNCTION STATUS WHERE Db='database_name';
SHOW GLOBAL VARIABLES;
SHOW PROCEDURE STATUS WHERE Db='database_name';
SHOW SESSION STATUS LIKE 'Ssl_cipher';
SHOW SESSION VARIABLES LIKE 'interactive_timeout';
SHOW SESSION VARIABLES LIKE 'lower_case_table_names';
SHOW SESSION VARIABLES LIKE 'offline_mode';
SHOW SESSION VARIABLES LIKE 'sql_mode';
SHOW SESSION VARIABLES LIKE 'version';
SHOW SESSION VARIABLES LIKE 'version_comment';
SHOW SESSION VARIABLES LIKE 'version_compile_os';
SHOW SESSION VARIABLES LIKE 'wait_timeout';
SHOW TRIGGERS FROM `database_name` WHERE `Table` = 'table_name';
```

and vitess didn't choke on the following query, but it showed all of them, instead of doing the `like`:
```SHOW DATABASES LIKE 'database_name';```

**Comment by sjmudd** [comment]
I do think that supporting the syntax in a compatible enough way for something like workbench to work would be good. This aids access to vitess from more users.  I've also seen code which sends other statements not currently supported by vitess which would make migration from MySQL easier.
In many cases we can come up with a "reasonable" answer to the questions these queries generate which for now should be good, or have some mode which is "pure vitess" and doesn't "support compatibility syntax" if that's not needed.  I realise that this doesn't make vitess better but more access means more users and better uptake and clearly for a piece of software like this that is also important.

**Comment by demmer** [comment]
+100 to that -- I spent a decent amount of time looking into what it would take to get phpmyadmin to work as that is the de facto tool here used to introspect database schemas / run ad-hoc queries.

The main work that seemed to require was a consolidated information_schema across all keyspaces, possibly performance_schema as well.

**Comment by yuananf** [comment]
I will take this.
