### ISSUE TITLE
continuous performance tests

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3141]
## Motivation

We would like to have a system which regularly runs performance tests on the code and publishes this data such that it is easy to track performance regressions (and improvements).

Ideally, we envision something like Travis CI or a code coverage service, but for custom performance metrics instead :-) An example for a performance metric is the p99 latency as observed by a client.

## Requirements

* Storing performance metrics over time in some kind of time series database.
* Visual graph which correlates performance metric with Git commit or GitHub pull request.
* optional: GitHub status integration i.e. post a passed or failed status depending on the difference in performance metrics.

## Plan

The first step here would be to research if there are existing services out there which can help with this task.

Is anybody aware of anything? (I haven't looked yet.)

The main goal here is to come up with a setup that is easy to maintain and extend. Therefore, we would prefer popular, proven solutions over custom developments.

## Where to run the tests

We expect that we will have to run the performance tests on dedicated resources (e.g. on Google Cloud VMs) to get reliable numbers. Getting these resources for us YouTubers should not be a problem.

## Performance Metrics

In terms of performance metrics, we're considering to start with something simple e.g. write an end to end test which starts all binaries (mysql, vttablet, vtgate) on the same machine and runs simple queries. Then capture latency and throughput numbers and publish them. Eventually, we may want to run full cluster tests i.e. setups across multiple machines with replicated MySQL.

If you can think of interesting metrics and how to possibly collect them, please chime in as well.

**Comment by acharis** [comment]
building such a system was my full-time gig for 2.5 years at my last employer. i have many thoughts on this topic.

**Comment by harshit-gangal** [comment]
We have it now.. https://benchmark.vitess.io/
