### ISSUE TITLE
support max_execution_time optimizer hint

### ISSUE THREAD

**Issue by bbeaudreault** [vitessio/vitess#3160]
https://dev.mysql.com/doc/refman/5.7/en/optimizer-hints.html#optimizer-hints-execution-time

Our app level adds these to some queries. It would be nice to support it in vitess for changing the timeouts enforced at vttablet and vtgate.

**Comment by sougou** [comment]
Didn't you add support for this already, or was it for max rows?

**Comment by harshit-gangal** [comment]
If that query is in transaction then transaction timeout also needs to be changed for that session

**Comment by sougou** [comment]
You mean the other way round? Query timeout should be shortened to not exceed transaction time? I think there is an issue for it already.

**Comment by bbeaudreault** [comment]
@sougou I added support for `setQueryTimeout` to make its way down. But people also use `max_execution_time`.  Hopefully they can use the same code path. The reason we need both is that people have also been conditioned to do it in ad-hoc queries, which can't call setQueryTimeout

**Comment by bbeaudreault** [comment]
You may also be thinking of the `set workload = 'dba'` i added. That is the codepath i hope to re-use, not the setQueryTimeout thing (which was java)

**Comment by sougou** [comment]
Sounds good.

**Comment by aquarapid** [comment]
This (the comment form) actually works today (the hint gets passed down to MySQL), so I am going to close this.

One thing we do not support is the session variable version of this, e.g. `set max_execution_time=500`.  I will log a new issue for that.
