### ISSUE TITLE
Reference to building Vitess with MySQL on CentOS 7

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3175]
It may be worth adding some notes about building Vitess on different platforms.

Information for CentOS 7 at least relating to Oracle's MySQL is that you need to:

* install the following MySQL Community RPMS (Enterprise rpms should work fine too)

```
mysql-community-libs-5.7.19-1.el7.x86_64
mysql-community-common-5.7.19-1.el7.x86_64
mysql-community-client-5.7.19-1.el7.x86_64       (client code)
mysql-community-server-5.7.19-1.el7.x86_64       (server code)
mysql-community-libs-compat-5.7.19-1.el7.x86_64  (needed for OS compatibility)
mysql-community-devel-5.7.19-1.el7.x86_64        (needed for building)
```

If using these rpms you need to set:
* `MYSQL_FLAVOR=MySQL56`    even though we're running MySQL 5.7
* Set `VT_MYSQL_ROOT=`     that is no explicit value.  You can use `VT_MYSQL_ROOT=/` but that yields some double slashes in a few places which looks ugly.

Note: that startup scripts will complain that `mysqld_safe` does not exist. that's fine and expected due to systemd usage (if using MySQL normally).  The initialise scripts will also use `mysqld --initialize`.

These comments may help others who are looking to build on CentOS 7.

**Comment by slanning** [comment]
From my notes when building on CentOS 7, in addition to the mysql packages mentioned above, the package names corresponding to the Manual Build docs:
- MySQL-python.x86_64
- automake.noarch
- bison.x86_64
- curl.x86_64
- gcc-c++.x86_64
- git.x86_64
- golang.x86_64
- libtool.x86_64
- make.x86_64
- openssl-devel.x86_64
- pkgconfig.x86_64
- python-devel.x86_64
- python-virtualenv.noarch
- unzip.x86_64

If using zookeeper:
- java-1.8.0-openjdk.x86_64

Test-related packages:
- apache-maven.noarch
- google-chrome-stable.x86_64
- mysql-community-server.x86_64
- xorg-x11-server-Xvfb.x86_64

**Comment by sjmudd** [comment]
Note: not all the required packages are needed to build vitess, many are needed to run the test suites.

Also of interest may be my first step to build vitess rpms which is here: https://github.com/sjmudd/vitess-rpm/

**Comment by morgo** [comment]
This is a bit easier now - the `MYSQL_FLAVOR` autodetects, and as soon as https://github.com/vitessio/vitess/pull/5361 merges, the mysqld_safe issue should be fixed which means `VT_MYSQL_ROOT` will autodetect correctly.

We are working on converting python tests to go, which should slim the dependencies further. I haven't checked if the ones you mention completely overlap with docs ( https://vitess.io/docs/contributing/build-from-source/ ). The build guide is looking a little dated, but I will probably wait for the tests to be all converted before revising it again.

**Comment by morgo** [comment]
I have added a specific guide for building on CentOS 7: https://vitess.io/docs/contributing/build-on-centos/

Note that it does not yet support running the test-suite in CentOS 7, but instead recommends using Docker. We can revisit this after the tests have been converted to golang.

I am going to close this issue now, but please feel free to re-open if you have followup questions.
