### ISSUE TITLE
Migrate blog from Blogger to Jekyll

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3196]
There are a number of benefits to doing this, mainly SEO benefits for running it on the same domain as the rest of the site, plus it looks more professional and integrated. Blog posts would be written in markdown and we would need to use a service like Disqus for comments, but it should be a fairly smooth transition.

To move forward, we'd just need an XML export of the site. I could handle this in conjunction with some of the other website work that I'm doing.
http://import.jekyllrb.com/docs/blogger/

@michael-berlin @sougou

**Comment by michael-berlin** [comment]
I would be fine with switching to Jekyll. Sugu, what do you think?

Derek, if you could work on this, that would be great :) Sugu or I should be able to provide the XML dump.

**Comment by sougou** [comment]
LGTM

**Comment by derekperkins** [comment]
Can one of you do the XML dump and attach it here or send it to me on Slack?

**Comment by sougou** [comment]
Done.
