### ISSUE TITLE
Cleanup our build dependencies since we no longer compile gRPC manually.

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3229]
Places I think of that need to be fixed:
* documentation for manual build
* Dockerfile

**Comment by michael-berlin** [comment]
The MacOS instructions have to be cleaned up and tested again as well. I'll take care of this as well.

**Comment by rafael** [comment]
We have reverted the change to not compile gRPC manually because of: https://github.com/youtube/vitess/pull/3461.

We should circle back on this and find a different approach to solve this issue.

**Comment by morgo** [comment]
This has been fixed. We've removed a lot of dependencies now.
