### ISSUE TITLE
SplitClone could add a schema check of source and destination shards prior to starting

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3239]
The time to do this should be minimal and it avoids problems coming up after a long run copying data from one shard to one or more.

Background: I had been setting up a manual SplitClone for testing the workflow, I'd had some issues with it and eventually figured out what to do but in the immediate term I had not recopied the database schema again from source to destination. The SplitClone workflow does not seem to check this and consequently after several hours of running the process it failed.

I'm not sure how DDLs are managed in Vitess (not looked yet) so maybe you want potentially for the destination and source shards to be different but in my case this caught me and this issue is just to make a note of this.

If it does not make sense to add such a check that's also fine but it would be useful to know the reasoning for that.

**Comment by mattlord** [comment]
Closing for now as `SplitClone` has been replaced by `MoveTables` in 6.0+. Please let me know if I misunderstood something. Thanks!
