### ISSUE TITLE
vtctld UI bug in the schema panel

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#3254]
There's a UI issue in `vtctld` when you try to visualize a schema with several columns: you can't scroll up and down, the view is truncated. 

<img width="1280" alt="screen shot 2017-09-27 at 14 54 47" src="https://user-images.githubusercontent.com/4038041/30917806-be086c92-a394-11e7-8a1b-5c6eaf29f1a8.png">

**Comment by gedgar** [comment]
Closing this - probably don't need to fix this with vtadmin on the way.
