### ISSUE TITLE
Vitess sample scripts should be combined to act like an init script

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3259]
I think that the Vitess sample scripts to start and stop various processes should be combined, one per process to provide 3 functions: `stop` / `start` / `status` and possibly `restart` which is simply a convenience wrapper around `stop` + `start`.
Additionally the `start` process should wait until the process has successfully started so the user can be confident, without having to go and check immediately after the start, that the process is started.

Background: I have been using variations of these scripts with different parameters and incorrect settings can break the startup of the process so it becomes quite tiresome having to check each time if a mistake has been made.  These new "init scripts" would then provide an easier away to manage the underlying vitess processes and ensure that changes are consistent (where this is important) between each function.

If the reason the start scripts are written the way they are is to allow more parallelism in the startup of different processes that is fine (add an option for this) but having the status command would still add value as it should be easier to validate or wait for process startup even if this is done in the background.

I am willing to help try to do this and am conscious that once completed quite a bit of documentation would need to be updated, and maybe some testing too but prior to embarking on this would like to know if this seems like a sensible direction.

Thoughts welcome

**Comment by sougou** [comment]
+1

**Comment by demmer** [comment]
+1

This sounds like a nice directional change.

**Comment by morgo** [comment]
There are a few changes which more or less make sense to do at the same time:
- Remove non-required files from examples/local/ (currently files related to client test are here. We should move them out, since they don't need to be bundled with releases).
- Convert the startup scripts to init style (this report).
- Enable the local_example CI test on macOS. Currently it is disabled due to flakiness, which I hope will be solved as part of the init scripts refactoring.

**Comment by GuptaManan100** [comment]
Is there something left to do or should we close this issue?

**Comment by deepthi** [comment]
Let us close this for now. If someone is willing/able to improve the examples beyond where they are today, it can be re-opened.
A few things have been addressed:
- wait for components to actually be up before the script finishes
- example works fine on macOS, though we don't actually have CI on macOS.
