### ISSUE TITLE
clear up ambiguity of "uid" in filtered replication code

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3285]
The filtered replication code has the concept of "uid" to distinguish multiple source shards.

This is necessary if you're merging e.g. two source shards into one dest shard: Then the dest shard will have the two source shards listed with the unique ID (uid) 0 and 1.

We should use a different name for "uid" in the code and the documentation.

**Comment by sougou** [comment]
Closed via vreplication rework.
