### ISSUE TITLE
all binaries should log the output of --version at startup

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3290]
This way we leave a paper trail in the logs which build was used.

Right now, you need to start the binary with `--version` or look at the Build* metrics under `/debug/var`.

This code should call the version Print() function: https://github.com/youtube/vitess/blob/master/go/vt/servenv/buildinfo.go#L54

Ideally, this code should be in an open-source specific file because we don't need it internally as we have our own existing log message with a build info.

**Comment by irfn** [comment]
@morgo @michael-berlin 

can you explain what you mean by 
> this code should be in an open-source specific file 
Isn't the entire code open source.

**Comment by morgo** [comment]
You can ignore this. It referred to youtube's internal branch.
