### ISSUE TITLE
SplitClone: enforce that a user specifies the source shard

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3310]
Right now it's possible to run vtworker SplitClone with a *destination* shard as parameter i.e. `vtworker SplitClone test_keyspace/-80`.

During initialization it will realize that the key range `-80` is covered by the serving shard `0` (and not `-80`) and will use `0` as source shard instead.

It's too intelligent here.

Instead, it should return an error instead which says that "test_keyspace/-80" is not an eligible source shard.

**Comment by sougou** [comment]
Now that we also support merges, specifying the source or destination is going to be confusing depending on the situation. We have a few options:
1. Leave it as is.
2. Require users to specify to source and destination shards (lists), and sanity check them.
3. Create a separate `MergeClone` command to differentiate from `SplitClone`. Then `SplitClone` will require specification of source, and `MergeClone` can request the destination.

For now, we can live with option 1, and then look at option 3 later.

**Comment by demmer** [comment]
In light of my recent experience trying (and failing) to create a workflow for a shard merge, my .02 is that it makes more sense to have a clear path for split vs merge as opposed to how it is today where the system tries to figure it all out for me.

Of these two options, I feel like 3 makes more sense from the standpoint of a user -- i.e. have different workflows and corresponding worker tasks for split vs merge, and in both cases it makes sense to specify the _source(s)_.

But this needs to be extended to the workflow as well.
