### ISSUE TITLE
3.0 Release Master bug

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3313]
The next vitess release is a major version upgrade because of the protocol change. Although this will be a breaking change, we will provide additional flags for those using legacy clients for one more release.

Before cutting the first candidate, we should:
* Update the documentation
* Fix miscellaneous bugs that improve user experience
* If there are any minor features that would be nice to have, now is a good time to speak up
* Delete deprecated code from one release before

I've created a 3.0 label to facilitate tracking of issues.

**Comment by michael-berlin** [comment]
Progress of the milestone: https://github.com/youtube/vitess/milestones?state=open

Open issues: https://github.com/youtube/vitess/milestones/v3.0
