### ISSUE TITLE
vitess sequences documentation is not clear about requiring the sequence id column to be 0

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3331]
Following instructions on http://vitess.io/user-guide/vitess-sequences/ I was trying to setup a new sequence. I missed the fact that:
* it's necessary to insert the first value
* the id column should have the value of 0.

Not inserting any rows generates an issue: `unexpected rows from reading sequence some_seq (possible mis-route): 0`

Suggestion add more information to the message. "expecting 1 row". If the lookup keyspace is not sharded then suggest adding the row. If the lookup schema is sharded then probably the current error makes more sense. As it is the context is rather limited and so confusing.

So help in improving the error message and documentations will make setting up sequences easier.

**Comment by sjmudd** [comment]
FWIW: I'm not sure if all of sougou's videos are referenced on the vitess site. I found the explanation from seeing this one: https://www.youtube.com/watch?v=71nTBafPtcM.

**Comment by sjmudd** [comment]
A question also remains unclear:

Where are the cached sequences stored?
* If I have multiple vtgates then they can’t store the last sequence number as this info would need to be distributed between them (to allow for incremental sequences to be generated) so I guess they are stored on the vttablet of the lookup keyspace.  If that's the case then getting a new sequence number requires access network round trip between vtgate and vttablet. That needs to be understood.  Also it makes that vttablet a sensitive part of the infrastructure, perhaps more so than the backend mysqld that it's caching data from.

Perhaps this is documented. If so links from  http://vitess.io/user-guide/vitess-sequences/ to the appropriate docs would be most useful to add.

**Comment by mattlord** [comment]
I'm closing this as "fixed" in https://github.com/vitessio/website/pull/928. If there's anything else specifically that you'd like to see documented though please let us know. Thank you!
