### ISSUE TITLE
JDBC VitessConnection.isValid doesn't check health of the peer vtgate

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3341]
We saw this in staging during an automatic OS upgrade of a vtgate host. The behavior of gRPC in case of a dead host seems to be to wait until the deadline expires. That is a lot longer than it needs to wait if we run health checks instead.

Connection pools such as Hikari will not hand out connection that do not return true from `isValid` so can be quite important.

**Comment by gedgar** [comment]
Closing this as the Vitess JDBC driver is no longer managed (outside of deprecating versions/naming conventions); we recommend folks use https://dev.mysql.com/doc/connector-j/8.0/en/
