### ISSUE TITLE
Return error on SET GLOBAL statements in a multi-sharded environment

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3354]
Once we have more than one keyspace or shard, it's not possible to support `SET GLOBAL` statements meaningfully. As suggested by @sjmudd, we should return a meaningful error like: "Unable to accept SET GLOBAL settings on a sharded keyspace. Please configure these settings on each mysqld’s my.cnf file".

**Comment by harshit-gangal** [comment]
Recent PR #6957 matches the value against mysql settings and log an info message if they mismatch.
