### ISSUE TITLE
With the replication_reporter enabled  and disable_active_reparents the reporter will still try to fix replication

### ISSUE THREAD

**Issue by mpawliszyn** [vitessio/vitess#3367]
So we are using external reparenting and have it setup as so via `disable_active_reparents`. We do want to monitor the replication for delays but it appears an additional side effect of turning `enable_replication_reporter` on is that if we manually turn off replication it will turn it back on automatically, anyone know if this is expected and/or can be configured away?

Root reason is that `disable_active_reparents` appears to have no effect on the expected stop state:
`if !r.agent.slaveStopped() {` in replication_reporter.go

**Comment by sougou** [comment]
@mpawliszyn The immediate work-around for this would be to revoke  `replication slave` from `vt_repl`. This will cause those operations to silently fail, but the reporter should continue to work.

@alainjobart do you have any thoughts on how to address this?

**Comment by tirsen** [comment]
I think this PR is at least a partial fix: https://github.com/youtube/vitess/pull/3300

**Comment by alainjobart** [comment]
I think the PR is a full fix, as the flag is then used in replication reporter.
