### ISSUE TITLE
Provide better control over filtered replication

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3399]
In the current resharding workflow, once you've reached the filtered replication phase, there's no straightforward way of going back to a previous phase. There is also no way to pause or resume replication.

Proposed vtctl commands:
* `StopFilteredReplication`
* `StartFilteredReplication`
* `AbandonFilteredReplication`: This will allow you to restart SplitClone. We can also consider implementing this as an additional worker flag: `-abaondon_filtered_replication`.

**Comment by arthurnn** [comment]
Should we call?:
`FilteredReplicationPause`
`FilteredReplicationStart`
`FilteredReplicationStop`(for the abandon)

**Comment by harshit-gangal** [comment]
Rather than this, can we start having options rather than different commands.
FilteredReplication <start|stop>
each command having additional options.

**Comment by sougou** [comment]
This was fixed through the various vreplication refactors.
