### ISSUE TITLE
Support Streaming SQL

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3421]
Something like this would be awesome to have in Vitess.
https://www.confluent.io/blog/ksql-open-source-streaming-sql-for-apache-kafka/

**Comment by alainjobart** [comment]
At some point, @sougou and I were talking about exposing Update Stream as a streaming SQL query. Which would allow joins with the v3 query engine, and pretty much enable everything... would be cool!

**Comment by derekperkins** [comment]
cc @raphael

**Comment by GuptaManan100** [comment]
We have a sql statement to initiate a vstream which was (re-)added in https://github.com/vitessio/vitess/pull/9392. If there is something else that is required, we should open a new issue with the use-case for it ❤️
