### ISSUE TITLE
SplitClone issues: Monitoring and "broken configuration" made it hard to see cause of breakage

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3429]
Discussed with @sougou but I think it's good to reflect this here. Users will bump into things like this  and figuring out the solution at the moment is pretty much impossible unless you know the internals.

Problem: I was trying to do a `SplitClone` of `keyspace/0` to `keyspace/-80` and `keyspace/80`. The destinations shards were setup and had a master, replica and rdonly tablet but the first phase of the `SplitClone` could not find any healthy RDONLY destination servers. I had already told `SplitClone` to only require `min_healthy_rdonly_tablets 1`

Reported error was:
```
E1130 20:54:47.153071   36721 vtworker.go:98] online clone() failed: table=B_TransactionMessage chunk=   9/1000: NewRestartableResultReader for destination: keyspace/-80 failed: tablet=unknown: failed get tablet for streaming query: keyspace/-80: no healthy RDONLY tablets available
```

Investigation showed the tablets to be healthy in vttablet but vtgate showed the tablets as red.

Cause was: `GetShard keyspace/-80` showed `tablet_controls` ==> `     "disable_query_service": true,`

This was triggered somehow when changing the serving shards on a previous setup.

The problem is that this "reason" was not reported in a way which I could understand.

Once this was understood `DeleteShard` was used to remove the shard and the tablets were restarted. For this test shard that didn't matter, but it would be good to know how to remove this `disable_query_setting` value as that would have been simpler.

My conclusions from this issue are:
* error reporting was not complete enough to see what the problem was. Perhaps the SplitClone reporting was correct. I'd like a `vtctlclient` command to allow me to do a detailed "health check" on one or more tablets so I can verify their state and see what the exact health is.
* Modifying the broken shard configuration seemed harder. I tried to disable this function but I wasn't allowed:

```
$ vtctlclient -server :15999 SetShardTabletControl --remove keyspace/-80 rdonly
E1130 22:28:08.167857   35899 main.go:61] Remote error: rpc error: code = Unknown desc = cannot safely alter BlacklistedTables as DisableQueryService is set for shard keyspace/-80
```

Clearly Vitess is trying to protect me from something. I'm not quite sure what here, so perhaps adding a `-force` option might be good?  The help text could perhaps provide more context so it's clear the consequences of this change and when it may be ok to use it?
* I notice that to find the state of the shard I was looking at I used the vtctlclient command line. I looked at the web output of `vtgate` and `vttablet` and `vtctld`. For a specific shard it would be nice to be able to get a more detailed unified view (from the command line?) so that I can run one command, see the state and react appropriately. All the information is there: it's just currently you need to know exactly where to look and for the uninitiated this is really hard.

I have decided to make sure I'm comfortable with the SplitClone (reshard process) prior to using Vitess in production. Someone who tries this with an unsharded keyspace may find some of these things rather confusing and they may not be able to throw away the setup (or modify it) as easily as I can now.

Thanks for considering how to improve some of these issues.

**Comment by alainjobart** [comment]
I agree this is all very confusing. Just a bit of background on this:

* The ShardTabletControl records (stored in the global Shard topology object) are used to disable serving of data from shards that are being migrated during a resharding. It can contain disable_query_service=true (disabling serving entirely, used for horizontal resharding), or blacklisted_tables (tables to block, used for vertical resharding).

* During resharding, the normal flow is to create the destination shards, copy the data, enable filtered replication, then migrate the serving types one at a time. As the serving types are migrated, we add ShardTabletControl to the source shards, so the tablets that are being migrated are not serving any more. For replica / rdonly, it's not such a big deal (until the master is migrated, then serving from the wrong shard would have very stale data). For master, it is critical, to be sure we don't insert data in the wrong place.

* if resharding fails somewhat, and serving types are migrated back to the source shard, we also put these ShardTabletControl records in the destination shards, again to prevent serving from the wrong place. (this is what happened to you, most likely).

* the 'vtctl SetShardTabletControl' command allows the user to manually fix the records. Its usage is not very well documented, nor friendly. It tries to prevent the user from using a combination of disable_query_service=true and blacklisted_tables, as their usage should be distinct (horizontal and vertical resharding, respectively).

**Comment by sjmudd** [comment]
Alain,

The criticism is meant in context. Clearly this all works if you know what you're doing. If you don't you can bring down or throw away a shard or keyspace leaving leftovers which will affect you later. I imagine at places like YouTube you know what needs to be done an existing processes make sure this all happens cleanly but for new comers like myself I manage to do the wrong thing and leave the system in a state which is not obviously broken but which may cause issues later. The SplitClone functionality is _really_ good.

So thanks for giving the background. My desire is to be able to _see_ in situations like those I describe the problem more clearly as then I can figure out what's going on, and also to prevent myself getting into the state where I'm lost and unable to get things working.

My feeling is that only a few small changes are needed and this will help. A little more documentation on these things (you have a lot of documentation but it's still hard to figure out everything: I know this is a hard job to do well) and perhaps some better monitoring scripts which can help identify these situations is enough.

Any thoughts would be most welcome.

**Comment by linuxgood1230** [comment]
The only way ,just can delete the shard ?
```
$ vtctlclient -server :15999 SetShardTabletControl --remove keyspace/-80 rdonly
E1130 22:28:08.167857   35899 main.go:61] Remote error: rpc error: code = Unknown desc = cannot safely alter BlacklistedTables as DisableQueryService is set for shard keyspace/-80
```

**Comment by hallaroo** [comment]
I'm going to close this for now as with 6.0+ we have the [`vreplication`](https://vitess.io/docs/reference/vreplication/vreplication/) workflows [that should be used instead of `SplitClone`](https://vitess.io/docs/user-guides/historical/vertical-split/). If you feel that you still have a valid use case for `SplitClone` today please let us know. Thanks!
