### ISSUE TITLE
SplitClone fails to insert checkpoint position due to failed previous attempt

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3431]
I ran a SplitClone and it failed right at the end. Logging shows:

```
E1201 16:07:28.762621   17624 vtworker.go:98] offline clone() failed: blp_checkpoint queries failed: ExecuteFetch failed on cell1-0000000200 (keyspace/80-) on the first attempt; not retrying as this is not a recoverable error: rpc error: code = Unknown desc = TabletManager.ExecuteFetchAsApp on cell1-0000000200 error: rpc error: code = Unknown desc = Duplicate entry '0' for key 'PRIMARY' (errno 1062) (sqlstate 23000) during query: INSERT INTO _vt.blp_checkpoint (source_shard_uid, pos, max_tps, max_replication_lag, time_updated, transaction_timestamp, flags) VALUES (0, 'MySQL56/d0bfef08-d0d9-11e5-9f68-5820b1e4c340:1-1058865702', 9223372036854775807, 9223372036854775807, 1512144448, 0, '')
```

Clearly this should not happen under normal circumstances. The mysqlds behind the tablets have had a working content previously and I guess I didn't clean things up while trying to rebuild the data.

I see that in the code that 2 functions are used to setup the checkpointing:
* `CreateBlpCheckpoint` creates the table
* `PopulateBlpCheckpoint` populates the table with an INSERT statement.

The first function is "safe" in that it will try to create the sidecar db and table if they don't exist. The second statement does an insert. If for whatever reason the table existed there is no check if there was data in `blp_checkpoint` table and so it can fail like it did for me.

Given the "create safely mechanism used in `CreateBlpCheckpoint` I'm tempted to suggest that an additional command is appended to what's there already: `TRUNCATE TABLE _vt.blp_checkpoint`. This will ensure that after running `_vt.blp_checkpoint` is created and is empty which I guess is the intended state and that should be the case even if previously the server had the table with some data in it.

I'll provide a tiny PR for this shortly.

**Comment by sjmudd** [comment]
I manually used the logs to adjust the values in the `_vt.blp_checkpoint` table and restarted the tablets to see if this would start the filtered replication. It didn't seem to work.

Is there are more detailed description of what SplitClone does so that I could have manually triggered whatever remaining steps were needed?

**Comment by sougou** [comment]
The new management commands should address this use case. You can just `CancelResharding` and rerun `SplitClone`.
