### ISSUE TITLE
customresourcedefinitions does not return etcd definition

### ISSUE THREAD

**Issue by jacob-israel-turner** [vitessio/vitess#3439]
I'm following the [guide to get vitess running on Kubernetes](http://vitess.io/getting-started/#start-a-vitess-cluster), and ran into an issue when getting etcd deployed. `etcd-up.sh` kept getting hung up on [this line](https://github.com/youtube/vitess/blob/master/examples/kubernetes/etcd-up.sh#L42).  It's checking if there's a custom resource definition for etcd, which fails every time, causing the script to fail.

The issue appears to be caused by aaafa50667153618b15fb9e72f04ac4d61862bbf, though I haven't done a full bisect to verify that.  Reverting to the commit immediately previous to aaafa50667153618b15fb9e72f04ac4d61862bbf does resolve the issue, however.

**Comment by jacob-israel-turner** [comment]
Tagging @alainjobart, the author of the mentioned commit.

**Comment by alainjobart** [comment]
Are you running Kubernetes 1.8? That feature was added then...

Also, @enisoc was looking at this last week.

**Comment by jacob-israel-turner** [comment]
Yes, I'm running `1.8`.

**Comment by alainjobart** [comment]
I am not sure what it can be, then.

One thing is for sure though, you don't want to revert to the previous commit for the script, unless it's just for a demo. That previous version uses an older version of our topology code, and version 2.0 of the etcd API (we since then upgraded to version 3.0 of the API).

I'll look at it at some point. My install was working, but I was battling with this for a while (why I added the check, to make sure it worked). Maybe I had done something else before that too, and I forgot to document it.

**Comment by jacob-israel-turner** [comment]
This is purely for personal learning purposes, so I'm not too concerned with using a slightly outdated version, as long as the usage is roughly the same.

Any insights would be awesome.  I'll also try giving this another go based on `master`, maybe I messed up an earlier step.

**Comment by jacob-israel-turner** [comment]
I've now reverted back to master, as going forward with the reverted commit caused other issues.

I'm pretty convinced I'm not doing anything wrong, but there is perhaps something wrong in the example or a missing step in [this guide](http://vitess.io/getting-started/#start-a-vitess-cluster).

I've run `./etcd-up.sh` with this output:
<img width="559" alt="screen shot 2017-12-05 at 6 54 29 pm" src="https://user-images.githubusercontent.com/8698364/33640452-f8bf812e-d9ed-11e7-9766-4b2c9ea7958f.png">

As you can see, the custom resource check fails.  If I check what resources were created, I get this:

<img width="591" alt="screen shot 2017-12-05 at 6 54 43 pm" src="https://user-images.githubusercontent.com/8698364/33640468-0ef64464-d9ee-11e7-8861-709e8d983e7e.png">

If I modify `./etcd-up.sh` to skip the custom resource checks (on the chance that the check itself is the only thing that's failing), I get this:
<img width="765" alt="screen shot 2017-12-05 at 6 57 58 pm" src="https://user-images.githubusercontent.com/8698364/33640498-404b2b92-d9ee-11e7-816c-8c1d1e35d896.png">

If `etcd-service-template.yaml` is indeed configured correctly, then I'm missing the `EtcdCluster` resource type.

Unfortunately, I'm afraid I don't have the depth of experience with kubernetes to debug this any further.  It really feels like there's just a step missing where I haven't defined/created the `EtcdCluster` resource type, and I can't find anything in my searching to fix that issue.

@alainjobart any input/feedback you have would be greatly appreciated.  Hopefully this issue is confined to me.  But if there is indeed an issue with the guide, I'd love to help sort out any kinks.  Thanks!

**Comment by enisoc** [comment]
I think the problem is that the CRD registration is asynchronous. After creating the deployment, we should wait until `kubectl get etcdclusters.etcd.database.coreos.com` returns success.

**Comment by jacob-israel-turner** [comment]
I don't think that's the case, unless it takes more than a few minutes to create. I've looked at all the resources minutes after running `./etcd-up.sh`, and I have never seen it show up.

That being said, I may just be looking for the wrong thing. As I said, I don't have the most experience with Kubernetes. But my understanding is, this should show up under a custom resource group, and I never saw anything show up there, even after trying and trying after hours.

**Comment by enisoc** [comment]
Do you mean you never see any results in `kubectl get etcdclusters`? Or that you don't see any results in `kubectl get crd`?

If it's the first one, my theory could still apply. It's just that the script failed to create the EtcdCluster because it didn't wait long enough for the CRD to register.

**Comment by derekperkins** [comment]
I know helm has had struggles with that in the past.

**Comment by jacob-israel-turner** [comment]
@enisoc Here is what I get after running `./etcd-up.sh` and trying to get both `etcdclusters` and `crd`:

<img width="573" alt="screen shot 2017-12-05 at 10 03 45 pm" src="https://user-images.githubusercontent.com/8698364/33645480-4f0e72d2-da08-11e7-8d9d-a680df9fa303.png">

**Comment by derekperkins** [comment]
@jacob-israel-turner do you have RBAC turned on? I think it is enabled by default now, and that can cause communication problems between services.

**Comment by DylanGraham** [comment]
I'm hitting this same issue. The `etcd-operator` deployment doesn't appear to have any CRD

```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.1
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name```

**Comment by Majasi** [comment]
> I'm hitting this same issue. The `etcd-operator` deployment doesn't appear to have any CRD
> ...

Are you trying to install in a custom namespace? If yes, check out the *create_role* script on how to pass your namespace. It falls back to `default` so you need to pass `--namespace=your-namespace.
