### ISSUE TITLE
Support Materialized Views

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3458]
## Proposal
Somewhat related to #3421, I would love to be able to define materialized views, including and maybe most importantly, cross-shard queries. In its most simple form, I would want it to work something like this:

### Basic Usage
- Define a keyspace for Vitess managed materialized views
- Define a query for a materialized view
- vtgate monitors the updatestream and updates the materialized view accordingly
- Queries target the materialized view directly as a MySQL table

### Limitations
- Materialized view should fit into a single shard
- Eventual consistency

### Future Enhancements 
- Analyze all queries to see if they could be served from a materialized view. That lets Vitess admins transparently increase performance without devs even needing to know that the materialized view exists. This would also speed up large enterprise systems without any code rewrites
-  use the same code for replicating small tables onto other schemas to allow for efficient in-shard joins (from @sougou)

**Comment by sougou** [comment]
Strangely, this feature request has a relationship with #2956, the support for multiple schemas in a single mysql server. The core design component for this feature would be something that can perform custom filtered replication from anything to anything.

It could get used for materialized views, or it could be used for replicating small tables onto other schemas to allow for efficient in-shard joins.

**Comment by derekperkins** [comment]
> it could be used for replicating small tables onto other schemas to allow for efficient in-shard joins

Plenty of good use cases for that, like user or customer id tables

**Comment by dweitzman** [comment]
A use case that would interest me is eventually-consistent caches of count(*) queries on large tables.

When `select count(id) from person where zipcode = 12345` is slow for a big table, you might manually cache the count by tracking when rows are added and removed in the application layer.  A materialized view similar to this could be a more elegant solution:

`select zipcode, count(id) from person group by zipcode`

**Comment by sougou** [comment]
I believe this is done :)
