### ISSUE TITLE
Various issues seen parsing queries not supported by vitess

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3520]
I'm looking to move some applications to Vitess. While pushing them through `vtexplain` I see several things fail. This issue is to document these things to see if we can make vitess handle them better:

* `/*!50708 SET max_execution_time=5000 */` gives `execute failed: vtgate: http://vtgate:15001/: unrecognized statement: /*!50708 SET max_execution_time=5000 */`    *Suggestion*: accept this comment. MySQL does.  (Is this because there ends up being no statement?)

* `SET SESSION WAIT_TIMEOUT = 3600` gives `execute failed: vtgate: http://vtgate:15001/: syntax error at position 25 near 'WAIT_TIMEOUT'`. This is a client to vtgate session timeout setting. How is this handled by vtgate? Can it not recognise this value and configure appropriately? 

* `select @@version_comment limit 1` returns `ERROR: E1023 15:41:01.672065   26834 tabletserver.go:1352] unknown error: unable to resolve table name dual (errno 1105) (sqlstate HY000) during query: select @@version_comment from dual where 1 != 1: Sql: "select @@version_comment from dual limit 1", BindVars: {}`.   basically this completely confuses Vitess. Supporting this like MySQL/MariaDB do would be good. Then apps that use this would be happy. I also wonder if we should be able to tell vtgate what version to advertise itself as being, or whether it should advertise itself as one of the mysqld versions behind vttablet?  Having that sort of flexibility would be useful later.

* handling of P_S tables. Many current apps may try to query P_S or I_S databases. What do we do  with this? Some sort of minimal support might be good (e.g empty tables)

* Some commands like `SHOW STATUS LIKE 'xxxx'`, `SHOW [GLOBAL |  SESSION] VARIABLES LIKE 'xxx'`, `SHOW SLAVE STATUS` fall into this category.  I know that previously with maxscale some special configuration variables where "visible" via SHOW GLOBAL VARIABLES LIKE 'xxxx' which MaxScale would understand and report. this might be handy to allow an app to know if it's talking to vitess or not. ( ? )

* `FLUSH NO_WRITE_TO_BINLOG HOSTS` gives `execute failed: vtgate: http://vtgate:15001/: unrecognized statement: FLUSH NO_WRITE_TO_BINLOG HOSTS`.  Probably this should just be ignored.

So this short list is a list of things that came up.  If Vitess would support these statements better it  would require less work to migrate from using MySQL to using Vitess directly.

Thoughts welcome.

**Comment by acharis** [comment]
performance_schema and information_schema are supported i think. specific errors would be helpful here

**Comment by sjmudd** [comment]
Are you sure? I'd need to check but my colleague noted the following errors from Vitess:

`mysql not found in vschema
INFORMATION_SCHEMA not found in vschema
performance_schema not found in vschema
`

In many cases the queries to I_S or P_S don't make sense. In some cases you're getting session or server state and it might make sense to query the downstream backend server(s) (one of them or all of them, the latter would be heavy on vtgate) so probably unless you're looking for "session state" or some "configuration state" this might not make sense. Even doing something like `SHOW PROCESSLIST` might be interesting if it showed the queries that `vtgate` was handling and maybe only allowing the user to see queries from other "similar users" or "all users". Perhaps these things aren't good but what's clear is that a lot of software if it's talking to MySQL does poke and look "inside" so can get quite confused by responses from vtgate which don't look normal and don't handle it well.  So in many cases I'm tempted to think that empty responses would keep the app happy even if it doesn't get data without necessarily over burdening vtgate (though that's extra code to support so not ideal).

Maybe some of this issue come from code which is "smart" (-er) and it's better to have code which is simple and stupid and just let vitess handle things properly. Migrating is harder though if such support is not available while the transition to Vitess happens.

**Comment by demmer** [comment]
The information_schema and performance_schema aren't _properly_ handled by vitess -- in certain cases it will forward the request to one mysql host out of the cluster and return the results but IMO what makes more sense is a vtgate-unified version of the information_schema that properly presents all the keyspaces as separate "databases" while exposing the structures of each table.

**Comment by sjmudd** [comment]
Just checked. At least in 5.7 if you provide grants to a user for a specific db it can *NOT* see `P_S` or `mysql` databases. It can see the `I_S` database. I guess I should also check the behaviour under 8.0, or compare with MariaDB 10.X.

So as we haven't given access to these databases I'd expect a similar error in Vitess:
`ERROR 1044 (42000): Access denied for user 'test'@'%' to database 'performance_schema'` whereas 5.7 shows a list of 61 tables.  Perhaps Access denied for user .... should be a standard behaviour of access to any table that's not recognised. it's not completely helpful for the user (but they shouldn't be able to distinguish Vitess from MySQL (easily), but the error messages would be consistent.

If we want to provide metadata that might be good though clearly vtgate already exposes that though not via the mysql interface.

So maybe for now it would be good to focus on the commands that fail if that's possible.

**Comment by grooverdan** [comment]
Note `/*M! ... ` is a [mariadb comment](https://mariadb.com/kb/en/comment-syntax/)

**Comment by harshit-gangal** [comment]
Closing this as we are handling all the queries listed here.
