### ISSUE TITLE
gRPC streaming for SplitQuery responses

### ISSUE THREAD

**Issue by gfmtim** [vitessio/vitess#3524]
Depending on the number of rows in a table, the length of the query, and the value of `num_rows_per_query_part`, a SplitQuery response can be larger than the 4MB maximum gRPC message size. Supporting streaming responses for SplitQuery would allow arbitrarily large responses to work.

**Comment by mattlord** [comment]
I'm closing this as [`SplitQuery`](https://pkg.go.dev/github.com/tranquildata/vitess/go/vt/vttablet/tabletserver/splitquery) has been [officially deprecated and removed in Vitess](https://github.com/vitessio/vitess/pull/5928) in Vitess 6.0+.
