### ISSUE TITLE
Productionize lookup vindexes

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3537]
# Background
I'm not sure "productionize" is the right word here but basically there's a few features missing from lookup vindexes for us to be able to use the feature. We're entering a phase where we need to remove a lot of cross shard queries so this is our next top priority.

# Missing features
The following features are missing from lookup vindexes for them to be ready for us to use.
* *Handle partial transaction failure* For "best effort" (default) transactions the main transaction might succeed but the transaction updating the lookup table might fail. We should support eventual consistency here.
* *Backfill* There's no way to backfill the lookup table from existing data.
* *Silent vindexes* The usual way to roll out a denormalization (such as an index) is to start by keeping it up to date, then backfill and then start using it. We should support "silent" lookup vindexes which keeps the lookup table up to date but isn't used by the query planner.

# Optional features
We're not sure but we might also need:
* *Best effort lookup vindexes* In order to support eventual consistency we might want to support a "best effort" mode where the query planner falls back on cross shard queries if there's a miss in the vindex. This might make the silent vindex unnecessary but unsure how it would handle "deletes". Do we leave a NULL milestone?

**Comment by sjmudd** [comment]
Is this part of a migration to using vitess on a table with an auto-increment column or are you talking about something different? I have such a case and think I can figure out a way to do the migration probably by adding a gap in ids to ensure the switchover is fast. If you're doing something different can you explain the problem you're trying to solve?

**Comment by tirsen** [comment]
No this isn't about migrating to sequences from autoinc.

This is using about using a "cross shard index", i.e. a table sharded by some input key with an output key being the sharding key. This is to avoid fan out queries in order to be able to grow to a large number of shards.

**Comment by tirsen** [comment]
Doing some more thinking I wonder if "best effort" vindexes is basically the solution to all of this. A "best effort" vindex is basically a vindex which in case of a missing index entry in the lookup table will simply fall back on a cross shard query. Having this we can enable the vindex before backfilling and we don't need to ensure strong eventual consistency from updates.

The main issue I can see is handling updates of the vindexed column. If there's a partial failure after an update the index entry isn't just missing, it's simply incorrect and will point at the incorrect shard. We could handle this by post-validating the returned result set and falling back on a cross shard query if the returned result set is incorrect.

**Comment by demmer** [comment]
💯 to this idea -- it's something we've been considering at Slack as well and have talked about the various approaches, so thanks for writing this all down.

One thing I'd like to add to this list is a _consistency checker_ that would walk the tables and verify each row has the right corresponding row in the lookup index table.

I need to think about this idea of "best effort" more -- my concern is that it negates the benefit for negative lookups. In other words for tables where queries are expected to fail some non-trivial amount of time, using the negative result from the lookup vindex allows this to be resolved on a single shard, while the "best effort" approach would mean these would all fall back to scatter to all shards.

It also could introduce strange behavior if the WHERE clause matches more than one entry in the lookup table since by definition you don't know if it's complete.

**Comment by tirsen** [comment]
Yeah doing some more thinking I'm not sure "best effort" is the best solution either. It's nice in some respects but it's also problematic in others.

One issue is that even if we have an in-shard "queue" for dealing with partial transaction failure there is a certain probability that the index is out of date with the real data. Do we have to deal with this regardless or do we simply assume eventual consistency and just live with that?

**Comment by tirsen** [comment]
If we narrow down to supporting columns that aren't updated we can create a lookup vindex that is transactionally safe and best effort like this:

- *On INSERT:* In a new transaction upsert a row into the lookup table with the input/output columns. Commit the lookup transaction before proceeding with the parent transaction.
- *On DELETE:* Do nothing. This is safe because the keyspace id will only be used as an advise, when you run the actual target shard query no rows will be returned.
- *On UPDATE:* Error, this type of lookup vindex does not support updates.
- *On point SELECT:* First query the lookup table with the input column. If there's a lookup row use the keyspace id to find a single target shard. If the row is missing we're still backfilling the lookup table so fall back on an all shard query. (We should be able to turn this off when the table has been backfilled, when turned off there will be an error on a missing lookup row.)
- *On multi-value SELECT with IN clause:* Do a query from the lookup table and make sure every input column value has a lookup row. Use the set of output columns to find target shards. If a single lookup row is missing we need to fall back on an all shard query.

**Comment by tirsen** [comment]
Ok, after discussion with Sugu we can also support updates:
* We don't support having a uniqueness constraint on the lookup table
* On update we insert a new row with autocommit and leave the old one around
* Optionally both on delete and update we clean up the stray row with a (best effort) post commit hook

**Comment by dweitzman** [comment]
I think backfill assistance is still not in the vitess codebase?

I don't think this was in scope for the bug, but also for non-unique lookup vindexes I think it's still the case that a failed transaction could mess up vindex content even though that could be avoided if vtgate/engine/update.go used .Add and .Remove for non-unique vindexes before and after the data transaction instead of .Update?

**Comment by sougou** [comment]
I think the recommended approach would be to run the vindex in upsert mode, and not delete anything if you expect collisions.
