### ISSUE TITLE
In SplitDiff and VerticalSplitDiff process tables in order of estimated size

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3543]
Right now tables are processed in random or alphabetical order or something. This means we might start processing a very large table very late in the process potentially making the operation run several times slower than it needs to.

If we instead process the tables in order of decreasing size (largest tables early) we could speed up the entire process greatly in the worse case.

**Comment by alainjobart** [comment]
We used to have code for this, but it disappeared. Remains of it can be seen in go/vt/mysqlctl/tmutils/schema.go where we define TableDefinitions as an []*TableDefinition but never use it. It use to have a Less method that compared the data size, and we were sorting by size. Now that type is unused in there. We could resurrect the sort method and use it.

Then the usage would be somewhat easy to fix: right now we do this (in somewhat shorten pseudo-code):
for ... := range tables {
  go func(table) {
    sem.Acquire()
    defer sem.Release()
    ...
   }
}

We could just create a channel of tableDefinition of the exact size, push all sorted values in order in there, and read the work item from it.

Somewhat easy startup project for a first-time contributor?

**Comment by mattlord** [comment]
I'm closing this as no longer relevant.
