### ISSUE TITLE
Full support for text collation

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3591]
Vitess currently has limited support for handling collation. It's currently handled by outsourcing the work to mysql's `weight_string` function. But this approach works for only certain constructs.

There seems to be a bug in go's collation library: https://github.com/golang/go/issues/23241. However, even if that bug is fixed, there is no guarantee that the library will exactly mimic mysql.

The longer term fix will likely involve building something from the ground up using the same unicode tables that mysql references. This will guarantee that vitess behavior matches mysql.

**Comment by harshit-gangal** [comment]
Closing in favor of https://github.com/vitessio/vitess/issues/8606
