### ISSUE TITLE
Failed to reload schema: gtid_mode is OFF

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#3606]
While following the [sharding tutorial](http://vitess.io/user-guide/horizontal-sharding/) after completing the [local startup in Docker](http://vitess.io/getting-started/local-instance/), the following error appears on the first attempt of the [copy schema step](http://vitess.io/user-guide/horizontal-sharding/#copy-data-from-original-shard):

```console
/vt/src/github.com/youtube/vitess/examples/local$ ./lvtctl.sh CopySchemaShard test_keyspace/0 test_keyspace/-80
W0130 17:51:23.992216   17466 main.go:58] W0130 17:51:23.991857 schema.go:102] Failed to reload schema on slave tablet test-0000000200 in test_keyspace/-80 (use vtctl ReloadSchema to try again): rpc error: code = Unknown desc = TabletManager.ReloadSchema on test-0000000200 error: WaitUntilPositionCommand(SELECT WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS('0d2333f5-05e6-11e8-9b13-0242c0a80902:1-8', 9)) failed: gtid_mode is OFF
```

If you run the command again, it works, but it should work the first time. We probably just need an additional wait step of some kind to prevent the race condition.

I think the error `gtid_mode is OFF` is a red herring. The message is not coming from MySQL, but rather hard-coded in Vitess any time the result of `WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS()` is `NULL`:

https://github.com/youtube/vitess/blob/4ad01c5d0225b42a50945301173089afc09d5b22/go/vt/mysqlctl/replication.go#L167-L169

It's likely we wrote this based on the MySQL 5.6 docs, which only say, "the function returns NULL whenever gtid_mode is OFF." However, the MySQL 5.7 docs have added the additional statement, "If the slave is not running then the function also returns NULL."

So we probably just need to wait for the slave to start before attempting the reload.

**Comment by sougou** [comment]
$4001 fixes this.
