### ISSUE TITLE
Query transaction order

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3615]
Strict ordering of transaction commits is critical when designing safe distributed transactions without 2PC. Currently we use Hibernate interceptors to detect the transaction order and make asserts at the in critical multi shard functions. This is flawed because a raw non-Hibernate update could change the transaction order without us detecting it.

It would be better if we had some form of function which returns the order which shards transactions will be committed in the currently running session.

**Comment by GuptaManan100** [comment]
We are currently working on adding atomic transactions #16245  which should alleviate the need for this.
