### ISSUE TITLE
Sqlparser.Preview faild to recognize statements start with parentheses

### ISSUE THREAD

**Issue by yuananf** [vitessio/vitess#3638]
For example the parser can parse the following statement correctly
```
(select 1) union (select 2)
```
but when running it on vtgate, it fails with error
```
unrecognized statement: (select 1) union (select 2)
```
The error is thrown by 
https://github.com/youtube/vitess/blob/master/go/vt/vtgate/executor.go#L211

**Comment by yuananf** [comment]
I think this is fixed by #3887

**Comment by sougou** [comment]
Yeah. Sorry, it's been taking me too long to remove Preview from vtgate. And it will be a while. So, I decided to accept the change from @acharis.

**Comment by yuananf** [comment]
It's OK, I know it needs a lot of work to remove it.
