### ISSUE TITLE
Panic in tabletserver on shutdown, txRequests WG not used properly.

### ISSUE THREAD

**Issue by alainjobart** [vitessio/vitess#3643]
Originally, we saw this panic. It happened when a master got unhealthy (couldn't reach mysql):

tabletenv.go:110 Uncaught panic:
sync: WaitGroup is reused before previous Wait has returned
panic.go:502 (0xca0f58)
waitgroup.go:131 (0xce7c4a)
go/vt/vttablet/tabletserver/tabletserver.go:535 (0x1797ec7)
go/vt/vttablet/tabletserver/tabletserver.go:520 (0x1797da2)
go/vt/vttablet/tabletserver/tabletserver.go:618 (0x17b2726)
asm_amd64.s:2361 (0xcd0ff0)

Which the doc describes as: Note that calls with a positive delta that occur when the counter is zero must happen before a Wait.

So I was digging more into this, and I can see a case when that happens:
* the shutdown code is stuck on waiting on txRequests, because there is a Begin in flight, for instance.
* a 'Commit' also comes in.
* now before txRequests wakes up, the Begin that's in flight finishes (reducing the txRequests count to zero), and the Commit tries to add to txRequests (while it's zero) , resulting in the crash.

Is it just that the Commit call should have isTx=false when calling execRequest? (and Rollback, Prepare, ...) It seems only the Begin should add to txRequests, the end-of-transaction guys should not...

Or am I missing something?

**Comment by alainjobart** [comment]
(I wasn't too clear, it's on QueryService.Shutdown(), which happens when the master vttablet cannot reach mysql for a bit for instance, our case. Then it panics the healthcheck go routine and it never recovers).

**Comment by hmcgonig** [comment]
I just had something similar happen during a planned reparent on one of our healthy keyspaces.

```
I0328 15:44:23.089948     105 rpc_replication.go:301] DemoteMaster disabling query service
I0328 15:44:23.090101     105 tabletserver.go:301] TabletServer state: SERVING -> SHUTTING_DOWN (Shutting Down)
E0328 15:44:23.092178     105 rpc_server.go:70] TabletManager.DemoteMaster() on test_iad-1186033802 panic: sync: WaitGroup is reused before previous Wait has returned
/usr/local/go/src/runtime/panic.go:491 (0x42dbc2)
/usr/local/go/src/sync/waitgroup.go:133 (0x475e0a)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:556 (0xb0a7c7)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:518 (0xb0a532)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:411 (0xb09aca)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/rpc_replication.go:302 (0xc03c62)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/vttablet/grpctmserver/server.go:366 (0xc122d1)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/go/vt/proto/tabletmanagerservice/tabletmanagerservice.pb.go:1289 (0xbbe5e5)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:920 (0x7ee013)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:1142 (0x7f1f17)
/usr/share/hubspot/build/workspace/vitess-internal/rpm_builder/vitess-build/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:637 (0x7f905e)
/usr/local/go/src/runtime/asm_amd64.s:2337 (0x45f400)
```

**Comment by alainjobart** [comment]
@sougou I think the fix could be very simple, if you agree with it (and I can do it). just want your opinion. :)

**Comment by sougou** [comment]
In the initial version, txRequests only tracked calls to Begin. The flow was as follows:
* Change state to shutting down: No new Begin calls are allowed at this point. However, existing Begin calls may be in progress that have not yet obtained a conn from the pool.
* So, wait for those begins to complete (txRequests).
* Then wait for all tx connections from the pool to be released through commit or rollback.

However, I think I detected another possible race that caused me to think that other in-flight transactional requests (including the 2PC ones) should also be counted. It's quite possible that I was just over-conservative.

Looking at it again, I think the correct fix will be to only add to txRequests for Begins. It's the only call that obtains a conn from the tx pool. All others perform a return.

Maybe even rename it to beginRequests.

Does this make sense?

**Comment by alainjobart** [comment]
Yes it does make sense, I'll work on a fix soon-ish.

**Comment by sougou** [comment]
Looks like this is addressed now.
