### ISSUE TITLE
Prometheus metrics for Vitess

### ISSUE THREAD

**Issue by zmagg** [vitessio/vitess#3644]
#### Overview
We’d like to build Prometheus support directly into Vitess, instead of relying on scraping the `/debug/vars`.

 The idea is that we’d publish Prometheus formatted stats at a URL like, http://<host>:<prom_port>/metrics from on each Vitess component. 

The Prometheus client needs more information than the existing interface provides. It needs:

-  type of the metric (Counter, Gauge, Histogram, Summary)
-  whether or not the metric is surfaceable in Prom (there are some pure strings in the expvars, like: e.g. `"BuildTimestamp": 1514968053` that don’t map to any time series)
- description of the metric
- prefix for what component the metric came from (e.g. ‘vtgate’, ‘vttablet’,...)

There are multiple ways the Prometheus client can get this information, some thoughts:

#### Implementation Idea 1

Prometheus as built-in, first-class way to export metrics inside Vitess

In this implementation, we’d change the existing stats.Publish interface (impacting the other interfaces that call it, like `stats.NewCounters`, `stats.NewTimings`) and all callsites, like so:

*Old interface:*

`func Publish(name string, v expvar.Var) `

*New interface:*

`func Publish(name string, t promType, desc string, v expvar.Var) `

In this implementation, we would change the `stats` package so that when `Publish` was called, we’d also instrument the metric via the Prometheus golang client library.

#### Implementation Idea 2

We could also make Prometheus more plugin-able and optional, instead of built-in. 

In this implementation, we’d have a Prometheus plugin in every Vitess component that would register as a new available backend that would get called on every expvar callback. The plugin itself would consist of a Vitess-specific wrapper around the Prometheus golang client. On every call to the Prometheus exporter endpoint, the Prometheus registered backend would be triggered and the metrics scraped (just like how the `/debug/vars` expvars work today). 

We would keep the existing `stats.Publish` interface. Inside the Prometheus plugin, we could write an extensive static mapping function between all of the existing metrics and the information the Prometheus client needs. Whenever somebody adds a new metric, they’d have to add it to this static mapping function explicitly in order for the metric to show up in the Prometheus exported stats. (This looks similar to the existing started-on Prometheus implementation inside Vitess).

#### Discussion
I favor Idea 1 over Idea 2, mostly for ease of maintenance as Vitess developers add more metrics. It would also make code reading easier for people using Vitess (one place to look for metrics, not two). Also, the addition of the type of metric to the interface would make it easier to integrate other metrics backends (like Dogstatsd/StatsD). 

But! I think Idea 1 is a more invasive change, and I’m not sure if we want the interface to actually look like that. Thoughts? Tradeoffs?

**Comment by sougou** [comment]
The original intent of the stats package was to provide higher level semantics over what expvar provided, and the ideas was to make it have feature parity with google's internal monitoring APIs.

In principle, there should be some similarity between the stats API and Prometheus. But the stats API hasn't changed in a long time. I'm wondering if it could be modified to match the prometheus API. If so, the functions could just proxy the calls to Prometheus.

But reality may be different. So, the above goal may not be achievable. I can look at prom vs stats API if I get the time and see if they're still reconcilable. But I have a few other high priority items to get through first.

**Comment by zmagg** [comment]
> I'm wondering if it could be modified to match the prometheus API. 

I think it can! That's essentially the idea behind the first implementation idea. The Prometheus API is a superset of the existing Vitess stats API.

**Comment by demmer** [comment]
> This project is still at a very early stage of development. The API is changing rapidly, vendoring is recommended.
Pretty young indeed.

**Comment by derekperkins** [comment]
That line was added to the readme a year ago and there have been several full-time engineers working on it for several months now, including @rakyll who moved over from the core Go team. Google Cloud is actively moving all customers off their metrics/trace SDK and onto OpenCensus. There were OpenCensus talks at KubeCon and FOSDEM. It's heavily tested and should be production ready. The warning is more related to potential breaking changes than project quality.

**Comment by rakyll** [comment]
I am happy to give more insights about the status of OpenCensus. We have been going through a lot of API improvements lately but willing to finalize them soon. OpenCensus is based on our internal instrumentation library and most concepts have been tested for over a decade at Google. Even though the project is new, it is not a prototype or an experiment.

The benefit of OpenCensus would be the vendor-agnostic nature of the project. You can easily add more support for different backends by using the existing exporters. We already support Prometheus.

The other benefit would be ease of adding support for other types of diagnostics signals. We currently provide a tracing package but soon will have more signals represented (e.g. logging).

**Comment by alainjobart** [comment]
Note we have the go/trace package in Vitess right now, that is not implemented in open source, but uses the internal google tools mentioned above internally. So that part of the functionality would be trivial to plug in.

I'd be in favor of changing our stats package to add what opencensus needs, and then implement the plugin. The added information will be useful for a lot of implementations anyway.

@nerdatmath was looking at Promotheus at some point, so making sure he knows about this thread.

**Comment by demmer** [comment]
@rakyll Thanks for the input on the state of the project.

For the record I intended my earlier comment more tongue in cheek than a serious concern, but realize in hindsight that might not have come across as well as I would have liked.

From my initial look OpenCensus looks like a great effort and the more we can avoid reimplementing abstractions inside Vitess itself to support the various backends, the better as far as I'm concerned.

@sougou / @alainjobart This seems like a PMC question? :)

**Comment by enisoc** [comment]
FYI we took an early step towards option 1 in #1703 but didn't get very far. I'm not expecting this to factor into the decision; just providing cross-references to related work.

@alainjobart wrote:
> I'd be in favor of changing our stats package to add what opencensus needs, and then implement the plugin.

Do you mean that Vitess would still have its own `stats` abstraction, and OpenCensus would just be one backend for it? It sounds like @demmer is proposing that we get rid of our `stats` package and use OpenCensus as the only abstraction. Am I interpreting that right?

If that's the case, one prerequisite is that we could still export in native Go `expvar` format. Does anyone know if OpenCensus supports that? I haven't found anything on the main site or the Go lib.

**Comment by alainjobart** [comment]
I don't think we can just use opencensus as abstraction, unless it is also supported inside google, and exports the same variables as we've been exporting. Let me look into that...

**Comment by derekperkins** [comment]
>  proposing that we get rid of our stats package and use OpenCensus as the only abstraction

@enisoc That is what I was proposing. Writing different exporters is relatively trivial compared to adding instrumentation throughout the codebase.

> I don't think we can just use opencensus as abstraction, unless it is also supported inside google

It would be pretty ironic if the open sourcing of Google's metrics wasn't supported inside Google. :)

**Comment by enisoc** [comment]
Ironicker things have happened. Open source is hard. :)

**Comment by alainjobart** [comment]
So to move forward on this, here is a summary of where we are, I think:
- we want to support Promotheus exports in a more native way.
- OpenCensus seems like a great portable way to achieve this, and also buys us tracing.
- YouTube still needs the 'stats' interface abstractions, as our internal monitoring cannot be switched to OpenCensus yet. But it will happen at some point.

So the plan I'm proposing:
- we add to our current Stats abstractions enough to support OpenCensus. The new fields may be ignored by existing implementations.
- we implement the OpenCensus stats plugin.
- we implement the OpenCensus trace plugin (we have an interface for this already).
- eventually, when OpenCensus is the only implementation, we can remove the interfaces and use the library more directly.

(note this is what we've been doing so far, using a library directly when it's the only implementation, but adding an interface when someone needs a custom implementation, even if that custom implementation is not in the repository. For instance gRPC follows the same model, even though it's the only RPC system in open source. And we are probably going to add an interface for gzip too, to make cgzip optional).

**Comment by zmagg** [comment]
@alainjobart That sounds great! Thanks for summarizing and investigating whether or not YouTube could use OpenCensus directly yet. 

If there's enough consensus on this, then I'm going to get started on the first two bits of the plan 

> * we add to our current Stats abstractions enough to support OpenCensus. The new fields may be ignored by existing implementations.
> * we implement the OpenCensus stats plugin. 

From there, it seems like we can implement the trace plugin separately.

**Comment by zmagg** [comment]
I've started working on instrumenting Vitess with OpenCensus, and I've run into a few problems. 

1) The biggest one is that OpenCensus currently *only* provides a push-style Stats interface like:

```
func Record(ctx context.Context, ms ...Measurement)
```
which means that in places that we have a callback in the Vitess code, we'd need to manage a timer to periodically sample and execute the callbacks and record the resulting stats. Like in:

```
func NewMultiCountersFunc(name string, labels []string, f CountersFunc) *MultiCountersFunc {
```

There's some conversation about changing the API to do pull-based in this [Open Census issue](https://github.com/census-instrumentation/opencensus-go/issues/372). 

2) The OpenCensus API is still in a bit of flux and currently includes *several* steps for exporting even one stat. See: [opencensus#484](https://github.com/census-instrumentation/opencensus-go/issues/484)

I have confidence that these problems will be fixed and the API will finalize, but in the meantime, we (Slack) really need Prom-native stats, and I have some time to work on it right now. : ) 

In talking with @demmer it seems like the first issue is a showstopper for now. 

Our proposal is that we should *for now* just go ahead with instrumenting with Prometheus directly. We can revisit using OpenCensus down the road when the OpenCensus API has stabilized. The Prometheus work can also be leveraged for future OpenCensus work, as the info that's needed by the API is similar in both.

**Comment by sougou** [comment]
Making the right decision isn't as important as getting something working. The stats API is a small surface area and an in-process one. So, we can iterate on it as needed.

I'm ok with the simpler approach followed by forward iterations.

**Comment by alainjobart** [comment]
Looking at the threads you linked, it seems it's not even clear which model will win (push or pull). So I agree punting on OpenCensus is the right decision for now, and just implement the Promotheus plugin, and add the missing information for that.

**Comment by rakyll** [comment]
> There's some conversation about changing the API to do pull-based in this Open Census issue.

Just to be clear, we are primarily supporting the push model and will have it as our primary model. Pull model has been historically in use but the monitoring community has almost came to a consensus that now push is always preferred apart from Prometheus which copies what Borgmon did 10 years ago. Monarch, the replacement of Borgmon is implementing the push model. Most APM companies only care about the push model. 

For a node, it is safer to schedule aggregation and push the metric collection data rather than letting an external service invoking the collection.

We currently don't have a gauge type that is going to follow the same export path the views will follow. I don't think Vitess can benefit from OpenCensus until most issues above are resolved.
