### ISSUE TITLE
grpc_python_plugin doesn't install in the expected place

### ISSUE THREAD

**Issue by slanning** [vitessio/vitess#3659]
When running `make proto`, it would fail with "go/bin//grpc_python_plugin: program not found or is not executable". That file is a symlink to `go/dist/grpc/grpc/bins/opt/protobuf/grpc_python_plugin`, which is done by the last command of `travis/install_grpc.sh`. It turns out, for whatever reason, that for me `grpc_python_plugin` gets installed in `$grpc_dist/grpc/bins/opt/grpc_python_plugin`, which is one directory up (above the "protobuf" directory). I've tried `make cleanall` before `bootstrap.sh`, and it's still the same. It seems likely related to commit 7a75df060626a2a138186c3b35d but I didn't get to the bottom of it.

Once I manually fixed it with
```
rm $VTROOT/bin/grpc_python_plugin
ln -sf $grpc_dist/grpc/bins/opt/grpc_python_plugin $VTROOT/bin/grpc_python_plugin
```
`make proto` seems to work.

**Comment by morgo** [comment]
I believe this issue is still present, but we have been converting tests from Python to Go, and will be finished in the next few months. I am going to close this as won't fix.

(The build guides are no longer requiring python to be installed locally.)
