### ISSUE TITLE
Controlling autocommit behavior

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3664]
When running in autocommit mode, we optimized the vtgate behavior to perform a single round-trip to a vttablet if it was going to be a single-statement pass-through.

However, it's desirable for some use cases to extend this behavior to scatter statements. This cannot be automatically allowed because this can result in extended data loss if there is a chronic failure in one of the masters or connections.

@demmer and I have brainstormed this a bit. There are two ways this can be done:
1. A hint in the statement: `delete /*+ multi-shard-autocommit:true */ from table`. If autocommit is true, and there is a pass-through of a scatter DML, then this hint will be honored.
2. A new autocommit value: `set autocommit=2`. If this is set, then all multi-shard DMLs will be sent as pass-through.

The advantage of option 1 is that it's a statement level control. The downside is that we're introducing a brand new concept of controlling behavior using comment hints. We'll need to define the language and write a parser for it.

The advantage of option 2 is that we reserve comment hints for future behavior control. And obviously, a value of '2' means "do it more aggressively" :). The downside is that you don't get statement level control.

Overall, if statement level control is not a requirement, I prefer option 2.

**Comment by demmer** [comment]
Although I appreciate the simplicity of option 2, another downside besides the lack of per-statement control is the need to do another round trip to set the autocommit mode for a given session which somewhat negates the performance advantages of doing this in the first place.

Another option to consider would be a new flag at vtgate to opt-in to these semantics for all multi-shard autocommit transactions. This would be the simplest of all to implement but with the least flexibility.

All things considered, I lean towards option 1.

It's clearly true that controlling behavior with comment hints is a new construct, but we could build the parser generically, possibly even reusing something like `update_list` so in the future this could still be used for other statement-by-statement directives.
