### ISSUE TITLE
Improve treatment of LAST_INSERT_ID() in Vitess

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#3668]
For a table defined as
```
CREATE TABLE `my_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `col2` bigint(20) unsigned DEFAULT NULL,
  `col3` bigint(20) unsigned DEFAULT NULL,
  `type` enum(…,'enum_value',…) NOT NULL DEFAULT '...',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9999 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
```

I connect to a keyspace explicitly and see the following:
```
vt_app@localhost keyspace@master> insert into my_table (col2,col3,type) values (10000000000,10000000000,'enum_value');
Query OK, 1 row affected (0.01 sec)
vt_app@localhost keyspace@master> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                0 |
+------------------+
(id=2353 is the row inserted)
```

I expect to get back from `LAST_INSERT_ID()` the value 2353 but don't get it.

Explanation is:
* using autocommit
* this means that the insert connection for statment 1 and the select statement for statement 2 are not necessarily using the same mysql connection.

Current workaround:
* wrap in `BEGIN; .....; COMMIT;` to use the same connection

Improvement in behaviour (suggested by @sougou) is to record the value in the client session
and in subsequent statements replace `LAST_INSERT_ID()` by the value that was previously recorded.

This issue to to record this problem and a mention a possible solution suggested by @sougou.

**Comment by sjmudd** [comment]
oh and actually although the above statements sent via the mysql command line seem to fail had this been done by a mysql app the id would have been available to the app after the first statement, returned by mysqld. So things would have worked anyway.

**Comment by morgo** [comment]
Some followup discussion:

- MySQL does return the insert_id (and affected rows) as part of the OK packet.
- Currently vttablet's drop this, but in future they could be included in the gRPC response and stored in thread-local.
- The parser would then need to identify `select last_insert_id()` specifically and then return the value from thread-local.
