### ISSUE TITLE
Insert on duplicate key update support

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#3679]
### Description

Building plans that have insert on duplicate key that do not change the PK should be supported by Vitess. At the moment a query like the following will be rejected by the planner:

```
/* id is the pk and primary vindex */
INSERT into users(id, name) values (1, "rafael") on duplicate key update id = 1

INSERT into users(id, name) values (1, "rafael") on duplicate key update id = id
```

These queries should be supported.

**Comment by sabondano** [comment]
This works now! This issue can probably be closed :)
