### ISSUE TITLE
Errors during shard split cut over

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#3698]
### Description

In the final step of a shard split, where the cutover finally happens and traffic is migrated to the [shards](http://vitess.io/user-guide/horizontal-sharding/#switch-over-to-new-shards), sometimes we see errors where vtgates don't discover fast enough about the new master  and send traffic to old masters. All these requests fail correctly because those masters are no longer serving.  However, it would be better to have even smoother transitions during this phase.  I see two things that we can do to improve this:

1) Improve the logic that broadcast the change of the masters, so vtgates find out sooner about this change and don't try to send traffic to  old masters.
2) Hook these kind of failures into the buffering mechanism and do something similar to what happens during PlannedReparenting. I think we've never seen this kind of issue in those cases.

**Comment by mattlord** [comment]
I'm going to close this as it is no longer relevant.
