### ISSUE TITLE
vtgate log spam when using mysql command line tool (COM_FIELD_LIST)

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#3701]
Steps to reproduce:

`$ mysql -v -h <hostname> -P <port> --protocol=TCP -u mysql_user --database <keyspace> -p`
... enter password ...

Log contents shows something on the order of 80 lines of errors, all a little different but in this basic format:
`E0228 23:53:37.162292       6 server.go:394] Got unhandled packet from client 9615 (host:port), returning error: [4 95 100 114 111 112 95 109 101 95 99 111 110 118 101 114 115 105 111 110 95 116 97 103 115 95 116 101 115 116 0]`

**Comment by dweitzman** [comment]
Haven't seen this lately, so I suspect the linked PR did indeed fix it.

**Comment by deepthi** [comment]
The linked PR was never merged and @sjmudd reported similar errors just a few days ago
PR#4547

**Comment by harshit-gangal** [comment]
This is a deprecated feature as of MySQL 5.7.11
Therefore marking as won't fix.

https://dev.mysql.com/doc/internals/en/com-field-list.html

**Comment by deepthi** [comment]
Closing since we don't plan to fix.
