### ISSUE TITLE
Failed to reconnect to master

### ISSUE THREAD

**Issue by zanes2016** [vitessio/vitess#3708]
I'm seeing the following error:
```
failed: CHANGE MASTER TO MASTER_AUTO_POSITION = 1 cannot be executed because @@GLOBAL.GTID_MODE = OFF
```
But I'm not sure how to turn on the gtid_mode. I've tried adding `gtid_mode = ON` to the my.cnf files but that doesn't seem to help.

**Comment by zanes2016** [comment]
After working with this, the only solution I found that works is to edit the db init file to turn on GTID_MODE. Something like the following works:
```
echo "SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = ON;" >> $INIT_DB_SQL_FILE
echo "SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;" >> $INIT_DB_SQL_FILE
echo "SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;" >> $INIT_DB_SQL_FILE
echo "SET @@GLOBAL.GTID_MODE = ON;" >> $INIT_DB_SQL_FILE
```

**Comment by sougou** [comment]
Sorry about coming late on this one. The default db init file should have worked. Ideally, we should have dug in to figure out why. For now, if this works for you, then it's all good.
