### ISSUE TITLE
Orchestrator does not Support Multi-Source Replication

### ISSUE THREAD

**Issue by zanes2016** [vitessio/vitess#3735]
I'm trying to configure Vitess with [Orchestrator](https://github.com/vitessio/vitess/blob/d5a695e8d67f224c31686360ef464b004de62887/doc/ServerConfiguration.md#orchestrator) for automatic failovers. However, Orchestrator does not support multi-source replication (see the [faq](https://github.com/github/orchestrator/blob/master/docs/faq.md#does-orchestrator-support-multi-master-replication), this [feature request](https://github.com/github/orchestrator/issues/38) and this [thread](https://groups.google.com/d/msgid/orchestrator-mysql/5b5f0c19-76ba-4762-aaa4-d6ea6f22f854%40googlegroups.com?utm_medium=email&utm_source=footer)). It appears that Vitess sets the master with "`FOR CHANNEL`" in the "`CHANGE MASTER TO ...`" command. This automatically means MySQL is using multi-source replication.

Is there a way to configure Vitesss/MySQL to not use single-source replication (i.e. without the `FOR CHANNEL`)?

**Comment by sougou** [comment]
This is weird. Vitess also doesn't support multi-master. We should find out where the `for channel` is coming from.

**Comment by shlomi-noach** [comment]
`orchestrator` surely does nto add `FOR CHANNEL`. If `vitess` doesn't, neither, is it possible MySQL adds this by itself? Or just claims to add it?
Which MySQL version is this?

**Comment by shlomi-noach** [comment]
Just noting that `'CHANGE MASTER TO FOR CHANNEL '' executed` is unrelated to multisource replication. The empty channel (`''`) stands for "standard", single source replication.
