### ISSUE TITLE
Release 2.2

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3748]
We've decided to make a 2.2 release before going for 3.0.

I've made a doc for the release notes here: https://docs.google.com/document/d/104uhwwkztoYz1rW9vi8Ju9dsTotvsqCB6TkIclHJhWo/edit?usp=sharing.

Please review for any missing items. Also send me a request for edit permission if you'd like to improve the presentation.

**Comment by arthurnn** [comment]
This is a big list. 👍 
IMO, does not need to be perfect. I like how it is, and am satisfied in releasing like that. We can always come back to it if we forgot anything.
After that release, should we push a `CHANGELOG.md` file to the repo, and before merging any PR, as folks to update that file? so, for 3.0 we will have a full list of changes?

**Comment by sougou** [comment]
We had another round of arguments today during the monthly meetup. There was a proposal to bite the bullet and release 3.0. However, there was no consensus. I further discussed with @jvaidya, and we decided to just stick to the current plan, and the following tweaks:

* Release 2.2 as planned, with curt release notes as in the doc.
* Call it an interim release explaining that it's a stand-in because we haven't released anything in a long time.
* Reserve 3.0 for the big splash, where the 2.2 release notes will be better expanded and documented.
* Release 3.0 after site documentation is also fixed.

**Comment by demmer** [comment]
This sounds like a good plan -- as such are there actually any blockers to releasing 2.2?

**Comment by sougou** [comment]
No blockers. We just have to do the release process work.

**Comment by michael-berlin** [comment]
It's a lot of manual work ;(

See: https://vitess.io/internal/release-instructions/

The current instructions even ask you to go through the Kubernetes tutorial to make sure you didn't break anything. On the YouTube side, we had a colleague working on end-to-end "cluster" tests which would automate going through all Kubernetes tutorial steps. But unfortunately he didn't finish it before leaving the team ;)
