### ISSUE TITLE
Decouple restoreFromBackup from "YouTube doesn't need this feature"

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3753]
There are a few things that keep popping up where the `restoreFromBackup` flag got treated as a catchall for "features that YouTube never wants to use". It would be helpful to separate those out so that new users who may utilize non-native Vitess backup strategies don't see unexpected side-effects.

cc @enisoc 

https://github.com/vitessio/vitess/issues/2451 (Orchestrator Failover)
https://github.com/vitessio/vitess/pull/3746 (potentially ChangeSlaveType)
https://github.com/vitessio/vitess/issues/4115 (Disabling the restore option on the vttablet fails to setup metadata table)

**Comment by mattlord** [comment]
I'm going to close this for now as I don't *think* this is still an issue. If you think that's an incorrect assessment here please let me know and we can re-open it. Thanks!
