### ISSUE TITLE
Failed WorkflowCreate stuck forever, unable to do another WorkflowCreate

### ISSUE THREAD

**Issue by swallowstalker** [vitessio/vitess#3768]
Hi guys,

I'm using `vitess/base:latest` image from docker, and I run this command with successful result:

```
vtctlclient -server "host:port" WorkflowCreate schema_swap -sql 
"CREATE TABLE `something` (`id` bigint NOT NULL PRIMARY KEY, 
`type` varchar(255), `name` varchar(255));" -keyspace test_keyspace
```

But I encountered a problem while running this command:

```
vtctlclient -server "host:port" WorkflowCreate schema_swap -sql 
"CREATE TABLE `something2` (`id` bigint NOT NULL PRIMARY KEY, `type` varchar(255), `name` varchar(255)); 
CREATE TABLE `something3` (`id` bigint NOT NULL PRIMARY KEY, `type` varchar(255), `name` varchar(255));" -keyspace test_keyspace
```

It shows error:

```
Error: rpc error: code = Unknown desc = TabletManager.ExecuteFetchAsDba on test-0000000303 error: 
rpc error: code = Unknown desc = You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use near 
'CREATE TABLE `something3` (`id` bigint NOT NULL PRIMARY KEY, `type` varchar(255)' 
at line 2 (errno 1064) (sqlstate 42000) during query:...
```

which is a bit confusing because I think there wasn't any syntax error in that sql command. After that I proceed to retry with single mysql create statement that should complete in success (`CREATE TABLE something2` only), but it shows error:

```
Error: Shard -80 has an already started schema swap with a different set of SQL statements;
Shard 80- has an already started schema swap with a different set of SQL statements
```

It seems that something is stuck between the second failed WorkflowCreate attempt and the third one. The only way to make the WorkflowCreate run smoothly again is to drop database, then set everything up from the beginning. (I'm still learning vitess tutorial)

However, when I use the `ApplySchema` command, the command will just works as it is. Would anyone help shed some light on this problem?

**Comment by sougou** [comment]
It could be the `;` at the end of the statement that caused the syntax error. It also looks like the workflow is stuck in a weird state. I think you can reset the workflow by deleting the metadata in the `_vt` schema.

**Comment by swallowstalker** [comment]
Hi @sougou, thanks for your response, but where do I find the `_vt` schema to reset the workflow?

**Comment by swallowstalker** [comment]
Thanks @sougou, finally I'm able to reset the workflow. For those who encounters same problem, I recommend following this steps:

1. Find your shards' masters mysql port, under ports column (in dashboard)
1. Connect via mysql to those masters (review `GRANT` permission for your master, in my case I needed to add `GRANT ALL ON *.* TO 'vt_dba'@'%' IDENTIFIED BY 'password';` and `GRANT GRANT OPTION ON *.* TO 'vt_dba'@'%' IDENTIFIED BY 'password';`, I was following guide up until [Horizontal Sharding](https://vitess.io/user-guide/horizontal-sharding/) I need to change `config/init_db.sql`)
1. Go to `_vt` database then delete row with name `CurrentSchemaSwapSQL` and `LastStartedSchemaSwap`
1. Re-run your workflow

Voila! It should works.

**Comment by sougou** [comment]
Thanks for the tip :)
