### ISSUE TITLE
document best practice configuration for vitess and orchestrator

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#3778]
Orchestrator is the recommended solution for handling unplanned master failures, yet there is no clear documentation for what the best practice should be for configuring vitess to work with orchestrator and vice-versa.

As evidenced by the recent discussion in Slack, there are various ways of doing this but no clearly understood best practice.
https://vitess.slack.com/archives/C0PQY0PTK/p1521779844000122

**Comment by shlomi-noach** [comment]
cc @shlomi-noach (myself) for tracking this issue. I'll be able to provide some details.

**Comment by morgo** [comment]
+1 for an orchestrator integration guide in the docs

I have a note about this already in https://github.com/vitessio/website/issues/263 , so I am going to close this issue for now to reduce duplication. But let's get it done :-)

**Comment by morgo** [comment]
The content will appear as a user-guide shortly: https://github.com/vitessio/website/pull/351
