### ISSUE TITLE
support scatter select * with order by

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#3788]
A query of the form `SELECT * from t order by col` is unsupported if the query is a scatter query and results in the  error:
> unsupported: in scatter query: order by must reference a column in the select list:

For ease of migration into Vitess, this should be supported.

In prior discussions with @sougou we discussed two approaches for this:

1. Change the vtgate query planner and sort implementation so that it defers the resolution of the column name => column number until after it receives the results from each shard
2. Add knowledge of the SQL schema to the healthcheck protocol so vtgate can figure out the field list and resolve this at plan time.

**Comment by hellracer** [comment]
Any news?

**Comment by sougou** [comment]
There is non-elegant support for this now: https://github.com/vitessio/vitess/pull/4336. I think we can close this issue, unless we want to wait for the elegant implementation, which will be a while.
