### ISSUE TITLE
Syntax Error in SET @@SESSION.*

### ISSUE THREAD

**Issue by nithoalif** [vitessio/vitess#3793]
Hello, 

I found this problem regarding vtgate & mysql protocol. The following query resulted in syntax error.

```mysql
SET  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483, @@SESSION.sql_mode = 'STRICT_ALL_TABLES'
```
```mysql
#HY000vtgate: http://24d2a7038323:8080/: syntax error at position 16
```
It seems that `SET sql_auto_is_null` and `SET wait_timeout` has been addressed in #3611 and #3557. However, it seems that SESSION variable has not been addressed.

For the background information, I am using the following stack:
- ruby2.3.0
- rails 4.2.7.1
- mysql2 0.4.6

Best regards :)

**Comment by harshit-gangal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Support Set Statements](https://trello.com/c/l7N3HbtN/1-support-set-statements)

**Comment by harshit-gangal** [comment]
#3896 added Support for @@Session. grammar.
#5921 We are improving the way SET is handled. 
But, this issue can be closed.
