### ISSUE TITLE
split sql method is too simple

### ISSUE THREAD

**Issue by zr-hebo** [vitessio/vitess#3798]
https://github.com/vitessio/vitess/blob/93224ed799b07e738202d6840d6a64e3f3abcb71/go/vt/schemamanager/plain_controller.go#L39

**Comment by zr-hebo** [comment]
as code shows, this method will get wrong sqls, when thereis ';' in sql statements. We will deal this bug later.

**Comment by sougou** [comment]
Nice catch :)
