### ISSUE TITLE
panic during LegacySplitClone

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#3800]
### Description

We got the following error during a LegacySplitClone:

```
I0405 11:15:57.995253   23293 clone_utils.go:53] Found 5 refresh target aliases in shard ks/-08
W0405 11:15:57.997214   23293 tablet.go:429] cell:"cell" uid:xxxxx : node doesn't exist
I0405 11:15:58.007554   23293 clone_utils.go:53] Found 4 refresh target aliases in shard ks/08-10
I0405 11:15:58.010833   23293 legacy_split_clone.go:682] Refreshing state on tablet us_east_1-0100198108
I0405 11:15:58.011220   23293 legacy_split_clone.go:682] Refreshing state on xxxxx
I0405 11:15:58.011527   23293 legacy_split_clone.go:682] Refreshing state on xxxxx
I0405 11:15:58.011825   23293 legacy_split_clone.go:682] Refreshing state on xxxxx
I0405 11:15:58.012127   23293 legacy_split_clone.go:682] Refreshing state on xxxxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x648332]

goroutine 2646 [running]:
vitess.io/vitess/go/vt/topo.(*TabletInfo).AliasString(0x0, 0xc60ef8, 0xc4204086a0)
      src/vitess.io/vitess/go/vt/topo/tablet.go:173 +0x22
vitess.io/vitess/go/vt/worker.(*LegacySplitCloneWorker).copy.func6(0xc4204086a0, 0xc420292000, 0xc420384a80, 0xc42044aa80, 0x0)
       src/vitess/go/vt/worker/legacy_split_clone.go:682 +0x8a
created by vitess.io/vitess/go/vt/worker.(*LegacySplitCloneWorker).copy
       src/vitess.io/vitess/go/vt/worker/legacy_split_clone.go:680 +0x1826
```

**Comment by michael-berlin** [comment]
I guess that the bug occurs when you have a "ShardReplication" object in the topology with orphaned tablet aliases.

You can run `vtctl ShardReplicationFix <keyspace>/<shard name>` to get the bad entry removed from the object.

The entry, for which no "Tablet" object in the topology exists, got also logged here:

> W0405 11:15:57.997214   23293 tablet.go:429] cell:"cell" uid:xxxxx : node doesn't exist

It was logged here: https://github.com/vitessio/vitess/blame/master/go/vt/topo/tablet.go#L429


## Background:

The SplitClone code has to ping the MASTER of each destination shard to refresh its state. it will then read the "Shard" object from the topology and find out that it should turn on filtered replication.

Currently, the code does too much: It only pings the MASTER, but instead every tablet in **each** cell.

It does so by reading the "ShardReplication" object from the topology first. This one has a list of all tablet aliases. Then the code retrieves the "Tablet" object from the topology for each alias.

In your case there is probably an inconsistency i.e. a tablet is listed in the "ShardReplication" object for which there is no "Tablet" object.

The split clone code cannot deal with this and therefore panics here.

In terms of bugfixes: The real solution is to get rid of this code and only call the refresh state RPC on each destination master. For that, we can use the existing "tsc" (TabletStatsCache) object. It is also used by other code within the worker to find out the current MASTERs.

**Comment by ajm188** [comment]
Going to close this as `LegacySplitClone` and friends have been deprecated and are being removed soon.
