### ISSUE TITLE
how to set charset utf8mb4  in my.cnf

### ISSUE THREAD

**Issue by curls** [vitessio/vitess#3817]
hi, my project need surpport emoji. so I must change utf8 to utf8mb4 in my.cnf file like this: 

> [client]
>default-character-set = utf8mb4

>[mysql]
>default-character-set = utf8mb4

>[mysqld]
>character-set-client-handshake = FALSE
>character-set-server = utf8mb4
>collation-server = utf8mb4_unicode_ci

but I don't know how to config this in vitess. please help me, thanks!

**Comment by sougou** [comment]
You should be able to add this to the appropriate cnf file here: https://github.com/vitessio/vitess/tree/master/config/mycnf. You can also specify additional ones through the `EXTRA_MY_CNF` env var. Here is an example: https://github.com/vitessio/vitess/blob/master/examples/local/vttablet-up.sh#L62.

**Comment by sougou** [comment]
Closing this. Please re-open if the suggestion didn't work.
