### ISSUE TITLE
Change the config to use `utf8mb4`

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#3866]
Change the config to use `utf8mb4` as the default character set for both MySQL & Vitess

**Comment by morgo** [comment]
I have been cleaning up the same config files (currently a draft, I plan to merge in Vitess 5.0) in https://github.com/vitessio/vitess/pull/5326

The upgrade path from utf8 -> utf8mb4 is not always straight forward, and mb4 can be a lot slower up until (but not including) MySQL 8.0.

So my suggestion would be:
- MySQL 8.0: utf8mb4 (its actually the default)
- All others: utf8
