### ISSUE TITLE
Unable to stop the vtctld service

### ISSUE THREAD

**Issue by KarthikeyanBrigita** [vitessio/vitess#3871]
when running this "./vtctld-down.sh" command  it shows the following error
                                                         
Stopping vtctld replicationcontroller...
Error from server (NotFound): replicationcontrollers "vtctld" not found

**Comment by sougou** [comment]
vtctld is just a process. The shell script performs a force kill at the end. So, it was most likely killed successfully. Should be good to ignore the error.
