### ISSUE TITLE
Make vtctld proxy all the nodes of the cluster

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#3878]
Currently, vtctld has links to various vttablets. However, those URLs may not be reachable either due to firewall rules or due to being hidden within Kubernetes. In such cases, it may be beneficial if vtctld itself acted as proxy to those URLs.

This should simplify many deployments.

**Comment by mattlord** [comment]
I'm closing this for now as [the Vitess project is moving towards replacing `vtctld` with the new `VTAdmin` tool](https://github.com/vitessio/vitess/issues/7117) so new features in this space would typically occur there. Please let me know if you think that this is still relevant with that in mind and we can re-open it. Thanks!
