### ISSUE TITLE
make site_test: Init() err: zk already inited

### ISSUE THREAD

**Issue by kivikakk** [vitessio/vitess#3893]
Hi there!

I'm trying to get vitess in a local dev environment ready to hack on. I have what I think is a working dev environment on a fresh VM. `make site_test` goes swimmingly, until the following:

``` console
ok      vitess.io/vitess/go/vt/workflow (cached)
ok      vitess.io/vitess/go/vt/workflow/resharding      (cached)
ok      vitess.io/vitess/go/vt/workflow/topovalidator   (cached)
ok      vitess.io/vitess/go/vt/wrangler (cached)
ok      vitess.io/vitess/go/vt/wrangler/testlib (cached)
--- FAIL: TestLifeCycle (0.00s)
        zkctl_test.go:38: Init() err: zk already inited
FAIL
FAIL    vitess.io/vitess/go/vt/zkctl    0.003s
Makefile:89: recipe for target 'unit_test' failed
make: *** [unit_test] Error 1
kivikakk@debian:~/src/vitess.io/vitess$
```

Just to be sure, I've done this on a fresh boot, without touching anything before running the tests, and the result is (still) like this.

Am I doing something obvious wrong? Thanks for your time!

**Comment by michael-berlin** [comment]
https://github.com/vitessio/vitess/blob/master/go/vt/zkctl/zkctl.go#L232

This is the code which returns true and then gets you that error.

When I add `fmt.Println(myidFile)` there and run `go test -v vitess.io/vitess/go/vt/zkctl`, it always prints `/tmp/vt/zk_255/myid` for me.

That file doesn't exist for me and therefore the test passes.

Can you please check what it's doing there for you?

**Comment by kivikakk** [comment]
``` console
kivikakk@debian:~/src/vitess.io/vitess$ go test -v vitess.io/vitess/go/vt/zkctl
=== RUN   TestLifeCycle
/home/kivikakk/vtdataroot/zk_255/myid
--- FAIL: TestLifeCycle (0.00s)
        zkctl_test.go:38: Init() err: zk already inited
FAIL
FAIL    vitess.io/vitess/go/vt/zkctl    0.004s
kivikakk@debian:~/src/vitess.io/vitess$ cat !$
cat ~/vtdataroot/zk_255/myid
255
```

Indeed, it exists! I removed it, and all tests pass.

Thank you! ❤️
