### ISSUE TITLE
potential deadlock in TabletStatsCache

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#3899]
As part of the investigation into #3898, I discovered a potential deadlock in `TabletStatsCache`:

`TabletStatsCache.StatsUpdate` finds and locks the `tabletStatsCacheEntry` for a given tablet, then calls `updateAggregateMap` which locks the `TabletStatsCache` itself. This is called via the `Healthcheck` listener code on every update from a tablet.

On the other hand, `TabletStatsCache.Subscribe` first takes a lock on the `TabletStatsCache`, then walks the data structure and takes read locks on each of the `tabletStatsCacheEntry` objects in turn so that it can build an array of `srvtopo.TargetStatsEntry` structs for each tablet. This seems to be called from `discoveryGateway.StreamHealth` => `StreamHealthFromTargetStatsListener`.

I can't actually find anywhere where this is called, since vtgate and others call `StreamHealth` directly on the individual tablet connections and not by going through the `DiscoveryGateway` implementation.

Still, we should either remove the dead code if it really isn't needed, or fix the implementation to not have this potential deadlock.

**Comment by sougou** [comment]
Correction: there is no data race on `TabletStats.Stats`. I'm still looking for a better way to model this.

**Comment by GuptaManan100** [comment]
`TabletStatsCache` doesn't seem to exist in the latest version of Vitess anymore. We can open a new issue if the problem still exists with the latest information.
