### ISSUE TITLE
wrong when i execute ./zk-up.sh in MacOS

### ISSUE THREAD

**Issue by longf0720** [vitessio/vitess#3907]
maybe there is a problem: no /bin/true file in MacOS

when i execute ./zk-up.sh in $VTTOP/examples/local， i got this:
➜  local git:(dev) ./zk-up.sh
Starting zk servers...
Waiting for zk servers to be ready...
ZK server number 1 failed to start. See log:
    /Users/long/go/vtdataroot/tmp/zkctl_1.out
ZK server number 2 failed to start. See log:
    /Users/long/go/vtdataroot/tmp/zkctl_2.out
ZK server number 3 failed to start. See log:
    /Users/long/go/vtdataroot/tmp/zkctl_3.out
Started zk servers.
^C
E0509 21:00:32.280620   28009 vtctl.go:103] action failed: AddCellInfo interrupted
./zk-up.sh: line 58: /bin/true: No such file or directory

should this be fixed?

**Comment by sougou** [comment]
@arthurnn who knows to deploy vitess on mac may be able to help you :).
