### ISSUE TITLE
Query for shard_name in vindex function

### ISSUE THREAD

**Issue by shellderp** [vitessio/vitess#3918]
#3094 adds vindex function to do query such as:

```select keyspace_id from user_index where id = :id```

Ideally we would also be able to query for shard_name, like so:

```select shard_name from user_index where id = :id```

Then we can easily target the shard for given id.

**Comment by aquarapid** [comment]
#7044 added support for this, e.g. (for unsharded):

```
mysql> select shard, hex_keyspace_id from xxhash where id = 2;
+-------+------------------+
| shard | hex_keyspace_id  |
+-------+------------------+
| -     | 8b59801662b52160 |
+-------+------------------+
```
