### ISSUE TITLE
passthrough dml erroneously removes table name from plan metrics

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#3927]
After enabling the `-queryserver-config-passthrough-dmls` I noticed that all of the DML queries were being recorded as `Join` for all the per-table query metrics.

This is because the tablet planbuilder exits too soon before the table name is extracted from the query and assigned to the plan.

**Comment by sougou** [comment]
This might have been fixed a while ago. If not, the recent refactor definitely did.
