### ISSUE TITLE
./etcd-up.sh fails to create pods

### ISSUE THREAD

**Issue by Coolfeather2** [vitessio/vitess#3930]
Following https://vitess.io/getting-started/#start-a-vitess-cluster

Ran configure.sh
set backup to file
ran etcd-up.sh

no pods created
no error messages printed

**Comment by RyanHartje** [comment]
Did you setup the etcd operator first?

It is mentioned in the prerequisites but would be easy to miss, I know I did at first.

The docs link to https://github.com/coreos/etcd-operator/blob/master/doc/user/install_guide.md
but this didn't work for me. I had to use the helm chart for etcd-operator. Even still, I wasn't able to bring up either the vitess helm chart or ./vtctld-up.sh bits.

**Comment by Coolfeather2** [comment]
I did not set it up the etcd operator first

**Comment by sougou** [comment]
The setting up of the operator should resolve this. Optimistically closing this.
