### ISSUE TITLE
Issue with bootstrap.sh

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#3931]
After syncing with vitess upstream master, my local environment started to fail. I'm getting this error when trying to run `govendor sync`: 

```
Updating govendor dependencies...
Error: lstat /vagrant/src/vitess.io/vitess/src: no such file or directory
govendor sync
	Ensures the contents of the vendor folder matches the vendor file.
	Options:
		-n           dry run, print out action only
		-insecure    allow downloading over insecure connection
		-v           verbose output
```

I think the issue was caused by this change: https://github.com/vitessio/vitess/commit/9a6f21e3c2cca612f213656ed8958d8793d5719f#diff-ddc2cfd1974a9de860d19fbdc66bbe83R114.

Without the fix, bootstrap.sh works in my environment 😅 - @michael-berlin, do you know why we need to add `$VTROOT` to the gopath? Can we remove this line altogether ?

**Comment by michael-berlin** [comment]
Yes, `$VTROOT` must be in your `$GOPATH`. In fact, it's the only thing in my Go path:

```sh
# This is my $VTTOP i.e. where Git is checked out.
$ pwd
/home/mberlin/workspace/vitess/src/vitess.io/vitess

$ echo $VTROOT
/home/mberlin/workspace/vitess

$ echo $GOPATH
/home/mberlin/workspace/vitess
```

**Comment by rafael** [comment]
Hmm - I see. 

I recreated my env from scratch and it fixed the problem. Going to close this.
