### ISSUE TITLE
[question] InitShardMaster hang forever. how to check lockInfo

### ISSUE THREAD

**Issue by linuxgood1230** [vitessio/vitess#3951]
- when I have two instance, one replica, and a rdonly
- I invoke InitShardMaster -force 
- vtctd log 
  - I0521 15:59:12.727229    7395 locks.go:351] Locking shard user_keyspace/0001-0002 for action InitShardMaster(shard-0000000883)

- lockShard never return

**Comment by sougou** [comment]
Hi there,

There are a few reasons why `InitShardMaster` can hang:
1. There are no replicas connected to a master, and it's expecting a semi-sync replication ack. This will make it hang forever.
2. You're trying to launch vttablet against an already running mysql instance, and for some reason, vttablet thinks that it has to restore from a replica. You can force it not to restore by adding the `-restore_from_backup=false` flag to your vttablet start script.
3. There may be stray vttablet records in the topology, and the script may be trying to contact the non-existent vttablets. If so, delete those records using `DeleteTablet`

**Comment by linuxgood1230** [comment]
Thanks
I found , A shard at least must have a rdonly and a replica, then it can InitShardMaster succ

**Comment by derekperkins** [comment]
If you don't have semi-sync enabled, it will complete with a single replica.
