### ISSUE TITLE
SHOW VITESS_TARGET

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3954]
In our code we want to use the `USE <target>` syntax to temporarily switch shard targeting and then revert to the previous target but there is no way to tell what the previous target is. We should have a `SHOW` command to return `Session.TargetString`.

**Comment by sougou** [comment]
I think the compatible syntax would be this
```
mysql> select database();
+------------+
| database() |
+------------+
| NULL       |
+------------+
1 row in set (0.01 sec)

mysql> use a
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select database();
+------------+
| database() |
+------------+
| a          |
+------------+
1 row in set (0.00 sec)

mysql> 
```

**Comment by tirsen** [comment]
https://github.com/vitessio/vitess/pull/3962
