### ISSUE TITLE
Change defaults for mysqlprotocol

### ISSUE THREAD

**Issue by smanpathak** [vitessio/vitess#3956]
Vitess.io endorses mysqlprotocol as the preferred way of connecting to vitess. Can we have the defaults in the helm chart expose mysql port?

**Comment by derekperkins** [comment]
The problem with setting it on by default is that we would then have to have a default password. The way it works now, you have to provide a k8s secret to be used as the password.

**Comment by RyanHartje** [comment]
Is there any reason why this project couldn't mimic the grafana chart, where by default it generates a random string, and uses that as the default password, allowing the user to override that if they wish?

**Comment by boopathykpm** [comment]
Any plan on rolling out this feature, anytime soon?

**Comment by sougou** [comment]
Give this announcement #6439, we can say that this issue is also obsolete. The newer operator recommends mysql protocol already. I'll close this issue if there are no other requests.
