### ISSUE TITLE
Orchestrator service failure

### ISSUE THREAD

**Issue by smanpathak** [vitessio/vitess#3958]
I deployed vitess helm chart with orchestrator enabled. It fails to come up. Logs from orchestrator nodes --
2018/05/21 22:05:00 [ERR] raft: Failed to make RequestVote RPC to 10.31.244.84:10008: dial tcp 10.31.244.84:10008: i/o timeout
2018/05/21 22:05:00 [ERR] raft: Failed to make RequestVote RPC to 10.31.249.135:10008: dial tcp 10.31.249.135:10008: i/o timeout
2018/05/21 22:05:00 [WARN] raft: Election timeout reached, restarting election
2018/05/21 22:05:00 [INFO] raft: Node at 10.31.249.197:10008 [Candidate] entering Candidate state
2018/05/21 22:05:00 [DEBUG] raft: Votes needed: 2
2018/05/21 22:05:00 [DEBUG] raft: Vote granted from 10.31.249.197:10008. Tally: 1
2018/05/21 22:05:01 [ERR] raft: Failed to make RequestVote RPC to 10.31.244.84:10008: dial tcp 10.31.244.84:10008: i/o timeout
2018/05/21 22:05:01 [ERR] raft: Failed to make RequestVote RPC to 10.31.249.135:10008: dial tcp 10.31.249.135:10008: i/o timeout
2018/05/21 22:05:02 [WARN] raft: Election timeout reached, restarting election
2018/05/21 22:05:02 [INFO] raft: Node at 10.31.249.197:10008 [Candidate] entering Candidate state
2018/05/21 22:05:02 [DEBUG] raft: Votes needed: 2
2018/05/21 22:05:02 [DEBUG] raft: Vote granted from 10.31.249.197:10008. Tally: 1
2018-05-21 22:05:02 DEBUG raft leader is ; state: Candidate

**Comment by smanpathak** [comment]
kubectl get svc,rs,statefulsets,po
NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                        AGE
svc/etcd-global             ClusterIP   None            <none>        2379/TCP,2380/TCP              42m
svc/etcd-global-client      ClusterIP   10.31.247.144   <none>        2379/TCP                       42m
svc/etcd-zone0              ClusterIP   None            <none>        2379/TCP,2380/TCP              42m
svc/etcd-zone0-client       ClusterIP   10.31.243.212   <none>        2379/TCP                       42m
svc/kubernetes              ClusterIP   10.31.240.1     <none>        443/TCP                        3d
svc/orchestrator            ClusterIP   10.31.242.12    <none>        80/TCP                         42m
svc/orchestrator-0          ClusterIP   10.31.244.84    <none>        80/TCP,10008/TCP               42m
svc/orchestrator-1          ClusterIP   10.31.249.135   <none>        80/TCP,10008/TCP               42m
svc/orchestrator-2          ClusterIP   10.31.249.197   <none>        80/TCP,10008/TCP               42m
svc/orchestrator-headless   ClusterIP   None            <none>        80/TCP,10008/TCP               42m
svc/vtctld                  ClusterIP   10.31.245.109   <none>        15000/TCP,15999/TCP            42m
svc/vtgate-zone0            ClusterIP   10.31.244.111   <none>        15001/TCP,15991/TCP,3306/TCP   42m
svc/vttablet                ClusterIP   None            <none>        15002/TCP,16002/TCP            42m

NAME                          DESIRED   CURRENT   READY     AGE
rs/etcd-operator-555f4df458   1         1         1         3d
rs/vtctld-7859b88f49          1         1         1         42m
rs/vtgate-zone0-6fbb4689cf    3         3         3         42m

NAME                                   DESIRED   CURRENT   AGE
statefulsets/orchestrator              3         3         42m
statefulsets/zone0-test-db-0-replica   3         3         42m

NAME                                READY     STATUS    RESTARTS   AGE
po/etcd-global-2d4tprb89j           1/1       Running   0          42m
po/etcd-global-hml7cb8q28           1/1       Running   0          42m
po/etcd-global-mxvmfhh6zf           1/1       Running   0          42m
po/etcd-operator-555f4df458-pttsq   1/1       Running   0          3d
po/etcd-zone0-45z5kwbr9h            1/1       Running   0          42m
po/etcd-zone0-grbbbg4tqm            1/1       Running   0          42m
po/etcd-zone0-lc4h96gt5n            1/1       Running   0          42m
po/orchestrator-0                   2/3       Running   0          42m
po/orchestrator-1                   2/3       Running   0          42m
po/orchestrator-2                   2/3       Running   0          42m
po/vtctld-7859b88f49-g9mp7          1/1       Running   1          42m
po/vtgate-zone0-6fbb4689cf-fv6pp    1/1       Running   2          42m
po/vtgate-zone0-6fbb4689cf-hmvvz    1/1       Running   2          42m
po/vtgate-zone0-6fbb4689cf-jbxjc    1/1       Running   2          42m
po/zone0-test-db-0-replica-0        4/4       Running   0          42m
po/zone0-test-db-0-replica-1        4/4       Running   0          42m
po/zone0-test-db-0-replica-2        4/4       Running   0          42m

**Comment by derekperkins** [comment]
What version of Orchestrator did you deploy?

**Comment by smanpathak** [comment]
It is using the default: vitess/orchestrator:3.0.6

**Comment by derekperkins** [comment]
Where are you deploying it to? It looks like there is a networking problem preventing the orchestrator nodes from communicating. Does the rest of your deployment work properly?

**Comment by smanpathak** [comment]
Yes, vitess is up and running fine. This deployment is on GKE

**Comment by derekperkins** [comment]
Can you try removing the orchestrator components and then redeploying?

My other thought is that we haven't tested the helm chart with RBAC enabled, so maybe that's causing some communication issues.

**Comment by derekperkins** [comment]
cc @enisoc

**Comment by smanpathak** [comment]
Turns out the statefulset pod-name label was missing. This was GKE K8S 1.8.0 cluster.
This seems to have been fixed. https://github.com/kubernetes/kubernetes/issues/44103

**Comment by derekperkins** [comment]
Makes sense. The notes say that Orchestrator only works on 1.9 or later for that reason.

**Comment by sougou** [comment]
This looks resolved.
