### ISSUE TITLE
mysqlctl(d) prometheus metrics endpoint

### ISSUE THREAD

**Issue by rolandhawk** [vitessio/vitess#3963]
I can not access `/metrics` for `mysqlctld` process. Is it intended? Because I can find influxdb backend in mysqlctld but not prometheus backend.

If it's okay to add `/metrics` endpoint for `mysqlctl(d)` process, I would like to contribute a PR for it.

Thanks.

**Comment by sougou** [comment]
I think this is a good idea. You'll probably just need to add the `plugin_...` file under cmd.
