### ISSUE TITLE
Create default Grafana dashboard

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3964]
Now that we've added Prometheus support, it'd be nice to have at least a starter dashboard to share with people. @zmagg @demmer - are you using Grafana and if so, do you have something shareable? 

Once we have that, I'd like to add Vitess support to Percona Monitoring & Management.
https://jira.percona.com/browse/PMM-1963
cc @vadimtk

**Comment by sougou** [comment]
Under here https://vitess.io/user-guide/server-configuration/, the critical list of debug/vars are published. They'd be a great starting point.

**Comment by zmagg** [comment]
Ooh, neat idea @derekperkins . We do use Grafana, but we're still in the process of moving our dashboards over to the new inside-Vitess Prometheus stats, but I can share a few dashboards in the next few weeks once we have them ported over.

**Comment by hellracer** [comment]
Hi @zmagg, do you intend to open source this? care to share a github link please?

**Comment by L3o-pold** [comment]
@zmagg Do you have any news about releasing some Grafana dashboard example?

**Comment by derekperkins** [comment]
Here's a link to a gist @sougou shared a year ago that sounds fairly dated, but who knows

> I have this grafana config that I used for a demo a long time ago 
https://gist.github.com/sougou/09d53531c5aa6baeb417cf50476dbe89

**Comment by sougou** [comment]
This was submitted by @guidoiaquinti
