### ISSUE TITLE
Support for the DO statement

### ISSUE THREAD

**Issue by dveeden** [vitessio/vitess#3972]
https://dev.mysql.com/doc/refman/8.0/en/do.html

Examples:
```
DO 1;
DO SLEEP(1);
```

Basically to run an expression without caring for the resultset.
This is sometimes used in health checks etc.

I started to work on this on a branch: https://github.com/dveeden/vitess/tree/do_statement

**Comment by harshit-gangal** [comment]
supported via #6239
