### ISSUE TITLE
olap vs oltp support of show and set

### ISSUE THREAD

**Issue by slanning** [vitessio/vitess#3977]
# this "show tables" syntax works

> vt_app@localhost vitess_schema@replica> show tables from vitess_schema like 'TableName';
> +-------------------------------------------+
> | Tables_in_vitess_schema (TableName) |
> +-------------------------------------------+
> | TableName                  |

# even in the master

> vt_app@localhost vitess_schema@master> show tables from vitess_schema like 'TableName';
> +-------------------------------------------+
> | Tables_in_vitess_schema (TableName) |
> +-------------------------------------------+
> | TableName                  |

# set workload to olap

> vt_app@localhost vitess_schema@master> set workload='olap';
> vt_app@localhost vitess_schema@master> show tables from vitess_schema like 'TableName';
> ERROR 1105 (HY000): vtgate: http://hostname:12345/: unsupported construct: show
> ERROR 1105 (HY000): vtgate: http://hostname:12345/: unsupported construct: show
> ERROR 1105 (HY000): vtgate: http://hostname:12345/: unsupported construct: show

Now we also can't set workload='oltp' because of "unsupported construct: set".

@sougou also mentioned he wants to merge the oltp and olap code paths.

**Comment by klkyy** [comment]
maybe we need to enable "set workload='oltp'" when we are in olap workload.
the others may not need to enable according the design of streamexecute?? @sougou

**Comment by sougou** [comment]
We need to support all statements in both modes eventually.

**Comment by harshit-gangal** [comment]
This is supported by moving show commands to be planner/engine base in v10. Resolving.
