### ISSUE TITLE
Dependency on MySQLdb causes test failues

### ISSUE THREAD

**Issue by dveeden** [vitessio/vitess#3978]
There are many test failures when I run `make test` after running `bootstrap.sh` and sourcing `dev.env`.

The output of `local.backpup-1.1.log:
```
Traceback (most recent call last):
  File "test/backup.py", line 23, in <module>
    import MySQLdb
ImportError: No module named MySQLdb
```

For now fixed by using pip to install mysql-python

Is bootstrap.sh supposed to install this or report that it is missing?

**Comment by sougou** [comment]
https://vitess.io/getting-started/local-instance/ lists a bunch of things to be pre-installed using apt-get. My guess is that they didn't want to add `sudo` commands in bootstrap.

**Comment by morgo** [comment]
I am going to close this as won't fix. We are quickly converting the test suite to Golang, and the contributing guides no longer suggest installing Python to run tests.. so this is a CI only problem.
