### ISSUE TITLE
Support SHOW CREATE TABLE without default keyspace

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#3985]
Currently you need to have a default keyspace for running SHOW CREATE TABLE. We should support SHOW CREATE TABLE without a default keyspace by auto-resolving the table name and then forwarding the SHOW CREATE TABLE to the first shard in that keyspace. We can assume table schemas are the same across shards for now.

**Comment by harshit-gangal** [comment]
This query works now.
