### ISSUE TITLE
TopologyWatcher removes the tablet record when polling the topo service fails

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#3987]
#### Overview of the Issue
When the topology service is unavailable, TopologyWatcher has a race condition which can cause it to remove the tablet from the routing, causing queries to fail with "no valid tablet: node doesn't exist".

#### Details
TopologyWatcher first gets a list of known tablets and then refreshes each in turn. However if the intial list succeeds but a subsequent Get request for a given TabletInfo record fails, it removes knowledge of that tablet from the HealthCheck interface and therefore won't route queries properly.

Note that setting the option to avoid refreshing tablets that was introduced in #3965 would have avoided this issue, but the behavior should be changed even when refreshing.

#### Reproduction Steps
We noticed this when doing a consul leader election under high QPS load, but it's not so straightforward to induce manually.

**Comment by mattlord** [comment]
We're trying to do some house cleaning to better serve users and I don't have a clear understanding of how to repeat this issue with Vitess 11/12 and a recent Consul version -- and I'm not entirely sure that the described behavior is wrong/incorrect/undesired -- so I'm going to close for now.

If you believe this is still an issue today, would you  be able to provide any additional info to help move this forward? Or if I'm missing/misunderstanding something please let me know as well. We can then re-open the issue in either case.

Thanks!
