### ISSUE TITLE
Applying empty unsharded schema gives "node doesn't exist" error

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#4013]
If you try to apply the "empty unsharded schema" on a completely fresh cluster you get a "node doesn't exist" error.

Like this:
```
> vtctlclient -server localhost:27001 ApplyVschema -vschema '{"sharded":false}' actors
main.go:114] initTabletMapProto failed: SaveVSchema(actors) failed: node doesn't exist
```

The reason is that `{"sharded":false}` serializes to the empty byte array and this code uses that as a signal to delete the vschema node. Unfortunately the node doesn't exist at this point (because it's a fresh cluster) so we get this weird error message. I wasted a few hours on this yesterday. :-)

```
	if len(data) == 0 {
		// No vschema, remove it. So we can remove the keyspace.
		return ts.globalCell.Delete(ctx, nodePath, nil)
	}
```

**Comment by dkhenry** [comment]
closed by #4868
