### ISSUE TITLE
Danger lurking in using "." to encode multi-timings labels

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4015]
Some of the stats-related code will encode a collection of label/tag names or values into a single string by separating them with a "."

If you end up with label names or values containing dots themselves, bad things can potentially happen, including panics.

Seems like the ideal solution would take string manipulation out of the equation entirely and keep lists as lists, wrapped in some helper type to assist with encoding for expvars

Short of that, sanitizing category names and values as they are created to remove dots and/or using a less-common character than a dot might reduce risk

**Comment by dweitzman** [comment]
One possible defense: https://github.com/vitessio/vitess/compare/master...dweitzman:crash_protection

Not totally satisfied with it, but neither do I have a concrete plan for a better solution.

**Comment by sougou** [comment]
I think it's better to just sub the `.` with underscore.

**Comment by dweitzman** [comment]
Yeah, substitution sounds simple and adequate.

**Comment by dweitzman** [comment]
Closing for now, since the immediate problem is mitigated.

The solution requires a bit of diligence going forward since it would be easy to re-introduce the bug for new types of metrics in the future by calling `strings.Join`instead of `safeJoinLabels`
