### ISSUE TITLE
SBR & v2 API: upsert fails with errno 1062 AlreadyExists if primary key is auto-inc and a unique index prevents the insert

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#4050]
Sugu, you're only executing if the INSERT of an UPSERT fails due to a 'PRIMARY' key constraint: https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/query_executor.go#L657

e.g. MySQL would return something like this then:

```
MariaDB [test]> INSERT INTO t1 (id, unique_column) VALUES (1, "bla");
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
```

Is there a reason why you cannot consider other UNIQUE key constraints as well?

e.g. in our case we're actually omitting the primary key column and therefore MySQL returns a different error. Vitess returns that error to us instead of UPDATEing the query.

```
MariaDB [test]> INSERT INTO t1 (unique_column) VALUES ("bla");
ERROR 1062 (23000): Duplicate entry 'bla' for key 'unique_idx_unique_column'
```

**Comment by sougou** [comment]
Yes. I thought I added a TODO to eventually address non-pk unique keys. Just haven't done the work yet.

**Comment by sougou** [comment]
SBR support is essentially deprecated now. No new features will be added for it at this point, unless they impact existing production.

We should eventually delete the code once everyone has migrated out.
