### ISSUE TITLE
Add link to Vitess Slack to CNCF

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4098]
We just get one of the fancy new Slack invite links and host it at slack.vitess.io. Once that is done, we should link that on the CNCF site. Do we have control over our DNS?

![image](https://user-images.githubusercontent.com/3588778/43104287-d93c4092-8e85-11e8-950f-f8da29220845.png)

**Comment by sougou** [comment]
Seems to work now. Don't know who fixed it.
