### ISSUE TITLE
Disabling the restore option on the vttablet fails to setup metadata table

### ISSUE THREAD

**Issue by ameetkotian** [vitessio/vitess#4115]
#### Overview of the Issue
If `-restore_from_backup` is disabled, `vttablet` does not setup the `_vt.local_metadata`. `_vt.local_metadata` is used, among others, by tools like `orchestrator` to get shard information and failover logic. 

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Start a new tablet process without `-restore_from_backup` option. 
1. Check the `_vt` database is empty:
```
 SELECT *  FROM _vt.local_metadata ;
```

The issue is `populateMetadataTables` is called only part of `mysqlctl.Restore`.

**Comment by derekperkins** [comment]
related to #3753

**Comment by derekperkins** [comment]
duplicate of #4006, but as this issue is better documented, I'll close the other issue.

cc @lokanadhamm
