### ISSUE TITLE
update -mysql_server_version to return a more recent version than Vitess-5.5.10

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4119]
Discussed on slack but I couldn't find an issue. @Sougou thought there was one but I don't see it.

MySQL latest GA version is 8.0 with 5.7 being GA for some time. Advertising via vtgate that vitess is 5.5.10 seems a bit old.

I'd suggest that the default version suggested is 5.7.X as that is unlikely to cause surprises to most people.

See: https://github.com/vitessio/vitess/blob/b9ec54a2e8f27ea0013027411ed0536cb3751ee3/go/mysql/server.go#L37 which was the reference pointed at during the conversation on slack.

**Comment by acharis** [comment]
vtgates now have a flag: `-mysql_server_version`

**Comment by acharis** [comment]
```
commit b33e3c35902d5a45676baa64daae4c0834ad3d3d (origin/server-version-flag)
Author: Alex Charis <acharis@hubspot.com>
Date:   Wed Feb 14 22:46:19 2018 -0500

    add mysql_server_version flag to control version displayed to STATUS
```

**Comment by morgo** [comment]
There were some issues with switching it to 5.7 because drivers tried to issue an rpc to refresh the connection (a 5.7 feature). It is now supported, so we should be able to bump it.
