### ISSUE TITLE
Pluggable / Simplified MySQL Server Buffering Strategies

### ISSUE THREAD

**Issue by danieltahara** [vitessio/vitess#4138]
Per https://github.com/vitessio/vitess/issues/3718, https://github.com/vitessio/vitess/pull/4120, and some offline discussion with @sougou and @alainjobart, it would be great to re-work the buffering strategy for the mysql server. In particular, it could be:
1. Less complex. Allocations aren't as expensive as they used to be
2. More efficient in steady state usage.

In particular, for use cases where there are ~100k+ steady state connections to the server, there is a ton of wasted memory sitting around in connection buffers: https://github.com/vitessio/vitess/blob/master/go/mysql/conn.go#L199

Ideally, the per-connection buffer would disappear entirely, and even better would be to write a pluggable/custom bufio implementation that only allocates memory when needed, rather than preallocating a buffer that it holds until the end of time.

One such strategy would be to have a "1 byte" buffer and then allocate a larger one (perhaps from a sync.Pool) on receiving data, which costs two syscalls but is probably okay for most use-cases. Another would be to use EPOLL or something similar https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb.

I know at one point @alainjobart had done some throughput tests and things. It would be good to see what those were as well as some thoughts for how to proceed.

**Comment by sougou** [comment]
I agree with the general idea. Some qualifying remarks:

* We should definitely get rid of the three ephemeral modes and just switch to `sync.Pool` uniformly. This should also get rid of `c.buffer`.
* In the early days of go, syscalls were very expensive. This was actually the reason why bufio was created. However, the situation might have changed. So, we'll need to confirm with benchmarks before switching to the "1-byte" scheme.
* If the benchmarks look good, then we should just drop bufio and directly read into a sync.Pool buffer. This will avoid the extra copy.
* As for writes, I don't think we need bufio at all (need confirmation).
* The EPOLL approach is too risky. We'll be depending on a library that is less used. We may also miss out on bug fixes and improvements going into the heavily used net package.

**Comment by LK4D4** [comment]
@sougou I also thought about a more efficient pool. We could use bucketed by size pools for `*[]byte` to avoid getting a too small buffer from the pool.

**Comment by sougou** [comment]
I agree. Makes sense.

**Comment by danieltahara** [comment]
Another update here -- the fixed buffers cause SWEEP stalls for allocations of the same size as the buffer: https://github.com/golang/go/issues/18155#issuecomment-418487869

So we'll get an extra benefit here of lower steady-state memory usage and fixing GC stalls.

**Comment by danieltahara** [comment]
Resolved.
