### ISSUE TITLE
Filtered replication does not handle BIT(1) fields properly

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#4145]
Filtered replication generates bad SQL for `BIT(1)` statements.

For example a delete statement generates the following statement:
```
DELETE FROM table_name WHERE ...snip... AND bit_column='\x01';
```
But this DELETE statement will never match.

Instead the binlog player should generated the following SQL statement:
```
DELETE FROM table_name WHERE ...snip... AND bit_column=b'01';
```

This one does match.

**Comment by sougou** [comment]
There is a similar issue #3984

**Comment by tirsen** [comment]
We've tested this with MySQL 5.7 and this is NOT an issue on that version.

However this IS an issue in production and we are still running 5.6 there. So potentially this is a MySQL version discrepancy?

**Comment by deepthi** [comment]
We are able to reproduce this with MySQL 5.7. We will go ahead and fix it.
