### ISSUE TITLE
MariaDB doesnt' support innodb_support_xa

### ISSUE THREAD

**Issue by dkhenry** [vitessio/vitess#4148]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### MariaDB doesn't support innodb_support_xa

As of version 10.3 of mariadb the innodb_support_xa flag is no longer supported. This should be removed from the default.cnf file and moved to the mysql specific cnf file

#### Reproduction Steps

Steps to reproduce this issue, example:

Deploy Vitess using mysqlctld and mariadb > 10.3.0

#### Binary version
Example:

```sh
dk at 12u in ~/go/src/vitess.io/vitess/config/mycnf on master ✔                                                                                                                                 
> git rev-parse HEAD 
18cd13d3fb324c661985a6034c8b68541723b836
```

**Comment by klkyy** [comment]
remove the innodb_support_xa=1 from config/mycnf/default.cnf

the new mariadb not support this option now，make xa transaction as default option.
