### ISSUE TITLE
Planned Reparent got stuck with no obvious reason or logging

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4159]
#### Overview of the Issue

I wanted to test a planned reparent to see how the process worked, how long it would take and to get an idea of behaviour etc. (Currently I do not have orchestrator setup and I wanted to update the tablet version on the master.)

So I ran the following:
`$ vtctlclient -server :15999 PlannedReparentShard -keyspace_shard=keyspace/0 -new_master=cell2-0000002002`

* The process started but got stuck.
* No errors were shown so it was not apparent to me what had gone wrong

(I'll provide some logging shortly)

I was expecting this to be a fast process, and if there were issues to get an error. Given this is a planned change it seems sensible to be able to do more safety checks and highlight any obvious problems prior to starting. This allows the administrator to be able to correct them first without producing an outage.  Given things got stuck (over 30 minutes) I'd expect any "issues" to get highlighted pretty quickly to I can look at them and take the appropriate action.

In the end with some help from @sougou it seems that there was a misconfiguration in one of the slaves having a similar server_id as another server though at the time replication from the old master to replicas had seemed to work fine.

Logging showed several "5 minute pauses" seeming to indicate some timeout was being triggered. It wasn't clear from the logging what that problem was as no warnings or errors were reported.

The issue I see here is to try to make this process more resilient. To report warnings or errors if the process is not running as expected, to basically allow the user to identify and rectify the issue concerned.

When looking at the config during this process it looks like it mainly worked. A single slave had replication stopped the others had been moved under the new master which was configured as read_write and were replicating. (I still don't have full monitoring setup yet on this cluster.)

#### Reproduction Steps

Run the command as shown. I'll upload some log info from the vtctld daemon to give some indications of what it logged.

#### Binary version

Version of Vitess from a week ago with the S3 PR  (https://github.com/vitessio/vitess/pull/4068) applied.

#### Operating system and Environment details

Linux, CentOS 7, bare metal.

#### Log Fragments

To be uploaded. (I need a reference to this issue first)

**Comment by sjmudd** [comment]
logging can be seen here: https://gist.github.com/sjmudd/ddac3c544c39f5abcd3206cf7c33afcf

I note: no reference seems to be made to the zookeeper node on cell2. Is this deliberate or was there some sort of firewall preventing that? I notice that access to the tablets on cell2 worked fine.  Perhaps this was one of the problems but logging does not indicate this very clearly.

**Comment by sjmudd** [comment]
vttablet.INFO logging can be seen here: https://gist.github.com/sjmudd/e67a2b39738e59a8544f9b976db40a0a

Note: the "stuck" / paused in logging. In the end I restarted the tablet but it looks like _maybe_ vitess was *silently* waiting for replication to be running forever.

**Comment by leoxlin** [comment]
Can you do a goroutine dump with pprof the next time it gets stuck?

We experienced a stuck planned reparent issues recently as well:
https://github.com/vitessio/vitess/issues/4197

**Comment by sougou** [comment]
Addressed via #4335
