### ISSUE TITLE
select count(distinct col1) from t1.... not works properly

### ISSUE THREAD

**Issue by klkyy2018** [vitessio/vitess#4181]
#### Overview of the Issue

select count(distinct col1) from t1.... not works properly

#### Reproduction Steps
drop table if exists messages; 
create table messages (page int primary key, supplier varchar(60), price int, quantity int);
insert into messages(page, supplier, price, quantity) values(1, 'A', 100, 1000), (2, 'B', 300, 500),(3, 'C', 500, 300),(4, 'A', 200, 500);
select count(distinct supplier) from messages;

vschema file: vitess/example/vschema.json

**Comment by klkyy** [comment]
data distribution
total 2 shards
shard1: A, B, C
shard2: A

**Comment by sougou** [comment]
#4917
