### ISSUE TITLE
security alert in guestbook example

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4204]
Github's security alerting flagged a couple of files from the guestbook examples as having security issues:

![image](https://user-images.githubusercontent.com/3308504/45822219-d558f900-bc9f-11e8-9281-6eea088a59dc.png)

**Comment by sougou** [comment]
I previously relied on @arthurnn to fix these. Is there anyone else who's familiar with ruby?

**Comment by arthurnn** [comment]
guestbook and keytar are python sub-projects, so I guess someone could fix those dependencies.
I can fix the Gemfile.lock one, just let me know which gems should be updated.

**Comment by arthurnn** [comment]
ffi update https://github.com/vitessio/vitess/pull/4210
