### ISSUE TITLE
Make canMoveViaGTID smarter - be aware of erroneous transactions on new master

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4239]
First mentioned in https://github.com/github/orchestrator/issues/640 but made into a separate issue to keep things clean.

The function `canMoveViaGTID` may need to be smarter as it currently does not take into account some issues which can arise and which may break replication when used from `moveReplicasViaGTID`. They are:

Erroneous transactions on the new master. if `master_auto_position` = 1 then the slave will try to sync any GTIDs it is missing. Often erroneous transactions will have disappeared from binlogs triggering the sync between the slave and it's new master to fail. So recognising if all needed GTIDs are available would be good.

**Comment by sjmudd** [comment]
Oh. sorry. This went to the wrong place my copy paste in the browser changed this to the wrong github project. My apologies.

**Comment by rafael** [comment]
I wonder if it applies to vitess too. We ran into something similar to this with a `PlannedReparent` once.

**Comment by shlomi-noach** [comment]
haha I'm sure it applies to vitess too 😆
