### ISSUE TITLE
vitess helm install fail:could not find the requested resource

### ISSUE THREAD

**Issue by rocket1024** [vitessio/vitess#4245]
vitess helm install fail, 

wondering if fetch chart vitess-0.9.0 from remote or need building locally?
pls note:
1. "helm install stable/mysql" is ok, so k8s is working normally
2. local pv has been setting up.
3. <vitess/examples/kubernetes>using vitess/lite image is working normally, to save up config time, I just try helm install, but it fail
4. have been try shrink replica size in values.yalm, limit cpu/mem, all not working

/vitess/helm/vitess$ helm ls
/vitess/helm/vitess$ helm install . --debug                                                                                                                                                   
[debug] Created tunnel using local port: '42723'
[debug] SERVER: "127.0.0.1:42723"
[debug] Original chart version: ""
[debug] CHART PATH: /vitess/helm/vitess
Error: release nosy-poodle failed: the server could not find the requested resource

/vitess/helm/vitess$ kc -n kube-system logs tiller-deploy-7f4974b9c8-c2w6l --since=1m
[tiller] 2018/10/05 11:31:45 preparing install for 
[storage] 2018/10/05 11:31:45 getting release "nosy-poodle.v1"
[tiller] 2018/10/05 11:31:45 rendering vitess chart using values
[tiller] 2018/10/05 11:31:45 performing install for 
[tiller] 2018/10/05 11:31:45 executing 0 crd-install hooks for nosy-poodle
[tiller] 2018/10/05 11:31:45 hooks complete for crd-install nosy-poodle
[tiller] 2018/10/05 11:31:49 executing 0 pre-install hooks for nosy-poodle
[tiller] 2018/10/05 11:31:49 hooks complete for pre-install nosy-poodle
[storage] 2018/10/05 11:31:49 getting release history for ""
[storage] 2018/10/05 11:31:49 creating release "nosy-poodle.v1"
[kube] 2018/10/05 11:31:49 building resources from manifest
[kube] 2018/10/05 11:31:49 creating 10 resource(s)
[tiller] 2018/10/05 11:31:49 warning: Release "nosy-poodle" failed: the server could not find the requested resource
[storage] 2018/10/05 11:31:49 updating release "nosy-poodle.v1"	
[tiller] 2018/10/05 11:31:49 failed install perform step: release nosy-poodle failed: the server could not find the requested resource

**Comment by derekperkins** [comment]
@rocket1024 That's not an issue with the Vitess chart, it's an issue with helm 2.11. https://github.com/helm/helm/issues/4699 If you downgrade both your client and tiller to 2.10, the installation will work just fine. I ran into this exact same issue yesterday.

**Comment by rocket1024** [comment]
thanks derekperkins, that works.
