### ISSUE TITLE
helm vitess storage choice and  unbound error for PersistentVolumeClaim in local-storage class

### ISSUE THREAD

**Issue by rocket1024** [vitessio/vitess#4247]
two questions:
question one: there seems to me there are three choice of data storage with helm vitess, could u have a comment, is there something pv can support Dynamic Volume Provisioning and better performance?

1.emptydir:potential dangerous with data lost risk
2.local pv:seems still need much manual setting, and no support Dynamic Volume Provisioning
3.nfs pv:good Dynamic Volume Provisioning, but poor performance since tcp stack overhead.

question two:

I try to bring up 1 table, but it seems met a pvc unbound error, pls note, pv has been allocated, below is my setting, pls have a check if only storageClassName is needed change for pvc, thanks
1.cmd use
helm install  -f site-values.yaml .
2.value.yaml change, just some resource constrain
diff --git a/helm/vitess/values.yaml b/helm/vitess/values.yaml
index 724ef3a..39ffe58 100644
--- a/helm/vitess/values.yaml
+++ b/helm/vitess/values.yaml
@@ -141,12 +141,12 @@ vttablet:

`-`      memory: 1Gi
`+  `    memory: 0.5Gi
   mysqlResources:

`-  `    memory: 1Gi
`+  `    memory: 0.5Gi

   dataVolumeClaimAnnotations:
   dataVolumeClaimSpec:
@@ -154,7 +154,7 @@ vttablet:
     
`- `   storageClassName: "pd-ssd"
`+  `  storageClassName: "local-storage"
     accessModes: ["ReadWriteOnce"]
     resources:
       requests:

3.kubectl get pod
vtgate is stuck at wait for vttable, since cell does not comes up
vttable does not has a unbound error, seems pvc can not put into bound state, could be any additional configure?
......
vtgate-zone1-545569979-9hh6k                       0/1     CrashLoopBackOff   5          5m
zone1-unsharded-dbname-0-replica-0                 0/4     Pending            0          5m
zone1-unsharded-dbname-0-replica-1                 0/4     Pending            0          5m
4. kc get pv
NAME        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS    REASON   AGE
vitess-pv   20Gi       RWO            Delete           Available           local-storage            7m
5.kc describe po zone1-unsharded-dbname-0-replica-1
Volumes:
  vtdataroot:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vtdataroot-zone1-unsharded-dbname-0-replica-0
    ReadOnly:   false
  vt:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  default-token-kl6bx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kl6bx
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  112s (x154 over 26m)  default-scheduler  pod has unbound PersistentVolumeClaims

**Comment by brunowego** [comment]
Same issue here.

**Comment by derekperkins** [comment]
I'm not sure that I fully understand the problem. I've used multiple `storageClassName` values successfully, and I am currently running on local ssds using local PV.

If you are interested in auto-provisioning local-pvs, you can use https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner.

**Comment by mattlord** [comment]
Closing this as it's gone cold. If you have any additional information please let us know. Thanks!
