### ISSUE TITLE
unbalanced load due to lookup vindexes that match no rows

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4258]
## Description
For all queries that use a secondary lookup vindex but find no match in the vindex, vtgate routes a `where 1 != 1` FieldQuery to the first shard in the keyspace.

This results in unbalanced query load on that shard as compared to all the others.

## Details
When a lookup vindex query doesn't match any rows in the backing table, it returns `DestinationNone`. This results in resolving no shard targets for the given query which makes it into the following logic in `vtgate/executor/route.go:`

```
	// No route.
	if len(rss) == 0 {
		if wantfields {
			return route.GetFields(vcursor, bindVars)
		}
		return &sqltypes.Result{}, nil
	}
```

The `GetFields` call ends up routing to `DestinationAnyShard` which could in principle actually route to any shard, but in practice always routes to the first shard in the keyspace.

## Remediation
The best fix for this issue would be if the vtgates were to obtain the table schema over the healthcheck protocol. That way we wouldn't have to route the FieldQuery to the tablet itself, but could instead resolve the fields at vtgate.

A less optimal but more straightforward approach would be to update `DestinationAnyShard.Resolve` to randomly pick a shard out of the set of all shards. This should fix the unbalance issue but would induce randomness which might make testing more complicated.

**Comment by sougou** [comment]
We should be able to cache the field info, but we should probably wait till vttablet starts sending schema updates. That way, we won't go stale if the underlying schema changes.

**Comment by sougou** [comment]
#4522
