### ISSUE TITLE
Support sharding by VARCHAR

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#4260]
We need (eventually) shard a bunch of columns by VARCHAR. Normally we use LONG INT columns for sharding but these are all lookup tables so we need to shard them by the input key, not the entity identifier.

Currently `hash.go` converts VARCHAR columns to an integer by parsing it as an alphanumeric integer using the call path `ToUint64 -> newIntegralNumeric -> strconv.ParseInt`. This is almost Perl-esque. If the VARCHAR parses as a number then we can shard by it, otherwise we can't. Is anyone relying on this behavior? Otherwise it would be much better if we just hash the VARCHAR string instead.

If there are users that rely on this behaviour (which seems crazy) then we need to add a new `string_hash` vindex type.

**Comment by sougou** [comment]
`unicode_loose_md5`
