### ISSUE TITLE
Have vttablet validate and populate _vt.local_metadata on start up when orchestrator flags are present

### ISSUE THREAD

**Issue by brybry192** [vitessio/vitess#4264]
Please search the existing issues for relevant feature requests, and use the [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

https://github.com/vitessio/vitess/blob/2e94e3e255d55adf4a38e64602e28857e9180017/go/vt/vttablet/tabletmanager/restore.go#L186

#### Feature Description

Have vttablet validate and populate _vt.local_metadata on start up when orchestrator flags are present on the command line. A quick scan of the code indicates that this workflow is only executed during the backup/restore procedure by mysqlctld. If managing mysql directly without mysqlctld, the metadata does not get populated and orchestrator is unable to determine the tablet alias needed during failover. 

#### Use Case(s)

mysql managed independently of mysqlctld.

**Comment by sougou** [comment]
Dup of #4115

**Comment by sougou** [comment]
Fixed in #4403
