### ISSUE TITLE
Shard splitting without controlling mysql replication

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#4266]
It would be very convenient to be able to do shard splitting without having control of replication.

[Here](https://docs.google.com/document/d/18q_nmaDXs_w-4zpQZSfYjIXBS5SJpE-zAR4tLFcy984) is a design doc describing the feature, when it would be useful, and what needs to be done to implement the feature.

**Comment by systay** [comment]
We (Square) are currently working on implementing this functionality.

**Comment by mattlord** [comment]
I'm going to close this as done for now as it's very old and Vitess is very different today. If there's stills something here please let me know and I'll open a new issue with more details based on main.
