### ISSUE TITLE
Add Vitess driver support to DBeaver

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4274]
This would help with ease of adoption and discoverability.
Issue in DBeaver: https://github.com/dbeaver/dbeaver/issues/4404

@hmcgonig

**Comment by derekperkins** [comment]
cc @leoxlin @harshit-gangal

**Comment by harshit-gangal** [comment]
I am not sure why fat jar is not shown on the maven central search repository. 
But, It is uploaded here http://central.maven.org/maven2/io/vitess/vitess-jdbc/2.2.0/

I will have to check this, issue should be around visibility only.

To unlock you, download the fatjar from the link above and refer it in DBeaver. This should work.

**Comment by derekperkins** [comment]
I've got it running in DBeaver, this issue was more about making Vitess more visible.

What the JDBC driver doesn't do however is respond with details for navigation (applicable to most clients). When using the MySQL protocol, you can see one specific keyspace (as seen below), but it is prefixed with `vt_`. That means that most calls fail, since `vtgate` is expecting to see the keyspace name without `vt_`.
![image](https://user-images.githubusercontent.com/3588778/47039014-1c6fc800-d140-11e8-938c-7eb02609b5a0.png)

When using the JDBC driver, it doesn't show any schemas or tables.
![image](https://user-images.githubusercontent.com/3588778/47039117-62c52700-d140-11e8-8af9-f0ad80c550da.png)

IMO, The expected behavior would be to have each keyspace returned as its own schema, that would then allow you to navigate into tables and fields.

**Comment by harshit-gangal** [comment]
Navigation is possible now with DBeaver

**Comment by apip6678** [comment]
i cant find class with fatjar
