### ISSUE TITLE
support partial results on scatter queries

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4279]
## Description
Return partial results in a scatter query where some shards fail.

## Motivation
Currently, if any individual shard encounters an error during a scatter query, the entire operation is failed, returning an aggregated error result to a client. This behavior is necessary to preserve atomicity semantics.

However, certain workloads could benefit from returning partial results to clients and an indication that one or more of the shards failed.

The goal of this PR is to augment Vitess with a non-standard syntax to opt into this behavior.

## Status
The feature is implemented in four PRs:
- Add vtgate engine support for the SCATTER_ERRORS_AS_WARNINGS query directive to suppress errors #4228 
- Add mysql protocol support to return warning count #4272
- Add vtgate session support to store warnings and return in `SHOW WARNINGS`  #4280
- Integrate all of the above so the scatter partial query directive stores errors in the session as warnings. #4293 

## Proposal and Approach
*After some discussion on Slack the earlier proposal has been modified. I left it the original proposal description below for historical context.*

1. To opt-in to the feature, a new query comment directive will be added:

```
SELECT /*vt+ SCATTER_ERRORS_AS_WARNINGS=1 */ * from table ...
```

When this is set, regardless of whether any of th shard queries fail, the query result contains whichever rows were returned. If the rows were used in an aggregation, the aggregation operates on the partial results.

2. To indicate to the client that the query partially succeeded, vitess will store the per-shard errors as "warnings" in the vtgate session.

Specifically, an array of warning records will be stored in the Session object with a string description of the issue along with an appropriate mysql error code depending on the actual error.

When querying vtgate using the GRPC protocol, the updated session containing these warnings is returned to the client alongside the query results, so clients can check for any warnings locally.

When querying vtgate using the mysql protocol, the protocol supports returning a warning count along with the results. This way clients can determine immediately whether or not the query was fully or partially successful. To obtain the specific warnings from the previous query, vtgate will support the `SHOW WARNINGS` command https://dev.mysql.com/doc/refman/5.6/en/show-warnings.html to return the warnings from the previous query.

## Original Proposal (Deprecated)
The proposed syntax is:

```
SELECT SHARD_PARTIAL shard_error(), id, val FROM table WHERE val2 > 123
```

The vtgate query planner will process the above syntax and produce a plan that executes the following standard sql on each shard:

```
SELECT null as shard_error, id, val FROM table WHERE val2 > 123
```

Assuming a four shard system where `shard/40-80` encounters a timeout during the processing, the above query plan would return:

```
Fields: [
    shard_error: varchar, id: bigint, val: varchar
]
Rows: [
    [null, 1, 'val1'],
    [null, 2, 'val2'],
    ['shard/40-80: GRPC timeout accessing tablet 12345', null, null],
]
```

This non-standard syntax includes two complementary elements, one to select the partial success mode, and one to surface errors to the client.

### Partial Mode Proposal (Deprecated)

The first syntax addition enables the caller to opt-in to partial results if a shard fails.

The choice of the `SHARD_PARTIAL` keyword is is analogous to the sequences model of `SELECT NEXT ...` by adding an explicit keyword to differentiate the desired behavior from the implicity atomic model of normal SQL.

An alternative and simpler approach would be to use a comment directive like `SELECT /*vt! SHARD_PARTIAL=1 */ ...`. Despite the fact that this new feature changes the atomicity characteristics of the query, the pre-existing MULTI_SHARD_AUTOCOMMIT comment directive and to some extent all multi-shard transactions similarly toes the line on atomicity.

Another approach would be to re-use an existing mysql keyword, e.g. `SELECT IGNORE ...` or `SELECT NO TRANSACTION ...`. However none of the existing keywords seem as clear as the explicit new keyword.

### Shard Error Surfacing Proposal (Deprecated)
The second element of the above proposal is the introduction of a non-standard function `shard_error()` into the field list of the query string.

As mentioned above, the query planner will turn the function into a field specification of `null as shard_error`. As such, if all of the shard queries succeed, vtgate has no need to do any postprocessing of the results.

Furthermore, in the event that one or more shards do fail, the Field specification in the result already contains a place to put the indication of error.

Finally, if a client simply wants to do a best-effort scatter query and doesn't need to know whether or not one of the shards failed, then it could simply omit the `shard_error()` function from the field list.

A potential downside of this approach is that the error string itself contains both the name of the shard that failed as well as the specific error string. So any client-side code that would want to operate on the specific shard result would have to parse the contents of this string out, and an alternative approach could use two separate columns.

**Comment by tirsen** [comment]
I really love the direction this feature is coming. Can I ask how you're going to be using it?

**Comment by sougou** [comment]
All done!
