### ISSUE TITLE
Fail SplitClone if the target rdonly tablets aren't caught up on replication delay

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4284]
If SplitClone picks a rdonly tablet from a target shard that's not caught up on replication is may appear to succeed without actually creating good shards. For example, if -80 is a new shard and its master has extra rows that don't exist in its rdonly, SplitClone will fail to delete those extra rows

This isn't a problem if you start from a totally empty shard, but if you had a previous sharding attempt or you're starting from a copy of the original full shard you could get yourself into trouble.

**Comment by sougou** [comment]
the final sync must delete extra rows. It doesn't do it now?

**Comment by dweitzman** [comment]
I think even the offline phase uses the rdonly tablets as the source of truth to figure out if there are extra rows to delete.

**Comment by sougou** [comment]
I looked at the code. It seems to do the right thing. I see all three operations: insert, update and delete, which will bring the destination shards fully in sync with the source: https://github.com/vitessio/vitess/blob/master/go/vt/worker/row_differ.go#L170

Did you actually run into this? If so, how should we reproduce?

**Comment by sougou** [comment]
According to my read of the code, it should delete (3, "I do not belong 3"). The code path I expect it to take is: https://github.com/vitessio/vitess/blob/master/go/vt/worker/row_differ.go#L174, where the comment says that it found an extra row in target, and must delete it.

**Comment by dweitzman** [comment]
SplitClone can't delete (3, "I do not belong 3") because it never reads from any `@master` instance. It only looks at `@rdonly` instances, which don't mention (3, "I do not belong 3"): 

https://github.com/vitessio/vitess/blob/master/go/vt/worker/split_clone.go#L996
https://github.com/vitessio/vitess/blob/master/go/vt/worker/tablet_provider.go#L82

**Comment by sougou** [comment]
Ohhh. I totally misunderstood the problem. I should learn to read the bug title...
Yes. If this is the case, it's definitely a problem, and we need to fix it.

**Comment by sougou** [comment]
Addressed via #4331
