### ISSUE TITLE
./etcd-up.sh not creating pods.

### ISSUE THREAD

**Issue by shinebayar-g** [vitessio/vitess#4351]
Actually there is exact same issue here https://github.com/vitessio/vitess/issues/3930. Since it's closed I'm opening new issue here to find answer. I'm trying to install my first ever Vitess deployment. 
I'm following [getting-started](https://vitess.io/getting-started/) documentation.
At **Start an etcd cluster** step, when I run `./etcd-up.sh` command it returns:
```
./etcd-up.sh 
Creating etcd service for 'global' cell...
etcdcluster.etcd.database.coreos.com/etcd-global created
Creating etcd service for 'test' cell...
etcdcluster.etcd.database.coreos.com/etcd-test created
```
But expected pods are not created.

**Note:** I've installed **etcd operator** using helm chart.

**Edit:** Oh at step 2 **Configure site-local settings** I don't have access to Google Cloud Storage bucket service. So I tried to select _file_ option. But I didn't know what to put there.

**Comment by trevex** [comment]
The etcd-operator by default will only watch CRDs in its own namespace. Are they both in the same namespace?

**Comment by shinebayar-g** [comment]
Yes, I've installed etcd-operator in **default** namespace.

**Comment by trevex** [comment]
Well since the logs apply the etcdcluster manifests successfully, it would indicate etcd-operator is not picking them up. Anything in the logs of the etcd-operator?

**Comment by shinebayar-g** [comment]
Nothing but bunch of these spamming every few seconds.
```
time="2018-11-08T15:12:47Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:12:55Z" level=info msg="Start reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:12:56Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:13:04Z" level=info msg="Start reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:13:04Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:13:12Z" level=info msg="Start reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-11-08T15:13:12Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
```

**Comment by hellracer** [comment]
If you built or compile your own not using a docker most likely the problem is this
ETCD_VERSION=$(cat "${VTROOT}/dist/etcd/version")
Change this to ETCD_VERSION=$(cat "${VTROOT}/dist/etcd/.installed_version")

should spawn etc perfectly.

**Comment by shinebayar-g** [comment]
I've just recreated everything.
1. Installed etcd operator using helm
2. `➜  ~ go get vitess.io/vitess/go/cmd/vtctlclient`
3. `➜  ~ cd $GOPATH/src/vitess.io/vitess/examples/kubernetes`
`Required ruby-2.2.3 is not installed.
To install do: 'rvm install "ruby-2.2.3"'`   -> Do I need to install ruby?
4. 
```
➜  kubernetes git:(master) ./etcd-up.sh
Creating etcd service for 'global' cell...
etcdcluster.etcd.database.coreos.com/etcd-global created
Creating etcd service for 'test' cell...
etcdcluster.etcd.database.coreos.com/etcd-test created
```
5. 
```
➜  kubernetes git:(master) kubectl get pods | grep etcd
etcd-global-9dh8bnzkct                                            1/1     Running   0          40s
etcd-global-f97bpzp2k9                                            1/1     Running   0          56s
etcd-global-wn5sbnljqx                                            1/1     Running   0          1m
etcd-operator-etcd-operator-etcd-backup-operator-7b888b9b8fs2qg   1/1     Running   0          2m
etcd-operator-etcd-operator-etcd-operator-896895ddc-fmqfk         1/1     Running   0          2m
etcd-operator-etcd-operator-etcd-restore-operator-9d7cb559frbnf   1/1     Running   0          2m
etcd-test-49khxt6lrd                                              1/1     Running   0          39s
etcd-test-q9mkn6sdhj                                              1/1     Running   0          55s
etcd-test-wfvjm2r2x9                                              1/1     Running   0          1m
```

Same steps followed this time, looks like issue is resolved?

**Comment by sougou** [comment]
Cool :+1:
