### ISSUE TITLE
vtgate complain unsupported: join with USING(column_list) clause 

### ISSUE THREAD

**Issue by hellracer** [vitessio/vitess#4362]
#### Overview of the Issue

Unsupported JOIN statement USING clause

#### Reproduction Steps

Execute query and talk to vtgate...

1. Run `SELECT 
            transaction_id,
            device_timestamp,
            latitude,
            longitude
FROM 
           recordheader JOIN device_event USING(transaction_id) LIMIT 1;
`
1. View error
ERROR 1105 (HY000): vtgate: http://vtgate01:15001/: unsupported: join with USING(column_list) clause

#### Binary version
Example:

```sh
giaquinti@workspace:~$ vtgate --version
Version: 52df90c (Git branch 'master') built on Wed Nov 14 08:28:21 UTC 2018 by vitess@zk using go1.11.2 linux/amd64giaquinti@workspace using go1.10 linux/amd64
```

#### Operating system and Environment details

Ubuntu 16.04 x86_64

**Comment by brunowego** [comment]
Yah, exactly same issue here 👍

**Comment by brunowego** [comment]
@hellracer this clause is mapped in not supported cases.
https://github.com/vitessio/vitess/blob/83c0faa981de680e14b17482bc6d7baaa4ce7355/go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt#L90-L92

**Comment by sougou** [comment]
There was something about this construct that made it non-trivial to blindly expand it. I think it was related to multi-table joins, or maybe it required some knowledge of the schema to do the right thing. Otherwise, this would have been implemented long ago.

**Comment by brunowego** [comment]
I'm running Matomo where that implements `Zend\DB` behind. To solve it, by now, I'm try fix with a workaround...

**Comment by derekperkins** [comment]
I think the tricky part is that mysql collapses the USING columns rather
than returning the keys from both sides.

**Comment by GuptaManan100** [comment]
@harshit-gangal This is now supported, right?

**Comment by harshit-gangal** [comment]
We still do not support it.

**Comment by harshit-gangal** [comment]
It is supported now https://github.com/vitessio/vitess/pull/10226
