### ISSUE TITLE
Support for Connection Attributes

### ISSUE THREAD

**Issue by dveeden** [vitessio/vitess#4369]
#### Feature Description

The MySQL protocol allows the client to send a set of key/value pairs when connecting.
These can be used for troubleshooting (client pid, client version, client program name, client user name, etc)

#### Use Case(s)

Useful for debugging and troubleshooting

**Comment by sjmudd** [comment]
* I'd expect a _summary_ of client connection attribute information to be available via `vtgate`
* I'd expect that `vttablet` should also try to provide some connection attributes to the mysqld it talks to. Meta data about the cell, keyspace, shard, vitess version.

**Comment by sougou** [comment]
Fixed in #4370
