### ISSUE TITLE
vitess local install: bootstrap.sh fails with ERROR: Selenium build failed

### ISSUE THREAD

**Issue by makandas** [vitessio/vitess#4373]
#### Overview of the Issue

ERROR: Selenium build failed

I am installing vitess locally in ubuntu 18.04 by following the instructions from https://vitess.io/getting-started/local-instance/

#### Reproduction Steps

Steps to reproduce this issue, example:

1. When I run ./bootstrap.sh, the script fails with error. 
```
Installed /home/malar/go/dist/py-mock-1.0.1/lib/python2.7/site-packages/mock-1.0.1-py2.7.egg
Processing dependencies for mock==1.0.1
Finished processing dependencies for mock==1.0.1
installing Selenium latest
Failed to import the site module
Traceback (most recent call last):
  File "/home/malar/go/dist/py-mock-1.0.1/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/home/malar/go/dist/py-mock-1.0.1/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python 3
  File "/usr/lib/python3.6/imp.py", line 27, in <module>
    import tokenize
  File "/usr/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
ERROR: Selenium build failed
```

2. python version is 2.7

#### Operating system and Environment details
Ubuntu 18.04

**Comment by wujysh** [comment]
Hit the same issue on Ubuntu 18.04.

**Comment by wujysh** [comment]
Output of `cat ~/.profile`
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

export GOPATH=$HOME/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
```

Output of `go version`
```
go version go1.11.4 linux/amd64
```

**Comment by raimondasv** [comment]
`BUILD_TESTS=0 ./boostrap.sh` will allow you to continue without bootstrapping test environment

**Comment by PrismaPhonic** [comment]
I'm encountering this same bug in Ubuntu 19.04.  @raimondasv that command helps get me past it for now.

**Comment by saifalharthi** [comment]
I did `unset PYTHONPATH` and it worked well for me.

**Comment by PrismaPhonic** [comment]
I just tried that and no dice.  I'll try it again with that command but building Vitess (with deps) as the very first thing I do after a fresh Ubuntu install (playing around in a VM right now).

**Comment by sougou** [comment]
You need to build vitess this way only if you plan to contribute. Otherwise, you can just download binaries from PlanetScale:

**Comment by sougou** [comment]
Sorry, premature submit. The instructions are:
```
git clone https://github.com/planetscale/vitess-releases.git
cd vitess-releases/bin
./install_latest.sh
```

**Comment by PrismaPhonic** [comment]
Thanks @sougou, that worked out great!

**Comment by morgo** [comment]
This relates to the tests in Python. The build guides now no longer recommend running Python tests, and will be enhanced further in https://github.com/vitessio/website/pull/372 .

Because we are also converting these tests to golang, it should be permanently fixed in the next few months. I am going to close this issue as 'Won't fix', but please feel free to re-open if you have further questions.
