### ISSUE TITLE
support drop vindex DDL statements

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4374]
## Description
Support `drop vindex` as a DDL statement.

## Details
The changes described in #3459 added DDL support for creating vindexes, associating vindexes with table columns and removing associations with table columns.

However this did not include support for actually removing the keyspace-level vindex definitions. This presents a minor inconvenience as the name of the vindex must be unique, so a typo in creating a lookup vindex means that the desired name might not be reusable.

The specific proposal is to implement a `DROP VINDEX <vindex>` DDL statement. This would verify that the vindex is not currently associated with any table columns in the keyspace and then if not, would remove it from the global list.

**Comment by sougou** [comment]
We also need to remove a table from the vschema on `drop table`.

**Comment by demmer** [comment]
Ah true -- but that's an orthogonal issue, no? I wanted to keep this one specific to the incompleteness of the existing support.

Oh one other thing that occurred to me -- we need a DDL syntax for adding/removing tables from an unsharded keyspace vschema. That's a bit tricky because there's no "vindex" per se.

**Comment by GuptaManan100** [comment]
This has been implemented. Please open a new issue if further changes are to be requested.
