### ISSUE TITLE
Queries wrapped in double parentheses will scatter

### ISSUE THREAD

**Issue by eeSeeGee** [vitessio/vitess#4379]
#### Overview of the Issue

When querying if the primary vindex clause is wrapped in an extra set of parentheses it will scatter.

#### Reproduction Steps

If the `customers` table is sharded on `customer_id` this query performs a scatter query:
```select * from customers where ((customer_id = 1234))```

**Comment by harshit-gangal** [comment]
This seems to work on 8.0. Please reopen if this still exists.
