### ISSUE TITLE
http: proxy error: context canceled

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4380]
hi, i try to access vtctld web UI  but get error

    # kubectl proxy --accept-hosts='.*' --address=0.0.0.0 --port=8001
    Starting to serve on [::]:8001
    I1123 14:15:47.578771   10862 logs.go:41] http: proxy error: context canceled
    I1123 14:15:47.580104   10862 logs.go:41] http: proxy error: context canceled
    I1123 14:15:47.580199   10862 logs.go:41] http: proxy error: context canceled
    I1123 14:15:47.580270   10862 logs.go:41] http: proxy error: context canceled
    I1123 14:15:47.580319   10862 logs.go:41] http: proxy error: context canceled

and the url can not be opened,why?

http://10.100.1.20:8001/api/v1/namespaces/default/services/vtctld:web/proxy

**Comment by sougou** [comment]
Those proxy errors indicate that the problem is with how the proxy is configured. It's not related to vitess. I verified that the URL works for me; I just ran `kubectl proxy` with no parameters.

I also fixed our outdated URL in the helm charts #4383.

**Comment by justlooks** [comment]
> Those proxy errors indicate that the problem is with how the proxy is configured. It's not related to vitess. I verified that the URL works for me; I just ran `kubectl proxy` with no parameters.
> 
> I also fixed our outdated URL in the helm charts #4383.

if no --address parameter ,it just open proxy on 127.0.0.1 ,i can not connect from my browser
