### ISSUE TITLE
Simplify orchestrator discovery with new template variable setting.

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4381]
Please search the existing issues for relevant feature requests, and use the [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Vitess has orchestrator support including some features to do discovery (from vttablet) but really this should not be needed that much. Orchestrator if suitably configured should be able to find any new slaves that appear.

Two settings I use for this are:

```
report_host = <hostname>
report_port = <mysql_port>
```

These settings are not in the default mysql config in `vitess/config/mycnf/default.cnf` partly because the hostname is not "known" or part of the current templating system.

It's trivial to add `report_port = {{.MysqlPort}}` as this value is already handled.

It might be convenient to add  an extra default template value such as `{{.Hostname}}` so the `report_port = {{.Hostname}}` could then used to report the slave's hostname in a way that orchestrator could use.

Also the current default suggestion discovery time suggested for `vttablet` configuration is probably too aggressive if mysqld is configured properly.

**Comment by mattlord** [comment]
Hi @sjmudd ! I'm going to close this for now as I'm not sure we're going to incorporate any further integration points between Vitess and Orchestrator. If we do, I think it will come via vtorc, which may end up being significantly different than Orchestrator. 

If you think that this is still relevant and something we should do in Vitess 12.0+ please let me know and we can re-open it. Thanks!
