### ISSUE TITLE
vtgate: executor timing metrics should include keyspace tag for v3 routed queries

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4382]
## Description
The vtgate exported metric QpsByKeyspace should account for v3 routed queries when determining the keyspace tag.

## Details
Currently, vtgate includes a keyspace tag only when the target string explicitly contains a keyspace, i.e. only for v2 routed queries:
https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/executor.go#L125-L128

Instead, the planbuilder Primitive should expose an interface so that the executor can extract the keyspace that the query routes to. Then the above timing code should be refactored to defer calculating the stats key until after the v3 routing is done, so that the query metrics end up properly tagged by keyspace.

For joins or other cross-keyspace queries this should be either "Join" or the empty string like it is now.

**Comment by rafael** [comment]
I think this was addressed here: https://github.com/vitessio/vitess/pull/4882

@demmer  could we close this one?

**Comment by GuptaManan100** [comment]
Closing this issue. Reopen in case of any new updates.
