### ISSUE TITLE
set session sql_mode='NO_ENGINE_SUBSTITUTION'

### ISSUE THREAD

**Issue by hellracer** [vitessio/vitess#4387]
#### Overview of the Issue

Laravel  connect to vtgate and does set this mode, but vtgate don't accept this as a valid construct
set session sql_mode='NO_ENGINE_SUBSTITUTION'

#### Reproduction Steps

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 16
Server version: 5.5.10-Vitess Percona Server (GPL), Release '25', Revision '7e2732e'

Copyright (c) 2009-2018 Percona LLC and/or its affiliates
Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> set session sql_mode='NO_ENGINE_SUBSTITUTION';
ERROR 1105 (HY000): vtgate: http://etcd:15001/: unsupported construct: set session sql_mode='NO_ENGINE_SUBSTITUTION'

1. Run `set session sql_mode='NO_ENGINE_SUBSTITUTION'`
1. View error `ERROR 1105 (HY000): vtgate: http://etcd:15001/: unsupported construct: set session sql_mode='NO_ENGINE_SUBSTITUTION'`

#### Binary version
Example:

```sh
giaquinti@workspace:~$ vtgate --version
Version: e232f21 (Git branch 'master') built on Thu Nov 22 07:32:04 PST 2018 by useradmin@etcd using go1.11.2 linux/amd64using go1.11.2 linux/amd6giaquinti@workspace using go1.10 linux/amd64
```

#### Operating system and Environment details

Ubuntu 16.04

**Comment by sougou** [comment]
FTR: This line was changed to make it work: https://github.com/laravel/framework/blob/5.7/src/Illuminate/Database/Connectors/MySqlConnector.php#L152
