### ISSUE TITLE
vitess has schedule problem in kubernetes

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4394]
i have opened two issue and closed them ,because i find this problem is same 
https://github.com/vitessio/vitess/issues/4393
https://github.com/vitessio/vitess/issues/4390

the vitess seems have problem in schedule the vttablet pod on node, i build 2-worker-node kubernetes cluster(node A ,node B) ,  and start vttablets on cluster ,only two vttablets can running normally, the other three is stay in pending ,when master node can schedule pod ,the three pending vttablet all start in master node (first error ,then running normally) ,and i create table ,two vttablet failed to execute, when i add two new node(node C,node D) to my kubernetes cluster ,tear down vitess  and restart vttablet i find the three vttablet still remain in pending  ,also if i kick off node A or node B ,i get vttablet lost,it will not restart on new node. i tear down vitess ,and also tear down k8s cluster ,rebuild it,this time i use node C and node D to build 2-worker-node k8s cluster.guess what,all vttablet remain in pending status.

**Comment by derekperkins** [comment]
@justlooks How are you installing Vitess? Are you using the helm chart? Here is a better getting started document that will be published soon on the main Vitess website.
https://docs.google.com/document/d/1saVUq6rFf5quTXgbOGC26GvJPu--W7bB8TOQPHEbbEw/edit

**Comment by justlooks** [comment]
> @justlooks How are you installing Vitess? Are you using the helm chart? Here is a better getting started document that will be published soon on the main Vitess website.
> https://docs.google.com/document/d/1saVUq6rFf5quTXgbOGC26GvJPu--W7bB8TOQPHEbbEw/edit

i try deploy vitess using helm ,but get error
```
# helm install ../../helm/vitess -f 101_initial_cluster.yaml
Error: validation failed: [unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2", unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"]

# docker images |grep etc
10.100.1.22/comm_images/etcd                                     v3.3.10             5602be0bc1ec        8 weeks ago         457.4 MB
k8s.gcr.io/etcd-amd64                                            3.2.18              90940a8f57d2        12 weeks ago        218.9 MB
quay.io/coreos/etcd                                              v3.1.10             47bb9dd99916        17 months ago       34.56 MB
quay.io/coreos/etcd                                              v3.1.8              dcf15f5d07cd        19 months ago       33.66 MB
```

**Comment by Murali-P** [comment]
Is this problem resolved ? (using operator)

example-etcd-faf13de3-1                                          0/1     Pending     0          51s
example-etcd-faf13de3-2                                          0/1     Pending     0          51s
example-etcd-faf13de3-3                                          0/1     Pending     0          51s
example-vttablet-zone1-2469782763-bfadd780                       0/3     Pending     0          51s
example-vttablet-zone1-2548885007-46a852d0                       0/3     Pending     0          51s
example-zone1-vtctld-1d4dcad0-7b659fb4c5-sc2xv                   0/1     Error       2          51s

Even i am facing the issue


ERROR: logging before flag.Parse: E0716 09:40:29.321689       1 syslogger.go:149] can't connect to syslog
I0716 09:40:29.343138       1 servenv.go:96] Version: 12.0.0-SNAPSHOT (Git revision 0dec50e08d branch 'main') built on Thu Jul 15 22:45:35 UTC 2021 by vitess@buildkitsandbox using go1.16.5 linux/amd64
W0716 09:40:30.409549       1 component.go:41] [core] grpc: addrConn.createTransport failed to connect to {example-etcd-faf13de3-client.cos.svc:2379 example-etcd-faf13de3-client.cos.svc <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.4.23.154:2379: connect: connection refused". Reconnecting...
W0716 09:40:32.457332       1 component.go:41] [core] grpc: addrConn.createTransport failed to connect to {example-etcd-faf13de3-client.cos.svc:2379 example-etcd-faf13de3-client.cos.svc <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.4.23.154:2379: connect: connection refused". Reconnecting...
F0716 09:40:34.344347       1 server.go:231] Failed to open topo server (etcd2,example-etcd-faf13de3-client.cos.svc:2379,/vitess/example/global): context deadline exceeded
