### ISSUE TITLE
vagrant / bootstrap.sh govendor sync hangs

### ISSUE THREAD

**Issue by falun** [vitessio/vitess#4396]
#### Overview of the Issue

```
~/src/vitess> vagrant up
~/src/vitess> vagrant ssh
...
Updating govendor dependencies...
```

At this point it seems to hang indefinitely on the following line: https://github.com/vitessio/vitess/blob/master/bootstrap.sh#L294

#### Reproduction Steps

1. Clean checkout of vitess project
2. `vagrant up`
3. `vagrant ssh`

#### Operating system and Environment details

osx, virtual box 5.1.26, vagrant 2.2.1

#### Comments / Workarounds
This seems to be connected to NFS file syncing as enabled in https://github.com/vitessio/vitess/blob/master/Vagrantfile#L45. 

Two work arounds are available:

1. do not use NFS as the syncing mechanism; this will generally work but file syncing will take a bit more time
2. run `govendor sync` on the host machine before `vagrant ssh`; this will cause govendor to identify that no new packages need to be added and whatever is causing the problem gets skipped

**Comment by rafael** [comment]
I would lean towards just not using NFS. In the past that has caused other kind of issues.

**Comment by morgo** [comment]
We have since removed govendor from the bootstrap, and use go modules instead.

I am going to close this issue, but feel free to reopen if you have further questions.
