### ISSUE TITLE
proto: no coders for int

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4398]
when i use etcd-up.sh script to start etcd ,it get error ,it seems vtctl add cellinfo cause problem

```
# "${VTROOT}"/bin/vtctl $TOPOLOGY_FLAGS AddCellInfo -root /vitess/test -server_address "${ETCD_SERVER}" test
proto: no coders for int
proto: no encoder for ValueSize int [GetProperties]
```

**Comment by mattlord** [comment]
I'm going to close this for now as I'm not able to repeat this today. If you feel that it's still relevant and you can repeat it with Vitess 8+, can you please provide the steps you're taking? Thanks!
