### ISSUE TITLE
MySQL Parser Spacing Error

### ISSUE THREAD

**Issue by msolters** [vitessio/vitess#4407]
#### Overview of the Issue

When the Vitess MySQL parser constructs a query it does not place a space between the table name and the parentheses.  This causes some bugs in MariaDB tablets.  For example, in MariaDB 10.2.2+ `lead` is a built-in function.  So, if you have a table named `lead`, an operation like `insert into lead()` will throw a syntax error, while `insert into lead ()` works just fine.  While this is one specific example, simply always adding the space after table name would ensure this problem or any variant does not occur (at least due to syntax error).

#### Reproduction Steps
Typing both of these would cause a syntax error, because the MySQL parser removes the space when reconstructing the query:

```
insert into lead(blah)...
insert into lead (blah)...
```

#### Operating system and Environment details
Latest Vitess running in kubernetes with MySQL 5.7 and MariaDB 10.3 vttablets.

#### Log Fragments
As can be seen here, including a space in the query does not help as the parser removes the space, triggering a syntax error:

```
mysql> INSERT INTO lead (id) VALUES (1);
ERROR 1064 (42000): vtgate: http://vtgate-app-6c4565fbc8-rdxlj:15001/: execInsertSharded: target: web_app.0.master, used tablet: app-1578204300 (app-web-app-x0x-master-0.vttablet), vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'lead(id) values (1) /* vtgate:: keyspace_id:166b40b44aba4bd6 */' at line 1 (errno 1064) (sqlstate 42000) (CallerID: moroder): Sql:
```

**Comment by harshit-gangal** [comment]
lead is added as reserved keyword in the grammar via https://github.com/vitessio/vitess/pull/5336 so this should not be an issue.
Closing this, reopen if this does not work.
