### ISSUE TITLE
Ship binary administration interface for vitess

### ISSUE THREAD

**Issue by gigatexal** [vitessio/vitess#4418]
I am currently using the vitess/base docker image and then doing a go install in the necessary directories to get working 'binaries' because Go and this just works. I was thinking it would be nice if there was a kubeadm / kubectl like interface to vitess. 

#### Feature Description

A Kubeadm / Kubectl style interface to vitess and its various aspects. 

#### Use Case(s)

Getting started and running would be a lot easier and I think scripting would be too.

**Comment by gigatexal** [comment]
this can be closed, the Vitess-cli being used from the vitess/base container on docker hub is fine.

**Comment by derekperkins** [comment]
@gigatexal if you want to deal with a much smaller container, `vitess/k8s` https://hub.docker.com/r/vitess/k8s/~/dockerfile/ just copies the binaries and some config out of base.
