### ISSUE TITLE
Auto Docker Image Tagging

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4431]
Since we rarely tag releases here, I propose that we start tagging nightly releases in Docker. It doesn't need to be overly tested or scientific. I think we should just set up a nightly cron that tags it with the date `2018-12-06`. The way it is now, there's no real way to rollback changes or test upgrades. I got burned by a change to the `master_mysql56.cnf` file, and the best solution was to build my own image.

**Comment by derekperkins** [comment]
Unless someone has another suggestion, I'll look at setting up Travis to run a build/tag job.
https://docs.travis-ci.com/user/cron-jobs/

**Comment by frouioui** [comment]
Hello @derekperkins is still still relevant today?

**Comment by derekperkins** [comment]
Nope, this is back when it was standard to run from tip
