### ISSUE TITLE
vtclient Backup respect localtime setting

### ISSUE THREAD

**Issue by hellracer** [vitessio/vitess#4442]
#### Feature Description

When performing a backup operation it would be a lot better to get the current localtime of the machine instead of harcoded UTC timezone.

#### Use Case(s)

If this has been implemented the  operator will no longer need to convert the timestamp directory to his/her timezone/localtime setting

**Comment by mattlord** [comment]
I'm closing this for now as I'm not sure it's still relevant with the most recent operator and I would hope we use UTC everywhere today to avoid these translation issues. If you feel that this is still relevant and something you'd like to see can you please provide more details? Thanks!
