### ISSUE TITLE
the new doc has some url broken

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4445]
here is the broken url which i find

in document  https://vitess.io/docs/overview/scalingwithvitess/ 

the following url link can not be found 
Horizontal sharding (Codelab)
Sharding in Kubernetes (Codelab)

they all point to  
https://vitess.io/docs/overview/scalingwithvitess/link  which can not be found

**Comment by sougou** [comment]
These should be all fixed now.

**Comment by sougou** [comment]
New docs are hosted from vitessio/website.
