### ISSUE TITLE
Allow Schema changes via vtgate to support migration tools like Alembic

### ISSUE THREAD

**Issue by gigatexal** [vitessio/vitess#4461]
#### Feature Description

Migrations on vanilla databases are hard given the potential for data destruction. Tools like Alembic exist in the Python world. Another tool worth looking into is Github's gh-ost. (https://github.com/github/gh-ost). But even it too is not vitess-aware and a killer use case would be a tool that would handle schema changes but also be aware of a sharded or unsharded schema.

#### Use Case(s)

A commit adds a new feature that adds a new column, changes a column data type, adds a foreign key, and does 10 other things to the underlying database schema to support the feature. 

Currently one has to find a way to use the ApplySchema command as the vtgate doesn't allow schema changes.

**Comment by harshit-gangal** [comment]
VTGate now supports DDL and also we have release online schema change using gh-ost or pt-online-schema change. Refer the Vitess 8.0 release notes.
