### ISSUE TITLE
Fix vttablet state transitions

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#4465]
VTTablet state transition design needs to be improved to address the new upcoming needs. The biggest changes are as follows:
* Allow transactions for replica and rdonly tablet types. Although these are not usable from vtgate right now, other tools like SplitClone could use them for obtaining snapshots. Eventually, we'll also allow vtgates to use them.
* 2PC handling: when a tablet gets externally reparented, then the old master may not get the memo and may still hold on to its 2PC transactions. However, it can detect this by the fact that it's become read-only, and therefore shutdown the tx pool.

The current design uses a single state variable to track vttablet transitions. The states are:
```
	// StateNotConnected is the state where tabletserver is not
	// connected to an underlying mysql instance.
	StateNotConnected = iota
	// StateNotServing is the state where tabletserver is connected
	// to an underlying mysql instance, but is not serving queries.
	StateNotServing
	// StateServing is where queries are allowed.
	StateServing
	// StateTransitioning is a transient state indicating that
	// the tabletserver is tranisitioning to a new state.
	// In order to achieve clean transitions, no requests are
	// allowed during this state.
	StateTransitioning
	// StateShuttingDown indicates that the tabletserver
	// is shutting down. In this state, we wait for outstanding
	// requests and transactions to conclude.
	StateShuttingDown
```

The vttablet itself can go from any tablet type to another: Master/Replica/Rdonly. Orthogonally, it could also be asked to serve or not serve. Some combinations are not expected like Master and non-serving. But we don't have to care.

# TxPool transitions

The new functionality complicates the mechanics of the txpool. Previously, you could just shut it down if the new state was not the master. However, now that we want to allow transactions for other tablet types, we have to keep it open, but also honor transition rules.

## Master -> Non-master
Existing transactions must first be resolved. After they're all resolved, we can perform the transition. In order to allow this transition to happen, we have to prevent new `Begin` from getting executed, and wait for `te` to Close. Once it's closed, we can reopen it.

## Non-master -> Master
You don't need to resolve existing transactions. However, the txpool may need to resurrect transactions if 2PC is enabled. So, it's better to close the pool and reopen it. Should we wait for existing transactions to be resolved? Maybe not very important (`te.Close` can be instant).

## Non-master -> Non-master
No need to transition. Existing pool can just continue as is.

## Master -> Not-serving
This state is similar to Master->Non-master: we have to wait for txpool to close. But we don't have to reopen it.

## Non-master -> Not-serving
We can instantly close the pool.

## Not-serving -> Serving
All pools are opened. This means `Open` calls need to be idempotent.

## Externally set read-only
It's possible for MySQL to be set to Read-Only externally. If the current tablet type is the master, then it's essentially lost its mastership. The tablet should either transition to a replica or remain a master with no transaction support. The reason why this needs to happen is because it will otherwise hold on to unresolved prepared transactions. And if it's eventually asked to commit them, they will fail, which will result in 2PC data corruption. If it closes the tx pool upfront, the next time it's asked to become master (or open the pool), it can resurrect the prepared transactions from the redo log, and still retain the ability to commit them.

## Closing of txpool
The tx pool takes an `immediate` flag, which decides if it should immediately shut down or wait for transactions to complete. If the flag is true, the shutdown is trivial. However, if it's false, other precautions need to be taken:
* Ensure that `Begin` calls are not allowed.
* If a `Begin` call has already started executing but has not acquired a txpool connection, we should for it to do so.
* Wait for all existing transactions to close, or be killed on their timeout.

The above function needs to be encapsulated and idempotent so we can freely call it as needed.

There is also a `txThrottler` in tabletserver. I believe it was mistakenly introduced for some form of protection. We should consider removing it after checking with the YouTube folks. Nevertheless, it's harmless right now. So, removing it is not a priority.

Other pools are fine as they are, and can be left alone.

# Design
I think we need a separate variable to track the txpool state transitions, and use that state to handle `Begin` calls also. This is only an initial thought. We can explore other approaches.

**Comment by systay** [comment]
I'm thinking about these two transitions:
1. Master -> Not-serving
2. Non-Master -> Not-serving

In #1, we say that we have to wait for the open transactions to finish before closing shop. For #2, you wrote that we can immediately close the tx-pool. Since we are allowing read-only transactions now, does this mean that we can kill read-only tx's, but not regular RW transactions?

And what does that mean for any read-only transactions that we might be hosting while in Master-mode. are those transactions OK to kill, or should they also get a chance to wrap up?

**Comment by sougou** [comment]
Essentially, yes to questions above.

The idea is that master transactions are generally more precious because they're likely to be writing data. We currently don't differentiate between RO and RW transactions.

As for replica/rdonly, the only use case right now is the resharding one, and vtworker knows how to retry. Even otherwise, they would be long-running transactions. So, a shutdown cannot wait for that long. We may have to revisit this when we start supporting other use cases, but this should be good enough for now.

**Comment by sougou** [comment]
This was done in #4533
