### ISSUE TITLE
no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"

### ISSUE THREAD

**Issue by justlooks** [vitessio/vitess#4479]
when i install vitess using helm , get error 

```
# helm install ../../helm/vitess -f 101_initial_cluster.yaml
Error: validation failed: [unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2", unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"]
```

**Comment by zloma** [comment]
Did you first install EtcdOperator prior to deploying vitess ?

**Comment by xambas84** [comment]
i'm having the same issue. in my case, EtcdOperator installed prior to vitess

**Comment by deepthi** [comment]
If you *just* installed etcd-operator, it takes a few seconds before it is fully available. Rerunning helm install should work.

**Comment by willzhang** [comment]
the same problems!
```
[root@k8s-master helm]# helm install ../../helm/vitess -f 101_initial_cluster.yaml
Error: validation failed: [unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2", unable to recognize "": no matches for kind "EtcdCluster" in version "etcd.database.coreos.com/v1beta2"]
```
etcd operator
```
[root@k8s-master helm]# kubectl get pod
NAME                                      READY   STATUS             RESTARTS   AGE
etcd-operator-865cd466d4-4h6dt            1/1     Running            0          10m
```

**Comment by derekperkins** [comment]
If you're using helm, you have to tell it to create the CRD resoures.
https://github.com/helm/charts/blob/master/stable/etcd-operator/values.yaml#L32-L38

**Comment by phanimullapudi** [comment]
I have installed the etcd operator and again made sure its running  - but still same error as @willzhang.

If this project supported in K8s officially ?

**Comment by derekperkins** [comment]
You probably used helm 3 that doesn't properly install the etcd CRDs.
