### ISSUE TITLE
Cancel Reparent if PlannedReparentShard fails

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4481]
Per a conversation on Slack with @sougou, the current behavior when `PlannedReparentShard` fails is dangerous, because it leaves things in a broken state.
https://vitess.slack.com/archives/C0PQY0PTK/p1545347205331200

- [ ] Implement a cancel / rollback of the reparent if it fails
- [ ] Have all actions use a short timeout by default. Should that decrease the default `action_timeout` or have all actions use `wait_slave_timeout` instead?

**Comment by sougou** [comment]
I think changing `action_timeout` will break other possibly long-running commands. Let's have this command use `wait_slave_timeout`. This will also allow the `cancel` function to use the actionTimeout context, because the waitSlave context would be expired and unusable.

**Comment by derekperkins** [comment]
I don't have time to tackle this right now. Per our conversation in Slack, @sougou mentioned this as something for @deepthi to tackle when she gets back from vacation.

**Comment by deepthi** [comment]
@derekperkins can you take a look at the PR and give me some feedback?
