### ISSUE TITLE
Proposal: Support Kubernetes API as a new lockserver implementation

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4488]
As more people continue to adopt Vitess inside of Kubernetes, we should investigate using the k8s api as a lockserver implementation, rather than forcing new users to also adopt and run etcd, zookeeper or consul. Not only will this make adoption easier, but where a large majority of users will be using hosted k8s like GKE, HA and disaster recovery are then provided in tandem with the full cluster.

A downside to this proposal is potentially unpredictable performance if the k8s api is overloaded. That will presumably be less of a concern once #3997 is implemented to reduce the load on the lockserver. We would want to make sure that there was a good path to migrate from k8s to dedicated etcd clusters.

Another concern is binary bloat and compilation trouble. Importing the official client https://github.com/kubernetes/client-go adds 25-50 MB to the binary size, and can cause problems with dependencies for compilation. To mitigate that, we could use an alternative client like https://github.com/ericchiang/k8s.

A less invasive idea might be to have the operator act as a proxy that translates existing etcd calls to their corresponding k8s api versions. This keeps any new logic out of the core, but then requires the operator to have a much different operational profile. I'm also not sure how this might impact performance or if it is even feasible.

The original idea is from @carsonoid, who just started working on https://github.com/vitessio/vitess-operator. He has been working on k8s implementations for the past couple years for Domo.

cc @sougou @dkhenry

**Comment by acharis** [comment]
I like this proposal from the standpoint of making vitess easier for new users to adopt.
But from the standpoint of running infrastructure, I also like the idea of keeping the two lockservers separate. So please keep this as an option, just like all the other lockserver plugins we have. And do also keep in mind that not all vitess users will be running the vitessio/vitess-operator.

**Comment by derekperkins** [comment]
> But from the standpoint of running infrastructure, I also like the idea of keeping the two lockservers separate.

The two being the k8s api and etcd? Or are you referring to global and cell lockservers? The proposal is to not give any special treatment to the k8s lockserver implementation, just a new fourth option.

> And do also keep in mind that not all vitess users will be running the vitessio/vitess-operator.

Definitely. The operator is mostly orthogonal to this issue. I only mentioned it as a possible workaround if was significant opposition to adding k8s as a core lockserver implementation.

**Comment by dkhenry** [comment]
@derekperkins can you stream updates from the k8s lockserver ? Without that functionality I don't know how we would implement the `Watch` interface

**Comment by sougou** [comment]
We'll need to think about how this would be configured in a multi-cell situation.

**Comment by derekperkins** [comment]
> We'll need to think about how this would be configured in a multi-cell situation.

I'm not sure how a multi-cluster setup would operate. Presumably you would have to point from inside one cluster to another cluster's master servers. I'm not sure if that's possible, but if not, I don't think that would be a big deal. If you're trying to run Vitess across multiple k8s clusters, you probably have the operational expertise to run your own lockservers.

Any thoughts @carsonoid?

**Comment by carsonoid** [comment]
It's entirely possible to support cross-cluster api access for multi-cell/multi-cluster use cases. However the main use case would be for smaller, single-cluster installations.

**Comment by carsonoid** [comment]
I am not a Vitess dev but I have done plenty of work with client-go. FWIW I have started a branch to work on this here: https://github.com/carsonoid/vitess/tree/kubernetestopo

**Comment by derekperkins** [comment]
> I ran some tests and the difference is pretty big. With client-go the vtgate binary is 50m without its 26m. All in there an additional 350m across all vitess binaries just from this one change. I am going to look into a more lightweight solution.

FYI, this is what happened recently when looking to add `client-go` https://github.com/vitessio/vitess/pull/4267#issuecomment-429416919

**Comment by derekperkins** [comment]
I think using a go build tag is a good compromise. I'd vote to have it built in by default so people aren't caught by surprise if it doesn't work. Most people running in production are probably building their own images, so they could just compile without it.

**Comment by derekperkins** [comment]
Or alternatively have it excluded by default, but just have the k8s images have it compiled in. That's probably a better solution.

**Comment by sougou** [comment]
I believe @carsonoid finished this work :)
