### ISSUE TITLE
Make it possible to determine keyspace_id with SQL

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4501]
It's a fairly common question where people ask how to determine a keyspace_id. It is especially useful when trying to choose shard boundaries to deal with hot tablets. @sougou suggested on Slack to try this, but it returned `unsupported: where clause for vindex function must be of the form id = <val> (rhs is not a value)`.

```
select myfield, keyspace_id from mytable join hash on mytable.id = hash.id
```

this is @sougou's suggested course of action.
> we can make it work with a few adjustments.
but it's not a one-line fix like i was hoping
i can fix it next time i go in there
implementation is to make it treat the rhs as a value, and implement the wireup function that substitutes it to a bind var.
this is how the join logic works across two routes, but i didn't bother doing it for vindex funcs.
it will be more like 10-20 lines of code

**Comment by harshit-gangal** [comment]
Support added via #7044

**Comment by derekperkins** [comment]
Thanks for pushing that through!
