### ISSUE TITLE
Built binaries available for download in release page as artifacts for each new version

### ISSUE THREAD

**Issue by ernestas-poskus** [vitessio/vitess#4505]
Hello. Please consider adding built docker image binaries to releases page as artifacts for download https://github.com/vitessio/vitess/releases. For example like in Prometheus releases page https://github.com/prometheus/prometheus/releases.

More info here https://blog.github.com/2013-07-02-release-your-software/

![](https://f.cloud.github.com/assets/21/737975/b987ea62-e33b-11e2-932b-356d75c86385.jpg)

**Comment by derekperkins** [comment]
You can find those here: https://hub.docker.com/u/vitess

Adding links to the release notes is a good idea.

**Comment by ernestas-poskus** [comment]
> You can find those here: https://hub.docker.com/u/vitess

Thank you I am aware that binaries are built with docker. 
It would be more convenient to retrieve binaries directly from Github like in provided example. Reason for request is Chef Vitess cookbook https://github.com/vinted/chef-vitess.

**Comment by morgo** [comment]
We are currently doing this. I am planning to automate in https://github.com/vitessio/vitess/issues/5463

I am going to close this issue now, but please feel free to reopen if you have further questions.
