### ISSUE TITLE
Improve vtgate reporting of state

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4511]
#### Feature Description

I see this message:
```I0109 18:04:47.820765    2655 gateway.go:101] Gateway waiting for serving tablets...
...
I0109 18:04:47.923096    2655 asm_amd64.s:1333] HealthCheckUpdate(Serving State): cell-0000007014, tablet: cell-7014 (host1.example.com) serving => true for keyspace/80- (REPLICA) reason: healthCheck update
...
W0109 18:05:17.820966    2655 gateway.go:114] Timeout waiting for all keyspaces / shards to have healthy tablets, may be in degraded mode
```

which shows the 8 tablets I expect to see being up and healthy. but the final error message seems to indicate something is not healthy.

The logging does not clearly indicate *what*.

* It would be good to include a count of unhealthy tablets or a list of unhealthy keyspaces to clarify so I can figure out what’s wrong.
* I think it would be convenient to be explicit about the timeout value used

So a suggested possible better message might be:

`W0109 18:05:17.820966    2655 gateway.go:114] Timeout after XXX_PERIOD waiting for all keyspaces / shards to have healthy tablets. Unhealthy tablets: 999, unhealthy keyspaces: keyspace1, keyspace2, ..., keyspacen.`

That would really aid in knowing what to look at and if the tablet or keyspace is “important”.

**Comment by maZahaca** [comment]
Hello,

I having the same issue on the latest release (9.0.0).
Apart of this message, I have tables connected to external database. And according to logs vtgate is being restarted multiple times. How can I track this issue to its roots?

**Comment by GuptaManan100** [comment]
The `/debug/status` page of vtgates now shows its perceived state of all the vttablets and their health. If you require some more information to be seen in that page, please create a new issue.
