### ISSUE TITLE
resharding, 2->4, MigrateServedTypeMaster error, vtctld panic

### ISSUE THREAD

**Issue by yangxuanjia** [vitessio/vitess#4530]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

resharding, 2->4, MigrateServedTypeMaster error, vtctld panic

#### Reproduction Steps
1. resharding 2 shards to 4 shards, use 4 vtworker.
2. when step MigrateServedTypeMaster, vtctld panic

#### Log Fragments

E0116 17:27:18.911639   21288 keyspace.go:616] failed to re-enable source masters: [migrate has gone past the point of no return, cannot re-enable serving for test_keyspace/80-]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9fedda]

goroutine 102 [running]:
vitess.io/vitess/go/vt/topo.(*ShardInfo).Keyspace(...)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/topo/shard.go:145
vitess.io/vitess/go/vt/wrangler.(*Wrangler).updateFrozenFlag(0xc0000bf110, 0x11f3900, 0xc0002e78f0, 0xc0001a6140, 0x1, 0x1, 0xc00049a500, 0x2, 0x2)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/wrangler/keyspace.go:728 +0x4a
vitess.io/vitess/go/vt/wrangler.(*Wrangler).masterMigrateServedType(0xc0000bf110, 0x11f3900, 0xc0002e78f0, 0xc0000b8680, 0xd, 0xc0001a6140, 0x1, 0x1, 0xc00049a560, 0x2, ...)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/wrangler/keyspace.go:557 +0x8b4
vitess.io/vitess/go/vt/wrangler.(*Wrangler).MigrateServedTypes(0xc0000bf110, 0x11f3900, 0xc0002e78f0, 0xc0000b8680, 0xd, 0xc0000b86ac, 0x3, 0x0, 0x0, 0x0, ...)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/wrangler/keyspace.go:270 +0x48a
vitess.io/vitess/go/vt/workflow/resharding.(*horizontalReshardingWorkflow).runMigrate(0xc0001ea540, 0x11f3840, 0xc0002545c0, 0xc0004a6780, 0x0, 0xc0003bec68)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/workflow/resharding/tasks.go:123 +0x1e8
vitess.io/vitess/go/vt/workflow/resharding.(*horizontalReshardingWorkflow).runMigrate-fm(0x11f3840, 0xc0002545c0, 0xc0004a6780, 0xc000000001, 0x0)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/workflow/resharding/workflow.go:408 +0x48
vitess.io/vitess/go/vt/workflow.(*ParallelRunner).executeTask(0xc0001b8380, 0xc0004a6780)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/workflow/parallel_runner.go:174 +0x13a
vitess.io/vitess/go/vt/workflow.(*ParallelRunner).Run.func1(0xc0000b90f0, 0xc0001b8380, 0xc000152380, 0xc0004a6780)
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/workflow/parallel_runner.go:150 +0x118
created by vitess.io/vitess/go/vt/workflow.(*ParallelRunner).Run
    /home/qqydqqq/Downloads/code/IdeaProjects/goproject/src/vitess.io/vitess/go/vt/workflow/parallel_runner.go:146 +0x169

**Comment by sougou** [comment]
Is this repeatable? I want to know what was the original error that caused. It got lost because of the panic. Can you put a log line there?

More specifically, the panic seems to come from the fact one of the shards became nil. I'm still trying to figure out how that happened. Because if that's the case, the code will just end up panicking later.

**Comment by yangxuanjia** [comment]
i try to repeat the bug, but it not happen again, it's strangely.  i will close the pr.
