### ISSUE TITLE
Panic in binlog streamer

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4535]
Haven't looked into this yet, but opening an issue to track

E0115 18:54:21.801900   30519 updatestreamctl.go:315] Uncaught panic:
runtime error: index out of range
/usr/local/go/src/runtime/panic.go:513 (0x42e4e8)
/usr/local/go/src/runtime/panic.go:44 (0x42d329)
/vt/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:741 (0xb5dce5)
/vt/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:610 (0xb5bce7)
/vt/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:534 (0xb596bf)
/vt/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:233 (0xb578e0)
/vt/src/vitess.io/vitess/go/vt/binlog/updatestreamctl.go:273 (0xb650ad)
/vt/src/vitess.io/vitess/go/vt/binlog/grpcbinlogstreamer/streamer.go:42 (0xc09327)
/vt/src/vitess.io/vitess/go/vt/proto/binlogservice/binlogservice.pb.go:138 (0xc06aa8)
/vt/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:1077 (0x84ec3c)
/vt/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:1143 (0x8500f9)
/vt/src/vitess.io/vitess/vendor/google.golang.org/grpc/server.go:683 (0x8590be)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x45e730)

**Comment by dweitzman** [comment]
Or since this was the streamer rather than the the player, might be that a DDL was done in mysql that the tablet didn't know about so the local binlogs didn't match the tablet's schema.

**Comment by sougou** [comment]
Yeah. This sounds valid. The new vreplication handles this use case by reloading the schema: https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go#L276. Maybe we should backport this fix.

**Comment by indera-shsp** [comment]
Got the same 
```
time="2021-07-15T18:46:55Z" level=error msg="VTGate read error: Code: UNKNOWN\nrpc error: 
code = Unknown 
desc = target: ...master: vttablet: rpc error: code = Unknown
desc = uncaught panic: runtime error: index out of range [266] with length 96\n.


 Stack-trace:\n/usr/local/go/src/runtime/panic.go:88 (0x435164)\n

/vt/src/vitess.io/vitess/go/mysql/binlog_event_rbr.go:221 

(0xfc6e98)\n/vt/src/vitess.io/vitess/go/mysql/binlog_event_rbr.go:1046 

(0xfcd12b)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:547 (0x126e555)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:307 (0x126c104)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:181 (0x126bac4)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:160 (0x126b7f6)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go:379 (0x126a224)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer/engine.go:225 (0x125cdd0)\n/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1114 (0x135a686)\n/vt/src/vitess.io/vitess/go/vt/vttablet/grpcqueryservice/server.go:349 (0x144b164)\n/vt/src/vitess.io/vitess/go/vt/proto/queryservice/queryservice.pb.go:1064 (0x1440bad)\n/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 (0xa59fb7)\n/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 (0xa5b67b)\n/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 (0xa698a4)\n/usr/local/go/src/runtime/asm_amd64.s:1374 (0x470660)\n\n 

at VGTID: .... , retrying in 5000000000 seconds\n"
```

**Comment by mattlord** [comment]
I'm closing this as stale for now as it seems to be about the legacy sharding code/tooling that has been deprecated for some time now and is scheduled for removal in v15.

Please let me know if I missed or misunderstood something though and we can re-open this. Thanks!
