### ISSUE TITLE
where is ChangeSlaveType(spare) ?????

### ISSUE THREAD

**Issue by yangxuanjia** [vitessio/vitess#4543]
split_diff.go
// change the cleaner actions from ChangeSlaveType(rdonly)
// to StartSlave() + ChangeSlaveType(spare)
wrangler.RecordStartSlaveAction(sdw.cleaner, sourceTablet.Tablet)

cleaner.go
func RecordStartSlaveAction(cleaner *Cleaner, tablet *topodatapb.Tablet) {
	cleaner.Record(StartSlaveActionName, topoproto.TabletAliasString(tablet.Alias), func(ctx context.Context, wr *Wrangler) error {
		return wr.TabletManagerClient().StartSlave(ctx, tablet)
	})
}

**Comment by GuptaManan100** [comment]
Closing this issue since these constructs are no longer part of the codebase.
