### ISSUE TITLE
Stats for vreplication transaction rates and indicating if there's an error

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4544]
Seems like the vreplication lag stat only updates if vreplication is successfully running and there's no stat currently to indicate if it's in "error" state

I may have a diff soon with some minimally helpful stats related to this, but wanted to file an issue because this will also be relevant for the new vstreamer where these kinds of stats could potentially be added from the start.

**Comment by mattlord** [comment]
@dweitzman I'm closing this for now as I'm unaware of anything to fix or address around this in v18+. If I'm missing or misunderstanding something then please let me know and we can re-open this. Thanks!
