### ISSUE TITLE
Vtctl should have an explicit mode that allows you to force Master to Backup

### ISSUE THREAD

**Issue by dkhenry** [vitessio/vitess#4557]
#### Feature Description
If a user ever is in a situation where there are no replica's it is currently impossible to take a backup without manually stopping the vttablet. There is a command called ChangeSlaveType, but it will not allow you to change from a MASTER to a REPLICA.  There should be an explicit flag on ChangeSlaveType that allows a user to change the tablet type without restart vttablet. This will then allow a user to set the tablet to REPLICA take a backup then set it back to MASTER without having to stop the tablet.

Alternatively the Backup command could have a flag ( perhaps `allow_emergency_backup_on_master` ) that will allow it to execute on the master  

#### Use Case(s)
If binlogs have been cycles and not suitable backup exists to recover from

**Comment by deepthi** [comment]
The downside to the first approach is that writes will hang / timeout until we switch the tablet back to master. Depending on data size, this could be hours.

Backing up on master will need us to implement something similar to mysql's enterprise backup or percona xtrabackup.

**Comment by derekperkins** [comment]
I think I prefer making it a flag on `Backup`, similar to `allow_master` on the `DeleteTablet` call. That lets you run the normal backup workflow, with having to manually run `ChangeSlaveType` to and from replica.

**Comment by sougou** [comment]
`allow_master` SGTM
