### ISSUE TITLE
Client for VReplication-based update stream

### ISSUE THREAD

**Issue by pH14** [vitessio/vitess#4579]
#### Feature Description

Since it appears that the Update Stream is being deprecated, we're interested in a client that can pull down changes via VReplication (see @sougou's comment in https://github.com/vitessio/vitess/pull/4540).

Ideally the client allows the choice of a particular keyspace and any or all shards, and can return a stream of row-level changes from a given offset. Adding the new streaming methods to the existing Java / Go / Python clients would be helpful.

#### Use Case(s)

For us specifically, we'd like to republish the update stream into a system like Kafka, so that we can have tons of consumers on our existing infrastructure tail row-level updates. This would then be used for:

* Triggering asynchronous tasks after transaction commits
* Triggering cache invalidations
* Syncing data to other systems
* Keeping streaming queries and datasets up-to-date

@sougou 
cc @mlauter @tirsen & others if you have any other needs here 😁

**Comment by tirsen** [comment]
The tricky thing is to support shard splits. That's hard. Here is an option: The clients open a stream per shard. When shard split/merge occurs and the client reaches the end of the binlog stream before the split there is a message on the stream itself which tells you which new shards this stream has split into and at what GTID to start streaming from on the new shard streams.

**Comment by rohit-nayak-ps** [comment]
This is implemented in the VStream API provided by VTGate and there is already a Debezium adapter.
