### ISSUE TITLE
VReplication TODO

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#4587]
As of #4586, the new VReplication has mostly reached feature parity with the old binlog player. Early tests indicate a 20x improvement in throughput. :tada: 

The only feature I've left out is the throttler, which doesn't seem to be needed by anyone right now. These are my notes about things that should be added that I may not get to immediately. So, someone else can run with them:

## Readability
* In binlogdata.proto, there are two `Filter` fields/types. One of them should be renamed.

## Observability
* `/debug/vreplication_log`: similar to querylog, it should stream what vreplication is playing.
* Counter for how many commits are getting batched.
* Counter for how often we're retrying due to locking related errors.
* `Timings` should be split into two. It currently tracks transactions and queries that are different units.
* There's currently no status (or stats) info for vstreamer (source). We have to add something there.
* `SecondsBehindMaster` has not been reliable. We should work on a more accurate reporting of this.
* `TransactionsBehindMaster` would also be nice, but may be harder.
* `vtbinlog`: this will be similar to the `mysqlbinlog`. However, it will show more meaningful statements using source schema. Essentially, this is a subset of what vplayer does, but for human consumption.

## Big features
* vtgate streaming: essentially requested by #4579.
* SplitClone and SplitDiff: This is the part I'll likely focus on next.
* `VMigrate` to replace older `MigrateServed*` functionality. 
* vreplication continuity: upon resharding, all vreplication streams have to be updated to the new sources and new positions.

_And, of course, documentation._

**Comment by nitins64** [comment]
sougou: do you have documentation in how we can use VReplication? Pointer to testcase would also help.

I want to use VStream to capture the data change and update data in Read optimized store in almost realtime.

Any pointer(s) would be greatly appreciated!

**Comment by sougou** [comment]
If it is to an external system, then the API still needs to be built. Conservative ETA is 3-4 weeks. I'm hoping I can beat it. You can follow my work on this branch: https://github.com/planetscale/vitess/tree/ss-vcopy, which is a few commits ahead of what's being reviewed for merging into master.

**Comment by pH14** [comment]
Any update on the VTGate streaming?

**Comment by sougou** [comment]
Things have fallen behind a bit. I'm planning to provide a grpc based solution to unblock a few that are waiting. ETA is about two weeks.

**Comment by zmagg** [comment]
I've thought of a few more things that would make VReplication more useful! 

### More administrative commands
* `vtctl ListStreams <keyspace/shard>` -- Today VReplicationExec allows you to get streams, their statuses, etc. but it'd be handy to have something that operates on the keyspace/shard/cluster level and not the primary tablet alias level, which changes. 
* `vtctl DeleteWorkflow <workflow_name> (optional)<keyspace/shard>` -- Similarly, you have to iterate over the list of primary tablets to delete workflows

### More Metrics
* equivalents to `QueryCounts`, `QueryTimes`, `QueryRowCounts`, `QueryErrorCounts`, etc. for writes that come through VRep and not through gates. We discussed this in Slack, but putting it here for completion. I'll start working on this one right now. 

There's probably more that are similar, I'll add to this issue as they come up for me.

**Comment by zmagg** [comment]
One more! 

The docs report:
> VReplication has the capability to batch transactions if the send rate of the source exceeds the replay rate of the destination.  

It'd be great to have metrics indicating how much batching is actually happening. A counter that increments for every batched transaction similar to the Consolidations metrics would be fantastic. Then we could see how much batching is happening overtime, if any.

Similarly, if there's a great way to sniff on VReplication -- perhaps a streaming log published on the /debug/status page? Curious actually if there's a good way to do that today. I'd like to see what batching we're actually getting on some workloads.

**Comment by sougou** [comment]
Check out `/debug/vrlog`.

**Comment by zmagg** [comment]
Wow, `/debug/vrlog` is exactly what I wanted in terms of seeing what was going on.

**Comment by mattlord** [comment]
I'm going to close this as done since I don't see any remaining work left from the PR description. If I'm missing something please let me know and we'll reopen this. Thanks!
