### ISSUE TITLE
Announce: deprecating support for Statement Based Replication

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#4593]
This is a heads up that we will soon stop supporting SBR. This decision was made a few meetups ago.

What does this mean to those who currently depend on SBR: For the foreseeable future, you will probably not be affected. All existing SBR features and settings will continue to work as is. We will continue accepting critical bug fixes in those areas. However, new features of vitess are not guaranteed to support or work with SBR. Specifically, the new vreplication related set of features will not work unless RBR is enabled.

The motivations behind this decision are as follows:
* The industry has firmly started moving away from SBR. There is not much new development or tooling for SBR any more. Many MySQL statements are already considered unsafe for SBR.
* The newer features of Vitess, like vreplication, can work only with RBR.
* Removing support for SBR will allow us to delete a lot of legacy code and improve maintainability of the code base.

We can look at accelerating the deprecation if all existing users that currently depend on SBR migrate out quickly.

**Comment by sougou** [comment]
We have confirmed that all users of the master branch are on RBR. Existing users of SBR have acknowledged that they will either not upgrade, or will switch to RBR before upgrading.

We can now declare that the master branch and subsequent releases of vitess will not support SBR. We are free to delete any SBR code as long as it doesn't break the rest of the system.

**Comment by morgo** [comment]
This is in the release notes, and the manual has been modified to say RBR is required. I am going to close this issue for now.
