### ISSUE TITLE
Support per query variables

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4596]
Both Percona and MariaDB support per query variables. It would be nice to support this construct as a pass through. Given the connection pooling of each tablet, there's no way to set a session variable for one-off commands. This provides a workaround.

```
SET STATEMENT var1=value1 [, var2=value2, ...] 
  FOR <statement>

SET STATEMENT var1=value1 FOR stmt

is roughly equivalent to

SET @save_value=@@var1;
SET SESSION var1=value1;
stmt;
SET SESSION var1=@save_value;
```

https://www.percona.com/doc/percona-server/5.7/flexibility/per_query_variable_statement.html
https://mariadb.com/kb/en/library/set-statement/

**Comment by morgo** [comment]
There is something similar to this in MySQL 8.0.  The [syntax is as follows](https://dev.mysql.com/doc/refman/8.0/en/optimizer-hints.html#optimizer-hints-set-var):

```
SELECT /*+ SET_VAR(sort_buffer_size = 16M) */ name FROM people ORDER BY name;
INSERT /*+ SET_VAR(foreign_key_checks=OFF) */ INTO t2 VALUES(2);
SELECT /*+ SET_VAR(optimizer_switch = 'mrr_cost_based=off') */ 1;
```

**Comment by harshit-gangal** [comment]
@derekperkins We already support query comments, am I missing anything here?

**Comment by derekperkins** [comment]
These used to get stripped out or mangled. We're 1.5 years behind, so I haven't tested this on recent versions

**Comment by harshit-gangal** [comment]
@derekperkins do you still see query comments getting stripped or mangled?
