### ISSUE TITLE
Proposal: Improve the schema model for vitess

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#4597]
Vitess currently exposes two ways to access tables spread across keyspaces:

## 1. MySQL schema model
In this model, every keyspace is exposed like a schema. This allows you to specify a keyspace wherever a mysql schema can be specified:
* DB connection
* USE statement
* Qualified table name: `keyspace.t`

## 2. Unnamed database model
In this model, the app connects without specifying a database name, and can access tables from any keyspace. If the table name is unique, then vitess sends the query to the corresponding keyspace. If there are duplicate tables across different keyspaces, then you cannot access them.

You can still access them by qualifying them by their specific keyspace.

# Proposal
The unnamed database model does not exactly map to how MySQL behaves: you cannot connect to mysql with an empty database name and expect to run queries with unqualified table names.

Because of this, some ORMs require you to specify a db name in the connection.

To unbreak this, we propose that you can connect to vitess using a pre-determined fake database name. The proposed name would be either `_vitess`, or `_unified`. If one connects to such a database, then you get the second model, where all tables appear to be part of a single schema.

Of the above usages, the important ones to cover (in order of priority) are:
1. DB connection
2. USE statement
3. Qualified table name: `_vitess.t`

While connected to `_vitess`, explicit `keyspace.t` constructs will continue to work as before. Nothing special needs to be done for these.

**Comment by tirsen** [comment]
I like it. We always get into issues with this although we have managed to work around it. What I would suggest however is that we still support the "no database" option for backwards compatibility. Otherwise a change like this would break everything here. :-)

**Comment by demmer** [comment]
Wouldn't this `_vitess` proposal be the same as just connecting to `@master`?

**Comment by sougou** [comment]
Ohh. Why didn't I think of that? Let me think and make sure there are no other corner cases, and then close this.
