### ISSUE TITLE
Improve UNION support

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4613]
Currently when trying to use `UNION ALL` this error is returned: `unsupported: UNION or subquery on different shards: vindex values are different`.

> it's probably a 1-2 day work, maybe less if you're familiar with v3 code @sougou 

```
SELECT id, retrieved_at FROM tbl where id=1 AND retrieved_at>=1549324800 ORDER BY retrieved_at DESC LIMIT 1
UNION ALL
SELECT id, retrieved_at FROM tbl where id=2 AND retrieved_at>=1549324800 ORDER BY retrieved_at DESC LIMIT 1
...
```

**Comment by sverch** [comment]
Had a discussion today about this, and @systay mentioned that `UNION ALL`, because it doesn't have to use distinct, wouldn't be too difficult to implement.

I was going to make a new issue, but it looks like your use case in the description is exactly what I was about to add.

**Comment by harshit-gangal** [comment]
@derekperkins if both the statement has Order by and limit is ambiguous whether the last order by limit belongs to the select or post union all.

Vitess will throw error
```
# ambiguous ORDER BY
"select id from user order by id union all select id from music order by id desc"
"Incorrect usage of UNION and ORDER BY - add parens to disambiguate your query (errno 1221) (sqlstate 21000)"
```
