### ISSUE TITLE
How to use mysql client access inside the container?

### ISSUE THREAD

**Issue by lkxjtu** [vitessio/vitess#4629]
I have a vitess cluster with two keyspaces, which is running well. For debug,I want to use mysql-client access mysql in the container.Can I?With username and password?I am a fresh man of vitess.Thank you very much!

    [root@master1 vitess]# kubectl exec -it zone1-commerce-0-replica-0 bash
    Defaulting container name to mysql.
    Use 'kubectl describe pod/zone1-commerce-0-replica-0 -n default' to see all of the containers in this  pod.
    bash-4.2$ mysql
    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
    bash-4.2$

**Comment by derekperkins** [comment]
It looks like you're running in Kubernetes deployed with the helm chart. If that's the case, you can access mysql directly with `mysql -uroot --socket=/vtdataroot/tabletdata/mysql.sock`.

**Comment by lkxjtu** [comment]
> It looks like you're running in Kubernetes deployed with the helm chart. If that's the case, you can access mysql directly with mysql -uroot --socket=/vtdataroot/tabletdata/mysql.sock.

Thank you very much! It works well! @derekperkins
