### ISSUE TITLE
Tools: Migrate from unused to staticcheck

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#4639]
After I updated the `unused` tool in misc/git/hooks, it gave me a message saying that it's deprecated and that we should use `staticcheck` instead. We should switch to that.

Also, pylint is sitting in hooks. It's an internal google tool. We should remove it.

**Comment by deepthi** [comment]
What do you think of replacing gpylint with pylint from https://github.com/PyCQA/pylint/?

**Comment by sougou** [comment]
Not worth it. We should migrate our python tests to go instead :smile:
