### ISSUE TITLE
How to create a Backup Storage？

### ISSUE THREAD

**Issue by lkxjtu** [vitessio/vitess#4650]
About how to create backup storage, I only found one link from the document: https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/backupstorage/interface.go
From this link, I still don't know how to create it. Is there a more detailed documentation? Thank you very much!My vitess cluster is running on kubernetes, and I want to create a backup storage of file type.

    vtctl -topo_implementation="etcd2" -topo_global_root=/vitess/global - topo_global_server_address="etcd-global-client.default:2379" Backup zone1-0794219800
    ERROR: logging before flag.Parse: E0221 11:22:30.034908      89 syslogger.go:122] can't connect to  syslog
    W0221 11:22:30.039507      89 vtctl.go:80] cannot connect to syslog: Unix syslog delivery error
    E0221 11:22:30.064590      89 vtctl.go:103] action failed: Backup rpc error: code = Unknown desc =     TabletManager.Backup on zone1-0794219800 error: no registered implementation of BackupStorage:   no registered implementation of BackupStorage

**Comment by slanning** [comment]
Try this: https://github.com/vitessio/vitess/blob/master/doc/BackupAndRestore.md
We pass some flags to vtctld and vttablet depending on what `-backup_storage_implementation` is.
For NFS for example, the implementation is "file" and you also pass `-file_backup_storage_root`.

**Comment by deepthi** [comment]
Thanks @slanning

**Comment by lkxjtu** [comment]
Thanks @slanning 
I have see the link above. About how create a backup storage, it only provides a link of https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/backupstorage/interface.go
I have tested to adding "-backup_storage_implementation=file" and "-file_backup_storage_root=/bak/".But the result is the same.

    vtctl -topo_implementation="etcd2" -topo_global_root=/vitess/global -topo_global_server_address="etcd-global-client.default:2379" -backup_storage_implementation=file -file_backup_storage_root=/bak/ Backup zone1-0794219800
    ERROR: logging before flag.Parse: E0222 00:26:29.245891      34 syslogger.go:122] can't connect to syslog
    W0222 00:26:29.251147      34 vtctl.go:80] cannot connect to syslog: Unix syslog delivery error
    E0222 00:26:29.281393      34 vtctl.go:103] action failed: Backup rpc error: code = Unknown desc = TabletManager.Backup on zone1-0794219800 error: no registered implementation of BackupStorage: no registered implementation of BackupStorage

**Comment by slanning** [comment]
Has the vttablet been restarted with the flags? (I think vtctl client doesn't need them.)

**Comment by deepthi** [comment]
@lkxjtu how are you running vitess? 
This is really odd because the BackupStorage implementations are registered during initialization and should always exist.
Questions like this should be asked on the vitess slack where there is a large community of users who can help. You can join using this link:
https://vitess.slack.com/join/shared_invite/enQtMzIxMDMyMzA0NzA1LTBjYjY1M2I2Yjg5YmY3ODIwOTk0N2M1YzI4Y2ViODdiNmIxMDdiMDM5YWQ1ZTc0YmJhZDdiOTliMGVkNDY4MjM

**Comment by lkxjtu** [comment]
Sorry, I made a mistake. The vtctl client has the option of "-backup_storage_implementation" and "-file_backup_storage_root" too. I was confused by it. Backup and restore can work fine. Thank you! @slanning @deepthi 

@deepthi Fine, I will ask question on it.
