### ISSUE TITLE
Composing Interceptors in grpc server 

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#4652]
In https://github.com/vitessio/vitess/blob/master/go/vt/servenv/grpc_server.go#L165, if we are using both authentication and prometheus, we'll end up adding two different `StreamServerInterceptor`/`UnaryServerInterceptor`'s to `opt`. This is not allowed by [grpc](https://github.com/grpc/grpc-go/blob/master/server.go#L275), and leads to a `panic`.

**Comment by systay** [comment]
Came across this when working on #4610, which would add an additional interceptor.

**Comment by dweitzman** [comment]
Looks like https://github.com/grpc-ecosystem/go-grpc-middleware/blob/master/chain.go might help with chaining multiple `UnaryServerInterceptor`s

**Comment by systay** [comment]
Sounds lika solution to me, @dweitzman! 👍
