### ISSUE TITLE
`-db_charset` doesn't behave the same way as deprecated `-db-config-*-charset` settings

### ISSUE THREAD

**Issue by tomkrouper** [vitessio/vitess#4654]
#### Overview of the Issue

We use emoji in our application and because of that we need to use `utf8mb4`. We still have the old-style `-db-config-<user>-charset` settings which we changed to `utf8mb4` and everything worked as expected. While working with this, I saw the deprecation notice, so I attempted to just use `-db_charset utf8mb4`. This did not work. @deepthi was able to point me to `func Init(defaultSocketFile string) (*DBConfigs, error)` which shows that `-db_charset` requires `-db_host`. Unfortunately, when I set `-db_host`, my.cnf gets ignored which causes other issues.

Expected behavior would be to have setting `-db_charset` be the same behavior as setting the charset on a user level.

#### Reproduction Steps

1. Spin up docker `vitess/base`.
1. Start vttablet with `-db-config-dba-charset utf8mb4 -db-config-app-charset utf8mb4 -db-config-appdebug-charset utf8mb4 -db-config-allprivs-charset utf8mb4 -db-config-repl-charset utf8mb4 -db-config-filtered-charset utf8mb4` options
1. Insert data with emoji.
1. SELECT data, see emoji in output.

1. Spin up docker `vitess/base`.
1. Start vttablet with -db_charset utf8mb4`
1. Insert data with emoji.
1. SELECT data, see `?` where emoji output should be.
 

#### Binary version
Example:

```sh
vitess@4792fbfd1caa:/vt/src/vitess.io/vitess$ vttablet --version
ERROR: logging before flag.Parse: E0221 22:23:34.724761    2113 syslogger.go:122] can't connect to syslog
Version: 613bb78e4 (Git branch 'master') built on Tue Feb 12 04:35:14 UTC 2019 by root@40b3289860a2 using go1.11.2 linux/amd64
```

#### Operating system and Environment details

docker vitess/base

**Comment by deepthi** [comment]
Fixed by #4814
