### ISSUE TITLE
mysql57.unit_race FAIL (and others) in Travis builds

### ISSUE THREAD

**Issue by gak** [vitessio/vitess#4701]
#### Random failures in Travis tests

Sometimes mysql tests fail even with unrelated PRs, e.g.: https://travis-ci.org/vitessio/vitess/jobs/499537337

The last few that have failed:

 * https://travis-ci.org/vitessio/vitess/jobs/498346958 -- unit_race, no code changes: https://github.com/vitessio/vitess/commit/d4176b97bcd95072ae452c399d90e4eefe135273
 * https://travis-ci.org/vitessio/vitess/jobs/497301184 -- mysql57.unit, no code changes
 * https://travis-ci.org/vitessio/vitess/jobs/496742297 -- mysql57.unit, no code changes
 * https://travis-ci.org/vitessio/vitess/builds/494667954 -- mysql57.unit_race and mysql57.local_example, no code changes

#### Reproduction Steps

It happens randomly, not sure of the odds. If I had to guess, 1 in 4. You just need to kick off a Travis build and it might happen.

#### Log Fragments

I'm not sure how to access the logs as Travis has no options for accessing the image after its done. Maybe a PR that can catch the output directory (e.g. `mysql57.unit_race: saving test output to _test/20190225-194605.4001/mysql57.unit_race-1.3.log`) as the artefact, or make the tests run with `-follow`.

**Comment by morgo** [comment]
Unit race is currently flaky again, but I have issue https://github.com/vitessio/vitess/issues/5523 open to cover it. I am going to close this issue now.
