### ISSUE TITLE
Set innodb_flush_log_at_trx_commit to 1 for durability and consistency?

### ISSUE THREAD

**Issue by HCHCHH** [vitessio/vitess#4707]
In the mysql [config file](https://github.com/vitessio/vitess/blob/63d2180c9442f64cec8f5cc6e5eb43947034e8ef/config/mycnf/default.cnf), **innodb_flush_log_at_trx_commit** is set to 2. 

However, the MySQL [official document](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit) recommends to set it to 1, which helps keep InnoDB ACID Compliant.
"For durability and consistency in a replication setup that uses InnoDB with transactions: **Always set innodb_flush_log_at_trx_commit=1.** ". 

I wonder if there is any durability or consistency concern. Thanks.

**Comment by sougou** [comment]
`innodb_flush_log_at_trx_commit` and `sync_binlog` setting depend on how you plan to run vitess and how you plan on handling failures.

If you plan to use mysql recovery to restart crashed nodes, you need to change these settings (as well as a few more) to make them safe for replication and recovery.

The alternate approach is to rely on semi-sync for durability, and always throw away a failed node. Instead, restore from backup and let it catch up by replicating binlogs from the master. In this approach, you can use buffered I/O for all operations, which will give you much higher throughput and better latencies than the previous approach. But your failure tolerance will be slightly lower, as you will be more exposed while a new replica is restoring or catching up to its master.
