### ISSUE TITLE
switch from govendor to go modules

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4721]
The main benefit is ease of use. Compiling vitess binaries and running unit tests will not require any bootstrapping

The drawbacks I'm aware of:
- It's not easy to ensure that the dependency versions with go modules exactly align with govendor, so the transition may slightly change the versions of many dependencies at once
- Somewhat related, go modules do not let you depend on different versions of packages within the same repo while govendor does. If this becomes an issue there are mitigations. go modules allow vendor directories, and there's also the option to fork a dependency and instruct the go toolset to resolve package names the forked version 
- go modules do not yet make it possible to avoid downloading or compiling indirect dependencies that aren't actually reachable from vitess. This can potentially waste some network/disk

Example code for switching to modules: https://github.com/dweitzman/vitess/tree/vgo

**Comment by saifalharthi** [comment]
This PR is looking into it https://github.com/vitessio/vitess/pull/5109

**Comment by acharis** [comment]
this can be closed now, yes?

**Comment by deepthi** [comment]
Fixed by #5109
