### ISSUE TITLE
Simplify sharding workflow for dbs with foreign keys

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4723]
This is a tracking bug for fk issues. These are some things that don't yet work gracefully for dbs that use foreign keys

- [ ] CopySchemaShard (PR #4722)
- [x] ApplySchema (PR #4696)
- [ ] SplitClone

For SplitClone, supporting fk's gracefully would be a matter of making sure that `foreign_key_checks = 0` on the db connections that do the initial cloning

In the meantime, people can run `set global foreign_key_checks = 0` on new destination shards and then `set global foreign_key_checks = 1` after SplitClone finishes while vreplication is running.

**Comment by deepthi** [comment]
@dweitzman I think #6284 addresses both the open items above. If you agree we can close this issue.

**Comment by dweitzman** [comment]
Sorry for the super late response: I don't think #6284 addresses both items. It addresses SplitClone, but not CopySchemaShard

I still think #4722 should probably reopened in some form in landed. I can't see think of any reason a person running `CopySchemaShard` would rather get a partial success and then a foreign key error (vs getting a shard with a copy of another shards schema, which is what you'd normally expect the command to do)

**Comment by mattlord** [comment]
I'm closing this as done since Vitess now supports foreign keys and I'm unaware of specific issues today related to Reshard. If I'm missing anything please let me know and we can re-open this with additional details.
