### ISSUE TITLE
on vtctld or vtctl ,some function not found

### ISSUE THREAD

**Issue by MicroftClock** [vitessio/vitess#4730]
> hello,every one.
> today i use vtctld and vtctl and meet a question.
> i want to use vtctld and vtctl make vttablet become master,but,it can't,and say:

`"There was a problem pinging replica(101): rpc error: code = Unimplemented desc = unknown service tabletmanagerservice.TabletManager "`

like this situation，also can find in Ping,InitShardMaster,refresh state,other in this picture.
![image](https://user-images.githubusercontent.com/30529481/54519368-55d38a80-49a1-11e9-800c-fb62d7a853fe.png)

some function can be used normally,like getkeyspace,deleteVttablet...
Is my GO package not installed completely?
how can i solve it?
thanks.

**Comment by MicroftClock** [comment]
![image](https://user-images.githubusercontent.com/30529481/54519622-ed38dd80-49a1-11e9-8d8c-25b0bef772cf.png)

**Comment by sougou** [comment]
Did you specify the service map for the vttablets? https://github.com/vitessio/vitess/blob/master/examples/local/vttablet-up.sh#L138

**Comment by MicroftClock** [comment]
thanks,yesterday,i solve this problem by this way,I manually started vttablet careless
