### ISSUE TITLE
Simplify query tracking between vtgate and vttablet

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4741]
#### Feature Description

This may be something that's work in progress but I think it's good to comment on and see that the issues I see at the moment.

I have seen some apps experience "slow queries".  Compared to connecting directly to MySQL this appears to be unexpected, so I'd like to track down the queries which are slow,  how long they last (as seen by Vitess) and the path from `vtgate` to `vttablet` to identify any common path or problem points. 

Right now you can query the web interface using `/debug/querylog` or `/debug/querylogz` which gives a prettier user-centric view of the information.

However, it's not currently possible as far as I can see to recognise a query coming into `vtgate` and determine which `vttablets` it gets sent to or exactly correlate logging between one and the other.

I'd like to see the following:
On vtgate:
* some sort of reference for the query being logged generated by *Vitess*.
* an indication of the `vttablet`s being queried: I'd guess that could be of the form of something like `<cell_name>:<uid>,...,<uid>;..;<cell_name>:<uid>,...,<uid>`.  Normally the number of cells and tablets will be quiet small. `uid` would be the tablet uid.

On vttablet:
* an indication of which vtgate sends the query
* the vitess reference from that came from the vtgate

With this information it should be easier to correlate query timings from the app to the `vtgate` ... `vttablet`(s) and back. 

A thought.
It might be convenient if the app can provide a reference to include that. The only way I can think of doing that would be to have a specially formatted SQL comment such as `/* VQR: akskenzuuhd */`  (VQR = Vitess Query Ref?, and the reference probably should be limited in size avoid extra overhead, but not sure on actual values here.)  If this reference existed it would need to be included in `/debug/querylogz?` logging too in some form.

#### Use Case(s)

Usage is to track performance problems so they can be resolved.  Issues may be for many reasons and the only way to follow them in a complicated environment such as Vitess is to have a way to follow queries from end to end.

Maybe there's a better way of handling this. If there is then I'd be most interested in following any suggested best practice, and at least this issue will be helpful for other users who have similar issues.

**Comment by dweitzman** [comment]
#4610 is a PR for wiring up distributed tracing support in vitess at the grpc level. As you mention, for the mysql protocol some kind of special comment syntax would be needed to propagate traceid & parent span ID. A person would also need to run separate software to collect & visualize traces, or else just aggressively grep for trace IDs. You can kind of do the grepping version today if you keep logs and put trace IDs into sql comments before they hit vtgate, but the comments might not make it into all the vindex or nextval queries.

I would also be interested in potentially adopting opencensus so that vtgate could sample additional information about some queries when recording metrics. The additional information could give a sense of what a recent slow query might actually look like in more detail: the sql, what tablets it fanned out to, etc. In opencensus these are called exemplars.

**Comment by demmer** [comment]
We handle this at Slack by including a unique identifier in all our API requests that is included in the DB queries as a trailing comment along with other useful information like the user and customer ID.

This is then recorded in the vtgate and vttablet query logs which we harvest and then parse into our data warehouse alongside other logs from our system for correlating queries from a given request.

It's expensive to log everything and the tracing stuff is probably a better path overall, but this works for us for now at least.

**Comment by sjmudd** [comment]
Thanks for links to real stuff that's being done now.  The opentracing tool sounds interesting. I need to read up on that and other options to see what's needed to plug this all in.
@demmer: I would see the processing of all query logs to be expensive as a site grows and while we do process a large amount of "events" query log processing at our scale may be tricky. Either way it's good to see this can work if things are plugged in appropriately.

So thanks for the pointers. I'll look forward to seeing how PR #4610 progresses and do some investigation into opentracing and other options.

**Comment by demmer** [comment]
> @demmer: I would see the processing of all query logs to be expensive as a site grows and while we do process a large amount of "events" query log processing at our scale may be tricky. Either way it's good to see this can work if things are plugged in appropriately.

It absolutely is and continue to weigh pros and cons as we increase scale.

**Comment by GuptaManan100** [comment]
https://github.com/vitessio/vitess/pull/4610 is merged and we also added support for VEXPLAIN - https://github.com/vitessio/vitess/pull/11892 which runs all the queries and collects timings and bunch of other information for a scatter query.

If there is something else that is required for better tracing please open a new issue.
