### ISSUE TITLE
Kubernetes tutorial does not work on Mac - Can't start server : Bind on unix socket: File name too long

### ISSUE THREAD

**Issue by ngrigoriev** [vitessio/vitess#4752]
#### Overview of the Issue

I have attempted to follow the "Run Vitess on Kubernetes" tutorial. The cluster does not seem to start. 

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Follow the K8S tutorial up to "Verify Cluster" section

2. Notice that the DB replicas fail to start and keep restarting

```
$ kubectl get pods,jobs
NAME                                       READY   STATUS             RESTARTS   AGE
pod/commerce-apply-vschema-initial-28qcq   0/1     Completed          0          52m
pod/etcd-global-rnf9q254xr                 1/1     Running            0          52m
pod/etcd-operator-7597c55847-mj7sb         1/1     Running            0          52m
pod/etcd-zone1-kf554vxg5m                  1/1     Running            0          52m
pod/vtctld-84f74b5458-dc84z                1/1     Running            2          52m
pod/vtgate-zone1-6866dd4cfb-j7qdh          1/1     Running            2          52m
pod/zone1-commerce-0-rdonly-0              4/6     CrashLoopBackOff   7          52m
pod/zone1-commerce-0-replica-0             4/6     CrashLoopBackOff            8          52m
pod/zone1-commerce-0-replica-1             4/6     CrashLoopBackOff            8          52m

NAME                                           DESIRED   SUCCESSFUL   AGE
job.batch/commerce-apply-schema-initial        1         0            52m
job.batch/commerce-apply-vschema-initial       1         1            52m
job.batch/zone1-commerce-0-init-shard-master   1         0            52m
```

#### Operating system and Environment details

- Operating system: MacOS 10.14.3
- Docker Desktop Community 2.0.0.3 (31259)
- Kubernetes: provided by Docker Desktop (minikube-based)

#### Log Fragments

I am not sure if this is the root cause but most likely it is. All 3 "*commerce-0-*" PODs have the same kind of error message in their error-log container:

```
...
2019-03-25T18:13:35.713617Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2019-03-25T18:13:35.713857Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2019-03-25T18:13:35.720762Z 0 [Warning] CA certificate ca.pem is self signed.
2019-03-25T18:13:35.722016Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2019-03-25T18:13:35.727904Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2019-03-25T18:13:35.728209Z 0 [Note] IPv6 is available.
2019-03-25T18:13:35.728444Z 0 [Note]   - '::' resolves to '::';
2019-03-25T18:13:35.728655Z 0 [Note] Server socket created on IP: '::'.
2019-03-25T18:13:35.730670Z 0 [ERROR] Can't start server : Bind on unix socket: File name too long
2019-03-25T18:13:35.731002Z 0 [ERROR] Do you already have another mysqld server running on socket: /vtdataroot/tabletdata/mysql.sock ?
2019-03-25T18:13:35.731270Z 0 [ERROR] Aborting

2019-03-25T18:13:35.731534Z 0 [Note] Binlog end
2019-03-25T18:13:35.732888Z 0 [Note] Shutting down plugin 'rpl_semi_sync_slave'
2019-03-25T18:13:35.733135Z 0 [Note] Shutting down plugin 'rpl_semi_sync_master'
2019-03-25T18:13:35.733406Z 0 [Note] unregister_replicator OK
...
```

**Comment by ngrigoriev** [comment]
I have just performed exactly the same exercise on Linux and it worked, so the problem seems to be Mac-specific.

**Comment by deepthi** [comment]
the apparent socket path is pretty short `/vtdataroot/tabletdata/mysql.sock`, so this could be caused by:
"There are issues with socket name lengths if the socket is being created on a volume shared with the Mac, as the path being created will be the full un-namespaced socket path and will also include the OSX directory path you are sharing, and the OSX length is shorter than the Linux one."
Credit: justincormack https://github.com/moby/moby/issues/23545

**Comment by ngrigoriev** [comment]
@deepthi 

Exactly. Just did a simple test: mounted a volume in a dummy container, created a path "/testvol/a/very/long/path/that/should/cause/troubles/on/mac/000000000000000000000000000000/11111111111111111111111111111" (/testvol is a volume I passwrd to "docker run -v"), ran this python script: 

```
/ # python
Python 2.7.15 (default, Aug 16 2018, 14:17:09)
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket as s; sock = s.socket(s.AF_UNIX);
>>> sock.bind('/testvol/a/very/long/path/that/should/cause/troubles/on/mac/000000000000000000000000000000/11111111111111111111111111111/my.sock')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: AF_UNIX path too long
```

Obviously, does not happen if it is not the mounted volume. So, confirmed.

**Comment by ngrigoriev** [comment]
Probably the solution would be to mount a volume created somewhere like under /tmp on the host

**Comment by phanimullapudi** [comment]
How to mount mysql.sock to /tmp on the host ?

**Comment by henders** [comment]
Any suggested workaround for this? I'm also running into this on the docker-for-mac builtin k8s cluster. Thanks.

**Comment by phanimullapudi** [comment]
i rather run on Centos....it worked for me

**Comment by henders** [comment]
@phanimullapudi : Do you mean you just changed the `mysql` docker image that is used (The Vitess Operator uses `percona:5.7.23` as the mysql image)? Or did you change something else to CentOS?

**Comment by PinZhang** [comment]
I have suffered the same problem on MacOS, any solution ?

**Comment by alvinzane** [comment]
**I'd like share my solution to resolve this issue(my evn: Mac with docker desktop).**

1. Update StorageClass is not default class:
`
$ kubectl edit storageclass
`
to be:
```
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "false"
```

2. Create the pvs manually with a short path which vitess needed:
```
$ cat my-pv.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: vitess-local
    app: vitess
  name: vitess-local-volume-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/vitess-data-0
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
...

$ kubectl apply -f my-pv.yaml
$ kubectl get pv -o name
persistentvolume/vitess-local-volume-0
persistentvolume/vitess-local-volume-1
persistentvolume/vitess-local-volume-2
persistentvolume/vitess-local-volume-3
persistentvolume/vitess-local-volume-4
persistentvolume/vitess-local-volume-5
persistentvolume/vitess-local-volume-6

```

3. Enjoy youselfs.

**Comment by mattlord** [comment]
I'm going to close this for now as it seems to be stale. I hope that this was/is addressed in future versions of Docker Desktop for Mac, but if not it looks like we currently have a noted workaround. Thank you!
