### ISSUE TITLE
Database migration problem

### ISSUE THREAD

**Issue by xichengliudui** [vitessio/vitess#4754]
Hello, I would like to ask about the migration of the database, I now have four databases, which take up a lot of resources, and I desperately want to improve them.
Respectively is:

  - mysql 5.3
  - mysql 5.6
  - mariadb
  - postgresql

Could Vitess help me improve them? Thanks again!

**Comment by deepthi** [comment]
The vitess slack is the best place for such questions. If you are not already on it, you can join:
https://vitess.slack.com/join/shared_invite/enQtMzIxMDMyMzA0NzA1LTBjYjY1M2I2Yjg5YmY3ODIwOTk0N2M1YzI4Y2ViODdiNmIxMDdiMDM5YWQ1ZTc0YmJhZDdiOTliMGVkNDY4MjM

**Comment by xichengliudui** [comment]
@deepthi  thanks!
