### ISSUE TITLE
Improve documentation on access and use of user stats

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/vitess#4765]
Users seek to differentiate metrics for bad_user@their_machine from good_user@their_machine instead of them both appearing to be the same user from the same server (from mysql logs).

Response info.:
Table ACLs are the way to go for this.  Vitess exports per-user stats, demonstrated in the end-to-end tests.
Config:
   ```https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/endtoend/main_test.go#L17```And here are the tests that demonstrate how it works:```https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/endtoend/acl_test.go```
Look in ```/debug/vars``` to see a few variables that start with User, like ```UserTableQueryCount```. It's a multi-dimentional export categorized by Table, User and query type. You'll find similar names exported as prometheus metrics.
If you see an incident of interest, looking at these variables will help you quickly narrow     down the root cause because of how fine-grained these stats are. Once you've identified the     table and query type, you can further drill down int /queryz (human readable) or /debug/        query_stats (JSON), to see if it's a particular query.

**Comment by hallaroo** [comment]
Add this to the FAQ now hosted in Freshdesk: https://planetscale.freshdesk.com/a/solutions/articles/64000257950
