### ISSUE TITLE
Improve GetVschema error reporting

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/vitess#4771]
#### Feature Description
GetVschema yields a somewhat vague error when keyspace exists but vschema itself has not yet been created.   This may technically be an error, but the reporting of the condition could be more precise.

#### Use Case
This condition was encountered while walking through  the Vitess tutorial: ```https://vitess.io/docs/tutorials/kubernetes/``` 

at the point where a new keyspace ```customer``` is created:
`helm upgrade $release ../../helm/vitess/ -f 201_customer_keyspace.yaml`

after which one can request  current vschema:
`vtctlclient -server <IP address:port> GetVschema customer`

which yields:
`E0401 09:56:48.838264   38486 main.go:63] Remote error: rpc error: code = Unknown desc = node doesn't exist: /vitess/global/keyspaces/customer/VSchema`

Could instead say: "keyspace exists, vschema does not"

**Comment by sougou** [comment]
Fixed in #4868 and #5010
