### ISSUE TITLE
Centralised dependency list

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#4780]
#### Overview of the Issue
In the codebase there are several places where we manage external dependencies. Unfortunately it's hard to keep them in sync and de-sync can often create [issues](https://vitess.slack.com/archives/CEN9DRWSJ/p1554224587001000).

Example:

- https://github.com/vitessio/vitess/blob/master/docker/bootstrap/Dockerfile.common#L3-L38
- https://github.com/vitessio/vitess/blob/master/vagrant-scripts/bootstrap_vm.sh#L17-L35
- https://github.com/vitessio/vitess/blob/master/doc/GettingStarted.md

I'm opening this issue to keep track of the problem and with the hope of discussing a proposal for a single source of truth for all the dependencies needed to build and run Vitess.

**Comment by morgo** [comment]
The dependency list should be shrinking a lot (use of go modules, converting Python tests to go etc.), which will make it easier to manage.

I will look at updating the [build guide](https://vitess.io/docs/contributing/build-from-source/) in a couple of months time as this work completes. We can then take another look at this issue.

**Comment by morgo** [comment]
I have been updating the build guides as we trim dependencies. See https://github.com/vitessio/website/pull/372 for a next-generation, where they are quite light.

I also added a dependency_check shell script to the Makefile in https://github.com/vitessio/vitess/pull/5527

I am going to close this issue now, but please feel free to re-open if you feel this is not sufficiently addressed.
