### ISSUE TITLE
Null pointer exception during MigrateServedTypes master if no master present

### ISSUE THREAD

**Issue by nagavamsi** [vitessio/vitess#4783]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

I setup replica/rdonly tablets for unsharded data and used split clone to create new shards.

I wanted to try my queries on sharded data to validate that they are working. However, it won't allow me to query sharded data until I do MigratedServerTypes. 

When I did that, I saw NPE.

#### Repro Steps
Including only the MigrateServedTypes. cmd

/usr/local/go/src/vitess.io/vitess/examples/local$ ./lvtctl.sh MigrateServedTypes ans/0 master
E0403 00:55:36.339511   54800 main.go:63] Remote error: rpc error: code = Unavailable desc = transport is closing

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`):
- Kernel version (output of `uname -sr`):
- Architecture (output of `uname -m`):

#### Log Fragments

:~/vtdataroot/tmp# cat vtctld.out
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9b1181]

goroutine 385 [running]:
vitess.io/vitess/go/vt/topo.(*Server).GetTablet(0xc0002a5680, 0x139aee0, 0xc000193ce0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/vitess.io/vitess/go/vt/topo/tablet.go:220 +0x51
vitess.io/vitess/go/vt/wrangler.(*Wrangler).refreshMasters.func1(0xc00046b110, 0xc000193c20, 0x139aee0, 0xc000193ce0, 0xc0000fac00, 0xc0001b3980)
    /usr/local/go/src/vitess.io/vitess/go/vt/wrangler/keyspace.go:442 +0x16d
created by vitess.io/vitess/go/vt/wrangler.(*Wrangler).refreshMasters
    /usr/local/go/src/vitess.io/vitess/go/vt/wrangler/keyspace.go:439 +0xe0 (edited)

**Comment by mattlord** [comment]
I'm closing this as no done / longer relevant.
