### ISSUE TITLE
[query planner] limited scatter query not supported with OR clause

### ISSUE THREAD

**Issue by brirams** [vitessio/vitess#4802]
#### Overview of the Issue

The query planner doesn't seem to take a VSchema's vindex into account when doing point queries using the OR operator. For the following case, where `col1` is the vindex:

```sql
select * from tbl where (col1 = $val1 AND col2 = $val2) OR (col1=$val2 AND $val2);
```

I'd expect vitess to do the same thing it does for IN clauses where the scatter is limited to just the shards that contain `$val1` and `$val2` rather than doing a `ScatterSelect` across the whole keyspace. 

Further, it seems that including extra parenthesis around a predicate for a point query results in a `ScatterSelect`, as well:

```sql
select * from tbl where (col1=$val1 and 1=1)
```

will hit a single shard while:

```sql
select * from tbl where ((col=$val1 and 1=1))
```

will do a scatter.

#### Reproduction Steps

I've pushed [a branch](https://github.com/vitessio/vitess/compare/master...tinyspeck:brirams_limited_scatter_query_planner) with a few additional testcases to `vtexplain_flaky_test.go` that highlight the expected behavior(IN clause) versus actual.

**Comment by GuptaManan100** [comment]
Vitess is able to handle queries like these. For the query - `select * from user where (id = 1 and col = 'val') or (id = 4 and col = 'val2')`, the plan looks like - 
```json
{
  "QueryType": "SELECT",
  "Original": "select * from user where (id = 1 and col = 'val') or (id = 4 and col = 'val2')",
  "Instructions": {
    "OperatorType": "Route",
    "Variant": "IN",
    "Keyspace": {
      "Name": "user",
      "Sharded": true
    },
    "FieldQuery": "select * from `user` where 1 != 1",
    "Query": "select * from `user` where id in ::__vals and (id = 1 or col = 'val2') and (col = 'val' or id = 4) and col in ('val', 'val2')",
    "Table": "`user`",
    "Values": [
      "(1, 4)"
    ],
    "Vindex": "user_index"
  },
  "TablesUsed": [
    "user.user"
  ]
}
```
