### ISSUE TITLE
[vttablet] Heap allocated usage high after sustained ScatterSelects

### ISSUE THREAD

**Issue by brirams** [vitessio/vitess#4810]
#### Overview of the Issue

While running a batch job against our vitess cluster where we were doing [primary key ordered scatter queries across the whole keyspace](https://github.com/vitessio/vitess/issues/4802), we found that the memory usage on some of the target tablets(all replicas), as reported by the exported  `memstats.HeapAlloc` metric, jumped from a steady state of about 18MB to a peak of 2GB. Even after stopping the batch job, memory usage has only dropped to about 1.2GB and has remained there. Note that in the steady state, these shards get about 100 queries per second, all writes(inserts/updates/deletes).

#### Reproduction Steps

1. Schema for this table:

```sql
CREATE TABLE `tbl` (
  `prim_key_1` bigint(20) unsigned NOT NULL,
  `prim_key_2` bigint(20) unsigned NOT NULL,
  `prim_key_3` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `field1` varchar(255) NOT NULL,
  `field2` varchar(255) NOT NULL,
  `prim_key_4` int(10) unsigned NOT NULL,
  `field3` int(10) unsigned NOT NULL,
  `field4` int(10) unsigned NOT NULL,
  PRIMARY KEY (`prim_key_2`,`prim_key_1`,`prim_key_3`,`prim_key_4`),
  KEY `key1` (`prim_key_1`,`prim_key_2`,`prim_key_4`),
  KEY `key2` (`prim_key_1`,`prim_key_4`),
  KEY `key3` (`prim_key_1`,`prim_key_2`,`prim_key_3`,`prim_key_4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED
```

2. VSchema:

```json
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    }
  },
  "tables": {
    "tbl": {
      "columnVindexes": [
        {
          "column": "prim_key_2",
          "name": "hash"
        }
      ]
    }
  }
}
```

3. Query pattern: repeated primary key ordered point queries similar to the below, with a maximum of 1000 records per query:

```sql
select * from tbl where 
(prim_key_1 = $val1 AND prim_key_2 = $val2 AND prim_key_3=$val3 AND prim_key_4=$val4) OR 
(prim_key_1 = $val5 AND prim_key_2 = $val6 AND prim_key_3=$val7 AND prim_key_4=$val8) OR 
(prim_key_1 = $val9 AND prim_key_2 = $val10 AND prim_key_3=$val11 AND prim_key_4=$val12) OR 
(prim_key_1 = $val13 AND prim_key_2 = $val14 AND prim_key_3=$val15 AND prim_key_4=$val16) OR
-- up to 1000 OR statements
```

4. watch `HeapAlloc` grow

```sh
 watch -d -n 2 "curl -s localhost:15000/debug/vars | jq '.memstats|.HeapAlloc'"
```

#### Binary version

Commit: https://github.com/tinyspeck/vitess/commit/f6b9ff4
```sh
$ vtgate --version
Version: f6b9ff4 (Git branch 'HEAD') built on Wed Apr  3 12:01:32 PDT 2019 by XXX using go1.12.1 linux/amd64
```

**Comment by brirams** [comment]
after cutting the size of these queries down(1000 -> 100), we saw heap usage drop precipitously. closing out for now.

**Comment by Irishemma** [comment]
> after cutting the size of these queries down(1000 -> 100), we saw heap usage drop precipitously. closing out for now.

The large amount of heap alloc is caused by  plan LRU cache. The SELECT  repeated primary key ordered point queries will be distributed to different shard with non-repeatable query plan, which need a lot of memory. Cutting down the vttablet parameter "-queryserver-config-query-cache-size" is effective.
