### ISSUE TITLE
Interrupted Restores Fail/Please Sanity Check Restores 

### ISSUE THREAD

**Issue by msolters** [vitessio/vitess#4821]
#### Overview of the Issue

Vttablets running with the `-restore_from_backup` flag will check the disk on boot, and if it is completely empty, they attempt to find a backup to restore from.  If this process is interrupted for any reason (VM failure, pod rescheduled, network failure, whatever) the disk ends up in an incomplete state: some of the backup has been restored, but not all of it.  At this point, the tablet becomes unusable without manual intervention, which usually consists of manually wiping the disk and restarting the restore.

It would be ideal if there were some kind of basic sanity checking with respect to backup restores: checking that the size of the data on disk matches what we expect from the bucket, or perhaps actually hashing the data in the bucket and comparing it to the hash of the data on the disk.  If the restore doesn't match, the disk should be wiped and the restore started over.

#### Reproduction Steps

1.  Create a shard `0` in a keyspace `ks`.  Create a backup with e.g. `./kvtctl.sh BackupShard ks/0`.
1.  Destroy the shard once the backup is complete, and then recreate it with the `-restore_from_backup` flag on the vttablets.
1.  Delete one of the pods while its vttablet logs report it is `copying all files` during the restore.
1.  When the tablet restarts, it will skip restoring because it finds there is _some_ data on disk.  However, the data is incomplete and typically the tablet gets stuck in a loop where it attempts to start replication, which fails, because so much of the data directory is missing.

Depending on when the restore process is interrupted, and how much write traffic the master is receiving, the failure mode varies.  I have seen everything from the tablet never becoming available because replication is fundamentally broken due to missing data dir files, to the tablet joining replication but literally missing data which only becomes evident when running a query.

#### Binary version
I first noticed this problem with a build from the master branch around Dec 2018, and as of a build from 4/16/2019 it is ongoing.

#### Operating system and Environment details

We are on COS nodes in GKE 1.11.6

#### Log Fragments

If the restore is interrupted early on, the vttablet container for the tablet enters a "replication start loop" like so:

```
I0417 19:51:29.802283       1 replication_reporter.go:69] Slave is stopped. Trying to reconnect to master...
I0417 19:51:29.805436       1 locks.go:361] Locking shard keyspace/e8- for action repairReplication to app-0666719400 as parent)
I0417 19:51:29.814082       1 query.go:73] exec CHANGE MASTER TO
  MASTER_HOST = 'app-keyspace-xe8-x-replica-0.vttablet',
  MASTER_PORT = 3306,
  MASTER_USER = 'vt_repl',
  MASTER_PASSWORD = '',
  MASTER_CONNECT_RETRY = 10,
  MASTER_AUTO_POSITION = 1
I0417 19:51:29.975446       1 query.go:73] exec START SLAVE
I0417 19:51:29.975805       1 locks.go:400] Unlocking shard keyspace/e8- for action repairReplication to app-0666719400 as parent) with error ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE
I0417 19:51:29.981451       1 replication_reporter.go:72] Failed to reconnect to master: ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE
I0417 19:51:29.982460       1 tabletserver.go:357] TabletServer state: NOT_SERVING (Not Connected) -> NOT_SERVING (Transitioning)
I0417 19:51:30.102972       1 engine.go:134] Time taken to load the schema: 92ns
I0417 19:51:30.103035       1 tx_engine.go:423] No grace period specified: performing normal wait.
I0417 19:51:30.103056       1 tabletserver.go:357] TabletServer state: NOT_SERVING (Transitioning) -> NOT_SERVING (Not Connected)
I0417 19:51:35.104567       1 replication_reporter.go:69] Slave is stopped. Trying to reconnect to master...
```

And this loops infinitely, leaving the tablet in an unhealthy state.  The only fix is to manually wipe the disk so that restore starts over entirely.

**Comment by derekperkins** [comment]
We have seen this fairly often too.

**Comment by deepthi** [comment]
Mark, are you using persistent disk or ephemeral storage?
