### ISSUE TITLE
Control unqualified routing when table names are reused across keyspaces

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4838]
Being able to configure a table in multiple vschemas while still marking one as default/dominant has two uses:

1) helps with migrating legacy databases
2) helps avoid outages due to the current default behavior for "dual", which is to route the lexicographically earliest keyspace:

https://github.com/vitessio/vitess/blob/7a201e3f042b4eab93ef8540f1ef7e405c7b95be/go/vt/vtgate/vindexes/vschema.go#L311

That behavior for "dual" is quite problematic if you bring up a new keyspace, because mysql-protocol clients like connector-j, sqlalchemy, or even the standard mysql command line client often do selects from dual immediately after connecting to check session properties.

When you bring up tablets for a new keyspace, you might incorrectly assume that you have some time to get them healthy by fixing sql modes, user grants, etc., and that existing traffic won't be impacted.

If anyone reading this issue is dealing with that problem, `vtctl RemoveKeyspace -recursive` + `vtctl RebuildVSchemaGraph` might help you restore serving.

**Comment by sougou** [comment]
#4833 will give you an easy work-around. If you created a routing rule that mapped `dual` to [`fixed_keyspace.dual`], then the creation of new keyspaces won't affect that fixed route.
