### ISSUE TITLE
Fails to reconnect to ZK on ZK restarts

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#4866]
The reason is that the DNS name is resolved to IP addresses at startup, when DNS changes the IP addresses are not re-resolved. So after a ZK restart on e.g. Kubernetes when the IP address changes then Vitess isn't able to reconnect without a restart.

**Comment by tirsen** [comment]
I'm pretty sure this was fixed by @deepthi ?

**Comment by deepthi** [comment]
No it was fixed by @tirsen :)

**Comment by tirsen** [comment]
Oh I forgot about that. Must be getting old. :-)
