### ISSUE TITLE
INFORMATION_SCHEMA join query doesn't work correctly

### ISSUE THREAD

**Issue by Santiclause** [vitessio/vitess#4885]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

A query against INFORMATION_SCHEMA that joins COLUMNS with itself fails, likely because it aliases the tables as `C1` and `C2`, and the planner probably interprets the join incorrectly and turns it into a cross-shard join or something, idk.

#### Reproduction Steps

Try to run this query: 
```
SELECT TABLE_NAME FROM information_schema.columns C1 JOIN information_schema.columns C2 USING(TABLE_SCHEMA, TABLE_NAME) WHERE C1.COLUMN_NAME = 'whoID' AND C2.COLUMN_NAME = 'whoType';
```

It fails against sharded and unsharded keyspaces alike, but it works if you specify a single shard to run it against (even for unsharded keyspaces, where there's only one!)

#### Binary version

```sh
$ vtgate --version
Version: 83c0faa98 (Git branch 'HEAD') built on Wed May 22 20:48:29 UTC 2019 by root@8be1335badd7 using go1.11.8 linux/amd64
```

#### Operating system and Environment details

It's all in kubbernetties

#### Log Fragments

```
mysql> use app;
Database changed
mysql> SELECT TABLE_NAME FROM information_schema.columns C1 JOIN information_schema.columns C2 USING(TABLE_SCHEMA, TABLE_NAME) WHERE C1.COLUMN_NAME = 'whoID' AND C2.COLUMN_NAME = 'whoType';
ERROR 1105 (HY000): vtgate: http://vtgate-app-6dbcd9986f-bkhrh:15001/: symbol C1.COLUMN_NAME not found
mysql> use app:-08;
Database changed
mysql> SELECT TABLE_NAME FROM information_schema.columns C1 JOIN information_schema.columns C2 USING(TABLE_SCHEMA, TABLE_NAME) WHERE C1.COLUMN_NAME = 'whoID' AND C2.COLUMN_NAME = 'whoType';
+------------+
| TABLE_NAME |
+------------+
| foo        |
| bar        |
+------------+
2 rows in set (0.06 sec)
```

**Comment by harshit-gangal** [comment]
Fixed it in https://github.com/vitessio/vitess/pull/6638/commits/427ea7891cd4e472e637bafb23879ea8b5132ee1
