### ISSUE TITLE
Helm chart validation "nil" error

### ISSUE THREAD

**Issue by jpds** [vitessio/vitess#4908]
#### Overview of the Issue

In Helm 2.14 the schema validation errors not is silenced anymore (helm/helm#5576). The Kubernetes quickstart for Vitess fails with the error below on initial cluster setup.

#### Reproduction Steps

1. Download Helm 2.14
2. Install Tiller 2.14 into cluster
3. Run initial cluster step:

```
$ helm install ../../helm/vitess -f 101_initial_cluster.yaml
Error: validation failed: error validating "": error validating data: [unknown object type "nil" in ConfigMap.data.backup.backup_storage_implementation, unknown object type "nil" in ConfigMap.data.backup.gcs_backup_storage_bucket, unknown obje
ct type "nil" in ConfigMap.data.backup.gcs_backup_storage_root, unknown object type "nil" in ConfigMap.data.backup.s3_backup_aws_region, unknown object type "nil" in ConfigMap.data.backup.s3_backup_server_side_encryption, unknown object type "
nil" in ConfigMap.data.backup.s3_backup_storage_bucket, unknown object type "nil" in ConfigMap.data.backup.s3_backup_storage_root]
```

**Comment by addshore** [comment]
I am also seeing this while trying to follow https://vitess.io/docs/get-started/kubernetes/ with helm 2.14.0

```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**Comment by addshore** [comment]
For anyone wanting to work around this for now see https://github.com/helm/helm/issues/5750#issuecomment-493471454

It looks like when helm 2.14.1 lands this will no longer be an issue?

**Comment by stevenkitter** [comment]
anyone can solve this problem?

**Comment by stevenkitter** [comment]
```helm init --upgrade --service-account tiller```
solved my problem

**Comment by GuptaManan100** [comment]
Closing this issue. Reopen in case of new updates.
