### ISSUE TITLE
can make vschema transparent to user?

### ISSUE THREAD

**Issue by klkyy2020** [vitessio/vitess#4910]
#### Feature Description

can we remove the vschema.json and let create table statement update it inside the system?

#### Use Case(s)

for example

create table t(id int primary key,  col1 int, col2 int) shard by BINARY_MD5(col1);

this statement will create a table with shard key col1 using binary_md5 algorithm

**Comment by sougou** [comment]
Work is already underway on this. You can already do something like what you described as vitess DDL. It's on my TODO list to document this.

**Comment by GuptaManan100** [comment]
This has been implemented. Please open a new issue if further changes are to be requested.
