### ISSUE TITLE
Setting session variables doesn't work in Transactions

### ISSUE THREAD

**Issue by rajeshkumart78** [vitessio/vitess#4915]
Session variables assignment for "last_insert_id()" are failing with this error.

mysql> set @user_id=LAST_INSERT_ID();
ERROR 1105 (HY000): vtgate: http://vtgate-freshworks-helpkit-000000000:15001/: invalid syntax: last_insert_id()

NOTE: this happens even for unsharded keyspaces.  For unsharded keyspaces, these session variables can be passed through to the corresponding vttablets directly?

**Comment by dkhenry** [comment]
@saifalharthi please review

**Comment by saifalharthi** [comment]
After looking into it I found out that it was not a parser issue. This would require some further work to find a good solution.

**Comment by rajeshkumarblr** [comment]
Hello,

  The last_insert_id() is working for me within a transaction for an AUTO_INCREMENT column with primary key.

======================================================================


mysql> create table test2(id int PRIMARY KEY NOT NULL AUTO_INCREMENT, name varchar(64));
Query OK, 0 rows affected (0.02 sec)
mysql> insert into test2 (name) values ("rajesh");
Query OK, 1 row affected (0.00 sec)
mysql> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)
mysql> insert into test2 (name) values ("suresh");
Query OK, 1 row affected (0.00 sec)
mysql> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                0 |
+------------------+
1 row in set (0.01 sec)
mysql> select * from test2;
+----+--------+
| id | name   |
+----+--------+
|  1 | rajesh |
|  2 | suresh |
+----+--------+
2 rows in set (0.00 sec)
mysql> insert into test2 (name) values ("suresh2");
Query OK, 1 row affected (0.01 sec)
mysql> select last_insert_id();
+------------------+
| last_insert_id() |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)


======================================================================

**Comment by saifalharthi** [comment]
Yes, that works. The error happenes when you try to `set` session variable.

**Comment by dkhenry** [comment]
I think this error is much like what we are seeing in #5002. The result of the SET expression is a SqlQuery not a statement. That is not handled in the SET handler.

**Comment by harshit-gangal** [comment]
This works in 7.0 and 8.0 releases.
