### ISSUE TITLE
"vttablet --help" shows incorrect command line flags

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/vitess#4932]
#### Overview of the Issue

The output from `vttablet --help` includes erroneous flags intended for other apps, e.g., `vtgate`

#### Reproduction Steps
This command `vttablet --help`
provides output including the following option flags and info that are not operable with this app:
```
  -mysql_auth_server_static_file string
        JSON File to read the users/passwords from.
  -mysql_auth_server_static_string string
        JSON representation of the users/passwords config.
  -mysql_auth_static_reload_interval duration
        Ticker to reload credentials
```

All three of `vgate`, `vttablet` and `vtctld`produce this same output.

**Comment by deepthi** [comment]
these are coming from go/mysql/auth_server_static.go

**Comment by rasikakale** [comment]
I am currently working on this.
I had to move the files within the mysql package to different packages, and create new packages as well to avoid circular dependencies of package names.

**Comment by tomkrouper** [comment]
There are other flags. `-discovery_low_replication_lag` that I found today that appears to be for vtgate only but shows up for vttablet's `--help`.

**Comment by deepthi** [comment]
The original issue is now fixed. However `-discovery_low_replication_lag` has not been fixed yet. It will be fixed when we complete #10751

**Comment by ajm188** [comment]
We're getting there!! Slowly, but surely, we'll get there 😂

**Comment by deepthi** [comment]
This is finally done 🎉
