### ISSUE TITLE
Unable to begin a transaction after setting workload to "olap"

### ISSUE THREAD

**Issue by skyler** [vitessio/vitess#4939]
#### Overview of the Issue
Can't `begin` after `set workload="olap"`.

After running `set workload="olap"`, a query to `begin` a transaction fails. However, a query to `begin` a transaction after `set workload="oltp"` succeeds as expected.

#### Reproduction Steps

Fresh connection, run `set workload="olap"` followed by `begin` fails:

```sql
mysql> set workload="olap";
Query OK, 0 rows affected (0.03 sec)

mysql> begin;
ERROR 1105 (HY000): vtgate: http://vtgate-app-fdb5585c5-w7fh6:15001/: unsupported construct: begin
```

However, `begin` works for the `oltp` workload mode:

Fresh connection, `begin` without `set workload="olap"` works successfully as expected:
```sql
mysql> begin;
Query OK, 0 rows affected (0.03 sec)
```

Fresh connection, run `set workload="oltp"` followed by `begin`  works successfully as expected:

```sql
mysql> set workload="oltp";
Query OK, 0 rows affected (0.03 sec)

mysql> begin;
Query OK, 0 rows affected (0.03 sec)
```

#### Binary version

```sh
Version:  (Git branch '') built on Tue Jun 18 16:19:23 UTC 2019 by root@7291704d265d using go1.11.8 linux/amd64
```

This is our own build but we are more or less up to date with `vitessio/master`.

#### Operating system and Environment details

- Operating system (output of `cat /etc/os-release`): 

```
Debian GNU/Linux 9 (stretch) (OS of the container) running on a Container-Optimized OS from Google node running Kubernetes 1.12.8.
```

- Kernel version (output of `uname -sr`): `Linux 4.14.119+` (OS of the container)
- Architecture (output of `uname -m`): `x86_64`

#### Log Fragments

vtgate:
```
E0619 16:38:47.379178       1 vtgate.go:1096] StreamExecute: unsupported construct: begin, request: map[BindVariables:map[] Session:autocommit:true options:<included_fields:ALL workload:OLAP > Sql:begin]
```

**Comment by makmanalp** [comment]
dupe https://github.com/vitessio/vitess/issues/3977
