### ISSUE TITLE
Multiple master in the same shard

### ISSUE THREAD

**Issue by srikantmuppalla** [vitessio/vitess#4957]
We found multiple master in the same shard And got application errors saying DB is read-only. Need to know what might be the possible root cause of the issue and how to avould this kind of issue in future.

**Comment by deepthi** [comment]
Can you post the relevant logs? from the vttablets and vtgate and mysql.

**Comment by sougou** [comment]
Multiple master is possible when the reparent process is not able to reach the old master to demote it. I've changed this bug to a Documentation because we should write a playbook on how to get out of this situation.

**Comment by sougou** [comment]
This problem should be fixed by the recent changes in how we handle mastership.
