### ISSUE TITLE
select from table which has `consistent_lookup_unique multi-column vindexes` returns  error or wrong results.

### ISSUE THREAD

**Issue by DeanZhou9** [vitessio/vitess#4967]
#### Overview of the Issue

select from table which has `consistent_lookup_unique multi-column vindexes` returns  error or wrong results.

> `type (int)` and `account (varchar)` are columns used by consistent_lookup_unique

1. `select * from accounts where type=0;` throws `paramsSelectEqual: Lookup.Map: unexpected multiple results` error;
2. `select * from accounts where type=0 and account='a1';` throws `paramsSelectEqual: Lookup.Map: unexpected multiple results` error;
3. `select * from accounts where account=0;` return all rows which is not expected.
4. `select * from accounts where account='a1';` return correct rows;

#### Reproduction Steps

Two keyspaces, one is called `lookup` unshared, and another is called `data` shard with `-80 and 80-`.

1. Deploy the following `vschema` to `lookup` keyspace:

    ```javascript
    {
        "sharded": false,
        "tables": {
            "accounts_seq": {
                "type": "sequence"
            },
            "lookup_type_account_uid_idx": {}
        }
    }
    ```
    
2. Deploy the following `schema` to  `lookup` keyspace:

    ```sql
    # for sequence 
    create table accounts_seq(id int, next_id bigint, cache bigint, primary key(id)) comment 'vitess_sequence';
    insert into accounts_seq(id, next_id, cache) values(0, 1000, 100);
    
    # for consistent_lookup_unique
    create table lookup_type_account_uid_idx(type int(10) unsigned, account varchar(255), keyspace_id binary(20), primary key(type, account));
    ```

3. Deploy the following `vschema` to `data` keyspace:

    ```javascript
    {
        "sharded": true,
        "vindexes": {
            "hash": {
                "type": "hash"
            },
            "lookup_type_account_uid_idx": {
                "type": "consistent_lookup_unique",
                "params": {
                    "table": "lookup_type_account_uid_idx",
                    "from": "type,account",
                    "to": "keyspace_id"
                },
                "owner": "accounts"
            }
        },
        "tables": {
            "accounts": {
                "column_vindexes": [
                    {
                        "column": "id",
                        "name": "hash"
                    },
                    {
                        "columns": ["type", "account"],
                        "name": "lookup_type_account_uid_idx"
                    }
                ],
                "auto_increment": {
                    "column": "id",
                    "sequence": "accounts_seq"
                }
            }
        }
    }
    ```
    
4. Deploy the following `schema` to  `data` keyspace:

    ```javascript
    CREATE TABLE `accounts` (
      `id` bigint(20) unsigned,
      `type` int(10) unsigned NOT NULL DEFAULT '0',
      `account` varchar(255) NOT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `accounts_type_account_unique` (`type`,`account`)
    ) ENGINE=InnoDB;
    ```
    
5. Insert test data

    ```javascript
    INSERT INTO accounts (type, account) values (0, 'a1');
    INSERT INTO accounts (type, account) values (0, 'a2');
    INSERT INTO accounts (type, account) values (1, 'a1');
    INSERT INTO accounts (type, account) values (1, 'a2');
    ```

6. Run `SELECT` and see error results

    ```
    mysql> select * from accounts where type=0;
    ERROR 1105 (HY000): vtgate: http://cb8c7a7667df:8080/: paramsSelectEqual: Lookup.Map: unexpected multiple results from vindex lookup_type_account_uid_idx: INT64(0)
    
    mysql> select * from accounts where type=0 and account='a1';
    ERROR 1105 (HY000): vtgate: http://cb8c7a7667df:8080/: paramsSelectEqual: Lookup.Map: unexpected multiple results from vindex lookup_type_account_uid_idx: INT64(0)
    
    mysql> select * from accounts where account=0;
    +------+------+---------+
    | id   | type | account |
    +------+------+---------+
    | 1001 |    0 | a2      |
    | 1003 |    1 | a2      |
    | 1000 |    0 | a1      |
    | 1002 |    1 | a1      |
    +------+------+---------+
    4 rows in set (0.01 sec)
    
    mysql> select * from accounts where account='a1';
    +------+------+---------+
    | id   | type | account |
    +------+------+---------+
    | 1000 |    0 | a1      |
    | 1002 |    1 | a1      |
    +------+------+---------+
    2 rows in set (0.02 sec)
    ```

#### Binary version
I'm using docker vitess/base latest version

```sh
Version: dcd88d09e (Git branch 'master') built on Wed Jun 26 21:07:07 UTC 2019 by root@d4b9a5e4fbad using go1.11.8 linux/amd64
```

**Comment by sougou** [comment]
I think you've misunderstood the capabilities of a lookup vindex. At this time, all vindexes are single column. In your above case, you have to choose either account or type to be the column on which the lookup is indexed. The additional columns in a lookup vindex are only meant for establishing ownership.

For example, if you created a lookup vindex on `account`, it's possible that you have multiple rows in the main table that have the same `account` value. In this case, you can store `type` as an additional value in order to allow two rows of the same `account` value to exist in the lookup table.

I hope this clarifies your question. Let me know if this doesn't make sense.

**Comment by DeanZhou9** [comment]
Hello @sougou, thanks for you quick reply! I'am new to vitess and trying to make composite unique key work. 

> `In your above case, you have to choose either account or type to be the column on which the lookup is indexed.`

Did you mean if I set `"from": "type,account"`, `type` is chosen for indexing lookup and `account` is for  establishing ownership?

I thought `select * from accounts where type=0 and account='a1';` should return the row `where id=1000`, because `type=0 and account='a1'` is unique in lookup table.

**Comment by sougou** [comment]
> Did you mean if I set `"from": "type,account"`, `type` is chosen for indexing lookup and `account` is for establishing ownership?

Right. To choose account instead, you specify: `"account,type"`.

> I thought `select * from accounts where type=0 and account='a1';` should return the row `where id=1000`, because `type=0 and account='a1'` is unique in lookup table.

For a sharded system, lookup indexes don't have to be exact like they are within a database. As long as one of the columns has high cardinality, you can choose that as the only key. In your case, account is likely the one you should choose, and that will work as efficiently, because vitess will use the lookup to send the query to the right shard, and then mysql will use the correct index to efficiently find the row using all the parts of the where clause.

**Comment by DeanZhou9** [comment]
I specified `"from": "account,type"` . 

When I input `select * from accounts where account='a1' and type=0;`, vtgate throws error `paramsSelectEqual: Lookup.Map: unexpected multiple results from vindex lookup_type_account_uid_idx: VARBINARY("a1")`

But, if I use `consistent_lookup` instead of `consistent_lookup_unique`, everything is working!

It seems that I misunderstood how `consistent_lookup_unique` works. I thought the composite unique columns should use `consistent_lookup_unique`. But, in fact, it requires that the first column must be unique.
