### ISSUE TITLE
StreamExecute doesn't support offsets with limits

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4972]
Filing this as a bug instead of a feature request because `Execute` does support limits with offsets.

It's not immediately clear that there's any specific reason why `StreamExecute` shouldn't also. Probably just an inconsistency in the code?

**Comment by dweitzman** [comment]
Relevant code: https://github.com/vitessio/vitess/search?q="offset+not+supported+for+stream+execute+queries"

**Comment by harshit-gangal** [comment]
Supported via #6655
