### ISSUE TITLE
Backups using -allow_master never completes with custom vreplication

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4973]
I had a replica get out of sync, so I needed to take a backup from master and restore, a process that typically takes ~10 minutes for this tablet. I ran `vtctlclient -action_timeout="4h0m0s" -server localhost:15999 Backup -allow_master cell-uid` multiple times, increasing the timeout each attempt, and that timed out at 4 hours. I had ~30 vreplication streams live running to the master. After deleting all the vreplication rows, the backup succeeded normally.

**Comment by derekperkins** [comment]
cc @deepthi

**Comment by sougou** [comment]
Was this to the target masters?

**Comment by derekperkins** [comment]
Yes, this was the target master.

**Comment by deepthi** [comment]
Do you have the logs? It will be useful to know where it got stuck.

**Comment by sougou** [comment]
I think we just have to stop vreplication.Engine before backup and restart it afterwards.

**Comment by derekperkins** [comment]
It looks to be infinitely looping here

![image](https://user-images.githubusercontent.com/3588778/60539853-e91f9a00-9cca-11e9-9959-161126baf0ba.png)

**Comment by deepthi** [comment]
> I think we just have to stop vreplication.Engine before backup and restart it afterwards.

The code to do this is already in place and has been around for a while: https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletmanager/state_change.go#L363

@derekperkins can you post an update if you run into this again?

**Comment by derekperkins** [comment]
We can go ahead and close this issue since you fixed it. We rarely do backups from master, but if we hit this again, I'll post here.
