### ISSUE TITLE
Insert ignore for vindexes without autocommit appear incorrect.

### ISSUE THREAD

**Issue by mpawliszyn** [vitessio/vitess#4974]
I created a test that proves this.
https://github.com/mpawliszyn/vitess/commit/8202a119f4c59f59b3a04755c7ad35d7bb4d802e

**Comment by sougou** [comment]
Same as this? https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/endtoend/lookup_test.go#L223

**Comment by mpawliszyn** [comment]
No that one uses an autocommit vindex so it works. I'm pretty sure the problem is that the insert ignore verify only works when the insert into the vindex has been committed. I suspect we aren't sending the right transaction id during that verify

**Comment by sougou** [comment]
Ahh. I see. Looks like I tested the wrong table. Let me try this one out.

**Comment by sougou** [comment]
Ok. I believe the test for t2 is still legit, and it would have failed without the ordering fix in that PR.
However, `insert ignore` does not work for consistent lookups. This is a different bug in the consistent lookup itself?

**Comment by mpawliszyn** [comment]
Yes t2 is absolutely legit and it fixes the problem we were having. We only use autocommit vindexes. I just found this bug while I was working on this so I wanted to track it somewhere. 

Note that if you try the insert ignore twice it works because in the first call the vindex is inserted so when the second call is made the verify works.

**Comment by sougou** [comment]
Yeah. I found the problem. The fix may be tricky because Verify is used from two different code paths (one of owne, the other unowned), and may have to use different commit order directives. I have to think of a way to do this without changing the Vindex API.

**Comment by mpawliszyn** [comment]
We are in no rush for a fix for this. I'm glad you found the problem so
quickly though.
