### ISSUE TITLE
Add recent presentation to resources section

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5008]
#### Feature Description

We should add recent presentations from the Slack Vitess meetup to: https://vitess.io/docs/resources/presentations/

Also: Sugu's CNCF webinar: https://www.cncf.io/event/cncf-webinar-series-vitess-running-sharded-mysql-on-kubernetes/

**Comment by deepthi** [comment]
Isn't this a website issue and as such belongs in the vitessio/website repo?
Also how is this different from https://github.com/vitessio/website/issues/213?

**Comment by morgo** [comment]
You are right. Closing this issue.
