### ISSUE TITLE
Golang modules does not like short version tags

### ISSUE THREAD

**Issue by physcat** [vitessio/vitess#5019]
Please add the patch version number to the Major releases tags in git. i.e.
for v3.0 add v3.0.0

Golang modules uses Semantic Versioning (https://semver.org/) to find versions.

When a developer does build or a get, they will get v2.1.1 as go does not recognise v3.0
```bash
$ go get -u vitess.io/vitess
$ grep vitess go.mod
	vitess.io/vitess v2.1.1+incompatible
```
This will result in errors such as:
```bash
./main.go:222:30: not enough arguments in call to vitessdriver.Open
	have (string, string)
	want (string, string, string, time.Duration)
```
The full list of tags that go modules recognises are:
```bash
$ go list -m -versions vitess.io/vitess
vitess.io/vitess v2.0.0-alpha1+incompatible v2.0.0-alpha2+incompatible v2.0.0-alpha3+incompatible v2.0.0-alpha4+incompatible v2.0.0-alpha5+incompatible v2.0.0-beta.1+incompatible v2.0.0-beta.2+incompatible v2.0.0-rc.1+incompatible v2.0.0-rc.2+incompatible v2.0.0+incompatible v2.1.0-alpha.1+incompatible v2.1.0-alpha.2+incompatible v2.1.0-rc.1+incompatible v2.1.0+incompatible v2.1.1+incompatible v2.2.0-rc.1+incompatible v3.0.0-rc.1+incompatible v3.0.0-rc.2+incompatible v3.0.0-rc.3+incompatible
```
Go will not install pre-release version by default, but since v3.0 and v3.0.0-rc3 are the same, the developer can do either:
    $ go get vitess.io/vitess@v3.0
or
    $ go get -u vitess.io/vitess@4f192d1
both will work, but resulting in the apparent dependency on a pre-release package:
```bash
$ grep vitess go.mod
	vitess.io/vitess v3.0.0-rc.3+incompatible
```

**Comment by morgo** [comment]
The Vitess 4.0 release was tagged as v4.0.0, which should address this. I am going to close this issue for now, but please let me know if it doesn't fix it.

**Comment by kirs** [comment]
I think this is still an issue.

```
go list -m -versions vitess.io/vitess
vitess.io/vitess v2.0.0-alpha1+incompatible v2.0.0-alpha2+incompatible v2.0.0-alpha3+incompatible v2.0.0-alpha4+incompatible v2.0.0-alpha5+incompatible v2.0.0-beta.1+incompatible v2.0.0-beta.2+incompatible v2.0.0-rc.1+incompatible v2.0.0-rc.2+incompatible v2.0.0+incompatible v2.1.0-alpha.1+incompatible v2.1.0-alpha.2+incompatible v2.1.0-rc.1+incompatible v2.1.0+incompatible v2.1.1+incompatible v2.2.0-rc.1+incompatible v3.0.0-rc.1+incompatible v3.0.0-rc.2+incompatible v3.0.0-rc.3+incompatible
```

There's no 4.0.0 or 4.0.0 in that list.

**Comment by physcat** [comment]
Yes, It looks like the modules are a bit stricter with major versions than I understood.

With the major version the import path needs updating for all the clients.

e.g.
```diff
- import "vitess.io/vitess/go/vt/vitessdriver"
+ import "vitess.io/vitess/v4/go/vt/vitessdriver"
```

I think this needs an update of ```go.mod```
```diff
- module vitess.io/vitess
+ module vitess.io/vitess/v4

go 1.12

require (
```
But I've not been able to test this yet.

This will explain the current errors I see:
```bash
$ go list -m -versions vitess.io/vitess/v4
go list -m: module vitess.io/vitess/v4: reading https://proxy.golang.org/vitess.io/vitess/v4/@v/list: 410 Gone
$ export GOPROXY=
$ go list -m -versions vitess.io/vitess/v4
go: finding vitess.io/vitess/v4 v4.0.1
go list -m: vitess.io/vitess/v4@v4.0.1: invalid version: go.mod has non-.../v4 module path "vitess.io/vitess" (and .../v4/go.mod does not exist) at revision v4.0.1
```

**Comment by scbizu** [comment]
Can someone please reopen this issue ? IMO this issue is not fixed whether you taged v4.0 or v4.0.0 , as @physcat said , module name `github.com/vitessio/vitess` should be modified  to the  `github.com/vitessio/vitess/v4` in order to remove the `incompatible` , or create the v4 directory to provide ` */v4` module as [gax-go](https://github.com/googleapis/gax-go) did. Maybe #5758  is the same issue ? 🤔

Refers to https://blog.golang.org/v2-go-modules

**Comment by sougou** [comment]
Reopening as requested.

**Comment by gordonyoon** [comment]
Ran into this issue. For anyone else who's looking, note that you can get packages by commit hash:

`go get -u vitess.io/vitess@7e09d0c` (for v8.0.0)

**Comment by sougou** [comment]
The golang modules approach will not work for the vitess versioning scheme. The work around I tried works fine, which is to stay under v1.0. I tagged the v7 release as https://github.com/vitessio/vitess/releases/tag/v0.7.0 and that worked. So, we should do the same for v8 and tag it as v0.8.0. Tagging @askdba.

**Comment by aquarapid** [comment]
Since we have the workaround in place, and we're consistently generating the v0.xx.x == Vitess vxx.x tags now when we do releases, I'm going to close this.

```
$ go list -m -versions vitess.io/vitess | head -c92
vitess.io/vitess v0.7.0 v0.8.0 v0.9.0 v0.9.1 v0.9.2 v0.10.0 v0.10.1 v0.10.2 v0.11.0 v0.11.1
```
