### ISSUE TITLE
Read only vtgate

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#5030]
#### Feature Description

We would like an option on vtgate that disallows any read-write transactions or DML or whatever is the easiest. Regardless of which tablet type is used. Something similar to the `read_only` global in mysql.

#### Use Case(s)

We have an internal user role which allows read only access to our databases. This is used for product managers and customer support staff to access existing data without being able to modify it. We would like to support this user role but with full access to Vitess SQL through vtgate.

Only supporting REPLICA tablet types is not good enough as some of these Vitess clusters do not actually have any REPLICA tablets. Also, there is no way to enforce REPLICA tablet types at the vtgate level since you can change tablet type using the `USE` command.

**Comment by sougou** [comment]
Table ACLs were built for this. Will those work?

**Comment by tirsen** [comment]
Yes it may very well solve this. Can you give a specific example of how I would say something like for a user called `read_only` I want to reads to all tables and writes to no tables?

**Comment by sougou** [comment]
Here's an example for read-only: https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/endtoend/main_test.go#L265, and you can look at `acl_test.go` in that same directory for the test.

You'll notice that the tables have wildcards. So, a single rule should be able to cover all tables.

YouTube had an internal plugin that would pull these values from the topo. We should implement a similar one. For now, you need a config file for every tablet.

**Comment by tirsen** [comment]
Yes I think you're right. It seems like this would solve things.

**Comment by tirsen** [comment]
Actually this feature is already supported with the `allowed_tablet_types` flag:
```
	topoproto.TabletTypeListVar(&allowedTabletTypes, "allowed_tablet_types", "Specifies the tablet types this vtgate is allowed to route queries to")
```
