### ISSUE TITLE
Select distinct returns null when a similar mysql query would return 0

### ISSUE THREAD

**Issue by mpawliszyn** [vitessio/vitess#5036]
#### Overview of the Issue
MySQL does the following
```
mysql> create table a(id int, val int, primary key(id));
Query OK, 0 rows affected (0.03 sec)

mysql> select * from a;
Empty set (0.00 sec)

mysql> select count(distinct id) from a where id = 0;
+--------------------+
| count(distinct id) |
+--------------------+
|                  0 |
+--------------------+
1 row in set (0.01 sec)
```
Whereas in vitess
```
select count(distinct id) from keyspace.anytable where id = 0
```
returns null. 

It didn't used to do this before:
https://github.com/vitessio/vitess/pull/4917/files#r293629548

**Comment by mpawliszyn** [comment]
Seems that for count it always returns 0 but for count it will return null.

`mysql> select * from testing;
+------+------+------+
| col1 | col2 | col3 |
+------+------+------+
| a    |    1 |    1 |
| a    |    1 |    2 |
| b    |    1 |    1 |
| c    |    3 |    1 |
| c    |    4 |    1 |
| d    | NULL |    1 |
| e    | NULL |    1 |
| e    |    1 |    1 |
| f    |    1 |    1 |
| f    | NULL |    1 |
| g    |    1 |    1 |
| g    |    1 |    1 |
| g    |    2 |    1 |
| g    |    3 |    1 |
| h    |    1 |    1 |
| h    |    2 |    1 |
| h    |    3 |    1 |
| h    |    4 |    1 |
| h    |    2 |    1 |
| i    |    3 |    1 |
| i    |    4 |    1 |
+------+------+------+
21 rows in set (0.00 sec)

mysql> select col1, sum(distinct col2), sum(col3) from testing;
+------+--------------------+-----------+
| col1 | sum(distinct col2) | sum(col3) |
+------+--------------------+-----------+
| a    |                 10 |        22 |
+------+--------------------+-----------+
1 row in set (0.00 sec)

mysql> select col1, sum(distinct col2), sum(col3) from testing group by col1;
+------+--------------------+-----------+
| col1 | sum(distinct col2) | sum(col3) |
+------+--------------------+-----------+
| a    |                  1 |         3 |
| b    |                  1 |         1 |
| c    |                  7 |         2 |
| d    |               NULL |         1 |
| e    |                  1 |         2 |
| f    |                  1 |         2 |
| g    |                  6 |         4 |
| h    |                 10 |         5 |
| i    |                  7 |         2 |
+------+--------------------+-----------+
9 rows in set (0.00 sec)

mysql> select col1, count(distinct col2), sum(col3) from testing group by col1;
+------+----------------------+-----------+
| col1 | count(distinct col2) | sum(col3) |
+------+----------------------+-----------+
| a    |                    1 |         3 |
| b    |                    1 |         1 |
| c    |                    2 |         2 |
| d    |                    0 |         1 |
| e    |                    1 |         2 |
| f    |                    1 |         2 |
| g    |                    3 |         4 |
| h    |                    4 |         5 |
| i    |                    2 |         2 |
+------+----------------------+-----------+
9 rows in set (0.01 sec)

mysql> select col1, sum(distinct col2), sum(col3) from testing group by col1;
+------+--------------------+-----------+
| col1 | sum(distinct col2) | sum(col3) |
+------+--------------------+-----------+
| a    |                  1 |         3 |
| b    |                  1 |         1 |
| c    |                  7 |         2 |
| d    |               NULL |         1 |
| e    |                  1 |         2 |
| f    |                  1 |         2 |
| g    |                  6 |         4 |
| h    |                 10 |         5 |
| i    |                  7 |         2 |
+------+--------------------+-----------+
9 rows in set (0.00 sec)

mysql> select * from a;
+----+------+
| id | val  |
+----+------+
|  1 | NULL |
|  2 |    2 |
+----+------+
2 rows in set (0.00 sec)

mysql> select id, count(val) from a;
+----+------------+
| id | count(val) |
+----+------------+
|  1 |          1 |
+----+------------+
1 row in set (0.00 sec)

mysql> select id, count(val) from a group by id;
+----+------------+
| id | count(val) |
+----+------------+
|  1 |          0 |
|  2 |          1 |
+----+------------+
2 rows in set (0.00 sec)

mysql> select id, count(distinct val) from a group by id;
+----+---------------------+
| id | count(distinct val) |
+----+---------------------+
|  1 |                   0 |
|  2 |                   1 |
+----+---------------------+
2 rows in set (0.00 sec)

mysql> select id, sum(distinct val) from a group by id;
+----+-------------------+
| id | sum(distinct val) |
+----+-------------------+
|  1 |              NULL |
|  2 |                 2 |
+----+-------------------+
2 rows in set (0.00 sec)`

**Comment by mpawliszyn** [comment]
Some more testing
```
mysql> truncate table a;
Query OK, 0 rows affected (0.05 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into a values (1,null);
Query OK, 1 row affected (0.06 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into a values (2,null);
Query OK, 1 row affected (0.02 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.00 sec)

mysql> insert into a values (3,7);
Query OK, 1 row affected (0.01 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   1 |                 7 |          1 |        7 |
+---------------------+-------------------+------------+----------+
1 row in set (0.00 sec)

mysql> insert into a values (4,11);
Query OK, 1 row affected (0.05 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   2 |                18 |          2 |       18 |
+---------------------+-------------------+------------+----------+
1 row in set (0.00 sec)

mysql> insert into a values (5,11);
Query OK, 1 row affected (0.02 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from a;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   2 |                18 |          3 |       29 |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)
```

**Comment by mpawliszyn** [comment]
Old version of Vitess pre Sougou's change
```
mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.02 sec)

mysql> insert into testing values (1,null);
ERROR 1105 (HY000): vtgate: http://170726918dcf:8080/: no column list
mysql> insert into testing (id, val) values (1,null);
Query OK, 1 row affected (0.01 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into testing (id, val) values (2,null);
Query OK, 1 row affected (0.01 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   0 |              NULL |          0 |     NULL |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into testing (id, val) values (3,7);
Query OK, 1 row affected (0.01 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   1 |                 7 |          1 |        7 |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into testing (id, val) values (4,11);
Query OK, 1 row affected (0.02 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   2 |                18 |          2 |       18 |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)

mysql> insert into testing (id, val) values (5,11);
Query OK, 1 row affected (0.01 sec)

mysql> select count(distinct val), sum(distinct val), count(val), sum(val) from testing;
+---------------------+-------------------+------------+----------+
| count(distinct val) | sum(distinct val) | count(val) | sum(val) |
+---------------------+-------------------+------------+----------+
|                   3 |                29 |          3 |       29 |
+---------------------+-------------------+------------+----------+
1 row in set (0.01 sec)
```

**Comment by dkhenry** [comment]
@saifalharthi

**Comment by saifalharthi** [comment]
@dkhenry This PR addresses this issue https://github.com/vitessio/vitess/pull/5097

**Comment by mpawliszyn** [comment]
Almost there is a follow up that fixes a bug in the bugfix :)
https://github.com/vitessio/vitess/pull/5121
I'm testing it now.

**Comment by mpawliszyn** [comment]
As soon as https://github.com/vitessio/vitess/pull/5121 has been merged then this can be closed
