### ISSUE TITLE
Website 404 - Consistent lookup vindexes

### ISSUE THREAD

**Issue by schneiderdba** [vitessio/vitess#5045]
#### Overview of the Issue

When I click on the "Consistent lookup vindexes" on the https://vitess.io/docs/schema-management/vschema/ page I receive a 404.

#### Reproduction Steps

In Chrome, navigate to https://vitess.io/docs/schema-management/vschema/ .  At the bottom of the "Predefined Vindexes" section, https://vitess.io/docs/schema-management/vschema/#predefined-vindexes , click on the link  "Consistent lookup vindexes" and you'll get a 404.

**Comment by morgo** [comment]
Thank you for the bug report! The correct link is: https://vitess.io/docs/schema-management/consistent-lookup/ I will work on a PR to fix shortly.

I also plan to do some research into finding a tool that discovers 404s, such as the Google Webmaster Tools. I don't believe it is currently being looked at.
