### ISSUE TITLE
Temporary my.cnf file for ApplySchema does not quote values

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#5060]
If your MySQL password contains characters like `#`, ApplySchema will fail to use the correct connection parameters. We need to escape and quote these values when writing the temporary my.cnf file in `defaultsExtraFile`:

https://github.com/vitessio/vitess/blob/7664d27b153c10606c1dac479587cfd3a26d4006/go/vt/mysqlctl/mysqld.go#L902-L917

**Comment by Gaurav-Punjabi** [comment]
Can I work on this issue?

**Comment by enisoc** [comment]
@Gaurav-Punjabi That would be great! Feel free to ask here if you have any questions on how to get started. You can also join slack.vitess.io if you haven't already.
