### ISSUE TITLE
XtraBackup: Log start and progress of backup

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#5063]
After starting a backup on a large database, the last thing I see logged is this:

```
I0808 21:08:56.605378 xtrabackupengine.go:118] Detected MySQL flavor: MySQL56
```

I can see from network traffic that it's uploading something, so I assume it's running. However, it would be nice to print to the logs that the backup is starting. Ideally we could also ask xtrabackup to print progress to stderr, capture it, and pipe it to our own logs.

cc @deepthi

**Comment by enisoc** [comment]
It looks like we do capture stderr, but we don't read it until after the whole upload is done.

**Comment by deepthi** [comment]
> It looks like we do capture stderr, but we don't read it until after the whole upload is done.

that is correct. we'll need to figure out a way to stream it.

**Comment by enisoc** [comment]
I have a prototype of streaming it. Just FYI so you don't duplicate effort.

**Comment by enisoc** [comment]
Also it turns out streaming stderr is necessary to allow long-running xtrabackup backups to complete. If you don't consume stderr, the write buffer fills up after a while and the xtrabackup process blocks. That was a fun one to diagnose...
