### ISSUE TITLE
repairReplication: attempt to fix 'Slave failed to initialize relay log info structure from the repository (errno 1872)'

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#5067]
There's an acknowledged [upstream MySQL bug](https://bugs.mysql.com/bug.php?id=83713) that affects at least 5.7 and 8.0 that shows this error when trying to start replication. We encounter it a few times per month.
`Slave failed to initialize relay log info structure from the repository (errno 1872)`

This has also been a cause for flaky tests in the past, so we may be experiencing it in CI more often than we know. #3237 

There is also a simple solution that should be 100% safe and works almost every time when we apply it manually.

    reset slave;
    start slave IO_THREAD;
    stop slave IO_THREAD;
    reset slave;
    start slave;

I'd like for `repairReplication` to attempt that when it encounters this specific error. If nobody is opposed, I'm happy to send in a PR.

@sjmudd has also experienced this issue and has commented on the linked MySQL bugs.

Here are the full Vitess logs surrounding the error. 

```
replication_reporter.go:69] Slave is stopped. Trying to reconnect to master...
locks.go:359] Locking shard domains/c0-e0 for action repairReplication to uscentral1-0498823900 as parent)
query.go:73] exec CHANGE MASTER TO ...
query.go:73] exec START SLAVE
locks.go:396] Unlocking shard domains/c0-e0 for action repairReplication to uscentral1-0498823900 as parent) with error ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE
replication_reporter.go:72] Failed to reconnect to master: ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE
```

**Comment by enisoc** [comment]
We've been hitting this too and have also been thinking about automating the workaround, so I'm in favor of this.

However, so far this simpler procedure from JFG in https://bugs.mysql.com/bug.php?id=92882 has been working for us:

```
stop slave;
reset slave;
start slave;
```

Do you know if the more complex one is necessary in some cases?

**Comment by derekperkins** [comment]
I don't know if the complex one is necessary. I just pulled it from the issue I linked.

**Comment by derekperkins** [comment]
Just had this happen to 5 more shards on an update. I verified that the easier 3 step fix worked.

**Comment by daboabou8** [comment]
Ouais derekperkins ça bien fonctionné pour moi aussi. @derekperkins.
God Job for the repport.

**Comment by arundevops1906** [comment]
Is there any way to avoid this? it's happening a lot in my slave.
