### ISSUE TITLE
Expression Implementation 

### ISSUE THREAD

**Issue by dkhenry** [vitessio/vitess#5098]
#### Feature Description
Implement the expressoin logic needed to match the MySQL Expression Engine. The following are expressions that need to be supported 

- [x] Addition `1 + 1` 
- [ ] Subtraction `1 - 1`
- [ ] Multiplication `1 * 1`
- [ ] Division `1 / 1` 

Long term the full of expressions to handle can be found here https://dev.mysql.com/doc/refman/5.6/en/non-typed-operators.html

#### Use Case(s)
Queries that must evaluate these expressions

**Comment by systay** [comment]
Do you have an example query that could benefit from implementing this? When do we try to execute this instead of passing it down to the actual MySQL engine?

**Comment by sougou** [comment]
There are a few in https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt. For example:
```
# expression on a cross-shard subquery
"select id+1 from (select user.id, user.col from user join user_extra) as t"
"unsupported: expression on results of a cross-shard subquery"
```

**Comment by harshit-gangal** [comment]
@deepthi I see the support is added now.
