### ISSUE TITLE
2PC should be supported during resharding cutover

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#5108]
2PC transactions currently don't work when writes are migrated during resharding. The challenge is that the redo logs contain original statements, which cannot be routed to the correct shard through vreplication that relies on RBR.

One possible short-term solution will be to disable 2PC during a resharding cutover. The cutover process can disable 2PC in the source shards, and re-enable them after the writes are migrated.

Longer term: we should look at relying on the XA API of the newer mysqls. For this, we have to validate that the behavior is as expected for all corner cases: replication, semi-sync, crash recovery, etc.

**Comment by mattlord** [comment]
I'm closing this as superseded by https://github.com/vitessio/vitess/issues/16245
