### ISSUE TITLE
USE statement not respected with JDBC MySQL driver and dbname in connection params

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#5132]
If you connect to mysql using the JDBC MySQL driver with a dbname in connection params then USE statements take no effect.

This doesn't affect the mysql CLI because it sends the `COM_INIT_DB` packet. The JDBC driver doesn't send the `COM_INIT_DB`, it uses the USE statement. As seen here:
https://github.com/mysql/mysql-connector-j/blob/36534fa273b4d7824a8668ca685465cf8eaeadd9/src/main/user-impl/java/com/mysql/cj/jdbc/ConnectionImpl.java#L2139

The issue is this:
https://github.com/vitessio/vitess/blob/60b4643725017fa809e11c0d00a81e5cc5498586/go/vt/vtgate/plugin_mysql_server.go#L149-L151

You can see that `c.SchemaName` overwrites `session.TargetString` for every call and that the mysql protocol ignores any `USE` statements.

I think the fix is to assign the value of `session.TargetString` to `c.SchemaName` but I'm not sure what the wider repercussions are...

**Comment by demmer** [comment]
I actually think the right fix would be to change that block of code to:

```
 if session.TargetString == "" && c.SchemaName != "" { 
 	session.TargetString = c.SchemaName 
 } 
```

In other words only override the session target to the connection parameter if it hasn't been explicitly set.

**Comment by tirsen** [comment]
Yeah that makes sense. I will make it so.
