### ISSUE TITLE
vtgate fails with no valid tablet: node doesn't exist and http probe failing

### ISSUE THREAD

**Issue by yuya-kanai** [vitessio/vitess#5164]
#### Overview of the Issue

I got this error while attempting to look into the tables like `SHOW tables FROM commerce;` while going through the official vitess k8s tutorial(https://vitess.io/docs/get-started/kubernetes)  
This error popped up when I try to fill the tables as well 

```
http://vtgate-zone1-5cb4fcddcb-gnpb2:15001/: target: commerce.0.master, no valid tablet: node doesn't exist: commerce/0 (MASTER)
```

#### Reproduction Steps
I followed the steps <a href= "https://vitess.io/docs/get-started/kubernetes/" >here</a>
but when it came to the sql related parts I was getting 
```
ERROR 1105 (HY000): vtgate: http://vtgate-zone1-5cb4fcddcb-gnpb2:15001/: target: commerce.0.master, no valid tablet: node doesn't exist: commerce/0 (MASTER)
```

#### Operating system and Environment details

- Operating system : macOS 10.14.4 + kubernetes
- Kernel version : Darwin 18.5.0
- Architecture : x86_64

#### Log Fragments
`kubectl get pods` gives me this result for zone-1-commerce  
```
NAME                             READY   STATUS    RESTARTS   AGE
zone1-commerce-0-rdonly-0        5/6     Running   0          21m
zone1-commerce-0-replica-0       5/6     Running   0          22m
zone1-commerce-0-replica-1       5/6     Running   0          22m
```  

`kubectl describe pod zone1-commerce-0-replica-0` shows(the other two has the same warning)
```
Warning  Unhealthy  3m12s (x108 over 21m)  kubelet, minikube  Readiness probe failed: HTTP probe failed with statuscode: 500
```

vtctld shows
![Screen Shot 2019-09-06 at 16 33 10](https://user-images.githubusercontent.com/49625890/64409524-0bb3a200-d0c4-11e9-874b-8d2bfa3662e7.png)

**Comment by sougou** [comment]
Those pods failed to come up (should show 6/6). Check the logs on the pods.

**Comment by gedgar** [comment]
Closing this issue as it appears to be an environmental issue, and the referenced Kubernetes example has been deleted/deprecated in favor of https://vitess.io/docs/get-started/operator/.

Please feel free to file a new issue if you're still encountering issues with Kubernetes using the operator. Thank you!
