### ISSUE TITLE
Error on connection

### ISSUE THREAD

**Issue by yhyddr** [vitessio/vitess#5168]
#### Overview of the Issue
I want run vitess with Local sh.and got this trouble .

Connection always be refused. I wonder if it is a problem about firewall.

![image](https://user-images.githubusercontent.com/32089134/64547572-687eb900-d35f-11e9-9195-e89666002427.png)

![image](https://user-images.githubusercontent.com/32089134/64547592-73394e00-d35f-11e9-8c7e-dd7e6a3b1fa3.png)

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.
![image](https://user-images.githubusercontent.com/32089134/64547619-81876a00-d35f-11e9-9c80-55463064b1ce.png)

- Operating system (output of `cat /etc/os-release`):
- Kernel version (output of `uname -sr`):
- Architecture (output of `uname -m`):

**Comment by morgo** [comment]
Hello! It looks like you are trying to deploy as root.

We have made a recent enhancement to make this more obvious in Vitess: https://github.com/vitessio/vitess/pull/5323

Please try again as a regular OS user.  Thank you!
