### ISSUE TITLE
Horizontal resharding and cell aliases.

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#5171]
### Description

* We recently discovered that there is a somewhat annoying regression that affects people using cell aliases and trying to split. 
* Before aliases, all the resharding workflows assumed that *all* the tablets involved in the split process will be part of the same cell. 
* We need to make sure the discovery process of tablets during a split workflow is aware of aliases. Similarly to how vtgates are able to route to different cells that are in the same alias, in this context it should be able to discover tablets in different cells. 

### Workaround while this bug is fixed

A viable workaround for this issue is to make sure that all the components involved in the split are provisioned in the same cell. Here an example: 

* Provision source tablets that are part of the copy phase in a given cell that is part of the alias (e.g cell  a).
* Provision vtworkers all the vtworkers in the same cell (e.g cell a).
* Provision destination tablets that are part of split diff in the same cell (e.g cell a). 
* Provision destination tablet masters in the same cell (e.g cell a).

**Comment by brirams** [comment]
Just wanted to bump this as it's required us to write a bunch of bespoke provision scripts to workaround this. For some specifics that I found while looking into this, it looks like worker actions like `LegacySplitClone` are not multi-cell aware and only [look for targets in their own cell](https://github.com/vitessio/vitess/blob/fceed44ff9914862f027896ca44dcca643f89631/go/vt/worker/legacy_split_clone.go#L360). Expanding this to use aliases would be 👍

**Comment by sougou** [comment]
The new resharding commands (about to be unveiled) support a cell flag :), and you can override them individually on the vreplication streams. I think cell will be an orthogonal concept to labels. But we'll know more when we iterate through the design doc.

**Comment by mattlord** [comment]
I'm closing this as legacy sharding was completely removed and I'm unaware of any similar issues in the `Reshard` command. Please let me know if I'm missing something and we can re-open this. Thanks!
