### ISSUE TITLE
Make reparents more robust

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#5172]
This is a tracking issue for an open task from #5151 

https://github.com/vitessio/vitess/pull/5151#issuecomment-527653083

We should implement a comprehensive fix that works for all 3 reparenting commands: PlannedReparentShard (PRS), EmergencyReparentShard (ERS), and TabletExternallyReparented (TER).

#5173 should also be covered by the fix.

**Comment by deepthi** [comment]
Discussion notes (cc @sougou @enisoc)
There are 2 principles that we want to keep in mind while designing this:
1. Global topo info should only be used for discovery. May not be authoritative.
2. Global topo should not be spammed by multiple polling requests.

The current masterAlias is stored in the global topo
Relying on the global topo is not a good idea because we won't be able to reparent without global topo. When we do a TER/PRS, we want to be able to complete the requested action, and update the global topo on a best-effort basis.

The way to achieve robust PRS/TER is to use consensus principles.
At this point we know that there can be impostors, but we also know that any impostors will be read-only. We trust that whoever is calling TER is ensuring the mysql states are consistent (only one master). PRS demotes the old master before promoting the new master.
In case of EmergencyReparentShard, the old master may be unreachable and we designate a new master. If semi-sync is set, this is not a problem. If semi-sync is off, you can have a co-master issue that is outside the scope of this work. (Discourage use of ERS)
Let's say that TER/PRS/ERS have a chosen master A. There is a timestamp associated with the master. We are assuming two things:
* An impostor master cannot accept writes
* The "correct" master always has the highest timestamp

PRS/ERS:
* use masterAlias as a starting point
* if masterAlias is not set, it is possible that the shard has never been initialized, this should fail
(need to add an RPC to get master timestamp from tablet)
(ISM & TER are still allowed to initialize masterAlias)
* once a tablet has been told that it is the master, it is the tablet's job to update the shard record. We need to add a timestamp to the masterAlias record in the shard record. The tablet will retry the update if it fails, until and unless it detects a higher timestamp.
* a master tablet will start watching the masterAlias as soon as it successfully writes to it 
* when a master tablet learns that it is no longer the master, it will demote itself and remove the watch

Code changes needed:
Retry shard record update until it succeeds (or there is some other master)
Setting a watch on shard record

**Comment by sougou** [comment]
This looks good. A clarification that may not be obvious: In this new scheme, TER becomes extremely simple. All it does is inform the new tablet that it's now the master. Everything else is handled by the unified mechanism.

**Comment by sougou** [comment]
Some additional thoughts:

* If there is clock skew, it's possible that two masters may end up with the same timestamp. If so, the first master wins. In other words, a new master can overwrite the tablet record only if its timestamp is strictly greater than the one in MasterAlias.
* With the above disambiguation, we can perform the following improvement in the future: we do a beset-effort check of the current time with global MasterAlias. If it's less, we adjust the time to be MaterAlias+1. This will allow for the new master to override the previous one. If we can't reach global topo, we fall back to using the current timestamp.
* The dual master scenario can still happen if the global topo is down, but it's not a material problem because vtgates will know who the right master is. The system will heal itself once the global topo becomes reachable.

**Comment by deepthi** [comment]
Some notes on how things will work during an upgrade / rollout:
* The recommended order of upgrade is vttablet, vtctld, vtgate as documented [here](https://vitess.io/docs/user-guides/upgrading/#upgrade-order)
* TER calls to old vtctld will continue to call the tablet RPC, and TER calls to new vtctld will work correctly because vttablets have already been upgraded.
* PRS on old vtctld will work (or not) just as it does now. After vtctld is upgraded you will get the new and shiny PRS.
* Same holds for ERS.

**Comment by enisoc** [comment]
We decided to also add a MasterTermStartTime to the tablet record (in addition to the shard record), to persist each tablet's timestamp, for the following reasons:

* We want TER to report success only if the information needed to ensure eventual consistency (new master, and master term start time) has been persisted in local topo. That way, even if the new master tablet crashes after returning success for TER but before updating the shard record, it will converge to the correct state after restarting. We do not want to add a dependency on global topo (the shard record), but we already have a dependency on local topo (updating the type in the tablet record) so there's no additional cost to also persist the timestamp in the tablet record before returning.
* We want vtctl InitTablet to persist the timestamp in topo, but we want to maintain the invariant that the shard record is updated by the master tablet itself, not by vtctld.

In either of the above cases (new master crashes, or initial start-up of master tablet), a tablet that decides to start up as master should "restore" its master term start time from its own tablet record. A tablet should also update the timestamp in its tablet record any time it updates its in-memory master term start time, such as when it transitions to being a master.

**Comment by morgo** [comment]
With #5391 merged, I am going to close this issue now. Please feel free to re-open it if this is in error.
