### ISSUE TITLE
Handle two-master scenarios

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#5173]
This is a tracking issue for an open task from #5151 

Run a watchdog thread (likely in vtctld), that will continuously monitor for the two-master scenario and demote the impostor.

https://github.com/vitessio/vitess/pull/5151#issuecomment-528140694

**Comment by derekperkins** [comment]
I'd like for this to also watch for fake zero-master scenarios. We have gotten into situations a decent amount where neither tablet thinks it is a replica, but the control plane thinks that one is.

**Comment by deepthi** [comment]
This is included in the scope of #5172, so I'm going to close this issue.
