### ISSUE TITLE
Drivers sending COM_CHANGE_USER or COM_RESET_CONNECTION to reset connections are unsupported by vtgate

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5201]
Specifically with the C# Connector (https://github.com/mysql-net/MySqlConnector), but this will also happen with JDBC Connectors:

  * When the connector decides to reset the connection, and it thinks vtgate is MySQL 5.5.10 (because of the default version string that vtgate reports), the connector will try and send a COM_CHANGE_USER MySQL rpc to vtgate to reset the connection.  This will fail because vtgate does not support COM_CHANGE_USER.

  * If you have vtgate report a MySQL version >= 5.7.3 (via the -mysql_server_version cmdline option to vtgate), the C# connector will instead send a COM_RESET_CONNECTION rpc to vtgate, which isn't supported either.

If you're using a pooling driver above the connector, you may be able to reduce/avoid these errors by setting more aggressive pool refresh settings.

We should add support for both these RPCs in vtgate

**Comment by morgo** [comment]
I believe this should be relatively straight forward. Here is the basic outline of what needs to be implemented:
```
diff --git a/go/mysql/conn.go b/go/mysql/conn.go
index 42b8215c8..f42c6b659 100644
--- a/go/mysql/conn.go
+++ b/go/mysql/conn.go
@@ -776,7 +776,14 @@ func (c *Conn) handleNextCommand(handler Handler) error {
                        log.Errorf("Conn %v: Flush() failed: %v", c.ID(), err)
                        return err
                }
-
+       case ComResetConnection:
+               // This RPC is used by connection pools to clean a connection to be used
+               // for the next user. In MySQL server teams clean means rollback transactions,
+               // clear session variables, temporary tables and prepared statements.
+       case ComChangeUser:
+               // This RPC is/was most commonly used by connection pools prior to the introduction
+               // of ComResetConnection. The use case was that by changing the user to the
+               // current user, the connection was cleaned.
        case ComPing:
                c.recycleReadPacket()
                // Return error if listener was shut down and OK otherwise
diff --git a/go/mysql/constants.go b/go/mysql/constants.go
index b1d4491f6..10537cf7b 100644
--- a/go/mysql/constants.go
+++ b/go/mysql/constants.go
@@ -150,6 +150,9 @@ const (
        // ComPing is COM_PING.
        ComPing = 0x0e
 
+       // ComChangeUser is COM_CHANGE_USER
+        ComChangeUser = 0x11
+
        // ComBinlogDump is COM_BINLOG_DUMP.
        ComBinlogDump = 0x12
 
@@ -177,6 +180,9 @@ const (
        // ComBinlogDumpGTID is COM_BINLOG_DUMP_GTID.
        ComBinlogDumpGTID = 0x1e
 
+       // ComResetConnection is COM_RESET_CONNECTION
+        ComResetConnection = 0x1f
+
        // OKPacket is the header of the OK packet.
        OKPacket = 0x00
```

Because Vitess does not have session-scoped variables, it's just prepared statements and transactions that need resetting.

@saifalharthi do you mind taking a look at this?

**Comment by schneiderdba** [comment]
Hello,
We are seeing errors after we added -mysql_server_version '8.0.16-7' \ to the vtgates and restarted.  

ERROR:
`MySql.Data.MySqlClient.MySqlException: command handling not implemented yet: 31`

**Comment by aquarapid** [comment]
Just to clarify;  >= 5.7.3, the C# connector will send COM_RESET_CONNECTION ;  < 5.7.3 it will send COM_CHANGE_USER.  So in the case where the built-in C# connector's connection pool tries to reset the connection, will will see one of the two errors, no matter what version vtgate is presenting.

**Comment by saifalharthi** [comment]
COM_RESET_CONNECTION was supported here https://github.com/vitessio/vitess/pull/5219

**Comment by sougou** [comment]
Now that we've bumped the default version of vtgate to 5.7. I think we should not support the deprecated change user opcode. If there are no objections, I'll close this issue.
