### ISSUE TITLE
MySQL JDBC driver tries to send "select @@query_cache_size as query_cache_size from dual;" to vtgate

### ISSUE THREAD

**Issue by sverch** [vitessio/vitess#5205]
#### Overview of the Issue

- The MySQL JDBC client is too smart for it's own good and thinks that vtgate is 5.5 (due to the mysql version we advertise).
- It then barfs on the fact that if the backend mysqld behind vtgate is MySQL 8.x ; we won't know that variable (MySQL 8.x does not support query_cache_size anymore).

Workaround: use vtgate -mysql_server_version to advertise a mysql 8.x version string (e.g. "8.0.17 Source distribution")

#### Reproduction Steps

Use Vitess with MySQL 8 and the MySQL JDBC client.

#### Vitess Version

```
$ bin/vtgate --version
Version: ad6099c (Git branch 'master') built on Wed Aug 28 22:59:33 UTC 2019 by planetscale@ip-172-31-17-134 using go1.11.4 linux/amd64
```

**Comment by sverch** [comment]
From @morgo:

- We should bump the advertised version to MySQL 5.7 (drivers will stop trying to do so many strange things).
- We should noop on set query_cache statements, since this feature is useless anyway.

**Comment by sougou** [comment]
Now that we've bumped the default version of vtgate to 5.7. I think we should not support the special construct. If there are no objections, I'll close this issue.

**Comment by sverch** [comment]
@sougou Does this mean that anyone using MySQL 8.x must pass `-mysql_server_version` to the vtgate?  Originally we were thinking that flag was a workaround for this issue, and the expectation was that once this was closed that argument wouldn't be needed any more, but it sounds like that understanding was off.  That does make sense though, just want to be sure.

**Comment by sougou** [comment]
I believe the issue doesn't have anything to do with the mysql version used in the backend. It's more due to the version advertised by vtgate. The clients seem to behave differently when it used to advertise 5.5. Now that we've bumped it to 5.7, they shouldn't be doing this any more.

**Comment by sverch** [comment]
Sounds good, I'll follow up with the original source of this issue to verify the fix worked.

**Comment by morgo** [comment]
Note that we only bumped the advertised default version to 5.7 in Vitess 5.0, and versions less than 8.0 will have issues with query-cache. So this issue is still likely to be a problem.

**Comment by harshit-gangal** [comment]
@morgo anyone using mysql-j-connection < 8.0 will still have problem, right?

**Comment by morgo** [comment]
I am not actually sure how it relates to client library versions. I suspect it may have been backported to earlier client libraries since it effectively prevents an 8.0 server from working.

The fix is easy though, just noop it :)

**Comment by harshit-gangal** [comment]
Set can be made noop. But it the select query for which we have to return something

**Comment by harshit-gangal** [comment]
There is one more issue. VTGate advertises as 5.7 to any connection. So, mysql java connector sends as select of @query_cache_size but for mysql 8.0 it does not exists. VTGate needs to emit the correct version.

**Comment by harshit-gangal** [comment]
The version needs to be set correctly on deployment using vtgate flag.
