### ISSUE TITLE
Add support for DROP CHECK grammar

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#5237]
In 8.0.16 support was added for check constraints. I'm currently able to create them in Vitess, but dropping a check throws a syntax error. Simple passthrough grammar support should be sufficient.
https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html

**Comment by saifalharthi** [comment]
@derekperkins  We should close this issue

**Comment by derekperkins** [comment]
Why should we close it?

**Comment by saifalharthi** [comment]
@derekperkins A PR was merged where I added `CHECK` to the parser. Assuming thats the scope of this issue.
