### ISSUE TITLE
indicate routing via served_from

### ISSUE THREAD

**Issue by acharis** [vitessio/vitess#5257]
During vertical resharding, we would like to know when it is safe to execute MigrateServedFrom, from the standpoint of apps. (It _is_ clear when vertical split clone has progressed to the Running state, which means it's safe to execute MSF from the standpoint of data.) If you have many many apps executing queries against the tables you're moving from OldKs to NewKs, it might not be entirely clear when all the apps have started to direct their queries to NewKs. I think vtgates have this information somewhere, but I can't find it exposed anywhere.

Implementation options:
- a simple counter on the vtgate incrementing when a query is redirected
- appending a `/* redirected */` comment to the end of redirected queries
- indicating redirection in the vtgate (or vttablet) querylogs

Context: https://vitess.slack.com/archives/C0PQY0PTK/p1569944860361400

**Comment by ajm188** [comment]
`served_from` is removed as of v15 (see #10409), going to close this
