### ISSUE TITLE
remove SSLv3 support

### ISSUE THREAD

**Issue by hwdef** [vitessio/vitess#5273]
#### Overview of the Issue

go/mysql/server.go:779:

```
func tlsVersionToString(version uint16) string {
	switch version {
	case tls.VersionSSL30:
		return versionSSL30
	case tls.VersionTLS10:
		return versionTLS10
	case tls.VersionTLS11:
		return versionTLS11
	case tls.VersionTLS12:
		return versionTLS12
	default:
		return versionTLSUnknown
	}
}

```

SSLv3 is cryptographically broken,unused and will be removed in Go 1.14. See [golang.org/issue/32716](https://golang.org/issue/32716).

**Comment by deepthi** [comment]
@morgo can you also take a look at
https://github.com/vitessio/vitess/pull/4276#discussion_r226040590?

**Comment by morgo** [comment]
Sure :-) I can take a look next week. It looks relatively straight forward. This should be a 4.0 feature too, since it is nice to clean this up prior to release.
