### ISSUE TITLE
Make topology implementation in helm configurable

### ISSUE THREAD

**Issue by aberfeldy** [vitessio/vitess#5322]
#### Feature Description
Currently etcd is hardcoded as topo-implementation in the helm chart [Line 102](https://github.com/vitessio/vitess/blob/63fef107a29dde39cebfb4bd0445052029b58ab2/helm/vitess/templates/_vtctld.tpl#L102)
It would be nice to have that determined by a value from values.yaml, since zookeeper and consul are supported as well. 

#### Use Case(s)
Users wouldn't have to rewrite/fork the helm chart in order to use a different topo-implementation on their Kubernetes cluster.

**Comment by morgo** [comment]
Thank you for the feature request.

**Comment by evalsocket** [comment]
@morgo Would like to work on this. Can this be assigned to me?

**Comment by morgo** [comment]
Be aware that there is also work in https://github.com/vitessio/vitess/pull/5703 to add Kubernetes as a topo. I expect that after this is added, it will eventually become the default as it simplifies installs.

**Comment by ajm188** [comment]
closing due to helm deprecation https://github.com/vitessio/vitess/issues/6439
