### ISSUE TITLE
about my.cnf parameter 

### ISSUE THREAD

**Issue by gaogaolulu** [vitessio/vitess#5358]
#### Feature Description
MySQL replication parameter issue : 

  /config/mycnf/default.cnf

binlog_format = ROW
basedir = /usr
lc_messages_dir=/usr/share/mysql
bind_address = 0.0.0.0

rpl_semi_sync_master_enabled = 1  
rpl_semi_sync_master_timeout = 1000   
rpl_semi_sync_slave_enabled = 1
 
 /config/mycnf/master_mysql57.cnf
 
gtid_mode = ON
enforce_gtid_consistency = ON
log_bin= mysql-bin
log_slave_updates = ON 
innodb_use_native_aio = 0

/config/mycnf/master_mysql56.cnf

gtid_mode = ON
enforce_gtid_consistency = ON
log_bin= mysql-bin
log_slave_updates = ON 
innodb_use_native_aio = 0

/config/mycnf/replica.cnf
#####log-slave-updates
log_slave_updates = ON

#### Use Case(s)
start Vitess with the script:   101_initial_cluster.sh

**Comment by morgo** [comment]
This will need investigation as it overlaps with https://github.com/vitessio/vitess/issues/4990
