### ISSUE TITLE
lacking system variables 

### ISSUE THREAD

**Issue by gaogaolulu** [vitessio/vitess#5359]
#### Overview of the Issue

when DBA wants to start Vitess , he/she must set following variables : 
 
export VT_MYSQL_BASEDIR=/usr

#### Reproduction Steps

execute :   101_initial_cluster.sh

  
#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.
Oracle Linux: 7.6 ,  64 bit
MySQL 5.7 

 
#### Log Fragments

 remote error: rpc error: code = Unknown desc = tablet zone1-0000000102 ResetReplication failed (either fix it, or Scrap it): rpc error: code = DeadlineExceeded desc = context deadline exceeded;tablet zone1-0000000101 ResetReplication failed (either fix it, or Scrap it): rpc error: code = DeadlineExceeded desc = context deadline exceeded;tablet zone1-0000000100 ResetReplication failed (either fix it, or Scrap it): rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by morgo** [comment]
I can see what causes this bug. `./examples/local/env.sh` tries to autodetect the `VT_MYSQL_ROOT` by checking for `mysqld_safe` in the PATH:
```
# Try to find mysqld_safe on PATH.
if [ -z "$VT_MYSQL_ROOT" ]; then
  mysql_path=`which mysqld_safe`
  if [ -z "$mysql_path" ]; then
    echo "Can't guess location of mysqld_safe. Please set VT_MYSQL_ROOT so it can be found at \$VT_MYSQL_ROOT/bin/mysqld_safe."
    exit 1
  fi
  export VT_MYSQL_ROOT=$(dirname `dirname $mysql_path`)
fi
```

The problem is that `mysqld_safe` is no longer reliably packaged, since newer systems use systemd. It's an easy fix, we just need to search for `mysqld` instead of `mysqld_safe`.
