### ISSUE TITLE
Snapshot Keyspaces: RestorePosition doesn't fit in local_metadata table

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#5377]
I'm blocked from restoring a backup because the replication position string is too long to fit in the local_metadata table, which was added for Snapshot Keyspaces:

```
F1029 23:40:46.360537       1 action_agent.go:324] RestoreFromBackup failed: Data too long for column 'value' at row 1 (errno 1406) (sqlstate 22001) during query: INSERT INTO _vt.local_metadata (name,value, db_name) VALUES ('RestorePosition','MySQL56/6b4b6b75-b8b8-11e9-8b73-6ae328f38128:1-15,7f2cc2a3-9b0b-11e9-94c3-760882732513:1-3,935a9f52-9b0b-11e9-999b-ce1b53fb507c:1-8,93a9ad68-9b0b-11e9-a3cd-cebf76dff321:1-33,93b17ec0-9b0b-11e9-9a45-be1232742c40:1-24,9e6432bf-ace3-11e9-a9e1-924619225ecf:1-8','vt_main') ON DUPLICATE KEY UPDATE value = 'MySQL56/6b4b6b75-b8b8-11e9-8b73-6ae328f38128:1-15,7f2cc2a3-9b0b-11e9-94c3-760882732513:1-3,935a9f52-9b0b-11e9-999b-ce1b53fb507c:1-8,93a9ad68-9b0b-11e9-a3cd-cebf76dff321:1-33,93b17ec0-9b0b-11e9-9a45-be1232742c40:1-24,9e6432bf-ace3-11e9-a9e1-924619225ecf:1-8'
```

The replication position string can technically grow without bound, but I suppose we have to decide on some larger column size for local_metadata. We can look at what size we use in places like the reparent journal. Hopefully it's straighforward to do an ALTER on startup. Or since it's local metadata, maybe we can just drop and recreate?

**Comment by deepthi** [comment]
We should be able to do an alter.
We can change the type to BLOB (which can hold upto 65535 bytes) or MEDIUMBLOB (which can hold up to 16,777,215 bytes). @sougou @morgo what would you recommend?

**Comment by morgo** [comment]
`BLOB` should be able to hold about 2000 pairs, but I've heard of some users with hundreds of gtid_executed sets.. so it's not a stretch to see it would run out. Yes, might even be worth `mediumblob` here.

**Comment by enisoc** [comment]
@deepthi How trivial do you think it will be to do the ALTER? If there's some risk there, maybe we should temporarily disable setting of RestorePosition in the meantime? Anyone with a position too long is blocked from restoring right now.

**Comment by deepthi** [comment]
Per @morgo even 65535 could run out, so I'm going to go with MEDIUMBLOB.
@sougou you should consider changing reparent_journal table to use MEDIUMBLOB as well.

**Comment by enisoc** [comment]
@morgo do you know what this means in the original comment on `MaximumPositionSize`?

> A row has a maximum size of 65535 bytes. So we want to stay under that.

Why did we think we had to keep the total row size under 64K? Is that just to get good performance?

**Comment by deepthi** [comment]
> Why did we think we had to keep the total row size under 64K? Is that just to get good performance?

That's a limit imposed by MySQL. BLOB columns are not subject to this limit because they are stored in a different location from the parent row.

**Comment by enisoc** [comment]
Ah I see - it's a limit only if you desire to avoid BLOB/TEXT columns. Thanks!
