### ISSUE TITLE
keyspaces_to_watch does not limit vtgate->tablet health checks

### ISSUE THREAD

**Issue by setassociative** [vitessio/vitess#5387]
### Summary
VTgates support a `keyspaces_to_watch` flag which exists to provide data isolation. Once of the side effects of this is that it shouldn't need to maintain a healthcheck to tablets that exist in a keyspace it can't reach.

### Reproduction Steps

1. Run a vtgate passing `--keyspaces_to_watch`
2. view vtgate logs and observe that there are healthchecks ongoing for keyspaces not listed in the arg above

**Comment by rafael** [comment]
@spark4 from Vitess team at slack will be working on this. 

For some reason, github does not allow me to assign it to you
