### ISSUE TITLE
Support caching_sha2_password authentication plugin

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5399]
#### Feature Description

Vitess only supports mysql_native_password (which was the default up until MySQL 8.0). This is based on sha1, which is now considered cryptographically weak.

This issue is to track adding caching_sha2_password.

**Comment by aquarapid** [comment]
Note that while this FR is (implicitly) for supporting caching_sha2_password in the server (vtgate) code, we should also support it in our client code used by vttablet.

**Comment by aquarapid** [comment]
Another wrinkle is that when talking to (real) MySQL, caching_sha2_password is only supported when the connection is encrypted, unless it's over a local unix_socket.  Something to keep in mind for vttablet supporting "external" MySQL instances.

**Comment by harshit-gangal** [comment]
This will be resolved by https://github.com/vitessio/vitess/pull/6716

**Comment by deepthi** [comment]
Fixed in #6716
