### ISSUE TITLE
mysqldump: server with gtids

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5403]
#### Feature Description

mysqldump on a server with GTIDs adds the following to the dump file, which can't be executed in VItess:

```
SET @MYSQLDUMP_TEMP_LOG_BIN = @@SESSION.SQL_LOG_BIN;
SET @@SESSION.SQL_LOG_BIN= 0;

# in MySQL 5.7:
SET @@GLOBAL.GTID_PURGED='0a953d85-ffd6-11e9-b87d-84fdd111e365:1-29';

# or in MySQL 8.0
SET @@GLOBAL.GTID_PURGED=/*!80000 '+'*/ '0a953d85-ffd6-11e9-b87d-84fdd111e365:1-27';
```

**Comment by harshit-gangal** [comment]
GTID_PURGED is something we do not intent to support and this can be avoided while taking mysqldump with `--set-gtid-purged=OFF`
