### ISSUE TITLE
Support for sharded subquery in insert values

### ISSUE THREAD

**Issue by mshow34jt** [vitessio/vitess#5408]
I have found that in an attempt to copy entries from a sharded database into an unsharded table, vtgate responds with:
"unsupported sharded subquery in insert values"
Sougou said via slack that this should be easy and requested I create this issue

**Comment by mindspin311** [comment]
Could really use this as well. Just ran into this trying to do an easy migration to a new database.

**Comment by harshit-gangal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Insert using select statement](https://trello.com/c/B220OazI/10-insert-using-select-statement)
