### ISSUE TITLE
vreplication failing 

### ISSUE THREAD

**Issue by npulikanti** [vitessio/vitess#5413]
Vreplication is failing 
#### Overview of the Issue

We are testing vreplication to generate some materialized views from an unsharded keyspace to a sharded one. But it seems like it is failing with an exception when we tried to initialize it. 

#### Reproduction Steps

Steps to reproduce this issue, example:

1. table is the unsharded keyspace in_sequence/0
CREATE TABLE `t_state` (
  `h` varchar(255) NOT NULL DEFAULT '',
  `ctag` varchar(255) DEFAULT NULL,
  `gtag` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`h`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

2.created vreplication stream for the sharded tablet test-200
cmd = [
  './lvtctl.sh',
  'VReplicationExec',
  'test-200',
  """insert into _vt.vreplication
  ( source, pos, max_tps, max_replication_lag, tablet_types, time_updated, transaction_timestamp, state) values
  ('keyspace:"in_sequence" shard:"0" filter:<rules:<match:"utopology_state" filter:"select * from topology_state" > >', '', 99999, 99999, 'master', 0, 0, 'Running')""",
]
3.check exception in the vttablet logfile 
"/usr/local/go/src/runtime/panic.go:513 (0x42e508)
/usr/local/go/src/runtime/panic.go:82 (0x42d65d)
/usr/local/go/src/runtime/signal_unix.go:390 (0x444481)
/export/home/eng/npulikan/src/vitess.io/vitess/go/vt/binlog/binlogplayer/binlog_player.go:236 (0xc032f5)
/export/home/eng/npulikan/src/vitess.io/vitess/go/vt/binlog/binlogplayer/binlog_player.go:177 (0xc01537)
/export/home/eng/npulikan/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:183 (0xc8ce46)
/export/home/eng/npulikan/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:124 (0xc8c86b)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x45e750)
W1106 18:58:44.082941    3413 controller.go:134] stream 1: panic: runtime error: invalid memory address or nil pointer dereference, retrying after 5s"

#### Binary version
Example:

```sh
bash-4.1$vtgate --version
Version: a88142d (Git branch 'master') built on Sun Mar 10 06:46:25 UTC 2019 by npulikan using go1.11.5 linux/amd64
```

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`):
Red Hat Enterprise Linux Server release 6.5 (Santiago)
- Kernel version (output of `uname -sr`):
Linux 2.6.32-431.17.1.el6.x86_64
- Architecture (output of `uname -m`):
x86_64

#### Log Fragments

Include appropriate log fragments. If the log is longer than a few dozen lines, please
include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue.

**Comment by deepthi** [comment]
The build being used is quite old: ```Version: a88142d (Git branch 'master') built on Sun Mar 10 06:46:25 UTC 2019 by npulikan using go1.11.5 linux/amd64```
Is updating to a more recent build an option? A lot of changes have gone into vreplication since March.

**Comment by npulikanti** [comment]
thankyou deepthi. How much effort is it to move to a newer version. is it inpace upgrade?

**Comment by npulikanti** [comment]
could i upgrade from my current version to the latest 4.0 or should i have to  from 2.0 --> 3.0 -->4.0 …

**Comment by deepthi** [comment]
3.0 was in Dec 2018, so you are past that. You should be able to go to 4.0.
As for the upgrade process, how carefully you want to do it depends on your environment. If it is production, then you will want to first test in a dev environment. The user guide has helpful information on how to do this.
