### ISSUE TITLE
The following urls are invalid.They will return 404 when looking for them.

### ISSUE THREAD

**Issue by tanjunchen** [vitessio/vitess#5438]
vitess/docker/README.md 
https://vitess.io/getting-started/docker-build/

**Comment by xichengliudui** [comment]
assigned to me

**Comment by tanjunchen** [comment]
remove  url in tables

**Comment by xichengliudui** [comment]
i think this function has been removed.

**Comment by tanjunchen** [comment]
@xichengliudui  agree. @morgo  @sougou  remove these doc about https://vitess.io/getting-started/docker-build/?

**Comment by morgo** [comment]
Thanks, I'll close this issue.
