### ISSUE TITLE
vitess/lite image has 122MB of unnecessary mysql data files

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#5443]
The `vitess/lite` Docker image has 122MB of unnecessary mysql data files:

```console
$ docker run -ti --rm -u root vitess/lite:latest du -sh /var/lib/mysql
122M    /var/lib/mysql
```

These probably come from the default database that gets initialized when we install mysql-server through a package manager. We should be able to avoid saving these if we delete them in the same `RUN` statement as the package installation.

**Comment by morgo** [comment]
I think this is a good suggestion. I don't think we ever use this mysql install, since mysqlctl initializes new databases.

**Comment by J0** [comment]
Hey @morgo, can I take this issue? I'll get to it after booth duty.

**Comment by morgo** [comment]
Go for it!
