### ISSUE TITLE
Add support for IMDSv2 (EC2 Instance Metadata Service) 

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#5447]
#### Feature Description
AWS just announced the release of a new version of the EC2 Instance Metadata Service (now IMDSv2). 

You can find more info in the blog post [here](https://aws.amazon.com/about-aws/whats-new/2019/11/announcing-updates-amazon-ec2-instance-metadata-service/) but the tl;dr; is that it adds several security enhancements.

The AWS SDK for go [has been already patched](https://github.com/aws/aws-sdk-go/pull/2958) to support this functionality. I'm creating this issue to keep track of the work needed to enable IMDSv2 by default in the Vitess codebase.
 
#### Use Case(s)
When `backup_storage_implementation` is set to S3, enforce the use of IMDSv2 during backup and restore operations.

**Comment by guidoiaquinti** [comment]
Most probably fixed by #5777 as IMDSv2 should be enabled by default in the new SDK

**Comment by harshit-gangal** [comment]
@guidoiaquinti can you confirm and close the issue?

**Comment by aquarapid** [comment]
We haven't had any issues running Vitess in an AWS account with IMDSv1 disabled.  Closing.
