### ISSUE TITLE
Ghost queries on vtgate

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#5452]
We noticed that vtgates receiving no actual traffic were showing about 1 QPS of `Execute()` calls according to the `vtgate_api_count` metric. We tracked it down to health checks from an AWS Classic ELB, which connects to vtgate's MySQL port and then immediately closes the connection, just to see if anyone answers.

Every time the ELB closes this connection, vtgate calls `Execute("rollback")` on itself, just in case any transaction was in progress:

https://github.com/vitessio/vitess/blob/83bfb049468cae3475f69e4f7c01ab5032c7e580/go/vt/vtgate/plugin_mysql_server.go#L86-L113

It does this even though no transaction was in progress -- in fact, no mysql-level handshake/authentication had ever occurred. The mere act of opening and closing a TCP connection triggers this rollback.

The rollback ends up being a no-op anyway (it doesn't even send anything to a vttablet), but we should clean this up to avoid noise and confusing ghost queries.

cc @sougou

**Comment by aquarapid** [comment]
This code has changed to call `CloseSession`;  which checks if we are in a transaction before issuing a rollback, so I'm pretty sure this isn't a problem anymore.
