### ISSUE TITLE
vtgate: Painpoint with `SELECT DATABASE()`

### ISSUE THREAD

**Issue by mc0** [vitessio/vitess#5459]
#### Overview of the Issue

When running `SELECT DATABASE()` the actual database is returned (from the vttablet) instead of from the vtgate's perspective. This causes weird tooling issues when trying to request the current database and then interact with that database specifically. For example, the mysql cli treats:
```
use `some_db`;
```
special by requesting the current database after running and then sending a ComInitDB packet with the next query.

Original select database support added here:
https://github.com/vitessio/vitess/issues/2245

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Use mysql cli to run:
```
use `some_db:-80@master`;
```
2. Run a query to fetch data from that database
1. Observe an error from vtgate about not finding the keyspace from srvkeyspace

**Comment by morgo** [comment]
Somewhat related: 

If `select database()` returns the correct keyspace, there will be more occurrences of https://github.com/vitessio/vitess/issues/5393  as a routing problem. We need to fix both.

**Comment by systay** [comment]
My understanding is that our current support of `database()` is enough to close this issue. Please feel free to re-open if I missed something.
