### ISSUE TITLE
Blob Support: Not allowing to insert blob more than 7MB of file size

### ISSUE THREAD

**Issue by vikaskesakar** [vitessio/vitess#5521]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

Vitess not allowing to insert blob of larger size if database schema contains column of type Long Blob.

#### Reproduction Steps
Try to insert blob size of 12-13 MB of file using MySQL insert query.

#### Log Fragments
Throwing error ER_TOO_MANY_USER_CONNECTIONS

**Comment by morgo** [comment]
I think this is a bug because the error message is incorrect. But it could be argued it is a feature request to insert large blog values, since it is less common in OLTP scenarios.

**Comment by derekperkins** [comment]
We've inserted near 100 MB blobs into json columns, so there shouldn't be an inherent limitation in Vitess. It did require us to tune the max grpc message size flags in vtgate and vttablet.

**Comment by vikaskesakar** [comment]
How to tune max grpc message size flags?

**Comment by derekperkins** [comment]
Just setting flags to the binaries. If you check the available flags for the binaries, they're easy to find.

**Comment by vikaskesakar** [comment]
Ok thanks. I'll check, if resolved, I will close this issue.
