### ISSUE TITLE
Add macOS and CentOS local_example tests

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5535]
#### Feature Description

The [local_example test](https://github.com/vitessio/vitess/blob/master/.github/workflows/local_example.yml) currently tests the latest Ubuntu LTS (18.04). We should add versions of this for CentOS and macOS, preferably using matrix builds.

This will help catch if there is something specific introduced which breaks other OSes.. which has happened in the past.

**Comment by J0** [comment]
Hey @morgo, I'd like to take this issue
