### ISSUE TITLE
The whole MySQL container memory is used during a sysbench

### ISSUE THREAD

**Issue by Smana** [vitessio/vitess#5537]
#### Overview of the Issue

During a sysbench test the whole mysql container memory is filled for an unknown reason.

![image](https://user-images.githubusercontent.com/4101366/70416373-3d3f5f00-1a5f-11ea-9ac7-74c42d4be995.png)

#### Reproduction Steps

1. Create a kubernetes cluster v1.13.11-gke.14

2. Configure Helm (v2.14.3), init tiller with cluster-admin role

3. Install the etcd operator

```
helm install --name etcd-operator stable/etcd-operator
```

5. From another server (a db loader), clone the Planetscale's sysbench repository
```
git clone https://github.com/planetscale/sysbench-tpcc
cd sysbench-tpcc
```

4. Use this [values.yaml](https://gist.github.com/Smana/f4e3733332868899c9eddc14009a3b6b) and run the following command
```
helm upgrade --install vitess-release-name -f values.yaml --namespace vitess ${VITESS_REPO}/helm/vitess
```

6. Run the sysbench `prepare` command
*warn*: You will have to expose the vtgates, here I used a GCP internal loadbalancer (here the hostname is `vitess`)
```
./tpcc.lua --mysql-host=vitess --mysql-port=3306 --mysql-db=my_db --time=300 --threads=32 --report-interval=1 --tables=10 --scale=10 --db-driver=mysql --use-fk=0 prepare
```

After a few minutes we can see that the mysql container memory reaches the limit

#### Operating system and Environment details

Kubernetes cluster running on GKE version v1.13.11-gke.14
Helm version v2.14.3
Sysbench version 1.0.18

On slack they suggest to load the tcmalloc librairy but that didn't help
```
LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
```

**Comment by morgo** [comment]
@aquarapid Did you mind taking a look at this one?

**Comment by derekperkins** [comment]
@Smana what does your my.cnf look like, specifically your buffer pool settings?

**Comment by Smana** [comment]
I just added this parameters to the default configuration @derekperkins  :
```
[mysqld]
innodb_buffer_pool_size = 4G
query_cache_size = 0
```

**Comment by Smana** [comment]
Note that the memory allocator is set in a environment variable
```
    Environment:                                                                                                                                                                                                   
      VTROOT:           /vt                                                                                                                                                                                        
      VTDATAROOT:       /vtdataroot                                                                                                                                                                                
      GOBIN:            /vt/bin                                                                                                                                                                                    
      VT_MYSQL_ROOT:    /usr                                                                                                                                                                                       
      PKG_CONFIG_PATH:  /vt/lib                                                                                                                                                                                    
      LD_PRELOAD:       /usr/lib/libtcmalloc_minimal.so.4
...
```
and just before the mysqld command
```
      export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"                                                                                                                                                        
      eval exec /vt/bin/mysqlctld $(cat <<END_OF_COMMAND                                                                                                                                                           
        -logtostderr=true                                                                                                                                                                                          
        -stderrthreshold=0                         
...
```

**Comment by derekperkins** [comment]
@Smana that's `mysqlctld`, not `mysqld` itself. This is where `mysqld` is shelled out https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/mysqld.go#L401 and it only has a couple env vars.

**Comment by Smana** [comment]
thanks @derekperkins ! I followed your advices in order to load the memory allocator before the `mysqld` command as follows

```
git diff docker/lite/Dockerfile
diff --git a/docker/lite/Dockerfile b/docker/lite/Dockerfile
index a63321a42..6bb0f2cf6 100644
--- a/docker/lite/Dockerfile
+++ b/docker/lite/Dockerfile
@@ -69,6 +69,11 @@ ENV PATH $VTROOT/bin:$PATH
 # Copy binaries (placed by build.sh)
 COPY --from=staging /vt/ /vt/
 
+# Load memory allocator
+RUN mv /usr/sbin/mysqld /usr/sbin/mysqld_orig
+COPY ./mysqld.sh /usr/sbin/mysqld
+RUN chmod 755 /usr/sbin/mysqld
+
 # Create mount point for actual data (e.g. MySQL data dir)
 VOLUME /vt/vtdataroot
 USER vitess
```
Then I checked that the running container contains the bash script:
```

kubectl exec zone1-dailymotion-0-replica-0 -c mysql cat /usr/sbin/mysqld
#!/bin/bash
export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
/usr/sbin/mysqld_orig "$@"
```

I ran a new benchmark
```
./tpcc.lua --mysql-host=vitess --mysql-port=3306 --mysql-db=dailymotion --time=300 --threads=128 --report-interval=1 --tables=10 --scale=10 --db-driver=mysql --use-fk=0 prepare
```

Unfortunately I still face the same issue. Maybe I'm still missing something ? :/

![image](https://user-images.githubusercontent.com/4101366/70853351-1d6bc900-1ead-11ea-8bdf-69a7b34caa31.png)

Note that I have buffer pool set to 2G
![image](https://user-images.githubusercontent.com/4101366/70853354-2bb9e500-1ead-11ea-8aaf-6f71eecb9413.png)

**Comment by gedgar** [comment]
Passthrough support for LD_PRELOAD was added in #5730, which makes it simpler to switch the allocator to tcmalloc.

Closing this issue for now but please feel free to reopen if you are still having issues @Smana. Thank you!
