### ISSUE TITLE
Panic: Runtime error while tablet teardown in python tests

### ISSUE THREAD

**Issue by arindamnayak** [vitessio/vitess#5538]
#### Overview of the Issue

There is a panic runtime error while running python testcase [(initial_sharding.py)](https://github.com/vitessio/vitess/blob/master/test/initial_sharding.py). Usually this error comes up,  when the tablets are being killed -- [here](https://github.com/vitessio/vitess/blob/master/test/initial_sharding.py#L641).

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Run the testcase using `./test/initial_sharding.py`. Since we need the log files to examine , better to run using this command `go run test.go initial_sharding --keep-data` 
2. Go to the `vtdataroot/tmp` directory, and check the vttablet stderr file. The files for vttablet can be identified with this pattern `vttablet-{tablet-UID}.stderr`. 
3. For this particular test, there are 9 tablets. Check the the log files (from the above pattern) with the max size. 
4. Towards, the end of the log file, you can see below stacktrace.

#### Log Fragments

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xaf3281]

goroutine 49 [running]:
vitess.io/vitess/go/vt/topo.(*Server).GetShard(0xc0004ad9c0, 0x15f39e0, 0xc000fc24e0, 0xc0017f9ce0, 0xd, 0xc0017f9cd9, 0x3, 0x0, 0x0, 0x0)
	/home/arindam-local/code/gopath/src/vitess/go/vt/topo/shard.go:198 +0x251
vitess.io/vitess/go/vt/topo.(*Server).UpdateShardFields(0xc0004ad9c0, 0x15f39e0, 0xc000fc24e0, 0xc0017f9ce0, 0xd, 0xc0017f9cd9, 0x3, 0xc001187dc8, 0xc001187db0, 0xc0002229a0, ...)
	/home/arindam-local/code/gopath/src/vitess/go/vt/topo/shard.go:254 +0x77
vitess.io/vitess/go/vt/vttablet/tabletmanager.syncShardMaster(0x15f39e0, 0xc000fc24e0, 0xc0004ad9c0, 0xc000c92dc0, 0xc2c61fb, 0xed5801b88, 0x0, 0x0, 0x0, 0x0)
	/home/arindam-local/code/gopath/src/vitess/go/vt/vttablet/tabletmanager/shard_sync.go:156 +0x197
vitess.io/vitess/go/vt/vttablet/tabletmanager.(*ActionAgent).shardSyncLoop(0xc00020c000, 0x15f3960, 0xc000435080)
	/home/arindam-local/code/gopath/src/vitess/go/vt/vttablet/tabletmanager/shard_sync.go:102 +0x393
created by vitess.io/vitess/go/vt/vttablet/tabletmanager.(*ActionAgent).startShardSync
	/home/arindam-local/code/gopath/src/vitess/go/vt/vttablet/tabletmanager/shard_sync.go:243 +0x124
```

**Comment by arindamnayak** [comment]
After merging #5667 , I am not able reproduce this / this error is not coming up anymore. Should we close this issue?

**Comment by deepthi** [comment]
> After merging #5667 , I am not able to reproduce this / this error is not coming up anymore. Should we close this issue?

thanks @enisoc!
