### ISSUE TITLE
VTGate does not rollback in-flight transactions when shut down

### ISSUE THREAD

**Issue by mikrobi** [vitessio/vitess#5553]
We experience a bunch of 

```
vttablet: rpc error: code = ResourceExhausted desc = transaction pool connection limit exceeded
```

errors each time we deploy VTGate. After [discussing this problem in Slack](https://vitess.slack.com/archives/C0PQY0PTK/p1575988316498700) @sougou [noted](https://vitess.slack.com/archives/C0PQY0PTK/p1576082927016000?thread_ts=1575988316.498700&cid=C0PQY0PTK) that VTGate does not rollback in-flight transactions on [shut down](
https://github.com/vitessio/vitess/blob/253b9ea692064c4e2c54b41dc9a89d557b85b05c/go/vt/vtgate/plugin_mysql_server.go#L413)

To avoid leaving transactions unfinished in the tablet where they would linger until the transactions timeout, we probably want them to rollback once the lame duck period has expired? 

/cc @drogart and @tomkrouper
/cc @dweitzman who might also be interested in this issue

**Comment by dweitzman** [comment]
As a note: this is specifically with the mysql protocol where a transaction happens on a single gate. It wouldn't be an issue with grpc, where gates are stateless and interchangeable (although the _clients_ of the gates might fail to kill grpc transactions if they shut down ungracefully).

**Comment by drogart** [comment]
Very interesting!

So, the hypothesis is that in flight txns on a vtgate do not complete during the lame duck period, then get left hanging on the tablet and consume a connection pool slot?

I guess we can either:
- bring the mysql protocol behavior in line with the grpc behavior
- increase the lame duck period (though this will still leave a long tail of txns this could happen to)

Any other ideas to alleviate this?

**Comment by dweitzman** [comment]
The useful behavior here would be for vtgate to roll back any in-progress mysql protocol transactions at the end of the lame duck period.
