### ISSUE TITLE
Vitess wrong results: show character set where

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5584]
Vtgate parses but handles this query incorrectly:
```
mysql> show character set where charset = 'utf8mb4';
+---------+---------------+--------------------+--------+
| Charset | Description   | Default collation  | Maxlen |
+---------+---------------+--------------------+--------+
| utf8    | UTF-8 Unicode | utf8_general_ci    |      3 |
| utf8mb4 | UTF-8 Unicode | utf8mb4_general_ci |      4 |
+---------+---------------+--------------------+--------+
2 rows in set (0.00 sec)
```

It was issued by MySQL workbench, and is expected to return 1 row.

**Comment by Ronihe** [comment]
Per @deepthi, right now the results returned from a `show charset` or `show character set` are hardcoded to be just these 2 rows. We could filter on the 2 rows, but we don't really want to expand the results or forward the query to an underlying mysql because vitess only supports these 2 charsets.
