### ISSUE TITLE
vtgate stuck at crashloop

### ISSUE THREAD

**Issue by philipposkhos** [vitessio/vitess#5618]
Hi, I am trying to follow the Vitess official doc to install Vitess. But when I was trying to `helm install ../../helm/vitess -f 101_initial_cluster.yaml --generate-name` , vtgate got CrashLoopBackOff like below.

> commerce-apply-schema-initial-jhg8h        1/1     Running            0          92s
commerce-apply-vschema-initial-kxj8f       1/1     Running            0          92s
etcd-global-mhl7hl2kcw                     1/1     Running            0          92s
etcd-operator-84cf6bc5d5-7chwm             1/1     Running            0          3m23s
etcd-zone1-h4ntbqvkq2                      1/1     Running            0          92s
vtctld-8557c6f9df-p22cj                    1/1     Running            2          92s
vtgate-zone1-59684f87b9-547pv              0/1     CrashLoopBackOff   3          92s
zone1-commerce-0-init-shard-master-c5whl   1/1     Running            0          92s
zone1-commerce-0-rdonly-0                  0/6     Pending            0          92s
zone1-commerce-0-replica-0                 0/6     Pending            0          92s
zone1-commerce-0-replica-1                 0/6     Pending            0          92s

I tried `kubectl logs vtgate-zone1-59684f87b9-547pv` . It turned out a error 

> E1223 08:35:34.809887       1 topology_watcher.go:192] cannot get tablets for cell: zone1: node doesn't exist: /vitess/global/cells/zone1/CellInfo

I try to search this issue on internet. But sadly, I can't find anything useful. Therefore, I post on here asking for help. 

My install step:
Two CentOS 7 VM on vultr.

1. Install kubernetes by following official Doc "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/". apply `flannel` network and another server has been joined into the network. 

2. Install etcd-operator by following "https://github.com/coreos/etcd-operator/blob/master/doc/user/install_guide.md"

3. Install helm 

> curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh

4. trying to install 101_initial_cluster.yaml
`helm install ../../helm/vitess -f 101_initial_cluster.yaml --generate-name`

then the issue ocurred.

Any idea / help will be appreciated. Thanks

**Comment by derekperkins** [comment]
@philipposkhos Helm 3 isn't supported yet by Vitess and more importantly by etcd-operator. It's very likely that your etcd-operator install never installed the crds, so there isn't an etcd instance running for the Vitess topology server.

**Comment by philipposkhos** [comment]
> @philipposkhos Helm 3 isn't supported yet by Vitess and more importantly by etcd-operator. It's very likely that your etcd-operator install never installed the crds, so there isn't an etcd instance running for the Vitess topology server.

Hi derek,

Thanks for the reply. But got the same error crashloop. I tried to replace helm 3 to helm 2 by the following step:

> curl -LO https://git.io/get_helm.sh
chmod 700 get_helm.sh
./get_helm.sh
 `helm init`

this time I met another error when I was trying `helm install ../../helm/vitess -f 101_initial_cluster.yaml`. I got `Error: no available release name found`. After I input the method from internet : 

> kubectl create serviceaccount --namespace kube-system tiller
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

I finally ran `helm install ../../helm/vitess -f 101_initial_cluster.yaml` successfully. 
Sadly, the result is vtgate still crashloop and the logs says `E1224 06:46:38.068558       1 topology_watcher.go:192] cannot get tablets for cell: zone1: node doesn't exist: /vitess/global/cells/zone1/CellInfo`

> NAME                                       READY   STATUS             RESTARTS   AGE
commerce-apply-schema-initial-8pf97        1/1     Running            0          8m31s
commerce-apply-vschema-initial-cr8n2       1/1     Running            0          8m31s
etcd-global-wwfsm84gn2                     1/1     Running            0          8m31s
etcd-operator-84cf6bc5d5-fbnzm             1/1     Running            0          17m
etcd-zone1-8dg9thvkch                      1/1     Running            0          8m31s
vtctld-8557c6f9df-t8hqj                    1/1     Running            2          8m32s
vtgate-zone1-59684f87b9-xdmpl              0/1     CrashLoopBackOff   6          8m32s
zone1-commerce-0-init-shard-master-2ghcw   1/1     Running            0          8m31s
zone1-commerce-0-rdonly-0                  0/6     Pending            0          8m31s
zone1-commerce-0-replica-0                 0/6     Pending            0          8m31s
zone1-commerce-0-replica-1                 0/6     Pending            0          8m31s


`

**Comment by derekperkins** [comment]
Did you reinstall etcd-operator? Can you verify that it is actually running?

Also, Vitess isn't RBAC aware, so it may not work if you have RBAC enabled.

**Comment by philipposkhos** [comment]
> Did you reinstall etcd-operator? Can you verify that it is actually running?
> 
> Also, Vitess isn't RBAC aware, so it may not work if you have RBAC enabled.

Thanks for the reply.

Yes. I reinstalled the server and re-did all steps. Just replace the helm3 to helm2.

But actually I am not sure etcd-operator is actually running. Below is my install etcd-operator steps:

> git clone https://github.com/coreos/etcd-operator.git
/root/etcd-operator/example/rbac/create_role.sh
echo '' > /root/etcd-operator/example/deployment.yaml
echo 'apiVersion: apps/v1' >> /root/etcd-operator/example/deployment.yaml
echo 'kind: Deployment' >> /root/etcd-operator/example/deployment.yaml
echo 'metadata:' >> /root/etcd-operator/example/deployment.yaml
echo '  name: etcd-operator' >> /root/etcd-operator/example/deployment.yaml
echo 'spec:' >> /root/etcd-operator/example/deployment.yaml
echo '  selector:' >> /root/etcd-operator/example/deployment.yaml
echo '    matchLabels:' >> /root/etcd-operator/example/deployment.yaml
echo '      app: etcd-operator' >> /root/etcd-operator/example/deployment.yaml
echo '  replicas: 1' >> /root/etcd-operator/example/deployment.yaml
echo '  template:' >> /root/etcd-operator/example/deployment.yaml
echo '    metadata:' >> /root/etcd-operator/example/deployment.yaml
echo '      labels:' >> /root/etcd-operator/example/deployment.yaml
echo '        app: etcd-operator' >> /root/etcd-operator/example/deployment.yaml
echo '    spec:' >> /root/etcd-operator/example/deployment.yaml
echo '      containers:' >> /root/etcd-operator/example/deployment.yaml
echo '      - name: etcd-operator' >> /root/etcd-operator/example/deployment.yaml
echo '        image: quay.io/coreos/etcd-operator:v0.9.4' >> /root/etcd-operator/example/deployment.yaml
echo '        command:' >> /root/etcd-operator/example/deployment.yaml
echo '        - etcd-operator' >> /root/etcd-operator/example/deployment.yaml
echo '        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md' >> /root/etcd-operator/example/deployment.yaml
echo '        #- -cluster-wide' >> /root/etcd-operator/example/deployment.yaml
echo '        env:' >> /root/etcd-operator/example/deployment.yaml
echo '        - name: MY_POD_NAMESPACE' >> /root/etcd-operator/example/deployment.yaml
echo '          valueFrom:' >> /root/etcd-operator/example/deployment.yaml
echo '            fieldRef:' >> /root/etcd-operator/example/deployment.yaml
echo '              fieldPath: metadata.namespace' >> /root/etcd-operator/example/deployment.yaml
echo '        - name: MY_POD_NAME' >> /root/etcd-operator/example/deployment.yaml
echo '          valueFrom:' >> /root/etcd-operator/example/deployment.yaml
echo '            fieldRef:' >> /root/etcd-operator/example/deployment.yaml
echo '              fieldPath: metadata.name' >> /root/etcd-operator/example/deployment.yaml
kubectl create -f /root/etcd-operator/example/deployment.yaml

After these steps. I type `kubectl get customresourcedefinitions` and `kubectl get pods` that gets the result below. 

> [root@test-db-00 ~]# kubectl get customresourcedefinitions
NAME                                    CREATED AT
etcdclusters.etcd.database.coreos.com   2019-12-25T04:01:04Z


> [root@test-db-00 ~]# kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
etcd-operator-84cf6bc5d5-jpsml   1/1     Running   0          4m50s

Is that meant the etcd-operator is actually running?

**Comment by knight76** [comment]
I have same issue. 

% helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}


 % kubectl get pods,jobs
NAME                                 READY   STATUS             RESTARTS   AGE
pod/etcd-global-5sn76ql8h2           1/1     Running            0          15m
pod/etcd-operator-866875d5dc-n49tl   1/1     Running            0          24m
pod/etcd-zone1-j79gzcpzjk            1/1     Running            0          15m
pod/percona-client                   1/1     Running            0          86s
pod/vtctld-8547867c9c-xs75h          1/1     Running            3          15m
pod/vtgate-zone1-5999cbcd49-ss4tx    0/1     CrashLoopBackOff   7          15m
pod/zone1-commerce-0-rdonly-0        0/6     Pending            0          15m
pod/zone1-commerce-0-replica-0       0/6     Pending            0          15m
pod/zone1-commerce-0-replica-1       0/6     Pending            0          15m

NAME                                           COMPLETIONS   DURATION   AGE
job.batch/commerce-apply-schema-initial        0/1           15m        15m
job.batch/commerce-apply-vschema-initial       0/1           15m        15m
job.batch/zone1-commerce-0-init-shard-master   0/1           15m        15m

% kubectl get pvc
NAME                                    STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
vtdataroot-zone1-commerce-0-rdonly-0    Pending                                      standard       18m
vtdataroot-zone1-commerce-0-replica-0   Pending                                      standard       18m
vtdataroot-zone1-commerce-0-replica-1   Pending                                      standard       18m

**Comment by riupie** [comment]
Same here. It running well on minikube and error on `real cluster`.

**Comment by gedgar** [comment]
Closing this issue as the [Helm charts were deprecated Vitess 7.0](https://github.com/vitessio/vitess/issues/6439).
