### ISSUE TITLE
Changing a tablet's type doesn't update its PromotionRule in local_metadata

### ISSUE THREAD

**Issue by gedgar** [vitessio/vitess#5655]
#### Overview of the Issue
When changing a tablet's type via `ChangeSlaveType`, we don't update the tablet's `PromotionRule` in `_vt.local_metadata`.

#### Reproduction Steps

1. Spin up a cluster with various tablet types (eg `101_initial_cluster.sh`):
```
$ lvtctl ListAllTablets
zone1-0000000100 commerce 0 master localhost:15100 localhost:17100 []
zone1-0000000101 commerce 0 replica localhost:15101 localhost:17101 []
zone1-0000000102 commerce 0 rdonly localhost:15102 localhost:17102 []
```
2. Observe each tablet's `PromotionRule`:
```
$ for tablet in 0 1 2; do mysql -S /home/gary/vtdataroot/vt_000000010$tablet/mysql.sock -uvt_dba -Ne 'select value from _vt.local_metadata where name="PromotionRule"'; done
+---------+
| neutral |
+---------+
+---------+
| neutral |
+---------+
+----------+
| must_not |
+----------+
```
3. Change a tablet's type to something with a different PromotionRule (eg `rdonly` -> `replica`):
```
lvtctl ChangeSlaveType zone1-0000000102 replica
```
4. Note that the new replica's PromotionRule isn't updated to `neutral` and still has the initial `rdonly` value of `must_not`

It looks like a fix for this was being worked on in #3746, though that PR is now closed.

**Comment by ajm188** [comment]
@gedgar i believe this was fixed in either vitess 12 or 13, can you confirm if you still see the issue?

**Comment by gedgar** [comment]
@ajm188, just tested on main (ccf1c60) and confirmed that this is still an issue.

**Comment by deepthi** [comment]
As of v16:
- Orchestrator integration is [no more](https://github.com/vitessio/vitess/blob/main/changelog/16.0/16.0.0/summary.md#orchestrator-integration-deletion
) 
- local_metadata table is [gone](https://github.com/vitessio/vitess/blob/main/changelog/16.0/16.0.0/summary.md#vttablet)

So this issue is no longer relevant.
