### ISSUE TITLE
Support transactional read-only queries against non-master tablet types

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5677]
Currently, if a client targets replica or rdonly Vitess instances (e.g.:  db@replica);  we do not support taking a read-only transaction against the database to get consistent SELECTs.  This breaks a large number of tools that try to do data extraction/transformation.

The limitation manifests itself in vtgate giving an error as soon as you issue a `BEGIN`, e.g.:

```
$ mysql -u root -P 15306 -h 127.0.0.1 commerce@replica
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 5.7.9-Vitess Source distribution
.
.
.
mysql> begin;
ERROR 1105 (HY000): vtgate: http://localhost:15001/: transactions are supported only for master tablet types, current type: REPLICA
```

From a conversation with @sougou , Vitess does not support this because there is no way to target a specific replica with a series of statements.  It is supported in the master case, because there is always just one master, so targeting is not an issue.

**Comment by deepthi** [comment]
Fixed by #6244
