### ISSUE TITLE
Remove python dependency from Java tests

### ISSUE THREAD

**Issue by neowulf** [vitessio/vitess#5687]
`make java_test` requires the python setup to spin up the database cluster.

Replace this dependency with the golang implementation.

**Comment by Its-Maniaco** [comment]
I discovered that there is no Python dependencies for `java_test`. Did I overlook something?
@neowulf @ajm188

**Comment by ajm188** [comment]
It's possible this was filed, then forgotten whenever we removed the python deps. I will close this. We can always re-open if that was wrong.
