### ISSUE TITLE
expose sqlparser's ColumnKeyOption constants

### ISSUE THREAD

**Issue by jmhodges** [vitessio/vitess#5706]
Currently, the ColumnKeyOption type is exposed in the API through ColumnType (and therefore ColumnDefinition type) but its values `colKeyNone`, `colKeyPrimary`, etc. are not exposed. This makes tools like sqlc have to duplicate those constants in order to create tests using the ColumnDefinition types.

**Comment by GuptaManan100** [comment]
They have been exported by https://github.com/vitessio/vitess/pull/12016
