### ISSUE TITLE
Call for maintainers: examples/kubernetes

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5713]
Currently, Vitess supports kubernetes deployments with `examples/helm` and `examples/kubernetes`, with only helm documented on vitess.io.

Only `examples/helm` is actively maintained. I do not believe that there is usage of `examples/kubernetes`, and on the [Vitess monthly call](https://vitess.io/community/) for December, put out the request for maintainers. We have not yet received any expressions of interest, so I am putting out the same call via this issue.

__If we do not receive an expression of interest by end of February 2020, I would like to propose that we deprecate and remove `examples/kubernetes`.__

**Comment by evalsocket** [comment]
@morgo I love to help on that issue. What are the things you want from me ?

**Comment by sougou** [comment]
I met @evalsocket at kubernetes forum. We agreed that it's better to deprecate this in favor of maintaining the helm charts with more focus.

**Comment by evalsocket** [comment]
@sougou @morgo Should I create a PR for removing Kubernetes templates from repository

**Comment by morgo** [comment]
@evalsocket Yes, it's now end of February. We can also mark https://github.com/vitessio/vitess-operator are archived.

**Comment by evalsocket** [comment]
@sougou @morgo 
https://github.com/vitessio/vitess/blob/ad4e47a2dbcdf545823fa5a7fae10aa766489f24/test/cluster/sandbox/vtctl_sandbox.py#L71
https://github.com/vitessio/vitess/blob/ad4e47a2dbcdf545823fa5a7fae10aa766489f24/test/cluster/sandbox/vitess_kubernetes_sandbox.py#L57
https://github.com/vitessio/vitess/blob/ad4e47a2dbcdf545823fa5a7fae10aa766489f24/test/cluster/sandbox/create_schema.py#L36
https://github.com/vitessio/vitess/blob/master/test/cluster/k8s_environment.py 
Do we need all these test after depricating kubernetes template
