### ISSUE TITLE
Vagrant Setup Ask for Maintainer

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#5723]
#### Feature Description

Few years ago it was really hard to build Vitess on Mac OS environments. For that purpose, we created a `vagrant` setup to create a virtual machine that installs all dependencies for Vitess. It looks like few people are actively using this setup and as a matter of fact is currently broken.

If other folks are still using this setup in the community, we would like to get help to find a maintainer. If not we would like to deprecate this setup. 

The deadline to find maintainers is 01/30/2020.

**Comment by morgo** [comment]
Vagrant support has been removed from Docs.
