### ISSUE TITLE
Rewrite session vars to SET_VAR hints

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5751]
#### Feature Description

Currently Vitess either ignores known safe-cases of clients setting session variables, or returns an error. I would like to propose a third-handling, which is to store in thread-local storage on VTGate, and then incorporate into queries as a [`SET_VAR` hint](https://mysqlserverteam.com/new-optimizer-hint-for-changing-the-session-system-variable/).

#### Use Case(s)

This is a MySQL 8.0 only feature. Not all vars are supported by `SET_VAR`, since the hint may be parsed too late in execution.

Some of the most useful cases:

- `unique_checks`: allows us to disable/enable uniqueness checks for faster imports (I think mysqldump does this?)
- `sql-mode`: allows applications to set the modes they require (many apps like wordpress, drupal do this)
- `optimizer-switch`: allow apps to workaround optimizer behavior if they need to. Better than setting a global setting on the mysql server, since you may lose track of why options were set.

**Comment by harshit-gangal** [comment]
This is completed.
