### ISSUE TITLE
gofmt requirement not being enforced at CI

### ISSUE THREAD

**Issue by jmhodges** [vitessio/vitess#5756]
The file `go/vt/vtctld/vtctld.go` is not formatted correctly according to gofmt, according to the commit hooks.

Could we run the commit hooks in CI, too, to avoid this problem from slipping through into unrelated patches? (I'm not sure how this patch got through as is, to be honest.)

This seems related to #5755

**Comment by morgo** [comment]
Long term I think we would like to use golangci as a hosted service. See https://github.com/vitessio/vitess/issues/5503

But it will take some work to review the issues it raises. I do not believe there is a way to just enable it on files that were modified.

I have created PR #5782 for a simple fmt check.
