### ISSUE TITLE
rewriter.go's go:generate make visitor doesn't work

### ISSUE THREAD

**Issue by jmhodges** [vitessio/vitess#5757]
The `go:generate` clause in `go/vt/sqlparser/rewriter.go` doesn't work. It's set to `go:generate make visitor`, but `go generate` will run the `make visitor` command in the sqlparser directory, and not the top-level directory where the `visitor` target is actually defined.

**Comment by sougou** [comment]
@systay Can you try the suggestion by @dweitzman that may allow you to use `go run`? If that works, we can address this issue also.

**Comment by GuptaManan100** [comment]
The code generation has been refactored quite a lot and it is working as intended. If there is still a bug in it, please open a new issue.
