### ISSUE TITLE
Parse check constraints

### ISSUE THREAD

**Issue by kyleconroy** [vitessio/vitess#5760]
#### Feature Description

When creating a table in MySQL, a number of [check constraints](https://dev.mysql.com/doc/refman/8.0/en/create-table-check-constraints.html) can be added.

```
CREATE TABLE t1
(
  CHECK (c1 <> c2),
  c1 INT CHECK (c1 > 10),
  c2 INT CONSTRAINT c2_positive CHECK (c2 > 0),
  c3 INT CHECK (c3 < 100),
  CONSTRAINT c1_nonzero CHECK (c1 <> 0),
  CHECK (c1 > c3)
);
```

The sqlparser module does not currently parse these statements.

#### Use Case(s)

sqlparser is being used by https://github.com/kyleconroy/sqlc, a SQL to Go code generator, and needs this information to correctly generate code from database migrations and other code using CHECK constraints.

**Comment by evalsocket** [comment]
@morgo Would like to work on this but I need a help.

**Comment by morgo** [comment]
@systay and @harshit-gangal are the best mentors. They are Andres Taylor and Harshit on Slack.

**Comment by supra08** [comment]
Hi @evalsocket ! Are you working on this? If not, I would like to take this up.
@morgo ?

**Comment by morgo** [comment]
@supra08 There are no open PRs that correspond to this. Let's give @evalsocket a brief moment to reply, but I think it's yours for the taking :-)

**Comment by supra08** [comment]
Alright thanks!

**Comment by ilknarf** [comment]
@supra08 have you been working on this? If not, I would love to take a crack.

**Comment by supra08** [comment]
No sorry, I haven't been working on it. You can take it up.

**Comment by ilknarf** [comment]
> No sorry, I haven't been working on it. You can take it up.

Thanks for the prompt reply, I'll take a shot at it.
