### ISSUE TITLE
Lookup keyspace IDs in batch when possible

### ISSUE THREAD

**Issue by gedgar** [vitessio/vitess#5781]
#### Feature Description
Currently, we lookup keyspace ids row-by-row: 
https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/vindexes/lookup_internal.go#L64

When possible, it'd be nice if we performed batch lookups.

Per Koz,

> The root of the issue is that if we were to batch the lookups, we have no way of actually associating the retrieved index value with an input. The reason for this is due to the specific collation of the mysql tables. You can't be sure that a string in Golang is going to equate to a given string in MySQL, so you really need to get the specific index out of mysql for the selected input.

@sougou and @koz had previously discussed various ways to make this work,
> one of them being to use a CASE statement to be able to seed the return statement with an index value, and another option being do a bulk query for types that don't have collation concerns and falling back to individual queries for those columns that do.

#### Use Case(s)

>  for our case, most, if not all, of the keys are integer and we do have a lot of queries to fetch the data for a relative large (a few dozen) batch values of a vindex column

**Comment by derekperkins** [comment]
Another option is to use `ORDER BY FIELD(...)` to guarantee return order

**Comment by morgo** [comment]
Another option is to recommend / default binary collations.

I thought it would be a bigger deal, but myrocks only supports binary by default. You need to enable an option for non-binary, and it has a performance hit (additional clustered key lookup; no covering index).

**Comment by gedgar** [comment]
Should be fixed as of 12.0 via https://github.com/vitessio/vitess/pull/8398/
