### ISSUE TITLE
Error: failed to start container "vtctld": Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by yiliaofan** [vitessio/vitess#5823]
run :

vitess/examples/kubernetes/vtctld-up.sh

The problem log is:

`
 Normal   Pulled     22m (x4 over 23m)     kubelet, 10.22.0.7  Successfully pulled image "vitess/lite"
  Normal   Created    22m (x4 over 23m)     kubelet, 10.22.0.7  Created container vtctld
  Normal   Pulling    22m (x4 over 23m)     kubelet, 10.22.0.7  Pulling image "vitess/lite"
  Warning  Failed     22m                   kubelet, 10.22.0.7  Error: failed to start container "vtctld": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/ssl/certs/ca-certificates.crt\\\" to rootfs \\\"/data/docker/overlay2/d08542f98d9c7030b82bcd26f4fc708f707144e1e503c067a0e6c11415b2a111/merged\\\" at \\\"/data/docker/overlay2/d08542f98d9c7030b82bcd26f4fc708f707144e1e503c067a0e6c11415b2a111/merged/etc/ssl/certs/ca-certificates.crt\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
  Warning  BackOff    2m59s (x95 over 22m)  kubelet, 10.22.0.7  Back-off restarting failed container
`
Thanks~

**Comment by gedgar** [comment]
Closing this issue as the `examples/kubernetes` directory/example has been deleted/deprecated in favor of https://vitess.io/docs/get-started/operator/. 

Please feel free to reopen if you're still having issues following that guide. Thank you!
