### ISSUE TITLE
Vitess clustering and testing problems

### ISSUE THREAD

**Issue by ResearchRogerPan** [vitessio/vitess#5830]
The following problems were encountered when the cluster was built:
1. When building a table or setting a vschema, it causes a few vttablets to lose their connection;
2. Ignore question 1, I import data through sql files (connecting one of the vtgates) will result in a "too many connections" error；
3. How to check the vschema settings successfully, through the web side can be detected?

Cluster environment:

- 9 physics machines

- 8 machines set 8 vtgate and 8 vttablet-mysqlsets,

- 1 machine set 3 zookeepers and 1 vtctld

The profile is as follows:

vtgate/vtctld/zk: official vtgate-up.sh/vtctld-up.sh/zk-up.sh script
env.sh:

`if [ "${TOPO}" = "zk2" ]; then
    zkcfg=(\
        "1@$hostname:28881:38881:21811" \
        "2@$hostname:28882:38882:21812" \
        "3@$hostname:28883:38883:21813" \
        )
    printf -v zkcfg ",%s" "${zkcfg[@]}"
    zkcfg=${zkcfg:1}

    zkids='1 2 3'

    ZK_SERVER="172.18.186.219:21811,172.18.186.219:21812,172.18.186.219:21813"
    TOPOLOGY_FLAGS="-topo_implementation zk2 -topo_global_server_address ${ZK_SERVER} -topo_global_root /vitess/global"

    mkdir -p $VTDATAROOT/tmp`

vttablet-up.sh: 

`cell=${CELL:-'VTDB'}
keyspace=${KEYSPACE:-'vitess'}
shard=${SHARD:-'0'}
uid_base=${UID_BASE:-'1000'}
port_base=$[15000 + $uid_base]
grpc_port_base=$[16000 + $uid_base]
mysql_port_base=$[17000 + $uid_base]
tablet_hostname=''

if [ "$TRAVIS" == true ]; then
  tablet_hostname=`hostname -i`
fi

script_root=`dirname "${BASH_SOURCE}"`
source $script_root/env.sh

init_db_sql_file="$VTROOT/config/init_db.sql"

mkdir -p $VTDATAROOT/backups
uids=${TABLETS_UIDS:-'0 1 2'}

for uid_index in $uids; do
  uid=$[$uid_base + $uid_index]
  mysql_port=$[$mysql_port_base + $uid_index]
  printf -v alias '%s-%010d' $cell $uid
  printf -v tablet_dir 'vt_%010d' $uid

  export KEYSPACE=$keyspace
  export SHARD=$shard
  export TABLET_ID=$alias
  export TABLET_DIR=$tablet_dir
  export MYSQL_PORT=$mysql_port

  tablet_type=replica
  if [[ $uid_index -gt 1 ]]; then
    tablet_type=rdonly
  fi

  export TABLET_TYPE=$tablet_type

  echo "Starting MySQL for tablet $alias..."
  action="init -init_db_sql_file $init_db_sql_file"
  if [ -d $VTDATAROOT/$tablet_dir ]; then
    echo "Resuming from existing vttablet dir:"
    echo "    $VTDATAROOT/$tablet_dir"
    action='start'
  fi
  $VTROOT/bin/mysqlctl \
    -log_dir $VTDATAROOT/tmp \
    -tablet_uid $uid \
    -mysql_port $mysql_port \
    $action &
done

wait

optional_auth_args=''
if [ "$1" = "--enable-grpc-static-auth" ];
then
	  echo "Enabling Auth with static authentication in grpc"
    optional_auth_args='-grpc_auth_mode static -grpc_auth_static_password_file ./grpc_static_auth.json -grpc_auth_static_client_creds ./grpc_static_client_auth.json'
fi

for uid_index in $uids; do
  uid=$[$uid_base + $uid_index]
  port=$[$port_base + $uid_index]
  grpc_port=$[$grpc_port_base + $uid_index]
  printf -v alias '%s-%010d' $cell $uid
  printf -v tablet_dir 'vt_%010d' $uid
  printf -v tablet_logfile 'vttablet_%010d_querylog.txt' $uid
  tablet_type=replica
  if [[ $uid_index -gt 1 ]]; then
    tablet_type=rdonly
  fi

  $VTROOT/bin/vttablet \
    $TOPOLOGY_FLAGS \
    -log_dir $VTDATAROOT/tmp \
    -log_queries_to_file $VTDATAROOT/tmp/$tablet_logfile \
    -tablet-path $alias \
    -tablet_hostname "$tablet_hostname" \
    -init_keyspace $keyspace \
    -init_shard $shard \
    -init_tablet_type $tablet_type \
    -health_check_interval 5s \
    -enable_semi_sync \
    -enable_replication_reporter \
    -backup_storage_implementation file \
    -file_backup_storage_root $VTDATAROOT/backups \
    -restore_from_backup \
    -port $port \
    -grpc_port $grpc_port \
    -service_map 'grpc-queryservice,grpc-tabletmanager,grpc-updatestream' \
    -pid_file $VTDATAROOT/$tablet_dir/vttablet.pid \
    -vtctld_addr http://$hostname:$vtctld_web_port/ \
    $optional_auth_args \
    > $VTDATAROOT/$tablet_dir/vttablet.out 2>&1 &
done

for uid_index in $uids; do
  port=$[$port_base + $uid_index]
  while true; do
   curl -I "http://$hostname:$port/debug/status" >/dev/null 2>&1 && break
   sleep 0.1
  done;
done;`

default.cnf:

`connect_timeout = 60
innodb_buffer_pool_size = 8G
max_allowed_packet = 16M
max_connections = 3000`

Problem log:

`1.ERROR 1040 (08004) at line 2992: vtgate: http://manager211.cdh:15001/: execInsertSharded: target: vitess.13-26.master, used tablet: VTDB-200 (172.18.186.212): vttablet: rpc error: code = ResourceExhausted desc = Too many connections (errno 1040) (sqlstate 08004) (CallerID: userData1)

2.If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).`

**Comment by harshit-gangal** [comment]
@ResearchRogerPan were you able to move forward?

**Comment by GuptaManan100** [comment]
Closing this issue. Reopen in case of further updates.
