### ISSUE TITLE
Suggestion: Remove parens from AST

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#5835]
Today,  we strive pretty hard to preserve the queries passed through Vitess as the user entered them. One of the things we do is to keep parenthesis in the AST, so they can be written out again before being sent by `vttablet` to `mysqld`.

Unfortunately, this means that the code analysing expressions needs to do a lot of extra work to ignore parenthesis that do not really add any semantic state.

I propose that we stop using the parenthesis as an AST node, and just insert them where needed according to the precedence rules of SQL when going back to a string. This would make our code simpler, but if you insert extra parenthesis into your queries, they will have been removed by the time they reach mysqld.

The code to add them back in would look something like this:
[Code](https://github.com/systay/vitess/blob/db2a7d75414255afb0d9a9f06cd06c5c09dcb51b/go/vt/sqlparser/unparser.go)
[Tests](https://github.com/systay/vitess/blob/db2a7d75414255afb0d9a9f06cd06c5c09dcb51b/go/vt/sqlparser/unparser_test.go)

WDYT?

**Comment by systay** [comment]
I've been working on this here: #5906

**Comment by harshit-gangal** [comment]
@systay I believe this can be closed now.
