### ISSUE TITLE
Flexibility to provide backup engine on the helm chart

### ISSUE THREAD

**Issue by boopathykpm** [vitessio/vitess#5847]
#### Feature Description

Configure the database engine, while creating the Vitess cluster using the helm chart. 

#### Use Case(s)

Currently, the helm chart is supporting the built-in database backup engine. When I want to use the `xtrabackup` as a backup engine, there is no provision to pass the database engine. 

It would be great if we can able to pass the database engine as below. 
```
backup:
    enabled: false
    database_engine: xtrabackup
```

It would provide flexibility to configure the desired database backup engine.

**Comment by deepthi** [comment]
helm charts are deprecated, hence closing.
