### ISSUE TITLE
Support MySQL 8.0 PARTITION BY clause in MySQL 8.0 mode

### ISSUE THREAD

**Issue by sverch** [vitessio/vitess#5852]
#### Feature Description

MySQL 8.0 supports the PARTITION BY clause in queries: https://dev.mysql.com/doc/refman/8.0/en/window-functions-usage.html

#### Use Case(s)

Vitess could support this clause when the vtgate is started with `-mysql_server_version` set to 8.0.

The use case is the general use case of when this would be useful in a query.  For example, given a table:

```
      id            timestamp         report_date      value      note
1     A           1pm                  2020-01-02     1.0          original report and publish
2     A            2pm                   2020-01-02     1.1          original report and publish
3     A            3pm                   2020-01-02     1.2          original report and publish
4     A            1pm                   2020-01-03     1.01        reported correction on row 1
6     B            1pm                   2020-01-02     3.2           original report and publish
7     B           2pm                  2020-01-02     3.3           original report and publish
8     B            2pm                   2020-01-03     3.1           reported correction on row 7
```

The query to select the latest `report_date` for each `id`+`timestamp` combination could look like:

```
SELECT a.id, a.timestamp, a.value, a.r from (SELECT id, timestamp, value, max(report_time) over (partition by id, timestamp order by timestamp) r from ts_table) a
    INNER JOIN ts_table b
    ON a.id = b.id
    And a.timestamp = b.timestamp
    AND a.r = b.report_time
    And a.value=b.value;
```

**Comment by sverch** [comment]
@aquarapid Do you think this should go in the MySQL 8.0 compatibility project?  Also wondering if there are alternatives to accomplish the same thing.

**Comment by aquarapid** [comment]
I would recommend lumping this together as "Support for MySQL 8.0 Window functions".  #4099 already covered a bunch of them (along with other stuff).

**Comment by sverch** [comment]
@aquarapid Ah, I didn't know about that one.  Thanks!  Should we add `PARTITION BY` to the scope of that issue then, and close this as a duplicate?

**Comment by aquarapid** [comment]
I would leave that to @systay ?  Not sure if we can (or will) implement window functions in a piecemeal fashion.  I would guess that it would fall under #4099, yes

**Comment by 413n** [comment]
Has this ever been implemented? Else how is it placed priority-wise? Would be really cool to use this

**Comment by systay** [comment]
This is already supported in Vitess
