### ISSUE TITLE
Applying VSchema referencing missing keyspace hides all keyspaces from UI

### ISSUE THREAD

**Issue by RyanLeonardSpruce** [vitessio/vitess#5867]
#### Overview of the Issue

On a healthy Vitess deployment with several keyspaces, applying a VSchema that references a keyspace that has never been initialized (by creating tablets for it) causes UI issues, including the fact that the UI doesn't show any of the keyspaces that do exist.

The nodes are visible in the vtgate UI, and everything goes back to normal after creating tablets for the keyspace.

#### Reproduction Steps

1. Create a standard Vitess deployment, with 1+ keyspaces.  They should be visible in the Vitess UI.
1. Apply a VSchema for a keyspace that doesn't exist.
1. The UI shows zero keyspaces.

#### Binary version
Example:

```sh
vagrant@ubuntu-bionic:~$ vitess/bin/vtctld --version
Version: 7835ecca4 (Git branch 'master') built on Wed Feb 12 19:18:44 UTC 2020 by root@ubuntu-bionic using go1.13.4 linux/amd64
```

(On the fork for the Region VIndex: https://github.com/vitessio/vitess/pull/5806)

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`):
  `Ubuntu 18.04.4`
- Kernel version (output of `uname -sr`):
  `Linux 4.15.0-76-generic`
- Architecture (output of `uname -m`):
  `x86_64`

Slack thread: https://vitess.slack.com/archives/C0PQY0PTK/p1582750176043500

![Screenshot from 2020-02-26 15-48-49](https://user-images.githubusercontent.com/57719367/75449677-63c4b600-593b-11ea-83ec-c5694db65dc7.png)

**Comment by derekperkins** [comment]
We've seen this happen too
