### ISSUE TITLE
Set 30 minute timeout for all github action workflows

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5927]
#### Feature Description

30 minutes should be good enough for any test. If it exceeds it, currently something is going wrong. If it exceeds it due to development changes, we can bump the limit temporarily while we investigate splitting tests better.

This seems like a good threshold to set so that we can ensure our continued productivity with fast tests.

It looks [straight forward](https://github.community/t5/GitHub-Actions/Limit-runtime/td-p/32841) to enable it in GitHub actions.

I am hoping new contributors may be interested in picking this up, and learning a little about the CI system :-)

**Comment by J0** [comment]
Hey @morgo, 

This seems like a quick fix that I could make. At the same time, it seems like there's a shortage of Good First Issues on the repo for newcomers to fix.

I'll wait for another five days and if no one pick this up I'll file a Pull Request to fix this. How does that sound?

Joel

**Comment by morgo** [comment]
SGTM, and I'll work on tagging more issues for new comers :-)
