### ISSUE TITLE
Allow use of --use-memory with xtrabackup --prepare during restore

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5946]
Currently, we just run the prepare phase of the xtrabackup restore with the `--defaults-file`, `--prepare` and `--target-dir` flags.  We should allow passing of the `--use-memory` flag, with a parameter, to allow speeding up of the prepare phase.  Since the restore (and prepare phase) are typically run on the shard host, there is usually plenty of memory available to dedicate to speeding up this phase.

Documentation for the flag here:  https://www.percona.com/doc/percona-xtrabackup/2.4/xtrabackup_bin/xbk_option_reference.html#cmdoption-xtrabackup-use-memory

**Comment by zhangjin-007** [comment]
@deepthi Can you provide vttablet with the complete configuration parameters of xtrabackup, how to restore data from a mysql backup? Thank you very much

**Comment by deepthi** [comment]
The documentation is at https://vitess.io/docs/user-guides/backup-and-restore/
Please let us know if it needs to be improved.
