### ISSUE TITLE
Simplify vttablet schema -> Breaking change

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#5950]
This announce includes more detail from #5569 

Most of the schema info vttablet currently loads is unused. We'll be deprecating the following:
* All table stats. These were also exported as variables in `/debug/vars`. They will not be exported any more.
* Index information: We only need the primary key column names. So, only this information will be loaded.
* Column information: The column info tracked if it was an auto-inc, and its default values. These will not be loaded.

Currently, the schema loader loops on every table to load additional metadata about it. The above changes allow us to load all the information in one scan. We'll continue to use the `BaseShowTables` query to scan table comments.

For looking up the primary key columns, we'll use the following query, which can load the pk info for all tables in a single read.

```
select table_name, column_name from information_schema.key_column_usage where table_schema='a' and constraint_name='PRIMARY' order by table_name, ordinal_position
```

At this point, the schema info is only used by the following features:
* Sequences
* VStreamer
* Messager

If the schema load is slow in spite of the above optimizations, we can look at starting the query service upfront, and make these features wait for the schema to load lazily.

**Comment by dweitzman** [comment]
I find myself missing the convenience of having the index information on a tablet's /schemaz

Was the index information removed for performance reasons or just because it didn't seem to be needed for anything?

**Comment by sougou** [comment]
It wasn't needed for anything. But also performance reasons. The algorithm has been changed to build everything in a single scan. If we can also collect the index info that way, we should be able to bring it back.
