### ISSUE TITLE
[vtctld] Topology browser in v1 app no longer working

### ISSUE THREAD

**Issue by brirams** [vitessio/vitess#6003]
#### Overview of the Issue

The `Topology Browser` UI at `https://${vtctld-host}/app/#/topo/` can not inspect beyond two levels deep into any topo path. This seems to be due to the fact that it's trying to hit a URL where the second `/` is url encoded so instead of `/api/topodata/global/cells` it's hitting `api/topodata/global%2Fcells`, causing a 404 and an operator freakout since the page only shows an empty page.

#### Reproduction Steps

1. From `https://${vtctld-host}/app/#/topo/`, click into `global` topo:

<img width="1278" alt="Screen Shot 2020-04-01 at 15 40 17" src="https://user-images.githubusercontent.com/1807482/78193441-667d6400-742f-11ea-87cb-90c6494361a1.png">

2. Click into any path, for this example, `cells`. Note there's no data and browser console shows a 404:

<img width="1274" alt="Screen Shot 2020-04-01 at 15 40 25" src="https://user-images.githubusercontent.com/1807482/78193452-6b421800-742f-11ea-9e36-c59f14d08667.png">
<img width="671" alt="Screen Shot 2020-04-01 at 15 41 40" src="https://user-images.githubusercontent.com/1807482/78193478-814fd880-742f-11ea-8b40-0c363ed5dfff.png">

<img width="1278" alt="Screen Shot 2020-04-01 at 15 42 48" src="https://user-images.githubusercontent.com/1807482/78193463-772dda00-742f-11ea-860e-c6651d710311.png">

#### Binary version
https://github.com/tinyspeck/vitess

**Comment by aquarapid** [comment]
@brirams can you clarify what this is hitting?  This doesn't seem to be the regular vanilla vtctld topo browser, which seems to work fine?

![vtctld-topo](https://user-images.githubusercontent.com/772642/134387336-d42b96a9-cafc-47d9-943a-197773c40947.png)

**Comment by captain-wolf** [comment]
Closing as this is an issue in V1 that is no longer used.
