### ISSUE TITLE
Publish the helm chart as helm repo

### ISSUE THREAD

**Issue by boopathykpm** [vitessio/vitess#6060]
## Feature Description

It would be great if there is an option to install the Vitess helm chart directly without cloning the git repository. 

#### Use Case(s)

It would be unnecessary to clone the whole repository and install the chart from the repo. It will be great if the helm is packaged as a helm chart and pushed somewhere, where everyone can install directly without cloning the repo.

**Comment by szmytson** [comment]
Second that. It would be great to have the helm chart in a repo.
Maybe this will help. https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by Anders-PlanetScale** [comment]
I am closing this issue as the the Vitess helm chart is no longer being maintained.
