### ISSUE TITLE
mysql unit test failure in CI

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6067]
--- FAIL: TestListenerShutdown (0.00s)
##[error]    server_test.go:253: listening on address '127.0.0.1' port 35367
##[error]    server_test.go:1341: Expected connRefuse delta=1, got 0
FAIL
FAIL	vitess.io/vitess/go/mysql	2.374s

Probably related to #5631

**Comment by GuptaManan100** [comment]
This doesn't seem to be flaky on the CI anymore. Kindly reopen if it resurfaces.
