### ISSUE TITLE
Removing deprecated dbconfig params

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6071]
The user specific connection params like `db-config-app-host` have been deprecated for a long time in favor of the global ones like `db_host` that apply to all users.

The new yaml based approach will not support these, and we'll therefore have to remove these. In order to ensure no loss of functionality, we'll additionally add a `PreferTCP` flag to every user that can force a connection to use TCP even if a socket is specified.

If anyone is still using user-specific overrides, please respond. Tagging @ameetkotian .

**Comment by ameetkotian** [comment]
Thanks for the note @sougou . We'll migrate to db_host

**Comment by GuptaManan100** [comment]
Closing this issue. Reopen if further updates.
