### ISSUE TITLE
vschema: should support back-quoted names

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6123]
VSchema needs to support back-quoted table and column names like
```
keyspace.`a.b`
```

**Comment by ochotinun** [comment]
I have created a schema with auto_increment pointing to a table of type "sequence" which has dots in the name. 
 "auto_increment": {
        "column": "id",
        "sequence": "Roblox.Testing.ScalarFields_seq"
      }
Inserts on the table that had this auto_incrment did not work. I tried backquoting the name of the sequence table in vschema, 
 "auto_increment": {
        "column": "id",
        "sequence": "`Roblox.Testing.ScalarFields_seq`"
      }
this did not solve the problem.

**Comment by sougou** [comment]
Adding clarification on the upcoming fix:

There are three places in the vschema where entries refer to tables:
* lookup vindexes: The table name parameter here is not interpreted during parsing of the vschema and is sent as is to the queries that access the tables. Any valid representation as understood by mysql should already work correctly.
* sequence table name in the AutoIncrement section: This table name is resolved by the vschema loader against a vschema table. Code will be changed to parse back-quoted keyspace and table names.
* routing rules target tables: The table names are resolved by the  vschema loader against a vschema table. Code will be changed to parse back-quoted keyspace and table names.

There are two places in the vschema where entries define table names that are looked up at runtime:
* vschema table name as key
* routing rules source tables

In the above cases, the table names must not be backquoted. Instead one should just concatenate the keyspace name and table name even if they contained special characters. This is because the table name resolver will build such a key to find the table in the vschema hash map. So, it has to be a simple rule that reliably matches what the user specified in the vschema.
