### ISSUE TITLE
Add `vtctlclient WaitForKeyspace commerce`

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#6124]
#### Feature Description

Currently, the local examples have a sleep call at the end of vttablet-up.sh:

https://github.com/vitessio/vitess/blob/0f1551aa78564a12677cbe2cfd744261ecd1bf80/examples/local/scripts/vttablet-up.sh#L60-L69

This is problematic to start with because it is sleeping for each tablet, versus just waiting for the last one. It also uses shell, which is not completely portable. For example, `curl` is actually not reliably available.

I would like to propose we remove the sleep call, and add a new vtctlclient command:
```
vtctlclient WaitForKeyspace commerce
```

As the name suggests, this just waits until the keyspace is healthy. It can have similar semantics to the existing `WaitForDrain` (such as allowing a -timeout). The difference is that WaitForKeyspace only needs the `keyspace`, not `keyspace/shard`:

```
  WaitForDrain [-timeout <duration>] [-retry_delay <duration>] [-initial_wait <duration>] <keyspace/shard> <served tablet type>
```

#### Use Case(s)

- Simplify Examples
- Remove non-portable shell code

**Comment by morgo** [comment]
Just to clarify, there is a second race: after starting a vtgate, it is not immediately queryable by MySQL clients. Currently in the examples code this is solved by a sleep:

https://github.com/vitessio/vitess/blob/3b64e30cbc0bd5156fac05d25a1d1b47654e8536/test/local_example.sh#L30-L32

This is not possible to fix by another `vtctlclient Wait..` command, because vtctlclient does not know about vtgates.

There are two ways to fix this:

### Option 1: Use a MySQL client

This could be solved by using a mysql client and attempting a `select 1` in a loop. We don't currently have a dependency on the `mysql` client in the examples shell code - but we could add it:

https://github.com/vitessio/vitess/blob/3b64e30cbc0bd5156fac05d25a1d1b47654e8536/examples/local/env.sh#L31-L34

### Option 2: Fix startup order in vtgate

The vtgate start script does try and block itself (waiting on the webserver to be listening), but this doesn't work correctly, because the MySQL port comes up after HTTP and the race still occurs. So it could be to fix it so that the webserver starts listening after the MySQL port. Then this code would work correctly:

https://github.com/vitessio/vitess/blob/3b64e30cbc0bd5156fac05d25a1d1b47654e8536/examples/local/scripts/vtgate-up.sh#L46-L56

**Comment by sougou** [comment]
After looking at the examples, this should not be necessary. I believe there is a regression in vttablet where it reports itself healthy before it can serve queries. So, if we fix that, vtgate will come up only when vttablets are ready.

Essentially, the vtgaet `wait_for_tablet_types` flag is this feature.

**Comment by GuptaManan100** [comment]
Closing this issue. Reopen if further updates.
