### ISSUE TITLE
flaky test: srvtopo

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6134]
--- FAIL: TestGetSrvKeyspace (0.90s)
    resilient_server_test.go:315: expected error 'timed out waiting for keyspace', got '<nil>'
E0430 13:23:13.503797   12550 resilient_server.go:461] Initial WatchSrvKeyspace failed for test_cell/test_ks: force long test error
E0430 13:23:13.503813   12550 resilient_server.go:464] WatchSrvKeyspace clearing cached entry for test_cell/test_ks
E0430 13:23:13.503822   12550 resilient_server.go:461] Initial WatchSrvKeyspace failed for test_cell/unknown_ks: node doesn't exist: keyspaces/unknown_ks/SrvKeyspace
E0430 13:23:13.503831   12550 resilient_server.go:464] WatchSrvKeyspace clearing cached entry for test_cell/unknown_ks
E0430 13:23:13.614002   12550 resilient_server.go:461] Initial WatchSrvKeyspace failed for test_cell/unknown_ks: node doesn't exist: keyspaces/unknown_ks/SrvKeyspace
E0430 13:23:13.614020   12550 resilient_server.go:464] WatchSrvKeyspace clearing cached entry for test_cell/unknown_ks
W0430 13:23:13.644674   12550 resilient_server.go:560] Error while watching vschema for cell test_cell (will wait 5s before retrying): node doesn't exist: SrvVSchema
W0430 13:23:13.704985   12550 resilient_server.go:308] GetSrvKeyspaceNames(context.Background, test_cell) failed: force test error (keeping cached value: [test_ks test_ks2])
W0430 13:23:13.735954   12550 resilient_server.go:308] GetSrvKeyspaceNames(context.Background, test_cell) failed: force test error (keeping cached value: [test_ks test_ks2])
E0430 13:23:13.957630   12550 resilient_server.go:310] GetSrvKeyspaceNames(context.Background.WithDeadline(2020-04-30 13:23:13.957462911 -0700 PDT m=+1.359994289 [-187.087µs]), test_cell) failed: force long test error (cached value expired)
FAIL
FAIL	vitess.io/vitess/go/vt/srvtopo	1.371s

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
