### ISSUE TITLE
Create sequences with DDL statements 

### ISSUE THREAD

**Issue by lkburns** [vitessio/vitess#6165]
#### Feature Description

Currently creating a sequence requires creating a sequence table, inserting seed values, and then modifying vschema for the source and target keyspace for enabling the sequence. This should be condensed into a single DDL statement to create the sequence and modify the vindexes accordingly. Additionally, support should be added to set the auto increment flag for a table in the target keyspace. 

#### Use Case(s)

1. User creates a keyspace with a table that requires auto_increment. 
2. User issues a create sequence command such as `CREATE SEQUENCE my_sequence`
3. User sets sequence to be used in target keyspace with `ALTER VSCHEMA ON ks.table_name ADD AUTO_INCREMENT <column name> USING <sequence name>`

**Comment by GuptaManan100** [comment]
This has been implemented. Please open a new issue if further changes are to be requested.
