### ISSUE TITLE
[olap mode] Add a construct to check if a connection has olap enabled

### ISSUE THREAD

**Issue by brirams** [vitessio/vitess#6171]
#### Feature Description

Today, if you enable olap mode on a connection, there is no way to query vitess on that same connection to check if it's been enabled. It would be great to be able to do something along the lines of:

```
mysql> set workload='olap';
Query OK, 0 rows affected
Time: 0.003s
mysql> select @@workload;
+------------------------------------+
| @@workload                         |
|------------------------------------|
| olap                                                    |
+------------------------------------+
```

in order to avoid trying to set olap multiple times on the same connection and getting the following error:
```
mysql> set workload='olap';
Query OK, 0 rows affected
Time: 0.003s
mysql> set workload='olap';
ERROR 1105 (HY000): vtgate: $host:$port/: plan building not supported
```

#### Use Case(s)

- multiplexing different types of queries to olap vs oltp connections based on the results of this check
- not issuing more `set` queries than necessary

**Comment by setassociative** [comment]
Suggestion -- instead of supporting the ability to query the workload I think it'd be nicer if we could make `set workload='olap'` a supported/noop operation in olap mode.

The suggested approach means users will need to introduce an extra round trip that shouldn't strictly be necessary.

**Comment by brirams** [comment]
agreed -- i like that, too

**Comment by demmer** [comment]
Seems to me like we want _both_ the ability to figure out the workload and also make the repeated `set workload='olap'` a no-op when already in olap mode, right?

**Comment by harshit-gangal** [comment]
```
mysql> select @@workload;
+-------------+
| @@workload  |
+-------------+
| UNSPECIFIED |
+-------------+
1 row in set (0.00 sec)

mysql> set workload = 'olap';
Query OK, 0 rows affected (0.00 sec)

mysql> select @@workload;
+------------+
| @@workload |
+------------+
| OLAP       |
+------------+
1 row in set (0.00 sec)

mysql> set workload = 'oltp';
Query OK, 0 rows affected (0.00 sec)

mysql> select @@workload;
+------------+
| @@workload |
+------------+
| OLTP       |
+------------+
1 row in set (0.00 sec)

```

Support is added looks like need to fix select @@workload when it is not set.
cc: @systay
