### ISSUE TITLE
Flaky message test

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#6212]
TestMessage has started failing often on CI:

=== RUN   TestMessage
--- FAIL: TestMessage (16.24s)
##[error]    message_test.go:119: next: 1590059093. must be about 1s after start: 1590059085
##[error]    message_test.go:138: next: 1590059101. must be about 3s after start: 1590059085

I am able to reproduce this often locally as well.

**Comment by deepthi** [comment]
does #6283 fix this?

**Comment by sougou** [comment]
Yes.
