### ISSUE TITLE
Support max memory rows override

### ISSUE THREAD

**Issue by spark4** [vitessio/vitess#6213]
#### Feature Description
I would like to introduce a new query comment directive that will allow us to override max memory row limits on a per-query basis. My intention here is to gather feedback on this proposal and implement it in the next few weeks.

#### Use Case(s)
We currently have warn and max thresholds for the number of rows returned by a given query. These have been great in allowing us to identify areas for improvement. However, there exists no mechanism for adding offending queries to an allow list for overriding these limits when these flags are enabled.

One use case for the proposed query comment directive could be tweaking the warn/max thresholds in the following example workflow:
1. Introduce and tweak warning threshold to find a baseline for the max row limit. 
2. Fix the straightforward ones that hit the warn row limit.
2. Whitelist offending queries for later investigation.
3. Set the max limit to the warning value.

As new queries get introduced, the proposed query comment directive can also be beneficial in our ability to serve new offending queries by adding them to the allow list temporarily while we investigate.

#### Proposal
I would like to propose a new `max_memory_rows_override` query comment directive, which would be opted in on a per-query basis.

The implementation would be quite similar to that for skipping the [plan query cache](https://github.com/vitessio/vitess/pull/3947/files) or the MaxPayloadSizeOverride introduced in [this PR](https://github.com/vitessio/vitess/pull/6143).

**Comment by harshit-gangal** [comment]
Supported via #6430
