### ISSUE TITLE
Modification not allowed using set construct for: sql_mode

### ISSUE THREAD

**Issue by badakhgovind** [vitessio/vitess#6218]
I am using Vitess latest version(vitess:lite-v6.0.20-20200508).
I got error, when I tried to import database script exported from other MySQL server.
Below is the import script example : 
```
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/* Import table and data statments */

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```
Below is warning and one error: 
- 0 row(s) affected, 1 warning(s): 1235 Modification not allowed using set construct for: sql_mode

- Error Code: 1105. vtgate: http://542a33d8ec22:8080/: target: dbschema.0.master, used tablet: tablet-1 (vttablet01): vttablet: rpc error: code = InvalidArgument desc = missing bind var __vtudvOLD_SQL_MODE (CallerID: root)

**Comment by deepthi** [comment]
related to #6107

**Comment by badakhgovind** [comment]
Thanks for reply,
But how can I import sample provided to my database without error?

**Comment by harshit-gangal** [comment]
The linked PR will resolve the error. 
Once we have the set system variable functionality out, you would not see the warnings as well.

**Comment by harshit-gangal** [comment]
Support added.
