### ISSUE TITLE
Is MySQL compatiblity a goal for the sqlparser package?

### ISSUE THREAD

**Issue by kyleconroy** [vitessio/vitess#6228]
Hey there!

I'm the maintainer of https://github.com/kyleconroy/sqlc, a SQL compiler for Go. We currently use the sqlparser package from Vitess to power our MySQL support. Over the last few months, we've run into issues where the parser doesn't support a certain MySQL syntax (https://github.com/vitessio/vitess/issues/5705, https://github.com/vitessio/vitess/issues/5686, https://github.com/vitessio/vitess/issues/5685, https://github.com/vitessio/vitess/issues/5682, https://github.com/vitessio/vitess/issues/5760).

We've been discussing (https://github.com/kyleconroy/sqlc/issues/150) switching to the https://github.com/pingcap/parser package, but that package has a different set of incompatibilities.

Is it a goal of the sqlparser package to be 100% compatible with MySQL? I'm happy to continue using the package and contribute bug fixes and features, but I'd like to make sure that those contributions are wanted. I completely understand in the answer is no. Vitess is not MySQL and isn't aiming to support all of its features.

**Comment by sougou** [comment]
Yes. The goal is to be mysql compatible, with a caveat: The vitess parser will likely remain more permissive than mysql. This is because we often rely on pass-through and rely on mysql to fail such queries. Will this be a problem?

**Comment by mattlord** [comment]
I'm closing this for now as I believe the question has been answered. The goal is to be 100% compatible but we're also not close to that yet with MySQL 8.0 (window functions, CTEs, etc). If there are any specific requests that may impact our scheduling/priority of adding support for anything specific we should use a dedicate issue for that if possible. Thank you!
