### ISSUE TITLE
Support transparent cross-cell migration for vreplication

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6229]
In the current vreplication-based workflows (e.g. `MoveTables`), a vreplication stream will be started for each source shard in the source keyspace.  However, if, during the time the stream is running (which could be hours or days for non-trivial use-cases);  the shard is re-mastered to a replica outside the current cell, the vreplication stream will stop.

Initially this was mysterious to me, until I understood that the vreplication streams initializes the `cell` column in `_vt.vreplication` to empty, which is shorthand for "local cell".  To "fix" the broken stream(s), it's the `cell` column in `_vt.vreplication` for the affected streams can be updated (via `VReplicationExec` to the new cell for the master tablet, and the stream will resume.

In most usages this is not a huge issue;  but with the Vitess Kubernetes Operator, the general best-practice design pattern is to create a cell per cloud provider AZ in a region, so remastering will often/always move a shard master to a different cell, causing the above problem.   In addition, the "target" keyspace vttablet(s) instances may or may not be cell-local when the `MoveTables` is initiated.

**Comment by mattlord** [comment]
I *think* this has been addressed, @aquarapid should we close this?

**Comment by aquarapid** [comment]
With the flexibility in the source and target cell selection in (for example) `MoveTables`, it is now possible to get the behavior (i.e. cross-cell) you may want.
