### ISSUE TITLE
flaky traffic_switcher_test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6234]
--- FAIL: TestTableMigrateNoReverse (1.07s)
##[error]    traffic_switcher_test.go:1404: Code: UNKNOWN
        rpc error: code = DeadlineExceeded desc = context deadline exceeded
        rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by rohit-nayak-ps** [comment]
We haven't seen this for a while now.
