### ISSUE TITLE
flaky TestConsolidation

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6235]
--- FAIL: TestConsolidation (0.21s)
    misc_test.go:292: 
        	Error Trace:	config_test.go:45
        	            				config_test.go:39
        	            				misc_test.go:292
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 3
        	Test:       	TestConsolidation
        	Messages:   	Waits/Histograms/Consolidations/Count

**Comment by deepthi** [comment]
@rohit-nayak-ps do you think you could look at this? It seems like a race.

**Comment by sougou** [comment]
I'll take this on.
