### ISSUE TITLE
Allow charset introducers with vindex column values

### ISSUE THREAD

**Issue by gedgar** [vitessio/vitess#6236]
#### Feature Description
Currently, Vindex column values do not support [charset introducers](https://dev.mysql.com/doc/refman/5.7/en/charset-introducer.html) (or any expression for that matter). 

This can be problematic if you have a BLOB column set as the `from` field of a lookup index and as a column in a lookup table for this vindex. 

For example, attempting to:
```INSERT INTO `Testing.GetByBytesEntity` (`bytes`) VALUES (@1);
SELECT `id`, `bytes` FROM `Testing.GetByBytesEntity` WHERE `id`=last_insert_id();```

Returns the following error:

```vtgate: could not compute value for vindex or auto-inc column: expression is too complex '_binary :vtg19'```

In this case, because parameter 1 is of type `[]byte`, the [go-sql-driver](https://github.com/go-sql-driver/mysql/blob/3f51e4ed70f7313fd12889ebc93fb42ab67d4941/connection.go#L288-L292) prepends the value with the `_binary` charset introducer. Attempts to work around this by sending the binary as a string-encoded equivalent (https://dev.mysql.com/doc/refman/5.7/en/hexadecimal-literals.html) were unsuccessful. 

CC @harshit-gangal

**Comment by aquarapid** [comment]
The PR works for SELECT / INSERT;  but fails on at least some UPDATE statements, viz:

```
mysql> desc t1;
+-----------+----------------+------+-----+---------+-------+
| Field     | Type           | Null | Key | Default | Extra |
+-----------+----------------+------+-----+---------+-------+
| id        | bigint         | NO   | PRI | NULL    |       |
| bytes_key | varbinary(255) | NO   | UNI | NULL    |       |
+-----------+----------------+------+-----+---------+-------+
2 rows in set (0.01 sec)
```

 * Note that column `t1.bytes_key` refers to a lookup vindex.
 
 * Inserts work fine:

```
mysql> insert into t1 (id, bytes_key) values (1,_binary '\0\0');
Query OK, 1 row affected (0.03 sec)
```

 * And so do selects, including selects with `_binary`:

```
mysql> select * from t1;
+----+----------------------+
| id | bytes_key            |
+----+----------------------+
|  1 | 0x0000               |
+----+----------------------+
1 row in set (0.01 sec)
mysql> select * from t1 where bytes_key = _binary '\0\0';
+----+----------------------+
| id | bytes_key            |
+----+----------------------+
|  1 | 0x0000               |
+----+----------------------+
1 row in set (0.01 sec)
```

 * However, updates with `_binary` does not work:
```
mysql> update t1 set `bytes_key`=_binary '\0\001\002' where `id`=1;
ERROR 1235 (HY000): vtgate: http://localhost:15001/: unsupported: Only values are supported. Invalid update on column: bytes_key
```
