### ISSUE TITLE
Queries returning NULL results not being parsed 

### ISSUE THREAD

**Issue by luisfmcalado** [vitessio/vitess#6240]
#### Overview of the Issue

Using ~the latest release~ master the OK packet is missing extra data. Any release from `v6.0.20-YYYYMMDD` is working as expected.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

```json
{
  "sharded": true,
  "vindexes": {
    "unicode_loose_md5": {
      "type": "unicode_loose_md5"
    }
  },
  "tables": {
    "user": {
      "column_vindexes": [
        {
          "column": "username",
          "name": "unicode_loose_md5"
        }
      ]
    }
  }
}
```

1. Deploy the following `schema`:

```sql
CREATE TABLE `user` (
  username varchar(128) NOT NULL,
  age int NOT NULL,
  fake varchar(128) 
);
```

1. Insert `INSERT INTO user (username, age) VALUES ("u1", 18)`
2. Run `SELECT AVG(age) FROM user WHERE username = 'user1'` or `SELECT fake FROM user WHERE username = 'u1'`

The command was run with `MyXQL` library for Elixir which returns:
```
(myxql) lib/myxql/protocol/values.ex:446: MyXQL.Protocol.Values.decode_decimal("", 0, [], [])
    (myxql) lib/myxql/protocol.ex:539: MyXQL.Protocol.decode_resultset/4
    (myxql) lib/myxql/client.ex:198: MyXQL.Client.recv_packets/6
    (myxql) lib/myxql/connection.ex:102: MyXQL.Connection.handle_execute/4
    (db_connection) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:539: DBConnection.parsed_prepare_execute/5
```

Checking the exchanged packets all are the same expect the OK packet which is missing the extra data when responding to the execute statement.

![good](https://user-images.githubusercontent.com/1489866/83235678-2b2ab780-a18a-11ea-9546-699a1ec8ae1a.png)

![bad](https://user-images.githubusercontent.com/1489866/83235698-3251c580-a18a-11ea-9104-52455bdd90cb.png)

#### Binary version

```
Version: a83f21486 (Git branch 'master') built on Tue May 26 11:14:38 UTC 2020 by vitess@bdbc14d2d293 using go1.13.9 linux/amd64
```

#### Operating system and Environment details

Using vitess operator with Kubernetes version 1.15
MariaDB 10.3.22
Running with:
```
vtctld: vitess/lite:mariadb103
vtgate: vitess/lite:mariadb103
vttablet: vitess/lite:mariadb103
vtbackup: vitess/lite:mariadb103
```

#### Log Fragments

The logs do not show any issue.

**Comment by aquarapid** [comment]
Confirmed.

This was broken by da9cfe06cb8dd130206e7d143ef3c5f94120c53d from #6130 .  Reverting that from master will solve your issue until this can be fixed up.
