### ISSUE TITLE
vtctl/vtctlclient RunHealthCheck does not do what you may expect

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6262]
```vtctlclient RunHealthCheck <tablet>```

Only reports an error if a "healthcheck" rpc call to a vttablet fails.  As such, it is really just a connectivity and vttablet liveness check, and is not the same as the "tablet healthcheck", i.e. as reported by the /healthz vttablet page, which will go bad on various downstream conditions (e.g. mysqld down, mysqld lagged, etc.).

We should clarify the documentation and help accordingly.

**Comment by hallaroo** [comment]
A note with this information has been added to https://vitess.io/docs/reference/programs/vtctl/tablets/#runhealthcheck.
