### ISSUE TITLE
shutdown heartbeats when demoting master

### ISSUE THREAD

**Issue by pH14** [vitessio/vitess#6269]
#### Overview of the Issue

vttablet may not auto-recover from a co-master situation when running with semisync and heartbeats.

#### Reproduction Steps

1. Run a shard with multiple replicas, and set `rpl_semi_sync_master_timeout` very high (we use `1000000000000000000` so that masters can never accept writes without a semisync ack)

2. Block incoming network traffic to the current master (e.g. `iptables -I INPUT -j DROP`)

3. Wait for Orch to TER to a new tablet

4. Unblock network traffic to the current master. The old master will observe that it needs to demote itself, but will block and not succeed.

What happens is vttablet will get jammed executing `SET GLOBAL (super_)read_only = 1`, since there is an outstanding write request, from the heartbeat, that is waiting indefinitely for a semisync ack. The MySQL thread state is `Waiting for global read lock`. Relevant MySQL issue: https://bugs.mysql.com/bug.php?id=96644

#### Binary version
Example:

```sh
> vttablet --version
Version: 2cf6f13 (Jenkins build 10) (Git branch 'HEAD') built on Wed May  6 14:41:57 UTC 2020 by root@88e163b90a11 using go1.13.10 linux/amd64
```

#### Log Fragments

```
W0603 20:37:34.134661       7 shard_sync.go:198] Another tablet (test_iad-0455239900) has won master election. Stepping down to REPLICA.
I0603 20:37:34.134672       7 shard_sync.go:216] Active reparents are enabled; converting MySQL to replica.
I0603 20:37:34.138080       7 rpc_replication.go:375] DemoteMaster disabling query service
I0603 20:37:34.138114       7 tabletserver.go:397] TabletServer state: SERVING -> SHUTTING_DOWN (Shutting Down)
I0603 20:37:34.138151       7 tx_engine.go:435] No grace period specified: performing normal wait.
I0603 20:37:34.138171       7 tabletserver.go:397] TabletServer state: SHUTTING_DOWN (Shutting Down) -> NOT_SERVING (Not Serving)
I0603 20:37:34.138398       7 query.go:73] exec SET GLOBAL super_read_only = ON
```

^^ This hangs forever on that last line

I'm not familiar with all of the reasons a master may enter a `NOT_SERVING` state... wondering if we want to close the heartbeat writer each time a master enters into it. This certainly makes sense for the `DemoteMaster` code path at least.

**Comment by deepthi** [comment]
I believe this has already been fixed as of 64c2075. `DemoteMaster` calls `SetServingType` before `SetReadOnly` and that eventually gets to https://github.com/vitessio/vitess/blob/30bf247d1db5019be9bb964bcb73d72b543fb819/go/vt/vttablet/tabletserver/repltracker/repltracker.go#L107

@pH14 do you want to verify this before we close it?

**Comment by pH14** [comment]
Heh, we're unfortunately pretty far off from verifying this one in our environment right now. On the surface, this looks good to me. Since we have a co-master recovery test in our test suite, we can reopen it if we run into trouble as part of our next upgrade 😛

**Comment by deepthi** [comment]
Sounds good. We'll close for now.
