### ISSUE TITLE
Prometheus interface: vtgate_buffer_* metrics cardinality

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#6326]
I'm opening this issue to discuss if we can find a better way to improve/reduce the cardinality of `vtgate_buffer_*` metrics like

- vtgate_buffer_failover_duration_sum_ms 
- vtgate_buffer_last_failover_duration_ms 
- vtgate_buffer_last_requests_dry_run_max  
- vtgate_buffer_requests_buffered 
- vtgate_buffer_requests_drained  
- vtgate_buffer_requests_evicted 
- vtgate_buffer_requests_skipped  
- vtgate_buffer_starts 
- vtgate_buffer_stops 
- vtgate_buffer_utilization_dry_run_sum 
- vtgate_buffer_utilization_sum

while still keeping the information that we want in the event something goes wrong in the failover buffering case. 

The current code (especially in big installations) generates quite a lot of metrics for a rarely exercised feature.

**Comment by sougou** [comment]
Can you try the two new flags:
* stats_combine_dimensions
* stats_drop_variables

They were introduced for #5791. PR: #5809.

**Comment by guidoiaquinti** [comment]
Ah, I didn't know about those new flags! Thanks @sougou! 🎉  

Closing this issue.
