### ISSUE TITLE
Query error mistakenly reported as 'unsupported: sharded subquery in insert values'

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#6330]
#### Overview of the Issue

Vitess has a problem with the `select` clause of a `replace into ... select` query. Instead of reporting the problem with the `select` clause, it reports a 'unsupported: sharded subquery in insert values'. In my scenario the cluster was not sharded and sharding had nothing to do with the error. It feels to me like the actual error was propagated then wrongly identified or wrapped as a shard error.

#### Reproduction Steps

1. Deploy the following `schema` (actual extract from `orchestrator`):

```sql
CREATE TABLE `cluster_alias` (
  `cluster_name` varchar(128) NOT NULL,
  `alias` varchar(128) NOT NULL,
  `last_registered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cluster_name`),
  UNIQUE KEY `alias_uidx` (`alias`),
  KEY `last_registered_idx` (`last_registered`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii
```

1. Run the following query:
```sql
replace into
  cluster_alias (alias, cluster_name, last_registered)
select
    cluster_name, cluster_name, now()
  from
    database_instance
  group by
    cluster_name
  having
    sum(suggested_cluster_alias = '') = count(*);
```
vitess responds with:
```
ERROR 1105 (HY000): vtgate: ...: unsupported: sharded subquery in insert values
```

The actual problem vitess has with the query is that the sub `SELECT` uses `cluster_name` twice:

```sql
select
    cluster_name, cluster_name, now()
  from
    database_instance
  group by
    cluster_name
  having
    sum(suggested_cluster_alias = '') = count(*);
```
```
ERROR 1105 (HY000): vtgate: ...: ambiguous symbol reference: cluster_name
```

The `REPLACE INTO ... SELECT` query is actually valid, in spite of the dual reference to `cluster_name`. However, in this Issue I'd like to focus on the fact vitess should have reported back a `ambiguous symbol reference` error rather than 'unsupported: sharded subquery in insert values'.

**Comment by harshit-gangal** [comment]
@shlomi-noach I was able to make this run on unsharded cluster. It this still an open issue?

**Comment by shlomi-noach** [comment]
@harshit-gangal this still happens on my local install, fresh from `master`:
```
    ->   `cluster_name` varchar(128) NOT NULL,
    ->   `alias` varchar(128) NOT NULL,
    ->   `last_registered` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ->   PRIMARY KEY (`cluster_name`),
    ->   UNIQUE KEY `alias_uidx` (`alias`),
    ->   KEY `last_registered_idx` (`last_registered`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=ascii;
Query OK, 0 rows affected (0.03 sec)

mysql> replace into
    ->   cluster_alias (alias, cluster_name, last_registered)
    -> select
    ->     cluster_name, cluster_name, now()
    ->   from
    ->     database_instance
    ->   group by
    ->     cluster_name
    ->   having
    ->     sum(suggested_cluster_alias = '') = count(*);
ERROR 1105 (HY000): vtgate: http://sn-carbon:15001/: unsupported: sharded subquery in insert values
```

**Comment by harshit-gangal** [comment]
I think I tried it on mysql directly. my bad.
