### ISSUE TITLE
TestConnectTimeout is flaky

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6333]
--- FAIL: TestConnectTimeout (0.20s)
##[error]    server_test.go:250: listening on address '127.0.0.1' port 41489
##[error]    client_test.go:121: was expecting SQLError 2013 / HY000 / initial packet read failed but got: context deadline exceeded

https://github.com/vitessio/vitess/runs/778220981?check_suite_focus=true

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
