### ISSUE TITLE
Alias on information_schema not supported

### ISSUE THREAD

**Issue by Topographic0cean** [vitessio/vitess#6334]
#### Overview of the Issue

Sending this query through Vitess shows the following error.  But if we do not use an alias, it works fine.   Are aliases not supported for the information_schema?

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

```javascript
{
  "mainkeyspace": {
    "sharded": false,
    "vindexes": {
      "hash": {
        "type": "hash"
      },
      "md5": {
        "type": "unicode_loose_md5",
        "params": {},
        "owner": ""
      },
      "users_name_idx": {
        "type": "lookup_hash",
        "params": {
          "from": "name",
          "table": "users_name_idx",
          "to": "user_id"
        },
        "owner": "users"
      }
    },
    "tables": {
    }
  }
}
```

2. Deploy the following `schema`:

```sql
   CREATE TABLE `notification` (
  `name` varchar(255) DEFAULT NULL,
  `sys_created_on` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

3. stmt.sql:
```sql
SELECT A.COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS A WHERE A.COLUMN_KEY in ('PRI','pri') ORDER BY A.COLUMN_NAME;
```

4. Run vtexplain:
vtexplain -vschema-file vschema.json -schema-file ./schema.sql -sql-file stmt.sql 

5. View error
vtexplain -vschema-file vschema.json -schema-file ./schema.sql -sql-file stmt.sql 
ERROR: vtexplain execute error in 'SELECT A.COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS A WHERE A.COLUMN_KEY in ('PRI','pri') ORDER BY A.COLUMN_NAME': symbol A.COLUMN_KEY not found

#### Operating system and Environment details

I don't think it matters.  I am testing on MacOSX catalina.

**Comment by harshit-gangal** [comment]
this is fixed via https://github.com/vitessio/vitess/pull/6638/commits/427ea7891cd4e472e637bafb23879ea8b5132ee1
