### ISSUE TITLE
builtinbackupengine uploads backup manifests despite s3 errors

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#6349]
#### Overview of the Issue

When taking backups using `builtinbackupengine` and `s3backupstorage` I have observed error codes being returned from the grpc `Backup` call to the tablet, but the backup manifest is still uploaded to s3, and file entries the manifest says are in s3 never get uploaded, rendering this backup present but unusable.

I believe that the following is happening:

In `builtinbackupengine.backupFiles`, we spawn a goroutine for each call to `be.backupFile`. If that returns an error we record it in `rec`. `be.backupFile` at one point calls `bh.AddFile`, which for the case of `s3backupstorage` backup handles, [does the actual upload in a goroutine](https://github.com/vitessio/vitess/blob/fce3f8fd06c0245290c015152e4c317637ea2a8d/go/vt/mysqlctl/s3backupstorage/s3.go#L127-L148) and returns `nil`. The goroutine then records any error later into `bh.errors`.

Since `rec` and `bh.errors` are separate instances of `concurrency.AllErrorRecorder`, and `backupFiles` only checks `rec`, it has no way to know if a fatal error happened asynchronously in the call to `s3manager.Upload`, so it assumes all is well, and proceeds to upload the MANIFEST.

#### Reproduction Steps

Get lucky and have a backup get some transient s3 error (rate limit, internal server error), then `aws s3 ls` the backup path and observe the manifest and missing backup part files.

#### Binary version

```sh
amason@workspace:~$ vttablet --version
Version: 7200712c6 (Jenkins build 435) (Git branch 'HEAD') built on Wed May 13 09:48:15 PDT 2020 by amason@workspace using go1.14.2 linux/amd64
```

#### Operating system and Environment details

```
sh
amason@workspace:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
amason@workspace:~$ uname -srm
Linux 4.4.0-1092-aws x86_64
```

#### Log Fragments

Output of `vtctl Backup` in the case of a rate limit:

```
(StatusCode.UNKNOWN, TabletManager.Backup on some_tablet_alias error: SlowDown: Please reduce your request rate.
status code: 503)
```

**Comment by deepthi** [comment]
Fixed by #6350
