### ISSUE TITLE
Table names with dollars signs do not work like mysql

### ISSUE THREAD

**Issue by Topographic0cean** [vitessio/vitess#6362]
#### Overview of the Issue

We have a few tables that have a dollar sign, "$", in the name.   This does not seem to be forbidden by msyql syntax and works just fine when sending queries directly to mysql, but does not work with Vitess unless the name is quoted.

You may argue, as I have with our DBAs, that using $ in a table name is a bad idea.   You may also argue that quoting solves the problem.   However, this works just fine on mysql and so should work on Vitess.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

```javascript
{
  "mainkeyspace": {
    "sharded": false,
    "vindexes": {
      "hash": {
        "type": "hash"
      },
      "md5": {
        "type": "unicode_loose_md5",
        "params": {},
        "owner": ""
      },
      "users_name_idx": {
        "type": "lookup_hash",
        "params": {
          "from": "name",
          "table": "users_name_idx",
          "to": "user_id"
        },
        "owner": "users"
      }
    },
    "tables": {
    }
  }
}
```

2. Deploy the following `schema`:

```sql
   CREATE TABLE `xx$yy` (
  `name` varchar(255) DEFAULT NULL,
  `sys_created_on` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

3. stmt.sql:
```sql
SELECT name FROM  `xx$yy`;
```

4. Run vtexplain:
vtexplain -vschema-file vschema.json -schema-file ./schema.sql -sql-file stmt.sql 

5. View error
$ vtexplain -vschema-file vschema.json -schema-file schema.sql -sql-file stmt.sql 
ERROR: vtexplain execute error in 'SELECT name FROM  xx$yy': syntax error at position 22 near '$'

6. But this works:
$ vtexplain -vschema-file vschema.json -schema-file schema.sql -sql-file stmt.sql
----------------------------------------------------------------------
SELECT name FROM  `xx$yy`

1 mainkeyspace/-: select name from `xx$yy` limit 10001

----------------------------------------------------------------------

#### Operating system and Environment details

I don't think it matters.  I am testing on MacOSX catalina.

**Comment by deepthi** [comment]
Which version of vitess are you using? This was fixed fairly recently (#6136) and is available only on master, not in any of the released versions.

**Comment by Topographic0cean** [comment]
My apologies, I was testing on the latest RELEASED version (6.0.20).   I did not see that issue (#6136) , sorry.

**Comment by Topographic0cean** [comment]
fixed on master.

**Comment by Topographic0cean** [comment]
just confirmed that the master branch fixes the naming issue I had.
