### ISSUE TITLE
Support MySQL logical XOR function

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6369]
Many (most?) of the other MySQL logical functions are supported (e.g. OR, AND, NOT).  There are even placeholders for XOR in the operator precedence code.  We should add support.

Current behavior:

```
mysql> select (1 XOR 1);
ERROR 1105 (HY000): vtgate: http://localhost:15001/: syntax error at position 14 near 'XOR'
```

**Comment by harshit-gangal** [comment]
Support added via #6371
