### ISSUE TITLE
Rename GitHub master branch to main

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#6378]
As part of making Vitess an inclusive environment, we want to rename master to main. I also checked with the CNCF, and they are encouraging all projects to do so.

It looks like GitHub will soon be performing this for new repositories, but there do not seem to be any additional helpers for existing ones. But, the operation is [quite straight forward](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx).

I suggest that we coordinate this to follow the release of Vitess 7. i.e.
- Create release branch for Vitess 7 on ~July 21st
- Vitess 7 is released July 28, 2020.
- Rename branch July 29th, 2020.

The idea behind this timing is that it doesn't get in the way of anyone during release time/everybody has a long heads up in case their own tooling depends on master (timing-wise it also means +2 weeks after the next Vitess monthly call, which can serve as a last reminder). It is possible to edit open PRs to change the branch, so it should be fairly low impact on code development.

**Comment by deepthi** [comment]
Given this: https://github.com/github/renaming
We might want to wait until those features are available.

**Comment by deepthi** [comment]
Assuming GH functionality lands by the end of the year, we can revisit this and plan for it.

**Comment by askdba** [comment]
https://github.com/github/renaming this needs to be tested.

**Comment by deepthi** [comment]
All done :tada:
