### ISSUE TITLE
streaming reads within transactions do not inherit transactional context

### ISSUE THREAD

**Issue by pH14** [vitessio/vitess#6386]
#### Overview of the Issue

Streaming reads run within a separate vttablet connection pool than transactions. This means that clients using all streaming reads cannot read-their-writes within a transaction, which is both a subtle and significant difference from MySQL transaction semantics.

#### Reproduction Steps

Steps to reproduce this issue, from the client:

1. BEGIN transaction
2. Write row X
3. Read row X with non-streaming read
4. Read row X with a streaming read

The non-streaming read will correctly find the row, the streaming read will not.

#### Thoughts

This issue has bitten our teams a number of times. I've heard rumblings of changes to the connection pool design... cc @systay @harshit-gangal is this one your radar?

**Comment by harshit-gangal** [comment]
Hey @pH14 Yes, we have work item open to unify streaming and non-streaming modes. Once it is done then this would not be an issue.

**Comment by harshit-gangal** [comment]
Should work now as #9115 is merged
