### ISSUE TITLE
tablet status link from vtctld UI is broken

### ISSUE THREAD

**Issue by acharis** [vitessio/vitess#6417]
vtctld/app/shard?keyspace=KeyspaceName&shard=0

the tablet status link all the way on the right used to link to the tablet's debug status page, but for me i see a link to /app/

**Comment by deepthi** [comment]
can one of you take a look? It could be that deleting the code / recent vttablet proxy changes broke this.

**Comment by rohit-nayak-ps** [comment]
It is working for me on master. For example, in the e2e vreplication test (go/test/endtoend/vreplication/vreplication_test.go) without teardown,  the rightmost link in the table for http://localhost:15000/app/shard?keyspace=customer&shard=0 goes to http://localhost:16500/debug/status 

Do you have a patched version (as we once discussed, you wanted to add patches for styling the prod/dev/staging envs)?

**Comment by rohit-nayak-ps** [comment]
assuming that this was a transient local issue.
