### ISSUE TITLE
sequences: support generation for value 0

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#6419]
#### Feature Description

https://dev.mysql.com/doc/refman/5.7/en/example-auto-increment.html

> No value was specified for the AUTO_INCREMENT column, so MySQL assigned sequence numbers automatically. You can also explicitly assign 0 to the column to generate sequence numbers, unless the NO_AUTO_VALUE_ON_ZERO SQL mode is enabled.

![image](https://user-images.githubusercontent.com/3588778/86848266-e50b2280-c06a-11ea-8eba-dba6f3f66410.png)

cc @MordFustang21

**Comment by sougou** [comment]
#4751

**Comment by derekperkins** [comment]
I thought I had seen an issue about that but couldn't find it.
