### ISSUE TITLE
RFC: Deprecating Helm

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6439]
The current helm charts have not been keeping up with the forward progress in vitess, and there has been no maintainer for it. Additionally, the operator has pulled ahead of what the helm charts could do. The operator can also be functionally more versatile than the helm charts because custom code can be written to manage complex workflows.

This essentially means that we have to deprecate the helm charts, unless someone feels strongly enough about them to want to take ownership and maintain them.

Please respond with your thoughts/feedback on this issue.

**Comment by deepthi** [comment]
Deprecated in 7.0
