### ISSUE TITLE
RFC: Deprecating Consul

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6440]
The usage of Consul has been problematic for vitess users. The main difficulty comes from the fact that it's non-trivial for a multi-cell deployment. Due to this, we want to discourage the use of consul as a a topo server, and would like to announce its deprecation.

There is no plan to delete the code. We will continue supporting legacy use cases. We will also continue running the tests for it.

However, it will not be included in the default build. Those who still want to use it can get a custom build by explicitly adding the appropriate `plugin_` file. Also, we will not be paying attention to any security notices, and will not be backporting such fixes to any of the supported vitess versions.

**Comment by deepthi** [comment]
Deprecated in 7.0
