### ISSUE TITLE
Application couldn't connect to external db giving error tabletserver.go:1522] Code: INVALID_ARGUMENT syntax error at position 33 near ':vtg2' (CallerID: gnocchi) : Sql: "select convert(:vtg1, CHAR(:vtg2)) as anon_1 from dual", 

### ISSUE THREAD

**Issue by Smita8081** [vitessio/vitess#6466]
### Overview of Issue###

**I have established connection of external db with vttablet running in k8 cluster, now I am trying to replace the mysql connection URL with vtgate endpoint, to connect my application to Vitess. But in application's pod I am getting below mentioned error**
2020-07-22 17:30:03,146 [1] INFO     gnocchi.cli.manage: Upgrading indexer SQLAlchemyIndexer: mysql+pymysql://***:***@100.20.2.102:3306/gnocchi?charset=utf8
2020-07-22 17:30:03,320 [1] WARNING  py.warnings: /usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py:322: SAWarning: Exception attempting to detect unicode returns: InternalError('(pymysql.err.InternalError) (1105, u"vtgate: http://gnocchi-gnocchizone-vtgate-e0fa99c5-868d59d85c-tkl8f:15000/: target: gnocchi.-.master, used tablet: gnocchizone-2007104406 (22.10.134.219): vttablet: rpc error: code = InvalidArgument desc = syntax error at position 33 near \':vtg2\' (CallerID: gnocchi)")',)
  "detect unicode returns: %r" % de)

2020-07-22 17:30:03,330 [1] WARNING  py.warnings: /usr/lib/python2.7/site-packages/pymysql/cursors.py:166: Warning: (1235, u'Modification not allowed using set construct for: sql_mode')
  result = self._query(query)

2020-07-22 17:30:03,338 [1] WARNING  oslo_db.sqlalchemy.engines: MySQL SQL mode is 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION', consider enabling TRADITIONAL or STRICT_ALL_TABLES
2020-07-22 17:30:03,384 [1] WARNING  oslo_db.sqlalchemy.engines: MySQL SQL mode is 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION', consider enabling TRADITIONAL or STRICT_ALL_TABLES

**Logs from vttablet are mentioned below:**

I0722 17:19:29.332532       1 shard_sync.go:172] Updating shard record: master_alias=gnocchizone-2007104406, master_term_start_time=2020-07-22 17:19:29.328056765 +0000 UTC m=+10.351512833
E0722 17:19:29.361926       1 syslogger.go:84] no connection, dropping syslog event: &events.ShardChange{KeyspaceName:"gnocchi", ShardName:"-", Shard:(*topodata.Shard)(0xc0002463f0), Status:"updated"}
I0722 17:19:29.362057       1 shard_sync.go:84] Change in shard record
E0722 17:19:29.615422       1 syslogger.go:84] no connection, dropping syslog event: &events.TabletChange{Tablet:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc00005f3c0), Hostname:"22.10.134.219", PortMap:map[string]int32{"grpc":15999, "vt":15000}, Keyspace:"gnocchi", Shard:"-", KeyRange:(*topodata.KeyRange)(0xc00012a780), Type:1, DbNameOverride:"gnocchi", Tags:map[string]string(nil), MysqlHostname:"192.168.1.100", MysqlPort:3306, MasterTermStartTime:(*vttime.Time)(0xc00035c450), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:113}, Status:"updated"}
E0722 17:19:29.615509       1 syslogger.go:84] no connection, dropping syslog event: &events.Reparent{StatusUpdater:events.StatusUpdater{Status:"updating global shard record", EventID:1595438369331286021}, ShardInfo:topo.ShardInfo{keyspace:"gnocchi", shardName:"-", version:20, Shard:(*topodata.Shard)(0xc0005b1b90)}, OldMaster:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc0003e5740), Hostname:"", PortMap:map[string]int32(nil), Keyspace:"", Shard:"", KeyRange:(*topodata.KeyRange)(nil), Type:1, DbNameOverride:"", Tags:map[string]string(nil), MysqlHostname:"", MysqlPort:0, MasterTermStartTime:(*vttime.Time)(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, NewMaster:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc000435a80), Hostname:"22.10.134.219", PortMap:map[string]int32{"grpc":15999, "vt":15000}, Keyspace:"gnocchi", Shard:"-", KeyRange:(*topodata.KeyRange)(0xc00041dea0), Type:1, DbNameOverride:"gnocchi", Tags:map[string]string(nil), MysqlHostname:"192.168.1.100", MysqlPort:3306, MasterTermStartTime:(*vttime.Time)(0xc0005b26c0), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, ExternalID:""}
I0722 17:19:29.615548       1 rpc_external_reparent.go:198] finalizeTabletExternallyReparented: updating global shard record if needed
E0722 17:19:30.431988       1 syslogger.go:84] no connection, dropping syslog event: &events.Reparent{StatusUpdater:events.StatusUpdater{Status:"finished", EventID:1595438369331286021}, ShardInfo:topo.ShardInfo{keyspace:"gnocchi", shardName:"-", version:20, Shard:(*topodata.Shard)(0xc0005b1b90)}, OldMaster:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc0003e5740), Hostname:"", PortMap:map[string]int32(nil), Keyspace:"", Shard:"", KeyRange:(*topodata.KeyRange)(nil), Type:1, DbNameOverride:"", Tags:map[string]string(nil), MysqlHostname:"", MysqlPort:0, MasterTermStartTime:(*vttime.Time)(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, NewMaster:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc000435a80), Hostname:"22.10.134.219", PortMap:map[string]int32{"grpc":15999, "vt":15000}, Keyspace:"gnocchi", Shard:"-", KeyRange:(*topodata.KeyRange)(0xc00041dea0), Type:1, DbNameOverride:"gnocchi", Tags:map[string]string(nil), MysqlHostname:"192.168.1.100", MysqlPort:3306, MasterTermStartTime:(*vttime.Time)(0xc0005b26c0), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}, ExternalID:""}
I0722 17:30:03.316612       1 tabletserver.go:1522] Code: INVALID_ARGUMENT
syntax error at position 33 near ':vtg2' (CallerID: gnocchi)
: Sql: "select convert(:vtg1, CHAR(:vtg2)) as anon_1 from dual", BindVars: {vtg1: "type:VARBINARY value:\"test plain returns\" "vtg2: "type:INT64 value:\"60\" "}
I0722 17:30:03.322328       1 tabletserver.go:1522] Code: INVALID_ARGUMENT
syntax error at position 33 near ':vtg2' (CallerID: gnocchi)
: Sql: "select convert(:vtg1, CHAR(:vtg2)) as anon_1 from dual", BindVars: {vtg1: "type:VARBINARY value:\"test unicode returns\" "vtg2: "type:INT64 value:\"60\" "}
I0722 17:30:03.372935       1 tabletserver.go:1522] Code: INVALID_ARGUMENT
syntax error at position 33 near ':vtg2' (CallerID: gnocchi)
: Sql: "select convert(:vtg1, CHAR(:vtg2)) as anon_1 from dual", BindVars: {vtg1: "type:VARBINARY value:\"test plain returns\" "vtg2: "type:INT64 value:\"60\" "}
I0722 17:30:03.374809       1 tabletserver.go:1522] Code: INVALID_ARGUMENT
syntax error at position 33 near ':vtg2' (CallerID: gnocchi)
: Sql: "select convert(:vtg1, CHAR(:vtg2)) as anon_1 from dual", BindVars: {vtg1: "type:VARBINARY value:\"test unicode returns\" "vtg2: "type:INT64 value:\"60\" "}
I0722 17

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: gnocchi
spec:
  images:
    vtctld: vitess/lite:v6.0.20-20200429
    vtgate: vitess/lite:v6.0.20-20200429
    vttablet: vitess/lite:v6.0.20-20200429
    vtbackup: vitess/lite:v6.0.20-20200429
  cells:
  - name: gnocchizone
    gateway:
      authentication:
        static:
          secret:
            name: gnocchi-cluster-config
            key: users.json
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  vitessDashboard:
    cells:
    - gnocchizone
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: gnocchi
    turndownPolicy: Immediate
    partitionings:
    - custom:
        shards:
        - databaseInitScriptSecret:
            name: gnocchi-cluster-config
            key: init_db.sql
          keyRange: {}
          replication:
            enforceSemiSync: false
          tabletPools:
          - cell: gnocchizone
            replicas: 1
            vttablet:
              extraFlags:
                db_charset: utf8
                queryserver-config-pool-size: "5"
                queryserver-config-stream-pool-size: "5"
                queryserver-config-transaction-cap: "5"
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
            externalDatastore:
              credentialsSecret:
                key: rds.json
                name: gnocchi-cluster-config
              database: gnocchi
              host: 192.168.1.100
              port: 3306
              user: test
            type: externalmaster
            dataVolumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: gnocchi-cluster-config
type: Opaque
stringData:
  rds.json: |
    { "test": [ "pass" ] }
  users.json: |
    {
      "gnocchi": [{
        "UserData": "gnocchi",
        "Password": "password"
      }]
    }
  init_db.sql: |
# Empty

**[dev] root@m1-kms0001:operator# vtgate --version
Version: 5245945 (Git branch 'HEAD') built on Mon May 25 19:17:32 UTC 2020 by runner@fv-az98 using go1.13.11 linux/amd64**

**Comment by harshit-gangal** [comment]
Fixed via #6304
