### ISSUE TITLE
Assigning results from queries is not supported

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#6471]
#### Overview of the Issue

At the moment, assigning the result of a query to a variable is not working on vtgates. 
#### Reproduction Steps

1. Connect to a vtgate using mysql cli.
1. Run the following:
    ```
    SET @test=(select 1);
    ```
3. See the error:
    ```
     expression not supported for SET: (select :vtg1 from dual)
    ```

#### Expected behavior

```
mysql> SET @test=(select 1 from dual);
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT @test;
+-------+
| @test |
+-------+
|     1 |
+-------+
1 row in set (0.00 sec)

```

**Comment by harshit-gangal** [comment]
Supported via #6964
