### ISSUE TITLE
vtctld - add a metric for serving vttablets count

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#6500]
#### Overview of the Issue
We rely on the metric `vttablet_tablet_server_state` and its label `name` to detect if vttablet is in serving state or not and alert if the number of vttablet serving for a specific keyspace/shard is < threshold.

Unfortunately, in few situations like a shard split we can't rely on that information as "individual vttablet view" doesn't take into account if the shard is non-serving.

#### Proposal
Add a metric (maybe in `vtctld`?) that exposes the # of serving tablets for serving and not-serving shards

```
vtctld_serving_vttablet_count{keyspace="test", shard="0", state="serving"} 4
vtctld_serving_vttablet_count{keyspace="test", shard="-80", state="non-serving"} 4
vtctld_serving_vttablet_count{keyspace="test", shard="80-", state="non-serving"} 4
```

**Comment by sougou** [comment]
Isn't this variable enough to infer the information you're asking for? https://github.com/vitessio/vitess/blob/99783bccae68f0f3e1e23b736bd47e855c904a41/go/vt/vttablet/tabletserver/tabletserver.go#L171.
Maybe I misunderstand the feature.

**Comment by guidoiaquinti** [comment]
Sorry for the misunderstanding. That variable is ok for _most of scenarios_, but it doesn't account cases like shard splits where tablets are in `SERVING` state, and they are technically part of a non-serving shard.

It could be nice to have a similar metric but that filters out non-serving shards (atm you can't archive that without some monitoring hacks like PromQL joins across jobs).

End goal is to be able to have an alert like
```
count(
  vtctld_serving_vttablet_count{
    job="vitess-vtctld",
    name="SERVING",
  }
) by (keyspace, shard) < threshold
```
that doesn't trigger false positives during shard splits or other maintenance operations.

Let me know if it doesn't make sense, thanks! 🙌

**Comment by guidoiaquinti** [comment]
We ended up using a different approach but with #7929 we can probably close this issue. We can now count the number of serving/non-serving tablets in a shard and group by the serving/non-serving shard state.
