### ISSUE TITLE
Support multiple session set statement syntax

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6508]
This is completely valid MySQL syntax, but does not work against Vitess 7.0:

```
mysql> SET SESSION NET_READ_TIMEOUT= 86400, SESSION NET_WRITE_TIMEOUT= 86400;
ERROR 1105 (HY000): vtgate: http://localhost:15001/: syntax error at position 63 near 'NET_WRITE_TIMEOUT'
```

Running them individually works fine:
```
mysql> SET SESSION NET_READ_TIMEOUT= 86400;
Query OK, 0 rows affected (0.00 sec)

mysql> SET SESSION NET_WRITE_TIMEOUT= 86400;
Query OK, 0 rows affected (0.01 sec)
```

unfortunately, certain connectors/clients that are not easy to modify use this syntax.  A good example is mysqldump in MySQL 8.0, which actually sends the above timeout variables sequence to the server, which cannot be bypassed via mysqldump CLI options.

**Comment by harshit-gangal** [comment]
working on master #6494
