### ISSUE TITLE
consistent_lookup_unique vindex reports unrelated error

### ISSUE THREAD

**Issue by ankitthakwani** [vitessio/vitess#6518]
#### Overview of the Issue
In a multi shard keyspace with a vtgate flag -transaction_mode set to SINGLE, a transaction which violates the global unique constraint of consistent_lookup_unique vindex fails with unrelated error message.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

    ```javascript
    {
      "sharded": true,
      "vindexes": {
        "unicode_loose_md5_vdx": {
          "type": "unicode_loose_md5"
        },
        "uniqueConstraint_vdx": {
          "type": "consistent_lookup_unique",
          "params": {
            "table": "uniqueConstraint_vdx",
            "from": "unique_constraint",
            "to": "keyspace_id",
            "autocommit": "true"
          },
          "owner": "txn_unique_constraints"      
        }
      },
      "tables": {
        "txn_unique_constraints": {
          "column_vindexes": [
            {
              "column": "txn_id",
              "name": "unicode_loose_md5_vdx"
            },
            {
              "column": "unique_constraint",
              "name": "uniqueConstraint_vdx"
            }
          ]
        },    
        "uniqueConstraint_vdx": {
          "column_vindexes": [
            {
              "column": "unique_constraint",
              "name": "unicode_loose_md5_vdx"
            }
          ]      
        }
      }
    }
    ```

2. Deploy the following `schema`:

    ```sql
    DROP TABLE IF EXISTS txn_unique_constraints;
    CREATE TABLE `txn_unique_constraints` (
      `id`                varchar(100) NOT NULL ,
      `txn_id`            varchar(50) NOT NULL,
      `unique_constraint` varchar(100) NOT NULL,
      `created_on`        timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_txn_unique_constraint` (`unique_constraint`),
      KEY `idx_txn_unique_constraints_txn_id` (`txn_id`),
      KEY `idx_txn_unique_constraints_created_on` (`created_on`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
    DROP TABLE IF EXISTS uniqueConstraint_vdx;
    CREATE TABLE uniqueConstraint_vdx(
      `unique_constraint` VARCHAR(50) NOT NULL,
      `keyspace_id`       VARBINARY(50) NOT NULL,
     PRIMARY KEY(unique_constraint)
    );
    ```

1. Run

   ```sql
   BEGIN;
   INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn1', 'txn_info_txn_id_txn1', '2020-03-25 23:59:59.000');
   INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn1', 'txn_info_mti_mc___mti1_mc1', '2020-03-25 23:59:59.000');
   COMMIT;

   BEGIN;
   INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn3', 'txn_info_txn_id_txn3', '2020-03-25 23:59:59.000');
   INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn3', 'txn_info_mti_mc___mti1_mc1', '2020-03-25 23:59:59.000');
   COMMIT;
   ```
1. View error

> ERROR 1105 (HY000): vtgate: http://localhost:15001/: execInsertSharded: getInsertShardedRoute: multi-db transaction attempted: [target:<keyspace:"oms_switch_sharded" shard:"80-c0" tablet_type:MASTER > transaction_id:1596185742231075256 tablet_alias:<cell:"dc1" uid:400 >  target:<keyspace:"oms_switch_sharded" shard:"40-80" tablet_type:MASTER > transaction_id:1596185717384876572 tablet_alias:<cell:"dc1" uid:300 > ]

Expected error should be something which describes that the unique constraint on vindex table failed.

#### Binary version
Example:

```sh
Version: 2dd43fe (Git branch 'master') built on Fri Jul 31 08:41:57 UTC 2020 by vitess@vtsoms using go1.14.1 linux/amd64
```

**Comment by ankitthakwani** [comment]
An observation, if you reverse the order of the transactions in above i.e. if you execute following then we will get the same error as we got after executing second transaction in the issue, this means the actual error was not `multi-db transaction attempted`


    BEGIN;
    INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn3', 'txn_info_txn_id_txn3', '2020-03-25 23:59:59.000');
    INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn3', 'txn_info_mti_mc___mti1_mc1', '2020-03-25 23:59:59.000');
    COMMIT;
    
    BEGIN;
    INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn1', 'txn_info_txn_id_txn1', '2020-03-25 23:59:59.000');
    INSERT INTO txn_unique_constraints(id, txn_id, unique_constraint, created_on) VALUES (UUID(), 'txn1', 'txn_info_mti_mc___mti1_mc1', '2020-03-25 23:59:59.000');
    COMMIT;

**Comment by harshit-gangal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [consistent_lookup_unique vindex reports unrelated error](https://trello.com/c/8txnR0DB/36-consistentlookupunique-vindex-reports-unrelated-error)
