### ISSUE TITLE
PlannedReparentShard should allow automatic replica selection even when cross cell boundaries

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6532]
Currently PRS allows user to not specify a `-new_master` option.  In this case, PRS will automatically choose a replica that is "reasonable" for promotion.

However, this logic only works for reparenting to a replica in the same cell as the current master.  If you want to cross cells with the reparenting, you need to explicitly provide a `-new_master` tablet name.

We should remove this limitation, and allow PRS to take a destination cell as a parameter, and then use the existing internal logic to chose the most up-to-date replica in that cell.

**Comment by GuptaManan100** [comment]
Resolved by https://github.com/vitessio/vitess/pull/16461
