### ISSUE TITLE
flaky vreplication test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6534]
--- FAIL: TestPlayerCopyBigTable (0.64s)
    framework_test.go:583: 
        	Error Trace:	framework_test.go:583
        	            				vcopier_test.go:327
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestPlayerCopyBigTable
        	Messages:   	QueryCount stat is incorrect

**Comment by rohit-nayak-ps** [comment]
This has been fixed
