### ISSUE TITLE
flaky vexec test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6537]
--- FAIL: TestWorkflowListStreams (0.00s)
    vexec_test.go:268: 
        	Error Trace:	vexec_test.go:268
        	Error:      	Not equal: 
        	            	expected: "map[Tablet{zone1-0000000200}:rows_affected:1  Tablet{zone1-0000000210}:rows_affected:1 ]"
        	            	actual  : "map[Tablet{zone1-0000000210}:rows_affected:1  Tablet{zone1-0000000200}:rows_affected:1 ]"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-map[Tablet{zone1-0000000200}:rows_affected:1  Tablet{zone1-0000000210}:rows_affected:1 ]
        	            	+map[Tablet{zone1-0000000210}:rows_affected:1  Tablet{zone1-0000000200}:rows_affected:1 ]
        	Test:       	TestWorkflowListStreams

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
