### ISSUE TITLE
Flaky TestStateManagerGracePeriod

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6607]
--- FAIL: TestStateManagerGracePeriod (0.02s)
    state_manager_test.go:228: 
        	Error Trace:	state_manager_test.go:228
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 2
        	Test:       	TestStateManagerGracePeriod

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
