### ISSUE TITLE
Throttling for VReplication streams

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6616]
The "old" implementation of Vitess SplitClone has throttling (ThrottlerSetMaxRate, etc.);  but the new VReplication-based implementation does not have any throttling today.  As a result, the only (marginally) practical way to throttle the copying process for a SplitClone (or other VReplication streams) is to implement some type of network-level throttle.  This may not be practical in some cases (e.g. k8s makes it hard to do system-level things like this).

We should implement a basic (rows / sec?) throttler for at least the VReplication copy phase.

**Comment by derekperkins** [comment]
Not sure if it's necessary, but I remember Cloudflare using this library to throttle Clickhouse replication. :) https://github.com/tylertreat/comcast

**Comment by aquarapid** [comment]
> Not sure if it's necessary, but I remember Cloudflare using this library to throttle Clickhouse replication. :) https://github.com/tylertreat/comcast

Yeah, that's the type of thing I had in mind by network-level throttle.  But that won't do much for you in k8s, unless you're willing to hack individual nodes and throttle indiscriminately...

**Comment by derekperkins** [comment]
I was thinking that if it was throttling inside vttablet as a library, you could limit the throughput regardless whether you were on k8s or not.

**Comment by hallaroo** [comment]
Closing this in favor of the issue opened here: https://github.com/vitessio/vitess/issues/7362
