### ISSUE TITLE
Compile warnings with new go-sqlite3 dep 

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6631]
We recently integrated some orchestrator code that depends on sqlite, and uses the go-sqlite3 module.

On newer gcc versions this will throw a warning during a (clean build):
```
$ make clean ; make
Wed Aug 26 09:24:23 PDT 2020: Building source tree
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:129019:10: warning: function may return address of local variable [-Wreturn-local-addr]
129019 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128979:10: note: declared here
128979 |   Select standin;
       |          ^~~~~~~
```

Upstream issue is https://github.com/mattn/go-sqlite3/issues/803 , but it does not seem like it will be addressed soon, and even if it does, the upstream dependencies might take a while to filter down to typical user installs.  We should work around it in the Vitess build, even if just in the interest of cleanliness.

**Comment by GuptaManan100** [comment]
If this issue is resolved, can we close this issue?
