### ISSUE TITLE
Flaky TestConcatenate_WithSourcesErrFirst

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6646]
--- FAIL: TestConcatenate_WithSourcesErrFirst (0.00s)
    --- FAIL: TestConcatenate_WithSourcesErrFirst/2_non_empty_result (0.00s)
        --- FAIL: TestConcatenate_WithSourcesErrFirst/2_non_empty_result/StreamExecute_wantfields_true (0.00s)
            concatenate_test.go:166: 
                	Error Trace:	concatenate_test.go:166
                	Error:      	Error message not equal:
                	            	expected: "failed"
                	            	actual  : "The used SELECT statements have a different number of columns (errno 1222) (sqlstate 21000)"
                	Test:       	TestConcatenate_WithSourcesErrFirst/2_non_empty_result/StreamExecute_wantfields_true
FAIL
FAIL	vitess.io/vitess/go/vt/vtgate/engine	0.017s

Passed when I reran `go test` under `engine`.

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
