### ISSUE TITLE
SET GLOBAL support

### ISSUE THREAD

**Issue by mcronce** [vitessio/vitess#6647]
#### Feature Description
While `SET` works, `SET GLOBAL` does not.  In particular, what I've found not working is `SET GLOBAL sql_mode = 'TRADITIONAL'`, but from what I've been able to tell we haven't added support for `SET GLOBAL` in general

#### Use Case(s)
I found this while doing testing for various frameworks.  In particular, the Rust `mysql` and `mysql_async` crates use it.  However, from what I can tell, they only use it for integration tests (`cargo test`) - actually writing an application using the framework works perfectly fine.  If anybody else comes across a more urgent use case, this would be a great place to record it :)

**Comment by systay** [comment]
We can't really do this at this moment. Not sure what a good way of handling it would be. Should we just ignore these SET queries, or just apply the settings in the session scope? Or is this one of those cases where the user has to configure MySQL with these settings, and then we could just let them be NoOps. WDYT? /cc @sougou @harshit-gangal
