### ISSUE TITLE
endtoend CI tests consistently timing out or sporadically failing

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#6658]
[cluster endtoend / build (17)](https://github.com/vitessio/vitess/pull/6547/checks?check_run_id=1060228572) is an example fo ra test that consistently times out after 10m-11m. In https://github.com/vitessio/vitess/pull/6547, I have added more tests to shard `17`, and those tests include some `Sleep()s` accumulating at about `1min`.
I'm not sure how to increase test time, and also unsure how to split my tests onto a new shard (tried setting this up in `test/config.json` but no CI job spawned).

Otherwise, some tests seem flaky: 

- `docker_test_1 / Docker Test 1` (failing after 32m)
- `cluster_initial_sharding_multi / cluster initial sharding multi` (failing after 15m)

cc @sougou @deepthi

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
