### ISSUE TITLE
Common empty resultset query on MySQL returns a row in Vitess

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6663]
A common way to run a query against MySQL that will return an empty resultset is:

```
select 1 from dual where false;
```

So, against MySQL:

```
mysql> select 1 from dual where false;
Empty set (0.00 sec)
```

But against Vitess:

```
mysql> select 1 from dual where false;
+-------+
| :vtg1 |
+-------+
|     1 |
+-------+
1 row in set (0.00 sec)
```

This is not significant per-se, but this query is often used as a connpool "keepalive" query, or as a test query that is expected to return an empty resultset.

**Comment by harshit-gangal** [comment]
Closed via #6666 6666
