### ISSUE TITLE
Creating table qualified with schema name fails

### ISSUE THREAD

**Issue by dkhenry** [vitessio/vitess#6664]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue
When issuing a create table command, if the name of the schema is prepended to the query the `CREATE TABLE` fails

#### Reproduction Steps

1. `CREATE TABLE `main`.`migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB`

fails with 

`error: Error: vtgate: http://12u:15000/: target: main.-.master, used tablet: test-1 (): vttablet: rpc error: code = InvalidArgument desc = Unknown database 'main' (errno 1049) (sqlstate 42000) (CallerID: userData1): Sql: "CREATE TABLE `main`.`migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB", BindVars: {}`

The following Query works 

`CREATE TABLE `migrations` (`id` int NOT NULL AUTO_INCREMENT, `timestamp` bigint NOT NULL, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB`

**Comment by harshit-gangal** [comment]
Supporting this today is non-trivial as the parser for DDL is not fully matured to parse and recreate the same query back. 
Query rewriting straight away is not possible. We will look into this, if we can do something around it.

**Comment by cjjb** [comment]
Had the same issue. Had to use a workaround for this where the database and keyspace names were exactly the same.

![image](https://user-images.githubusercontent.com/66693257/92982380-1cc38b80-f45b-11ea-837b-243ebdc1c184.png)

Hope this helped.

**Comment by harshit-gangal** [comment]
@GuptaManan100 this is support now?

**Comment by GuptaManan100** [comment]
Yes it is! Closing the issue now
