### ISSUE TITLE
Support query using WHERE 1=0 on a cross shard subquery 

### ISSUE THREAD

**Issue by ankitthakwani** [vitessio/vitess#6676]
#### Feature Description
Spark SQL module when fires a query on MySQL uses a construct SELECT * FROM (<user query>) WHERE 1=0, it does this because Spark tries to infer the schema of the data without actual loading of the data. 

Reference: https://stackoverflow.com/questions/48827041/why-does-spark-appends-where-1-0-at-the-end-of-sql-query#:~:text=versions%20of%20DataframeReader.-,jdbc.,to%20get%20the%20schema%20information.

```
User Query         --> SELECT MIN(update_timestamp) FROM txn_info
Spark converts it  --> SELECT * FROM (SELECT MIN(update_timestamp) FROM txn_info) WHERE 1=0

```

This construct of cross shard subquery is not currently supported.

#### Use Case(s)
Spark SQL is widely used for ETL.

**Comment by GuptaManan100** [comment]
We have expanded a lot on our support for derived tables. This should be working now. I have tested the example in the description and it works with the latest version of Vitess. If there is something else that Vitess doesn't support, please open a new issue.
