### ISSUE TITLE
Reshard: table /.* not found in vschema

### ISSUE THREAD

**Issue by kubanowSKY** [vitessio/vitess#6701]
When trying to Reshard 1 shard to 2 another got an error:
```
E0911 12:30:23.312045    2031 main.go:67] remote error: rpc error: code = Unknown desc = buildResharder: readRefStreams: blsIsReference: table /.* not found in vschema
```

In logs I got only queries sent to `_vt.vreplication` on vttablets which returns nothing.

Debian 10, vitess 7.0 running in Docker, vitess installed and running using local via docker.

**Comment by kubanowSKY** [comment]
Had stopped vreplication after previous sharding (which seemed to completed well, was from empty shard 0 to 2 shards). I've truncated _vt.vreplication on old shards and retried Resharding. Seems to work.

**Comment by rohit-nayak-ps** [comment]
The issue you reported has to do with previous streams not being properly cleaned up. Running DropSources after a workflow is completed cleans these up, but if it is not called or if there was some error in between it is possible these streams linger. Hence your deleting of those rows in _vt.vreplication fixed that issue. 

We will be fixing this soon.. Do you recall the flow when you faced this: did you rerun the same workflow without running DropSources? Or encounter any errors during SwitchWrites?

**Comment by kubanowSKY** [comment]
I wasn't aware I should DropSources after reshard works were done. Now I see one `STOPPED` VReplication task. Should I `DropSources` now?

My flow was as it is:
- create shard 0 empty
- Reshard to -80 and 80- (still empty, no errors)
- SwitchReads, SwitchWrites (no errors)
- Insert some data
- Try to Reshard to any of -40,40-80,80-c0,c0- and got on first error.

**Comment by sougou** [comment]
Via #6814
