### ISSUE TITLE
Transactional read support for OLAP

### ISSUE THREAD

**Issue by hallaroo** [vitessio/vitess#6703]
#### Feature Description

Add read-only transactional support with streaming for OLAP. This does not currently exist. 

#### Use Case(s)

In order to integrate with Sqoop and do larger splits, OLAP had to be enabled and a custom solution devised to circumvent the lack of support for transactions in OLAP using the java connector.

Note: Sqoop requires transactional reads and it is not possible to configure it to not use transactions. Thus the modification to the Java MySQl connector library.

**Comment by harshit-gangal** [comment]
Closed with #9115
