### ISSUE TITLE
The client got the wrong database name

### ISSUE THREAD

**Issue by hellobob** [vitessio/vitess#6753]
Please search the existing issues for relevant feature requests, and use the [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description
some client like  sharding jdbc get the database name from query like select * from tb where 1!=1 to get the  table_schema and the dbname.
But vitess return dbname xxx   like  vt_xxx,   the client user the wrong dbname  to send query to vitess and get the  errs  like 
keyspace vt_vt_commerce not found in vschema（using select * from vt_commerce.tb ）
or  
Table 'vt_vt_commerce.tb' doesn't exist（using show full columns from vt_commerce.tb  ）

use tcpdump get the follows info:
![5DD4ECD4-E695-488B-BDCD-5BEA5B99F5C0](https://user-images.githubusercontent.com/6309288/93731934-db24a480-fc01-11ea-91c9-c9524c74c0c5.jpg)

![21B4F287-4858-472A-A3CE-79EA095065D4](https://user-images.githubusercontent.com/6309288/93731938-e081ef00-fc01-11ea-80b7-4e9c9373a9ae.jpg)

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by harshit-gangal** [comment]
Current workaround would be to provide `-init_db_name_override` in vttablet command line flag to same as keyspace name.

**Comment by harshit-gangal** [comment]
have to tried providing database name in jdbc connection url? Does that work?

**Comment by hellobob** [comment]
> connection

this does't work .    the developer used the java   framewrok named shardingjdbc to  sharding tables and  used vitess to shard db
