### ISSUE TITLE
Permit usage of "_" character in keyspace name

### ISSUE THREAD

**Issue by Smita8081** [vitessio/vitess#6755]
Hi, I have been struggling to create keyspace having _ in its name, for instance nova_api. Seems like there is restriction in using _ character.
#### Feature Description

Permit usage of '_' character in keyspace name.

#### Use Case(s)

Since my database name have _ in its name and that Vitess keyspace doesn't allow to create keyspace name with _ in it. So i had to do a lot many changes in the application to direct the request from earlier mentioned database name(nova_api) to now (novaapi). This is something I really want to avoid so as to make the integration of Vitess cluster with application more effortless.

**Comment by deepthi** [comment]
Vitess itself allows `_` in keyspace names. It seems like you are using the operator?

**Comment by Smita8081** [comment]
yes I am using operator.

**Comment by deepthi** [comment]
Can you create an issue here instead?
https://github.com/planetscale/vitess-operator/issues

**Comment by maZahaca** [comment]
I've just created one in vitess-operator: https://github.com/planetscale/vitess-operator/issues/164

**Comment by aquarapid** [comment]
This is supported now; https://github.com/planetscale/vitess-operator/issues/164 closed;  closing this issue as well.
