### ISSUE TITLE
Monitoring.md page did not get migrated to vitess.io docs?

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6761]
When we built out the vitess.io documentation last year, we removed much of the docs that existed in the vitess repo (under /doc) (see commit bfeed1ead9d5e524ec086d9ff3e4034e11d5fb2e).

Specifically it was noted that the monitoring page here got removed:

https://github.com/vitessio/vitess/blob/f93c96c738d7d5bbbcdc03c828f8bf0a5ba16250/doc/Monitoring.md

We should resurrect some of that content on the vitess.io site;  and also check for anything else that might have gotten lost in the shuffle.

**Comment by hallaroo** [comment]
Closing PR where monitoring was re-added: https://github.com/vitessio/website/pull/644
