### ISSUE TITLE
Task: vtorc endtoend tests

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6769]
Now that we have a vitess-native implementation of [orchestrator](https://github.com/openark/orchestrator) aka vtorc, we need to add endtoend tests for the following use cases.
- [x] Cluster has no master, master should be elected automatically
- [x] Cluster has no master, RDONLY should not be elected as master
- [x] Bring master down, a replica should be elected, replication from other instances should be re-configured to point to new master
- [ ] Bring up old master, should rejoin cluster properly
- [x] Graceful takeover
- [x] TER to a non-master, wait for repair
- [x] Make Master read-only, wait for repair
- [x] stop replication on a replica, wait for repair
- [x] point replica elsewhere, wait for repair
- [x] make replica read-write, wait for repair
- [x] Create a co-master situation (instance A replicates from B and B from A), wait for repair
- [x] Basic testcases for `-clusters_to_watch` (default, single keyspace, single keyspace/shard)
- [x] In a multi-cluster environment, each orc instance acts on specified clusters (`-clusters_to_watch` flag)

Infrastructure tasks:
- [x] basic test infrastructure
- [x] enable in CI by adding to `test/config.json`
- [x] configuration changes to speed up tests
- [x] generate port number instead of using default

EDIT June 1, 2021:
Replace Decider with vtorc.

**Comment by GuptaManan100** [comment]
The only remaining test left in the list is `Bring up old master, should rejoin cluster properly`. I am not sure if that is a good idea. We don't recommend people bring up their old primaries back after they have been killed. If we decide to add this test, then it would be inherently flaky wherein the old primary could end up having errant-GTIDs causing the test to fail. If we decide we want to add that test, let's open a new issue for it. Meanwhile, I am closing this issue.
