### ISSUE TITLE
Certain compound logic statements not supported by vtgate parser

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6795]
In vtgate in current master (ac3a3d698):

```
mysql> select 1>0>1;
ERROR 1105 (HY000): vtgate: http://localhost:15001/: syntax error at position 12
```

vs. against the backend MySQL (8.0.21) directly:

```
mysql> select 1>0>1;
+-------+
| 1>0>1 |
+-------+
|     0 |
+-------+
```

A similar situation exists for similar logic statements in a `WHERE` clause, for example.

**Comment by harshit-gangal** [comment]
It is supported now.
