### ISSUE TITLE
SQLAlchemy:Alternative tablet_type separator for database name

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#6798]
In Vitess we use `@` to separate the keyspace (database) name and the tablet type, e.g.:

```
databasename@replica
```

Unfortunately, when you use this string as the database name in the (JDBC inspired) connection string of some client-side application platforms, the `@` character is interpreted incorrectly, since it's used as a separator between username/password and hostname/IP.  As a concrete example, in SQLAlchemy 1.3.12, we have this:

```
 Input DB URL:    mysql://username:password@hostname.a.b/dbname@replica

SQLAlchemy interpretation:

{'username': 'username', 'password': 'password@hostname.a.b/dbname', 'port': None, 'database': None, 'query': None, 'host': 'replica'}
```

i.e. SQLAlchemy scans greedily up to the last `@` character.

In this specific case SQLAlchemy uses a regex to parse the connection string, and does not really support escapes, so no amount of trickery seems to be able to convince it to parse the connection string the way we want.  It is trivial to change SQLAlchemy's parser to not scan the connection string greedily;  but not all users are able/willing to patch their libraries like this.

We should consider supporting another character in addition to '@' as the tablet_type signifier, preferably one that's not significant in common connection string implementations.

**Comment by harshit-gangal** [comment]
I tested this and not able to replicate.

```python
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://some_user:some_pass@some_host/test@replica?charset=utf8mb4")
args, kwargs = engine.dialect.create_connect_args(engine.url)
args, kwargs
([], {'host': 'some_host', 'database': 'test@replica', 'user': 'some_user', 'password': 'some_pass', 'charset': 'utf8mb4', 'client_flag': 2})
```

```
❯ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
```

```
Successfully installed sqlalchemy-1.4.20
```
