### ISSUE TITLE
Issues in "Getting Started" with GCP Cloud SQL

### ISSUE THREAD

**Issue by robfig** [vitessio/vitess#6809]
#### Overview of the Issue

Following the "Getting started" guide to use Vitess 7.0.2 with GCP Cloud SQL does not work out of the box. 

I installed it according to this page:
https://vitess.io/docs/get-started/local/

and configured it in Unmanaged Mode (which seems to be the only mode compatible with Cloud SQL) according to this:
https://vitess.io/docs/user-guides/unmanaged-tablet/

I ran into two issues, the second of which I'm not sure how to get past.

1. `vttablet` has an `-init_populate_metadata` flag that runs `SET @@session.sql_log_bin = 0;` which requires SUPER permission. Cloud SQL does not support SUPER permission: https://cloud.google.com/sql/docs/features#unsupported_mysql_features -- I removed that flag and continued on.

2. `vtctlclient InitShardMaster` results in the following error:

```
W1001 15:45:33.550504   19196 main.go:64] W1001 15:45:33.549464 reparent.go:185] master-elect tablet zone1-0000000401 is not the shard master, proceeding anyway as -force was used
W1001 15:45:33.550559   19196 main.go:64] W1001 15:45:33.549514 reparent.go:191] master-elect tablet zone1-0000000401 is not a master in the shard, proceeding anyway as -force was used
I1001 15:45:33.550571   19196 main.go:64] I1001 15:45:33.549573 reparent.go:222] resetting replication on tablet zone1-0000000401
E1001 15:45:33.555754   19196 main.go:67] remote error: rpc error: code = Unknown desc = tablet zone1-0000000401 ResetReplication failed (either fix it, or Scrap it): rpc error: code = Unknown desc = TabletManager.ResetReplication on zone1-0000000401 error: ExecuteFetch(STOP SLAVE) failed: Access denied for user 'profile'@'%' (using password: YES) (errno 1045) (sqlstate 28000) during query: STOP SLAVE: ExecuteFetch(STOP SLAVE) failed: Access denied for user 'profile'@'%' (using password: YES) (errno 1045) (sqlstate 28000) during query: STOP SLAVE
```

The instructions need to be updated to walk through initializing a shard in a master role.

#### Reproduction Steps

Following the Getting Started steps with Cloud SQL on the site reproduces this error.

#### Binary version

Release 7.0.2

#### Operating system and Environment details

CentOS7 

```
[bastion@vt01 my-vitess-example]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[bastion@vt01 my-vitess-example]$ uname -sr
Linux 3.10.0-1127.19.1.el7.x86_64

[bastion@vt01 my-vitess-example]$ uname -m
x86_64
```

#### Log Fragments

Included above

**Comment by sougou** [comment]
Sorry about getting back at this late. To run vitess with externally managed mysql, you'll need to tweak some settings and use a slightly different flow. I have an example here that uses the operator and works for RDS https://github.com/planetscale/vitess/tree/ss-rds-example/examples/rds.

You may also find this useful https://vitess.io/docs/user-guides/unmanaged-tablet/

**Comment by robfig** [comment]
That is useful, but this issue report is about how the instructions on the page (https://vitess.io/docs/user-guides/unmanaged-tablet/) do not work. 

I used TabletExternallyReparented instead of InitShardMaster, and that seemed to work.

**Comment by hallaroo** [comment]
Following up here as it looks like the instructions [here](https://vitess.io/docs/user-guides/configuration-advanced/unmanaged-tablet/) do properly show 'TabletExternallyReparented' rather than  'InitShardMaster'. And a further [note](https://github.com/vitessio/website/commit/a1516295171cc8e4101cd7834366142a5b267d60#diff-ffafdfbfa22e74aeec2aeb2fe852e52c8409150a2ba8fd8ea47211518eb01919) on using AWS RDS, AWS Aurora or Google CloudSQL was added as well.
