### ISSUE TITLE
Proposal: Integrate skeema for declarative schema management

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#6884]
Now that we're building out all these awesome schema lifecycles, I wanted to propose perhaps a logical next step. We already have some primitives for schema comparisons: ValidateSchemaShard & ValidateSchemaKeyspace. Except for advanced canary testing or other testing purposes, generally it is desirable to have a declarative schema for all shards and replicas in a keyspace, and that is something that Vitess is uniquely suited to provide.

@shlomi-noach has implemented managed DDL, safe DROP TABLE, throttling and other related schema functionality which really are awesome. He has implemented internal state machinery and coordination with vtctld. If we allow users to add their schema definitions, similar to how we store vschemas, we could use those same types of primitives to monitor for schema skew and optionally automatically apply changes to bring things back into alignment.

We could use Skeema (https://github.com/skeema/skeema) to provide the core functionality. Skeema is written in Go, so it should be possible to use it as a library rather than an external binary. I have had email conversations in the past with @evanelias, the creator of Skeema, and he has expressed some interest in better Vitess integration for Skeema.

Vitess has all the pieces necessary to make this happen, and this would further extend the value of the control plane. It would be tremendously valuable if we could figure out how to integrate the two.

Commentary on skeema
- https://news.ycombinator.com/item?id=19881434
- https://sendgrid.com/blog/schema-management-with-skeema/

Related projects
- https://blog.replicated.com/schemahero-declarative-schema-management/

cc @dweitzman @sougou

**Comment by shlomi-noach** [comment]
Great topic!

Another relevant take I thought might be relevant is where  `skeema` does not speak directly to the databases, but instead is used within the developer's flow, with an external operator deploying the changes in production; illustrated in https://github.blog/2020-02-14-automating-mysql-schema-migrations-with-github-actions-and-more/

**Comment by evanelias** [comment]
For deep integration, the main challenge would be the conflicting models of the two systems. Skeema's sharding support is designed to speak directly to MySQL: users configure a mapping between a directory and environments/shards, and Skeema introspects each shard (querying `information_schema` and running various `SHOW` commands) to determine the difference between that shard and the desired state. This allows Skeema to properly detect and fix drift (shards that are unexpectedly in the wrong state). But it's potentially incompatible with a model where all queries are routed through a central proxy like vtgate, if I understand Vitess's model correctly.

> it should be possible to use it as a library rather than an external binary

Possible in theory, but not straightforward currently. Skeema's configuration system makes some assumptions about CLI usage, and there's some cross-dependencies in Skeema's subpackages. I hope to clean this up at some point in the future, which could enable easier library usage, but I don't have concrete plans yet.

> where `skeema` does not speak directly to the databases, but instead is used within the developer's flow

I would like to note that [Skeema Cloud Linter](https://www.skeema.io/cloud/) SaaS can already provide this flow, and is the recommended/official way of doing so with Skeema.

For a more complete automation lifecycle, one could parse out the SQL codeblocks (containing the generated DDL) from Skeema Cloud Linter's check run results or PR/commit comments.

For a cleaner approach, in theory it would be possible to add an API to Skeema Cloud Linter, providing on-demand DDL generation for any git branch, PR, commit, or commit range. There just hasn't been enough demand to implement this yet.

**Comment by mattlord** [comment]
Just noting that Vitess now uses an internal package called `schemadiff` which leverages the Vitess parser:
  - Blog post: https://vitess.io/blog/2023-04-24-schemadiff/
  - Source: https://github.com/vitessio/vitess/tree/21b490a7c4a0c51764a0b978a0f195d4e5bbffe2/go/vt/schemadiff

For anyone that may be curious. I are already quite a fewOSS projects using the Vitess parser, and will likely be some that use `schemadiff` over time as well.

**Comment by mattlord** [comment]
One last related note — there's now an OSS CLI that leverages the Vitess schemadiff library: https://github.com/planetscale/schemadiff/blob/main/README.md
