### ISSUE TITLE
Add MoveAllTables Functionality to MoveTables

### ISSUE THREAD

**Issue by jawabuu** [vitessio/vitess#6896]
#### Feature Description

`MoveTables` should allow a user to create DDL & copy/replicate all tables  from source to target without specifying each table individually.
Possible approaches;
`Copy SchemaShard` already has a catchall "/.*" filter
Use an exclude filter to skip unwanted tables
#### Use Case(s)
1. Migrating from unmanaged tablet to vitess managed tablet.
2. Cases where the source database has a large number of tables. Specifying each of them is unwieldly.

@sougou @rohit-nayak-ps

**Comment by jawabuu** [comment]
Hey @sougou 
I believe this has been addressed by https://github.com/vitessio/vitess/pull/7018. You may close.
Thank you @rohit-nayak-ps

**Comment by rohit-nayak-ps** [comment]
Closed via https://github.com/vitessio/vitess/pull/7018
