### ISSUE TITLE
Proposal: Support backups with volume snapshots

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#6952]
All major clouds support disk snapshot capabilities that provide a faster and usually cheaper alternative to file based backups. Snapshots can also be incremental, which further saves time and cost. Here's a performance comparison between the standard Vitess file backup and the snapshot alternative:

1.3 TB shard
- Standard Vitess backup: ~3 hours (355 GB)
- GCP disk snapshot: ~3 minutes (314 GB)

### Backups
Backups should be relatively easy to implement. We could either shut down MySQL like we do with the standard backup to ensure that the filesystem is stable, or potentially leave it running, but shutting down replication and anything else that writes to the disk. In our case, we're already taking MySQL down, so reducing that downtime by 99% is still a win, without dealing with all the potential corner cases for leaving it running.

We also have already imported major cloud SDKs, so adding in snapshot functionality should have minimal impact on dependency management and binary bloat.

### Restores
This is a much different use case than we support today, and I'm not sure that Vitess itself can or should handle restores. Restoring from snapshots involves provisioning a new disk based on the existing snapshot, so it would need to happen out of band before the Vitess binaries start up, but no new code should be required, as they will detect the existing data directories and start the same as they do today after a restart. 

This is potentially where the Vitess operator could provide support. For users outside Kubernetes or not using the operator, they would have to orchestrate their own infrastructure to provision new tablets using the latest snapshot.

### For consideration
- The Percona MySQL operator supports volume snapshots inside kubernetes, so there is a case to be made for backups to happen there too, but I think there is value for users outside of Kubernetes to be able to at least create snapshots. https://www.percona.com/blog/2020/10/22/using-volume-snapshot-clone-in-kubernetes/
- @dkhenry and I had a brief conversation about this in Slack here https://vitess.slack.com/archives/C8V721QN8/p1603462945020100

**Comment by deepthi** [comment]
To summarize a discussion on slack (https://vitess.slack.com/archives/CNE9WP677/p1621529098007200)
- This doesn't belong in core vitess because it is unclear how you would restore
- Operator has the correct scope to implement a volume snapshot backup/restore
