### ISSUE TITLE
Flaky test: TestCellAliasVreplicationWorkflow

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6979]
--- FAIL: TestCellAliasVreplicationWorkflow (79.16s)
Error:     vreplication_test.go:304: SwitchWrites error: E1030 20:36:44.312954    4441 main.go:64] E1030 20:36:44.312520 traffic_switcher.go:270] waitForCatchup failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        E1030 20:36:44.332702    4441 main.go:67] remote error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
        
FAIL
FAIL	vitess.io/vitess/go/test/endtoend/vreplication	79.172s
FAIL

https://github.com/vitessio/vitess/pull/6978/checks?check_run_id=1333994771

**Comment by rohit-nayak-ps** [comment]
Fixed in #7169
