### ISSUE TITLE
Postgres compatibility

### ISSUE THREAD

**Issue by kyoujuro** [vitessio/vitess#7003]
Hello to whom it May concern

If I create a postgres compatibility
May I send a pull request etc.?
I'm sorry for being a beginner,
Please check.

Sorry if I have missed any prior discussions on this front.

**Comment by deepthi** [comment]
Hi @kyoujuro! Contributions are always welcome.
Since this is a non-trivial task, the process is for you to write up a proposal and request comments from the maintainers and community. An example proposal / RFC can be seen here: #5791.

**Comment by kyoujuro** [comment]
Thank you for your reply.
Also, thank you for your teaching.
I will try to compare Postgres with MySQL and show you the benefits of creating Postgres compatibility and more.

I will do my best to power up Vitess together.
Please wait for a while to prepare my comment.
Thank you for your continued support.

Best Regards,

**Comment by kyoujuro** [comment]
# introduction

As Vitess adoption expands, a number of feature requests have been popping up that will benefit from compatibility　with PostgreSQL.

If you often use PostgreSQL, it is as follows:

・prioritize robustness  
・prioritize high performance  
・use GIS features  
・Parallel execution performance

will make the vitess architecture more flexible.

# Features
This section describes the use cases and their features. An important prerequisite: In order to retain backward compatibility, the new features should not cause existing behavior to be affected.

|Comparison items | MySQL | PostgreSQL |
|---|---|---|
|Storage architecture  |Renewal type |Addendum type  |
|UPDATE  |It has a simple behavior of directly overwriting the value of the row to be UPDATE.  |Perform processing similar to an INSERT statement  |

# Postgres utilization pattern
- PostGIS, a third-party OSS tool  
When launching a new product, grasp whether there are many target groups based on the census data.  
Collect manufacturing data of each factory and display the good and bad points.  
It takes in CAD data of buildings, etc., displays it together with a map, and manages it.


# Summary
MySQL has a very high share rate, and it is very strong when it is necessary to process at high speed because of its simple specifications such as Web services.  
Postgres, on the other hand, is highly functional and robust, and demonstrates its strengths in services such as mission-critical services.  
From the above, we believe that it will be further utilized by adding compatibility with Postgres.

**Comment by deepthi** [comment]
This is interesting. Until now I always thought that people would have already chosen PostgreSQL as their DB and are looking to Vitess to provide scaling / management on top of that. What you are suggesting is that people might look at Vitess first and then want to decide between MySQL and PostgreSQL.

**Comment by kyoujuro** [comment]
Thank you for your interest in this.
Please wait for a while to create for Postgres compatibility and send a pull request.

**Comment by GuptaManan100** [comment]
There has been no progress on this in a while. If we want to add Postgress support to Vitess it would be a good idea to write a new RFC given that Vitess has changed a lot since this issue was opened.
