### ISSUE TITLE
Vitess: reported replication lag is higher than threshold

### ISSUE THREAD

**Issue by vikaskeskar11** [vitessio/vitess#7013]
Error log:
Disabling query service because of health-check failure: reported replication lag: 7201.261347594 higher than unhealthy threshold: 7200

#### Overview of the Issue

The issue is affecting production environment. 

#### Reproduction Steps

1. Start backup with built in backup engine
2. It will shutdown mysqld
3. At the same time, continuously delete some of the records on master
4. When backup tablet will transitioned to replica, connect to specifically to that tablet mysql and run query, ``` show slave status ```. You will see error there, something like ``` Error_code: 1032, HA_ERR_KEY_NOT_FOUND ``` or might be some different error
5. Wait for exceeding threshold of replication lag
6. Run health check

#### Operating system and Environment details
This issue is observed on K8S cluster.

**Comment by sougou** [comment]
For some reason, your replica seems to have diverged from the master. That's what I inferred by googling for HA_ERR_KEY_NOT_FOUND. You may have to throw away that replica and rebuild a new one from an existing backup.

**Comment by vikaskeskar11** [comment]
This thing happens whenever there is backup going on and some delete operation gets performed on master. 
![image](https://user-images.githubusercontent.com/24711514/98703239-4d636b00-23a1-11eb-9ccf-363f8af96adc.png)
These are some more details

**Comment by sougou** [comment]
I asked a few people. No one has seen this before. The only thing I can think of is that something is misconfigured in mysql that's causing statements to be applied inconsistently.

**Comment by vikaskeskar11** [comment]
I have checked for all configurations of mysql, but nothing is wrong with them. This issue occurs when one tablet is used for backup(Tablet is out from replication as backup is going on it). But when that tablet is again joined for synchronization, and delete operation is performed on master, then it is not able to find that record on master, so it throws error ```Error_code: 1032, HA_ERR_KEY_NOT_FOUND``` and stops synchronization with replication lag error,

**Comment by mattlord** [comment]
I'm closing this for now as it seems to have gone stale. I'm sorry that you had these problems! I hope that the issue is no longer occurring but if it is and you are able to come up with a repeatable test case (including MySQL, Vitess, K8s version/arch details) we can re-open this with those details and dig in again.
