### ISSUE TITLE
Issue Triage

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7030]
Issue labels have been cleaned up so that we now have the following:
- Type: Bug/Feature Request etc.
- Component: There are only 4 components - Query Serving, VReplication, Cluster Management and Build
- Priority: Every new issue will be assigned P3 on initial evaluation. It might then be upgraded (or down) as needed.
- Status: Every issue is a "New" issue until it is assigned a Status label.

@askdba will do the initial triage of new issues and assign a Component and Priority (always set to P3). 
Based on the component, issues will be assigned as follows:
Query Serving @systay 
VReplication @rohit-nayak-ps 
Cluster Management @deepthi 
Build @shlomi-noach 

These individuals will then determine further action on the issue.

**Comment by shlomi-noach** [comment]
Please assign me to Build.
