### ISSUE TITLE
vtgate crashes during multiple shards executing DDL 

### ISSUE THREAD

**Issue by inolddays** [vitessio/vitess#7046]
we execute an alter table DDL statment(add two columns) throught vtgate on one keyspace which has 16 shards.
And found the vtgate clusters are becoming crashes.
After crashes for some minutes (almost near 30 minutes)
All vtgates are available again
Here is the call stack:
![image](https://user-images.githubusercontent.com/2297199/99347442-1e358800-28d2-11eb-8035-15ceb345abab.png)

have been discussed with @sougou    
this problem may because when we applying ddl on multiple shard and at the same time the business app runs select * as well.
vtgate send query to first shard and first shard says it 5 columns but the other shard return 4. vtgate then expects uniform number of columns.
One solution is persuade user not use select * and rewrite sql like :explicitly select a,b,c, then it won't fail .
But some times it not that easy to make user change.
so we need to add some protections on this situation.
This does not fundamentally solve the problem but at least vtgate will not crash 
Here may another pr i paste it here to track if it is something  could refer on or related :
https://github.com/vitessio/vitess/issues/5572

**Comment by aquarapid** [comment]
The better solution may be to use vschema, that includes the table column lists with authoritative set to true;  then perform the DDL to add the column against the shards.  When the DDL on all the shards are complete, update the vschema to add the new column.  In this way, a `select *` will not expand to additional columns until after the vschema update is done.

**Comment by Johnny-Three** [comment]
> The better solution may be to use vschema, that includes the table column lists with authoritative set to true; then perform the DDL to add the column against the shards. When the DDL on all the shards are complete, update the vschema to add the new column. In this way, a `select *` will not expand to additional columns until after the vschema update is done.

this may can solve the problem. but one thing should care about , will this kind of realization cause too many changes compare with the former code structure ?

**Comment by Johnny-Three** [comment]
reproduce it on my labtop @sougou   
![image](https://user-images.githubusercontent.com/2297199/99393978-19e08d80-2919-11eb-85b8-805bd69fcf41.png)
when i add new column directly to first shard's master mysql.
then i exeute "select * from sbtest limit 1\G"
![image](https://user-images.githubusercontent.com/2297199/99394676-3cbf7180-291a-11eb-8c4c-94be12cc34bf.png)
debug the vttablet:
![image](https://user-images.githubusercontent.com/2297199/99394083-45637800-2919-11eb-97cf-7df202831712.png)
![image](https://user-images.githubusercontent.com/2297199/99394102-4eece000-2919-11eb-96b4-286572e668df.png)
fileds and row.length are not equal cause the query.plan.fields are used old one.
At first i add two pieces of code on vtgate like this:
![image](https://user-images.githubusercontent.com/2297199/99394302-9ffcd400-2919-11eb-8ad1-3d5622c457b0.png)
but it will not work with the ddl like :
alter table sbtest1 add grade1 int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'grade1' after _hd_update_region;
fields' order are not rightly be parsed then.
so i guess pr 
https://github.com/vitessio/vitess/pull/5572 
seems fix this problem but it bring another flag, and it may not easy for people to know when the right time to set the flag as false.
@aquarapid  gives a perfect solution that i agree also.  currently the temporary solution for me is to bring the flag "watch_replication_stream" back on vttablet. this flag will seeing ddl change on schema and reload schema instantly and clear the query plan, This will greatly reduce the likely occurrence of such a panic.

**Comment by sougou** [comment]
Chiming in. We should still fix the panic. If the field length is longer than the number of columns returned, maybe we can pad with nulls, or return an error. Maybe returning an error is better.

**Comment by xhh1989** [comment]
vtgate is a gateway cluster that supports multi-tenancy. Some of our gateways are used by hundreds of applications. If an application has a similar problem causing the gateway cluster to crash, hundreds of applications will be unavailable， This will be a very serious accident， I think The priority should be P0

**Comment by sougou** [comment]
This should only be an internal panic. I don't think vtgate actually crashes at this point.

**Comment by Johnny-Three** [comment]
> This should only be an internal panic. I don't think vtgate actually crashes at this point.

vtgate will crashes. it depends on how long time vttablet will reload schema itself. Default value is 30 minutes. In other words, if all applications use the same vtgate cluster , vtgate wil not be available until 30 minutes later. During this time, when there is query like "select *", gates cluster will alway crashes

**Comment by harshit-gangal** [comment]
We have schema tracking at vtgate which should solve this As it does `star` expansion for sharded queries.
