### ISSUE TITLE
select CAST('123' as INT) - syntax error at position 25 near 'INT'

### ISSUE THREAD

**Issue by indera-shsp** [vitessio/vitess#7063]
#### Overview of the Issue
Unable to cast a string as an integer.

#### Reproduction Steps

1. Run 
```
select CAST('123' as SIGNED);
+------------------------+
| convert('123', SIGNED) |
+------------------------+
|                    123 |
+------------------------+
```

1. View error
```
select CAST('123' as INT);
syntax error at position 25 near 'INT'
```

#### Binary version
Example:

```sh
giaquinti@workspace:~$ vtgate --version
Version: a95cf5d (Git branch 'HEAD') built on Fri May 18 16:54:26 PDT 2018 by giaquinti@workspace using go1.10 linux/amd64
```

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`):
```
cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.9.4
PRETTY_NAME="Alpine Linux v3.9"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel version (output of `uname -sr`):
```
Linux 4.19.112+
```

- Architecture (output of `uname -m`):
```
x86_64
```

#### Log Fragments

Include appropriate log fragments. If the log is longer than a few dozen lines, please
include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue.

**Comment by harshit-gangal** [comment]
Related to https://github.com/vitessio/vitess/issues/6223

**Comment by indera-shsp** [comment]
Related to https://github.com/vitessio/vitess/pull/6304/files maybe

**Comment by GuptaManan100** [comment]
`select CAST('123' as INT);` is not syntactically correct and does not run even on vanilla mysql. use `select CAST('123' as SIGNED INTEGER);` instead. Refer to https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html for other options.
