### ISSUE TITLE
Using a dot to specify database names in sql statements fails with unknown database

### ISSUE THREAD

**Issue by Preisschild** [vitessio/vitess#7067]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

A paragraph or two about the issue you're experiencing.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Create keyspace with name 'test'

1. Deploy the following `schema`:

    ```sql
    create table test.user(user_id bigint, name varchar(128), primary key(user_id));
    ```

mysql-client returns: 
`vttablet: rpc error: code = InvalidArgument desc = Unknown database 'test' (errno 1049) (sqlstate 42000) (CallerID: user): Sql: "create table test.user(user_id bigint, name varchar(128), primary key(user_id))", BindVars: {}`

If i execute the same SQL-Statement, but with `vt_test` as database name instead of `test`:
 
```sql
create table vt_test.user(user_id bigint, name varchar(128), primary key(user_id));
```
mysql-client returns `Query OK, 0 rows affected (0.098 sec)`

#### Binary version

```sh
Version: 771aa75d (Git branch 'HEAD') built on Thu Mar 19 05:07:41 UTC 2020 by vitess@445ddadd2fdc using go1.12.14 linux/amd64
```

**Comment by harshit-gangal** [comment]
This is work in progress. As of now, DDL are not fully parsed and passed as-is to mysql. 
cc: @GuptaManan100

**Comment by Preisschild** [comment]
i just noticed that this is an duplicate of #6664, closing this
