### ISSUE TITLE
Task: Remove deprecated RPCs and vtctl commands

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7109]
In 7.0, we deprecated the following RPCs and vtctl commands. They should now be deleted.

vtctl commands:
StopSlave
StartSlave
ChangeSlaveType

vttablet RPCs:
InitSlave
SlaveStatus
StopSlave
StopSlaveMinimum
StartSlave
StartSlaveUntilAfter
GetSlaves
SlaveWasPromoted
SlaveWasRestarted

Also delete the Request and Response protobufs associated with these RPCs.

**Comment by derekperkins** [comment]
Not sure if the timelines line up, but we could potentially save some work by prioritizing the new `vtctld` interface and just removing these commands altogether rather than changing them. #7058

**Comment by deepthi** [comment]
These RPCs and commands have already been deprecated so we will delete them.
But we might be able to change how we accomplish #7114. If the vtctl commands anyways call the new vtctld RPCs we might be able to do what you are suggesting and delete some of the RPCs right away instead of deprecating them.
