### ISSUE TITLE
Task: Remove references to "slave" in vtctld UI

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7111]
The exact scope of this task needs to be determined.
The UI allows calls to vtctl commands. Those can be replaced with the equivalent new commands.
The rest has to be evaluated.

**Comment by deepthi** [comment]
We'll be deleting the vtctld2 web UI after v15. At that time this task will no longer be relevant.

**Comment by deepthi** [comment]
I believe @ajm188 is on point to delete the old web UI. Assigning.

**Comment by dbussink** [comment]
Closing this as the UI is deleted.
