### ISSUE TITLE
Task: Replace use of "blacklist" with "denylist" or "excluded"

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7112]
We have references to `blacklistedTables`, `blacklistRules` etc.
They should all be replaced with appropriate names. 

This needs to be done in a backwards-compatible way so it might take more than one release cycle.
The first round of changes/deprecations should happen in 9.0.
The website docs should be updated at the same time.

**Comment by derekperkins** [comment]
Upstream MySQL is going with `blocklist`, so I'd vote to keep it consistent.

![image](https://user-images.githubusercontent.com/3588778/101110794-03803600-3597-11eb-9efa-7a0a6944916f.png)

https://mysqlhighavailability.com/mysql-terminology-updates/

**Comment by deepthi** [comment]
Fixed by #8630
