### ISSUE TITLE
Task: Replace master with primary (except TabletType)

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7114]
All usages of master in variable names / function parameters can be replaced.
vtctl commands will need to be deprecated and equivalent new ones provided. e.g. `SetShardIsMasterServing`
vtctl command arguments will need to go through a deprecation cycle. For one release, we accept both old and new arguments and then remove the old ones. e.g. `-include_master`
RPCs will need to be deprecated and new ones created. e.g. `DemoteMaster`

There is a separate task for TabletType #7113 

Update website docs at the same time to document new commands and flags and mark deprecated ones.

**Comment by derekperkins** [comment]
Cross posting from #7113 https://github.com/vitessio/vitess/issues/7113#issuecomment-738495107

While I personally prefer primary, I'd vote to match MySQL and call it source
https://mysqlhighavailability.com/mysql-terminology-updates/
https://dev.mysql.com/doc/refman/8.0/en/replication.html

**Comment by deepthi** [comment]
x-post: https://github.com/vitessio/vitess/issues/7109#issuecomment-738498969

**Comment by deepthi** [comment]
- [x] mysqld functions and structs #8251
- [x] tabletmanager interface and implementations #8251
- [ ] tabletmanager RPCs
- [ ] ReplicationStatus Protobuf

After the next release
- [ ] Change wrangler code to use new RPCs
- [ ] Deprecate old RPCs

After one more release
- [ ] Delete deprecated RPCs

**Comment by deepthi** [comment]
I have opened separate issues for the outstanding work (which can only happen one release at a time in order to maintain compatibility across releases). Closing this because the rest of the work is complete.
Ref: #8837 #8838 and #8839
