### ISSUE TITLE
"select @@query_cache_size as query_cache_size from dual" fails with MySQL 8.0

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7149]
`query_cache_size` has been removed in MySQL 8.0.

When running vitess in front of MySQL 8.0 databases, some frameworks (flyway) will send this query because vtgate advertises it's server version as 5.7.
We can't simply bump that to 8.0 using the vtgate flag `mysql_server_version` because then frameworks might start sending 8.0 specific queries that we don't yet support.

@morgo had suggested dealing with this particular variable by making it a no-op.
https://github.com/vitessio/vitess/issues/5205#issuecomment-533247548

**Reproduction Steps**
Use Vitess with MySQL 8 and execute the select statement from a mysql client.

**Version**
```
$ vtgate --version
Version: e484bc60c (Git branch 'master') built on Wed Dec  9 12:20:01 PST 2020
```

**Comment by deepthi** [comment]
Context from previous discussion:
https://github.com/vitessio/vitess/issues/5205#issuecomment-542396903

**Comment by harshit-gangal** [comment]
I think we should ask users to advertise the correct version of mysql and we fix forward for any query that framework sends that does not work.

**Comment by deepthi** [comment]
> I think we should ask users to advertise the correct version of mysql and we fix forward for any query that framework sends that does not work.

@mavenraven can you try doing this and let us know if it doesn't work?

**Comment by mavenraven** [comment]
@deepthi I'm sure it will work, as it's what @sverch mentioned in the beginning of the other issue. I took this issue more of as UX thing for new users than anything else.

**Comment by deepthi** [comment]
Actually we don't know for sure that it will work without errors. What if after detecting the version as MySQL 8.0, the client sends something that is new in 8.0 and not yet supported by vitess?

**Comment by mavenraven** [comment]
@deepthi That's definitely possible, but I think that's unrelated to this particular issue.

**Comment by harshit-gangal** [comment]
That will be easier to fix than supporting deprecated system variable query.

**Comment by harshit-gangal** [comment]
Closing this.
