### ISSUE TITLE
'show tables' to system schema does not work

### ISSUE THREAD

**Issue by eseokoh** [vitessio/vitess#7160]
#### Overview of the Issue

#7150 allows us to use system schemas, however, "show tables" does not work.

#### Reproduction Steps

execute mysql via vtgate:

```
mysql> use mysql
Database changed
mysql> show tables;
ERROR 1105 (HY000): vtgate: http://my-zone1-vtgate-2f3311c0-5d8c94d7c9-gp5z5:15000/: keyspace mysql fetch error: node doesn't exist: /vitess/my/local/zone1/keyspaces/mysql/SrvKeyspace
```

Please notice the error. 

```
mysql> select * from user limit 1 \G
*************************** 1. row ***************************
                  Host: localhost
                  User: root

...

1 row in set (0.01 sec)
```

Querying to a table of schema works. 

#### Binary version

The latest vitess/lite image: (cb7d74ca53e293f91ebfe6eb06acd452afc1d60e)

**Comment by harshit-gangal** [comment]
Show planner is legacy, once we move to new planner it will work.
