### ISSUE TITLE
Local and operator example not in sync.

### ISSUE THREAD

**Issue by jfg956** [vitessio/vitess#7208]
I am going through the Vitess Tutorial.  I did a Local install {1} and I am now doing the MoveTable steps {2}.  I would like to contribute improvements to the tutorial (new issue or PR to be created), but while preparing this, I realized that the `select_commerce_data.sql` files are not in sync for the Local {3} and the Operator {4} tutorials.  The Local file had `commerce/0` in it and the Operator file has only `commerce` in it.  It looks to me like these are equivalent, but consistency would be good here.  Also, maybe dropping the file in `examples/operator` in favor of the file in `examples/common` would be good, and this would impact the {2} guide.

{1}: https://vitess.io/docs/get-started/local/

{2}: https://vitess.io/docs/user-guides/migration/move-tables/

{3}: https://github.com/vitessio/vitess/blob/master/examples/common/select_commerce_data.sql

{4}: https://github.com/vitessio/vitess/blob/master/examples/operator/select_commerce_data.sql

**Comment by jfg956** [comment]
Somehow related pull request {5}.

{5}: https://github.com/vitessio/website/pull/645

**Comment by askdba** [comment]
@hallaroo when you get a chance can you verify this?

**Comment by hallaroo** [comment]
@askdba - I can confirm what is stated above. 

The more recent edit was done to the operator example (May 2020 as opposed to Dec 2018), so if it won't cause any issues I would offer to update the Local {3} file and the MoveTables user guide {4} and have you review.

**Comment by askdba** [comment]
@hallaroo sounds like a plan. Thanks! We can have @jfg956 verify as well :)

**Comment by jfg956** [comment]
Personally, I prefer the file in common, as it does not introduce Vitess weirdness (/0) in an early tutorial.  But if I check in {2}, there is a reference in there for `commerce/0`, so I guess it is ok to use the file in the operator example.

However, I would encourage you to converge on a single file to avoid duplication and new divergence in the example.  I would remove the file in the operator directory to only have a file in the common directory.

And one last thing, if you choose to introduce Vitess /0, please give a little more detain about it in the tutorial.  I do not fully understand the difference of `use commerce` and `use commerce/0` in {2}, but if there is, please explain it (the answer I got in {5} was not super clear).  I would understand the difference of `use customer`, `use customer/0`, `use customer/-80` and `use customer/80-` in the context of {6} (sharding tutorial), so I would suggest only to introduce this notion there.

{5}: https://vitess.slack.com/archives/C0PQY0PTK/p1608568517350600

{6}: https://vitess.io/docs/user-guides/configuration-advanced/resharding/

**Comment by hallaroo** [comment]
> Personally, I prefer the file in common, as it does not introduce Vitess weirdness (/0) in an early tutorial.

Agreed. The common file is the less recently updated one with the /0 and will need to be changed no matter what.

> However, I would encourage you to converge on a single file to avoid duplication and new divergence in the example. I would remove the file in the operator directory to only have a file in the common directory.

I'm checking to see if there is a good reason that we have the two files. Depending on that answer we can do one of two options:

* Update the common file and the guides to remove any reference to /0 before the resharding guide 
* Remove the operator file, update the common file, update the guides to reference only to the file in common, and remove any reference to /0 before the resharding guide  

> And one last thing, if you choose to introduce Vitess /0, please give a little more detain about it in the tutorial. I do not fully understand the difference of `use commerce` and `use commerce/0` in {2}, but if there is, please explain it (the answer I got in {5} was not super clear). I would understand the difference of `use customer`, `use customer/0`, `use customer/-80` and `use customer/80-` in the context of {6} (sharding tutorial), so I would suggest only to introduce this notion there.

Agreed as well. The /0 should be introduce when we introduce sharding. It would indeed be good to better explain what /0 means in general. I've taken a todo to add an FAQ. 

I'll add a link here to the hosted FAQ once I have it live.

**Comment by hallaroo** [comment]
Ok I heard back and there isn't a good reason we have the two files. 

I'll take a look at your PR linked above and make another PR for anything else that needs to be done to complete everything in the second option:

* Remove the operator file, update the common file, update the guides to reference only to the file in common, and remove any reference to /0 before the resharding guide

**Comment by askdba** [comment]
Thank you @hallaroo, I am assigning this issue to you. Let me know if you need any help.

**Comment by hallaroo** [comment]
Second PR to compliment the work done in vitessio/website#646 : https://github.com/vitessio/website/pull/656

**Comment by hallaroo** [comment]
Status update:
* **Completed: Both website PR's have been merged.**
* WIP: I'm awaiting approval on the PR to remove the operator file and will also be working on completing the hosted FAQ.

**Comment by hallaroo** [comment]
Status update:

* **Completed: Hosted FAQ added [here](https://planetscale.freshdesk.com/support/solutions/articles/64000259591-what-does-%E2%80%9C-0%E2%80%9D-or-%E2%80%9C-%E2%80%9Dmean-)**
* WIP: awaiting approval on the PR to remove the operator file
