### ISSUE TITLE
Add a hook func to stats.Timings 

### ISSUE THREAD

**Issue by narcsfz** [vitessio/vitess#7298]
#### Feature Description
The problem with stats.Timmings is it relies on a histogram to collect percentile information. If the stats backend does not support the interface that takes histogram bucket and do the aggregation for us, we need to do compute difference between two sample time to get the percentile metrics, and report them as gauges.

This could be annoy if we choose to integrate with backend like statsd, where the API we have is simply declaring the type of metrics we want (time or histogram) and then the current value of it - and it will aggregate it on the server side: https://godoc.org/github.com/DataDog/datadog-go/statsd#Client.Histogram

Some ideas to export timmings / histogram properly with statsd:
1. do the calculation by ourself by keeping track of previous histogram before reporting, taking the diff and report stats as gauges
2. add a hook to timmings (similar to stats.histogram) and use a global variable in stats package to register the hook function. Different stats backend can choose differently

To illustrate option 2, we add the register function like:
```
--- a/go/stats/histogram.go
+++ b/go/stats/histogram.go
@@ -38,6 +38,18 @@ type Histogram struct {
        total   sync2.AtomicInt64
 }

+type histogramClerk struct {
+       timingHook func(string, int64)
+       histogramHook func(string, int64)
+}
+var clerk = histogramClerk{}
+func RegisterHistogramHook(h func(string, int64)) {
+       clerk.histogramHook = h
+}
+func RegisterTimingHook(h func(string, int64)) {
+       clerk.timingHook = h
+}
+
```

and then stats backend can register as needed (using timming in statsd as an example):
```
--- a/go/stats/statsd/statsd.go
+++ b/go/stats/statsd/statsd.go
+               stats.RegisterTimingHook(timerHook)
        })
 }

+var timerHook = func(name string, elapsed int64) {
+       statsdClient.TimeInMilliseconds(name, float64(elapsed), nil, 1)
+}
+

        case *stats.Timings:
-               // TODO: for statsd.timing metrics, there is no good way to transfer the histogram to it
-               // If we store a in memory buffer for stats.Timings and flush it here it's hard to make the stats
-               // thread safe.
-               // Instead, we export the timings stats as histogram here. We won't have the percentile breakdown
-               // for the metrics, but we can still get the average from total and count
-               labels := []string{v.Label()}
-               hists := v.Histograms()
-               for labelValsCombined, histogram := range hists {
-                       sb.addHistogram(k, histogram, makeLabels(labels, labelValsCombined))
-               }
+               // don't need to anything since hook function already export stats for us
        case *stats.Histogram:
                sb.addHistogram(k, v, []string{})
```
and lastly, it hooks up with stats.Timings:
```
--- a/go/stats/timings.go
+++ b/go/stats/timings.go
@@ -33,6 +33,7 @@ type Timings struct {

        mu         sync.RWMutex
        histograms map[string]*Histogram
+       hook       func(string, int64)

        help          string
        label         string
@@ -50,6 +51,9 @@ func NewTimings(name, help, label string, categories ...string) *Timings {
                label:         label,
                labelCombined: IsDimensionCombined(label),
        }
+       if clerk.timingHook != nil {
+               t.hook = clerk.timingHook
+       }
        for _, cat := range categories {
                t.histograms[cat] = NewGenericHistogram("", "", bucketCutoffs, bucketLabels, "Count", "Time")
        }
@@ -92,6 +96,9 @@ func (t *Timings) Add(name string, elapsed time.Duration) {
        hist.Add(elapsedNs)
        t.totalCount.Add(1)
        t.totalTime.Add(elapsedNs)
+       if t.hook != nil {
+               t.hook(t.label, elapsed.Milliseconds())
+       }
 }
```

We can setup same thing for histogram as well (histogram already has a hook but there is no way to set it yet)
 
(One downside here I could think of is we expose some global variables here in order to do this)

Any feedback / comment / suggestions are appreciated!

**Comment by derekperkins** [comment]
I'm hesitant to do too much work here when the long-term plan should be to replace our stats/trace functionality with OpenTelemetry.

**Comment by narcsfz** [comment]
Thanks for the feedback @derekperkins, it makes sense. What's the expected timeline for OpenTelemetry?

If we are moving towards OpenTelemetry would it be an argument to take step and unblock the application that wants to integrate with statsd / opentsdb right now (versus defining a future-proof API)?

**Comment by derekperkins** [comment]
I'm not opposing changes, just adding context that I think our whole stats layer should be removed, including whatever hooks or changes you make now. I'd mark them as experimental so that we aren't bound by our deprecation policy.

I'm not the only or the strongest stakeholder around stats, so happy to get feedback from others.
