### ISSUE TITLE
why do not define < and > in sql.go

### ISSUE THREAD

**Issue by david-sail** [vitessio/vitess#7322]
define variables:
const LE = 57455
const GE = 57456
const NE = 57457

   why do not define GT and LT? return ascii code for < and >

here is scan code:

		case '<':
			switch tkn.lastChar {
			case '>':
				tkn.next()
				return NE, nil
			case '<':
				tkn.next()
				return SHIFT_LEFT, nil
			case '=':
				tkn.next()
				switch tkn.lastChar {
				case '>':
					tkn.next()
					return NULL_SAFE_EQUAL, nil
				default:
					return LE, nil
				}
			default:
				return int(ch), nil
			}

**Comment by shlomi-noach** [comment]
`sql.go` is code generated by a CC (compiler compiler). @david-sail can you please clarify what the problem is in the first place, is there some functionality missing, or is this just a curious question?

**Comment by Anders-PlanetScale** [comment]
This issue appears to be stale. If there is still an outstanding issue or more information to provide please open a new issue.
