### ISSUE TITLE
Feature Request: Incorporate more VTExplain-style information into EXPLAIN FORMAT=vitess

### ISSUE THREAD

**Issue by jmoldow** [vitessio/vitess#7335]
#### Feature Description

VTExplain, particularly with `-output-mode json`, provides a rich set of information that isn't available via `EXPLAIN FORMAT=vitess`. Placing more of that information into the `EXPLAIN FORMAT=vitess` (or into a new `EXPLAIN` format; or optionally enabled with an additional parameter to `EXPLAIN FORMAT=vitess`) would increase the utility of `EXPLAIN FORMAT=vitess`, and decrease the amount of work needed to expose that information.

I'm open to other suggestions here. This also isn't an important request. Just seems like it'd be nice-to-have for the ecosystem.

This complements #7333 . Neither feature is an important request. And there is a lot of overlap between them, so if we do one, we don't have to do both. On the other hand, each one also supports use-cases that aren't supported by the other, so they can both be implemented without being a waste of effort.

This would also be complemented nicely by #4448 / #7273. In VTExplain, if you have a query that utilizes a lookup vindex, the expansion of the lookup table query will show the correct shard (since it is based on the static hash value), but the expansion of the final query will show an arbitrary shard, since VTExplain cannot actually perform the lookup. One advantage that `EXPLAIN FORMAT=vitess` has in this case over the proposal in #7333, is that with #4448 / #7273, `EXPLAIN` could actually perform the lookup in step 1, and then display the actual target shards for step 2 (or the absence of target shards, if the lookup doesn't find a match).

#### Use Case(s)

Seeing the query plans of live queries in the live vschema, made easily available to all service owners. For example, to see the vindex that gets utilized by a query, and to see any lookup vindex table queries that are auto-generated due to the selection of a lookup vindex, and to see which shards are targeted by the query, etc.

**Comment by harshit-gangal** [comment]
PR: https://github.com/vitessio/vitess/pull/10556
