### ISSUE TITLE
mysqldump: fails with recommended settings on mysql > 5.7

### ISSUE THREAD

**Issue by avaidyanatha** [vitessio/vitess#7351]
When trying to run mysqldump against my Vitess cluster using [this guide](https://vitess.io/docs/user-guides/configuration-basic/exporting-data/), I run into this error:

```
mysqldump: Couldn't execute '/*!80000 SET SESSION information_schema_stats_expiry=0 */': vtgate: <HOSTNAME>:15000/: unsupported construct in set: session information_schema_stats_expiry = 0 (1105)
```

### Reproduction
Simply run a mysqldump binary version greater than 5.7.

**Comment by deepthi** [comment]
What is your vitess version and mysql version?

**Comment by aquarapid** [comment]
This happens with MySQL 8.0.21 (community) and Vitess 9.0 RC1.  From the MySQL source, mysqldump tries to set that variable unconditionally in newer versions, and there isn't a mysqldump flag to prevent it from doing so.
