### ISSUE TITLE
vtgate throws invalid table name while table can be queried through mysql

### ISSUE THREAD

**Issue by aberfeldy** [vitessio/vitess#7371]
#### Overview of the Issue

Migrated some dbs to a vitess cluster (mysql 5.7). When I query through the vtgate I get 
`ERROR: vtgate: http://db-zone1-vtgate-xxxxxxxxxxx: invalid table name: db.Language` 

When connecting to the mysql client with user vt_dba directly I get the proper response.
```
$ mysql -uvt_dba -S /vt/socket/mysql.sock
mysql> use vt_db;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from Language;
+--------+--------------+
| langID | languageText |
+--------+--------------+
|      1 | normal       |
|      2 | no           |
|      3 | en           |
+--------+--------------+
3 rows in set (0.00 sec)

```
Is it due to Language actually being a reserved keyword in mysql that vtgate fails calling the query?

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploying an unsharded keyspace with helm chart using the :latest image tags

1. Create a table named Language

 ```sql
    CREATE TABLE `Language` (
  `langID` int(11) NOT NULL AUTO_INCREMENT,
  `languageText` varchar(50) NOT NULL,
  PRIMARY KEY (`langID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;
 ```

3. Run `SELECT * FROM Language`

#### Operating system and Environment details

vitess installed via helm chart on kubernetes
images: all using latest tag

**Comment by sougou** [comment]
It's likely that the table is not in the vschema. Take a look at https://vitess.io/docs/user-guides/vschema-guide/unsharded/.

We should keep the issue open. I think vitess should also create the vschema entry automatically when a `create table` is issued. That will be a better user experience.

**Comment by aberfeldy** [comment]
well I applied a vscheme with `vtctlclient ApplyVSchema -vschema="$(cat vscheme_init.json)" db` which contained something like the following, so I'd expecting the table to be in the scheme. ` vtctlclient GetVSchema db` also shows the correct vscheme containing "Language".

vscheme_init.json:
```json
{
  "tables": {
    [...]
    "GroupMember": {},
    "Language": {},
    "Layout": {},
    "LayoutType": {},
    [...]
  }
}
```

**Comment by sougou** [comment]
I think it's a problem with escaping. Vitess escaping requirements are not identical to mysql. Can you try back-quoting the table:

```
select * from `Language`
```

**Comment by aberfeldy** [comment]
same result:
```sql
mysql> select * from `Language`;
ERROR 1105 (HY000): vtgate: http://db-zone1-vtgate-xxxxxxxxxxx/: invalid table name: db.Language


mysql> show tables like "Language";
+---------------------------------+
| Tables_in_vt_db (Language) |
+---------------------------------+
| Language                        |
+---------------------------------+
1 row in set (0.05 sec)

```

**Comment by sougou** [comment]
In that case, I'll invoke the experts for a drill down.

**Comment by harshit-gangal** [comment]
Have you used VReplication for migration?

**Comment by aberfeldy** [comment]
No, just imported sql dumps after a bunch of `CREATE TABLE`'s

**Comment by harshit-gangal** [comment]
Can you add Build* variables from vtgate UI?

**Comment by harshit-gangal** [comment]
Also, have you set Autoincrement sequence table on Vschema?

**Comment by aberfeldy** [comment]
"BuildGitBranch": "master",
"BuildGitRev": "0ca4f9937",
"BuildHost": "14a7573ba298",
"BuildInformation": {"14a7573ba298.vitess.1611550390.0ca4f9937.master.0": 1},
"BuildNumber": 0,
"BuildTimestamp": 1611550390,
"BuildUser": "vitess"


no, it's just the table names in the vschema

**Comment by harshit-gangal** [comment]
I added and e2e and the test passed.
https://github.com/planetscale/vitess/compare/0ca4f9937...planetscale:language-table-test

**Comment by aberfeldy** [comment]
So I ran your test against our vtgate, to see what it does: 
```
~/Dev/go/src/github.com/planetscale/vitess/go/test/endtoend/vtgate/unsharded • go test main_test.go                                                              16:55
--- FAIL: TestLanguageTable (0.17s)
    main_test.go:238:
        	Error Trace:	main_test.go:244
        	            				main_test.go:271
        	            				main_test.go:238
        	Error:      	Received unexpected error:
        	            	vtgate: http://db-zone1-vtgate-xxxxxxxxxxx/: invalid table name: db.Language (errno 1105) (sqlstate HY000) during query: select * from Language
        	Test:       	TestLanguageTable
FAIL
FAIL	command-line-arguments	0.504s
FAIL
```

So I tried on another vitess cluster running the v8.0.0 docker images and voila it works. Tuning down the db cluster from :latest to :v8.0.0 and it also works there (test runs with OK against v8.0.0). Should have tried that before... 
But still I'm wondering what went wrong. Even rebuilding the cluster with the latest tag and applying the `CREATE TABLE` on an empty mysql didn't help.

**Comment by harshit-gangal** [comment]
I have very less information about images. 
@deepthi what do you think?

**Comment by harshit-gangal** [comment]
We have release v9.0.0, can you try the same thing on 9.0 image?

**Comment by aberfeldy** [comment]
updated to v.9.0.0 and reimported the db without any issues. Everything looks fine thank you

**Comment by deepthi** [comment]
We'll close the issue for now. Please open a new one if you run into this again.

**Comment by harshit-gangal** [comment]
We have found the issue. The fix is here: https://github.com/vitessio/vitess/pull/7511
