### ISSUE TITLE
Fix & Improve WithDDL by introducing a schema version backend table

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#7392]
Some of vitess's own features use backend tables for persisting state. Right now these are multiple vreplication tables, `schema_migrations`, `heartbeat`. The number of tables can grow in time.

Each of these tables has a schema, and naturally new developments require changes to the schema. The issue is to resolve schema changes required by Vites's own code.

[WithDDL](https://github.com/vitessio/vitess/blob/f8c0583edd3abd7d231de36e09b7e1c38bf92096/go/vt/withddl/withddl.go) is meant to be a mechanism that solves this, however it only partially solves the problem.

`WithDDL` works in a way that the app asks it to run some DML query (e.g. a `SELECT`). `WithDDL` runs that query; if it encounters a MySQL DDL error, such as a "bad column", it infers that the schema in the database must be incompatible with the schema definition in code, and proceeds to apply the schema.

This only works when the schema change clearly contradicts the query, like adding or dropping a column. But if the change is an dded index, or a change to a column datatype (`int`->`bigint`), WithDDL does not encounter an error and therefore does not apply the change.

The solution IMO is to have a schema tracking table: a meta table that knows, for each "WithDDL", whether it is up to date or not. I've applied a similar mechanism in `orchestrator` in the past. There's multiple approaches to evaluating whether our schema is up to date. In `orchestrator` this was based on the `git` commit SHA. In Django this is based on a per-schema change. But another approach is to just programmatically checksum the sequence of DDLs and compare/persist that.

So my suggestion is to create a table like so:

```sql
create table `internal_schema_checksum (
  with_ddl_name varchar(32) not null primary key,
  checksum varchar(64),
  last_update timestamp not null
)
```

This table format is not going to change.

So applying a WithDDL change is based on consulting with this table. Once WithDDL applies a schema change, it persists the checksum it has applied, so that the next WithDDL does not need to attempt further changes.

This means any single change to the WithDDL sequence generated a new checksum, which then implies we correctly apply the new schema.

I remember @sougou once mentioning a DDL can change during the lifetime of a vttablet -- I don't recall what's the use case? A restore from backup? I was thinking WithDDL only needs to check once upon startup, and we can also force upon restore from backup or any other special case.

Somewhat related: https://github.com/vitessio/vitess/issues/7388

**Comment by jmoldow** [comment]
What is the need for persisting the checksum, vs. dynamically computing the current checksum by dumping the current schema?

**Comment by shlomi-noach** [comment]
@jmoldow the way our DDL looks like and the way the schema dump looks like are very different. We create an initial table and then add a series of changes (`add` this column, `modify` that column). We work this way because we have to provide the upgrade path from previous version (note: we don't strictly "have to"; we could use a declarative approach rather than an imperative approach, but that'sa different discussion). The schema dump only shows the final `CREATE TABLE`(s) sequence. Moreover, we need to know which tables exactly are referenced, and that means we need to be a SQL engine for ourselves, which is an overhead. Last, we need to be able to ignore noise, such as the `AUTO_INCREMENT` value in production, etc.

**Comment by sougou** [comment]
The use case where the schema went back to the old snapshot was reported by @dweitzman. What happened was that they lost the database and restored it from the backup, without restarting vttablet. This caused an outage.

Those days, we used to allow all kinds of things: unprovision vttablet and later assign it to a different keyspace, etc. We are a lot more opinionated now. So, maybe we can now require you to restart vttablet if you change mysql underneath.

**Comment by shlomi-noach** [comment]
If we're good to assume the schema cannot change during the lifetime of the tablet, then we may just try the brute force approach: force-apply the schema upon vttablet startup without even checking.

**Comment by dweitzman** [comment]
> The use case where the schema went back to the old snapshot was reported by @dweitzman 

Doesn't ring a bell for me, so it may have been someone else

**Comment by shlomi-noach** [comment]
Hit an important use case myself just now. Suggested fix is https://github.com/vitessio/vitess/pull/7419/commits/3ba8845ca6547cf7562fbc1e1758bd684d84a9d7 : we use `sync.Once` to just go ahead and apply the schema upon first use of WithDDL. This will ensure adding an index, for example, gets applied.

**Comment by mattlord** [comment]
I'm closing this for now as WithDDL has been removed/replaced. If I'm missing something please let me know and we can re-open it.

**Comment by shlomi-noach** [comment]
Definitely not needed anymore. We're using `schemadiff` to set up the backend tables.
