### ISSUE TITLE
feature request: VTGate support for retrieving GTIDs from shards

### ISSUE THREAD

**Issue by gordonyoon** [vitessio/vitess#7400]
#### Feature Description

Expose a VTGate command that retrieves the GTID of a given shard.

Our current solution is to run the following commands:
```
SHOW vitess_shards;
for each:
  USE keyspace/shard;
  SELECT @@global.gtid_executed;
```

#### Use Case(s)

We have a query-cache system that relies on the VGTID passed through VStream. From the query-cache, we get the current GTID for a shard and apply messages from VStream based on the relative position of the VGTID to the one retrieved directly from VTGate.

**Comment by gordonyoon** [comment]
Queries to `SHOW vitess_shards` frequently returns the following error:
```
Code: UNKNOWN
vtgate: http://0765d3618921:15001/: keyspace names fetch error: interrupted: keyspaces
```

From Jacques:
> The timeout for that query (when it hits the topology) is rather short;  but the underlying problem is that those entries are cached for a very short amount of time by vtgate.  We can boost the cache TTL; which will make it perform better in the general case.  But the occasional timeout is still possible (but less likely/frequent as you up the TTL).

**Comment by harshit-gangal** [comment]
This can be supported with a new query syntax
`SHOW GLOBAL VGTID_EXECUTED` - This will give VGTID from selected keyspace
`SHOW GLOBAL VGTID_EXECUTED FROM <KEYSPACE>` - This will give VGTID from provided keyspace

**Comment by gordonyoon** [comment]
It would be great to also understand the availability of the command.

**Comment by harshit-gangal** [comment]
@gordonyoon The command is as available as the cluster.

**Comment by harshit-gangal** [comment]
We have added 2 for commands

SHOW GLOBAL GTID_EXECUTED - This will give GTID from all shards in the selected keyspace
SHOW GLOBAL GTID_EXECUTED FROM <KEYSPACE> - This will give GTID from all shards in provided keyspace
