### ISSUE TITLE
Feature Request: slim down the release build Docker images for hub.docker.com/r/vitess/vtexplain

### ISSUE THREAD

**Issue by jmoldow** [vitessio/vitess#7401]
#### Feature Description

At https://hub.docker.com/r/vitess/vtexplain , the image for tag `v9.0.0` is 2.75GB.

Somehow, the `latest` image manages to be only 56.4 MB, which is much more reasonable.

The Dockerfile definitions are different for some reason. Compare these two:

- https://hub.docker.com/layers/vitess/vtexplain/latest/images/sha256-0e3d3a69394a6562ab06e5a04bf2405ddd0ff7f88a1d835c75c75bc8b23cc936?context=explore
- https://hub.docker.com/layers/vitess/vtexplain/v9.0.0/images/sha256-bebc3c25bab57989b388638e2f87e50092a7cb515273b4dde5741213686c18cf?context=explore

Do the release builds need to be that big? Can they be the same as the `latest` build?

It's probably too late to change the existing release builds, since those are expected to be immutable. But can it be changed for future releases?

#### Use Case(s)

Being able to `docker pull vitess/vtexplain:$version` and `docker run vitess/vtexplain:$version` on your local development computer, for easy switching between versions, instead of having to install go and build the client manually for each new version.

This Docker image should be much more compact than the `vitess/base` image, which is multiple GB and takes a long time to download onto a local development computer without a blazing fast internet connection.

**Comment by jmoldow** [comment]
The slim Dockerfile build in `:latest` matches the definition in https://github.com/vitessio/vitess/blob/master/docker/k8s/vtexplain/Dockerfile . So I'm not sure where the bulky versioned images are coming from. Are we doing a full build of the Vitess service, and uploading it as if it were just `vitess/vtexplain`?

**Comment by deepthi** [comment]
As I suspected, the build configuration on dockerhub was wrong. For release tags, vtexplain was being built from the main Dockerfile instead of the vtexplain version of the Dockerfile.
I have fixed the build configuration and will trigger a build as soon as dockerhub lets me do that.

**Comment by deepthi** [comment]
I have pushed a new `vtexplain:v9.0.0`. Please try it out and let me know if it doesn't work.

**Comment by jmoldow** [comment]
`docker pull vitess/vtexplain:v9.0.0` and `docker run vitess/vtexplain:v9.0.0` seem to be working, thanks!
