### ISSUE TITLE
How Can I import file data to vitess DB? 

### ISSUE THREAD

**Issue by happi-lee** [vitessio/vitess#7427]
I'd like to try a bulk insert operation to Vitess Database. (for a test, before production)
 I noticed in the page below that vitess supports the 'load data' function.
https://vitess.io/docs/reference/compatibility/mysql-compatibility/#load-data-statement

I tried Load data through the Vitess guide document, but it failed with the following error message.

1.in my mysql Database, It worked
 mysql> LOAD DATA LOCAL INFILE '/home/ubuntu/environment/loaddata/loaddata_emp.txt' INTO TABLE emp FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
 Query OK, 4 rows affected, 7 warnings (0.01 sec)
 Records: 4 Deleted: 0 Skipped: 0 Warnings: 7

2.vitess Database, It occurs an error.
 mysql> LOAD DATA LOCAL INFILE '/home/ubuntu/environment/loaddata/loaddata_emp.txt' INTO TABLE emp FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES;
 ERROR 1105 (HY000): vtgate: http://example-zone1-vtgate-bc6cde92-6bbdc9c7cc-7zwtd:15000/: syntax error at position 5 near 'LOAD'

**Comment by askdba** [comment]
Hi, Vitess does not support `LOAD DATA IN FILE` you can either by pass the vtgate and go directly to MySQL backend or use other methods documented here https://vitess.io/docs/user-guides/migration/migrate-data/

**Comment by askdba** [comment]
Hi @happi-lee are you still struggling with the import of your data?
