### ISSUE TITLE
MoveTables - Support on_ddl Configuration

### ISSUE THREAD

**Issue by msolters** [vitessio/vitess#7438]
#### Feature Description

The `MoveTables` command should support, syntactically, a way to instruct Vitess as to how to handle DDLs that are encountered in the resulting vreplication streams.  That is, one should be able to issue a `MoveTables` and specify "ignore DDLs" or "apply DDLs" etc at that time.

#### Use Case(s)

Any time you are moving tables that may have DDLs acting on them

**Comment by mattlord** [comment]
Fixed in: https://github.com/vitessio/vitess/pull/11532
