### ISSUE TITLE
Enforced Semi Sync falls back to async replication

### ISSUE THREAD

**Issue by marcelo140** [vitessio/vitess#7446]
#### Overview of the Issue

When setting vtorc's `Durability` to `semi_sync` , Vitess sets `rpl_semi_sync_master_timeout` to an unreachable value in order to not fallback to async replication. However, by killing the query after 15s, the transaction is still committed to the storage engine even though it didn't receive any acknowledgement from a replica. This happens both when `rpl_semi_sync_master_wait_point` is set to `AFTER_COMMIT` or `AFTER_SYNC`.

#### Reproduction Steps

1. Deploy a keyspace where `tabletPools` has `replicas` set to `1` and set the orchestrator's `Durability` setting to `semi_sync`. The keyspace was sharded equally into 3 shards.

1. Deploy the following `vschema`:

    ```javascript
    {
      "sharded": true,
      "vindexes": {
        "hash": {
          "type": "hash"
        },
      "tables": {
        "account_status": {
          "column_vindexes": [
            {
              "column": "account_id",
              "name": "hash"
            }
          ]
        }
      }
    }
    ```

1. Deploy the following `schema`:

    ```sql
    create table account_status(account_id varchar(64), status varchar(128), primary key(account_id));
    ```
1. The query will hang for 15s and fail, but the tables will still be created.
1. Run `INSERT INTO account_status (account_id, status) VALUES ('1', 'online');`
1. Observe that, as when we were creating the tables, the `INSERT` will fail after 15s due to context deadline exceeded, but the data will still be persisted in the database. VTTablet logs report the query as cancelled.

#### Binary version

```sh
$ vtgate --version
Version: daa608598 (Git branch 'heads/v9.0.0') built on Tue Jan 26 13:48:04 UTC 2021 by vitess@d3f21ae8881d using go1.15.6 linux/amd64
```

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`): Debian GNU/Linux 10 (buster)
- Kernel version (output of `uname -sr`): Linux 4.19.157
- Architecture (output of `uname -m`): x86_64
- mysqld: mariadb:10.3.20

#### Log fragments
VTTablet's log
```
E0204 18:03:22.164876       1 query_executor.go:385] failed to reload schema Code: DEADLINE_EXCEEDED
resource pool context already expired
E0204 18:03:22.166164       1 tabletserver.go:1339] Code: CANCELED
```

**Comment by askdba** [comment]
Checking some documentation about this https://mariadb.com/kb/en/semisynchronous-replication/

**Comment by GuptaManan100** [comment]
Vitess has dropped support for MariaDB since v14.0.0. If this problem is happening with MySQL as well with the latest versions of Vitess, please reopen the issue.
