### ISSUE TITLE
Add support for `GROUP BY WITH ROLLUP` in the Vitess query parser

### ISSUE THREAD

**Issue by yuluomeng** [vitessio/vitess#7476]
#### Feature Description

We've been slowly migrating our queries over to Vitess, and I think we've run into an incompatibility between Vitess and MySQL that I haven't found documented in the docs or the [unsupported test suite cases](https://github.com/vitessio/vitess/blob/master/go/vt/vtgate/planbuilder/testdata/unsupported_cases.txt) (though there's a chance I may have missed it!). Specifically, we have a table that looks something like

```sql
CREATE TABLE `purchases` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `month` varchar(12), # formatted YYYY-MM
  `customer_id` varchar(36),
  `plan_id` varchar(48),
  `money` double,
)
```

and a query that looks something like

```sql
select month,
       plan_id,
       sum(money),
       count(distinct customer_id)
  from purchases
 group by month, plan_id with rollup
```

This runs correctly against our current MySQL setup using [MySQL's `GROUP BY WITH ROLLUP` feature](https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html), but Vitess 9.0 throws a `syntax error at position 497 near 'with'` which I'm guessing means that it doesn't know how to parse the `with rollup` part of the query. (The query without the `with rollup` part runs fine)

#### Use Case(s)

We use this query to aggregate our purchases both on a per-month level and on a per-month-per-plan level, and want to avoid having to run this query twice with different `group by` columns, since the table is kind of big which makes the query somewhat expensive.

Would love to understand if this is an incompatibility and if so, if you have any workarounds that may be available.

Apologies in advance if this isn't quite the right place / way to ask about this - we're just getting started with Vitess so this is my first time posting here. Thank you!

**Comment by jmordica** [comment]
I have also experienced this.

**Comment by quantaprasanth** [comment]
Is there any update on when this issues will be resolved?
