### ISSUE TITLE
Allow plugin implementation for CREATE and DROP DATABASE

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7525]
#### Feature Description

We should add support for plugin implementations of CREATE DATABASE and DROP DATABASE.

* The default plugin will return an error (NOT_ALLOWED or something like that).
* For CREATE, if database (keyspace) already exists we return an error, otherwise we call the plugin.
* For DROP, if database (keyspace) does NOT exist, we return an error, otherwise we call the plugin.

#### Use Case(s)

Frameworks like Rails create temporary databases for running test suites.

**Comment by systay** [comment]
The default plugin should return a failure, not a no-op, right?

**Comment by deepthi** [comment]
> The default plugin should return a failure, not be a no-op, right?

Good point. I will edit the description.
