### ISSUE TITLE
Incorrect Routing to Unmanaged Keyspace for 'SHOW VARIABLE' queries in v9.0.0

### ISSUE THREAD

**Issue by jawabuu** [vitessio/vitess#7532]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

I am experiencing an issue in v9.0.0 where queries like `SHOW VARIABLES LIKE 'sql_mode'` are being routed to the unmanaged keyspace despite explicitly selecting a managed keyspace.
The cluster consists of the following;
Unmanaged Keyspace - **ext_db**
Managed Keyspace - **exampledb** with `master, rdonly & replica` tablets.
Run  `use exampledb@replica`
Run `SHOW VARIABLES LIKE 'sql_mode'`
Error
```
1105, 'vtgate: http://example-zone1-vtgate-bc6cde92-5f6b95c68d-qh28g:15000/: target: ext_db.-.replica: no valid tablet'
```
Query is running against `ext_db` instead of `exampledb`

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following operator on your k8s cluster

```bash
 kubectl kustomize github.com/planetscale/vitess-operator.git/deploy?ref=v2.3.0 | sed "s/v2.0.0/v2.3.0/g" | kubectl apply -f -
```

1. Deploy the following cluster.yml:
https://gist.github.com/jawabuu/da27bb6bbb562d9caa5d1692955c892a#file-vitess-cluster-yml
1. Connect to vtgate
1. Run  `use exampledb@replica`
1. Run `SHOW VARIABLES LIKE 'sql_mode'`
Error
```
1105, 'vtgate: http://example-zone1-vtgate-bc6cde92-5f6b95c68d-qh28g:15000/: target: ext_db.-.replica: no valid tablet'
```
Query is running against `ext_db` instead of `exampledb`
1. Run `SELECT ..` or `SHOW TABLES..` 
No error is returned.

Below are 2 queries to illustrate this

```
mysql> SHOW variables like 'ssl';
ERROR 1105 (HY000): vtgate: http://example-zone1-vtgate-bc6cde92-5f6b95c68d-qh28g:15000/: target: ext_db.-.replica: no valid tablet
mysql> SHOW variable like 'ssl';
ERROR 1064 (42000): vtgate: http://example-zone1-vtgate-bc6cde92-5f6b95c68d-qh28g:15000/: target: exampledb.-.replica, used tablet: zone1-4112137365 (10.42.1.65): vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'variable like 'ssl'' at line 1 (errno 1064) (sqlstate 42000) (CallerID: vtgate): Sql: "SHOW variable like 'ssl'", BindVars: {}
```

#### Binary version
```sh
Version: 10.0.0-SNAPSHOT (Git revision 0a9e2dd40 branch 'master') built on Mon Feb 22 10:59:07 UTC 2021 by vitess@f62d43cab080 using go1.15.6 linux/amd64
```

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Kernel version (output of `uname -sr`): Linux 5.4.0-65-generic
- Architecture (output of `uname -m`): x86_64

#### Log Fragments
@harshit-gangal 
@deepthi

**Comment by harshit-gangal** [comment]
routing issue is fixed with #7531 

You are seeing no valid tablet on unmanaged keyspace, is that because you do no have a replica setup there?

**Comment by jawabuu** [comment]
Hey @harshit-gangal, you are correct.
I have no replica in unmanaged keyspace.
Only externalmaster.
The issue here is why when selecting replica in managed keyspace, the query is being routed to unmanaged keyspace.
Point to note is that this only affects `SHOW VARIABLE` queries.

**Comment by jawabuu** [comment]
@systay @harshit-gangal Thanks for the fix.
When should an image be ready for testing?

**Comment by jawabuu** [comment]
Fix confirmed with latest image.
`vitess/lite@sha256:324300f8031f1681bccff73e89cd95e5fe7b1d8045366486079a2f328d98cfb7`
Thanks for the quick turnaround @systay @harshit-gangal 
Feel free to close.

**Comment by jawabuu** [comment]
Hey @systay @harshit-gangal 
Same issue is occurring now but with `select` statements.
`SELECT` statements are being routed to `external_db` keyspace.

**Comment by harshit-gangal** [comment]
I could not find you message here. I received a mail that you are having same issue with select statement, can you help me for which query are you seeing this?

**Comment by jawabuu** [comment]
Sorry @harshit-gangal False alarm. It was a different issue that happened after using `MoveTables` instead of `VReplication`.
I will carry out some more tests and get back to you.
