### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7533]
#### Feature Description
Right now we produce errors like "no valid tablet", which are accurate but not very helpful. Sometimes the error messages also contain references to internal functions like `execInsertUnsharded`.

- [x] Remove vitess-internal texts from error messages (e.g. function names)
- [x] Every error must have some error code, and should closely match the type of error defined by MySQL. If possible also return root cause.
- [x] Document all error messages and root causes https://github.com/vitessio/website/pull/750

#### Use Case(s)
VTAdmin
Usability

**Comment by derekperkins** [comment]
This would be very useful to support on the Go driver side. We currently have a ton of text parsing to recreate the original proto error struct.

**Comment by GuptaManan100** [comment]
Is there something pending on this issue? We are now generating documentation for the website automatically.

**Comment by harshit-gangal** [comment]
The scoped work is completed.
