### ISSUE TITLE
Document which functional vindex types are capable of mapping NULL values

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#7551]
Not all vindex types are capable of mapping `NULL` SQL values.

For example, the `hash` vindex type outputs `DestinationNone` for a `NULL` SQL value.  As a result, any vschema that uses a primary vindex of type `hash`, effectively cannot have `NULL` input values for that primary vindex column for any rows.

Other vindex types, such as `xxhash` or `unicode_loose_md5` is happy to map `NULL` values.

We should document this.

**Comment by hallaroo** [comment]
PR opened to document this here: https://github.com/vitessio/website/pull/714
