### ISSUE TITLE
Materialize: allow specifying cells for selecting source tablets 

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#7555]
#### Feature Description
MoveTables and Reshard have the `-cells` parameter that allows the user to specify which cells to select source tablets to replicate from. This should be added to Materialize. 

Currently it uses the local cell and if there are no candidates in that cell to replicate from, the streams get stalled.

A couple of other issues around this:
* We may also want to add `-tablet_types` to limit the kind of tablets used as source tablets
* `CreateLookupVindex` uses `-cell`. We should change that to `-cells` for uniformity

**Comment by deepthi** [comment]
Fixed in #7562
