### ISSUE TITLE
MySQL 8.0 binlog compression does not work with Vitess VReplication

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#7567]
Scenario:
  * MySQL Community 8.0.21
  * Vitess recent master (bba94ad)
  * Two keyspaces (unsharded):
    * `keyspace1`
    * `keyspace2`
  * MySQL binlog compression enabled via my.cnf setting on all tablet instances:
  ```
binlog_transaction_compression = ON
  ```
  * Connect to vtgate and look at the binlog compression variables:
  ```
mysql> show global variables like '%binlog_transaction_com%';
+-------------------------------------------+-------+
| Variable_name                             | Value |
+-------------------------------------------+-------+
| binlog_transaction_compression            | ON    |
| binlog_transaction_compression_level_zstd | 3     |
+-------------------------------------------+-------+
  ```
  * Create a test table and insert some data:
  ```
mysql> use keyspace1;
Database changed
mysql> create table t1 (c1 int, primary key (c1));
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t1 (c1) values (1),(2),(3),(4);
Query OK, 4 rows affected (0.01 sec)

mysql> select * from t1;
+----+
| c1 |
+----+
|  1 |
|  2 |
|  3 |
|  4 |
+----+
4 rows in set (0.01 sec)
  ```
  * Now start a `Materialize` for table `t1` from `keyspace1` to `keyspace2`:
  ```
$ vtctlclient -server 127.0.0.1:15999 Materialize '{"workflow": "workflow1", "source_keyspace": "keyspace1", "target_keyspace": "keyspace2", "table_settings": [{"target_table": "t1", "source_expression": "select * from t1", "create_ddl":"copy"}]}'
  ```
  * Check that the copy occured:
  ```
mysql> use keyspace2;
Database changed
mysql> select * from t1;
+----+
| c1 |
+----+
|  1 |
|  2 |
|  3 |
|  4 |
+----+
4 rows in set (0.01 sec)
  ```
  * Now insert another row into `keyspace1.t1`, and see if it was copied over:
  ```
mysql> use keyspace1;
Database changed
mysql> insert into t1 (c1) values (5);
Query OK, 1 row affected (0.02 sec)
mysql> use keyspace2;
Database changed
mysql> select * from t1;
+----+
| c1 |
+----+
|  1 |
|  2 |
|  3 |
|  4 |
+----+
4 rows in set (0.00 sec)
  ```
  So, apparently the initial row copy works, but replication of later inserts does not.  Let's look at the workflow status:
  ```
$ vtctlclient -server 127.0.0.1:15999 workflow keyspace2.workflow1 show
{
        "Workflow": "workflow1",
        "SourceLocation": {
                "Keyspace": "keyspace1",
                "Shards": [
                        "0"
                ]
        },
        "TargetLocation": {
                "Keyspace": "keyspace2",
                "Shards": [
                        "0"
                ]
        },
        "MaxVReplicationLag": 0,
        "ShardStatuses": {
                "0/zone1-0000000900": {
                        "MasterReplicationStatuses": [
                                {
                                        "Shard": "0",
                                        "Tablet": "zone1-0000000900",
                                        "ID": 1,
                                        "Bls": {
                                                "keyspace": "keyspace1",
                                                "shard": "0",
                                                "filter": {
                                                        "rules": [
                                                                {
                                                                        "match": "t1",
                                                                        "filter": "select * from t1"
                                                                }
                                                        ]
                                                }
                                        },
                                        "Pos": "MySQL56/4e726174-794f-11eb-8180-60571886d4d6:1-19",
                                        "StopPos": "",
                                        "State": "Running",
                                        "DBName": "vt_keyspace2",
                                        "TransactionTimestamp": 0,
                                        "TimeUpdated": 1614467038,
                                        "Message": "",
                                        "CopyState": null
                                }
                        ],
                        "TabletControls": null,
                        "MasterIsServing": true
                }
        }
}
  ```
  So no obvious errors there.  There is also no obvious error in the target keyspace `keyspace2` master tablet logs:
  ```
I0227 15:02:54.024302  383106 vcopier.go:200] Copying table t1, lastpk: <nil>
I0227 15:02:54.050199  383106 vcopier.go:322] Copy of t1 finished at lastpk: map[lastpk:type:VARBINARY value:"fields:<name:\"c1\" type:INT32 > rows:<lengths:1 values:\"4\" > " ]
I0227 15:02:54.069381  383106 vplayer.go:135] Starting VReplication player id: 1, startPos: 4e726174-794f-11eb-8180-60571886d4d6:1-19, stop: <nil>, filter: keyspace:"keyspace1" shard:"0" filter:<rules:<match:"t1" filter:"select * from t1" > > 
I0227 15:03:58.332532  383106 rpc_server.go:84] TabletManager.VReplicationExec(query:"select id, source, pos, stop_pos, max_replication_lag, state, db_name, time_updated, transaction_timestamp, message from _vt.vreplication where db_name = 'vt_keyspace2' and workflow = 'workflow1'" )(on zone1-0000000900 from ): (*tabletmanagerdata.VReplicationExecResponse)(nil)
  ```

I suspect that some of the new binlog event types introduced by binlog compression are not understood by our binlog player, and leading to this problem.

**Comment by derekperkins** [comment]
This feels like a higher priority item than Severity 3 if we're silently dropping data and not reporting any errors.

**Comment by rohit-nayak-ps** [comment]
This links suggest the change to handle the compressed binlogs on the client side is non-trivial:
https://github.com/siddontang/go-mysql/issues/533
https://github.com/hanchuanchuan/goInception/issues/286

@derekperkins' point is well taken: we shouldn't silently fail!  To start with, while we undertand the changes required to implement this, I will plan to check for this new event (transaction_payload_event, id 40) and error out the workflow.

@sougou, @deepthi  FYI

**Comment by rohit-nayak-ps** [comment]
Fixed in #7670

**Comment by rohit-nayak-ps** [comment]
Was incorrectly closed, since we want to track this until we actually get binlog compression working with vreplication. Only error reporting has been added via #7670

**Comment by mattlord** [comment]
I'm going to park this for now. We do plan to add this support in the future, but it's a matter of prioritization as this will require some significant effort (tests/testing being a big chunk of it). The known reasons being:
- It will take some time to get the codec 100% correct as it's not documented super clearly so we will have to follow the C++ code in [`libbinlogevents`]( https://github.com/mysql/mysql-server/tree/8.0/libbinlogevents) (which I started to do), and you can see [the initial commit adding this support to MySQL here](https://github.com/mysql/mysql-server/commit/1e5ae348c6f760b16a3972d84956358606a30041)
- [`max_allowed_packet`](https://dev.mysql.com/doc/refman/en/server-system-variables.html#sysvar_max_allowed_packet) becomes a consideration at the vitess level because the entire transaction is compressed and sent in a single `transaction_payload_event`
- Related to that, the *compressed* event could be up to 1GB in size and obviously the uncompressed payload could be several times larger. So we'd have to handle that properly, e.g. by using a fixed/capped size buffer and when the uncompressed payload size (part of the header) is too large, uncompress the payload to a ~ mktemp file and stream the results from the file using the buffer 
- There's almost certainly some as yet unknown challenges involved

I put the results of my initial investigation in a branch that you can see here: https://github.com/vitessio/vitess/pull/9556

We will come back to this when the priority of this work increases relative to everything else.

**Comment by derekperkins** [comment]
Noting here that this would've come in handy for us last weekend with some json data. We were manipulating a message table with a large (~1-3 MB) json column. The table is compressed to 3.5 GB, but during processing, generated ~600 GB of binlogs. This should be pretty rare, so this shouldn't necessarily impact the priority, but definitely a nice to have.

This could also have been mitigated with some changes to how messaging causes unnecessary churn when the queue size exceeds the cache size, but that's for another day and another issue.
