### ISSUE TITLE
Documentation support for Mysql X DevAPI

### ISSUE THREAD

**Issue by InfiniteRandomVariable** [vitessio/vitess#7599]
I couldn't find any relevant information/google regarding whether Vitess can support X Dev API and port 33060.
https://dev.mysql.com/doc/x-devapi-userguide/en/
The doc said compatible with MySQL 8.0, means supporting X Dev API also?
Thanks

**Comment by deepthi** [comment]
This is not currently supported.

**Comment by hallaroo** [comment]
We've added a note that this is not supported to the Vitess docs.
