### ISSUE TITLE
Reshard Workflow VSchema validation

### ISSUE THREAD

**Issue by rafael** [vitessio/vitess#7620]
#### Feature Description

Sometimes it is possible to have tables that are not part of the VSchema in VTtablets. Most notably when doing schema changes with tools like ghost. In our environment these tables are kept for sometime in case we need to run some audits or we have to rollback a change. 

Currently, Reshard workflows don't validate if all the tables in the tablet are part of the VSchema. We should add a validation for this. If a table is in the tablet but not in the VSchema, the workflow can't be created. 

At the moment, 
#### Use Case(s)

The use case here is to provide a better experience to Reshard workflows. Let the user early in the process that it needs to do some cleanup, otherwise the overall process will fail.

**Comment by rohit-nayak-ps** [comment]
Fixed by @makinje16  in https://github.com/vitessio/vitess/pull/7977
