### ISSUE TITLE
VReplication: evaluate progress"

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#7631]
Please search the existing issues for relevant feature requests, and use the [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by rohit-nayak-ps** [comment]
@shlomi-noach, is the intent of this issue fixed by https://github.com/vitessio/vitess/pull/7980

**Comment by shlomi-noach** [comment]
Wow this issue seems completely broken. I don't even recall submitting it, I think text focus must have been on the wrong component in my desktop :open_mouth:
