### ISSUE TITLE
decimal not accepting parameters

### ISSUE THREAD

**Issue by gitbernd** [vitessio/vitess#7648]
#### Feature Description

CAST(svMinorVersionId AS DECIMAL(10,0)) is not accepted, DECIMAL can only be used without parameters.

Should also work with parameters.

#### Use Case(s)

SELECT CAST(svVersionIdApp AS DECIMAL(10,0)) FROM svSchemaVersion;

Snippet was part of an existing query which worked on plain MySQL

MySQL version 5.7

**Comment by GuptaManan100** [comment]
This was fixed by https://github.com/vitessio/vitess/pull/12009
