### ISSUE TITLE
[vtadmin] Aggregate table sizes across-shards in schema-related API endpoints

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#7650]
#### Feature Description

For a given table, we want vtadmin to be able to say both how large a table is in-aggregate, as well as what the size of a table is in a particular shard in a keyspace.

**Comment by doeg** [comment]
@ajm188 is this one ok to close given https://github.com/vitessio/vitess/pull/7751 is merged?

**Comment by ajm188** [comment]
It's not merged yet! 😅  Gonna ping Rafa to get his thoughts on the latest changes as well.
