### ISSUE TITLE
[vtadmin|vtexplain] vtexplain is not safe for concurrent use

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#7723]
#### Overview of the Issue

Each time vtadmin's VTexplain endpoint runs, we call `vtexplain.Init` (aside, we should add a `defer vtexplain.Stop()` call but that's a separate issue and not actually a "bug", just a minor improvement to the code). As part of vtexplain's init, it writes to package-private global variables in order to set up a [tablet execution environment](https://github.com/vitessio/vitess/blob/ef31a7a42d0a74590922a31eaccda507b52a1da8/go/vt/vtexplain/vtexplain_vttablet.go#L47-L56) and a [vtgate execution environment](https://github.com/vitessio/vitess/blob/ef31a7a42d0a74590922a31eaccda507b52a1da8/go/vt/vtexplain/vtexplain_vtgate.go#L46-L55). These writes are unguarded (no mutex or other synchronization method), _and_ they are specific to the parameters of a _particular_ vtexplain invocation.

This means we can have the following scenario:

1. Request A calls `vtexplain.Init`, creates execution environment with parameter set A.
2. Request B calls `vtexplain.Init`, overwrites execution environment with parameter set B.
3. Request B calls `vtexplain.Run`, returns successful and sensible result, given that parameter set B was used by the vtexplain execution environment.
4. Request A calls `vtexplain.Run`, returns a _successful and yet nonsensible result_, given that parameter set B was used by the vtexplain execution environment.

There are other, potentially worse (I'm not sure, I haven't looked into to it that much), failure modes where request B calls `Init` somewhere in the middle of request A's call to `Run`, overwriting the execution environment at any point in the middle of the explain invocation, but in any case, we should fix this!

#### Short/long-term Fixes

In the short-term, we can "fix" this in vtadmin by adding a mutex to the api server to prevent multiple calls to `/api/vtexplain` from executing concurrently.

The more correct fix, in my opinion, would be to refactor `package vtexplain` to support more than the original one-shot command-line invocation. This would look something like having `vtexplain.Init` return a `vtexplain.VTExplainer`, which would be a struct wrapping the `explainTopo` along with anything else needed to run the explain. That way, multiple invocations of the endpoint can run without stepping on each other.

**Comment by deepthi** [comment]
Would it be better to enhance vtgate's `explain format=vitess` and use that instead of invoking `vtexplain`?
Ref: #7335 #7273

**Comment by ajm188** [comment]
Oh that's a way better idea!! I keep forgetting about that option. I can play with that in vtadmin and see how it works.

**Comment by ajm188** [comment]
This was obsoleted by #10374, following up in vtadmin to remove the mutex.
