### ISSUE TITLE
vtorc linux binary is not included in the rpm package

### ISSUE THREAD

**Issue by mikolajwalkiewicz** [vitessio/vitess#7733]
#### Feature Description

As per Slack conversation, it looks like the Vitess rpm package is missing vtorc binary for Linux.

Can you please, include it as it would make much easier to follow [some guidelines](https://vitess.io/docs/user-guides/configuration-basic/vtorc/) especially, for the new users. Also, as per documentation, it already looks like it should be part of the package even though it is still in experimental phase.

Thanks

**Comment by askdba** [comment]
Fixed in https://github.com/vitessio/vitess/pull/7750
