### ISSUE TITLE
Flaky TestExecutorAddSequenceDDL

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7736]
--- FAIL: TestExecutorAddSequenceDDL (0.06s)
Error:     executor_vschema_ddl_test.go:372: Code: INTERNAL
        vschema does not contain table test_table in keyspace TestExecutor
        
Error:     executor_vschema_ddl_test.go:380: want autoinc column:"id" sequence:"test_seq" , got autoinc <nil>

**Comment by harshit-gangal** [comment]
not seeing this recently
