### ISSUE TITLE
Column needs to be part of select list if it is used in order by

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#7748]
#### Overview of the Issue

In response to a command like `User.order(:created_at).take(6)` Rails issues query like
```sql
 SELECT users.* FROM users ORDER BY users.created_at ASC LIMIT 6
```
This thows an error on vitess 
```sql
unsupported: in scatter query: order by must reference a column in the select list: users.created_at asc
```

#### Reproduction Steps

Steps to reproduce this issue, example:

1. On vttestserver image in sharded mode create a user table with the following schema
```ruby
create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "email"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "password_digest"
    t.string "remember_digest"
    t.boolean "admin", default: false
    t.string "activation_digest"
    t.boolean "activated", default: false
    t.datetime "activated_at"
    t.string "reset_digest"
    t.datetime "reset_sent_at"
    t.index ["email"], name: "index_users_on_email", unique: true
  end
```
2. Run a schema command
```sql
alter vschema on test.users add vindex `binary_md5`(created_at) using `binary_md5`
```
3. Then issue the rails command `User.order(:created_at).take(6)` to see the error

**Comment by harshit-gangal** [comment]
Even the below query fails with same error
```
SELECT col FROM users ORDER BY created_at ASC LIMIT 6
```

**Comment by harshit-gangal** [comment]
> Even the below query fails with same error
> 
> ```
> SELECT col FROM users ORDER BY created_at ASC LIMIT 6
> ```

PR https://github.com/vitessio/vitess/pull/8070 fixes this type of query which does have * column selection in it.

**Comment by harshit-gangal** [comment]
This is resolved.
