### ISSUE TITLE
vttestserver: "Test" plugins for CREATE/DROP database

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7770]
#### Feature Description
#7381 added support for making CREATE and DROP database pluggable. We should implement "test" plugins for vttestserver/vtcombo.

- vttestserver/vtcombo: vtcombo already creates separate databases for shards. In Vitess a "database" is a keyspace. Existing multi-database support can be extended to allow creation of separate databases for new keyspaces.

#### Use Case(s)
New users testing their dev/ORM framework against Vitess. A lot of frameworks create and drop temporary databases for tests.

EDIT: Created a separate issue #7893 for docker-compose and removed it from this one.

**Comment by shlomi-noach** [comment]
I suggest reassigning this to @systay who wrote #7381

**Comment by deepthi** [comment]
When someone is ready to work on this, they can assign to themselves.
