### ISSUE TITLE
Missing VSchema DDL Statements

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#7789]
#### Feature Description

Currently, there are no VSchema DDL statements to add columns to a table list or to make the table authoritative. These need to be added manually to the Vschema directly.

#### Use Case(s)

Making an authoritative column list is useful in multiple situations described in [Advanced VSchema](https://vitess.io/docs/user-guides/vschema-guide/advanced-vschema/). It would be helpful to be able to do this without manually changing the file.

**Comment by deepthi** [comment]
Prior discussion on #4711.

**Comment by GuptaManan100** [comment]
Closing since there is an open issue
