### ISSUE TITLE
Feature Request: log unsupported queries

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#7859]
In order to get a sense of which Vitess limitations are being hit upon in the query path, it would be nice to log these on vtgate and vttablet

**Comment by harshit-gangal** [comment]
I think logging at vtgate would be sufficient as first there will be only few queries if they reach vttablet will throw error as Vitess limitations, second even if there are some will get caught at VTGate as limitations only.

**Comment by deepthi** [comment]
Do we need to worry about redacting bind variable values?
