### ISSUE TITLE
Flaky TestMakeCommonTags

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7870]
#### Overview of the Issue
--- FAIL: TestMakeCommonTags (0.00s)
    statsd_test.go:455: 
        	Error Trace:	statsd_test.go:455
        	Error:      	Not equal: 
        	            	expected: []string{"a:b", "c:d"}
        	            	actual  : []string{"c:d", "a:b"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 ([]string) (len=2) {
        	            	- (string) (len=3) "a:b",
        	            	- (string) (len=3) "c:d"
        	            	+ (string) (len=3) "c:d",
        	            	+ (string) (len=3) "a:b"
        	            	 }
        	Test:       	TestMakeCommonTags
FAIL
FAIL	vitess.io/vitess/go/stats/statsd	0.049s

#### Reproduction Steps
Failed in CI

**Comment by deepthi** [comment]
Should use `assert.ElementsMatch` instead of `assert.EqualValues`.

**Comment by deepthi** [comment]
Fixed by #7843

**Comment by narcsfz** [comment]
Thanks for fixing it!
