### ISSUE TITLE
Improve ALTER TABLE to support partitioning of not partitioned table

### ISSUE THREAD

**Issue by vkovacik** [vitessio/vitess#7871]
#### Feature Description

`ALTER TABLE` currently (v9.0.0) silently fails to enable partitioning on an existing **not** partitioned table.
This feature request is to fix or add support for `ALTER TABLE t1 PARTITION BY ...`

Please note that e.g. ADD/DROP PARTITION alter options work correctly on already partitioned table. This request is for a not partitioned table.

#### Use Case(s)

Time series table had originally been created with no partitioning. We need to alter the table to enable partitioning. This currently  fails (is ignored).

**Comment by vkovacik** [comment]
**Reproduction steps:**
```
CREATE TABLE t1 (
    id INT,
    year_col INT
);

ALTER TABLE t1
    PARTITION BY HASH(id)
    PARTITIONS 8;
```
https://dev.mysql.com/doc/refman/5.7/en/alter-table-partition-operations.html

**Current behaviour:**
```
SHOW CREATE TABLE t1 \G;
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `year_col` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Expected behaviour:**
```
SHOW CREATE TABLE t1 \G;
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `year_col` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY HASH (id)
PARTITIONS 8 */
```

**Comment by vkovacik** [comment]
vtgate reports error:
```
W0415 00:29:13.406749       1 parser.go:90] ignoring error parsing DDL 'ALTER TABLE t1
    PARTITION BY HASH(id)
    PARTITIONS 8': syntax error at position 29 near 'PARTITION'
```

**Comment by vkovacik** [comment]
@askdba @harshit-gangal 
I've re-tested using Vitess version 11.0.0 and this ticket is not reproducible anymore. I'm assuming that the support `ALTER TABLE t1 PARTITION BY ...` has been added.

**Comment by harshit-gangal** [comment]
I believe it was in 10.0, closing on above comment
