### ISSUE TITLE
TableGC Flaky Test

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#7878]
#### Overview

Not sure if this is already reported, but this test is failing quite frequently. 

```
=== RUN   TestPurge
    tablegc_test.go:331: 
        	Error Trace:	tablegc_test.go:331
        	Error:      	Should be false
        	Test:       	TestPurge
    tablegc_test.go:337: 
        	Error Trace:	tablegc_test.go:337
        	Error:      	Should be true
        	Test:       	TestPurge
    tablegc_test.go:123: 
        	Error Trace:	tablegc_test.go:123
        	            				tablegc_test.go:338
        	Error:      	Should NOT be empty, but was 
        	Test:       	TestPurge
```

**Comment by shlomi-noach** [comment]
Seems to be in similar category of DDL tests: it doesn't make sense for this test to be flaky and this suggests an underlying platform problem. Scheduler gone wrong; VM gone starved.

**Comment by shlomi-noach** [comment]
I suspect this is now solved with the GitHub Actions DNS patch. I do not see these tests failing now.

**Comment by deepthi** [comment]
I saw this again a couple of times today.

**Comment by shlomi-noach** [comment]
I was just about to close this issue... :cry: 
Looking into.
