### ISSUE TITLE
Update health should not nuke out all healthy tablet when the primary tablet returned error

### ISSUE THREAD

**Issue by narcsfz** [vitessio/vitess#7906]
#### Overview of the Issue
I think the change we made here https://github.com/vitessio/vitess/pull/7654/files#diff-b52bf818696494288a93bba0e91b8ff75fb2fd109bb1c80c77d166ea8349b722R452 might leads to some unexpected behavior during an unplanned external reparent failover.

For example, there are 3 tablets t1 (primary), t2, t3. Now t1 crashed and t2 becomes the new primary through an external reparent process. t2 will notify VTGate via the stream connection so that VTGate knows there is a new primary.

However, because t1 crashed, the stream connection also closed, we will jump into updateHealth with `isPrimary = true; isPrimaryUp = false` from the check conn [here](https://github.com/vitessio/vitess/pull/7654/files#diff-c87b92e62c8d14accef2560231f8abeb6e54f66b98fe5d519b15ad44b2b74821R309) and nuke out all the primary tablet -- including the updated one from the healthcheck stream and VTGate needs to wait the poll from topo server to recover from this case.

IMO, we might just want to do delete the crashed tablet from `hc.healthy[targetKey]` here instead of nuking it out completely. 

#### Reproduction Steps
See the description above

#### Binary version
We are on top of `fe6d095ccae0f50356d4691b0171bbeb8778e911`

#### Operating system and Environment details
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```

cc @deepthi

**Comment by deepthi** [comment]
We will probably almost always receive an update from t2 before t1 times out, so this needs to be fixed.

**Comment by wangmeng99** [comment]
The health check for the crashing primary and one for the newly appointed primary could always race. We can use `MasterTermStartTime` to differentiate which check wins.

**Comment by narcsfz** [comment]
I think we already use ` MasterTermStartTime` when we do the insertion on newly appointed primary case: https://github.com/vitessio/vitess/blob/master/go/vt/discovery/healthcheck.go#L438

When the old primary crashed, we just need to remove the tablet from healthy tablet map (without insertion). So I think we don't need compare `MasterTermStartTime` in this case bc we don't want to update/insert the master record

**Comment by wangmeng99** [comment]
> I think we already use ` MasterTermStartTime` when we do the insertion on newly appointed primary case: https://github.com/vitessio/vitess/blob/master/go/vt/discovery/healthcheck.go#L438
> 
> When the old primary crashed, we just need to remove the tablet from healthy tablet map (without insertion). So I think we don't need compare `MasterTermStartTime` in this case bc we don't want to update/insert the master record

AFAIK, these two health check responses race
* newly appointed primary
* health check error on old one

And we have  `healthy map[keyspaceShardTabletType][]*TabletHealth` which is key'ed on tablet type. So when we see a response of 'primary down' that's old (i.e. happened earlier) we shouldn't do anything; but if we see something new (i.e. rapid failure after a primary appointed) we should remove. Am I missing something ?

**Comment by narcsfz** [comment]
> if we see something new (i.e. rapid failure after a primary appointed) we should remove. Am I missing something ?

Yes, that is correct. I think in either case, we would try to remove "old-tablet" from the `healthy` map as long as it's in the `healthy` map.

But I don't think we need to compare the `MasterTermStartTime` here? Since if a stream crashed, no matter how old or new the `MasterTermStartTime` is, we would remove it from the map

**Comment by deepthi** [comment]
Yes, the two healthcheck responses do race. We are doing the right thing when we receive the response from the "newly appointed primary". However, the error from the old one can blow that away if it comes in later.
What @narcsfz is suggesting will work. The error from old primary only removes it from healthy (if it exists). If the response from the new primary was received first, the old primary has already been removed and no work will be done.
