### ISSUE TITLE
jdbc:mysql @replica is not working

### ISSUE THREAD

**Issue by biostone** [vitessio/vitess#7916]
When we were trying to use third-party tool TDDL to automatically separate READ transactions and WRITE transactions, to dispatch WRITE to master tablet only and READ to other replica tablets, we found the jdbc:mysql connection on replica does not work. For example: "jdbc:mysql://192.168.20.231:15306/dbname@replica" is actually connecting to the master tablet.

**Comment by GuptaManan100** [comment]
There are 3 ways of specifying the dbname with MySQL JDBC specified in https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-source-replica-replication-connection.html

- `?propertyName1=propertyValue1` in the URL. For example - `?dbname=test_db@replica`
- `[/[database]]` which is what you tried out
- Put the dbname in the properties options. `props.put("dbname", "dbname@replica");`

We tested it out and all 3 ways seem to be working with Vitess on the master branch with the latest JDBC driver. Could you retry and report your version informations in case of failure? We will also attach the PR adding the test for the driver over here.
