### ISSUE TITLE
The sqlparser library can not parse the “if not exists” field when create table

### ISSUE THREAD

**Issue by l00297133** [vitessio/vitess#7926]
the “if not exists” field in "CREATE TABLE if NOT EXISTS T_user()" parse loss by use function sqlparser.ParseNext

**Comment by harshit-gangal** [comment]
Can you give more details around this? which version and what is the issue you are seeing?

**Comment by harshit-gangal** [comment]
we have a parse_test that shows it works.
PR: https://github.com/vitessio/vitess/issues/7926

**Comment by l00297133** [comment]
where is this case in code， please tell me clearly
