### ISSUE TITLE
vttestserver: default charset

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7942]
#### Feature Description
vttestserver defaults the charset to utf8. Either we should change this to utf8mb4 or provide a way to override it on the docker container (or both).
https://github.com/vitessio/vitess/blob/master/go/vt/vttest/vtprocess.go#L179

#### Use Case(s)
Frameworks set charset. This is required to automate testing.

**Comment by harshit-gangal** [comment]
I am of the opinion that we make it as default on vttablet.

**Comment by deepthi** [comment]
Fixed in #7970
