### ISSUE TITLE
vtgate queries randomly routed to unhealthy or non-existent replicas

### ISSUE THREAD

**Issue by DeathBorn** [vitessio/vitess#7981]
#### Overview of the Issue

queries sent to `@replica` like `SET ..` are sent randomly to alphabetically first keyspace replicas or keyspaces without replicas or keyspaces with all replicas unhealthy.

#### Reproduction Steps

This can be reproduced by local example
*  [Vitess Release 11.0.0-SNAPSHOT-37c09d3be](https://github.com/planetscale/vitess-releases/releases/tag/37c09d3be)
* [vitess-8.0-dev-c02b7d5](https://github.com/planetscale/vitess-releases/releases/download/c02b7d5/vitess-8.0-dev-c02b7d5.tar.gz) 

1. add threshold `-unhealthy_threshold=10s` to `scripts/vttablet-up.sh`
2. Deploy

    ```bash
      source env.sh
      ./101_initial_cluster.sh
      ./201_customer_tablets.sh
     # start unmanaged tablet if needed
    ```

1. Stop customer replicas and rdonly

    ```bash
    vtctl StopReplication zone1-0000000201
    vtctl StopReplication zone1-0000000202
    ```

1. Run query on loop

   ```bash
   while (true) do  date; mysql --host 127.0.0.1 --port 15306 '@replica' -e "set session character_set_results = null;select @@HOSTNAME, @@PORT";  sleep 0.1; done
   ```
1. View error

   ```bash
   # success, picked commerce replica
    +------------+--------+
    | @@HOSTNAME | @@PORT |
    +------------+--------+
    | example      |  17101 |
    +------------+--------+
    .....
    # failure, picked unmanaged keyspace (which does not have any replicas)
    ERROR 1105 (HY000) at line 1: target: unmanaged.0.replica: no healthy tablet available for 'keyspace:"unmanaged" shard:"0" tablet_type:REPLICA '
    ...
    # failure, picked customer replica even if there were no healthy replicas
    ERROR 1105 (HY000) at line 1: target: customer.0.replica: no healthy tablet available for 'keyspace:"customer" shard:"0" tablet_type:REPLICA '
   ```

**Comment by harshit-gangal** [comment]
The planner does not see healthy or unhealthy tablets, to avoid this I would suggest you to connection to VTGate with a default database.

As you are setting `@replica` so that default database should have atleast one healthy tablet.

**Comment by DeathBorn** [comment]
you mean by `default_keyspace@replica` yes ?

**Comment by harshit-gangal** [comment]
yes.

**Comment by harshit-gangal** [comment]
We check the value against the mysql and for that we need a keyspace and tablet_type to query against. If it is not provided, planner will pick a random keyspace and then the a healthy tablet  (in this case replica) will be picked to query. If no healthy tablet is available it will error out.

**Comment by DeathBorn** [comment]
I guess this is about these sysvars https://github.com/vitessio/vitess/blob/master/go/vt/sysvars/sysvars.go#L210

**Comment by DeathBorn** [comment]
in PROD we also use `enable_system_settings=false`

**Comment by harshit-gangal** [comment]
even you set these it will be validated against mysql.

what we can do is to change it to enum where you can set this to ignore.
cc: @systay

**Comment by DeathBorn** [comment]
we think it is possible to workaround by not using those sysvars which are in that check and ignore list and ensuring them in my.cnf.
