### ISSUE TITLE
Flaky test: TestPurge (TableGC)

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#7984]
```
=== RUN   TestPurge
    tablegc_test.go:331: 
        	Error Trace:	tablegc_test.go:331
        	Error:      	Should be false
        	Test:       	TestPurge
--- FAIL: TestPurge (125.03s)
FAIL
FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager/tablegc	206.970s
FAIL

**Comment by shlomi-noach** [comment]
https://github.com/vitessio/vitess/pull/7947 should have fixed this. But apparently didn't. https://github.com/vitessio/vitess/runs/2475285377?check_suite_focus=true

**Comment by deepthi** [comment]
Happened again on #8250

**Comment by shlomi-noach** [comment]
:+1:  will look into it.

**Comment by shlomi-noach** [comment]
another workflow failure url: https://github.com/vitessio/vitess/pull/8255/checks?check_run_id=2736778722

**Comment by shlomi-noach** [comment]
yeah this now fails more often than not :scream:

**Comment by shlomi-noach** [comment]
hopefully resolved by #8270

**Comment by shlomi-noach** [comment]
Nooooo! Just happened again. What is going on?!

https://github.com/vitessio/vitess/pull/8278/checks?check_run_id=2765885600

Only *ever* happens on GitHub CI and *never* on local tests

**Comment by deepthi** [comment]
Right now there are 3 flaky tests in this suite.
![tablegc](https://user-images.githubusercontent.com/388311/159538507-1a47caa4-e824-4134-9562-262b4f083b22.png)

**Comment by shlomi-noach** [comment]
re-investigating
