### ISSUE TITLE
RFC: VTGate Schema Tracking

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#7995]
# Introduction
VTGate does not track table schema. The users have an option to provide an authoritative list of columns for the tables through VSchema which VTGate uses in query plans. If the users does not provide such a list, there are some types of queries which are not supported by VTGate due to lack of information.

# Use Case
With the availability of table schema, Vitess planner will be able to plan more queries. Tracking schema means that VTgate has authoritative information about all tables.
Following query set could be planned:
* SELECT * cross-shard queries that needs evaluation at VTGate level.
* Queries that are not able to resolve the column dependency of the table like query with no table qualifier in the projection/filter list.
* By knowing the column types, Vitess planner can use this information to get comparable value (using WEIGHT_STRING) to handle any comparisons at VTGate.

# Design
There are two aspects here.
* Information Retrieval: Gathering the information about the table schema
* Storage & Versioning: Storing this information at VTGate level and also maintaining the current schema version for each table in the keyspace.

## Information Retrieval
The current plan is to use healthcheck updated from VTTablet to provide the information if there is any change in the table schema. Using this information VTGate can request more information from the VTTablets.

## Storage
VTGates will store the schema in memory and local to themselves. We choose to go with local storage as maintaining a global view needs an external storage to be shared with VTGates and also they would need to sync the version.

### V1
During the first part of the implementation, VTGate's will read the table schema from the master tablets and updates its schema information. More details can be found here #7994

Wins:
1. No coordination needed between VTTablets/VTGates.
2. It solves all the unsupported query that required schema information.
3. Easy to implement

Still unsolved:
Not able to handle when shards differ mostly during schema migration.

### V2
The next part would be to make handle divergent schema state between shards.
VTGate will store schema from all the shards and will make columns authoritative that are identical in all shards.

Potential issues:
 - Will the increased memory pressure on vttablets and vtgates be a problem?
- Increases traffic between VTGate and VTTablet.

# Call for feedback
We're looking for community's feedback on the above suggestions/flow. Thank you for taking the time to read and respond!

**Comment by deepthi** [comment]
Related https://github.com/vitessio/vitess/issues/4669

**Comment by timvaillancourt** [comment]
👋 thanks @harshit-gangal, this is an interesting RFC for Slack!

> Information Retrieval: Gathering the information about the table schema

It seems to me this approach is required because schema migrations can happen out-of-band of Vitess, ie: `gh-ost`, `pt-osc`, direct-`ALTER`s, etc

I am curious if the tight integration of the Online DDL feature is an opportunity to reduce/eliminate the pulling of schema information, ie could the Online DDL workflow hypothetically "inform" `vtgate`s on what is changing as it happens (hand waving)? cc'ing @shlomi-noach

**Comment by shlomi-noach** [comment]
I don't have much insight into VTGate; but Online DDL  -wise, the workflow is perhaps initiated by VTGate/vtctld, yet is actually executed and completed by the tablets. So it would be a tablet's responsibility to inform VTGate that a migration is complete. Add to that the fact that shards operate Online DDL independently of each other. I'm merely adding data points here, that other people can use.

**Comment by harshit-gangal** [comment]
As @shlomi-noach said, Online DDL workflow runs on vttablet so still a notification has to be provided from Vttablet to VTGate. 
What we are looking at is to simplify this notification, in vttablet we have 2 schema tracking happening in parallel, one for vreplication (for historical schema) and another for vtgate (only current schema). So, we indeed to reduce this duplicate effort.

**Comment by timvaillancourt** [comment]
@shlomi-noach / @harshit-gangal thanks for clarifying 👍

**Comment by harshit-gangal** [comment]
The current implementation is sufficient and works as expected. Closing this.
