### ISSUE TITLE
`srv_topo_timeout` of 1s too aggressive

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8010]
A recent change (#7278), introduced a timeout for srv_topo operations.  The default value was set at 1 second.  This seems reasonable, but it has had the unintended side-effect of causing topo timeouts, especially during vtgate startup (tablet wait/healthcheck), for users that have topology spread across multiple DCs.

In the interest of sane defaults, I suggest we lift the default to 5 seconds; and those who need a lower value can set it down.

For discoverability, here is the type of error you would see:

```
E0430 16:34:01.359471       1 resilient_server.go:311] GetSrvKeyspaceNames(context.Background.WithDeadline(2021-04-30 16:34:30.359023101 +0000 UTC m=+30.040465073 [28.999518338s]), xxxx4a1) failed: deadline exceeded: /vitess/tst006/global/cells/xxxx4a1/CellInfo (no cached value, caching and returning error)
F0430 16:34:01.359543       1 vtgate.go:157] gateway.WaitForTablets failed: deadline exceeded: /vitess/tst006/global/cells/xxxx4a1/CellInfo
```

**Comment by deepthi** [comment]
Fixed by #8011
