### ISSUE TITLE
Cannot run onlineddl migrations with Vitess and pt-osc on AWS Aurora

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8039]
If you use Vitess against an external tablet that is an AWS Aurora instance, and you try to use onlineddl (e.g. `vtctlclient ... ApplySchema -ddl_strategy "pt-osc ....."`), you will get the following error in the `message` field of the `show vitess_migrations\G` output:

```
Error creating pt-online-schema-change user: Access denied for user 'vt_dba'@'%' (using password: YES) (errno 1045) (sqlstate 28000) during query: GRANT SUPER, REPLICATION SLAVE ON *.* TO 'vt-online-ddl-internal'@'%'"
```

This is unsurprising, since Aurora does not provide `SUPER` privs.

**Comment by aquarapid** [comment]
#8038 should fix this.

**Comment by aquarapid** [comment]
Of course, the usual `pt-osc` requirements on Aurora still apply, e.g. you need to set the MySQL parameter `log_bin_trust_function_creators` to `1` via a parameter group.

**Comment by hallaroo** [comment]
#8038 is merged
