### ISSUE TITLE
PRS will fail if both VReplication schema tracking and semi-sync are enabled

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#8078]
#### Overview of the Issue
During reparent operations the tabletserver is shut down and restarted.
When the tabletserver is restarted for a PRIMARY tablet, it goes through a flow where it attempts to create the `_vt` database followed by creating the `schema_version` table. This will hang because there are no replicas that can send a semi-sync ACK yet.
The code path is:
```
serveMaster -> sm.tracker.Open() -> tracker.process -> possiblyInsertInitialSchema -> CREATE DATABASE
```
#### Reproduction Steps
Using the local example, change vttablet-up.sh and set `-track_schema_versions`.
Run PlannedReparentShard to change the primary from `zone1-100` to `zone1-101`. PRS will timeout after 30 seconds with a `Deadline exceeded` message.

#### Binary version
Version: 11.0.0-SNAPSHOT (Git revision 01148a0ecb branch 'master')

#### Operating system and Environment details
Ubuntu 18.04

**Comment by mattlord** [comment]
@deepthi I'm going to close this for now as I'm not aware of any related work to do in v18+. If I'm missing something please let me know and we can re-open this. Thanks!
