### ISSUE TITLE
Default transaction_mode shows UNSPECIFIED but documentation says MULTI

### ISSUE THREAD

**Issue by bolt-leandro** [vitessio/vitess#8150]
#### Overview of the Issue

The docs say default is **MULTI**:

> The atomicity policy is controlled by the transaction_mode flag. The default value is multi, and will set it in multi-database mode.
[https://vitess.io/docs/reference/features/two-phase-commit/#configuring-vtgate
](https://vitess.io/docs/reference/features/two-phase-commit/#configuring-vtgate
)

But when I start up cluster and check, it says **UNSPECIFIED**. This mode is not documented and doesn't correspond to what docs state.

It would be nice either to fix vtgate default to **MULTI** or to update the documentation with description of **UNSPECIFIED**. 

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy [local example](https://vitess.io/docs/get-started/local/) until you have sharded customer keyspace (eg: until step 307_delete_shard_0.sh)

2. Connect to vtgate and check default _transaction_mode_
```
mysql> select @@transaction_mode;
+--------------------+
| @@transaction_mode |
+--------------------+
| UNSPECIFIED        |
+--------------------+
1 row in set (0.00 sec)

mysql> set transaction_mode='multi';
Query OK, 0 rows affected (0.00 sec)

mysql> select @@transaction_mode;
+--------------------+
| @@transaction_mode |
+--------------------+
| MULTI              |
+--------------------+
1 row in set (0.00 sec)
```

#### Binary version
```sh
vagrant@ubuntu-bionic:~/vitess-9.0.0-daa6085/examples/local$ vtgate --version
Version: daa6085 (Git branch 'HEAD') built on Tue Jan 26 09:37:50 UTC 2021 by runner@fv-az195-520 using go1.15.7 linux/amd64
```

#### Operating system and Environment details

- Operating system (output of `cat /etc/os-release`):
```
vagrant@ubuntu-bionic:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel version (output of `uname -sr`):
```
vagrant@ubuntu-bionic:~$ uname -sr
Linux 4.15.0-143-generic
```
- Architecture (output of `uname -m`):
```
vagrant@ubuntu-bionic:~$ uname -m
x86_64
```
#### Log Fragments
Not much it seems:
```
vagrant@ubuntu-bionic:~/vitess-9.0.0-daa6085/examples/local/vtdataroot$ grep -i transaction_mode tmp/*
tmp/vtgate_querylog.txt:Execute	127.0.0.1:40840	vagrant	'userData1'	'vagrant'	2021-05-19 15:40:52.061379	2021-05-19 15:40:52.061488	0.000109	0.000101	0.000007	0.000000	SELECT	"select :__vttransaction_mode as `@@transaction_mode` from dual"	map[__vttransaction_mode:type:VARBINARY value:"UNSPECIFIED" ]	0	1	""	""	""	"MASTER"
tmp/vtgate_querylog.txt:Execute	127.0.0.1:40840	vagrant	'userData1'	'vagrant'	2021-05-19 15:53:56.251677	2021-05-19 15:53:56.251826	0.000149	0.000138	0.000009	0.000000	SET	"set session transaction_mode = 'multi'"	map[]	0	0	""	""	""	"MASTER"
tmp/vtgate_querylog.txt:Execute	127.0.0.1:40840	vagrant	'userData1'	'vagrant'	2021-05-19 15:53:57.730034	2021-05-19 15:53:57.730234	0.000200	0.000186	0.000012	0.000000	SELECT	"select :__vttransaction_mode as `@@transaction_mode` from dual"	map[__vttransaction_mode:type:VARBINARY value:"MULTI" ]	0	1	""	""	""	"MASTER"
```

**Comment by PaarthAgarwal** [comment]
> It would be nice either to fix vtgate default to **MULTI** or to update the documentation with description of UNSPECIFIED.

Which one of these approaches would you prefer?

**Comment by hyhuang1218** [comment]
It looks like the initial value of `@@transaction_mode` is always UNSPECIFIED no matter what is the actual transaction_mode.

In our case, we create vttestserver with option `--transaction_mode=SINGLE`. It works as expected, but `@@transaction_mode` is still `UNSPECIFIED`:
```

mysql> insert into tags (label, tenant_key, created_at, updated_at) values ('1', '1', '2023-01-01', '2023-01-01'),('2', '2', '2023-01-01', '2023-01-01'),('4', '4', '2023-01-01', '2023-01-01'),('3', '3', '2023-01-01', '2023-01-01'),('11', '11', '2023-01-01', '2023-01-01'),('22', '22', '2023-01-01', '2023-01-01');
ERROR 1317 (70100): multi-db transaction attempted: [target:{keyspace:"test-app-shops" shard:"a0-c0" tablet_type:PRIMARY} transaction_id:1685643362920476910 tablet_alias:{cell:"test" uid:16} target:{keyspace:"test-app-shops" shard:"c0-e0" tablet_type:PRIMARY} transaction_id:1685643363059536837 tablet_alias:{cell:"test" uid:19} target:{keyspace:"test-app-shops" shard:"40-60" tablet_type:PRIMARY} transaction_id:1685643362577274206 tablet_alias:{cell:"test" uid:7} target:{keyspace:"test-app-shops" shard:"80-a0" tablet_type:PRIMA
mysql> select @@transaction_mode;
+--------------------+
| @@transaction_mode |
+--------------------+
| UNSPECIFIED        |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by austenLacy** [comment]
I think where this is confusing is that `UNSPECIFIED` is returned in relation to the current session and [if `UNSPECIFIED` then Vitess uses the value provided via the `--transaction_mode` vtgate flag](https://github.com/vitessio/vitess/blob/main/go/vt/proto/vtgate/vtgate.pb.go#L49-L50) as evidenced by @hyhuang1218's comment above.

I think the simplest fix would be for documentation to be updated to mention that `UNSPECIFIED` will use the value of `transaction_mode` which does appropriately [default to `MULTI`](https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/vtgate.go#L59).

**Comment by Its-Maniaco** [comment]
@austenLacy 
I tried framing it like this: The atomicity policy is controlled by the transaction_mode flag. If not specified, the default value is `UNSPECIFIED`, which itself defaults to `MULTI`.
