### ISSUE TITLE
build fails on AArch64, Fedora 33, master + v9.0.1 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [vitessio/vitess#8168]
[jw@cn05 master]$ sudo make VERBOSE=1 -j$(nproc) build
Fri May 21 14:19:06 CEST 2021: Building source tree
go: downloading google.golang.org/grpc v1.37.0
go: downloading github.com/dave/jennifer v1.4.1
go: downloading google.golang.org/api v0.45.0
go: downloading google.golang.org/genproto v0.0.0-20210413151531-c14fb6ef47c3
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/jmoiron/sqlx v1.2.0
go: downloading golang.org/x/oauth2 v0.0.0-20210413134643-5e61552d6c78
go: downloading github.com/go-sql-driver/mysql v1.5.1-0.20210202043019-fe2230a8b20c
go: downloading golang.org/x/sys v0.0.0-20210412220455-f1c623a9e750
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/AdaLogics/go-fuzz-headers v0.0.0-20210330150358-dbd898e17899
go: downloading github.com/prometheus/client_golang v1.5.1
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/planetscale/tengo v0.9.6-ps.v3
go: downloading github.com/nozzle/throttler v0.0.0-20180817012639-2ea982251481
go: downloading github.com/VividCortex/mysqlerr v0.0.0-20170204212430-6c6b55f8796f
Error: unable to open executable file: open /data/jw/vitess/master/bin/vttablet: no such file or directory
exit status 1
[jw@cn05 master]$

**Comment by askdba** [comment]
@LutzWeischerFujitsu have you tried this with the latest build in `main`? There was a fix for a couple of go modules.
