### ISSUE TITLE
Watch all namespaces

### ISSUE THREAD

**Issue by millaguie** [vitessio/vitess#8172]
Currently, the environment variable WATCH_NAMESPACE sets the namespace where the operator watches for new clusters, but if we want to deploy Vitess clusters in any namespace is not possible.

The current workaround for this is to deploy the operator in every namespace (because the comma-separated syntaxis for WATCH_NAMESPACE is not working neither)

#### Feature Description

Allow using the default operator-sdk behaviour of working cluster wide, by not setting WATCH_NAMESPACE environment variable.  Because an operator should be cluster-wide scoped not namespace-scoped.

#### Use Case(s)

Running a single copy of the operator in the cluster be able to deploy multiple Vitess clusters in different namespaces.

**Comment by deepthi** [comment]
Can you please open this issue in https://github.com/planetscale/vitess-operator instead?
