### ISSUE TITLE
Unable to get next value from sequence

### ISSUE THREAD

**Issue by saikrishna4d8** [vitessio/vitess#8235]
Hi,
I  created a vitess sequence and tried to query the next value. but I am facing error as  Error Code: 0 Server sent unknown charsetnr (0).

#### Reproduction Steps
I creeated the table as 
CREATE TABLE `application_seq` (
   `id` int NOT NULL,
   `next_id` bigint DEFAULT NULL,
   `cache` bigint DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='vitess_sequence';
, given the vschema as 

{
  "sharded": false,
  "tables": {
	"application_seq": {
        "type": "sequence"
    }
  }
}
, then I inserted the first record into the table as 
insert into application_seq(id, next_id, cache) values(0, 1000, 100);
and then i executed the below query to get the next value as
select next value from application_seq;
I am getting the below error as a result of executing above query.
**Error Code: 0 Server sent unknown charsetnr (0)**

#### Binary version: Version: 7e09d0c20 (Git branch 'heads/v8.0.0') built on Tue Oct 27 14:35:28 UTC 2020 by vitess@00939aa4be4b using go1.13.15 linux/amd64

- Operating system (output of `cat /etc/os-release`):PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel version (output of `uname -sr`): Linux 4.9.0-11-amd64
- Architecture (output of `uname -m`): x86_64

**Comment by oops-lgtm** [comment]
more easy to read
```sql
CREATE TABLE `application_seq` (
  `id` int NOT NULL,
  `next_id` bigint DEFAULT NULL,
  `cache` bigint DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='vitess_sequence';
```

```json
{
  "sharded":false,
  "tables":{
    "application_seq":{
      "type":"sequence"
    }
  }
}
```

`insert into application_seq(id, next_id, cache) values(0, 1000, 100);`

`select next value from application_seq;`

**Comment by aquarapid** [comment]
I cannot reproduce this in newer Vitess version.  Can you retry with a newer version?

**Comment by deepthi** [comment]
maybe relevant: https://stackoverflow.com/questions/51051440/server-sent-charset-255-unknown-to-the-client-set-mysql-charset-to-utf8-w-o
This looks like a MySQL server config issue. Let's give the OP time to respond and then close if we can get that confirmed.

**Comment by saikrishna4d8** [comment]
Yes, modifying the charset helped me to resolve this. thank you
