### ISSUE TITLE
vtctld should sanitize HTTP requests before logging to avoid logging sensitive headers

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#8277]
#### Overview of the Issue

It looks like the vtctld's long polling implementation logs HTTP requests without sanitizing headers. As a result, sensitive information like cookies can turn up in the logs.

Here's a specific example of this: https://github.com/vitessio/vitess/blob/c9b6d60/go/vt/workflow/long_polling.go#L160-L164

```go
func httpErrorf(w http.ResponseWriter, r *http.Request, format string, args ...interface{}) {
	errMsg := fmt.Sprintf(format, args...)
	log.Errorf("HTTP error on %v: %v, request: %#v", r.URL.Path, errMsg, r)
	http.Error(w, errMsg, http.StatusInternalServerError)
}
```

This is the only instance we've seen, but it'd be worth it to do a quick audit to see if there are any other places this should be patched.

A straightforward approach is to log all header keys, but omit the values for the "known sensitive" headers (`Authorization`, `Cookie`). For flexibility, we could consider adding a build flag to disable this behaviour (but I'm not sure if this is necessary...?)

**Comment by doeg** [comment]
Here's a very nice + succinct fix proposed by our very own @setassociative ❤️ 

```
rbailey@localhost $ git diff -- go/vt/workflow/long_polling.go
diff --git a/go/vt/workflow/long_polling.go b/go/vt/workflow/long_polling.go
index 3e804a8ff..294396121 100644
--- a/go/vt/workflow/long_polling.go
+++ b/go/vt/workflow/long_polling.go
@@ -157,9 +157,14 @@ func getID(url, base string) (int, error) {
        return i, nil
 }
+func sanitizeRequestForLogging(r *http.Request) *http.Request {
+       return http.NewRequest(r.Method, r.URL, nil)
+}
+
 func httpErrorf(w http.ResponseWriter, r *http.Request, format string, args ...interface{}) {
        errMsg := fmt.Sprintf(format, args...)
-       log.Errorf("HTTP error on %v: %v, request: %#v", r.URL.Path, errMsg, r)
+
+       log.Errorf("HTTP error on %v: %v, request: %#v", r.URL.Path, errMsg, sanitizeRequestForLogging(r))
        http.Error(w, errMsg, http.StatusInternalServerError)
 }
 ```
 
 I can open up a PR for this later on this week.

**Comment by setassociative** [comment]
It occurs to me that `sanitizeRequestForLogging` is technically only accurate if

- we never print the raw URL object extracted from the request
- the URL path doesn't contain sensitive info

example https://play.golang.org/p/mS-9XkeHoVN

**Comment by doeg** [comment]
@setassociative since our internal concern is specifically around logging the `Cookie` header, I'm pretty happy to leave concerns around the URL as a future enhancement... 😎

**Comment by doeg** [comment]
I'm going to start on this shortly. Two things I'd love to run by y'all (especially @deepthi, @ajm188) up front:

**Question 1:** Where should this function go? I was thinking of adding a new `request_logger.go` file in [go/vt/logutil/](https://github.com/vitessio/vitess/blob/main/go/vt/logutil/), but that's just a guess.

**Question 2:** per @setassociative's note above, I'd like to leave ["sensitive information in the URL"](https://github.com/vitessio/vitess/issues/8277#issuecomment-856062044) as a separate/future enhancement. To my knowledge, cookies are the specific concern behind this ticket. Does that sound okay? 

**Question 3:** Does anyone have strong opinions on how to configure flags for this? 

For some context, @ajm188 shared a snippet that seems a lil more flexible than the `http.NewRequest` approach, in that one could in theory allow indivdiual headers to be included/omitted: https://play.golang.org/p/pNoiRyxMkp0 This is likely the approach I'll take:

```go
package main

import (
	"fmt"
	"net/http"
)

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	r, err := http.NewRequest("GET", "https://google.com", nil)
	must(err)
	
	r.AddCookie(&http.Cookie{
		Name: "secret1",
		Value: "value1",
	})
	r.AddCookie(&http.Cookie{
		Name: "secret2",
		Value: "value2",
	})
	
	
	fmt.Printf("%#v\n", r)
	
	cookies := r.Cookies()
	r.Header.Del("Cookie")
	
	fmt.Printf("%#v\n", r)
	
	for _, cookie := range cookies {
		cookie.Value = "********"
		
		r.AddCookie(cookie)
	}
	
	fmt.Printf("%#v\n", r)
}
```

Concerning flags, I can think of a couple of ways to do it. Flag name suggestions welcome, haha.

1. Redact values for sensitive headers ("Cookie", "Authorization") by default. Add a single flag, `-log-all-request-headers`, to override this and log all header values, including sensitive ones. 
2. Add flags to redact individual headers: `-log-request-redact-header Cookie - log-request-redact-header Authorization`. The downside of this is that logging "fails open", as it were, without those flags. 

I am somewhat biased to the first option, since it seems like a reasonable default to me, but the second one is definitely more flexible. What do you think?

**Comment by setassociative** [comment]
I'm going to be a feature creep here -- if we're going to deny-list specific headers it'd be _magic_ if we could piggyback on whatever infrastructure there is in place to support live-edited vars so that if we need to add new exclusions in the future it doesn't require a roll of the fleet.

Nice to have.
