### ISSUE TITLE
flaky vreplication_basic test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#8318]
Happened on CI 

   --- FAIL: TestBasicVreplicationWorkflow/materializeMerchantOrders (0.03s)
        --- FAIL: TestBasicVreplicationWorkflow/materializeMerchantOrders/materialize (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x170 pc=0xda5588]

goroutine 306 [running]:
testing.tRunner.func1.1(0x11bcfe0, 0x1dd13f0)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc0006cc900)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:1075 +0x41a
panic(0x11bcfe0, 0x1dd13f0)
	/opt/hostedtoolcache/go/1.15.13/x64/src/runtime/panic.go:969 +0x1b9
vitess.io/vitess/go/test/endtoend/cluster.(*VttabletProcess).QueryTablet(0x0, 0xc0003476c0, 0x1c, 0x1354bdd, 0x8, 0xc000347601, 0x0, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vttablet_process.go:322 +0x88
vitess.io/vitess/go/test/endtoend/vreplication.validateCountInTablet(0xc0006cc900, 0x0, 0x1354bdd, 0x8, 0x13532be, 0x7, 0x2)
	/home/runner/work/vitess/vitess/go/test/endtoend/vreplication/helper.go:86 +0xe9
vitess.io/vitess/go/test/endtoend/vreplication.materializeMerchantOrders.func1(0xc0006cc900)
	/home/runner/work/vitess/vitess/go/test/endtoend/vreplication/vreplication_test.go:765 +0x216
testing.tRunner(0xc0006cc900, 0x13c5ed8)
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.15.13/x64/src/testing/testing.go:1168 +0x2b3
FAIL	vitess.io/vitess/go/test/endtoend/vreplication	361.380s

**Comment by rohit-nayak-ps** [comment]
The line it is panicking  is 
```
	dbParams := NewConnParams(vttablet.DbPort, vttablet.DbPassword, path.Join(vttablet.Directory, "mysql.sock"), keyspace)
```

This means that the receiver `vttablet` is null, which is strange. Possibly there is a previous error in the run which is causing the vttablet process to shutdown? 

I have noticed this test fail earlier due to the CI running slowly and the test timing out prematurely.

**Comment by mattlord** [comment]
I'm closing this as fixed for now as it's become stale and I think we've addressed it in the last year. Thanks!
