### ISSUE TITLE
`analyze-pr-labels` check should not run on merge commits

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#8324]
#### Feature Description

`analyze-pr-labels` check should not run on merge commits.

#### Use Case(s)

Since there's no associated PR with the commit that merges a branch into `main`, this check never passes, and all of our merge commits have had at least one failing check (this one).

**Comment by systay** [comment]
ping @shlomi-noach

**Comment by shlomi-noach** [comment]
please see https://github.com/vitessio/vitess/pull/8327
