### ISSUE TITLE
Flaky test: onlineddl_vrepl_suite_test.go

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#8351]
`onlineddl_vrepl_suite_test.go` keeps failing on unrelated PRs. 

Two examples:
https://github.com/vitessio/vitess/pull/8312/checks?check_run_id=2855474705
https://github.com/vitessio/vitess/pull/8325/checks?check_run_id=2855475377

Saved a log output:
https://gist.github.com/systay/35275ed8337a8c7a2e9dbc4cbd8c3053

**Comment by shlomi-noach** [comment]
For immediate relief I made the `vrepl_suite` test non-`required`. Looking into.

**Comment by shlomi-noach** [comment]
The failing test is `update-pk`, added in https://github.com/vitessio/vitess/pull/8345

**Comment by shlomi-noach** [comment]
Hmmm, _also_, and unrelated, there's a `10m` timeout.

**Comment by shlomi-noach** [comment]
Fixedin https://github.com/vitessio/vitess/pull/8355
