### ISSUE TITLE
VStream should be aware of reparent event

### ISSUE THREAD

**Issue by sonne5** [vitessio/vitess#8426]
#### Feature Description
The [doc](https://vitess.io/docs/reference/vreplication/vreplication/#failover-continuation) mentions that 
> If a failover is performed on the target keyspace/shard, the new master will automatically resume VReplication from where the previous master left off.

What it means if the old primary tablet crashed and trigger the failover, vstream will automatically create a new stream from the new primary. However, if the old primary does not crash and the primary tablet changed (e.g., external reparent for maintenance purpose), vtgate will continue streaming from the old node. 

This is not ideal since if we start vstream with `"tablet_type":"MASTER"`, we will tail from a replica node silently. Although the replica should still have the same binlog, but it violates the api that created the vstream.

A few ideas to address this: 
- we can have vttablet periodically checks the tablet type with the requested one - the tablet can return error on the vstream endpoint if there is a type mismatch.
- or we can integrate vstream with the healthcheck component at vtgate so that we can migrate streams for a primary failover.

Both approaches can be extended to take the "healthiness" of the tablet into account: if the mysql replication stops but tablet server is still running, we can trigger the same code to migrate the stream. Note that given it is easy to detect a replica is unhealthy, this can be addressed separately.

I'm not sure what might be the easiest solution here, if this is already something under your radar and have a fix - that would be great!

#### Use Case(s)
See description above, this should apply to all the use cases for vstream / vreplication

**Comment by rohit-nayak-ps** [comment]
I think we should use the healthcheck mechanism within the vtgate vstreams, which should identify both the change in tablet type and if the tablet becomes unhealthy. Let me discuss internally and see how easy it is to incorporate it.

**Comment by narcsfz** [comment]
@rohit-nayak-ps is there any update? I think this issue also leads to issues with schema tracking: a primary get reparented to a replica, then the schema tracking won't work because the tracker cannot do the write anymore.

**Comment by indera-shsp** [comment]
it looks like this issue is resolved by https://github.com/vitessio/vitess/pull/8445

**Comment by rohit-nayak-ps** [comment]
Closed via #8445
