### ISSUE TITLE
Querylogging results in much higher memory usage than without for vttablet and vtgate

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8447]
**Scenario 1:**
  * Running recent-ish main branch e018d0fd94dadd82fa0b7b377571c1ee8afe6bb9, compiled with `go1.16.3` (`linux/amd64`)
  * Unsharded database, single vtgate and two vttablets
  * querylogging to file is disabled on both vtgate and vttablet (i.e. no `-log_queries_to_file` option)
  * Create the cluster from scratch, then load a large-ish (~400 MB) dump file in multiple threads (I used 16 threads, but 4 threads also shows the problem to a slightly lesser degree).  Each insert in the dump file is a multivalued insert with around 2 MB of SQL to insert around 2500 rows.
  * Nothing special about the table being inserted to, it's an OLTP sysbench schema, e.g.:
  ```
CREATE TABLE `sbtest1` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `k` int unsigned NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB;
```
  * Observe the memory usage of vtgate and vttablet in top (or your favorite tool)

**Result 1:**
  * Baseline, the resident set size (RSS) of vttablet will peak around 1.2 GB and vtgate around 1.1 GB.

**Scenario 2:**
  * Repeat scenario 1 (after recreating the cluster from scratch);  but this time have a `curl` running to redirect query logs from the vttablet to a file via:
  ```
curl http://localhost:15100/debug/querylog > /var/tmp/foo
  ```

**Result 2:**
  * Memory usage (RSS) for vttablet will peak at 4.1 GB

**Observations:**
  * Similar behavior to scenario 2 is seen if vttablet is configured to output query logs to a file (via `-log_queries_to_file`)
  * vtgate shows similar behavior whether redirecting querylogs via the web port (as above) or via `-log_queries_to_file`
  * A quick vttablet heapdump during the run does not immediately reveal where the memory is going.
  * The issue here is that in a system where memory is bounded (e.g. container/k8s);  this behavior may result in unexpected/unwanted OOMs, just by enabling logged (e.g. for debugging).

**Comment by GuptaManan100** [comment]
Me and @harshit-gangal were not able to replicate the issue on `main`. We tried using sysbench with 2MB queries but the vtgate memory usage peaked at about `600MB` and vttablet peaked at about `1.4GB`. The heap profile showed that `LogToFile` was only using `2MB` data with `-log_queries_to_file ` flag.

**Comment by aquarapid** [comment]
Ah, I found the issue.  I had a stray `GOGC=2500` environment variable in my setup;  which (of course) causes GC to be super-delayed;  explaining the behavior.  If I reset to `GOGC=100` (the default), all is well.

Sorry for the noise.
