### ISSUE TITLE
CI Failures: MariaDB 10.1 does not exist anymore

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#8449]
Our unit/`mariadb101` build is failing:

- Images from DO for MariaDB 10.1 do not exist anymore: http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/ubuntu
- Per MariaDB, `10.1` was EOL `17 Oct 2020`: https://mariadb.org/about/#maintenance-policy

Should we remove `10.1` from Vitess builds?

**Comment by deepthi** [comment]
Fixed by #8446 
Is there any reason this issue needs to stay open? maybe we need to make the same change on release branches?

**Comment by shlomi-noach** [comment]
The issue can be safely closed to the best of m understanding
