### ISSUE TITLE
Bug Report: Duplicate column name 'migration_context'

### ISSUE THREAD

**Issue by jmoldow** [vitessio/vitess#8469]
#### Overview of the Issue

I brought up a new, completely empty demo cluster, didn't do anything with it besides let it initialize for the first time, and I got this replication breaking event on one of the shards:

`"Error 'Duplicate column name 'migration_context'' on query. Default database: 'vt_foobar'. Query: 'ALTER TABLE _vt.schema_migrations add column migration_context varchar(1024) NOT NULL DEFAULT '''"`

Don't know if this is a schema management problem, or if vtorc allowed a split brain to occur at startup, or something else.

#### Reproduction Steps

Unknown. I had just brought up a new demo cluster via vitess-operator.

The setup is similar but not precisely identical to https://github.com/jmoldow/vitess-operator-examples/blob/master/examples/operator/vtorc_example.yaml

#### Binary version

Running vitess-operator on commit 1aef31a78a616069f7fb31d9aefd5e396de474a7 , and a 11.0.0-SNAPSHOT build of Vitess (commit 46406453b490c2a21351db3b7f0a336cb453481e ).

#### Operating system and Environment details

```
Linux 5.10.25-linuxkit
x86_64

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

#### Log Fragments

LMK if you're interested in this, and if so, what logs/configs you would want me to gather before I recycle the cluster.

<img width="654" alt="Screen Shot 2021-07-13 at 11 48 58 PM" src="https://user-images.githubusercontent.com/1150978/125577719-2a578b63-a66c-4fe6-8f87-173a0c5485e1.png">
<img width="781" alt="Screen Shot 2021-07-13 at 11 48 43 PM" src="https://user-images.githubusercontent.com/1150978/125577731-8f7ab66b-2a3a-496c-93b3-2150826d00fe.png">

**Comment by deepthi** [comment]
@shlomi-noach @rohit-nayak-ps do we think this is fixed by the schema init refactor?

**Comment by shlomi-noach** [comment]
> do we think this is fixed by the schema init refactor?

Yes. Or else we have OtherBigProblems.

**Comment by shlomi-noach** [comment]
This issue has unfortunately not been addressed when reported; I believe it to be irrelevant with today's logic. @jmoldow if you're still around to confirm/deny, please let me know.

**Comment by shlomi-noach** [comment]
I'm going to close this issue on the basis that Vitess 16 compeltely changes it's internal schema deployment, using declarative statements via `schemadiff`. This kind of error will never be an issue going forward.
