### ISSUE TITLE
VStream supports stream from head of the existing binlog

### ISSUE THREAD

**Issue by 5antelope** [vitessio/vitess#8488]
#### Feature Description
it looks like we only supports 3 kind of “position”:
1. Current
2. Specific gtid position
3. Entire table (vstream copy)

I think it would be useful to support start vstream from “begin” of the existing binlog. 

#### Use Case(s)

Vstream requires client to store checkpoint, when checkpoint is not available, start from the begin (earliest transaction) of binlog is a safe fallback.

**Comment by narcsfz** [comment]
cc @deepthi @rohit-nayak-ps in case there is an existing setup that I missed :-)

**Comment by sonne5** [comment]
cc @aquarapid for visibility since we chat about this briefly over slack

**Comment by mattlord** [comment]
I'm going to close this as done for now since you can do this today as a user and the use case is not clear to me. If I'm missing anything then please let me know and we can re-open this with some additional details. Thanks!
