### ISSUE TITLE
vitess 11.0.0 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [vitessio/vitess#8554]
👋 trying to build the latest release, but run into some regression test issue.

And here is my `vgate` command (with etcd started with `localhost:8882`):

```
vtgate   -topo_implementation   etcd2 \
-topo_global_server_address  localhost:8882 \
-topo_global_root  ./global \
-tablet_types_to_wait   MASTER,REPLICA \
-cells_to_watch   test \
-port  8883
```

And I am running into this vgate startup failure

```
F0727 17:47:20.696553   23379 vtgate.go:144] cells_to_watch validation failed: node doesn't exist: /private/tmp/vitess-test-20210727-23369-19uul3e/global/cells/
```

relates to Homebrew/homebrew-core#81984

**Comment by askdba** [comment]
Hi @chenrui333 👋🏽  , are you still having the issue? 
Can you give me more details on how is your build environment setup so I can try it? 
Please send reproductions steps if possible.

**Comment by chenrui333** [comment]
yeah, this is still an issue. What I did is basically `brew install` from the resource and I did run vtgate command locally. Does that make sense?

**Comment by deepthi** [comment]
We used to not validate the value provided to `cells_to_watch` flag. Now we validate that is in fact a valid "cell".
Before starting vtgate, a directory like `/vitess/test` needs to be created on etcd, and the `AddCellInfo` command has to also be invoked.
Example of this is at https://github.com/vitessio/vitess/blob/a0e0aa8c8f41be8e97e92f1afdae974b8e2bd427/examples/local/scripts/etcd-up.sh#L35

**Comment by mattlord** [comment]
Trying to address this here: https://github.com/Homebrew/homebrew-core/pull/88725

**Comment by mattlord** [comment]
I'm closing this as fixed via https://github.com/Homebrew/homebrew-core/pull/88725 for now. If I missed something please let me know and we can re-open it. Thanks!
