### ISSUE TITLE
VStream schema tracking should include shard info

### ISSUE THREAD

**Issue by sonne5** [vitessio/vitess#8579]
#### Overview of the Issue
When vtgate manages VStream's FIELD_EVENTS, it adds keyspace into the table name: https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/vstream_manager.go#L497

However, this does not disambiguate various shards within the same keyspace. 

Imagine the following situation:
t1: schema migration happened on shard_1
t2: vtgate gets the new schema for the shard
t3: schema migration happned on shard_2

Any events from `shard_2` that arrives between t2 and t3 needs to use the old schema. However, with current implementation, client needs to look into the vgtid -> shard_gtids[0] -> shard in order to do per shard schema cache.

Instead, I think we could carry over the shard info together with the keyspace info at `vstream_manager` and make the table name:
```
ks/shard.table_name
```

**Comment by deepthi** [comment]
@rohit-nayak-ps WDYT?

**Comment by sonne5** [comment]
I might miss something and be completely wrong, but it feels knowing the schema / table_plan for a keyspace is not useful, vstream clients would need to track vstream at shard level in order to do things correctly. Or is there some gotcha I missed?

**Comment by rohit-nayak-ps** [comment]
Your point is valid. Maybe we need to add `Keyspace` and `Shard` as additional attributes for a `FieldEvent`.  

Adding the shard to the prefix is probably breaking the database.tablename abstraction and will break backward compatibility. Sending one field event per row event adds a huge overhead.

Let me discuss this internally and get back to you later this week.

**Comment by sonne5** [comment]
thanks @rohit-nayak-ps, I think if we add `Keyspace` and `Shard` as additional attributes for `FieldEvent`, might be useful to add them into `RowEvent` as wll
