### ISSUE TITLE
Support plan for `AVG` for scatter queries in Gen4 

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#8582]
#### Overview of the Issue

The following query returns incorrect result - 
```sql
SELECT AVG(book6s.price) FROM book6s
```

The plan created from Gen4 is as follows -
```json
{
  "QueryType": "SELECT",
  "Original": "select AVG(user.intcol) from user",
  "Instructions": {
    "OperatorType": "Aggregate",
    "Variant": "Ordered",
    "Aggregates": "count(0)",
    "Inputs": [
      {
        "OperatorType": "Route",
        "Variant": "SelectScatter",
        "Keyspace": {
          "Name": "user",
          "Sharded": true
        },
        "FieldQuery": "select AVG(`user`.intcol) from `user` where 1 != 1",
        "Query": "select AVG(`user`.intcol) from `user`",
        "Table": "`user`"
      }
    ]
  }
}
```

The plan is incorrect since we are running an `AVG` in SelectScatter. For an AVG query, we have to get all the rows from the shards and take the average on vtgate.

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Copy the query to `onecase.txt`
2. Run the test `TestOneCase`

#### Binary version
- main

**Comment by harshit-gangal** [comment]
It does not add support for it. But it blocks from producing wrong plans.

https://github.com/vitessio/vitess/pull/8593

**Comment by harshit-gangal** [comment]
PR: https://github.com/vitessio/vitess/pull/14419
