### ISSUE TITLE
VDiff improvements

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8584]
Scenario:
  * VDiff across large workflows (e.g. after MoveTables or Reshard)
  * During this process, Vitess runs consistent snapshot SELECTs against the source tablet(s), which has a potentially significant performance impact on the source tablet (growing history length, i.e. undo records in MySQL).
  * Because of this, it is recommended to have RDONLY tablets for all shards, and use these for VDiff.  The assumption is that the performance impact would be less of an issue for RDONLY tablets.

However, this does not completely address the issue;  especially because not all users want/need to run RDONLY tablets.  Also, some users have started to use group replication with Vitess, and there the performance of a replica is tightly bound to write performance, and you may want to avoid long-running consistent snapshots against replica tablets as well.

There are a few possibilities here:
  * Reduce the length of time for each consistent snapshot during VDiff, potentially pausing between them to allow the history length to drop.
  * Introduce/use VDIff throttling related to the size of the history length on the source tablet(s)
  * Introduce a new VDiff mechanism that uses variable chunking and checksums (potentially persistent) on the source and target tablets to compare tables;  i.e. in a similar fashion to `pt-table-checksum`.

**Comment by aquarapid** [comment]
Note that there is now the option:

```
-vreplication_copy_phase_duration duration
```

(defaults to 1 hour).

Reducing this could help with the first part.

**Comment by mattlord** [comment]
I'm going to close this for now as we now support max diff duration and throttling the vdiff would only cause the problem to become worse (history list growing longer e.g.). A new mechanisms using checksums would be an entirely new feature. 

We can instead create new issues for any specific problem / proposal in v21+.
