### ISSUE TITLE
vtorc CGO: glibc version

### ISSUE THREAD

**Issue by vczyh** [vitessio/vitess#8599]
## Error

Centos 7 GLIBC version lower

start vtorc failed, error message below:

```
vtorc: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by vtorc)
```

## System Infomation

```shell
$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

```shell
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by vczyh** [comment]
How to slove it if i continue to use Centos7?

**Comment by GuptaManan100** [comment]
This does not seem to be a vtorc issue. Could you take a look at this https://access.redhat.com/discussions/3244811

**Comment by vczyh** [comment]
> This does not seem to be a vtorc issue. Could you take a look at this https://access.redhat.com/discussions/3244811

YES, I have solved it, by compiling vtorc on centos7
