### ISSUE TITLE
Collation and Character set support

### ISSUE THREAD

**Issue by GuptaManan100** [vitessio/vitess#8606]
## Feature Description

Vitess does not yet have support for collations and character-sets. So, to compare varchar strings Vitess needs to rely on [WEIGHT_STRING](https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_weight-string) function for now. As per MySQL documentation, WEIGHT_STRING is a debugging function, meant only for internal use. We can move away from this implementation after we have collation and character-set support in Vitess

## Use Case(s)
- Having the ability to compare strings using collation and character set support we will be able to better implement ORDER BY, GROUP BY, JOIN.
- It will also allow us to leverage more advanced join techniques than what we currently implement.

**Comment by king-11** [comment]
Hey, @GuptaManan100 I would like to apply for this project under LFX. I am not much familiar with Vitess as of now can you point me somewhere I can look at current implementation so that I can design the changes that need to be made. Thanks 😄

**Comment by GuptaManan100** [comment]
Hello, @king-11 https://github.com/vitessio/vitess/tree/main/go/vt/vtgate/planbuilder is the package which has the code for building the plans of how queries are to be executed in Vitess. You can look at this https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/testdata/aggr_cases.txt file which contains the test data for aggregation queries. You will find weight_string function added to a lot of those. You can run the tests locally from https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/plan_test.go file.

**Comment by rgrupesh** [comment]
Hello @GuptaManan100 

I went through the issue and I feel like I can accomplish this task. I am working on my cover letter, will submit that along with my resume through LFX portal.

Is there else that I should know of?

**Comment by rgrupesh** [comment]
> Hello, @king-11 https://github.com/vitessio/vitess/tree/main/go/vt/vtgate/planbuilder is the package which has the code for building the plans of how queries are to be executed in Vitess. You can look at this https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/testdata/aggr_cases.txt file which contains the test data for aggregation queries. You will find weight_string function added to a lot of those. You can run the tests locally from https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/planbuilder/plan_test.go file.

Thank you for the links. This was helpful.

**Comment by GuptaManan100** [comment]
@rgrupesh There is no other explicit requirement. The mentor for this project is going to be @vmg.

**Comment by rgrupesh** [comment]
> @rgrupesh There is no other explicit requirement. The mentor for this project is going to be @vmg.

Thanks again @GuptaManan100 !

**Comment by vmg** [comment]
For anybody else who is interested on applying for this task: the actual integration into Vitess is not that important, I will assist you with it once you've implemented the collation code.

The most important thing for your application is understanding what are Character Sets and Collations in MySQL, how do they work, and how they're implemented (i.e. https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html), then looking at the `x/text/collate` package from the Go maintainers (https://pkg.go.dev/golang.org/x/text/collate) and figuring out: how many of the existing MySQL collations are implemented in that package, how many behave exactly the same as in MySQL and how many will need to be implemented from scratch.

A strong application cover letter will give rough answers to all those questions (obviously they don't have to be fully correct/definitive -- I'm sure we'll find many nuances and bugs once we start integrating the collations into Vitess).

Thanks everyone and good luck with your applications!

**Comment by king-11** [comment]
Can we still submit the cover letter? I thought the deadline was 22nd and questions that needed to be answered were the mentioned ones only 😅

**Comment by vmg** [comment]
@king-11: ah, fair enough, the deadline went by while I was on holidays. The point still stands about what's important for the project, but don't worry if you've already submitted. :)

**Comment by king-11** [comment]
@vmg I have read about what, how they work and how they are implemented. So I was moving to the go collate package how can I compare their implementations vs MySQL for each collation can you help me out on that.

**Comment by vmg** [comment]
So, there are many ways to accomplish this. The first thing I'd try is implementing a [`WEIGHT_STRING`](https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_weight-string) function in Go on top of the `collate` package. It should take a string and a collation, and return a binary string like MySQL's implementation does. With this function in place, it should be trivial to start writing unit tests that compare the output of our collation package with the results that MySQL returns. Let me know if you run into any roadblocks attempting this.
