### ISSUE TITLE
Equivalents of #8373 were not merged

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8656]
As a result, `ExternalizeVindex` still does not rebuild SrvVSchema on release-9.0, release-10.0 , release-11.0 or main branches.

See #8374 #8375 #8376

**Comment by deepthi** [comment]
The fix does exist in release-9.0 and release-10.0.
Only release-11.0 and main are missing the relevant commit.
#8669 and #8670 have been created to address this.

**Comment by deepthi** [comment]
Forward-ported to 11.0 branch and main.
