### ISSUE TITLE
mysqld.go:645] mkdir /vt/vtdataroot/vt_2548885007: permission denied

### ISSUE THREAD

**Issue by samhuangszu** [vitessio/vitess#8657]
pod create from example/operator/101_initial_cluster.yaml

I0823 09:14:09.810767       1 mysqld.go:589] execCmd: /usr/sbin/mysqld /usr/sbin/mysqld [--version]
I0823 09:14:09.816126       1 mysqld.go:603] execCmd: /usr/sbin/mysqld output: /usr/sbin/mysqld  Ver 5.7.31 for Linux on x86_64 (MySQL Community Server (GPL))
I0823 09:14:09.816160       1 mysqld.go:171] Using flavor: mysql, version: {5 7 31}
I0823 09:14:09.816183       1 mysqld.go:642] mysqlctl.Init
I0823 09:14:09.816186       1 mysqld.go:624] mysqlctl.InitConfig
I0823 09:14:09.816191       1 mysqld.go:926] creating directory /vt/vtdataroot/vt_2548885007
E0823 09:14:09.816219       1 mysqld.go:627] mkdir /vt/vtdataroot/vt_2548885007: permission denied
E0823 09:14:09.816228       1 mysqld.go:645] mkdir /vt/vtdataroot/vt_2548885007: permission denied
E0823 09:14:09.816234       1 mysqlctld.go:87] failed to initialize mysql data dir and start mysqld: mkdir /vt/vtdataroot/vt_2548885007: permission denied

**Comment by askdba** [comment]
Hi @samhuangszu , are you trying this on gcloud? Have you checked this out https://vitess.io/blog/2020-11-09-vitess-operator-for-kubernetes/ ?
