### ISSUE TITLE
vtgate: panic in tabletHealthCheck

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#8687]
#### Overview of the Issue

This panicked today in prod. We've only seen it once, so I don't have any reason to believe it's widespread.

```
panic: assignment to entry in nil map

goroutine 263686 [running]:
vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).updateHealth(0xc00045c000, 0xc00153e870, 0xc0016c61e0, 0x101)
	/vt/src/vitess.io/vitess/go/vt/discovery/healthcheck.go:430 +0x17b
vitess.io/vitess/go/vt/discovery.(*tabletHealthCheck).processResponse(0xc000cc5320, 0xc00045c000, 0xc001933090, 0x1dd7d80, 0xc001933090)
	/vt/src/vitess.io/vitess/go/vt/discovery/tablet_health_check.go:203 +0x1e7
vitess.io/vitess/go/vt/discovery.(*tabletHealthCheck).checkConn.func3(0xc001933090, 0xc001933090, 0x0)
	/vt/src/vitess.io/vitess/go/vt/discovery/tablet_health_check.go:284 +0x8e
vitess.io/vitess/go/vt/vttablet/grpctabletconn.(*gRPCQueryClient).StreamHealth(0xc001457600, 0x20f2fc0, 0xc001457380, 0xc001925b30, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/grpctabletconn/conn.go:598 +0xfa
vitess.io/vitess/go/vt/discovery.(*tabletHealthCheck).stream(0xc000cc5320, 0x20f2fc0, 0xc001457380, 0xc001925b30, 0xc00166a540, 0xc0017eea90)
	/vt/src/vitess.io/vitess/go/vt/discovery/tablet_health_check.go:132 +0x74
vitess.io/vitess/go/vt/discovery.(*tabletHealthCheck).checkConn(0xc000cc5320, 0xc00045c000)
	/vt/src/vitess.io/vitess/go/vt/discovery/tablet_health_check.go:276 +0x2d5
```

Operating system and Environment details
vtgate: v10.0.2
vttablet: v11.0.0

**Comment by harshit-gangal** [comment]
I checked the code and this looks unrelated to the changes in the health check struct.

The panic tells that the issue in in below line
`hc.healthData[targetKey][tabletAlias] = th` 

which is only possible if `hc.healthData[targetKey]` is nil and the flow to come to this path is through `AddTablet` which adds that required map on the key  `hc.healthData[targetKey]`

@deepthi do you see any other path when this can be nil.

**Comment by deepthi** [comment]
@harshit-gangal that seems correct. We initialize the map when we AddTablet, and create the vtgate -> vttablet connection at that time. It is not possible to receive a healthCheck message from vttablet until that happens.

**Comment by harshit-gangal** [comment]
@derekperkins have you seen this error again?

**Comment by deepthi** [comment]
I believe this should fix it
https://github.com/vitessio/vitess/pull/9237/files#diff-b52bf818696494288a93bba0e91b8ff75fb2fd109bb1c80c77d166ea8349b722R436-R438
