### ISSUE TITLE
[vtadmin] Topology browser

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#8704]
# vtctld2 UI

Found under http://localhost:15000/app/topo

<img width="1792" alt="Screen Shot 2021-08-27 at 12 46 30 PM" src="https://user-images.githubusercontent.com/855595/131161446-7c5f212d-3bc5-4b0e-9c59-16e194b7403e.png">

# VTAdmin Implementation Notes

- This ticket is _specifically_ for the topology browser interface. Sub-functionality is ticketed separately (e.g., viewing vtctld elections) even when it's part of the topology browser in the vtctld2 UI. 

- The topology browser offers a way to browse the Vitess topology in a more nest-y, treelike way. VTAdmin already has something akin to the topology browser in its infrastructure list pages.  Before re-implementing the vtctld2 topology browser as-is, let's consider whether the combination of the existing VTAdmin UI + global search would fulfill the same use cases (with less surface area to write + maintain). 

- We'll need to add a couple more vtadmin-api endpoints; specific endpoints TBD.

**Comment by notfelineit** [comment]
The old topology feature provides the following info:
<img width="1850" alt="topology@2x" src="https://user-images.githubusercontent.com/31225471/163279401-d0a366fc-8244-4c24-9a34-247619abd401.png">

Auditing vtadmin to check if it shows the same info!

**Comment by notfelineit** [comment]
Corresponding VTAdmin routes for the global topo:
<img width="1156" alt="topology-vtadmin-global@2x" src="https://user-images.githubusercontent.com/31225471/163287206-338b262d-620f-4844-ae9d-0738b7fbb1ef.png">

**Comment by notfelineit** [comment]
Corresponding VTAdmin routes for the local topo:
<img width="991" alt="topology-vtadmin-local@2x" src="https://user-images.githubusercontent.com/31225471/163490561-a75dd40b-6300-4c44-84b5-0e056b853d23.png">

**Comment by notfelineit** [comment]
I believe this is the main file that powers topology in the current vtctld2 UI: https://github.com/vitessio/vitess/blob/main/go/vt/vtctld/explorer.go

It should be useful for replicating topology in VTAdmin!
