### ISSUE TITLE
[vtadmin] Ignore Health Check for tablets

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#8710]
# vtctld2 UI 

<img width="1792" alt="Screen Shot 2021-08-27 at 3 37 37 PM" src="https://user-images.githubusercontent.com/855595/131180101-96d7b68e-3e92-4492-aadb-09acd844524b.png">

<img width="1792" alt="Screen Shot 2021-08-27 at 3 37 33 PM" src="https://user-images.githubusercontent.com/855595/131180097-1d281349-83bc-441f-8d71-f38ec9116754.png">

# VTAdmin Implementation Notes

- The current UI uses both "Ignore Health Check" and "Ignore Health Error" phrasing

**Comment by notfelineit** [comment]
I think we'll be leaving this out of the VTAdmin UI due to https://github.com/vitessio/vitess/issues/9383

**Comment by deepthi** [comment]
we can go ahead and close this.
