### ISSUE TITLE
[vtadmin] Validate shard

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#8717]
# vtctld2 UI

Found at http://localhost:15000/app/shard?keyspace=commerce&shard=0 > menu > "Validate Shard"

<img width="1792" alt="Screen Shot 2021-08-27 at 6 13 04 PM" src="https://user-images.githubusercontent.com/855595/131193765-a6e90d9d-e16e-4a88-accc-11fb2cce45c9.png">
<img width="1792" alt="Screen Shot 2021-08-27 at 6 13 06 PM" src="https://user-images.githubusercontent.com/855595/131193767-20914eb3-98e9-46a3-b616-64db480d9007.png">
<img width="1792" alt="Screen Shot 2021-08-27 at 6 22 10 PM" src="https://user-images.githubusercontent.com/855595/131194308-5f76e07b-5dc4-4323-a761-a40d7e4d944a.png">

**Comment by notfelineit** [comment]
@maksimov are you still working on this? If not I'm happy to take it over as part of my parity work.

**Comment by maksimov** [comment]
@notfelineit can you leave it with me for another week, I'll let you know if it doesn't work out. Thanks!

**Comment by notfelineit** [comment]
Sure thing @maksimov - we are just trying to get to parity by the next release!

**Comment by notfelineit** [comment]
Hey @maksimov, just checking in if you have had time to do this? If not I can address it this week as a part of parity by v15.

**Comment by maksimov** [comment]
Go for it Frances, I won't have the capacity in the next few weeks, unfortunately.

**Comment by notfelineit** [comment]
@maksimov no worries, thank you!
