### ISSUE TITLE
[vtadmin] Reload keyspace schema

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#8738]
# vtctld2 UI

Found at http://localhost:15000/app/keyspace?keyspace=commerce > menu > reload schema in keyspace

<img width="1792" alt="Screen Shot 2021-08-30 at 12 23 10 PM" src="https://user-images.githubusercontent.com/855595/131371749-bf8e7851-2849-4002-a811-cd79ac484319.png">
<img width="1792" alt="Screen Shot 2021-08-30 at 12 23 11 PM" src="https://user-images.githubusercontent.com/855595/131371755-ca8b5026-ff2f-493e-9237-dc5437441edf.png">
<img width="1792" alt="Screen Shot 2021-08-30 at 12 23 13 PM" src="https://user-images.githubusercontent.com/855595/131371760-e879f841-900a-477c-a03c-f5d1f84c0238.png">

**Comment by notfelineit** [comment]
It looks like this was completed!
