### ISSUE TITLE
Pass vtgate user/principal through to MySQL as a query comment

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#8761]
# Summary

Today it is not possible to distinguish on a MySQL level which application (i.e. vtgate user) initiated a query.

# Use-cases
  * Auditing:  since vttablet/vtgate does not guarantee it's logging for audit purposes, users with strict audit requirements have to rely on logging on the MySQL server side (or the MySQL Enterprise audit plugin).  Having this information in the query can be leveraged to tie the application user to query actions.
  * Monitoring:  Allows potential for separating out monitoring of application query usage and performance on a per-application-user basis.

# Proposed solution
 
Add a new vttablet queryserver option to prefix the MySQL query with a comment including the effective callerid

**Comment by hallaroo** [comment]
Fixed by https://github.com/vitessio/vitess/pull/8783
