### ISSUE TITLE
Where is nodeSelector of helm

### ISSUE THREAD

**Issue by sim-wangyan** [vitessio/vitess#8799]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [Vitess User Guide](https://vitess.io/user-guide/introduction/)
- Any other questions can be asked in the community [Slack workspace](https://vitess.io/slack)

**Comment by mattlord** [comment]
This seems to be more of an FYI and redirect for similar questions in the future so closing the issue and it can continue to serve that purpose. If I misunderstood something we can re-open it. Thanks!
