### ISSUE TITLE
Add v2 vReplication Workflow Actions to vtctlclient CLI help/usage

### ISSUE THREAD

**Issue by Anders-PlanetScale** [vitessio/vitess#8906]
#### Feature Description
Currently vtctlclient does not define or explain the new v2 vReplication Workflow actions.

These include:
Create
SwitchTraffic
ReverseTraffic
Complete
Cancel
Show
Progress
GetState

To be aware of the new v2 workflow a user has to read the docs [here](https://vitess.io/docs/reference/vreplication/)
OR
They need to read through the vtctl.go code [here](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/vtctl.go) 

#### Use Case(s)
The old v1 process is in the CLI (SwitchReads/SwitchWrites) this could be confusing for end users
We should properly document the new workflow in the CLI -h/usage: sections for MoveTables and Reshard. And eventually depricate/remove the v1 steps from the CLI -h/usage:

**Comment by mattlord** [comment]
I'm closing this as done for now, please let me know if there's specific things left to document. Thanks!
