### ISSUE TITLE
v2 vReplication Workflows don't accept primary as a valid tablet-type

### ISSUE THREAD

**Issue by Anders-PlanetScale** [vitessio/vitess#8907]
#### Overview of the Issue
When running a v2 vReplication workflow, like MoveTables SwitchTraffic or ReverseTraffic, the -tablet_types flag does not accept `primary` as a valid tablet_type. You must use `master` to switch over writes.

#### Reproduction Steps
Start a v11.0.0+ vitess cluster (for ease of repro I used [vtmanager](https://github.com/mattlord/vtmanager))
`$ vtmanager create cluster test -v 11.0.0 -m 8.0`

Create a keyspace and a table in the keyspace. (using docker because of vtmanager)
`$ docker exec -it mysqld-test-1 mysql -u root -h vtgate-test -P 15306 unsharded_ks -e "create table t1 (id int)"`

Create a v2 vReplication MoveTables workflow:
```
$ docker exec -it vttablet-test-1 /vt/bin/vtctlclient -server=vtctld-test:15999 MoveTables -source=unsharded_ks -tables='t1' Create unsharded_ks.workflow
Waiting for workflow to start:
0% ... 0% ... 0% ... 0% ... 0% ... 
Workflow started successfully with 1 stream(s)

Following vreplication streams are running for workflow unsharded_ks.workflow:

id=1 on -/local-0000000001: Status: Running. VStream Lag: 0s.

```
Attempt a SwitchTraffic using -tablet_types:primary
```
$ docker exec -it vttablet-test-1 /vt/bin/vtctlclient -server=vtctld-test:15999 MoveTables -tablet_types=primary SwitchTraffic unsharded_ks.workflow
E0929 19:09:15.269797      63 main.go:67] E0929 19:09:15.269330 vtctl.go:2031] 
invalid tablet type passed primary

Following vreplication streams are running for workflow unsharded_ks.workflow:

id=1 on -/local-0000000001: Status: Running. VStream Lag: -1s. Tx time: Wed Sep 29 19:09:13 2021.

MoveTables Error: rpc error: code = Unknown desc = invalid tablet type passed primary
E0929 19:09:15.276105      63 main.go:76] remote error: rpc error: code = Unknown desc = invalid tablet type passed primary
```
Confirm it works with master:
```
$ docker exec -it vttablet-test-1 /vt/bin/vtctlclient -server=vtctld-test:15999 MoveTables -tablet_types=master SwitchTraffic unsharded_ks.workflow
SwitchTraffic was successful for workflow unsharded_ks.workflow
Start State: All Reads Switched. Writes Switched
Current State: All Reads Switched. Writes Switched

```

Cleanup:
`$ vtmanager delete cluster test`

NOTE: I used vtmanager in this repro example but I first ran into this with a local cluster that had two keyspaces running a v2 MoveTables on several tables with actual data. Vtmanager with an empty table was just easiest to repro to show the syntax error.

#### Binary version
$ docker exec -it vtgate-test /vt/bin/vtgate --version
ERROR: logging before flag.Parse: E0929 19:20:16.628988      25 syslogger.go:149] can't connect to syslog
Version: 11.0.0 (Git revision aa798b854a branch 'heads/v11.0.0') built on Tue Jul 27 11:40:19 UTC 2021 by vitess@buildkitsandbox using go1.16.5 linux/amd64

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`):
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
- Kernel version (output of `uname -sr`):
`Linux 5.11.0-7614-generic`

- Architecture (output of `uname -m`):
`x86_64`

#### Log Fragments
N/A

**Comment by mattlord** [comment]
`PRIMARY` tablets are new in 12.0. The function in play here is: https://github.com/vitessio/vitess/blob/main/go/vt/topo/topoproto/tablet.go#L168-L178 with the types defined here: https://github.com/vitessio/vitess/blob/main/go/vt/topo/topoproto/tablet.go#L168-L178

That was updated here and is only in `main` today: https://github.com/vitessio/vitess/commit/d2f884d21752e33b5e0943a5eb5b1b5c812517cf

That function in 11.0 is: https://github.com/vitessio/vitess/blob/v11.0.1/go/vt/topo/topoproto/tablet.go#L168-L175 and the types are: https://github.com/vitessio/vitess/blob/v11.0.1/go/vt/proto/topodata/topodata.pb.go#L200-L211

Unless I misunderstood?

**Comment by Anders-PlanetScale** [comment]
OK yeah looks like we don't need to "fix" it then. But 11.0 uses v2 workflow, which documentation on the site is incorrect for until 12.0 release.

We can probably close this issue and if anyone else notices it before 12.0 release then we can point them here.
