### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [vitessio/vitess#8917]
#### Overview of the Issue

Run a static analyzer DeepGo, which reports a coding issue.

#### Reproduction Steps

At https://github.com/vitessio/vitess/blob/main/go/vt/wrangler/keyspace.go#L1018-L1022,
https://github.com/vitessio/vitess/blob/d685cc1e27b2b709eb5c4722ec8febe4cf2f05c3/go/vt/wrangler/keyspace.go#L1018-L1022

Within the loop `for _, ts := range healthyTablets {`, variable `ts` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of `&ts` within the loop may refer to the last node item updated by the loop. As a consequence, nodes may hold multiple instances of the same tablet.

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

A fix is to avoid storing the address of the shared variable `ts`:
```
		for i, ts := range healthyTablets {
			if ts.Stats.Qps == 0.0 {
				drainedHealthyTablets[ts.Tablet.Alias.Uid] = &healthyTablets[i]
			} else {
				notDrainedHealtyTablets[ts.Tablet.Alias.Uid] = &healthyTablets[i]
			}
		}
```

**Found by #deepgo.**

**Comment by ajm188** [comment]
While the analysis is correct, this function (`(*wrangler.Wrangler).waitForDrainInCell`) is only called via the `vtctl` command `WaitForDrain` (`vtctl.commandWaitForDrain` => `(*wrangler.Wrangler).WaitForDrain` => `(*wrangler.Wrangler).waitForDrainInCell`), which is [deprecated](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/vtctl.go#L1328-L1329) (and, fun fact, the system it was replaced by has _also_ been deprecated in favor a third, newer system), so I'm going to just close this.
