### ISSUE TITLE
MoveTables doesn't migrate sequence in VSchema definition

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#9002]
#### Overview of the Issue

When migrating from a sharded keyspace to an unsharded keyspace, my expectation was that the sequence would continue to be applied afterwards, but it wasn't in the vschema definition. I quickly re-added it, so I didn't do any testing to see how it actually behaved.

Before MoveTables (sharded keyspace)

```javascript
    "semetrics_grepwords_pipeline": {
      "autoIncrement": {
        "column": "pipeline_id",
        "sequence": "semetrics_grepwords_pipeline_seq"
      }
    },
```

After MoveTables (unsharded keyspace)

```javascript
    "semetrics_grepwords_pipeline": {}
```

#### Operating system and Environment details

vttablet: 11.0.1
vtctld: 11.0.1
vtgate: 10.0.0

**Comment by DeathBorn** [comment]
I think for Movetables, one needs to provide vindexes or/and sequence definitions for target. In v8, when moving unsharded to sharded, I had to provide both.

Another note, when Movetables and  switchwrites is performed on sequence table, tables which use that sequence table do not  respect routing rules at all. Maybe sequence tables should not be migrated in that way.

**Comment by rohit-nayak-ps** [comment]
Closed via https://github.com/vitessio/vitess/pull/9288
