### ISSUE TITLE
RFC: Steering Committee

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9080]
### Overview

This document outlines the mission, scope, and objectives of the Vitess Steering Committee. 

### Goals
The Steering Committee exists as the overall governing body of the Vitess project, providing the project values, operations and structure.

### Scope

The Steering Committee has a set of rights and responsibilities including the following:

- Charter for Steering Committee.
- Define and evolve project governance structures and policies, including how contributors become maintainers.
- Define Steering Committee structure, terms and elections.
- Decide, for the purpose of elections, who can vote.
- Logo/landing page/marketing.
- Maintain relationships with CNCF in conjunction with the technical lead and community advocate
- Define, evolve, and defend the vision, values, mission, and scope of the project.
- Establish processes regarding, and provide a final escalation path for any contested project governance related decision.
- Establish processes regarding other project resources/assets, including artifact repositories, build and test infrastructure, web sites and their domains, blogs, social-media accounts, etc.
- Request funds and other support from the CNCF (e.g. marketing, press, etc.).
- Delegate appropriate authority to trusted individuals.

### Committee Structure
- Committee structure will initially be determined by a bootstrap steering committee (see below). Beyond that the steering committee can itself decide to change the committee structure if necessary.

### Bootstrap Steering Committee
We will form a bootstrap Steering Committee to serve for one year. The responsibilities of the bootstrap committee will be as follows.
- Charter for Steering Committee.
- Define Steering Committee structure, terms and elections.
- Decide, for the purpose of elections, who can vote.
- Conduct elections to form the next Steering Committee.

#### Members
- Rafael Chacon @rafael 
- Michael Demmer @demmer
- Paul Hemberger @pH14 
- Derek Perkins @derekperkins 
- Deepthi Sigireddi @deepthi 
- Sugu Sougoumarane @sougou, Chair

Related Issues/PRs: 
* #8577 
* #8609 

EDIT (Nov 22, 2021): Add bootstrap committee

**Comment by jberkus** [comment]
here's the template we have for a simple electoral structure: https://github.com/cncf/project-template/blob/main/GOVERNANCE-elections.md

**Comment by deepthi** [comment]
@jberkus @geekygirldawn Thank you for your feedback. I have incorporated your suggestions regarding the bootstrap committee into the proposal.
