### ISSUE TITLE
[vtadmin] "Operator's Guide" documentation

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#9127]
(These docs would live on vitess.io)

Quick + incomplete list of points to cover:

- Authentication (or lack of)
- Authorization
- Build
- Deployment
- Plugins
- vtctld2 parity

... and we can make it very clear that VTAdmin is still experimental.

**Comment by ajm188** [comment]
https://vitess.io/docs/16.0/reference/vtadmin/operators_guide/
