### ISSUE TITLE
Upgrade Bundled/Vendored Version of Etcd

### ISSUE THREAD

**Issue by mattlord** [vitessio/vitess#9128]
#### Overview of the Issue

We currently [incorporate etcd v3.3.10](https://github.com/vitessio/vitess/blob/f260405ef5c76787e9ffcfe7c6a3ec8aac09b15f/bootstrap.sh#L267) and that's what is installed via `make tools` which ends up [downloading that from our resources](https://github.com/vitessio/vitess/blob/f260405ef5c76787e9ffcfe7c6a3ec8aac09b15f/bootstrap.sh#L139-L168).

The latest GA release of etcd 3 as of today is 3.5.1 (and what gets installed via homebrew): https://github.com/etcd-io/etcd/releases

Not only have there been many bug fixes and feature improvements in etcd since 3.3.10 -- [released in Oct 2018](https://github.com/etcd-io/etcd/releases/tag/v3.3.10) (_ancient_ in Vitess time 😄) -- but the native Mach-O macOS binaries were built on a pretty old version of macOS and they no longer work on macOS 12.0 Monterey (Darwin 21 likely removed some deprecated kernel behavior and/or backwards compatibility features). 
> Note: macOS 10.14 Mojave was released at the end of September 2018 so I would guess these etcd binaries were built on macOS 10.13 High Sierra given the etcd release date.

#### Reproduction Steps

You can do either of the following which end up laying down the same etcd binary in the end:
1. In the vitess repo on the main branch: `make tools && ./bin/etcd --version`
2. From anywhere: 
```
ETCD_VER=v3.3.10

# choose either URL
GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/etcd-io/etcd/releases/download
DOWNLOAD_URL=${GOOGLE_URL}

rm -f /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
rm -rf /tmp/etcd-download-test && mkdir -p /tmp/etcd-download-test

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-darwin-amd64.zip -o /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
unzip /tmp/etcd-${ETCD_VER}-darwin-amd64.zip -d /tmp && rm -f /tmp/etcd-${ETCD_VER}-darwin-amd64.zip
mv /tmp/etcd-${ETCD_VER}-darwin-amd64/* /tmp/etcd-download-test && rm -rf mv /tmp/etcd-${ETCD_VER}-darwin-amd64

/tmp/etcd-download-test/etcd --version
```

We get a dynamic linker (`dyld`) failure that causes us to panic in the `bsdthread_register` syscall:
```
fatal error: runtime: bsdthread_register error
```

**Comment by mattlord** [comment]
For comparison:
```
$ otool -l /tmp/etcd-download-test/etcd | grep -E -A4 "LC_BUILD_VERSION|LC_VERSION_MIN_MACOSX"
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.7
      sdk 10.7
      
$ otool -l /opt/homebrew/bin/etcd | grep -E -A4 "LC_BUILD_VERSION|LC_VERSION_MIN_MACOSX"
      cmd LC_BUILD_VERSION
  cmdsize 24
 platform 1
    minos 11.0
      sdk 11.0
```

**Comment by deepthi** [comment]
@mattlord are you able to run without problems with etcd 3.5.1?
While we are at it we should also update the build time [dependency](https://github.com/vitessio/vitess/blob/f085f12b1cd38a9bcf907604a747af308e93c4fd/go.mod#L91) to match, it's currently at v3.5.0.

**Comment by mattlord** [comment]
@deepthi we've been doing various testing etc with etcd 3.5.0 and the .1 patch release should have bug fixes.

The bigger issues are ... why do we use the https://github.com/vitessio/vitess-resources/releases/download/v1.0/ location at all? I guess to be sure we don't lose access to a dependency (e.g. what happened with ZooKeeper). But https://github.com/vitessio/vitess-resources/releases/download/v1.0/etcd-v3.5.1-{linux,darwin}-{amd,arm}64.{.zip,tar.gz} artifacts do not exist there, do you know where/how we add files? @askdba maybe does?

Once those files are in place, I can easily update the go mod deps and the shell script that downloads and installs etcd.
