### ISSUE TITLE
vtctlclient: handle empty strings in Workflow commands

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#9137]
#### Overview of the Issue

When not specifying a workflow name, vtctlclient returns an error.

```
vtctlclient Workflow workspaces show
E1103 17:47:19.685981   21866 main.go:67] remote error: rpc error: code = Unknown desc = invalid format for <keyspace.workflow>: workspaces
```

Calling it with a period and no name appears to return all workflows appended together.

```
vtctlclient Workflow workspaces. show

{
	"Workflow": "",
	"SourceLocation": {
		"Keyspace": "workspaces",
		"Shards": [
			"0"
		]
	},
	"TargetLocation": {
		"Keyspace": "workspaces",
		"Shards": [
			"0"
		]
	},
	"MaxVReplicationLag": 1564264,
	"ShardStatuses": {
		"0/uscentral1-0089375700": {
			"PrimaryReplicationStatuses": [
				{
					"Shard": "0",
					"Tablet": "uscentral1-0089375700",
					"ID": 1,
...
```

Similarly, calling `vtctlclient Workflow workspaces. delete` deletes all workflows.

I believe we should explicitly error out on the empty string case, the same way it does without the period.

#### Binary version

v12.0.0

**Comment by rohit-nayak-ps** [comment]
Closed via #9224
