### ISSUE TITLE
Panic (concurrent map iteration and map write) in CopyBindVariables using vtcombo

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#9139]
A user reported this problem running against vttestserver/vtcombo (from the upstream docker containers) from a few weeks ago.

The scenario was running a load of queries like:

```
(SELECT c1 AS name FROM t1 LIMIT 1)
UNION
(SELECT c2 AS name FROM t2 LIMIT 1)
UNION
(SELECT c3 AS name FROM t3 LIMIT 1)
UNION
(SELECT c4 AS name FROM t4 LIMIT 1)
UNION
(SELECT c5 AS name FROM t5 LIMIT 1)
```

where t1,t2,t3,t4,t5 are all sharded tables.

Panic attached.

Brief look seems like we are somehow modifying the bind variables involved while copying them internally between the vtgate and vttablet "parts" of vtcombo.  It is therefore likely that this does not affect Vitess itself.

[panic.txt](https://github.com/vitessio/vitess/files/7471633/panic.txt)

**Comment by chreniuc** [comment]
Hi, I've noticed something similar when I'm using [typeorm](https://typeorm.io/#/) and connect it to vtgate.

I'm using mysql driver for typeorm, from nodejs. Typeorm has an option: [`synchronize`](https://typeorm.io/#/undefined/creating-a-connection-to-the-database), if that is set to true, it will start a transaction and it will query the `INFORMATION_SCHEMA` to see if the current db is up to date, if not, it will alter the tables.

The queries look similar to the ones from above, I will upload them below.

When I start the app and it does those queries, the vtgate crashes and it logs something similar as in the panic.txt(I will also upload the logs).

This was an empty database with only one shard, it was running on a k8 cluster using the operator.

The vttablet logs something like this:

```
W1107 17:52:23.181555       1 tabletserver.go:1358] Code: ABORTED
I1107 17:52:23.187492       1 dbconn.go:349] Due to context canceled, elapsed time: 2.362835ms, killing query ID 87 select * from INFORMATION_SCHEMA.`COLUMNS` where TABLE_SCHEMA = 'vt_ionescu' and TABLE_NAME = 'site_item_event' limit 100001
I1107 17:52:23.187975       1 dbconn.go:349] Due to context canceled, elapsed time: 3.685578ms, killing query ID 106 select * from INFORMATION_SCHEMA.`COLUMNS` where 1 != 1
E1107 17:52:23.204832       1 tabletserver.go:1358] Code: CANCELED
(errno 2013) due to context canceled, elapsed time: 3.685578ms, killing query ID 106 (CallerID: ionescu_backend)
: Sql: "select * from INFORMATION_SCHEMA.`COLUMNS` where TABLE_SCHEMA = :__vtschemaname and TABLE_NAME = :TABLE_NAME5", BindVars: {TABLE_NAME5: "type:VARBINARY value:\"site_item\""TABLE_NAME6: "type:VARBINARY value:\"site\""TABLE_NAME7: "type:VARBINARY value:\"company\""TABLE_NAME8: "type:VARBINARY value:\"user_company\""TABLE_NAME9: "type:VARBINARY value:\"user\""__replacevtschemaname: "type:INT64 value:\"1\""vtg1: "type:VARBINARY value:\"ionescu\""vtg10: "type:VARBINARY value:\"user_company\""vtg11: "type:VARBINARY value:\"user\""vtg2: "type:VARBINARY value:\"company_invite_code\""vtg3: "type:VARBINARY value:\"site_role\""vtg4: "type:VARBINARY value:\"item\""vtg5: "type:VARBINARY value:\"site_item_urgent\""vtg6: "type:VARBI
[mysqld.log](https://github.com/vitessio/vitess/files/7513889/mysqld.log)
NARY value:\"site_item_event\""vtg7: "type:VARBINARY value:\"site_item\""vtg8: "type:VARBINARY value:\"site\""vtg9: "type:VARBINARY value:\"company\""}
```

Vtgate logs this and multiple call stacks and crashes:

```
fatal error: concurrent map writes
fatal error: concurrent map iteration and map write
```

Do you have any idea why this happens?

Here are the logs:
 - [nodejs_start_logs.log](https://github.com/vitessio/vitess/files/7513890/nodejs_start_logs.log)
 - [vtgate.log](https://github.com/vitessio/vitess/files/7513891/vtgate.log)
 - [vttablet.log](https://github.com/vitessio/vitess/files/7513892/vttablet.log)
 - [mysqld.log](https://github.com/vitessio/vitess/files/7513898/mysqld.log)

**Comment by chreniuc** [comment]
@systay is there an ETA when a new version(bug fix version) will be released? We encountered this problem and we would like to use the new version(We're using the docker image).

**Comment by systay** [comment]
@chreniuc not sure. I think @frouioui might though

**Comment by chreniuc** [comment]
@systay I've noticed that the latest `vitess/lite` image that was generated here: https://hub.docker.com/r/vitess/lite/tags, was 10 hours ago. How is the [`latest`](https://hub.docker.com/layers/vitess/lite/latest/images/sha256-a0621cd099bc39cb32eefb63ea5e3a57875f8d073959c1968c07f26564a757ad?context=explore) tag generated? Everyday using the main branch from this repository?

**Comment by frouioui** [comment]
Hello @chreniuc,

What version of Vitess are you running?

As far as I know, Vitess does not have a patch release planned soon. However, we already have a few bug fixes piling up for the next patch release (`v12.0.1`), we can probably release it sometime soon. @deepthi and @askdba, what do you think?

If you're using a different version than `v12.0.0` we can also backport the fix to a previous release and do a patch release for it.

Regarding the Docker image, if you feel comfortable running your cluster on `main` (latest), you can use the `lite:latest` image which is built after every commit on main.

**Comment by chreniuc** [comment]
@frouioui I'm using `v12.0.0`, but I could use the `lite:latest` until a bug fix release is done. Thanks.

**Comment by chreniuc** [comment]
@systay @frouioui I've used the latest version and this commit did fix that issue, but I've encountered another problem now. It's another panic, I've described here: https://github.com/vitessio/vitess/issues/9214
