### ISSUE TITLE
Tablet manager detects and publishes `Identified mysql port: 0` during restore 

### ISSUE THREAD

**Issue by streadway** [vitessio/vitess#9153]
#### Overview of the Issue

Tablets that restore from backup identify and publish a `mysql_port: 0` before transitioning to REPLICA. After transitioning to REPLICA, the port remains published as 0.

This causes vtorc to discover instances with a 0 port, and detects a failure `ClusterHasNoPrimary: 10.0.0.1:0`.

Restarting the vttablet/mysqld pair publishes the correct port.

#### Reproduction Steps

1. Use planetscale/vitess-operator to create a keyspace with a backupLocationName and replicas: 1
1. Wait for vtbackup init pods to complete
1. Wait for the vttablet pods to restore from the initial backup
1. Observe the tablet is PRIMARY
1. Update replicas to 10 (something large enough to find a potential race)
1. Wait for tablets to transition from RESTORE to REPLICA
1. Observe at least one published 0 port with `vtctlclient ListAllTablets | grep ":0 "`

#### Binary version

* vitess/lite:v12.0.0
* planetscale/vitess-operator:v2.5.1
* kubernetes: v1.19

#### Operating system and Environment details

* Cross-region etcd2 global topology server with 100-500ms write times
* Datacenter local etcd2 cell topology server with 1-10ms write times
* Reproduced with non-virtualized hardware, local SSD data volumes
* Reproduced with AWS EBS data volumes

Relevant vttablet flags:

```text
--backup_engine_implementation=xtrabackup
--backup_storage_implementation=gcs
--binlog_use_v3_resharding_mode=true
--disable_active_reparents=true
--enable_replication_reporter=true
--enable_semi_sync=false
--health_check_interval=5s
--mycnf_socket_file=/vt/socket/mysql.sock
--mysqlctl_socket=/vt/socket/mysqlctl.sock
--restore_concurrency=10
--restore_from_backup=true
--wait_for_backup_interval=10s
```

#### Log Fragments

```text
I1104 22:13:40.295180       1 xtrabackupengine.go:655] move-back stderr: 211104 22:13:40 completed OK!
I1104 22:13:40.299880       1 xtrabackupengine.go:401] Restore: returning replication position f1ccf5a2-3d93-11ec-8a89-aa86234d344d:1-3,ff3a5091-3d93-11ec-89f8-fa2c3fe42f95:1-28
I1104 22:13:40.299900       1 backup.go:330] Restore: starting mysqld for mysql_upgrade
I1104 22:13:40.299906       1 mysqld.go:325] executing Mysqld.Start() remotely via mysqlctld server: /vt/socket/mysqlctl.sock
I1104 22:13:42.634742       1 tm_init.go:582] Identified mysql port: 0
I1104 22:13:42.634767       1 tm_state.go:355] Publishing state: alias:{cell:"db" uid:1810940814} hostname:"10.0.0.1" port_map:{key:"grpc" value:15999} port_map:{key:"vt" value:15000} keyspace:"example" shard:"40-50" key_range:{start:"@" end:"P"} type:RESTORE db_name_override:"vt_example" mysql_hostname:"10.0.0.1"
I1104 22:13:42.640762       1 syslogger.go:129] example/40-50/db-1810940814 [tablet] updated
I1104 22:13:43.304735       1 backup.go:337] Restore: running mysql_upgrade
I1104 22:13:43.304775       1 mysqld.go:256] executing Mysqld.RunMysqlUpgrade() remotely via mysqlctld server: /vt/socket/mysqlctl.sock
I1104 22:13:44.030852       1 backup.go:348] Restore: populating local_metadata
I1104 22:13:44.030873       1 metadata_tables.go:82] Populating _vt.local_metadata table...
I1104 22:13:44.038427       1 backup.go:356] Restore: restarting mysqld after mysql_upgrade
I1104 22:13:44.038444       1 mysqld.go:486] Mysqld.Shutdown
I1104 22:13:44.038451       1 mysqld.go:490] executing Mysqld.Shutdown() remotely via mysqlctld server: /vt/socket/mysqlctl.sock
I1104 22:13:48.048335       1 mysqld.go:325] executing Mysqld.Start() remotely via mysqlctld server: /vt/socket/mysqlctl.sock
```

**Comment by streadway** [comment]
The [findMysqlPort](https://github.com/vitessio/vitess/blob/84aad0d0a6c46ed38f6d4add00f6434c52169a20/go/vt/vttablet/tabletmanager/tm_init.go#L578-L581) goroutine uses the result of a successful `GetMysqlPort()` without validation.

[Mysqld.GetMysqlPort](https://github.com/vitessio/vitess/blob/84aad0d0a6c46ed38f6d4add00f6434c52169a20/go/vt/mysqlctl/replication.go#L153) succeeds to `SHOW VARIABLES like 'port'` over the unix socket. This could be before mysqld has bound the port, or mysqld has been configured to bind to a port.

**Comment by GuptaManan100** [comment]
This was reported again in https://github.com/vitessio/vitess/issues/12985 and eventually fixed. Please file a new issue if the problem still persists.
