### ISSUE TITLE
Fix breaking change to `ListAllTablets`

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9186]
#### Overview of the Issue
ListAllTablets output has changed, and breaks scripts or code that parses it.
Possibly other commands (like GetTablet) may also have this issue.

https://github.com/vitessio/vitess/pull/8973#issuecomment-964720741

#### Reproduction Steps
```
$ vtctlclient ... ListAllTablets
```

#### Binary version
Any build that includes e524e615593e4d3f619312c2ffc56cc85e77daa8

#### Operating system and Environment details
Any

**Comment by deepthi** [comment]
@ajm188 let's make sure we don't duplicate work on this. @mattlord is planning to do a fix PR unless you already have one in the works.

**Comment by ajm188** [comment]
https://github.com/vitessio/vitess/pull/8973#issuecomment-965642491
