### ISSUE TITLE
Backup fails with gRPC GOAWAY

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9195]
#### Overview of the Issue
While running a backup with the builtinbackupengine, if there is a large file (200G+ in this case) that has to be uploaded to s3, it can take a while. In the meantime the client (`vtctlclient`) gets a `GOAWAY` from the vttablet that is running the backup.

#### Reproduction Steps
Execute `vtctlclient ... BackupShard ...` on a keyspace/shard on a large-ish database. I haven't figured out a lower bound on how long the backup should be running, but the error shows up within 2 minutes of the last log message received from the tablet.

#### Binary version
Built from commit SHA 9ebc060dc91285c0ec62aafa0d2d9578c36f406c, so basically 12.0

#### Operating system and Environment details
EKS+s3 running `vitess/lite:mysql80` image

#### Workaround
The workaround is to run the backup with the flag value for `grpc_keepalive_time` set to greater than the expected backup time. For example:
```
$ vtctlclient ... -grpc_keepalive_time=2h -action_timeout=2h BackupShard ...
```

#### Log Fragments
```
E1111 02:18:33.644275       1 main.go:76] remote error: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings
BackupShard Error: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: ENHANCE_YOUR_CALM, debug data: too_many_pings
I1111 02:16:52.799998       1 main.go:67] I1111 02:16:52.799517 backup.go:187] I1111 02:16:52.830390 builtinbackupengine.go:376] Backing up file: table_name_redacted.ibd
```

**Comment by deepthi** [comment]
Even though there is a workaround, we should fix this properly.
This seems like a regression from when we updated the gRPC dependency version. The majority of keepalive options are being left at default values in the vitess client/server implementations, but we do set the client side keepalive_time to 10s.

Suggestion from @vmg is to rewrite the gRPC call as a streaming RPC so that the server sends updates back to the client.

Refs:
https://grpc.github.io/grpc/core/md_doc_keepalive.html
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
https://github.com/vitessio/vitess/blob/main/go/vt/grpcclient/client.go#L42
https://github.com/vitessio/vitess/blob/main/go/vt/servenv/grpc_server.go#L173

**Comment by vmg** [comment]
:+1: I'll be working on fixing the RPC by making it a streaming call.

**Comment by vmg** [comment]
After reviewing this code, the `Backup` call in our GRPC interface is already a stream, it's just not sending updates frequently enough.
