### ISSUE TITLE
RFC: Move VDiff to vttablet

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#9216]
#### Feature Description

Currently vdiff runs at the vtctld layer, which is responsible for contacting tablets involved in a workflow, streaming the rows into memory, doing the diff, and output the results. This _works_ but it does not scale well for running many vdiffs, or large vdiffs at once on vtctlds (which often are much less beefy than vttablets, hardware-wise as well).

If we were able to push down the work to just the tablets involved in the workflow, and leave the vtctld to only coordinate and collect results from the tablets, we could achieve much better vdiff throughput.

#### Design

This issue is a placeholder to start the discussion around how best to achieve this. We should eventually write up a design before doing significant work here.

**Comment by mattlord** [comment]
Closing this as fixed in: https://github.com/vitessio/vitess/pull/10382

Planned follow-up work can be seen here: https://github.com/vitessio/vitess/issues/10494

Please feel free to re-open this if I missed or misunderstood something.
