### ISSUE TITLE
RFC: Rollback of partial failed query in an explicit transaction

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#9266]
# Problem Statement
In a transaction, when a single DML (data manipulation language) query is broken into sub-queries like a scatter query or a vindex query. Then, any error in executing those queries leads to the rollback of the complete transaction.

This helps in guaranteeing that no unexpected data is committed on the transaction but it also leads to a bad user experience on handling distributed query errors inside transactions.

# Proposed Solution
In an explicit transaction created by the user, any DML query that executes on the multi-shard or needs a vindex update will execute in the scope of a savepoint. If there is any partial failure then the effect of that DML query will be rollback to the savepoint. In case the query completes successfully, savepoint will not be released, and only on a commit/rollback by the user, it will be cleared.

In an auto-commit mode, when a DML goes to multi-shard or vindex is updated, the implicit transaction created at the VTGate level will still have the same behavior of rollback of the transaction i.e. no impact of the failed DML query on the database.

# Test Cases

| S.No. | Test Case | Expectation |
| ----- | ------------- | ------------- |
| 1 | Begin -> partial failing query | transaction remains open; partial change rolled back |
| 2 | Begin -> partial vindex failing query | transaction remains open; partial change rolled back |
| 3 | Autocommit false -> partial failing query | transaction remains open; partial change rolled back|
| 4 | Autocommit false -> partial vindex failing query | transaction remains open; partial change rolled back |
| 5 | Partial change rollback failed (rollback to savepoint) | transaction is rolled back |
| 6 | Autcommit true -> partial failed query | Transaction is rolled back; No change on the database |

All 4 the cases in OLTP, OLTP-reserved, OLAP, OLAP-reserved

**Comment by arthurschreiber** [comment]
> In case the query completes successfully, savepoint will not be released

I'm curious why the savepoint could not be released. 🤔

**Comment by harshit-gangal** [comment]
It is extra work that is not required( i.e. slows down the query execution time), as soon as the transaction is committed or rolled back they do not exist anymore.

**Comment by harshit-gangal** [comment]
Original Discussion happened in #8984 

@arthurschreiber commented on 13 Oct
```
Description
We've encountered an issue where writing to a sharded table with a lookup VIndex can fail and cause the surrounding transaction state to be lost.

In our case, writing to the original table failed due to a unique key constraint not being met. Because this failure happens after Vitess has written information to the Lookup Vindex's table, Vitess performs a rollback of the transaction.

When outside of a user-initiated transaction, this is the correct behaviour to revert all changes that were performed. But when inside of a user-initiated transaction, this will actually abort the user's transaction, and can leave the application that is performing the operation in an undefined state.

I think the correct behaviour here would be to check whether a transaction was already started. If no transaction was started yet, the current behaviour is correct and should be used. If a transaction was already started, Vitess should create a new savepoint that it can roll back to in case of a later failure, or release the savepoint if the insert operation on the table succeeds.

Is https://github.com/arthurschreiber/vitess/blob/f10fa1eb0060f58e1088726a7330a61340dfabe9/go/vt/vtgate/plan_execute.go#L118-L123 the location in the code where that logic would have to be implemented / modified?
```

@arthurschreiber commented 26 Oct
```
As mentioned in the PR description above, the "problem" here lies with an incorrect handling of Vitess when application/user initiated transactions and VIndex operations are used together.

When Vitess encounters a DML statement that requires additional VIndex operations, it will generate a plan that requires executing the original DML plus the additional queries (before or after the original DML). To ensure these operations can be rolled back in case of an error, Vitess wraps these queries inside a transaction.

This is the correct behaviour for DML statements executed outside an existing transaction / in autocommit mode, but if a transaction was started by the application/user beforehand, the behaviour becomes problematic:

Vitess recognizes that a transaction is already in progress, so it skips starting a new transaction (as MySQL does not support true nested transactions), and it correctly skips committing the transaction if the DML operation (both the original plus the VIndex maintenance queries) were successful.

But in case of an error happening either in the original DML or a VIndex query, Vitess will execute a rollback, which will rollback the transaction that the application/user started.

What Vitess should be doing instead is to create a savepoint if it detects that the connection is already inside a transaction, and then either roll back to the savepoint in case of failure, or release the savepoint if the DML and VIndex queries were successful. This way, if an error happens, the transaction will not be rolled back, but the modifications made by Vitess will be cleaned up correctly.

There are some gotchas with using savepoints, as rolling back a savepoint in MySQL does not release any locks that were acquired after the creation of the savepoint - but I don't believe this should be a problem (and could simply be documented as a known limitation of using lookup VIndexes).
```
