### ISSUE TITLE
compatibility: TRIM operators not supported

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#9285]
From the docs, `TRIM` has optional arguments of `LEADING`, `BOTH` or `TRAILING`. `TRIM` without arguments works, but fails for all the rest. This syntax has been around since at least 5.6. I haven't dug any deeper into the failing syntax.
https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim

```
mysql> SELECT TRIM('  bar   ');
        -> 'bar'
mysql> SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');
        -> 'barxxx'
mysql> SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');
        -> 'bar'
mysql> SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
        -> 'barx'
```

`[1105] syntax error at position 32 near 'FROM'`

Vitess components @ v12.0.0

**Comment by GuptaManan100** [comment]
This would have been fixed by https://github.com/vitessio/vitess/pull/9834
