### ISSUE TITLE
Return the exact keyspace/shard in VEvent

### ISSUE THREAD

**Issue by 5antelope** [vitessio/vitess#9332]
#### Problem
Right now the VStream() endpoint returns VEvent with a [VGtid](https://github.com/vitessio/vitess/blob/main/proto/binlogdata.proto#L380). This filed contains all the target shards for the VStream endpoint. AFAICT, we do this as the checkpoint returns to the client so that they can store it and resume vstream if needed. 

However, this makes it hard identify which shard is the event coming from. We do have shard info inside FieldEvent and RowEvent https://github.com/vitessio/vitess/blob/main/proto/binlogdata.proto#L285-L298 but there are VEvent without those fields set as well.

#### Proposal
Would it make sense to return exact shard info as the top level field in `VEvent` (e.g., `ShardGtid`) so that the client always know which shard the event is coming from (the `VGtid` will be returned as is for checkpoint purpose)? 

This would help Vitess be more compatible with Debezium, where people usually expect a deterministic id for events. 

One might think why now use `VGtid` as the id directly? There are two problems with that: 1. the order of VGtid might changed depends on VStream API; 2. it is a unbounded list that is as long as number of targeted shard.

**Comment by sonne5** [comment]
cc @rohit-nayak-ps @deepthi would love to hear your thoughts on this! Thanks

**Comment by sonne5** [comment]
cc @aquarapid for visibility as well

**Comment by rohit-nayak-ps** [comment]
I get your point. We could definitely add keyspace/shard at the top level. Code change is easy, just a lot of tests need to be updated. 

However I would also like @keweishang's input on this since he was involved with writing the Vitess Debezium adapter: I wonder if they faced the same issue and if so, what approach they took.

**Comment by sonne5** [comment]
I think until recent, Vitess Debezium connector only emit field event/row event as is, without thinking about the transaction.

Therefore it wasn't a concern so far.

**Comment by keweishang** [comment]
>I think until recent, Vitess Debezium connector only emit field event/row event as is, without thinking about the transaction.

Correct, it isn't a concert for us so far. If adding keyspace/shard at the top level can be easily done, it would be much more consistent and Debezium friendly 👍

**Comment by sonne5** [comment]
Thanks @rohit-nayak-ps, I will close this ticket.

cc @shichao-an @jeffchao @gunnarmorling for visibility:

In the next Vitess release, we will have shard/keyspace as the top level field in `VEvent`, this means for Debezium's transaction metatadata we can iterate over `VGtid` and figure out the accurate `ShardGtid` that can be used as transaction id - as opposed to what we have now where the transaction id is a unbounded concatenation of `ShardGtid` from all the shards. 

There is still a hop away from the information we want (i.e., iterating `VGtid` to find the correct `ShardGtid`), but I think this is a good first step to improve the compatibility between Vitess and Debezium :)

**Comment by sonne5** [comment]
@rohit-nayak-ps A wild thought: do you feel it makes sense to pass `ShardGtid` directly as a top level filed in the `VEvent`, instead of just keyspace/shard? Or would that require significant more work here?

**Comment by sonne5** [comment]
re-open the issue to hash out the last bit on this issue re: `keyspace/shard` vs `ShardGtid`. Hopefully we can sort this out before the next release :)

**Comment by rohit-nayak-ps** [comment]
Hmm, `ShardGtid` is only valid _after_ a transaction is committed. For a transaction with multiple row events, for example, there will be a single related GTID which is sent after the _commit_. 

If we send the gtid for every event could end up with data inconsistency depending on client implementations in situations like:
* a transaction with two row events is being streamed with gtid `gtid1`
* the first row event sends `gtid1`
* connection fails
* client restarts using the last seen gtid: `gtid1`

In this flow the VStream API would start streaming from the next gtid and hence skip the second row event.

**Comment by sonne5** [comment]
@rohit-nayak-ps thanks for the inputs. 

IIUC, the events from a transaction will be sent by a single VEvent. In the example you have, a two-row txn will have one VEvent with two RowChange in this case. In this setup, the client would either receive both row updates with `gtid1` or they will see nothing.

Is my understand correct or am I missing something? Thanks.

**Comment by mattlord** [comment]
I'm going to close this for now as I'm not aware of any remaining work. If I'm missing something please let me know and we can re-open this. Thanks!
