### ISSUE TITLE
vtgate does not buffer queries when primary is unhealthy and awaiting a primary failover

### ISSUE THREAD

**Issue by tslo-stripe** [vitessio/vitess#9346]
#### Overview of the Issue

Vitess vtgate has an option (-enable_buffer) which enable buffering queries during a primary failover.  During testing, I found that when the primary vttablet becomes unhealthy and before the primary has failed over to another tablet, queries are not buffer and number of query failures did not drop as expected .  Looking at the code, it looks like we skip buffering when no healthy primary is found - https://github.com/vitessio/vitess/blob/main/go/vt/vtgate/tabletgateway.go#L288.

Is this expected?  Is it possible to buffer queries in vtgate when the primary becomes unhealthy and primary failover is pending?

#### Reproduction Steps

1. Enable buffering by setting -enable_buffer in vtgate
2. Start generating load to a shard in vitess through the vtgate with buffer enabled
3. Restart the primary tablet of that shard
4. Observe is queries are getting buffered and note the number of query failures.
5. Repeat steps 2-4 with buffer disabled (leave enable_buffer unset) and compare the results.

**Comment by GuptaManan100** [comment]
Hello @tslo-stripe, the buffering only happens for failover scenarios. So the buffering will happen if `PlannedReparentShard` is called. The buffering does not happen when the primary tablet is restarted for now.

There is also a new implementation of buffering, controlled by the flag `buffer_implementation`. The new implementation uses `keyspace_events` and it also buffers when a resharding operation is in progress. There was also a bug fix https://github.com/vitessio/vitess/pull/9112 that went into the newer implementation for buffering while PRS was in progress.

**Comment by GuptaManan100** [comment]
cc @deepthi @harshit-gangal @vmg

**Comment by vmg** [comment]
Yes, you should try the new keyspace events watcher: `-buffer_implementation=keyspace_events`. It has heuristics to detect more cluster states where buffering is safe to perform, including some cases where the primary is down.

**Comment by tslo-stripe** [comment]
Thanks.  It sounds like the reason is that even though vttablet is restarted and reparent will happen soon, we do not buffer requests as we are not sure if it is safe to do so and will rely on client to restart, is that correct?

I saw the buffer_implementation flag and it says "for testing" for "keyspace_events", so I was not sure if it is safe to be used in prod environment.

**Comment by vmg** [comment]
@tslo-stripe: we haven't received any reports of issues with the new implementation, so I think we're ready to make it the default. There are definitely people using it in production with good results, as it fixes another bug related to buffering during failovers.

**Comment by tslo-stripe** [comment]
Sounds good I'll update our config and set that flag to use keyspace_events.  Thanks.
