### ISSUE TITLE
Packaging of MySQL 5.7 tagged Docker Container

### ISSUE THREAD

**Issue by FancyFane** [vitessio/vitess#9353]
#### Overview of the Issue

Even though our documentation claims we do not deploy MySQL 5.6 docker containers it appears we still do. In addition, it appears that there are no MySQL 5.7 equivalent containers on Docker Hub. 

https://github.com/vitessio/vitess/blob/main/docker/README.md?plain=1#L41

#### Reproduction Steps

There are no MySQL 5.7 instances to find:
https://hub.docker.com/r/vitess/base/tags?page=1&name=mysql57

However, we are deploying MySQL 5.6:
https://hub.docker.com/r/vitess/base/tags?page=1&name=mysql56

**Comment by mattlord** [comment]
The stack is:
  - bootstrap (https://hub.docker.com/r/vitess/bootstrap/tags, https://github.com/vitessio/vitess/tree/main/docker/bootstrap)
  - base (https://hub.docker.com/r/vitess/base/tags, https://github.com/vitessio/vitess/blob/main/docker/base/Dockerfile)
  - lite (https://hub.docker.com/r/vitess/lite/tags, https://github.com/vitessio/vitess/tree/main/docker/lite)

The bootstrap layer is the one that installs the database version. 

If you look at the default Dockerfile in each layer of the stack you will see that 5.7 is the default:
  - base: https://github.com/vitessio/vitess/blob/main/docker/base/Dockerfile#L25
  - lite: https://github.com/vitessio/vitess/blob/main/docker/lite/Dockerfile#L1

**Comment by FancyFane** [comment]
There appears to be some confusion here caused by the line in the  documentation that was written to "avoid confusion". We may need to modify this as Vitess now ship many flavors of MySQL to Docker hub:

https://github.com/vitessio/vitess/blob/main/docker/README.md?plain=1#L41

In addition Vitess' default images comes with the `mysql57` flavor but there are no images with the tag `mysql57`. We may want to create this new tag in the event Vitess changes the default flavor. This would allow users to lock in the `mysql57` flavor until they are ready to change the flavor or upgrade independent of Vitess' future decisions. 

https://hub.docker.com/r/vitess/lite/tags?page=1&name=mysql5
https://hub.docker.com/r/vitess/base/tags?page=1&name=mysql5

**Comment by FancyFane** [comment]
I will close this issue out as MySQL 5.7 is soon to be EOL, and this write up has lost it's relevance.
