### ISSUE TITLE
in vttablets web ui of Vitess 12.0.0: can not Delete master tablet

### ISSUE THREAD

**Issue by Jin-2019** [vitessio/vitess#9361]
#### Overview of the Issue

I want to delete tablet pod in vttablets web ui of Vitess 12.0.0 , but throwing error that  flag provided but not defined: -allow_master.
![image](https://user-images.githubusercontent.com/64535472/145771917-1df2bb1e-cb3f-4104-b33c-8cf6a8470935.png)

#### solution
I think there is a problem with 9 line of web/vtctld2/src/app/shared/flags/tablet.flags.ts 
![image](https://user-images.githubusercontent.com/64535472/145772418-96556841-3a46-4bed-a588-045129f187fc.png)

**Comment by ajm188** [comment]
👋 unfortunately we didn't get to this, but the entire UI is deprecated and being deleted, so i'm going to close this as wont fix
