### ISSUE TITLE
Deprecate `IgnoreHealthError` at vtctl 

### ISSUE THREAD

**Issue by notfelineit** [vitessio/vitess#9383]
#### Feature Description
We want to deprecate `IgnoreHealthError` rpc endpoint because it's deprecated at the tablet level:
![image](https://user-images.githubusercontent.com/31225471/146040677-fa77165d-ecd7-4e9e-92c0-2a51a2888fff.png)

We should also remove it from vtctl2 UI if we think that's relevant. 

#### Use Case(s)g)
In the vtctld2 UI and vtctl rpc endpoint:
![image](https://user-images.githubusercontent.com/31225471/146040818-c38b5c59-89e2-4adb-bb60-7575487c548b.png)

**Comment by deepthi** [comment]
Fixed in #9594
