### ISSUE TITLE
Batch requests to topo server for ListAllTablets in vtctld 

### ISSUE THREAD

**Issue by zhongr3n** [vitessio/vitess#9384]
Please search the existing issues for relevant feature requests, and use the [reaction feature](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing requests.

#### Feature Description

Currently when ListAllTablets is called from vtctld client, vtctld server sends find all the tablet aliases in the cell and sends them in one [GetTabletMap call](https://github.com/vitessio/vitess/blob/master/go/vt/topotools/utils.go#L45-L51), which in turn [makes one request for each tablet alias to topo server in parallel](https://github.com/vitessio/vitess/blob/master/go/vt/topo/tablet.go#L426-L443). This causes a spike of requests sent to topo server. In our case, we see ListAllTablets fail frequently due to topo server throttle when there's many tablets in a cell.

Two things to consider:
1. Shall we batch the GetTabletMap call to topo server, so we don't overload the topo server when there's many tablets in the cell?
2. It'd be good to also support filtering on ListAllTablets on the server side (e.g. list all the `SPARE` tablets) See use cases below

#### Use Case(s)

1. Operator calls ListAllTablets in a cell and grep on the result to find some specific tablet
2. We have some automate workflows that call this API to find all the `SPARE` tablets in a cell and verify if we have enough spare capacity before it takes some action.

**Comment by zhongr3n** [comment]
@mattlord Thank you for improving ListAllTablets user interface! It's a lot more friendly.

One thing remaining though is we still make [one GetTabletMap call](https://github.com/vitessio/vitess/blob/4b37d644f3d3cb98b7d5c3df65ea8f6708652fc3/go%2Fvt%2Ftopo%2Ftablet.go#L334) for all the tablet aliases in a cell, which results in [one parallel request for each tablet alias](https://github.com/vitessio/vitess/blob/4b37d644f3d3cb98b7d5c3df65ea8f6708652fc3/go%2Fvt%2Ftopo%2Ftablet.go#L524-L542). The filtering on tablet type etc is happening on vtctld server, but doesn't affect the call from vtctld to topo server. If there are many tablets in a cell, it could still cause huge spike of load from vtctld to topo server.

Shall we consider break the list of tablet aliases in a cell into batches and paginate through them?

**Comment by mattlord** [comment]
Hi @zhongr3n!

That [`GetTabletMap` call](https://github.com/vitessio/vitess/blob/4b37d644f3d3cb98b7d5c3df65ea8f6708652fc3/go%2Fvt%2Ftopo%2Ftablet.go#L334) is within [`GetTabletsIndividuallyByCell`](https://github.com/vitessio/vitess/blob/f906693c6441f4b41d8f842ffb9dba85258b5158/go/vt/topo/tablet.go#L326) which is only [used as a fallback when the topo server does not implement the list call](https://github.com/vitessio/vitess/blob/f906693c6441f4b41d8f842ffb9dba85258b5158/go/vt/topo/tablet.go#L297-L308) (ZooKeeper and Memory topo servers).

Are you concerned about the topo servers that still use the individual calls? Or am I missing or misunderstanding something?

Thanks!

**Comment by zhongr3n** [comment]
@mattlord Gotcha. Missed that part. We're using etcd so it's all good now. I suppose it might still be useful for ZooKeeper users?

**Comment by mattlord** [comment]
Hi @zhongr3n!

No worries. It would definitely be useful with ZooKeeper but it doesn't support scans AFAIK. You can only request a specific key, one at a time (basic K/V interface). So you have to know what the keys are and ask for them one at a time, which was the old method (fallback now) used. 

If you have some ideas though (I may have missed or misunderstood something) I'd be interested in chatting with you about them. 

Best Regards

**Comment by zhongr3n** [comment]
@mattlord Oh I meant it'll be useful in the fallback method for ZooKeeper to paginate through all the tablet aliases in batches instead of [calling GetTablet for all tablet aliases in parallel](https://github.com/vitessio/vitess/blob/4b37d644f3d3cb98b7d5c3df65ea8f6708652fc3/go%2Fvt%2Ftopo%2Ftablet.go#L524-L542) resulting in a burst of requests. That was what caused throttling on our side previously.

**Comment by mattlord** [comment]
Hi @zhongr3n, 

OK, thanks! We could limit the parallelism when doing it tablet by tablet, but that will of course make the `ListAllTablets` calls take much longer too (could be 10x or even 100x) — which could in turn result in more higher level `ListAllTablets` calls being run concurrently. Are you still using ZooKeeper? How important is this to you?

Best Regards

**Comment by zhongr3n** [comment]
Hi @mattlord Yeah that's a fair point. It might not scale very well unless the client also does pagination. On the other hand, if there's too many tablets (1000s), calling everything in parallel also could fail due to throttling (which was what we saw consistently with consul before this fix)

We're on etcd now, so it's not really a concern for us. Raising this only because we were previously affected by this. Feel free to punt given there's no actual data points from ZooKeeper users.
