### ISSUE TITLE
[vtadmin-api] Allow RBAC config file to be optional

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#9419]
The `--rbac-config` flag is required when running vtadmin-api. If omitted:

```
F1217 12:14:01.251523   31578 main.go:72] open rbac.yaml: no such file or directory
```

The local example provides a default rbac.yaml file here: https://github.com/vitessio/vitess/blob/main/examples/local/vtadmin/rbac.yaml 

However, it might be more ergonomic + explicit if Vitess operators could _either_:
- Provide an `--rbac` flag and an `--rbac-config` file, or
- Provide a `--no-rbac` (or `--rbac=false`) flag to explicitly opt out of using RBAC.

**Comment by setassociative** [comment]
I was reading the related backscroll with [jakon](https://vitess.slack.com/archives/C01H307F68J/p1639611736036300) and had the thought that defaulting allow-all when no rbac config flag is convenient but allows failure in an unsafe way: I can imagine fucking up a chef flag -> not passing an rbac flag -> opening write actions to the world.

Still extremely into easy allow-all option but we should make it opt-in under `--no-rbac` or similar.

**Comment by notfelineit** [comment]
A clarifying q, does that mean we're either saying 1) must pass in rbac config or 2) must explicitly pass --no-rbac to default to all?

**Comment by jakon89** [comment]
@setassociative +1 for `--no-rbac` 
Anyway, unknown flags aren't allowed so its unlikely that scenario is possible:
```
adam@local ~ % docker run vtadmin:latest --rbac-confi /non-exisiting-file
ERROR: logging before flag.Parse: E1217 18:05:40.620713       1 syslogger.go:149] can't connect to syslog
Error: unknown flag: --rbac-confi
Usage:
  vtadmin [flags]
```

**Comment by setassociative** [comment]
@notfelineit yea, that's my suggestion

@jakon89 so when constructing args to set up vtadmin there is the error where you typo the arg and it's safe as you point out. I'm more worried about a scenario where it gets omitted entirely for whatever reason and I'd rather fail hard and fast in that situation

**Comment by doeg** [comment]
This sounds great. I updated the issue description to specify an explicit `--no-rbac` flag (instead of "failing open" if an RBAC config file is not provided).

**Comment by doeg** [comment]
Also what about `--rbac` and `--rbac=false`? 🤔 Not sure if Vitess has a convention for boolean flags.

**Comment by notfelineit** [comment]
This issue is being addressed here: https://github.com/vitessio/vitess/pull/9972
