### ISSUE TITLE
[vtctld]When delete the tablet , allow_master is not defined

### ISSUE THREAD

**Issue by wangsijia1985** [vitessio/vitess#9444]
Delete replica(1600417777)
There was a problem deleting replica(1600417777): flag provided but not defined: -allow_master
Log:
flag provided but not defined: -allow_master

Usage: DeleteTablet [-allow_primary] <tablet alias> ...

Deletes tablet(s) from the topology.

  -allow_primary
    	Allows for the primary tablet of a shard to be deleted. Use with caution.

**Comment by mattlord** [comment]
Hi @wangsijia1985,

The `master` terminology has been replaced by the more inclusive `primary` terminology throughout Vitess in 12.0. You can see the docs for this specific example here: https://vitess.io/docs/12.0/reference/programs/vtctl/tablets/#deletetablet

I will close this for now as this seems to be expected, but please let me know if I'm missing or misunderstanding something.

Thank you!
