### ISSUE TITLE
Support checking workflow lag before initiating SwitchTraffic (SwitchReads/SwitchWrites)

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#9525]
Scenario:
  * On a busy keyspace, a MoveTables (or Reshard) SwitchTraffic operation will today blindly switch reads, and then writes, as long as the copy phase is complete
  * If, due to heavy traffic, the vreplication lag is significant, the SwitchWrites part of SwitchTraffic will eventually fail (due to the 30s default operation timeout), but at that point write downtime will already have been incurred.
  * A workaround for this currently is to manually check the workflow vreplication lag (via a `Workflow... show` or the newer `MoveTables ... Progress` or `Reshard ... Progress`) before executing the `SwitchTraffic`
  * However, the user-friendly way of doing this might to do this check first, with a configurable "acceptable" lag, before executing either of the switching operations and incurring any read/write downtime.

**Comment by kristee-planetscale** [comment]
@mvh-stripe

**Comment by mattlord** [comment]
Closing this for now as I believe the issue was addressed in https://github.com/vitessio/vitess/pull/9538. Please let me know if that's not right and we can re-open this. Thanks!
