### ISSUE TITLE
Add CI check for drift between src/proto and generated pb.go files

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#9588]
Similar to https://github.com/vitessio/vitess/issues/9571, this issue proposes we add a CI check to ensure that the `proto/*.proto` files are in sync with the generated `go/vt/proto/*.pb.go` files. This would catch any instance where a .proto file is updated but `make proto` is not run.

**Comment by frouioui** [comment]
Closing this issue, #9644 is merged :)
