### ISSUE TITLE
RFC: Remove the vtctld2 UI codebase

### ISSUE THREAD

**Issue by doeg** [vitessio/vitess#9686]
This RFC proposes a roadmap for sunsetting and removing the [web/vtctld2](https://github.com/vitessio/vitess/tree/main/web/vtctld2) user interface:

![image](https://user-images.githubusercontent.com/855595/153923518-daaf85be-6bc9-4b4d-b274-a15fd3e5109b.png)

The vtctld2 codebase was built in 2016 and has not been actively maintained since ~2017.  Vitess operators are encouraged to switch to [VTAdmin](https://github.com/vitessio/vitess/issues/7117) instead. Further motivation for this change is described in the original VTAdmin RFC: https://github.com/vitessio/vitess/issues/7117.

Feedback of all kinds is requested and appreciated! 🙇 Dates are fairly flexible, especially for Vitess 15.0 onwards. 

# Roadmap

### Vitess 13.0, February 2022

- Add `enable_vtctld2_ui` flag, default to `true`, so the UI remains enabled by default. 
    - (This flag was added in https://github.com/vitessio/vitess/pull/9614 but still needs to be backported to 13.0.) 

- Add and update documentation
    - VTAdmin operator’s guide
    - vtctld2 → VTAdmin migration guide
    - Integrate VTAdmin into the local example

- Work in web/vtctld2 (including bugfixes and dependency updates) will not be prioritized going forward. 

### Vitess 14.0, June 2022

- Finish bringing VTAdmin to feature parity with the vtctld2 UI; roadmap: https://github.com/vitessio/vitess/projects/13

- Update `enable_vtctld2_ui` flag to default to `false`. The UI will be disabled by default. Vitess operators still wishing to run the UI should run their `vtctld` processes with `enable_vtctld_ui=true`.

- Third party security audit (pending approval)

### Vitess 15.0, October 2022

- VTAdmin's web interface (vtadmin-web) is GA. 

### Vitess 16.0, January 2023

- Remove the web/vtctld2 codebase. 

# Notes

- We will not be deprecating the [vtctld API](https://github.com/vitessio/vitess/blob/main/go/vt/vtctld/api.go#L195) that is used by the vtctld2 web interface as part of this work.

**Comment by doeg** [comment]
One thing worth adding to this RFC might be the release where we deem VTAdmin as no longer "experimental". 

I'm not sure if Vitess has an official definition of the term; for VTAdmin, I'm thinking that this would primarily affect the HTTP API. I can see people using that programmatically in which case breaking changes might matter a lot -- at Slack we were experimenting with it for monitoring, for example. 

@deepthi @notfelineit would love your thoughts. 🙇

**Comment by deepthi** [comment]
People do use the vtctld2 API. @doeg the guideline is that we keep things "experimental" to give us flexibility to change the interface. During that time no version compatibility guarantees. Once something is GA then we have to start supporting +/- 1 version via deprecations and notices in release notes or PRs.

**Comment by derekperkins** [comment]
Is there anything in the http api that isn't in the grpc api? I wouldn't be opposed to marking the http api experimental for a few releases

**Comment by notfelineit** [comment]
The "dynamic clusters" change I made a few weeks back is only in the http api, and not in the grpc api, but it's a feature that wouldn't make sense in the grpc api anyway, since it relies on cookies and expects the client to be a web browser.

**Comment by doeg** [comment]
I just want to check my understanding of the thread so far, since there are so many moving pieces:

- vtctld2 is comprised of two pieces, and I'm going to give them names for the sake of discussion:
   - `vtctld2-web`: the UI, which primarily lives in [web/vtctld2]((https://github.com/vitessio/vitess/tree/main/web/vtctld2) and is served from the vtctld in [go/vt/vtctld/vtctld.go](https://github.com/vitessio/vitess/blob/66109e7/go/vt/vtctld/vtctld.go#L144-L145)
   - `vtctld2-api`: the REST API, which is also served from the vtctld [here](https://github.com/vitessio/vitess/blob/66109e7/go/vt/vtctld/vtctld.go#L157)

- VTAdmin is comprised of two pieces, too:
  - `vtadmin-web`: the UI, which is located at [web/vtadmin](https://github.com/vitessio/vitess/tree/main/web/vtadmin)
  - `vtadmin-api`: the HTTP(S) API, which is located in [go/vt/vtadmin](https://github.com/vitessio/vitess/blob/main/go/vt/vtadmin/api.go). 
  
So far it sounds like the proposal is:
- `vtadmin-web` can be GA before `vtadmin-api` since there are fewer compatibility concerns with a user interface. (People can't/won't be using it programmatically.) 
- `vtadmin-api` (the HTTP(S) API) will stay experimental for now, meaning we won't have to worry about backwards compatibility right away. [1]

There are two things I want to add. :) 

## Thing #1: should we prioritize removing `vtctld2-api`?
 
This is a clarification on the milestone "Remove the vtctld2 codebase", under the 16.0 release, since in retrospect that is ambiguous. 

My primary goal is to remove `vtctld2-web`; that is, removing all of the user interface code in [web/vtctld2](https://github.com/vitessio/vitess/tree/main/web/vtctld2), since _that_ is the part of the codebase that is irreparably out of date. (The `vtctld2-api` code hasn't been modified in a long time, but it's less of an issue since it's golang + therefore about as up to date as the rest of the go codebase.)  

The gap analysis done for the parity roadmap in https://github.com/vitessio/vitess/projects/13 in its current state was done "from the UI perspective". That is, mapping out all of the features in `vtctld2-web` without special consideration for `vtctld2-api`. 

There are some features of `vtctld2-api` that are missing from that roadmap; for example, the work to port over the realtime stats API and the debug endpoints. (IIRC, those two in particular will entail a bit of consideration since they are presently without types/protos, _and_ somewhat context dependent.) 

I'd definitely like to remove `vtctld2-api`, **but I'm wondering if that might be best for a subsequent project/RFC.**

I think initially focusing on removing `vtctld2-web` will let us remove that codebase more swiftly, which is important as many of the core web/vtctld2 dependencies are very (very!) out of date and impossible to update, which is not great for security reasons. 

Would love to hear what you think!

**Comment by notfelineit** [comment]
@doeg I'm in agreement with you that the scope should be focused on the web UI's - deprecating vtctld2 web UI and "GA"-ing vtadmin web UI. We probably need further analysis for bringing the APIs to parity 😄

**Comment by doeg** [comment]
@notfelineit Thank you! 🎉 +1 that we can take a closer look at `vtctld2-api` later on since I've been doing the same. (I think the realtime stats and debug endpoints will be fun to revisit, tbh!) 

I'll rename this RFC + also https://github.com/vitessio/vitess/projects/13 to be more specific about removing "just" the UI, if there are no objections. :)

**Comment by derekperkins** [comment]
Right now the `vtctld` docker image ships with `vtctld2-web`. It seems like it vtadmin should be added there by default, to make the transition easier.

**Comment by notfelineit** [comment]
^ We should make that a part of parity then if folks are relying on the vtctld docker image 😄

**Comment by notfelineit** [comment]
Closing this now that the web components are removed. If/when we want to remove the HTTP API, let's open a separate issue.
