### ISSUE TITLE
Unhandled Error in the demo example

### ISSUE THREAD

**Issue by TahsinTunan** [vitessio/vitess#9763]
Here's a code snippet from [demo.go](https://github.com/vitessio/vitess/blob/main/examples/demo/demo.go) from the `examples` folder:
```go
srow := make([]string, 0, len(row))
for _, value := range row {
	if value.Type() == sqltypes.VarBinary {
		srow = append(srow, hex.EncodeToString(value.ToBytes()))
	} else {
		srow = append(srow, value.ToString())
	}
}
```
Here, `ToBytes()` returns 2 things:
1. A slice of byte
2. An error

And the `EncodeToString()` function takes only a slice of byte as an argument. Shouldn't we handle the error coming from `ToBytes()` since it passes two arguments to the `EncodeToString()` function instead of one?

**Comment by TahsinTunan** [comment]
needs triage

**Comment by TahsinTunan** [comment]
needs-triage

**Comment by mattlord** [comment]
There’s an open PR for this: https://github.com/vitessio/vitess/pull/9615

I’ll link the two. Thank you!
