### ISSUE TITLE
call to sequence table is leaking reserved connections on vttablet

### ISSUE THREAD

**Issue by jakon89** [vitessio/vitess#9851]
### Overview of the Issue

Reserved connections on vttablet where the sequence is hosted are not being closed when inserting a new row. Sounds weird but see reproduction steps - it's super easy to understand by reading it step by step.

This is a major issue for me - the vttablet that hosts sequence tables is restarting its query engine very frequently once a number of reserved connections hit the MySQL limit - apparently, each vttablet's reserved connection holds MySQL connection thus limiting its availability. The restart of the query engine results in transactions being dropped and it's affecting client applications.

IMO the issue starts in `go/vt/vtgate/engine/insert.go:519`
The code mentioned above clones the current session and calls the sequence holder** with `select next :n values from ...` query - I think it could just create a new session (don't clone it) and that will result in a non-reserved connection. WDYT? 

**In this example the vttablet calls itself - but the issue occurs also when two vttablets are involved - vttablet that is receiving `INSERT` query and the second that is generating sequence number.

//edit
see comment https://github.com/vitessio/vitess/issues/9851#issuecomment-1067265470 for use case explanation
### Reproduction Steps

commerce keyspace `vschema`:
```json
{
    "sharded": false,
    "tables": {
        "user": {
            "auto_increment": {
                "column": "id",
                "sequence": "commerce.user_seq"
            }
        },
        "user_seq": {
            "type": "sequence"
        }
    }
}
```

commerce keyspace tables:
```sql
create table user_seq
(
    id      bigint,
    next_id bigint,
    cache   bigint,
    primary key (id)
) comment 'vitess_sequence';


insert into user_seq(id, next_id, cache)
values (0, 10, 10000);


CREATE TABLE `user`
(
    `id`   bigint(20) NOT NULL AUTO_INCREMENT,
    `name` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Step by step with vitess for local:

```
# git clone git@github.com:vitessio/vitess.git && cd vitess

git checkout main && git pull

make docker_local

./docker/local/run.sh

vtctlclient ApplyVSchema --vschema '{"sharded":false,"tables":{"user":{"auto_increment":{"column":"id","sequence":"commerce.user_seq"}},"user_seq":{"type":"sequence"}}}' commerce

vtctlclient ApplySchema --sql-file=$(pwd)/user.sql commerce

step 1:
curl http://localhost:15100/debug/vars -s | grep ReservedCount

step 2:
mysql -h 127.0.0.1 -P 15306 commerce -e "insert into user (name) values ('Adam'); select * from user;"

step 3:
curl http://localhost:15100/debug/vars -s | grep ReservedCount

step 4:
mysql -h 127.0.0.1 -P 15306 commerce -e "set max_tmp_tables=11; insert into user (name) values ('Mark'); select * from user;"

step 5:
curl http://localhost:15100/debug/vars -s | grep ReservedCount
```

Step 1 is just to show that there aren't any reserved connections in vttablet.

Step 2 and 3 adds a new row using *connection from connection pool* - no reserved connection involved yet. This step is to show that issue doesn't exist for pooled connections.

Step 4 *the issue is here* - I force vtgate to open reserved connection by setting `set max_tmp_tables=11;` for current session, then add a new row.

Step 5 shows that the reserved connection wasn't properly closed and is still open, however, it's effectively dead - no one will ever use it as the client closed its session with vtgate.

### Binary Version

```sh
vitess@0b97648e3d31:/vt/local$ vtgate --version
ERROR: logging before flag.Parse: E0309 15:45:45.414492    2252 syslogger.go:149] can't connect to syslog
Version: 14.0.0-SNAPSHOT (Git revision 8c92a04efb branch 'main') built on Wed Mar  9 15:04:57 UTC 2022 by vitess@buildkitsandbox using go1.17.6 linux/amd64
```

### Operating System and Environment details

```sh
linux/docker
```

**Comment by harshit-gangal** [comment]
For a workaround, if you really do not need system settings changes on the session then disable it on VTGate with `-enable_system_settings=false`

**Comment by aquarapid** [comment]
Note that the leaked sessions should disappear as soon as the tablet's tx timeout (`-queryserver-config-transaction-timeout` default 30 seconds) fires, logging something like this in the vttablet log:

```
W0309 13:25:05.848487   91936 tx_pool.go:126] killing transaction (exceeded timeout: 30s): 1646860601578329973
```

This probably explains why no-one noticed it before;  unless your sequence's `cache` value is very low (general starting recommendation is around `1000` if it's a `BIGINT` column) and/or you are inserting many thousands of rows per second, your leak is unlikely to grow to more than a few dozen connections before the reaping stabilizes the number of concurrent leaked connections.

**Comment by jakon89** [comment]
Thanks all for your input!

@aquarapid IMO this is only partially true.

If you execute step `4` from my comment above multiple times (let's say 5) you will see 5 connections being active:
```
... insert 4x Mark....
vitess@87646cf6f940:/vt/local$ mysql -h 127.0.0.1 -P 15306 commerce -e "set max_tmp_tables=11; insert into user (name) values ('Mark'); select * from user;"
+----+------+
| id | name |
+----+------+
| 10 | Adam |
| 11 | Adam |
| 12 | Adam |
| 13 | Mark |
| 14 | Mark |
| 15 | Mark |
| 16 | Mark |
| 17 | Mark |
+----+------+
vitess@87646cf6f940:/vt/local$ curl http://localhost:15100/debug/vars -s | grep ReservedCount
"UserActiveReservedCount": {"vitess": 5},
"UserReservedCount": {"vitess": 5},
```

despite the fact that cache value was set to 10k:
```sql
vitess@87646cf6f940:/vt/local$ cat user.sql
create table user_seq
(
    id      bigint,
    next_id bigint,
    cache   bigint,
    primary key (id)
) comment 'vitess_sequence';


insert into user_seq(id, next_id, cache)
values (0, 10, 10000);
```

IMO it looks that vttablet is either not honoring cache value at all (very unlikely IMO as seq table is not being updated that frequently) or opening a new MySQL connection for every `select next :n values from %s` received from vtgate.

In either case it is causing a lot of troubles for me :( 

@harshit-gangal 's advice is cool but we can't disable it now. My quick fix is to set tx limit to 30s or less for that single vttablet that generates IDs but it won't work with my rate of inserts in any env except QA.

**Comment by harshit-gangal** [comment]
Before we do the fix there is one more workaround if you can set at the MySQL level in my.cnf the settings your app is changing then it will not go into reserved connection.

**Comment by jakon89** [comment]
@harshit-gangal that sounds good! Do you know any easy way to know what settings are causing the connection to become reserved? For now, I am taking tcpdump between app and vtgate and trying to guess but maybe there is a better way.

**Comment by harshit-gangal** [comment]
you can check the mysql general log on the sequence database and check for the set statement that is getting executed.

**Comment by jakon89** [comment]
Thx @harshit-gangal
It looks that *some* parts of my app are doing bulk inserts:
```sql
set unique_checks = 0;
INSERT INTO tbl_name (a,b,c) VALUES(1,2,3), (4,5,6), (7,8,9);
set unique_checks = 1;
```
This is loading a huge amount of data and was optimized quite a while back. 

Now I am wondering about possible workarounds. AFAIK setting `unique_checks = 0;` on sequence vttablet won't work as *standard inserts with unique_checks = 1;* will be creating reserved conns. Not to mention that  `unique_checks = 0;`  isn't something I want to enable per server.

Any ideas? 🙏

**Comment by harshit-gangal** [comment]
If you are on 8.0, then on the PR https://github.com/vitessio/vitess/pull/9641 we changed the logic to avoid using reserved connection if it can be dealt with using SET_VAR. If you can run that version it might work for you.
