### ISSUE TITLE
Flaky tabletmanager tests

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9946]
### Overview of the Issue

![tm](https://user-images.githubusercontent.com/388311/159539465-176b8a0c-e570-49e2-88f6-3bab44abf727.png)

### Reproduction Steps

Seen in CI
https://app.launchableinc.com/organizations/vitess/workspaces/vitess-app/flaky-tests

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
GH Actions
```

**Comment by GuptaManan100** [comment]
I don't think we are tracking anything on this issue anymore. Should we close this?
