### ISSUE TITLE
Flaky TestUnShardedRecoveryAfterSharding

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9947]
### Overview of the Issue

Flaky test in CI from package `unshardedrecovery`

### Reproduction Steps

CI Build

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
GH Actions
```

**Comment by GuptaManan100** [comment]
This test doesn't appear to be flaky anymore on launchable. Should we close this issue?
