### ISSUE TITLE
ApplySchema -strategy "direct -allow-zero-in-date" silently drops DDL errors

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/vitess#9996]
When running `vtctlclient ApplySchema -skip_preflight -strategy "direct -allow-zero-in-date"`, and when -`sql` has an error, then the command does not report the error.

Specifically, we were looking at `create view problem_view as select * from no_such_table` where `no_such_table` does not exist. The view creation fails, but `vtctlclient ApplySchema` does not return an error.

The reason is with this code:

https://github.com/vitessio/vitess/blob/68cbda31c046866aadad094b3b47077d76fe01e6/go/vt/schemamanager/tablet_executor.go#L432-L435

Because we prepend a valid SQL (`SET sql_mode...`) before the DDL, we get the error code for _that_ instead of for the DDL, and the error code is empty.

I'm not sure what's the best way to go about this. I'm thinking adding a `bool allow_zero_in_date = 6;` to `message ExecuteFetchAsDbaRequest` in `proto`, and then add a `allowZeroInDate bool` argument in all `ExecuteFetchAsDba` function signatures. But it seems excessive measures for just this particular scenario.

any other ideas are welcome.

**Comment by rohit-nayak-ps** [comment]
What about adding "vitess" comments to the sql and parsing it in `ExecuteFetchAsDba`? This will make it more extensible, in case there are other flags that need similar handling in the future.

**Comment by shlomi-noach** [comment]
@rohit-nayak-ps that makes sense, good idea! While not all query types support comments, all DDLs do, so that should work.

**Comment by shlomi-noach** [comment]
OK this change was simple, PR to follow.

**Comment by shlomi-noach** [comment]
Addressed by #9998
